ruffle-rs/ruffle

core/src/avm2/globals/flash/text/engine/text_block.rs, core/src/display_object/edit_text.rs
TLF also seems to support device fonts, so I enabled that flag. (I am testing this with device font support)
=> avm2: Support more ElementFormat font options in TextBlock

Cargo.lock
Changes:
Updating git repository `https://github.com/gfx-rs/wgpu`
Updating crates.io index
Updating git repository `https://github.com/ruffle-rs/rust-flash-lso`
Updating git repository `https://github.com/ruffle-rs/jpegxr`
Updating git repository `https://github.com/ruffle-rs/nellymoser`
Updating git repository `https://github.com/kyren/gc-arena`
Updating git repository `https://github.com/ruffle-rs/h263-rs`
Updating git repository `https://github.com/ruffle-rs/nihav-vp6`
Updating crossbeam-channel v0.5.9 -> v0.5.10
Updating crossbeam-epoch v0.9.16 -> v0.9.17
Updating crossbeam-utils v0.8.17 -> v0.8.18
Updating event-listener v4.0.0 -> v4.0.1
Updating fdeflate v0.3.1 -> v0.3.2
Updating linkme v0.3.19 -> v0.3.20
Updating linkme-impl v0.3.19 -> v0.3.20
Updating mach2 v0.4.1 -> v0.4.2 …
=> chore: Run `cargo update` to bump patch versions in `Cargo.lock`

core/src/player.rs, web/packages/core/src/config.ts, web/packages/core/src/load-options.ts, web/src/lib.rs
Not super familiar with Rust, and I don't have a test for AIR. Does this look correct?
This addresses https://github.com/ruffle-rs/ruffle/pull/13077#issuecomment-1709249976 following #14166.
=> web: Add playerRuntime option to config for air or flashPlayer

core/src/avm2.rs, core/src/avm2/activation.rs
**Edit: Most of the changes described below have been abandoned in favor of https://github.com/ruffle-rs/ruffle/pull/14563**
Currently the very hot code in `do_next_opcode` is basically split into two parts:
- Reading/decoding the opcode via `Reader::read_op`
- Dispatching based on the decoded data
This doesn't seem to produce very good code. Most interpreters that I know fuse decoding and dispatching. In this proof of concept the compiler seems to generate jump tables for at least a subset of opcodes. 
I am not sure if I trust the numbers, but the time spent in a very tight loop like this seems to be reduced by 25%
```actionscript
var foo: int = 0xFFFFFFFF;
for (var i: int = 0; i < 100000; i++) {
for (var j: int = 8; j >= 0; j--) {
var bar: int = -(foo & 1);
foo = (foo >> 1) ^ …
```
=> avm2: Optimize the interpreter loop

core/src/avm2/activation.rs, swf/src/avm2/read.rs, swf/src/avm2/types.rs, swf/src/avm2/write.rs
This reduces the size of `Op` from 24 to 16 bytes, at the cost of `LookupSwitch` having a bit more overhead. This is useful for #14563, because it would reduce the total bytecode size by 1/3.
=> avm2: Reduce the size of Op on 64bit

.cargo/config.toml, Cargo.toml, core/Cargo.toml, core/build_playerglobal/Cargo.toml, core/macros/Cargo.toml, desktop/Cargo.toml, exporter/Cargo.toml, render/Cargo.toml, render/canvas/Cargo.toml, render/naga-agal/Cargo.toml, render/naga-pixelbender/Cargo.toml, render/webgl/Cargo.toml, render/wgpu/Cargo.toml, ruffle_gc_arena/Cargo.toml, scanner/Cargo.toml, swf/Cargo.toml, tests/Cargo.toml, tests/framework/Cargo.toml, tests/input-format/Cargo.toml, tests/mocket/Cargo.toml, tests/socket-format/Cargo.toml, video/Cargo.toml, video/software/Cargo.toml, web/Cargo.toml, web/common/Cargo.toml, web/packages/extension/safari/Cargo.toml, wstr/Cargo.toml
This got stabilized in Rust 1.74:
https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#lints
https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-lints-section
https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#the-lints-table
https://github.com/rust-lang/cargo/issues/5034 is done by https://github.com/rust-lang/cargo/issues/12115, and https://github.com/rust-lang/cargo/pull/12148 is also merged.
=> chore: Move lint configuration from `.cargo/config.toml` to `Cargo.toml`

.github/workflows/test_rust.yml, tests/tests/swfs/avm2/pixelbender_effect_BlurredFocus/test.toml, tests/tests/swfs/avm2/pixelbender_effect_glassDisplace_shaderfilter/test.toml, tests/tests/swfs/avm2/pixelbender_effect_smudge/test.toml, tests/tests/swfs/avm2/pixelbender_effect_tintype/test.toml, tests/tests/swfs/avm2/pixelbender_effect_twirl/test.toml, tests/tests/swfs/avm2/pixelbender_images/test.toml, tests/tests/swfs/avm2/pixelbender_shaderdata/test.toml, tests/tests/swfs/avm2/stage3d_agal_cross_product/test.toml, tests/tests/swfs/avm2/stage3d_bitmap/test.toml, tests/tests/swfs/avm2/stage3d_blend/test.toml, tests/tests/swfs/avm2/stage3d_errors/test.toml, tests/tests/swfs/avm2/stage3d_errors_swf_29/test.toml, tests/tests/swfs/avm2/stage3d_fractal/test.toml, tests/tests/swfs/avm2/stage3d_rotating_cube/test.toml, tests/tests/swfs/avm2/stage3d_sampler/test.toml, tests/tests/swfs/avm2/stage3d_texture/test.toml, tests/tests/swfs/avm2/stage3d_texture_bytearray/test.toml, tests/tests/swfs/avm2/stage3d_texture_bytearray_compressed_alpha/test.toml, tests/tests/swfs/avm2/stage3d_texture_bytearray_compressed_raw_alpha/test.toml, tests/tests/swfs/avm2/stage3d_triangle/test.toml, tests/tests/swfs/avm2/stage3d_triangle_bytes4/test.toml, tests/tests/swfs/avm2/stage3d_triangle_float1/test.toml, tests/tests/swfs/avm2/stage3d_triangle_index_upload/test.toml, tests/tests/swfs/stage3d/sampler_odd_size/test.toml, tests/tests/swfs/stage3d/scissor_rectangle/test.toml, tests/tests/swfs/stage3d/scissor_rectangle_invalid/test.toml, tests/tests/swfs/visual/shumway_acid_tests/acid_large/test.toml
This is supposed to avoid https://github.com/gfx-rs/wgpu/issues/4885, as `nextest` runs every test in its own process.
Supposedly for the same reason, WARP is a lot less delicate, therefore #14393 is mostly reverted.
There still seem to be some sort of random driver [de]initialization issue on Ubuntu, but with allowing a few retries, this should hopefully not actually cause failures often. EDIT: Allowed retrying test because of this.
It's also nicer to debug failures, because it's always obvious exactly which test case failed.
Run on 4 threads at once, to overlap CPU-bound and IO-bound work.
I have considered adding a file in `.config` instead of the 3-4 command line arguments, but I think this is still fine as is.
=> ci: Switch to `cargo-nextest` for running Rust tests

web/packages/extension/src/content.ts, web/packages/extension/src/ruffle.ts
=> extension: Bail if postMessage event has no data

core/src/html/layout.rs
=> core: Don't treat known aliases as default fonts before trying to load them as device fonts

core/src/font.rs, core/src/html/layout.rs, core/src/player.rs, desktop/src/player.rs, web/packages/core/src/load-options.ts
This makes any movie using Japanese text start rendering, pretty much!
It's not flawless and we will likely adjust the matched fonts in the future.
=> core: Support Japanese font defaults

core/src/html/layout.rs
Seems like I was wrong and @Dinnerbone was right.
=> core: Use sans instead of serif when missing a font

core/src/font.rs
Very likely fixes #14695. I don't have the Verdana font, but it fixes DejaVu Sans. I somehow missed this instance of pixels vs. points, most likely because none of the fonts I tried actually used this type of kerning.
=> core: Font kerning is in points not pixels

web/packages/core/src/ruffle-player.ts
Flash Player seems to treat `base="."` (in object and embed tags) as a magic value meaning 'the main SWF's directory'. As far as I can tell, it treats every other base value as relative to the page URL, not the SWF URL. Since this behavior is confusing and undocumented, I implemented it only for Ruffle's polyfill logic, not its JS API.
This fixes the content on http://mywww.caihongtang.com/games/16334.htm . With this PR, it successfully loads `minguowangshi-data.swf`, as it does with the Flash plugin. (This problem was originally reported by a user on Discord)
=> web: Add special case for base="."

core/src/avm2/activation.rs, core/src/avm2/domain.rs, core/src/avm2/object/class_object.rs, core/src/avm2/property.rs, core/src/avm2/value.rs
Since it was always the `Ok` variant anyway, just sometimes with a `None` in it, not a `Some`.
Noticed by @Lord-McSweeney [on Discord](https://discord.com/channels/610531541889581066/1018988594259574845/1193255188300038245).
=> avm2: Cleanup: Make `Domain::get_class` not return a `Result`

core/src/avm2/globals/flash/display/DisplayObjectContainer.as
Reference: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/DisplayObjectContainer.html
I only found these two methods with a version higher than FP 9.
API versions determined according to `avm2/globals/README.md`.
This is supposed to fix #14704 according to @Lord-McSweeney (https://github.com/ruffle-rs/ruffle/issues/14704#issuecomment-1888113744), but haven't tested it, as I don't know how.
=> avm2: Add API versioning to DisplayObjectContainer

Cargo.lock
This fixes a crash when loading an ATF 'compressed alpha' texture under wasm. The rust-side jpegxr wrapper was calling C functions that trigger a WASM ABI bug.
See https://github.com/ruffle-rs/jpegxr/commit/d49988f40f220e3e9c90d9f3df1d4e3bc41f6ce2 for more details
=> Bump jpegxr dependency for wasm ABI bugfix

deny.toml
Deny unknown crate registry and git repository sources, plus disallow "kyren" as GitHub organization as crate source, since we have switched to the published `gc-arena` 0.5.0 release in #14616.
=> chore: Deny unknown crate sources

.github/workflows/track_merged_prs.yml
Tested in a private repo and works!
https://github.com/orgs/ruffle-rs/projects/7
> All merged PRs to Ruffle will automatically land in the No Category column of this project.
> 
> Maintainers should occasionally go through and roughly categorize them according to the PRs topic.
> 
> If the PR isn't worth calling out because (it's meta, dependencies, or such a small change it has little to no impact on actual content), move it to N/A.
> If there's no matching category and it's a minor change, put it in the Minor column.
> If there's no matching category and it's a major change that we definitely want to call out, make a new category for it.
> If the Minor column has a bunch of similar topics already, make a new category for those and move them out.
=> ci: Track merged PRs in a project

core/src/avm2/globals/flash/sensors/Accelerometer.as, core/src/avm2/globals/globals.as
This fixes Asterius from showing "undefined" as intro text (Fixes #12463).
=> avm2: Stub Accelerometer.isSupported

.github/workflows/release_nightly.yml, .github/workflows/test_web.yml, web/README.md, web/docker/Dockerfile
Fixup for https://github.com/ruffle-rs/ruffle/pull/14754.
=> chore: Update wasm-bindgen version references to 0.2.90

Cargo.lock, core/Cargo.toml, core/src/avm2/value.rs
With more than 15 digits, avmplus uses **BigInteger** arithmetic to avoid rounding errors (fix #14426). https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/MathUtils.cpp#L1359-L1379
=> avm2: Fix multiply with overflow in `string_to_f64`

web/packages/extension/src/utils.ts
It appears that the promise in the following code was never fulfilled, so `window.close()` was never called:
https://github.com/ruffle-rs/ruffle/blob/f0ed5c7211c22eda87425456e04e4d665068fa21/web/packages/extension/src/popup.ts#L176-L179
The same issue also occurred in Chrome, but it wasn't noticeable as this browser seems to close the popup by itself after calling `chrome.tabs.create`.
=> extension: Close `popup.html` when clicking "Open SWF Player" in Firefox

core/src/backend/ui.rs, core/src/loader.rs, desktop/src/backends/ui.rs, tests/framework/src/backends/ui.rs, web/packages/core/src/ruffle-player.ts, web/packages/core/texts/en-US/messages.ftl, web/src/lib.rs, web/src/ui.rs
Note: The error when loading a page which is not an SWF is the same as the error when loading an SWF that does not exist for the purpose of code simplicity. This can be changed if desired.
=> web: Properly panic when loading invalid SWF files (fix #14665)

desktop/src/app.rs
Fix a bug introduced by f65060e8 (#14703). The text input event was triggered two times: at key press and release. This patch makes sure that text input is triggered only on key press.
=> desktop: Fix doubling inputted characters

core/src/player.rs
After https://github.com/ruffle-rs/ruffle/pull/14671, there's no `Player::set_root_movie`, which I used to use in the Android app.
The way to go now is through `Player::mutate_with_update_context`, but that is only available within the same crate. Let's change that.
=> core: Make `Player::mutate_with_update_context` public

Cargo.lock, tests/Cargo.toml, tests/framework/Cargo.toml, tests/framework/src/lib.rs, tests/framework/src/test.rs, tests/tests/external_interface/tests.rs, tests/tests/regression_tests.rs, tests/tests/shared_object/mod.rs
It's the responsibility of the caller to do it how they want
=> tests: Don't set logger in test framework

core/src/display_object/avm2_button.rs
=> core: Invalidate cached bitmap on state change in AVM2Button

swf/src/types/fixed.rs
This makes the debug output more readable, e.g. in the debug UI filter's list.
Before:
After:
=> swf: Show scaled value in `swf::FixedN`'s `Debug` implementations

desktop/src/player.rs
The default device font name for Japanese was incorrect and has been corrected.
=> desktop: Change the default Japanese fonts

render/wgpu/src/context3d/mod.rs, render/wgpu/src/surface.rs, render/wgpu/src/utils.rs
This rounds the requested sample count down to a value that's supported by the device.
=> Use supported_sample_count for Context3D sample count

Cargo.lock, Cargo.toml, deny.toml, desktop/src/gui/controller.rs, desktop/src/util.rs, render/naga-agal/Cargo.toml, render/naga-agal/src/builder.rs, render/naga-agal/tests/snapshots/wgsl__complex_fractal.snap, render/naga-agal/tests/snapshots/wgsl__complex_raytrace-2.snap, render/naga-agal/tests/snapshots/wgsl__misc_opcodes-2.snap, render/naga-agal/tests/snapshots/wgsl__misc_opcodes.snap, render/naga-agal/tests/snapshots/wgsl__shaders.snap, render/naga-pixelbender/src/lib.rs, render/wgpu/Cargo.toml, render/wgpu/src/backend.rs, render/wgpu/src/clap.rs, render/wgpu/src/context3d/mod.rs, render/wgpu/src/mesh.rs, render/wgpu/src/target.rs, render/wgpu/src/utils.rs, tests/tests/swfs/avm2/bitmapdata_applyfilter_colormatrix/test.toml, tests/tests/swfs/avm2/netstream_seek_flv/test.toml, web/Cargo.toml, web/src/lib.rs
=> wgpu: Update wgpu and naga to 0.19

Cargo.lock, Cargo.toml, deny.toml
This now includes https://github.com/gfx-rs/wgpu/pull/5091.
=> chore: Switch to wgpu 0.19.1 from git

core/src/avm2/globals/Error.as, core/src/avm2/object/error_object.rs, tests/tests/swfs/from_avmplus/ecma3/ErrorObject/e15_11_2_1/test.toml, tests/tests/swfs/from_avmplus/ecma3/ObjectObjects/class_003/test.toml, tests/tests/swfs/from_avmplus/ecma3/ObjectObjects/regress_72773_rt/test.toml
And remove `ErrorObject::to_string` implementation. This fixes a few avmplus tests.
=> avm2: Implement `Error.prototype.toString`

core/src/avm2/globals/flash/system/capabilities.rs
See: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/Capabilities.html#playerType
=> avm2: flash.system.Capabilities#playerType should return "Desktop" when the current runtime is AIR runtime(unless the swf is loaded by an HTML page)

core/src/avm2.rs, core/src/avm2/domain.rs, core/src/debug_ui.rs, core/src/debug_ui/domain.rs, core/src/debug_ui/handle.rs, desktop/assets/texts/en-US/main_menu.ftl, desktop/src/gui.rs
This opens a searchable list (similar to what we have for display objects), which shows a tree of Domains and their associated classes.
Currently, clicking on the domain/class buttons doesn't do anything. In a follow-up, I'm planning to add additional windows to display information about a class.
=> debug_ui: Add 'Show Domains' menu to view domains and classes

core/src/avm2/globals/flash/desktop/ClipboardFormats.as, core/src/avm2/globals/flash/events/ActivityEvent.as, core/src/avm2/globals/flash/events/IOErrorEvent.as, core/src/avm2/globals/flash/events/StageVideoEvent.as, core/src/avm2/globals/flash/ui/GameInputDevice.as, core/src/avm2/globals/flash/ui/KeyLocation.as
Browsing https://ruffle.rs/compatibility/avm2, these stood out as random missing pieces.
Easy wins for our API percentage.
_Goodhart's law has not been broken during the making of this PR._
=> avm2: Add a bunch more constants

Cargo.lock, core/src/avm1/globals/netstream.rs, core/src/backend/navigator.rs, core/src/loader.rs, core/src/net_connection.rs, core/src/streams.rs, desktop/src/backends/navigator.rs, tests/framework/src/backends/navigator.rs, web/Cargo.toml, web/src/navigator.rs
Adds the ability to stream fetched data instead of an all-at-once download. Also adds the ability to get estimated download size. Most of `NetStream` was already built in anticipation of streaming download, so we're applying these new backend capabilities to it first.
This also reserves buffer capacity and sets `bytesTotal` based on the estimated file size length.
This does *not* add SWF progressive download capability. While we already have well tested implementations of *simulated* streaming download (specifically to hide shape processing latency), we need streaming-aware zlib/LZMA decompressors before we can actually download SWFs in chunks.
~~This PR is a draft because I haven't actually tested it in a browser yet.~~ I have been able to successfully do streaming playback on at least …
=> Progressive download of video files

core/src/display_object/stage.rs, core/src/player.rs, web/packages/core/src/config.ts, web/packages/core/src/load-options.ts, web/packages/core/src/ruffle-player.ts, web/src/lib.rs
Note 1:
I realized on `fullscreenchange`, `this.instance?.set_fullscreen` is called (this was to fix escape key behavior IIRC):
https://github.com/ruffle-rs/ruffle/blob/e0f5b8906dc1893416d9d836fd4458c8acc2817b/web/packages/core/src/ruffle-player.ts#L1140-L1142
That same function got called by clicking the context menu item "Enter/Exit Fullscreen", but with my change in `set_display_state` that Rust function doesn't actually full screen the content when `allowFullScreen` is false. So I switched "Enter/Exit Fullscreen" to use the pure JavaScript `setFullscreen` function, which will subsequently trigger a `fullscreenchange` event to call `this.instance?.set_fullscreen` to do the Rust portion of the logic. That way full-screening the content with the context menu always works, but only …
=> web: Add allowFullScreen embed/object option (part of #4258)

tests/framework/src/backends/log.rs, tests/framework/src/environment.rs, tests/framework/src/options.rs, tests/framework/src/runner.rs, tests/framework/src/test.rs, tests/tests/environment.rs, tests/tests/external_interface/tests.rs, tests/tests/regression_tests.rs, tests/tests/shared_object/mod.rs
Commit log explains the changes out, the full diff is a bit messy looking I guess :D
With these changes, tests run absolutely fine (though slow) on web. That's in a pending PR though as I'm still working on the actual web UI.
Main changes are:
- Testing is no longer just "run test", now it creates a runner and tick/test/tick/test until finished. This way, wasm can run tests that need async.
- Slightly less panic happy (panics on web are sad)
- Only one renderer per environment; the application running the tests can just run them again with a new environment
=> tests: More improvements to make them runnable on web

desktop/src/gui/controller.rs
This is mainly useful to allow forcing usage of Vulkan on non-compliant drivers, such as Mesa's driver for Intel Haswell IGPUs, using the `WGPU_ALLOW_UNDERLYING_NONCOMPLIANT_ADAPTER` environment variable. Currently, wgpu will always reject adapters with non-compliant drivers, even though they will often still work fine.
=> desktop: Allow specifying WGPU instance flags from environment

web/src/ui.rs
Better to not open a save dialog instead of crashing, while we look into fixing #14949.
=> web: Temporary disable display_file_save_dialog to prevent panics

desktop/src/app.rs, desktop/src/gui.rs, desktop/src/gui/context_menu.rs
Previous approach was to immediately spawn a blank panel with a context menu attached, so egui would then see the right click event too and do its thing.
This was too unreliable, so now we just have our own context menu.
=> desktop: Fix context menu

core/src/avm2/object/script_object.rs
Very small thing I noticed. Unlikely to ever be in a hot path; if anything, we currently mostly call it in during builtin classes' initialization :)
=> avm2: Avoid double lookup in setPropertyIsEnumerable

core/src/avm2/globals/flash/system/Capabilities.as, core/src/avm2/globals/flash/system/capabilities.rs
`flash.system.Capabilities.manufacturer` now reports Adobe Windows and `flash.system.Capabilities.os` Windows 8
=> Report OS as Windows instead of Linux for now

core/src/avm2/globals/string.rs, core/src/player.rs, core/src/string/avm_string.rs, core/src/string/interner.rs, core/src/string/repr.rs
This plugs in basic support for dependent strings, which are roughly similar to dependent strings in avmplus or Firefox.
This way, calling `LONG_STRING.substr(1)` is O(1) instead of O(n). And this way, scripts like
```
while(data.length > 0)
{
char = data.charAt(0);
data = data.substr(1);
// ...code...
```
are no longer quadratic in space and time.
MVP scope:
- `substring()`, `substr()`, `slice()`
- `charAt()`, `split("")`
- cached, interned `""` and ASCII chars
- `a.substr().substr().substr()` points at the original parent string - no chain of depenednts
Out of MVP scope:
- other AVM2 APIs
- AVM1 APIs
- substring of a static string should be a static string (it's obvious on how to implement, but not obvious on how to nicely structure the code around it, it's already stretched across many …
=> avm2: Support dependent strings, small string optimizations

.github/workflows/release_nightly.yml
#15031 broke this night's release workflow run: https://github.com/ruffle-rs/ruffle/actions/runs/7719064767/job/21041617006
This is because `actions/upload-artifact@v4` no longer allows uploading the same artifact twice: https://github.com/actions/upload-artifact/issues/478
Hopefully this will fix it.
I see no reason why we would need to upload the safari extension from the web demo builder job as well (it has nothing to do with it), when we are already uploading it from the regular web builder job. (Because the universal macOS binary needs it for some reason...?)
=> ci: Don't upload the Safari extension as artifact when building the web demo

core/src/avm1/globals/math.rs
Since we were a bit eager to get BTD5 solved, we merged the Math.random() AVMPLUS implementation to AVM2 ahead of considering including it in AVM1. This simply copies that code (and assumes we can apply the same test).
=> Matching AVM1 to AVM2 for the sake of consistency

Cargo.lock, Cargo.toml, core/src/avm2.rs, core/src/avm2/domain.rs, core/src/avm2/function.rs, core/src/avm2/namespace.rs, core/src/avm2/object/script_object.rs, core/src/avm2/specification.rs, core/src/player.rs, core/src/stub.rs, exporter/Cargo.toml, stub-report/Cargo.toml, stub-report/src/main.rs
This brings Dinnerbone's implementation.json generation into master. You can now run `cargo run -p stub-report implementation.json` to write the implementation report to a file named `implementation.json`.
In a follow-up PR, I'm going to add a Github Action workflow to automatically run this and update the website when it changes.
=> avm2: Integrate avm2 implementation.json generation into new `stub-report` crate

Cargo.lock, core/Cargo.toml, core/src/avm2/regexp.rs, core/src/display_object/edit_text.rs, core/src/events.rs, desktop/src/util.rs, web/src/lib.rs, wstr/src/common.rs, wstr/src/ops.rs, wstr/src/tests.rs
This PR implements the following controls:
* <kbd>Ctrl</kbd> + <kbd>Delete</kbd> &mdash; delete a word to the right,
* <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> &mdash; delete a word to the left,
* <kbd>Ctrl</kbd> + <kbd>→</kbd> &mdash; move a word to the right,
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>→</kbd> &mdash; select a word to the right,
* <kbd>Ctrl</kbd> + <kbd>←</kbd> &mdash; move a word to the left,
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>←</kbd> &mdash; select a word to the left,
* <kbd>Home</kbd> &mdash; move left to the beginning of the line,
* <kbd>Shift</kbd> + <kbd>Home</kbd> &mdash; select left till the beginning of the line,
* <kbd>Ctrl</kbd> + <kbd>Home</kbd> &mdash; move left to the beginning of the document,
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Home</kbd> …
=> text: Advanced horizontal text controls for EditText

core/src/avm2/namespace.rs
Some obfuscators use random mark on all the object. Ignore them as avmplus does otherwise some things won't run.
Example #15006
=> Ignore bad version mark (sometimes used by obfuscators) (close #15006)

.github/workflows/release_nightly.yml
This should reduce the unzipped(?) size from ~216 MB down to ~15MB, hopefully allowing the submission of it to AMO to not fail.
Also leave the `*` wildcard expansion up to `zip` instead of doing it in the invoking shell.
Plus a (now) much needed line wrap for bonus.
=> github: Also exclude `.git` and `tests/tests/swfs` from `reproducible-source.zip`

web/packages/extension/tools/sign_xpi.js
This was a problem in the last review. I am not super familiar with docker, but I assume this 
```bash
sudo docker cp $(sudo docker create ruffle-web-docker:latest):/ruffle/web/packages web/docker/docker_builds/packages
```
would be the right way to use the following with sudo:
```bash
docker cp $(docker create ruffle-web-docker:latest):/ruffle/web/packages web/docker/docker_builds/packages
```
=> web: Explicit instruction how to use sudo for docker building

core/src/avm2/class.rs, core/src/avm2/object/class_object.rs, core/src/debug_ui/domain.rs
This re-uses our existing infrastructure for displaying AVM2 Class objector. One minor limitation of this approach is the inability to view a `Class` that hasn't yet had its `ClassObject` created - however, this should be rare in practice.
=> debug_ui: Show ClassObject when clicking on domain class

.github/workflows/release_nightly.yml
This regressed in #15094.
I wasn't paying enough attention, and/or haven't verified the change myself, and/or hoped that there is a semver-like fuzzy matching of these versions.
Looks like there isn't.
=> github: Use full version for the `mnao305/chrome-extension-upload` action

.github/workflows/release_nightly.yml, stub-report/generate-report.sh
We upload it to the release as a file named 'avm2_report.json' The website will use this to automatically display the latest report
=> github: Generate AVM2 report as part of nightly release

web/package-lock.json, web/package.json
It was only needed to be 7 back in 2022, and the bot just kept updating it. We're long past 7 now.
=> web: Remove npm version requirement

Cargo.lock, Cargo.toml, core/Cargo.toml, deny.toml, desktop/Cargo.toml, desktop/src/gui/controller.rs
The update was completely painless, and I haven't noticed any issues either.
For the changelog, see: https://github.com/emilk/egui/releases/tag/0.26.0
=> desktop: Update egui to 0.26.0

core/src/avm2/object.rs
I noticed this while reviewing #15119. Need to test this though.
=>  avm2: has_property should do proto.has_property instead of has_own_property

core/src/avm2/globals/flash/sampler.as
Flash output:
```
clearSamples() undefined
getGetterInvocationCount(obj, qname) -1
getInvocationCount(obj, qname) -1
getLexicalScopes(function(){}) null
getMasterString("") null
getMemberNames(obj) undefined
getSampleCount() 0
getSamples() undefined
getSavedThis(function(){}) undefined
getSetterInvocationCount(obj, qname) -1
getSize(obj) 112
isGetterSetter(obj, qname) false
pauseSampling() undefined
sampleInternalAllocs(false) undefined
setSamplerCallback(function(){}) undefined
stopSampling() undefined
startSampling() undefined
```
=> avm2: Stub all flash.sampler methods

.github/workflows/test_web.yml
No change in functionality intended, only a little cleanup.
=> ci: Remove Rust version from the web CI matrix - it was always stable

.github/workflows/test_rust.yml
Two failures:
- mesa-vulkan-driver just updated from 23.0.4 to 23.2.1, which brought in a new bug that fails any test with a blur filter. Update to a newer one from PPA (reverts #8708) to see if it helps.
- Don't upload artifacts with the same name, overwriting them
=> ci: Fix failing visual tests

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml
Supersedes https://github.com/ruffle-rs/ruffle/pull/15198.
For changelog, see:
- https://github.com/emilk/egui/releases/tag/0.26.1
- https://github.com/emilk/egui/releases/tag/0.26.2
=> desktop: chore: Update `egui` to 0.26.2

.github/workflows/release_nightly.yml, .github/workflows/test_web.yml, Cargo.lock, render/Cargo.toml, render/canvas/Cargo.toml, render/webgl/Cargo.toml, web/Cargo.toml, web/README.md, web/common/Cargo.toml, web/docker/Dockerfile
Supersedes https://github.com/ruffle-rs/ruffle/pull/15195, as we also need to match the `wasm-bindgen-cli` version exactly in a few more places.
=> web: chore: Bump wasm-bindgen to 0.2.91

web/packages/core/tools/set_version.js
I don't know where/when this broke, but we started reading the version seal from the wrong place - making it never used.
This is one small step towards getting reproducible builds again.
=> web: Fix version seal path

core/src/external.rs
I only tested it on
```
document.querySelector('ruffle-player').purchaseItem({
itemId: 123,
itemHash: "hash"
});
```
which seemed to deserialize correctly. Should be enough to fix https://github.com/ruffle-rs/ruffle/issues/15221 (but note that I didn't directly test that either).
The `unwrap()`s are unfortunate, as we don't return Result from there; but these spots also aren't likely to throw any AS exceptions. It's up to reviewers :D whether this should be better handled.
=> avm2: Implement JS->AS3 Object deserialization

Cargo.lock, core/Cargo.toml, core/src/avm2/amf.rs, tests/tests/swfs/from_shumway/encoding_1/test.toml
Depends on https://github.com/ruffle-rs/rust-flash-lso/pull/55
=> avm2: Always serialize as ECMAArray, which produces an AMF0 MixedArray

.github/workflows/release_nightly.yml
https://github.com/josStorer/get-current-time/releases/tag/v2.1.2
=> ci: Update get-current-time to v2.1.2 which uses Node 20

web/packages/extension/webpack.config.js
Instead of [big random hash] it'll be the actual name of the wasm file.
This way `player.js` will not make a diff because the filename changed, and it'll also be clear which wasm file is which
=> web: Don't generate random name of wasm files in extension

.github/workflows/test_extension_dockerfile.yml
Currently fails due to the differences, as expected
=> ci: Extend the docker test to include diffing against normal builds

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, web/docker/Dockerfile, web/package.json, web/packages/core/tools/build_wasm.js, web/packages/extension/tools/sign_xpi.js
It's a solution to the reproducible extension issue.
Unexpected, but allowed. We'll include the wasm in the source we send them, and then the JS will match.
The final wasm files inside the build they make will **not** match, until https://github.com/rustwasm/wasm-bindgen/pull/3851 - we're told this is okay though, so I've just removed the wasm-opt step too for brevity.
=> web: Include wasm file in docker builds as Mozilla say this is okay

desktop/src/backends/navigator.rs
All this bureaucracy for swapping two letters in a comment... :)
=> nit: desktop/navigator: Fix a typo in a comment: ownerhsip -> ownership

.github/workflows/test_rust.yml, Cargo.toml
This is a continuation of #15241, which I somehow messed up (the source branch was in this repo, not in my fork - oops, sorry, branch deleted).
=> ci: Add a dedicated Cargo profile, test with that

Cargo.lock, desktop/Cargo.toml
See the changes here: https://github.com/rust-windowing/winit/releases/tag/v0.29.11
Plus the usual bumps of all (non-problematic, unrelated) deps in Cargo.lock.
=> desktop: chore: Update `winit` to `0.29.11`

.cargo/config.toml, .github/workflows/test_rust.yml, Cargo.toml
With these tweaks, I clocked in a sub 13 minute run on Windows, in an ideal scenario: https://github.com/torokati44/ruffle/actions/runs/8063891683
For reference, currently we are in the 15..17 minute (or 13..20 including outliers) range.
While I discarded them earlier, this does include the changes in both https://github.com/ruffle-rs/ruffle/pull/15324 and https://github.com/ruffle-rs/ruffle/pull/15325.
And admittedly, a few more random changes, and I regretfully admit that I can't empirically show exactly which ones help how much.
But overall, none of them should be too risky, while all of them have a chance to help _somewhat_.
=> ci: Try to speed up CI runs on Windows

core/src/avm1/globals/bitmap_data.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm1/globals/sound.rs, core/src/avm2/error.rs, core/src/avm2/globals/flash/display/bitmap.rs, core/src/avm2/globals/flash/display/bitmap_data.rs, core/src/character.rs, core/src/debug_ui/movie.rs, core/src/display_object.rs, core/src/display_object/bitmap.rs, core/src/display_object/movie_clip.rs, core/src/library.rs, render/src/utils.rs, swf/src/read.rs, swf/src/test_data.rs, swf/src/types.rs, swf/src/write.rs
We hit a pathological case in House
(https://github.com/ruffle-rs/ruffle/issues/15154), where eagerly decoding bitmaps during preloading results in over 10GB of ram being used.
With this PR, we store the compressed bitmap, and only decode it each time we instantiate it. In order to support bitmap fills, we store the decoded width/height and a lazily-initialized GPU handle in `Character::Bitmap`
=> core: Implement lazy decoding of bitmaps

Cargo.lock, core/src/backend/navigator.rs, core/src/socket.rs, desktop/Cargo.toml, desktop/src/backends/navigator.rs, desktop/src/executor.rs, desktop/src/player.rs, tests/framework/src/backends/navigator.rs, web/src/navigator.rs
This patch makes sure that any pending data is sent before the socket closes. Without this fix Ruffle ignored the data sent right before calling `socket.close`.
=> desktop: Add socket tests and fix flush on close

.github/workflows/release_nightly.yml, .github/workflows/test_rust.yml, Cargo.lock, README.md, core/src/events.rs, core/src/player.rs, desktop/Cargo.toml, desktop/src/app.rs, desktop/src/cli.rs, desktop/src/player.rs, desktop/src/util.rs
This is mostly a proof-of-concept, because I totally fail at playing Super Mario without a gamepad. We probably need to do some kind of per-game/swf remapping logic to actually make this useful, considering how peculiar some of those keybinds are.
=> desktop: Introduce generic gamepad remapping support

web/packages/core/src/load-ruffle.ts
Palemoon "added an initial implementation of the ReadableStreams API, improving web compatibility with sites that apparently use this API in utilitarian fashion," according to http://www.palemoon.org/releasenotes.shtml#v32.5.0.
Unfortunately, that decreased Ruffle's compatibility with Pale Moon, as we rely on the existence of the [ReadableStreamDefaultController](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultController) when ReadableStream is defined. Therefore, change the compatibility check for ReadableStream to check for the existence of ReadableStreamDefaultController specifically.
=> web: Don't panic on browsers without ReadableStreamDefaultController

Cargo.lock, core/Cargo.toml
This brings in https://github.com/ruffle-rs/jpegxr/pull/1 and https://github.com/ruffle-rs/nellymoser/pull/5, thereby dropping the `bindgen` `0.68.1` and `bitstream-io` `1.10.0` duplicate dependencies, plus `peeking_take_while` entirely.
=> chore: Bump `jpegxr` and `nellymoser-rs` git references

Cargo.lock, Cargo.toml
Basically https://github.com/ruffle-rs/ruffle/pull/15372, but newer!
=> chore: Bump `wgpu` to `0.19.3`, `naga` to `0.19.2`

.cargo/config.toml, web/packages/core/tools/build_wasm.js
At least `wgpu` no longer requires this as of `0.19.3` (even for WebGPU).
Let's see whether everything else keeps working without it...
Referencing: https://github.com/ruffle-rs/ruffle/pull/5250
=> web: No longer set the `web_sys_unstable_apis` config variable

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/backend/audio.rs, core/src/backend/audio/mixer.rs, core/src/loader.rs, core/src/local_connection.rs, core/src/net_connection.rs, core/src/socket.rs, desktop/Cargo.toml, desktop/src/backends/navigator.rs, desktop/src/executor.rs, video/Cargo.toml, video/software/Cargo.toml, video/software/src/backend.rs, video/src/lib.rs, video/src/null.rs, web/Cargo.toml, web/src/lib.rs
Because `generational-arena` is unmaintained, and `slotmap` is the recommended alternative.
Most of it was a trivial search-and-replace, except for:
- That `.rev()` from `LoadManager` is gone, because this iterator type does not support it.
- Note that iteration order was undefined before, and is undefined now. Therefore, we shouldn't have been relying on this already.
- Replaced by a clumsy hand-cranked reversing solution, but it should behave the same (undefined, but accidentally usually correct) way.
- `loader.rs` has sometimes used `Index` instead of the `Handle` type it defines, in its API.
- We should probably also rename that to match the convention of the rest of the handle types.
- The dummy handle in the socket tests was replaced by the default, I hope that's fine, @kjarosh.
In …
=> chore: Replace `generational-arena` with `slotmap`

Cargo.lock, desktop/Cargo.toml, desktop/src/gui.rs
This is a fixup for https://github.com/ruffle-rs/ruffle/pull/15280 which forgot to update it in `desktop`.
=> chore: Deduplicate the `fluent-templates` dependency

core/src/avm2/activation.rs
Noticed when profiling a random SWF from discord. Previously we constructed a `TypeError` each time these opcodes were executed, and since the construction involves a full AS bytecode function invocation, this was super heavy for a single op.
=> avm2: Only construct type_error on error in astype, instanceof

LICENSE.md, core/src/backend/audio.rs, core/src/backend/audio/mixer.rs, core/src/loader.rs, core/src/local_connection.rs, core/src/net_connection.rs, core/src/socket.rs, core/src/streams.rs, desktop/src/executor.rs, video/software/src/backend.rs, video/src/lib.rs, video/src/null.rs, web/LICENSE.md
Followup for https://github.com/ruffle-rs/ruffle/pull/15383.
I didn't dare touch `web/lib.rs`, because "scary JS interop", but that is the only `SlotMap` left with `DefaultKey`, so there probably won't be any confusion with that.
An ACK for the audio behavior change in `streams.rs` from @kmeisthax would be appreciated. I think this has been a bug so far, resulting from the exact same type of confusion that this PR is aiming to prevent in the future.
=> Define distinct key types for different kinds of slotmaps

Cargo.lock, core/Cargo.toml, deny.toml, desktop/Cargo.toml
=> chore: Switch `fluent-templates` back from `master` to `v0.9.0`

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, Cargo.lock, core/Cargo.toml, render/Cargo.toml, render/canvas/Cargo.toml, render/webgl/Cargo.toml, render/wgpu/Cargo.toml, web/Cargo.toml, web/README.md, web/common/Cargo.toml, web/docker/Dockerfile
This brings in https://github.com/rustwasm/wasm-bindgen/pull/3851, which will hopefully bring us closer to deterministic WASM modules for AMO.
It wasn't trivial: https://github.com/rustwasm/wasm-bindgen/pull/3870
=> chore: Update `wasm-bindgen` to `v0.2.92`

web/package-lock.json, web/package.json, web/packages/demo/package.json, web/packages/extension/package.json, web/packages/selfhosted/package.json
Same as https://github.com/ruffle-rs/ruffle/pull/15365, but excluding the `chai` and `chai-html` bumps.
=> chore(deps): update node.js dependencies

deny.toml
Makes CI check go green.
Reason is: https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v1.6.0
Explanation of changes:
- `all-features` got moved under `graph`: https://github.com/EmbarkStudios/cargo-deny/pull/605
- The Unicode 3.0 license is what superseded the previous DFS license: https://opensource.org/license/unicode-inc-license-agreement-data-files-and-software
- `licenses.unlicensed` and `licenses.deny` got deprecated, as `deny` is now the default policy: https://github.com/EmbarkStudios/cargo-deny/pull/606
- Updating to new config version: https://github.com/EmbarkStudios/cargo-deny/pull/611
=> chore: Update `cargo-deny` configuration

core/src/backend/audio.rs, core/src/context.rs, core/src/loader.rs, core/src/socket.rs, core/src/timer.rs, desktop/src/executor.rs, desktop/src/player.rs
Turns out that the comment from `set_root_movie` was right all along! `set_root_movie` should not be used when replacing the root movie, because it will leave out unclosed resources. This patch introduces `replace_root_movie`, which is dedicated to be used when replacing (instead of just setting) the root movie.
The best solution would be to use RAII, e.g. destroy and recreate the whole Player instance, but this patch is a first step towards proper resource control.
Additionally, I made WinitAsyncExecutor thread-safe and fixed potential deadlocks, because they started happening when sockets were closed during a task poll.
=> core: Close sockets and timers when replacing the root movie

render/wgpu/src/backend.rs
We're currently always requesting a maximum of 31 components, which is too low for some SWFs.
=> Request highest 'max_inter_stage_shader_components' supported by adapter

core/src/avm2/activation.rs, core/src/avm2/class.rs, core/src/avm2/error.rs, core/src/avm2/method.rs, core/src/avm2/op.rs, core/src/avm2/optimize.rs, core/src/avm2/verify.rs, swf/src/avm2/read.rs, swf/src/avm2/types.rs, swf/src/avm2/write.rs
Most common ops now no longer call `pool_maybe_uninitialized_multiname` or similar functions. As a result, `pool_maybe_uninitialized_multiname` practically disappears from profiles for most SWFs. 
TODO:
=> avm2: Lookup multinames in verifier and store them in `Op`

.github/workflows/release_nightly.yml
The zip goes from 837 MB to 27 MB
=> ci: Remove web/packages/*/dist and target from reproducable source zips

core/src/avm2/activation.rs, core/src/avm2/function.rs
The tldr is that it changes
```rs
fn from_method() -> Result<Activation> {
// initialize p1
let activation = ...;
// initialize p2
Ok(activation)
}
let activation = from_method()?;
```
to
```rs
fn from_nothing() -> Activation { ... }
fn init_from_method(&activation) -> Result<()> {
// initialize p1
// initialize p2
Ok(())
}
let activation = from_nothing();
activation.init_from_method()?;
```
Which helps the compiler avoid the work of making an Activation, stuffing it in `Ok()`, then pulling it out with `?`.
This might or might not help with stack use too, didn't check.
Also, it's super ugly design-wise; if you know any ways to make it more idiomatic without losing perf, please let me know :D
I saw 10-15% improvements in a microbenchmark repeatedly calling `function noop(){}`, and 4-5% on …
=> avm2: Reduce memcpy overhead in BytecodeMethod calls

Cargo.lock, desktop/Cargo.toml, desktop/src/player.rs
Fix so that desktop title properly renders non ASCII characters (the web player uses a static title so no fix is needed there)
issue: https://github.com/ruffle-rs/ruffle/issues/15454
=> desktop: Add URL decode to desktop window's title (close: #15454)

CONTRIBUTING.md, Cargo.lock, desktop/Cargo.toml, desktop/assets/texts/en-US/preferences_dialog.ftl, desktop/src/app.rs, desktop/src/gui/preferences_dialog.rs, desktop/src/log.rs, desktop/src/main.rs, desktop/src/preferences.rs, desktop/src/preferences/read.rs, desktop/src/preferences/write.rs
Ruffle now logs to `ruffle.log` by default, with the same filter as CLI (`RUST_LOG`). `RUST_LOG` now also defaults to `warn,ruffle=info,avm_trace=info` when not specified.
The preferences dialog also contains an option for whether to log to a single file (best for users) or multiple timestamped files (best for devs).
This does not add any way to change the filtering outside of environment variable because no consensus can be reached on discord on how to make this possible.
=> desktop: Log to disk

Cargo.lock, desktop/Cargo.toml
AFAICT `image` is only used by `desktop` to load the embedded Ruffle logo for the "About" dialog.
And since default features are already disabled everywhere else, look how many indirect dependencies we're dropping!
=> desktop: Turn off default features of `image`

.github/workflows/release_nightly.yml
This is a fixup for https://github.com/ruffle-rs/ruffle/pull/15518 and https://github.com/ruffle-rs/ruffle/pull/15066, because the reproducible source zip in https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-03-12 is still 800M+.
Turns out, `zip` doesn't exclude an entire folder unless the exclusion pattern ends with `/*` - looks like it does a sort of string matching, rather than the usual recursive FS globbing?
Also, `-x` takes a list of patterns, no need to specify it multiple times.
I've also added the `web/docker/docker_builds` folder to the exclusion list, just to be safe.
=> ci: Properly exclude large stuff from the reproducible FF extension source zip

desktop/src/backends/ui.rs
On Wayland ruffle uses https://github.com/YaLTeR/wl-clipboard-rs which only supports [`wlr-data-control-unstable-v1`](https://wayland.app/protocols/wlr-data-control-unstable-v1) which is not intended to be supported by all compositors.
There are options with better support https://wayland.app/protocols/primary-selection-unstable-v1 but until it's implemented in `wl-clipboard-rs` ruffle will crash for want of clipboard access.
For most platforms this MR wont effect anything. On platforms without clipboard support it'll quietly fail to set and get the clipboard.
Fixes https://github.com/ruffle-rs/ruffle/issues/15213
Mutter doesn't intend to support it: https://gitlab.gnome.org/GNOME/mutter/-/issues/524
=> desktop: Make clipboard support optional

core/src/avm2/globals/function.rs, core/src/avm2/object/function_object.rs, tests/tests/swfs/from_avmplus/ecma3/FunctionObjects/e15_3_4_2/test.toml, tests/tests/swfs/from_avmplus/ecma3/ObjectObjects/class_006/test.toml
Part of https://github.com/ruffle-rs/ruffle/issues/15474
=> avm2: Add Function.prototype.toString and toLocaleString 

core/src/avm2/globals/namespace.rs, core/src/avm2/object/namespace_object.rs, core/src/avm2/object/vector_object.rs
Turns out the Vector to_string function that I added (#15562) was just duplicating what the default implementation did. The Namespace one was just plain wrong.
Fixes #15474
=> avm2: Remove all to_string implementations except Object and Class.

core/src/display_object/edit_text.rs
This should optimize cases where there's a lot of text left to be scrolled under the textfield. The speedup can be extreme if there are hundreds of pointlessly-drawn lines.
(However, note that this doesn't help with the opposite case - when you scroll to the bottom, it'll still draw all the text :/  )
The perfect solution might be to implement all 4 types of culling (lines under/above* textfield/screen), but with all the transforms, height metrics etc etc this was the only one I could confidently implement - and even in this one I'm not convinced I didn't skip any edge cases.
(Note that due to how `scrollV` works, lines above the textfield could be skipped without even iterating over them. In fact... maybe FP (and us) could deduce in-bounds for each glyph, thus making us not require …
=> core: Cull text under textfield

Cargo.lock, core/Cargo.toml, desktop/Cargo.toml, exporter/Cargo.toml, exporter/src/main.rs, render/wgpu/Cargo.toml, tests/Cargo.toml, tests/framework/Cargo.toml, tests/framework/src/options.rs, tests/framework/src/runner.rs, tests/framework/src/util.rs
I hope some visual tests will fail on this, at least on Windows.
To be fixed by an alternative implementation based on https://github.com/jansol/texpresso, as recommended.
=> chore: Bump `image` to `v0.25`, without the `dxt` feature

Cargo.lock, render/Cargo.toml, video/software/Cargo.toml
This is just to bring in https://github.com/ruffle-rs/h263-rs/pull/52, dropping the duplicated `itertools` dependency.
=> chore: Bump `h263-rs` git refs

core/src/streams.rs
This fixed the playback of FLV videos for me on Linux.
Rationale:
Currently, `stream_time` is only advanced when there was at least one tag processed in a tick.
However, in certain conditions (high rendering FPS, low video FPS, large audio chunks), it's possible that no tick ever has a `dt` large enough to bridge the time gap from the last processed tag, to the next. In this case, the stream got stuck.
With this change, any and all `dt` passed into `tick` will be accumulated into `stream_time`, no matter if it triggered any tag processing or not.
=> core: Make sure that streams progress even with many small-dt ticks

core/src/avm2/activation.rs, core/src/avm2/optimize.rs, core/src/avm2/scope.rs, core/src/avm2/verify.rs
The best improvements I could find were in Doom Triple Pack: 20% more `InitProperty` optimizations and 2.5% more `CoerceD` optimizations
=> avm2: Various optimizations

desktop/src/gui.rs, desktop/src/gui/controller.rs, desktop/src/gui/preferences_dialog.rs, render/wgpu/src/backend.rs
We now try every single backend one-by-one to work around https://github.com/gfx-rs/wgpu/issues/2384 & https://github.com/gfx-rs/wgpu/issues/5324
=> desktop: Improve backend selection

desktop/src/app.rs
Previously the title showed the filename in the title even after the file had been long closed.
=> desktop: Fix window title after closing the file

core/src/avm2/optimize.rs
This was accidentally removed in #15476. Adding it back significantly improves optimizations for Box2D.
=> avm2: Properly push coerced value back to stack in optimizer for Coerce op

web/src/lib.rs
Noticed a bunch of PRs were marked as failing. Let's see if this fixes that.
=> chore: Fix false positive clippy lint in rustc 1.78 betas

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml
Unfortunately, with the current grouping, RenovateBot will most likely mess this up. *(Stares at #14146.)*
=> chore: Update `egui` to `v0.27.0`

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml, render/naga-agal/Cargo.toml
Right when https://github.com/ruffle-rs/ruffle/pull/15783 got merged... :upside_down_face:
Changelog for that: https://github.com/emilk/egui/releases/tag/0.27.0
Changelog for this: https://github.com/emilk/egui/releases/tag/0.27.1
Changelog for `insta`: https://github.com/mitsuhiko/insta/releases/tag/1.38.0
`cargo update` changes:
```
Updating chrono v0.4.35 -> v0.4.37
Updating memchr v2.7.1 -> v2.7.2
Updating memoffset v0.9.0 -> v0.9.1
Updating openssl-sys v0.9.101 -> v0.9.102
Updating regex-syntax v0.8.2 -> v0.8.3
Updating similar v2.4.0 -> v2.5.0
Updating tokio v1.36.0 -> v1.37.0
```
`profiling` and `tracy-client` held back as usual.
=> chore: Update `egui` to `v0.27.1`, `insta` to `v1.38.0`

desktop/src/gui/preferences_dialog.rs
=> desktop: show translated string for currently selected language

.github/workflows/test_rust.yml, Cargo.lock, exporter/Cargo.toml, render/canvas/Cargo.toml, render/naga-pixelbender/Cargo.toml, render/webgl/Cargo.toml, render/wgpu/Cargo.toml, tests/framework/Cargo.toml, web/Cargo.toml
Contrary to the source branch name, I went with `cargo-machete` instead of `cargo-udeps`: https://blog.benj.me/2022/04/27/cargo-machete/
Unfortunately, both point to a couple false positives, so they would need some manual handholding, polluting our `Cargo.toml` files. ( https://github.com/bnjbvr/cargo-machete/issues/118 )
~~Do we even need this...? :/~~
=> ci: Split cargo-deny into its own job, add cargo-machete

desktop/src/preferences/read.rs
The current item path is now kept track of dynamically removing the need for a hardcoded warnings.
and the caller no longer has to call `result.add_warning` themselves (mostly).
=> desktop: Cleanup warning boilerplate from preferences reader

.github/workflows/test_web.yml
The mismatch was introduced by https://github.com/ruffle-rs/ruffle/pull/15217.
For explanation: https://github.com/ruffle-rs/ruffle/pull/15782#issuecomment-2020541422
Thanks for noticing, @danielhjacobs!
This will hopefully unblock the CI run for https://github.com/ruffle-rs/ruffle/pull/15839.
=> ci: Fix the name of the no-op `check-required` job in the `Test Web` workflow

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml
Same story as https://github.com/ruffle-rs/ruffle/pull/15783.
=> chore: Bump `egui` to `v0.27.2`

core/src/player.rs, desktop/assets/texts/en-US/preferences_dialog.ftl, desktop/src/cli.rs, desktop/src/gui/preferences_dialog.rs, desktop/src/player.rs, desktop/src/preferences.rs, desktop/src/preferences/read.rs, desktop/src/preferences/storage.rs, desktop/src/preferences/write.rs, web/src/lib.rs
Implements #12943 and expands on it by adding it to preferences.
Unresolved questions:
Should we keep these preferences as `save`, rename to `storage` or something different entirely?
=> desktop: Add preference to change storage backend

Cargo.toml, core/Cargo.toml, core/build_playerglobal/Cargo.toml, desktop/Cargo.toml, exporter/Cargo.toml, flv/Cargo.toml, frontend-utils/Cargo.toml, render/Cargo.toml, render/canvas/Cargo.toml, render/naga-agal/Cargo.toml, render/naga-pixelbender/Cargo.toml, render/webgl/Cargo.toml, render/wgpu/Cargo.toml, scanner/Cargo.toml, swf/Cargo.toml, tests/Cargo.toml, tests/framework/Cargo.toml, tests/input-format/Cargo.toml, tests/mocket/Cargo.toml, tests/socket-format/Cargo.toml, video/Cargo.toml, video/software/Cargo.toml, web/Cargo.toml, web/common/Cargo.toml
Anything that we specified 4 times or more...
=> chore: Dedupe a whole bunch of dependency version specifications

.github/dependabot.yml
This should let us switch back from Renovate to Dependabot
=> chore: Re-enable Dependabot with dependency groups

desktop/src/app.rs, desktop/src/gui/controller.rs
On platforms that support synchronous resizing such as wayland `request_inner_size` returns the new window size and no `WindowEvent::Resize`  is generated ([documented here](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.request_inner_size)).
This MR resizes the gui if `request_inner_size` returns a value different from its original value.
| before | after |
|-|-|
| ![Screenshot from 2024-03-26 12-49-02](https://github.com/ruffle-rs/ruffle/assets/334272/a3e07c86-bf44-4977-936b-d2f8d51f8335) | ![Screenshot from 2024-03-26 12-44-55](https://github.com/ruffle-rs/ruffle/assets/334272/7dce39e2-286b-430b-82de-14e9a083d953) |
=> desktop: Fix gui scale on launch on wayland

.github/dependabot.yml
See: https://github.com/ruffle-rs/ruffle/network/updates/810167068
Fixup for https://github.com/ruffle-rs/ruffle/pull/15869, which was a fixup for https://github.com/ruffle-rs/ruffle/pull/14146.
=> chore: Fix Dependabot `npm` path

Cargo.lock, desktop/src/preferences/write.rs, frontend-utils/Cargo.toml, frontend-utils/src/lib.rs, frontend-utils/src/write.rs
This moves the logic previously found in BookmarkWriter's `with_underlying_table` into a common trait to be reused by other writers.
=> frontend-utils: Add TableExt trait

.github/dependabot.yml
This will hopefully make it not timeout
Kinda sucks but... oh well
=> chore: Only do direct dependencies with dependabot

.github/workflows/test_rust.yml, desktop/src/preferences/read.rs
Currently to check if it would have caught the unused import on master.
=> ci: run extra clippy step without tests

core/src/events.rs, desktop/src/util.rs, web/src/lib.rs
This patch adds support for <kbd>NumLock</kbd>, which was missing.
Now <kbd>NumLock</kbd> (144) may be used as a parameter in methods from the `Key` class.
=> input: Add support for `NumLock`

core/src/debug_ui/display_object.rs, core/src/display_object.rs, core/src/display_object/edit_text.rs, core/src/display_object/interactive.rs, core/src/focus_tracker.rs
This makes debugging easier, especially related to tab ordering :eyes: :eyes: :eyes:
=> core: Add focus tracker to debug UI

web/packages/extension/src/content.ts
The easier half of #15862, which does not apply in other browsers because other browsers don't inject an inline script for this purpose.
This matches Method 2: Inject embedded code (MV2) from https://stackoverflow.com/questions/9515704/access-variables-and-functions-defined-in-page-context-from-an-extension/9517879#9517879
=> extension: Cleanup plugin-polyfill inline script on Firefox

web/packages/extension/src/content.ts
This is almost identical to "Method 1: Inject another file" from https://stackoverflow.com/questions/9515704/access-variables-and-functions-defined-in-page-context-from-an-extension/9517879#9517879, but uses `addEventListener` instead of `onload`.
When merged alongside #15958, fixes #15862.
=> extension: Remove Ruffle's own script tag onload

core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/function.rs, core/src/avm2/method.rs, core/src/avm2/object.rs, core/src/avm2/object/function_object.rs, core/src/avm2/op.rs, core/src/avm2/optimize.rs, core/src/avm2/value.rs, core/src/avm2/verify.rs
`CallPropVoid` optimizes to `CallMethod` surprisingly well, sometimes around 60%.
The second commit turns out to be a little more complicated than #11954: FP does verification _before_ validating the user-passed arguments vs the function signature, so this requires some juggling in `Activation::init_from_method`. Specifically, we need the number of local registers to be known before initializing the Activation, but we also need that initialized Activation to resolve the arguments (which are put into local registers) in the verifier. This ended up being a good thing: we now allocate fewer locals (specifically, we now only do `num_locals + 1`, while previously we were doing `num_locals + num_declared_arguments + arg_register + 1`).
I noticed #15485 starts about 3 seconds faster for me. A …
=> avm2: More performance improvements

core/src/backend/audio/mixer.rs, core/src/display_object/graphic.rs, core/src/display_object/morph_shape.rs, core/src/library.rs, core/src/streams.rs, render/naga-agal/src/builder.rs, wstr/src/ptr.rs
As seen in: https://github.com/ruffle-rs/ruffle/actions/runs/8760095373/job/24044462484#step:6:709 (and all the way through the end of that step)
The `dead_code` lint is just silenced twice, because it seemed that the fields hold some kind of useful info that might be needed for future enhancements; while the third time I removed the field, because it looked like just a leftover technicality.
These lints are invisible, because we don't error out on them ( https://github.com/ruffle-rs/ruffle/actions/runs/8760095373/workflow#L134 ), but are also not printed as annotations either. The latter could be a TODO for later?
=> nits: Silence nightly lints

core/src/avm2/namespace.rs
This was getting spammed after #16069
=> avm2: Remove "namespace not matching" message

desktop/src/preferences/read.rs, frontend-utils/src/bookmarks/read.rs, frontend-utils/src/bundle.rs, frontend-utils/src/bundle/info.rs, frontend-utils/src/parse.rs
This lays the groundwork for translated warnings.
=> frontend-utils: Unify warning format strings; add warning enum

Cargo.lock
Really sorry for the spam, but it's that time of the week again, and now that RenovateBot doesn't do this, and DependaBot can't without timeouting, _someone has to_... :robot: (Okay, sure, not strictly, but why not...)
The only new node this adds to our dependency graph is `windows_i686_gnullvm`, which is a factory Windows thing - otherwise, it only tweaks versions and edges between crates.
To avoid `tracy-client` duplication, `profiling` and `profiling-procmacros` had to be held back, as usual.
Here's the summary:
```
Updating ab_glyph v0.2.23 -> v0.2.25
Updating allocator-api2 v0.2.16 -> v0.2.18
Updating async-executor v1.8.0 -> v1.11.0
Updating async-trait v0.1.79 -> v0.1.80
Updating bumpalo v3.15.4 -> v3.16.0
Updating cc v1.0.90 -> v1.0.95
Updating clipboard-win v5.3.0 -> v5.3.1 …
```
=> chore: Run `cargo update`, excluding `tracy-client` duplication

.github/workflows/release_amo.yml
We keep getting a note because of it about Node.js 16 actions being deprecated:
https://github.com/ruffle-rs/ruffle/actions/runs/8670264413
See: https://github.com/mathiasvr/command-output/issues/10
Also see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Drop the `mathiasvr/command-output@v2.0.0` action from the `release_amo` workflow

desktop/src/preferences/read.rs, frontend-utils/src/bookmarks/read.rs, frontend-utils/src/bundle/info.rs, frontend-utils/src/parse.rs
This PR should make it easier to parse key-value tables (like `parameters` in the upcoming bundle options).
=> frontend-utils: Parse API improvements

Cargo.lock, tests/Cargo.toml, tests/tests/regression_tests.rs
Regression tests were looked up using full directory walk regardless of whether there was an exact match or not. This patch looks up the test on exact match without scanning for all tests. This improvement is important due to how nextest executes tests: one by one using exact matches.
Additionally, this PR adds support for test kinds: `libtest_mimic` adds test kind as a prefix (e.g. `[kind] test` instead of `test`), which has to be taken into account when filtering for possible test candidates. This patch ensures compatibility with `libtest_mimic` when using test kinds.
Related comment: https://github.com/ruffle-rs/ruffle/pull/15950#issuecomment-2052141069
=> tests: Improve test lookup and add support for test kinds

web/packages/core/src/ruffle-player.ts
The `download_as_file` function in #16178, which is the `web_sys` version of this function just with `&[u8]` as input instead of a blob, made me realize this is unnecessary as it's not done in that function.
=> web: Don't append and subsequently remove link just to download files

Cargo.lock
This lets us drop `derivative` - one less thing keeping in `syn` `v1.x`.
Not yet bumping `arboard` to `v3.4.0` to not duplicate the `objc` crates.
This also adds https://github.com/polyfill-rs/is_terminal_polyfill, but it's a tiny crate.
Also taking care not to break `tracy-client` by duplicating it via a `profiling` update.
=> chore: Do a conservative `cargo update` manually

desktop/src/app.rs
Under hyprland tiling window manager, the resize event fails and the loading stops until the user manually resizes the window to trigger a resize event. 
This should fix that by not waiting for a resize event to continue loading if we know the resize failed.
The resize also fails even if the window is floating, so that may be something worth looking into separately.
=> desktop: Skip waiting for resize event after resize fails

core/src/avm2/globals/XML.as, core/src/avm2/globals/xml.rs, core/src/avm2/object/xml_object.rs, tests/tests/swfs/from_avmplus/e4x/XMLList/e13_5_1/test.toml
[XML.contains()](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/XML.html#contains()) method implemented.
Test:
```as
<?xml version="1.0" encoding="utf-8"?>
<mx:Application xmlns:mx="http://www.adobe.com/2006/mxml" layout="absolute" minWidth="955" minHeight="600" creationComplete="init()">
<mx:Script>
<![CDATA[			
private function init():void {
var xml:XML = 
<order>
<item>Rice</item>
<item>Kung Pao Shrimp</item>
</order>;
trace(xml.item[0].contains(<item>Rice</item>)); // true
trace(xml.item[1].contains(<item>Kung Pao Shrimp</item>)); // true
trace(xml.item[1].contains(<item>MSG</item>)); // false
}
]]>
</mx:Script>
</mx:Application>
```
=> avm2: Implement XML.contains

core/src/avm2/object.rs, core/src/avm2/vtable.rs
This PR shares the optimization from `call_property` which skips binding methods that don't need receivers with `call_method`. Currently, for example, Chess Demons allocates almost 1GB of unnecessary function objects during loading, this patch fixes that:
```
Command                            USS 
./ruffle_desktop_opt cd.swf       1.5G 
./ruffle_desktop_no_opt cd.swf    2.5G
```
A quick `perf stat` run shows a small decrease in loading time and page faults cut in half:
```
Performance counter stats for './ruffle_desktop_opt cd.swf':
20,082.41 msec task-clock:u                     #    0.582 CPUs utilized             
0      context-switches:u               #    0.000 /sec                      
0      cpu-migrations:u                 #    0.000 /sec                      
376,719 …
```
=> avm2: share binding skip optimization with `call_method`

core/src/ecma_conversions.rs, render/src/matrix.rs
This patch improves performance of `ecma_conversions::round_to_even()` and `matrix::round_to_i32()`:
1. by using `f64::round_ties_even()`/`f32::round_ties_even()`, which have been stable since 1.77.0, instead of a custom algorithm; and
2. by removing an unnecessary comparison to `i32::MIN`, as casting a float to an integer automatically saturates values smaller than the minimum integer value to the minimum value of the integer type.
A primitive benchmark shows around 20% faster execution of these operations. In the case of `matrix::round_to_i32()` we can potentially expect noticeable improvements in overall performance as this operation is quite commonly used.
| Platform | Operation | Type | Improvement |
| -------- | --------- | ---- | ------- |
| amd64    | …
=> core,render: Improve performance of "round to nearest, ties to even" float operations

core/src/avm2/activation.rs, core/src/avm2/bytearray.rs, core/src/avm2/verify.rs
This PR has been stripped of most of the larger changes. The only notable change remaining is a fast path for setting index properties on arrays.
=> avm2: Minor performance improvements

core/src/debug_ui/display_object.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/avm2_button.rs, core/src/display_object/edit_text.rs, core/src/display_object/interactive.rs, core/src/display_object/movie_clip.rs
Newly implemented "Interactive" tab:
Some visual improvements for "Stage" tab:
=> debug_ui: Add a tab for interactive objects

core/src/config.rs, core/src/display_object/stage.rs, core/src/loader.rs, core/src/player.rs, desktop/src/cli.rs, desktop/src/player.rs, frontend-utils/src/bundle.rs, frontend-utils/src/bundle/README.md, frontend-utils/src/bundle/info.rs, frontend-utils/src/parse.rs, frontend-utils/src/player_options.rs, frontend-utils/src/player_options/read.rs, render/src/quality.rs, web/src/lib.rs
Differences in the specification between the gist and this PR.
- Some examples in the gist referred to their old names, this has been fixed.
- Explicitly mentions that frame rate can be a floating-point value as well as an integer. (Changed for consistency, since script_timeout allows both)
- Fixed typo in `frame_rate` description (Maybe be -> May be).
cc @Dinnerbone
=> frontend-utils: Add bundle player options

.github/workflows/test_rust.yml
This will hopefully prevent CI failures like these:
https://github.com/ruffle-rs/ruffle/actions/runs/9103363884/job/25025064793
https://github.com/ruffle-rs/ruffle/actions/runs/9103952906/job/25026859930
Thanks for finding the issues linked from the code, @Dinnerbone!
=> github: Add a workaround for nextest failing on Windows

.github/dependabot.yml
"profiling" ignore:
The other two ignored crates are indirect through this.
`Cargo.lock` bump:
Hopefully, now that it runs on GHA infra, it won't timeout.
=> `github`: Make Dependabot also ignore "profiling", add a group to bump `Cargo.lock`

.github/dependabot.yml, Cargo.lock, Cargo.toml, render/naga-pixelbender/Cargo.toml, render/naga-pixelbender/src/lib.rs, render/src/shader_filter_common.wgsl, render/wgpu/Cargo.toml, render/wgpu/shaders/bitmap.wgsl, render/wgpu/shaders/blend/alpha.wgsl, render/wgpu/shaders/blend/darken.wgsl, render/wgpu/shaders/blend/difference.wgsl, render/wgpu/shaders/blend/erase.wgsl, render/wgpu/shaders/blend/hardlight.wgsl, render/wgpu/shaders/blend/invert.wgsl, render/wgpu/shaders/blend/lighten.wgsl, render/wgpu/shaders/blend/multiply.wgsl, render/wgpu/shaders/blend/overlay.wgsl, render/wgpu/shaders/color.wgsl, render/wgpu/shaders/common.wgsl, render/wgpu/shaders/copy.wgsl, render/wgpu/shaders/copy_srgb.wgsl, render/wgpu/shaders/filter/blur.wgsl, render/wgpu/shaders/filter/color_matrix.wgsl, render/wgpu/shaders/gradient.wgsl, render/wgpu/src/shaders.rs
One fewer dependency. We've only used the very basics of its capabilities lately anyway.
Also, so we're not stuck waiting for the likes of https://github.com/bevyengine/naga_oil/pull/87.
Unblocks https://github.com/ruffle-rs/ruffle/pull/16168, and the update to `egui` `master` (temporarily), thereby the fixing of #15836.
TODO:
- ~~sort out vertex colliding entry point names...?~~
- ~~pipeline constants for `early_saturate`~~
- After the switch to `wgpu` 0.20
- Currently solved with a simple string substitution, the compiler will probably optimize out the dead piece of code.
- investigate effect on shader compilation times (startup)
=> `render/wgpu`: Drop `naga_oil` in favor of manual string manipulation

.github/dependabot.yml
This reverts commit 6c144a038f476c81521523973e005d8371f32131.
See https://github.com/ruffle-rs/ruffle/runs/25067106580. The only options for the dependency-type of a group are production and development: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups. This was done with the options for allow in mind: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow.
As for update-types, that should have been:
```
update-types:
- "major"
- "minor"
- "patch"
```
=> Revert "github: Add a Dependabot group just for bumping Cargo.lock"

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/debug_ui/avm1.rs, core/src/debug_ui/avm2.rs, core/src/debug_ui/display_object.rs, core/src/debug_ui/display_object/search.rs, core/src/debug_ui/movie.rs, deny.toml, desktop/Cargo.toml, desktop/src/gui/movie.rs, render/naga-agal/src/builder.rs, render/wgpu/src/context3d/current_pipeline.rs, render/wgpu/src/descriptors.rs, render/wgpu/src/filters/bevel.rs, render/wgpu/src/filters/blur.rs, render/wgpu/src/filters/color_matrix.rs, render/wgpu/src/filters/displacement_map.rs, render/wgpu/src/filters/glow.rs, render/wgpu/src/pipelines.rs, render/wgpu/src/pixel_bender.rs
~~Depends on https://github.com/emilk/egui/pull/4433 and https://github.com/bevyengine/naga_oil/pull/87/~~.
~~Also includes https://github.com/ruffle-rs/ruffle/pull/16077 because https://github.com/emilk/egui/pull/4394 is in `egui` `master`.~~
Builds on top of https://github.com/ruffle-rs/ruffle/pull/16330.
Fixes #15836 by switching to `egui` `master`.
=> render,desktop: Port to `wgpu` `v0.20.0`, switch to `egui` `master`

Cargo.lock
If not automatically on a schedule (RIP https://github.com/ruffle-rs/ruffle/pull/16335), then manually from time to time, as before.
As usual, taking care not to duplicate `tracy-client` by holding back `profiling`.
```
Updating arboard v3.3.2 -> v3.4.0
Updating autocfg v1.2.0 -> v1.3.0
Updating camino v1.1.6 -> v1.1.7
Updating cc v1.0.96 -> v1.0.97
Updating darling v0.20.8 -> v0.20.9
Updating darling_core v0.20.8 -> v0.20.9
Updating darling_macro v0.20.8 -> v0.20.9
Updating errno v0.3.8 -> v0.3.9
Updating gc-arena v0.5.1 -> v0.5.3
Updating gc-arena-derive v0.5.1 -> v0.5.3
Updating linux-raw-sys v0.4.13 -> v0.4.14 (latest: v0.6.4)
Updating lyon_path v1.0.4 -> v1.0.5
Updating num-complex v0.4.5 -> v0.4.6
Adding objc2-app-kit v0.2.0
Adding objc2-core-data v0.2.0
Updating parking_lot v0.12.1 …
```
=> chore: Run `cargo update` to bump indirect deps in `Cargo.lock`

.github/workflows/test_web.yml, web/README.md
It has been out for like three weeks now, and it is the next LTS release.
https://nodejs.org/en/blog/announcements/v22-release-announce
https://nodejs.org/en/about/previous-releases
=> ci: Test with Node.js 22 instead of 21

render/wgpu/shaders/bitmap.wgsl, render/wgpu/src/pipelines.rs, render/wgpu/src/shaders.rs
Also call it `late_saturate` instead, to avoid the confusing negation between the constant name and the (now removed) shader module name.
Follow-up for https://github.com/ruffle-rs/ruffle/pull/16168.
See also: https://github.com/gfx-rs/wgpu/blob/trunk/CHANGELOG.md#pipeline-overridable-constants
=> render/wgpu: Switch to pipeline-overridable constant for bitmap saturation order toggle

core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/domain.rs, core/src/avm2/globals.rs, core/src/avm2/object.rs, core/src/avm2/op.rs, core/src/avm2/optimize.rs, core/src/avm2/scope.rs, core/src/avm2/script.rs, core/src/avm2/verify.rs
Also propagate types from `getslot`, `getglobalscope`, and `getglobalslot`.
A single `getlex QName(PackageNamespace(""), "Math")` executes about 2.5x faster with this PR.
New stats for box2d:
```
FindPropStrict -> GetScriptGlobals : 45.16%
FindPropStrict -> GetOuterScope : 7.87%
FindPropStrict -> GetScopeObject : 1.69%
FindProperty -> GetOuterScope : 2.83%
FindProperty -> GetScopeObject : 5.66%
InitProperty -> SetSlot : 38.15%
InitProperty -> SetSlotNoCoerce : 37.87%
SetProperty -> SetSlot : 15.03%
SetProperty -> SetSlotNoCoerce : 30.42%
SetProperty -> CallMethod : 1.57%
GetProperty -> GetSlot : 59.69%
GetProperty -> CallMethod : 0.34%
CallProperty -> CallMethod : 31.45%
CallPropVoid -> CallMethod : 61.74%
Coerce -> Nop : 46.95%
CoerceD -> Nop : 78.36%
CoerceB -> Nop : 8.11%
CoerceU -> …
```
=> avm2: Optimize `findpropstrict`, `findproperty`, and `getlex`

.github/workflows/test_rust.yml
This will probably fix the CI failures.
As per https://github.com/dtolnay/linkme/pull/88, following https://github.com/rust-lang/rust/pull/124129.
=> ci: Disable rust-lld on Rust nightly

core/src/debug_ui/display_object.rs, core/src/display_object/edit_text.rs
This patch adds multiple properties and controls to EditText tab.
This includes for instance:
* border, border color,
* background, background color,
* editable, selectable, word wrap properties,
* autosize, max chars, restrict, etc.
Additionally this fixes a bug when the EditText's bitmap was not invalidated after disabling both border and background (causing them to render regardless).
| Before | After |
| ------ | ----- |
| <image src="https://github.com/ruffle-rs/ruffle/assets/1507072/34c04d5f-71da-4b2f-b6ca-2dd3c68990f1" width="300"/> | <image src="https://github.com/ruffle-rs/ruffle/assets/1507072/f3ffcc65-9a0a-4f2d-ae6c-e7e9c0f18c15" width="300"/> |
=> debug_ui: Improve EditText tab

web/packages/core/src/ruffle-player.ts
Just returns 0 or 100 right now, I don't know exactly how it should work but this is enough to progress some stuff
Fixes #15023
Fixes #15021
(In the future we'll need to limit these to just the polyfill API I think)
=> web: Stub the PercentLoaded() JS method

core/src/display_object/movie_clip.rs
This is preparation for allowing a class to be linked to the root movie clip and instantiated.
=> core: Store MovieClip avm2_class in MovieClipStatic

desktop/src/gui.rs, desktop/src/gui/menu_bar.rs, desktop/src/player.rs, frontend-utils/src/recents.rs, frontend-utils/src/recents/read.rs, frontend-utils/src/recents/write.rs
This should lead to shorter recent entries in the GUI by only showing the filename or bundle name (depending on which was opened).
If name field is missing from `recents.toml`, which would be the case with files created by previous Ruffle versions, it falls back to the filename from the URL.
=> desktop/frontend-utils: Show filename or bundle name in recent list

core/src/avm2.rs, core/src/avm2/call_stack.rs, core/src/avm2/function.rs, core/src/avm2/object.rs, core/src/avm2/object/class_object.rs, core/src/avm2/object/function_object.rs, core/src/avm2/specification.rs
Fun fact, `Executable` has been almost unchanged since the very first AVM2 commit. Time for some code churn? :) 
The diff looks large, but most of it is just moving `exec()` implementation.
This merges several refactors:
- `NativeExecutable` and `BytecodeExcecutable` are basically identical, aside from the `method` field - so I collapsed them back to a single struct.
- At this point `Executable` is pretty much just a `BoundMethod`, so I renamed it to such.
- also did some internal renaming, like `superclass` is really just a `bound_class`, but I didn't do it outside of `Executable`.
- The only way to directly call a method is `Executable::from_method(...).exec(...)`, which is kinda pointless (and does pointless work of handling bound/unbound `this`), so I collapsed this to a single …
=> avm2: Refactor Executable->BoundMethod, introduce freestanding exec()

tests/tests/swfs/avm1/issue_2084/Column.as, tests/tests/swfs/avm1/issue_2084/Main.as
No functional changes. I didn't bother recompiling the SWF files since just the comments were removed. Just addresses a small pet peeve of mine where these files were appearing in this search: https://github.com/search?q=repo%3Aruffle-rs%2Fruffle++language%3AJavaScript&type=code
=>  chore: Remove inaccurate syntax comments from AS files

.gitattributes
Right now it thinks .frag files are JavaScript: https://github.com/search?q=repo%3Aruffle-rs%2Fruffle++language%3AJavaScript+&type=code. The .vert files are correctly highlighted (https://github.com/search?q=repo%3Aruffle-rs%2Fruffle++path%3A.vert&type=code), but it's still better to be explicit. I looked at some of these results on GitHub to match sure I use the right syntax for the .gitattributes file: https://github.com/search?q=*.frag+++linguist-language%3D&type=code
=> chore: Properly detect files as GLSL on GitHub

core/src/avm2/e4x.rs, core/src/avm2/globals/xml.rs, core/src/avm2/object/xml_list_object.rs, core/src/avm2/object/xml_object.rs
In preparation of giving E4X elements a list of all their namespace (declarations) I am switching the namespace property on all objects to the newly introduced `E4XNamespace`. We don't yet use the new prefix information for anything, so this should not change any behavior.
=> avm2: Introduce an E4XNamespace type (NFCI)

frontend-utils/src/backends/navigator.rs
This fixes loading AQ (eg https://game.aq.com/game/gamefiles/Loader3.swf?ver=a) - but it's also just good form.
Example useragent: `Ruffle/0.1.0 (https://ruffle.rs)`
=> frontend-utils: Set a useragent for requests

web/src/lib.rs
This was pretty error-prone, and now it shouldn't be!
For reviewing, take it commit-by-commit. Maybe ignore whitespaces.
=> web: Dedupe a whole bunch of JS callback boilerplate

web/package-lock.json
This fixes this advisory:
https://github.com/ruffle-rs/ruffle/security/dependabot/71
https://github.com/advisories/GHSA-78xj-cgh5-2h22
=> web,chore: Run `npm audit fix` to resolve an `ip` vulnerability

core/src/avm1/globals/load_vars.rs
The `LoadVars.send` signature is `send(url:String, target:String, [method:String]):Boolean`
There was a small mistake in the code that read the second parameter for target AND method.
=> avm1: fix loadvars.send parameters

core/src/avm1/globals/netstream.rs, core/src/streams.rs
This should fully fix #12934.
`bufferLength` always reports that the buffer is fully filled, while `bufferTime` can be set but has no effect.
=> avm1: Stub `bufferLength` and `bufferTime` on `NetStream`

desktop/src/backends/external_interface.rs
I was debugging a game that it is actually using `eval` for looking up the location.
=> desktop: Support for spoofing eval("window.location.href") with ExternalInterface

core/src/avm2/class.rs, core/src/avm2/globals.rs, core/src/avm2/globals/array.rs, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/boolean.rs, core/src/avm2/globals/class.rs, core/src/avm2/globals/date.rs, core/src/avm2/globals/flash/text/ime/CompositionAttributeRange.as, core/src/avm2/globals/flash/text/ime/IIMEClient.as, core/src/avm2/globals/function.rs, core/src/avm2/globals/global_scope.rs, core/src/avm2/globals/globals.as, core/src/avm2/globals/int.rs, core/src/avm2/globals/namespace.rs, core/src/avm2/globals/number.rs, core/src/avm2/globals/object.rs, core/src/avm2/globals/string.rs, core/src/avm2/globals/uint.rs, core/src/avm2/globals/vector.rs, core/src/avm2/globals/void.rs, core/src/avm2/object.rs, core/src/avm2/object/class_object.rs, core/src/avm2/optimize.rs, core/src/avm2/script.rs, core/src/avm2/vtable.rs
This is a little hacky, but it should be simplified once the class refactor is done.
Box2d stats:
```
FindPropStrict -> GetScriptGlobals : 62.18% (+17.02%)
FindPropStrict -> GetOuterScope : 7.76% (-0.11%)
FindPropStrict -> GetScopeObject : 8.24% (+6.55%)
FindProperty -> GetOuterScope : 2.83%
FindProperty -> GetScopeObject : 94.34% (+88.68%)
InitProperty -> SetSlot : 40.93% (+2.78%)
InitProperty -> SetSlotNoCoerce : 44.51% (+6.64%)
SetProperty -> SetSlot : 28.67% (+13.64%)
SetProperty -> SetSlotNoCoerce : 39.51% (+9.09%)
SetProperty -> CallMethod : 1.57%
GetProperty -> GetSlot : 67.31% (+7.62%)
GetProperty -> CallMethod : 0.34%
CallProperty -> CallMethod : 41.13% (+9.68%)
CallPropVoid -> CallMethod : 74.24% (+12.5%)
Coerce -> Nop : 49.78% (+2.83%)
CoerceD -> Nop : 81.34% (+2.98%)
CoerceB …
```
=> avm2: Improve optimizations on static methods

core/src/avm2/object.rs
A `ScriptObject` was being allocated on every `call_method` call
=> avm2: Fix performance regression

Cargo.lock, core/src/config.rs, core/src/player.rs, render/webgl/src/lib.rs, web/common/Cargo.toml, web/common/src/lib.rs, web/packages/core/src/internal/builder.ts, web/packages/core/src/load-options.ts, web/packages/core/src/load-ruffle.ts, web/packages/core/src/ruffle-player.ts, web/packages/core/test/config.ts, web/src/builder.rs, web/src/lib.rs
The main motivation here is to get all the parsing of config stuff out from Rust and into TypeScript, for a few reasons:
1. Duck typing is what JS/TS is good at - Rust is really, really bad at it.
2. As we evolve the config, potentially change which values are accepted (eg the duration once went from object to number), we can just translate that in TS and Rust only needs to know the "real", final value
3. We can easily add tests for config parsing, which wasn't quite as simple in Rust
4. We can change what Rust accepts on a whim now, as needed - without changing the actual config interface we expose publicly
Along with this, lots of refactoring to split up `lib.rs` some more. A new `RuffleInstanceBuilder` is responsible for actually constructing the `Player `and `RuffleInstance`.
I've …
=> web: Make config parsed by TS, not rust - and lots of other refactorings

core/src/avm2.rs, core/src/avm2/amf.rs, core/src/avm2/globals/flash/net.as, core/src/avm2/globals/flash/net.rs
No functional changes intended.
Prerequisite for future refactor to make `class_to_alias_map` use a `Class` instead of `ClassObject` key.
=> avm2: Port registerClassAlias logic to Rust

core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/amf.rs, core/src/avm2/class.rs, core/src/avm2/error.rs, core/src/avm2/globals.rs, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/flash/display/bitmap_data.rs, core/src/avm2/globals/flash/display/graphics.rs, core/src/avm2/globals/flash/display/stage.rs, core/src/avm2/globals/flash/media/video.rs, core/src/avm2/globals/flash/system/application_domain.rs, core/src/avm2/globals/flash/utils.rs, core/src/avm2/globals/vector.rs, core/src/avm2/object.rs, core/src/avm2/object/class_object.rs, core/src/avm2/object/error_object.rs, core/src/avm2/object/primitive_object.rs, core/src/avm2/object/script_object.rs, core/src/avm2/object/vector_object.rs, core/src/avm2/optimize.rs, core/src/avm2/scope.rs, core/src/avm2/script.rs, core/src/avm2/vector.rs, core/src/avm2/vtable.rs, core/src/debug_ui/avm2.rs, core/src/display_object/bitmap.rs
This is work on storing a `Class` instead of a `ClassObject` as an Object's `instance_of`, which is necessary for the refactor.
Notable changes:
- `ClassObject` no longer stores its interfaces
- `ClassObject` no longer stores its type parameter, and the `applications` map is now a `Option<Class>` -> `ClassObject` map instead of an `Option<ClassObject>` -> `ClassObject`
- `has_class_in_chain` has been moved to `Class`
- `Class` now stores a list of all its interfaces (`all_interfaces`)
- `ClassKey` and `ClassHashWrapper` have been removed as they were no longer necessary after #16128
- `VectorStorage` now stores the value type as a `Class` instead of a `ClassObject`
- Logic for applying a type parameter to a `ClassObject` has been moved into its own function, `ClassObject::parametrize`
=> avm2: More work on the class refactor

core/src/avm1/value.rs, core/src/avm2/class.rs, core/src/avm2/globals/flash/display/shader_parameter.rs, desktop/src/cli.rs
Not all of them are fixed, see: https://github.com/rust-lang/rust-clippy/issues/12917
=> chore: Fix some beta clippy lints

.github/workflows/test_rust.yml
Should fix CI failing with beta Rust (aside from the lints, for which there's https://github.com/ruffle-rs/ruffle/pull/16679 and https://github.com/ruffle-rs/ruffle/pull/16683).
Now that Rust beta also uses `rust-lld` by default on `x86_64-unknown-linux-gnu`, we can't use `-Z` as a workaround.
An alternative to https://github.com/ruffle-rs/ruffle/pull/16448.
Also reverts https://github.com/ruffle-rs/ruffle/pull/16390.
Referencing: https://github.com/dtolnay/linkme/issues/94
For more info, see: https://lld.llvm.org/ELF/start-stop-gc
=> ci: Set the `-znostart-stop-gc` flag for lld when testing

core/src/avm2/globals/flash/display/graphics.rs
Split out from https://github.com/ruffle-rs/ruffle/pull/16679.
Referencing https://github.com/rust-lang/rust-clippy/issues/12917 again.
=> chore: Suppress a `clippy::doc_lazy_continuation` beta lint false positive

web/packages/extension/manifest_firefox.json5, web/packages/extension/src/background.ts, web/packages/extension/src/content.ts, web/packages/extension/src/utils.ts, web/packages/extension/webpack.config.js
Currently works on Firefox Nightly and Beta. Will reach stable on July 9th. ~~This will stay a draft until we deem adaptation levels for Firefox 128 acceptable to merge it. Any version of Firefox below Firefox 128 has the following error due to the code in background.ts: `Error: Type error for parameter scripts (Error processing 0: Unexpected property "world") for scripting.registerContentScripts.` We probably could avoid the `strict_min_version` and I'm guessing the only issue on older browsers would be a failure to spoof the Flash plugin, but I thought it better that the spoofing always works.~~
Edit: Now works on all Firefox versions.
=> extension: Use scripting permission for Flash spoofing on Firefox too

core/src/display_object/container.rs, core/src/display_object/interactive.rs, core/src/display_object/movie_clip.rs, core/src/player.rs
This prevents problems in case of mixed-AVM content.
cc @Lord-McSweeney
=> core: Use DisplayObject.movie() instead of context.swf where applicable

core/Cargo.toml, core/src/backend/navigator.rs, core/src/config.rs, core/src/context_menu.rs, core/src/events.rs, core/src/player.rs, render/Cargo.toml, render/src/backend.rs, tests/framework/Cargo.toml, web/Cargo.toml, web/src/lib.rs
We still need the dependency because of `serde_json` - but this removes the `derive` feature at least, which should increase compile times a bit (for desktop at least; web still uses serde a little)
Sadly it's still being built on desktop anyway because of https://github.com/emilk/egui/pull/4641 but... eventually!
=> core: Reduce serde dependency

web/packages/extension/tools/tsconfig.json, web/packages/extension/tools/zip.ts
Will hopefully fix last night's errors: https://github.com/ruffle-rs/ruffle/actions/runs/9491395142
=> extension: Fix zip tool by adding import.meta.url back

Cargo.lock, swf/Cargo.toml
I published a new version of `swf` after like two years and needed to bump the version.
=> swf: Bump version to 0.2.1 in preparation for new package publication

.github/workflows/release_nightly.yml, .github/workflows/test_rust.yml
At least until a release with https://github.com/gfx-rs/wgpu/pull/5831 is out.
Fixes https://github.com/ruffle-rs/ruffle/issues/16715
=> ci: Release and test with Rust 1.78 instead of stable

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml, desktop/src/gui/context_menu.rs, desktop/src/gui/dialogs/bookmarks_dialog.rs
`egui` actually reverted to `wgpu` `0.19` for a while (https://github.com/emilk/egui/pull/4559), but now that https://github.com/gfx-rs/wgpu/pull/5681 fixed the reasons for the downgrade, they have updated again: https://github.com/emilk/egui/pull/4560
The little `egui` API change was: https://github.com/emilk/egui/pull/4556
=> core,desktop: Update `wgpu` to `v0.20.1`, bump `egui`

.cargo/config.toml, .github/workflows/test_rust.yml, web/Cargo.toml, web/packages/core/src/ruffle-player.ts, web/packages/core/src/shadow-template.ts, web/packages/core/texts/en-US/messages.ftl, web/packages/core/tools/build_wasm.ts, web/src/lib.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/16678.
Ruffle does not have direct clipboard access on web, so the current paste implementation from the context menu does not work. This patch intercepts the paste context menu callback, and uses the Clipboard API to ask the browser for the clipboard and update it before calling the callback. When the Clipboard API is not available, a modal informing the user about cut, copy, paste shortcuts is displayed.
| Firefox | Chromium |
| ------- | -------- |
| <image src="https://github.com/ruffle-rs/ruffle/assets/1507072/dd3d576f-7ecc-4140-aa8b-ffba7e14ef8a" width="400"/> | <image src="https://github.com/ruffle-rs/ruffle/assets/1507072/7a5aeb40-3dab-4a0c-9d59-8598aff05d4c" width="400"/> |
| Clipboard modal |
| --------------- |
| <image …
=> web: Implement pasting text using Clipboard API

core/src/debug_ui/display_object.rs, core/src/display_object/edit_text.rs
It's useful when debugging issues related to EditText's layout.
| Disabled | Enabled |
| -------- | ------- |
| <image src="https://github.com/ruffle-rs/ruffle/assets/1507072/50331a04-6a85-4cb2-ab98-023728f44102" width="300"/> | <image src="https://github.com/ruffle-rs/ruffle/assets/1507072/5666d71f-3830-43ba-87e0-4e3a30d2989a" width="300"/> |
=> debug_ui: Add option to draw layout boxes for EditText

core/src/display_object/edit_text.rs, core/src/html.rs, core/src/html/layout.rs
This PR neither fixes any bugs nor implements new features. The main goal is to refactor the `layout` module, so that it's not _that_ painful to use.
This PR removes `LineData` & `get_line_data` and incorporates their logic into layout calculation adding `Layout` and `LayoutLine`. The goal is to simplify operations on the layout, as now line data is always present and integrated with the layout. Specialized methods may be added to `Layout` and `LayoutLine` in the future.
This refactor opens up possibilities for further improvements:
* providing binary-search-based layout box lookup,
* simplifying `screen_position_to_index`,
* implementing vertical text control,
* implementing advanced text API for AVM2.
This PR already includes some improvements:
* `EditText.layout_metrics` refactor — …
=> text: Restructure layout to include text lines

web/packages/core/src/ruffle-imports.ts, web/packages/selfhosted/test/integration_tests/external_interface/test.ts
This fixes #8330 (club penguin / newcp.net). It works surprisingly well, minor issues so far - mostly audio and text. Decent performance too!
It looks like my earlier PR to make LocalConnection likely would have fixed Club Penguin in general, but this specific site uses some javascript that doesn't work in strict mode. This change (thanks @evilpie for the recommendation to use Function!) makes it work!
The site needs a proxy to get working, which I'll leave as an exercise to the site owners.
=> web: Don't use direct eval, use indirect new Function(...) instead

render/wgpu/shaders/filter/displacement_map.wgsl
Fixes https://github.com/ruffle-rs/ruffle/issues/12844, fixes https://github.com/ruffle-rs/ruffle/issues/16642.
Turns out that 'packed' is a keyword in some GLSL shaders, and naga currently preserves it, producing a syntax error.
As a workaround, this patch renames the variable to something else.
=> wgpu: Do not use 'packed' as variable name in WGSL shaders

core/src/focus_tracker.rs
This patch bypasses AVM2 conditionally when firing roll over events triggered by a focus change until a proper support for AVM2 events is implemented.
Related to https://github.com/ruffle-rs/ruffle/issues/16789. See also https://github.com/ruffle-rs/ruffle/pull/16581.
=> avm2: Do not fire roll over events on focus change (yet)

web/package-lock.json
Like this:
```
$ rm -rf package-lock.json node_modules/
$ npm update
$ npm install --save --save-dev --save-peer
```
Seems that this gets crufty over time for some reason.
Mostly trying to make https://github.com/ruffle-rs/ruffle/security/dependabot/72 disappear - not there yet.
That is, to get "ws" to a version including https://github.com/websockets/ws/pull/2231.
=> chore: web: Regenerate `package-lock.json`

.github/workflows/release_nightly.yml, .github/workflows/test_rust.yml, Cargo.lock, core/Cargo.toml, swf/Cargo.toml
Now that https://github.com/gfx-rs/wgpu/pull/5831 is merged, let's revert https://github.com/ruffle-rs/ruffle/pull/16764, go forward to the ~~yet un~~released `wgpu` version, and finish up https://github.com/ruffle-rs/ruffle/pull/16770.
=> chore: Update `wgpu-core` and `wgpu-hal` to `v0.21.1`

core/src/debug_ui.rs, core/src/debug_ui/display_object.rs, core/src/debug_ui/display_object/search.rs, core/src/display_object.rs
Before this patch, it was possible that some objects did not have a debug rect despite existing on the stage and interacting with the user. That was the case for instance for buttons with hit bounds and no up state (see for instance https://github.com/ruffle-rs/ruffle/issues/16921).
This patch ensures that debug rect is at least as big as highlight bounds, which are used to highlight focused objects on the stage.
Additionally, when the user hovers on world bounds and highlight bounds, debug rects signifying their positions are automatically drawn in order to visualize their positions on the stage.
=> debug_ui: Improve debug rect bounds calculation & draw bounds on hover

Cargo.lock, core/Cargo.toml, core/src/avm1/globals/xml.rs, core/src/avm2/e4x.rs, core/src/html/text_format.rs, tests/tests/swfs/from_avmplus/as3/RuntimeErrors/Error1090XmlElementMalformed/test.toml
Split from https://github.com/ruffle-rs/ruffle/pull/16769 / https://github.com/ruffle-rs/ruffle/pull/16870 / https://github.com/ruffle-rs/ruffle/pull/16871.
Changelog:
https://github.com/tafia/quick-xml/releases/tag/v0.32.0
https://github.com/tafia/quick-xml/releases/tag/v0.33.0
https://github.com/tafia/quick-xml/releases/tag/v0.34.0
https://github.com/tafia/quick-xml/releases/tag/v0.35.0
I'm not 100% sure I did all the `UnexpectedEof` replacements correctly.
=> chore: Update quick-xml to 0.35.0

core/src/library.rs
We only support one default font implementation anyway and currently this generates annoying warnings about unknown device fonts.
=> core: Stop searching after finding the first default font

web/packages/core/src/index.ts, web/packages/core/src/install.ts, web/packages/core/src/load-ruffle.ts, web/packages/core/src/public-api.ts, web/packages/core/src/ruffle-player.ts, web/packages/core/src/source-api.ts, web/packages/demo/src/main.tsx, web/packages/extension/src/player.ts, web/packages/extension/src/ruffle.ts, web/packages/selfhosted/js/ruffle.js
Now things like ruffle website can *actually* depend on ruffle-core as a library, rather than only as an already built zip of assets and js files.
This does **not** include releasing ruffle-core to npm, I'll look at that later after reviewing the API.
API of selfhosted does not change. API of ruffle-core changes... but nobody can use it yet anyway, so it's all fine.
=> web: Make ruffle-core actually work when not being used as a selfhosted zip

web/packages/extension/webpack.config.js
This fixes #16939
Turns out we've always specified this wrong, but accidentally worked around it at runtime before
=> web: Specify the correct path of assets for webpack in extension

web/packages/extension/webpack.config.js
Fixes #16939 for realsies
"auto" uses the scripts current path and derives it from there.
=> web: Use automatic publicPath in extension

core/src/avm2/globals/XMLList.as
This closes #3588, though it spams errors in desktop because of fscommand not being accessible. #4527 is also almost definitely fixed but I couldn't check.
=> avm2: Use proper coercion in XMLList prototype methods

Cargo.lock, Cargo.toml, core/Cargo.toml, deny.toml, desktop/Cargo.toml
Changelog: https://github.com/emilk/egui/releases/tag/0.28.0
Fortunately, we have already accommodated for all the API changes in https://github.com/ruffle-rs/ruffle/pull/16704.
=> desktop: Update `egui` to `v0.28.0`

web/.eslintrc.yaml, web/package-lock.json, web/packages/core/package.json, web/packages/core/src/globals.d.ts, web/packages/core/src/internal/constants.tsx, web/packages/core/src/internal/errors.tsx, web/packages/core/src/internal/ui/panic.tsx, web/packages/core/src/ruffle-embed.ts, web/packages/core/src/ruffle-object.ts, web/packages/core/src/ruffle-player.ts, web/packages/core/src/ruffle-player.tsx, web/packages/core/src/source-api.ts, web/packages/core/tsconfig.json
It's *so much nicer*
At compile time, it's converted into regular javascript.
For example - though slightly modified as I've done other refactors to make things just generally cleaner around there. New code is actually cleaner than shown here.
```jsx
const errorFooter = document.createElement("ul");
for (const linkInfo of footerInfo) {
const footerItem = document.createElement("li");
const footerLink = document.createElement("a");
footerLink.href = linkInfo.url;
footerLink.textContent = linkInfo.label;
if (linkInfo.url === "#") {
footerLink.id = "panic-view-details";
} else {
footerLink.target = "_top";
}
footerItem.appendChild(footerLink);
errorFooter.appendChild(footerItem);
}
// ...
const panicDiv = document.createElement("div");
panicDiv.id = "panic";
const panicTitle = …
```
=> web: Allow the use of tsx, and refactor panic screen to use tsx

Cargo.lock
The version we're currently locking to got yankificated: https://crates.io/crates/httparse/versions
=> chore: Bump `httparse` to `v1.9.4`

web/packages/extension/manifest.json5, web/packages/extension/src/background.ts
Dual-purpose:
1) Don't register the 4399 content script if Ruffle is installed but disabled.
2) Don't show a separate permission for 4399 to avoid confusing people (see https://github.com/ruffle-rs/ruffle/discussions/16990). I tested on Firefox and it doesn't show after this PR.
Also has another benefit, which is that there's no manifest warning on Firefox versions without MAIN world support.
Ideally, the 4399 specific code could be toggled off in the extension settings, but between this and the declarativeNetRequestWithHostAccess change, at least its code doesn't generate additional permissions anymore, so I'll leave that for now. I could change the `contentScriptRegistered` function but since they're both registered at once it seems unnecessary.
Edit: Important note: this has not …
=> extension: Don't register 4399 content script if Ruffle is disabled

render/wgpu/src/context3d/current_pipeline.rs, render/wgpu/src/context3d/shader_pair.rs
This reduces number of shader recompiles in `ShaderPairAgal::compile`:
- OimoPhysics: 3/frame -> 0
- FPA4: 12/frame -> 0
This results in major (2x, 4x) fps improvements on web (tested on firefox) on a lot of Stage3D content.
On FPA4, there are still some runtime webgl shader recompiles left; that's still to be researched :(
=> wgpu: Don't use textures for shader cache keys

.github/dependabot.yml
It's completely ignoring things like new major versions, because it thinks we're a library and the default strategy for libraries is to stay semver compatible
However; the only library that we will actually publish is `ruffle-core` - which has no publicly accessible dependencies, so it's fine
Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
=> chore: Make dependabot increase version requirements for npm dependencies

core/src/avm2/globals/flash/display/Loader.as
We still need to implement the 'stop' behavior, but this should bring us closer to matching Flash Player.
=> avm2: Make 'Loader.unloadAndStop' call 'Loader.unload'

core/src/avm1/globals/text_field.rs, core/src/display_object/edit_text.rs, core/src/font.rs
Replace `round_to_pixel_half_even` and `round_down_to_pixel` with existing methods used for rounding twips to pixels.
=> core: Use existing methods for rounding twips

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml
See for changelog: https://github.com/emilk/egui/releases/tag/0.28.1
Since https://github.com/emilk/egui/pull/4641 was basically reverted by https://github.com/emilk/egui/pull/4786 to workaround https://github.com/emilk/egui/issues/4771, also disabling the default features of `egui-extras`, to not re-add `serde` and `accesskit` as indirect dependencies - we don't make use of them. This also drops `mime_guess2`, but I'm not sure this will cause any problems either. (The Ruffle logo in the About dialog still works, etc.)
=> desktop,chore: Bump `egui` to `v0.28.1`

desktop/src/gui/menu_bar.rs
egui expects most specific shortcuts to be checked first, previously <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd> would open the normal file dialog.
=> desktop: Fix open advanced shortcut

core/src/display_object/edit_text.rs
Progresses https://github.com/ruffle-rs/ruffle/issues/1891.
| Before | After |
| ------ | ----- |
| <img src="https://github.com/ruffle-rs/ruffle/assets/1507072/e11fee24-cd94-44ae-abec-09c23472d521" width="200"/> | <img src="https://github.com/ruffle-rs/ruffle/assets/1507072/23a9bf33-67d4-4dee-96aa-b762f1bcbac8" width="200"/> |
| <img src="https://github.com/ruffle-rs/ruffle/assets/1507072/845cc2fc-b030-479b-b7be-d7ae1bfa34a2" width="200"/> | <img src="https://github.com/ruffle-rs/ruffle/assets/1507072/96068edb-8235-44ad-8bae-cc4dc8c8adb1" width="200"/> |
=> core: Fix double caret rendering in justified text

core/src/avm2/activation.rs, core/src/avm2/class.rs, core/src/avm2/globals.rs, core/src/avm2/globals/function.rs, core/src/avm2/op.rs, core/src/avm2/optimize.rs, core/src/avm2/traits.rs
These depend on the class refactor. We now propagate the resulting type from `astypelate`, and convert the case of
```
findpropstrict "int"
...
callproperty "int"
```
to
```
getscriptglobals ...
...
coerceiswappop
```
(and the same applies for Number and uint). Surprisingly, calls like that made up a large portion of `callproperty`s in the box2d SWF that I use for testing:
```
FindPropStrict -> GetScriptGlobals : 62.18%
FindPropStrict -> GetOuterScope : 7.76%
FindPropStrict -> GetScopeObject : 8.24%
FindProperty -> GetOuterScope : 2.83%
FindProperty -> GetScopeObject : 94.34%
InitProperty -> SetSlot : 17.31% (-21.43%)
InitProperty -> SetSlotNoCoerce : 68.13% (+21.43%)
SetProperty -> SetSlot : 20.28% (-3.67%)
SetProperty -> SetSlotNoCoerce : 48.6% (+3.84%)
SetProperty -> CallMethod : 1.57% …
```
=> avm2: More optimizations

Cargo.lock, LICENSE.md, swf/Cargo.toml, swf/src/lib.rs, swf/src/read.rs, swf/src/write.rs, web/LICENSE.md
The 'flate2' crate already supports both C and pure Rust backends, so we don't gain anything by supporting libflate
=> swf: Remove 'libflate' feature

web/packages/extension/webpack.config.js
Fixes #15064 
The default value for Webpack `devtool` under development mode is `eval`, however, CSP `script-src: unsafe-eval` is banned from Chrome manifest v3. The PR fixes the issue by changing `devtool` to `source-map`.
=> extension: Use source-map devtool for debug build (close #15064)

tests/tests/swfs/avm1/edittext_html_swf8/test.as
That comment is obsolete after https://github.com/ruffle-rs/ruffle/pull/17056.
=> tests: Remove an obsolete comment from edittext_html_swf8

core/src/avm2/globals.rs, core/src/avm2/object.rs, core/src/avm2/vtable.rs
The Object/Function/Class fields on the global's class now correctly refer to `Object$/Function$/Class$` instead of generic `Class`. This isn't really easily observable, as they were already correctly set on the ClassObject's vtable.
Also simplified the code a little bit.
Side note: we should consider changing `TraitKind::Class` to refer to a c-class instead of an i-class. Currently it's kinda confusing which type the traits correspond to.
=> avm2: Correct setting builtins' types on classes

desktop/src/app.rs
Progresses https://github.com/ruffle-rs/ruffle/issues/17110.
This matches FP's behavior: both keyboard and mouse input should be ignored.
=> desktop: Ignore input when the context menu is open

core/src/avm2/globals/flash/desktop/NativeProcess.as, core/src/avm2/globals/flash/desktop/NativeProcessStartupInfo.as, core/src/avm2/globals/flash/filesystem/File.as, core/src/avm2/globals/flash/system/ImageDecodingPolicy.as, core/src/avm2/globals/globals.as
Fixes​ #13436 locking up when getting to the first savepoint.
Also progresses #13437 a tiny bit, it needs `File.exists` to work next.
=> avm2: Add AIR classes used by Evoland

core/src/avm2/activation.rs, core/src/avm2/value.rs
I checked that it speeds up a `vector[0] = 0; ...up to 10` microbenchmark by ~2x; will also reduce GC work, significantly if a movie relies on these kinds of accesses a lot.
This will become irrelevant for this benchmark when we optimize `setproperty` and `nextvalue` to not create strings at all, but it's a useful optimization anyway.
Created as draft as I still wanna play with it later today.
=> avm2: Use small string cache when stringifying ints < 10

core/src/backend/navigator.rs, core/src/context.rs, core/src/player.rs, frontend-utils/src/backends/navigator.rs, web/src/builder.rs, web/src/navigator.rs
We use 'wasm-bindgen-futures' as our futures executor on web, which in turn uses 'queueMicroTask'. This can result in the browser executing one of our futures while we're still inside our `requestAnimationFrame` callback (in particular, while we still have the `Player` mutex locked).
We now detect this condition by attempting the lock the Player mutex inside of our `spawn_local` future. If this fails, we `await` a `setTimeout`-based promise, which ensures that our code runs in a new top-level `setTimeout` javascript 'task' (outside of our `requestAnimationFrame` callback).
Fixes #8427
=> web: Check for locked 'Player' mutex and reschedule with setTimeout

core/src/loader.rs
This would have been helpful when debugging Dungeon Blitz
=> core: Log an error when a URLLoader load fails

.github/workflows/test_web.yml
See https://github.com/nodejs/node/issues/53902
=> ci: Temporarily pin to Node 22.4

web/Cargo.toml, web/src/builder.rs, web/src/lib.rs
This reverts commit 5441749e3e785c3a5d136bd17b55f00107f31016.
Fixes https://github.com/ruffle-rs/ruffle/issues/17155, fixes https://github.com/ruffle-rs/ruffle/issues/17162.
This functionality will be reapplied with proper virtual keyboard support in https://github.com/ruffle-rs/ruffle/pull/17158.
=> Revert "web: Use browser focus events for focus management"

web/packages/core/src/ruffle-imports.ts
I couldn't find any references to them anymore, they're probably leftovers from before a refactor (~probably~ _definitely_ #4273).
An actual test in Safari would be nice - I don't really have access to it.
=> web: Remove now unused `copyToAudioBuffer` and `getAudioOutputTimestamp`

swf/src/error.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/7945. I also added a simple test that will fail to compile if Send + Sync on swf::error::Error is accidentally lost due to future changes.
=> Make swf::error::Error implement Send + Sync

web/packages/core/src/internal/ui/container.tsx, web/packages/core/src/internal/ui/static-styles.css
This has been incorrect since https://github.com/ruffle-rs/ruffle/pull/6843. The SVG `scale` attribute only exists on \<feDisplacementMap>: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/scale
=> web: Use CSS scale attribute instead of non-existent scale property

web/packages/core/src/globals.d.ts
Apparently I don't know how this works. I need to import the old type declarations before defining new ones.
=> web: Fix globals.d.ts file type declarations

core/src/avm2/globals/string.rs, core/src/string/avm_string.rs, core/src/string/interner.rs, core/src/string/repr.rs
Small `AvmString`-related cleanups and optimisations:
- Rename `Source::Owned` to `Source::Managed`, to avoid confusion with the owned/depending distinction in `AvmStringRepr`
- Store a raw `Gc<AvmStringRepr>` instead of an `AvmString` in `AvmStringRepr`'s `owner` field; there's no reason to ever make a dependant string pointing to a static `AvmString`.
=> Small `AvmString` cleanup

CONTRIBUTING.md, core/src/avm2/activation.rs
When the `avm_debug` feature is enabled, we log all caught exceptions under the `avm_caught` target at INFO level. This is useful for debugging SWFs that catch and suppress exceptions, which can end up hiding errors from unimplemented flash APIs.
=> avm2: Add 'avm_caught' trace target to log caught exceptions

tests/tests/swfs/avm2/netstream_seek_flv/test.toml, tests/tests/swfs/avm2/stage3d_blend/test.toml, tests/tests/swfs/avm2/stage3d_raytrace/test.toml, tests/tests/swfs/from_shumway/flash_geom_ColorTransform/test.toml
Some tests were failing on my system despite producing valid results. This PR updates tolerance for their output comparison.
~~... and replaces image output of `netstream_seek_flv` with FP's original output (lets see how it performs on other platforms)~~ — that did not help, I increased tolerance instead.
=> tests: Fix some image tests failing locally

desktop/src/app.rs
=> desktop: Do not resize the window while it is maximized

core/src/backend/ui.rs, core/src/focus_tracker.rs, desktop/src/backends/ui.rs, tests/framework/src/backends/ui.rs, web/Cargo.toml, web/packages/core/src/internal/ui/static-styles.css, web/packages/core/src/ruffle-player.tsx, web/src/lib.rs, web/src/ui.rs
Reapplication of reverted https://github.com/ruffle-rs/ruffle/pull/17165, with fixed virtual keyboard.
Virtual keyboard on web is represented as an input inside the container. In order to preserve player focus when virtual keyboard is open, this PR moves the focus management to the container from the canvas. This way, when the input is focused, the container does not lose its focus.
This PR also integrates the virtual keyboard with the newly added focus management and removes Android-specific code, instead using generic logic which takes advantage of improved focus support in SWFs. It also fixes some issues related to the keyboard flickering when selecting text.
=> web: Use browser focus events for focus management, improve virtual keyboard support

Cargo.lock, desktop/Cargo.toml, desktop/src/app.rs, desktop/src/custom_event.rs, desktop/src/dbus.rs, desktop/src/gui/controller.rs, desktop/src/main.rs
The function `start_dbus_theme_watcher` detects system theme on freedesktop-compliant systems and starts a watcher which listens for changes.
Tested on GNOME and KDE, Fedora and Manjaro.
| Before | After |
| ------ | ----- |
| <image src="https://github.com/user-attachments/assets/1703164c-8cda-43c0-a619-d188298d84cd" width="300"/> | <image src="https://github.com/user-attachments/assets/d2fd71f3-a395-4b8a-85cb-1c9c6a3935ae" width="300"/> |
| <image src="https://github.com/user-attachments/assets/2cd2f4fd-c9fd-419b-9d9c-9c14f803325c" width="300"/> | <image src="https://github.com/user-attachments/assets/6a8b6106-2b53-4e78-a134-110d173bb97a" width="300"/> |
Before vs after:
https://github.com/user-attachments/assets/9d671e23-8ad5-4b33-8cb7-05b04a29cf4f
=> desktop: Detect light theme on Linux

core/src/avm2/globals/flash/display/FrameLabel.as, core/src/avm2/globals/flash/display/Stage.as, core/src/avm2/globals/flash/events/Event.as, core/src/avm2/globals/flash/events/FocusEvent.as, core/src/avm2/globals/flash/events/HTTPStatusEvent.as, core/src/avm2/globals/flash/events/TouchEvent.as, core/src/avm2/globals/flash/net/FileReference.as, core/src/avm2/globals/flash/net/NetStream.as, core/src/avm2/globals/flash/net/URLRequestDefaults.as, core/src/avm2/globals/flash/system/IME.as, core/src/avm2/globals/flash/system/LoaderContext.as, core/src/avm2/globals/flash/system/Security.as, core/src/avm2/globals/flash/system/Worker.as, core/src/avm2/globals/flash/text/TextRenderer.as, core/src/avm2/globals/flash/text/engine/TextLine.as, core/src/avm2/globals/flash/ui/GameInputControl.as, core/src/avm2/globals/flash/ui/Keyboard.as, core/src/avm2/globals/flash/ui/MouseCursorData.as, core/src/avm2/globals/flash/utils/ByteArray.as, core/src/avm2/globals/flash/utils/IDataInput2.as, core/src/avm2/globals/flash/utils/IDataOutput2.as, core/src/avm2/globals/globals.as
It's not *everything*, we have some issues remaining, but it's a pretty good chunk
-----
Remaining issues if anyone else wants to tackle those:
```
String static has extra method "fromCharCode"
```
This is *technically correct*, the worst kind of correct. Flash doesn't define it on the class, somehow. I didn't care enough to figure out why.
-----
```
flash.accessibility.AccessibilityImplementation has extra method "get_selectionActiveIndex"
flash.accessibility.AccessibilityImplementation has extra method "get_selectionAnchorIndex"
```
Should be gated behind API 736 which ruffle doesn't support 
-----
```
flash.display3D.Context3D variable "maxBackBufferWidth"'s access should be "readwrite", actually "readonly"
flash.display3D.Context3D variable "maxBackBufferHeight"'s access should be …
```
=> avm2: Fix a bunch of API mismatches (versions/base class/accessors)

desktop/assets/texts/en-US/preferences_dialog.ftl, desktop/src/app.rs, desktop/src/backends/fscommand.rs, desktop/src/backends/ui.rs, desktop/src/custom_event.rs, desktop/src/gui.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs/preferences_dialog.rs, desktop/src/gui/theme.rs, desktop/src/player.rs, desktop/src/preferences.rs, desktop/src/preferences/read.rs, desktop/src/preferences/write.rs
Related to https://github.com/ruffle-rs/ruffle/issues/17288.
This PR adds a setting for GUI theme. The default value is `System`, which matches the theme with system's theme and watches for theme changes.
The theme-related code became somewhat complicated, so I added `ThemeController` to make the code more readable.
=> desktop: Add theme preference

core/src/display_object/edit_text.rs, core/src/html.rs
This refactor makes it possible for layout boxes in the same line to have different extents, and it does not change the method's behavior.
Currently Ruffle ensures that all layout boxes within the same line have the same extent, which is wrong, as they should be aligned by their respective baselines, not their extents. This refactor makes it possible to fix that misalignment.
This is the first step of a bigger layout refactor, which in turn will make it possible to implement `screen_position_to_index` in a simpler way.
=> core: Use layout lines in `screen_position_to_index`

core/src/avm1/globals/stage.rs, core/src/avm2/globals/flash/display/stage.rs, core/src/display_object/stage.rs, core/src/player.rs, desktop/assets/texts/en-US/main_menu.ftl, desktop/assets/texts/en-US/settings.ftl, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/gui/menu_bar.rs
This PR adds the "View" menu, which is responsible for controlling the view:
1. options "100% (Unscaled)" and "Zoom to Fit" are analogous to FP's "100%" and "Show All",
2. options "Stretch to Fit" and "Crop to Fit" allow setting other scale modes which are not in FP,
3. option "Letterbox" controls letterbox rendering when "Zoom to Fit" is selected,
4. option "Full Screen" enter the full screen (as in FP),
5. option "Quality" selects the quality (as in FP, context menu does not have to be always shown).
=> desktop: Add View menu

core/src/html/layout.rs
This fixes a small regression introduced by https://github.com/ruffle-rs/ruffle/pull/17312. In some cases, having bullets or underlines in the text will negatively influence `screen_position_to_index` calculations due to their dummy bounds, and cause the result to be more off than before.
Unfortunately writing a test for that is currently very difficult, as this method (and generally laying out multiline text) is inaccurate.
=> text: Fix calculating line bounds

desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
Makes URLs more stable after merging https://github.com/ruffle-rs/ruffle/pull/11227
=> desktop: Update screenshot URLs to point to a commit

Cargo.lock, Cargo.toml, core/Cargo.toml, deny.toml, desktop/Cargo.toml, desktop/src/cli.rs, desktop/src/gui/controller.rs, desktop/src/gui/movie.rs, exporter/Cargo.toml, exporter/src/main.rs, render/wgpu/Cargo.toml, render/wgpu/src/backend.rs, render/wgpu/src/context3d/current_pipeline.rs, render/wgpu/src/descriptors.rs, render/wgpu/src/filters/bevel.rs, render/wgpu/src/filters/blur.rs, render/wgpu/src/filters/color_matrix.rs, render/wgpu/src/filters/displacement_map.rs, render/wgpu/src/filters/glow.rs, render/wgpu/src/pipelines.rs, render/wgpu/src/pixel_bender.rs, tests/README.md, tests/framework/src/options.rs, tests/tests/environment.rs, tests/tests/swfs/avm2/stage3d_raytrace/test.toml, tests/tests/swfs/avm2/stage3d_sampler_partial_upload/test.toml
Deduplicates the `base64` dependency (by dropping `ron`) and `libloading` (by updating `ash`).
I don't know how important is it to wait for the `trace` feature to be added back.
Also see the commit messages for a bit more info.
=> render,desktop: Update to `wgpu` `v22.1.0` and `egui` from `git`, remove `exclude_warp`

.github/workflows/test_rust.yml
Currently available as beta on GHA: https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/
Just want to see whether anything will break once we switch, plus whether we can clean up the tricks we did to get Lavapipe, and to tolerate SIGABRT.
A minor added benefit is that we won't lose CI if/when Launchpad is down (as has happened a couple times recently), and that nextest will alert us of genuinely flaky tests with higher probability (the retries hack won't hide them). Also, the Ubuntu jobs will be a bit faster.
Note that after merging this, the set of required checks will have to be updated by a repo admin to match.
=> ci: Run Rust tests on Ubuntu 24.04

core/src/avm1/activation.rs, core/src/avm1/globals/context_menu.rs, core/src/avm2/globals/flash/ui/context_menu.rs, core/src/context_menu.rs, core/src/player.rs
Made the context menu work on all AVM1 objects, was only the root before. 
Shows the context menu when clicking instead of releasing on desktop like flash player did.
Don't add a context menu item when there already is a item with the same caption present. (avm1)
.swf and .fla used for testing:
[context menu.zip](https://github.com/ruffle-rs/ruffle/files/14652961/context.menu.zip)
=> avm1: made the context menu work for all avm1 objects

core/src/avm2/amf.rs, core/src/avm2/globals.rs, core/src/avm2/object.rs, core/src/avm2/object/class_object.rs, core/src/avm2/object/function_object.rs, core/src/avm2/object/script_object.rs, core/src/avm2/scope.rs, core/src/avm2/script.rs, core/src/debug_ui/avm2.rs
This is required to change `ScriptObjectData.slots` from `RefLock<Vec<Value>>` to `Vec<Lock<Value>>`
=> avm2: Make ScriptObjectData vtable non-Optional

web/packages/extension/assets/_locales/en/messages.json, web/packages/extension/assets/css/options.css, web/packages/extension/assets/options.html, web/packages/extension/assets/popup.html, web/packages/extension/manifest.json5, web/packages/extension/src/background.ts, web/packages/extension/src/common.ts, web/packages/extension/src/options.ts, web/packages/extension/src/player.ts, web/packages/extension/src/popup.ts, web/packages/extension/src/utils.ts
This is based on https://github.com/w3c/webextensions/issues/460. I added feature detection. This should be tested on Chrome Beta or above.
See screencast:
[Screencast from 2024-06-28 09-56-35.webm](https://github.com/ruffle-rs/ruffle/assets/29206584/a25ef9f7-ac10-4141-9069-63f9e5273ab2)
=>  extension: Re-enable SWF takeover using declarativeNetRequest 

Cargo.lock, video/external/Cargo.toml, video/external/src/backend.rs
The video backend downloads openh264 by:
- "do we have it already"
- if no:
- download it to memory
- extract it to disk
- check md5sum to make sure all is good
But, CI runs in parallel - so multiples of these were running at once. The "do we have it already" for the second instance would return true during the extraction operation of the first, but the md5sum would obviously fail if it hasn't finished extracting.
I work around this by downloading to a temporary file and renaming it in place once extraction has finished; the temp file is adjacent to the target file, so it should be an atomic move. This way - whenever the file does exist, it's guaranteed to exist whole and valid.
=> video: Fix race condition when downloading openh264. This fixes CI flakiness.

core/src/avm2/e4x.rs
Most XML nodes are in the default namespace, which uses `None`.  This reduces the size of `E4XNodeData` on x86-64 from 152 to 120 bytes.
Supersedes #17449.
=> avm2: Box E4XNamespace in E4XNodeData

core/src/avm2/e4x.rs
This is intentionally a very minimal PR (only interns element and attribute local name), to minimize refactoring/bikeshedding and get pareto-style 80% of benefit for 20% of the work c: Any more work can be done in follow-ups.
Note that technically this isn't free in terms of time, since interning requires more passes over the string than before: first `ruffle_wstr::from_utf8_bytes` checks whether copying to a WString is needed (very unlikely, since node names are usually ascii); then second and third pass to hash it and compare in the interner. This means some XML parsing microbenchmarks can regress, but very slightly.
(though this can also improve lookups, since comparisons will fast-path on pointer equality more often)
I did a memory test with
```as
var s = "<test attr=\"1\"></test>";
s …
```
=> avm2: Intern XML node name

core/build_playerglobal/src/lib.rs, core/src/avm2/globals/README.md, core/src/avm2/globals/avmplus.as, core/src/avm2/globals/flash/filters/ColorMatrixFilter.as, core/src/avm2/globals/flash/net/URLVariables.as, core/src/avm2/globals/flash/text/engine/GroupElement.as, core/src/avm2/globals/flash/xml/XMLDocument.as, core/src/avm2/globals/globals.as
In order for asc.jar to generate efficient bytecode (a direct 'callproperty' instead of a dynamic namespace and method lookup), we need to have 'namespace AS3' in each package where we do a qualified 'obj.AS3::SomeMethod()' call.
I've adjusted `build_playerglobal` to scan all of our playerglobal method bodies to ensure that we don't have the bad bytecode. This uncovered several places where we were missing `namespace AS3'
Before this change, we were creating a new bound method within all of our prototype methods in `XML/XMLList`, since they used 'self.AS3::SomeXmlMethod()' calls to delegate to the AS3 native method.
This saves several hundred megabytes on
`https://s1106-r2game-sq.7road.net`, since we no longer create bound `FunctionObject`s for all of the distinct XML/XMLList objects that …
=> avm2: Declare 'namespace AS3' and validate bytecode in playerglobals

.config/nextest.toml, .github/workflows/test_rust.yml
I'm not saying this is a nice solution (because it's not at all), but the flaky CI annoyed me too much...
Somewhat related: https://github.com/ruffle-rs/ruffle/pull/17385
=> ci: Run nextest with profile "ci", add a test-specific override to allow retries for `avm2/pixelbender_shaderdata`

web/packages/extension/src/background.ts
This causes the browser to inject our polyfill script into iframes as well as the main document. This ensures that we can always inject the fake 'Shockwave Flash' plugin before the page's javascript has a change to check 'navigator.plugins'
This fixes an inconsistent 'Flash Player Missing' error on 7Road Wartune
=> extension: Register navigator polyfill script with allFrames: true

Cargo.lock, video/external/Cargo.toml, video/external/src/backend.rs, video/external/src/decoder/README.md
Continuation of https://github.com/ruffle-rs/ruffle/pull/17243.
We want to be better than Cisco and give our users more security by replacing MD5 with SHA256 hashes. Calculating a SHA256 hash on a safe network after verifying MD5 is a lot more secure than using HTTP+MD5 everywhere.
Thanks to @Fullmetal5 for noticing it and submitting a patch.
My comment from the commit:
> Cisco distributes the OpenH264 binaries and their MD5 hashes over HTTP.
Knowing that HTTP is insecure, MD5 hashes may easily collide,
and both are served over the same medium, saying that
this method is ridiculous is an understatement.
> 
> Take into account that these are binaries we download and execute, and
we for sure do not want to turn Ruffle into a remote code execution framework.
> 
> This patch changes MD5 to …
=> video: Check OpenH264 library downloads with SHA256 instead of MD5

core/src/avm2/globals/flash/geom/Rectangle.as
This fixes old classes that extend Rectangle and define `copyFrom` without marking it as an override
Fixes #17423
=> avm2: Add `[API("674")]` to Rectangle.copyFrom

core/src/avm2/optimize.rs
Previously, swfs with debug opcodes would never be able to use the `has_simple_scoping` optimization, since we would fail to match the getlocal0/pushscope sequence.
We now allow any number of interleaved debug opcodes when checking for this pattern.
=> avm2: Ignore debug opcodes when checking has_simple_scoping

core/src/avm2/activation.rs, core/src/avm2/method.rs, core/src/avm2/optimize.rs, core/src/avm2/verify.rs
This allows us to pretty-print a method name from within `optimize` using `display_function` (which needs to do `Gc::ptr_eq`)
=> avm2: Pass in `Gc<'gc, BytecodeMethod<'gc>>` to `optimize`

web/packages/core/src/internal/player/ruffle-player-element.tsx, web/packages/selfhosted/test/integration_tests/external_interface/test.ts
Noticed the error here: https://github.com/ruffle-rs/ruffle/issues/16492#issuecomment-2276380003
Realistically it's just noise though, because we're replacing the method with the same method (a "call a callback by the name of foo"), so it works out anyway. This silences the warning by making the property configurable (aka "it can be redefined")
=> web: Fix logged error when defining an ExternalInterface method twice

core/src/avm2/globals/flash/display/BitmapData.as, core/src/avm2/globals/flash/display/Graphics.as, core/src/avm2/globals/flash/display/GraphicsPath.as, core/src/avm2/globals/flash/display3D/textures/CubeTexture.as, core/src/avm2/globals/flash/display3D/textures/RectangleTexture.as, core/src/avm2/globals/flash/display3D/textures/Texture.as, core/src/avm2/globals/flash/media/Camera.as, core/src/avm2/globals/flash/media/Sound.as, core/src/avm2/globals/flash/net/NetStream.as
Dinnerbone's list - https://gist.github.com/Dinnerbone/0cfad60f4587292005d41e566368c709
except one - "String static has extra method "fromCharCode"
=> avm2: Added all missing `[API()]` to methods from the list

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, Cargo.lock, Cargo.toml, web/README.md, web/docker/Dockerfile
Have to keep things consistent by hand with this one.
https://github.com/rustwasm/wasm-bindgen/blob/main/CHANGELOG.md#0293
=> chore: Update to wasm-bindgen 0.2.93

Cargo.lock, deny.toml, desktop/Cargo.toml, desktop/src/app.rs, desktop/src/gui.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs.rs, desktop/src/gui/dialogs/bookmarks_dialog.rs, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/gui/widgets.rs, desktop/src/util.rs
Related to https://github.com/ruffle-rs/ruffle/issues/11336 a bit.
This patch makes sure that all file pickers are children of Ruffle. This way, file pickers will hover over the main window and will have to be dismissed before the user may interact with it.
Related functionality added in rfd:
* https://github.com/PolyMeilex/rfd/pull/209
=> desktop: Set main window as parent of file pickers

core/src/avm1/property_decl.rs, core/src/string/avm_string.rs, core/src/string/interner.rs, core/src/string/repr.rs
Allows `&'static WStr`s to be converted into interned `AvmString`s without moving the string data into an heap-allocated buffer.
Slight progress towards getting rid of static `AvmString`s altogether :)
=> Managed `AvmStringRepr`s can now point to a `&'static WStr`

desktop/src/app.rs, desktop/src/gui/menu_bar.rs
This PR removes <kbd>Alt</kbd>+<kbd>Enter</kbd> as the shortcut and replaces it with <kbd>F11</kbd>, additionally the shortcut hint is added to the menu.
=> desktop: Use F11 as fullscreen shortcut

.config/nextest.toml
Since https://github.com/ruffle-rs/ruffle/pull/17574 haven't worked out (yet)...
Let's try "fixing" the Rust test flakyness this way.
=> ci: Allow more retries, for the `avm2/graphics_round_rects` test too

core/src/avm2/globals/flash/display/GraphicsPath.as
Turns out, the docs were wrong again.
Making right the amendment I made at https://github.com/ruffle-rs/ruffle/pull/17523#discussion_r1720849567.
My apologies for doubting you, @MartySVK.
=> avm2: Fix GraphicsPath.cubicCurveTo() [API()] version

core/src/player.rs, desktop/assets/texts/en-US/context_menu.ftl, desktop/src/app.rs, desktop/src/custom_event.rs, desktop/src/gui.rs, desktop/src/gui/context_menu.rs
This option allows the user to exit full screen without knowing the <kbd>Esc</kbd> shortcut.
=> desktop: Add "Exit Full Screen" option to context menu

core/src/debug_ui/avm1.rs
Changing object properties can be useful for helping debugging games, or just cheating/general messing around.
Also adds a filter to quickly find fields of interest.
Todo
AVM2 debug ui code would require significant changes to add editing support, and I want to keep this pull request fairly simple. Perhaps a followup/intermediate step would be some refactoring and unification work on the AVM1 and AVM2 debug UI code.
Screenshot of what it looks like:
=> [AVM1 debug ui] Make some object properties editable

core/src/avm2/globals/flash/system/Capabilities.as, core/src/avm2/globals/flash/system/capabilities.rs
This is my alternative suggestion for #17517 @Mesteery that keeps reporting the OS as windows for FlashPlayer (so not AIR) usage.
=> avm2: For AIR report the correct OS in flash.system.Capabilities

Cargo.lock, Cargo.toml, desktop/Cargo.toml, web/Cargo.toml
This makes sure there's only one version of `rfd` used and fixes Flatpak compilation issues.
```
error: checksum for `rfd v0.14.1` could not be calculated, but a checksum is listed in the existing lock file
this could be indicative of a few possible situations:
* the source `registry `crates-io`` supports checksums,
but was replaced with one that doesn't
* the lock file is corrupt
unable to verify that `rfd v0.14.1` is the same as when the lockfile was generated
```
=> chore: Move rfd dependency to workspace

.github/workflows/release_nightly.yml
Should match https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token and these permissions, except for `id-token`:
=> ci: Set most GITHUB_TOKEN permissions back to defaults

desktop/src/app.rs, desktop/src/backends/fscommand.rs, desktop/src/custom_event.rs, desktop/src/player.rs
Previously the fullscreen state was set on the window directly causing a desync with the rest of the player code.
Fixes #17617
=> desktop: Change fullscreen fscommand to use event loop events

.github/workflows/release_nightly.yml
Follow-up for: https://github.com/ruffle-rs/ruffle/pull/17618 https://github.com/ruffle-rs/ruffle/pull/17629 https://github.com/ruffle-rs/ruffle/pull/17322
See: https://github.com/ruffle-rs/ruffle/actions/runs/10537036436/job/29197923957#step:11:15
=> ci: Grant write permission for contents to nightly web build job

desktop/src/app.rs, desktop/src/gui.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs.rs, desktop/src/gui/dialogs/bookmarks_dialog.rs, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/gui/picker.rs, desktop/src/gui/widgets.rs, desktop/src/util.rs
With asynchronous file picking, the user may open multiple file pickers by accident or thinking that the previous click did not work when the picker takes significant time to open. This PR prevents that situation by disallowing multiple picker instances.
This PR shares one commit with https://github.com/ruffle-rs/ruffle/pull/17604.
=> desktop: Allow only one file picker open at a time

Cargo.lock, desktop/Cargo.toml, frontend-utils/Cargo.toml
Made possible by: https://github.com/bkchr/proc-macro-crate/pull/52
=> chore: Update to `proc-macro-crate` `v3.2.0`, deduplicate `toml_edit` and `winnow`

Cargo.lock
_beep boop_ :broom: :robot: :notes:
=> chore: Bump some locked crate versions, deduplicate `nix`, move away from yanked `bytes` version

core/src/avm2/e4x.rs, tests/tests/swfs/from_avmplus/e4x/XML/kXMLMarkupMustBeWellFormedErr/test.toml
I am frankly not sure why this weird case needs a special error, but whatever.
=> avm2: Throw special XML parsing error for unmatched end tag at the root level

core/src/avm2/globals/flash/display/DisplayObject.as, core/src/avm2/globals/flash/display/InteractiveObject.as, core/src/avm2/globals/flash/display/Sprite.as, core/src/avm2/globals/flash/display/Stage.as, core/src/avm2/globals/flash/events/Event.as, core/src/avm2/globals/flash/events/HTTPStatusEvent.as, core/src/avm2/globals/flash/events/MouseEvent.as, core/src/avm2/globals/flash/events/PressAndTapGestureEvent.as, core/src/avm2/globals/flash/events/VideoTextureEvent.as, core/src/avm2/globals/flash/net/Socket.as, core/src/avm2/globals/flash/system/JPEGLoaderContext.as, core/src/avm2/globals/flash/system/LoaderContext.as, core/src/avm2/globals/flash/text/TextField.as, core/src/avm2/globals/flash/text/engine/FontMetrics.as, core/src/avm2/globals/flash/text/engine/LineJustification.as
Dinnerbone's list - https://gist.github.com/Dinnerbone/0cfad60f4587292005d41e566368c709
- I could not find a lot of "metaData" variables
Plus some others I discovered randomly.
=> avm2: Added missing `[API()]` to variables from the list

Cargo.lock, core/Cargo.toml, core/src/avm2/function.rs, desktop/Cargo.toml, desktop/src/main.rs, desktop/src/tracy.rs
Now supports/requires tracy 0.11.0
With the new `avm2_profile` feature, AVM2 callstack is visible in tracy.
=> desktop: Update tracy + add avm2 calls

desktop/assets/texts/en-US/message_dialogs.ftl, desktop/src/app.rs, desktop/src/backends/navigator.rs, desktop/src/backends/ui.rs, desktop/src/custom_event.rs, desktop/src/gui.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs.rs, desktop/src/gui/dialogs/message_dialog.rs, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/player.rs
This PR implements MessageDialog in egui and replaces some usages of rfd with it. It provides the following improvements:
1. current dialogs do not have parent/child relationship with Ruffle, the newly added MessageDialog uses egui which renders over the content,
2. when opening a dialog Ruffle is now responsive,
3. dialogs are internationalized,
4. message dialogs are now consistent with other dialogs.
<image width="400" src="https://github.com/user-attachments/assets/399bb5d0-38e4-4b51-b2c5-dd6f8633306e"/>
=> desktop: Implement message dialogs in egui

.github/workflows/test_rust.yml, core/build_playerglobal/src/lib.rs, core/src/avm2/optimize.rs
Unfortunately nextest does not support doctests yet (https://github.com/nextest-rs/nextest/issues/16), they need to be run using cargo test.
This adds ~10s on Linux and macOS and ~15s on Windows.
=> ci: Fix failing doctests and run them in CI

Cargo.lock, core/Cargo.toml
To pull in https://github.com/ruffle-rs/rust-flash-lso/pull/66.
=> chore: Bump `rust-flash-lso` dependency to latest `master`

core/src/avm2/class.rs, core/src/avm2/e4x.rs, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/int.rs, core/src/avm2/globals/namespace.rs, core/src/avm2/globals/object.rs, core/src/avm2/globals/uint.rs, core/src/avm2/globals/xml.rs, core/src/avm2/globals/xml_list.rs, core/src/avm2/method.rs, core/src/avm2/multiname.rs, core/src/avm2/namespace.rs, core/src/avm2/object/function_object.rs, core/src/avm2/object/qname_object.rs, core/src/avm2/object/xml_list_object.rs, core/src/avm2/property.rs, core/src/avm2/script.rs, core/src/avm2/specification.rs, core/src/avm2/vtable.rs
`Namespace` now holds a `Option<Gc<_>>` internally, with `None` representing the Any namespace.
This is closer to how avmplus represents namespaces internally (they use a `NULL` pointer for the Any case), and allows creating the Any namespace without a `&Mutation<'gc>`.
=> avm2: Do not allocate for `Namespace::any()`

.github/workflows/release_nightly.yml
Fixes a whoopsie introduced in https://github.com/ruffle-rs/ruffle/pull/17429.
The `sha512sum` command hidden within a subshell required to be executed in the repo root directory.
See:
* https://github.com/ruffle-rs/ruffle/actions/runs/10729997045/job/29758052349#step:7:5
* https://aur.archlinux.org/cgit/aur.git/commit/?h=ruffle-nightly-bin&id=930e21a846965df8fef8e39d2932bf94a1f23f16
=> ci: Fix missing checksum in AUR package

core/src/avm2/specification.rs
Fixup for https://github.com/ruffle-rs/ruffle/pull/17771, will probably fix https://github.com/ruffle-rs/ruffle/issues/17783.
=> core: fix: Revert an accidental condition negation in AVM2 stub reporting

desktop/assets/texts/en-US/network_access_dialog.ftl, desktop/src/backends/navigator.rs, desktop/src/gui/dialogs.rs, desktop/src/gui/dialogs/network_access_dialog.rs
Add network access dialog written in egui and replace rfd's socket confirmation with it.
<image width="400" src="https://github.com/user-attachments/assets/ae3e1286-12bb-4eb3-bab5-337a76822757"/>
=> desktop: Add network access dialog

.github/workflows/release_nightly.yml
This is useful for downstream binary distributions as they can now use the official logo, metainfo, and desktop file when installing Ruffle instead of creating their own or checking out sources.
=> ci: Package Ruffle logo, desktop file, and metainfo for Linux

Cargo.lock, Cargo.toml
This fixes filters in XDG portals and allows showing files without an extension.
Fixes https://github.com/ruffle-rs/ruffle/issues/17776.
=> deps: Bump RFD to the newest revision

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, web/docker/Dockerfile
Came out yesterday: https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v119
=> chore: Bump Binaryen to version 119

CONTRIBUTING.md
Change `-compiler.debug` to `-debug` to make it work in PowerShell.
It gets tripped up by the period in the argument name.
Change `-output` to `-o` to make it shorter.
Make note of the capitalisation of the file name.
It won't compile unless the casing matches that of the class name's.
=> docs: Correct Apache Flex SDK compiling guide

core/src/xml/tree.rs
For a regex
```as
new XML('<data><a x="0" y="0" w="0" h="0">data</a> (repeated 25 times) </data>');
```
This speeds up my microbenchmark by 4-5x.
=> xml: Cache regex in custom_unescape

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/debug_ui/display_object.rs, core/src/debug_ui/domain.rs, core/src/debug_ui/movie.rs, deny.toml, desktop/Cargo.toml, desktop/src/app.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/gui/dialogs/preferences_dialog.rs, desktop/src/util.rs
Still needs some cleanup and porting and migrating away from deprecated stuff to the new and shiny new trait-based APIs I think.
~~Not latest minor version, because:~~
~~https://github.com/emilk/egui/pull/4849#issuecomment-2258111041~~
~~But soon it probably can be:~~
~~https://github.com/rust-windowing/winit/pull/3849~~
Supersedes https://github.com/ruffle-rs/ruffle/pull/16835.
=> core,desktop: Update to `winit` `v0.30.5` and latest `egui` from git

desktop/assets/texts/en-US/file_picker.ftl, desktop/src/gui/dialogs.rs, desktop/src/gui/picker.rs
This PR adds internationalization to strings in file pickers and improves a bit their filters.
=> desktop: Internationalize file pickers & improve filters

Cargo.lock
=> chore: Bump `wayland-*` dependencies, drop duplicate `quick-xml` version `0.34.0`

core/src/avm2.rs, core/src/avm2/class.rs, core/src/avm2/globals.rs, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/int.rs, core/src/avm2/globals/object.rs, core/src/avm2/globals/uint.rs, core/src/avm2/method.rs, core/src/avm2/multiname.rs, core/src/avm2/object/function_object.rs, core/src/avm2/property.rs, core/src/avm2/script.rs, core/src/avm2/traits.rs, core/src/avm2/vtable.rs
Return types, slot types, and parameter types are all behind Gcs now. To avoid recreating the same Multiname several times while adding traits to classes, a `CommonMultinames` structure storing some common multinames has been added to `Avm2`.
=> avm2: Put more Multinames behind a Gc

desktop/packages/linux/aur/ruffle-nightly-bin/PKGBUILD
This most importantly adds a way of opening Ruffle using GUI.
Tested on Manjaro GNOME, would appreciate if someone else also tested it!
=> desktop: Install Ruffle metadata in PKGBUILD

Cargo.lock, desktop/src/player.rs, tests/framework/src/options.rs, video/external/Cargo.toml, video/external/src/backend.rs, video/external/src/decoder/openh264.rs, video/external/src/decoder/openh264_sys.rs
Some systems do have OpenH264 installed and in order to get rid of the delay caused by downloading the library (and needlessly downloading it in the first place), an attempt is made first to load OpenH264 as a system library. When loading fails (or version is mismatched), only then Ruffle downloads OpenH264 and uses that version of the library.
This also will make it possible to support OpenH264 in Flatpak.
=> video: Prefer loading system OpenH264 library to downloading it

.github/workflows/release_nightly.yml
Reverts ruffle-rs/ruffle#17810
Merge once the Vector.sort situation is _sorted out_.
=> Revert "build: Freeze rustc for nightly builds to 1.80.1"

desktop/src/main.rs
Renamed in Rust 1.81.0, see https://releases.rs/docs/1.81.0/#compatibility-notes
CC @torokati44
=> chore: Use PanicHookInfo instead of PanicInfo

core/src/avm2/activation.rs, core/src/avm2/class.rs, core/src/avm2/error.rs, core/src/avm2/method.rs, core/src/avm2/multiname.rs, core/src/avm2/namespace.rs, core/src/avm2/property.rs, core/src/avm2/qname.rs, core/src/avm2/script.rs, core/src/avm2/traits.rs, core/src/avm2/value.rs, core/src/avm2/verify.rs
This requires passing around an Activation in some places. The PR also adds better verification for `Class` and slot names.
`Any` namespaces can now only be found in Multinames with a `NamespaceSet::Single`.
=> avm2: Return actual VerifyErrors for constant pool errors

core/src/avm2/globals/array.rs, core/src/avm2/globals/vector.rs
=> avm2: Also use avmplus' qsort in `Vector.sort`

desktop/packages/linux/rs.ruffle.Ruffle.desktop, desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
1. Change order of categories. — Apparently the order matters when desktop environments decide to include the app only in one category. It seems that we should list more important categories first.
2. Add `VectorGraphics` Freedesktop category — Ruffle handles SWF files, which are generally vector graphic animations.
=> desktop: Update Freedesktop categories

desktop/src/app.rs, desktop/src/backends/ui.rs, desktop/src/gui/picker.rs, desktop/src/gui/widgets.rs, desktop/src/player.rs
This improves the experience of picking files from AS, as the pickers will now be properly integrated with Ruffle (child/parent relationship + making sure only one picker is present at any moment).
=> desktop: Use FilePicker for picking files in ActionScript

core/src/avm2/object/loaderinfo_object.rs, core/src/display_object.rs, core/src/display_object/movie_clip.rs, core/src/frame_lifecycle.rs, core/src/loader.rs
This removes the need to traverse the entire display object tree - we instead just try to fire events (when ready) on corresponding `MovieClip`s for our `Loader::Movie` instances
=> core: Replace `on_exit_frame` with iteration over Loaders

desktop/packages/linux/rs.ruffle.Ruffle.desktop, desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
As per the documentation [1,2], Ruffle hardly fits in this category.
[1] https://specifications.freedesktop.org/menu-spec/latest/category-registry.html#main-category-registry
[2] https://specifications.freedesktop.org/menu-spec/latest/additional-category-registry.html
Please share your thoughts about this change. See also https://github.com/ruffle-rs/ruffle/pull/17909#issuecomment-2351176256, https://github.com/ruffle-rs/ruffle/pull/17909#issuecomment-2351649359
CC @evilpie
=> desktop: Remove Utility Freedesktop category

desktop/src/main.rs
Logs are non-essential and can be removed, contrary to config files. This PR changes the log directory from config dir to cache dir.
| Platform | Old Path | New Path |
| -------- | -------- | -------- |
| Linux    | `~/.config/ruffle/*.log` | `~/.cache/ruffle/log/*.log` |
|macOS     | `~/Library/Application Support/ruffle/*.log` | `~/Library/Caches/ruffle/log/*.log` |
| Windows  | `C:\Users\Alice\AppData\Local\ruffle\*.log` | `C:\Users\Alice\AppData\Local\ruffle\log\*.log` |
Old log files will be migrated to the new path on startup.
=> desktop: Do not store logs in config directory

core/src/avm2/globals/flash/system/capabilities.rs, render/wgpu/src/backend.rs
Fix a few instances of `target_os = "macos"`. Required for https://github.com/madsmtm/ruffle-ios.
=> chore: Improve iOS support

core/src/bitmap/bitmap_data.rs, core/src/bitmap/operations.rs
This removed repeated range checks on each pixel, replacing them by possibly-memcpy.
I originally only added `set_pixel32_row_raw`, which improved 640x480 fills by 3x (FF) - 5x (desktop).
Then I tried adding a full-fill fast path, which (as expected) didn't do a noticeable difference on desktop, but somehow improved FF times by another 2x.
~~EDIT: I just remembered that I tested browser perf without wasm extensions, but bulk-memory might also do a difference here. Will check it soon.~~
With wasm-opt and bulk-memory enabled, the line-fill path and full-fill path are equally fast, and another 2x faster than the best result without extensions. Just slightly slower than desktop now (though weirdly, the FF profiler doesn't show `memory.fill` like it used to).
This only helps the CPU side, it …
=> core: Optimize BMD.fillRect()

core/src/avm2/class.rs, core/src/avm2/domain.rs, core/src/avm2/function.rs, core/src/avm2/globals.rs, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/int.rs, core/src/avm2/globals/object.rs, core/src/avm2/globals/uint.rs, core/src/avm2/method.rs, core/src/avm2/multiname.rs, core/src/avm2/object/function_object.rs, core/src/avm2/object/xml_object.rs, core/src/avm2/property.rs, core/src/avm2/script.rs, core/src/avm2/specification.rs, core/src/avm2/traits.rs, core/src/avm2/verify.rs, core/src/avm2/vtable.rs
For example, we now throw a class lookup VerifyError ("`Class *::* could not be found`") when trying to call a method with return type `QName(null, null)` instead of incorrectly assuming that the name is the Any name.
This removes the `any` Multiname from `CommonMultinames`.
=> avm2: Correctly differentiate between Any and null Multiname

Cargo.lock, Cargo.toml, desktop/Cargo.toml, desktop/src/backends.rs, desktop/src/player.rs, frontend-utils/Cargo.toml, frontend-utils/src/backends.rs, frontend-utils/src/backends/audio.rs
Required for https://github.com/madsmtm/ruffle-ios.
=> desktop: Move `cpal` audio backend to `frontend-utils`

Cargo.toml, desktop/Cargo.toml, desktop/src/player.rs, render/canvas/Cargo.toml, render/webgl/Cargo.toml, render/wgpu/Cargo.toml, tests/framework/Cargo.toml, tests/framework/src/options.rs, video/external/Cargo.toml, video/external/src/backend.rs, video/external/src/decoder.rs, video/external/src/decoder/openh264.rs, web/Cargo.toml
This is the first (more ready and conflicty, but less risky and controversy) part of https://github.com/ruffle-rs/ruffle/pull/16794 split out. The rest can be more or less additive after this, once I finally get back to it.
I know that `external_video` itself is already a blanket feature that disables this; and having that enabled, but `openh264` not, is somewhat silly, but ... bear with me? :grinning:
=> video/external: Make OpenH264 support optional at build time

desktop/src/gui/theme.rs
This fixes the following warning on macOS & Windows (and probably others that we do not build for here).
```
warning: unused import: `futures::StreamExt`
--> desktop/src/gui/theme.rs:5:5
|
5 | use futures::StreamExt;
|     ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `ruffle_desktop` (bin "ruffle_desktop" test) generated 1 warning (run `cargo fix --bin "ruffle_desktop" --tests` to apply 1 suggestion)
```
=> chore: Fix compilation warnings on non-Linux

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/gui/theme.rs
Aiming to fix https://github.com/ruffle-rs/ruffle/issues/17986.
Please verify, @kjarosh.
=> desktop: Bump `egui` to latest `master`, set theme instead of visuals

desktop/src/gui/dialogs/open_dialog.rs
This replaces the letter x with the trash can emoji, which looks nicer (IMO) and has clearer semantics.
| Before | After |
| ------ | ----- |
| <image src="https://github.com/user-attachments/assets/e6d13f50-8394-40b7-89fd-84217742b6d2" width="300"/> | <image src="https://github.com/user-attachments/assets/5d4c34e8-8433-4f2c-b045-d2456e960a79" width="300"/> |
=> desktop: Use trash can emoji on remove buttons

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml
Following https://github.com/ruffle-rs/ruffle/pull/17987, to pull in https://github.com/emilk/egui/pull/5133, fixing https://github.com/emilk/egui/issues/5132.
Cc: @kjarosh
=> desktop: Bump `egui` to latest `master` (again)

web/packages/selfhosted/test/js_api/exposed.ts
This test ensures we notice when accidentally adding or removing something from the public RufflePlayer API.
=> tests: Test exposed RufflePlayer API

web/packages/core/src/internal/player/inner.tsx
Before, the panic screen just said:
"Failed to load Ruffle WASM": https://github.com/ruffle-rs/ruffle/issues?q=is%3Aissue+is%3Aopen+%22Failed+to+load+Ruffle+WASM%22
The only LoadRuffleWasmError that should produce a report bug button is a TypeError I believe, but we can't really be sure that's working properly with this issue in place. Often when there's a TypeError it does mean the website is redefining a global so often there is nothing we can do, but sometimes we may be able to work around such instances if they are common enough and the workaround is simple enough, which is why the report button appears.
See the LoadRuffleWasmError constructor: it has a cause which is itself an error, so we should report on that: https://github.com/ruffle-rs/ruffle/blob/master/web/packages/core/src/int …
=> web: Show the original cause of the error when Ruffle fails to load

Cargo.lock, Cargo.toml, deny.toml
Changelog: https://github.com/PolyMeilex/rfd/releases/tag/0.15.0
=> chore: Switch to `rfd` release `v0.15.0` from git

desktop/src/gui/menu_bar.rs
Previously <kbd>Alt</kbd>+<kbd>Enter</kbd> was a hidden shortcut that was used to toggle full screen, and it is used by Flash Player to toggle full screen on Windows too.
As Windows users sometimes expect this shortcut to work, this patch brings it back as a hidden shortcut (until we add some kind of preferences).
CC @n0samu
=> desktop: Add Alt+Enter back as a hidden shortcut on Windows

.github/workflows/test_web.yml
Split out of https://github.com/ruffle-rs/ruffle/pull/16352 due to problems with Edge WebDriver discussed therein.
=> ci: Run Web tests on Ubuntu 24.04

Cargo.lock
Since https://github.com/ruffle-rs/ruffle/pull/18048 got replaced by https://github.com/ruffle-rs/ruffle/pull/18065 after https://github.com/toml-rs/toml/pull/788, this is just a careful `Cargo.lock` bump now.
=> chore: Bump some indirect dependencies in `Cargo.lock`

core/src/bitmap/operations.rs
Verified that it fixes https://github.com/ruffle-rs/ruffle/issues/17964 . Hopefully should fix most/all of "dimension X is zero" in applyFilter.
I don't know whether this is the best place (it can be done a layer above and below, and after more clamping). @Dinnerbone can you please check it out?
=> core: Make applyFilter with zero-sized rects noops

.github/workflows/download_translations.yml, crowdin.yml
The Crowdin action does not allow adding custom modifications after downloading the translations and before creating the PR. Created the PR manually we can now modify files before creating the PR.
Additionally this PR reformats `crowdin.yml`.
This is a first step of automating localization of metainfo & .desktop file.
=> ci: Commit translations and create PR manually

.github/workflows/release_amo.yml, .github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml
Since the `ubuntu-latest` alias now means the latter, I think it's time.
https://github.com/actions/runner-images/#available-images
https://github.com/actions/runner-images/issues/10636
=> ci: Switch all remaining GHA workflows from ubuntu-22.04 to ubuntu-24.04

desktop/assets/texts/en-US/filesystem_access_dialog.ftl, desktop/src/backends/navigator.rs, desktop/src/cli.rs, desktop/src/gui/dialogs.rs, desktop/src/gui/dialogs/filesystem_access_dialog.rs, desktop/src/player.rs, frontend-utils/src/backends/navigator.rs, frontend-utils/src/content.rs
This is an attempt to address the issue of movies having unrestricted filesystem access.
When a movie wants to access a local file, a dialog is shown which asks for permission. They user may allow access to the file or to one of the parent directories.
<image src="https://github.com/user-attachments/assets/52a961d2-9b8c-449d-b6e7-112ba3129331" width="500"/>
This behavior can be changed with:
* `--filesystem-access-mode allow`
* `--filesystem-access-mode deny`
* `--filesystem-access-mode ask` (default)
Comments and suggestions are welcome!
=> desktop: Add filesystem access dialog

Cargo.lock, Cargo.toml, core/Cargo.toml, deny.toml, desktop/Cargo.toml, desktop/src/gui/controller.rs, desktop/src/gui/movie.rs
Fresh out of the oven: https://github.com/emilk/egui/releases/tag/0.29.0 :bread:
~~We weren't that far behind already, so no significant changes expected.~~ EDIT: Spoke too soon...
=> chore: Switch `egui` back to release `0.29.0` from git

web/package-lock.json
This should resolve https://github.com/ruffle-rs/ruffle/security/dependabot/82 (CVE-2024-47068).
=> chore: Bump the `rollup` npm package to `4.22.5`

desktop/assets/texts/hu-HU/filesystem_access_dialog.ftl, desktop/assets/texts/ko-KR/filesystem_access_dialog.ftl, desktop/packages/linux/rs.ruffle.Ruffle.desktop, desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
New Crowdin pull request with translations 🎉
=> chore: Update translations

desktop/src/backends.rs, desktop/src/backends/navigator.rs, desktop/src/gui/dialogs/filesystem_access_dialog.rs
This patch fixes the following two issues:
1. On Windows the allowed path check was not always working, due to Windows paths being Windows paths, now paths are canonicalized before comparison.
2. On some systems the dialog was not rendered when the main SWF wasn't loaded, and the dialog was not able to allow the main SWF. Now the dialog allows the SWF instantly when constructed.
That needs testing from @n0samu and @Lord-McSweeney, as I cannot reproduce these issues.
Fixes https://github.com/ruffle-rs/ruffle/issues/18141, fixes https://github.com/ruffle-rs/ruffle/issues/18142.
=> desktop: Fix filesystem access dialog

web/src/lib.rs, web/src/ui.rs
This patch introduces `WebUiBackend::set_clipboard_content_buffer` which is able to set the clipboard buffer without also setting the clipboard. This method is then used in places where Ruffle is notified about a paste event, so that it doesn't have to set the clipboard to the same value.
This fixes a borrow checker error during pasting.
This does not (yet) fix the context menu pasting issue.
=> web: Don't set the clipboard when notified about clipboard change

web/packages/extension/src/background.ts
I think this is the cause of the issue described here: https://github.com/ruffle-rs/ruffle/discussions/18161#discussioncomment-10846127
I mentioned this briefly on Discord: When you use Ruffle on a browser without support for a responseHeaders RuleCondition that later gets support, Ruffle has already set this value to true. I assumed that we could just default to false if it wasn't set and that would be fine, but then in this situation it just stays true indefinitely.
=> extension: Set responseHeadersUnsupported to false explicitly

crowdin.yml
Previously if a string changed, all translations get removed.
With this, they'll stay - but it'll unapprove the translations as they may not be strictly accurate anymore.
=> chore: Preserve translations (but unapprove them) when strings change

Cargo.lock, deny.toml, desktop/Cargo.toml
See:
https://github.com/bilelmoussaoui/ashpd/pull/240
https://github.com/bilelmoussaoui/ashpd/releases/tag/0.9.2
Thanks for you patches, @kjarosh!
=> chore: Bump `ashpd` to `0.9.2`, deduplicating it

desktop/src/app.rs, desktop/src/main.rs
This is one of the TODOs from #17401
Needs testing please! Largest change is to ControlFlow (specifically, how often we redraw things). In the previous update model, we'd force it to wait until the next frame time after every event we receive. Now, we conditionally do it at the end of a batch of events.
There's still another pending TODO (make the window later, instead of before event loop) - but that's a larger and messier change.
We can also clean up the ControlFlow usage further by using a callback in egui, but I didn't want to risk more changes than needed.
=> desktop: Migrate to winit 0.30's ApplicationHandler

.gitignore, Cargo.lock, core/Cargo.toml, core/src/avm1/globals/netconnection.rs, core/src/avm1/globals/shared_object.rs, core/src/avm2/amf.rs, core/src/avm2/array.rs, core/src/avm2/globals/flash/net/net_connection.rs
This constitues the ruffle-side changes of https://github.com/ruffle-rs/rust-flash-lso/pull/67 and https://github.com/ruffle-rs/rust-flash-lso/pull/68. 
This fixes the following (previously would panic on load): 
https://github.com/ruffle-rs/ruffle/issues/17902 - loads
https://github.com/ruffle-rs/ruffle/issues/17709 - loads
https://github.com/ruffle-rs/ruffle/issues/13748 - loads
https://github.com/ruffle-rs/ruffle/issues/10520 - loads
This prevents panics on the following:
https://github.com/ruffle-rs/ruffle/issues/17782 - (and possible dupe https://github.com/ruffle-rs/ruffle/issues/17336 )
Now errors with "Property uploadFromBitmapData not found on flash.display3D.textures.RectangleTexture and there is no default value."
https://github.com/ruffle-rs/ruffle/issues/14329
Fails to load …
=> core: Fix "Failed to get Object" panics

desktop/src/app.rs, desktop/src/gui/controller.rs
This resolves the remaining TODO from #17401
Winit wants us to create the window after the event loop starts, and that wasn't very easy - but here we are.
Kindly requesting that someone tests on Wayland & X11 to make sure it's fine still :D
=> desktop: Create the window after the event loop

core/src/avm2/globals.rs, core/src/avm2/globals/flash/display3D/context_3d.rs, render/wgpu/src/context3d/mod.rs
This still needs a test, but I'm planning to add that in a follow-up PR
Fixes https://github.com/ruffle-rs/ruffle/issues/15487
=> Implement surfaceSelector in Context3D.setRenderToTexture

core/src/avm1/globals/movie_clip.rs, core/src/display_object/graphic.rs, core/src/display_object/movie_clip.rs, core/src/drawing.rs, core/src/font.rs
All `MovieClip`s (and `Graphic`s) logically have a `Drawing` (that can be manipulated by ActionScript), but most of these stay empty.
This does two things:
- avoid registering `ShapeHandle`s for empty drawings;
- box and lazily allocate drawings inside `MovieClip`s and `Graphic`s.
Thanks to @adrian17 for notifying this inefficiency!
=> core: Do not allocate or render empty `Drawing`s

desktop/src/player.rs
This makes sure the warning is logged only when someone tries explicitly enabling GameMode.
=> desktop: Do not warn about GameMode on non-Linux unless explicitly enabled

core/src/display_object.rs, render/src/commands.rs
Noticed on `The Last Stand: Union City` that it tries to draw out-of-frame street lights; the draw is culled, but the blending logic doesn't know that.
This won't improve max FPS if everything is in frame, but should save some GPU resources when there's blended stuff out of frame.
=> render: Skip blending if there's nothing to draw

web/package-lock.json
This should resolve https://github.com/advisories/GHSA-pxg6-pf52-xh8x (CVE-2024-47764 ).
=> chore: Bump the `express` and `cookie` npm packages

core/src/debug_ui/display_object.rs, core/src/display_object.rs, core/src/display_object/edit_text.rs
Displaying all at once would be a mess, so this patch adds a way of enabling and disabling specific types of layout debug boxes.
Hopefully we'll be able to reduce the number of different kinds of bounds soon, but unless it's done, displaying any of them is very useful for debugging.
=> debug_ui: Improve layout debug boxes

desktop/src/util.rs
Flash Player maps non-ASCII input characters to key codes equal to their respective Unicode code points.
=> desktop: Support key codes for non-ASCII characters

core/src/display_object/edit_text.rs, core/src/html/layout.rs
This refactor simplifies existing code and makes it easier to write code related to character positions (evaluating a font each time is not needed anymore).
=> text: Calculate character positions during relayout

.github/workflows/download_translations.yml, .github/workflows/upload_texts.yml
This stops GitHub from wasting our time by messing around with `ubuntu-latest`.
=> chore: Use `ubuntu-24.04` for Crowdin actions

web/packages/extension/manifest.json5, web/packages/extension/src/background.ts
My organization uses https://outlook.office.com secured by Duo Security, and they use Duo Security's check for Flash installation to ensure you don't log in with Flash installed. Unfortunately or fortunately depending on how you look at it, Ruffle is detected as Flash. We can't avoid that without fooling fewer plugin detection scripts used to enable Flash content, so we instead have to disable Ruffle on this site.
=> extension: Disable Ruffle on Duo Security

desktop/src/app.rs, desktop/src/gui.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs.rs, frontend-utils/src/backends/navigator.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/18236.
This consists of two main parts:
1. Handling failures when sending `SocketAction` properly instead of panicking
2. Closing the dialogs that require a notifier when player is destroyed
=> desktop: Close dialogs when the player is destroyed

Cargo.lock
Dropping a duplicate `libredox` version.
Noticed this during a routine manual `cargo update` check.
=> chore: Bump the `orbclient` indirect dependency

core/src/avm1/globals/external_interface.rs, core/src/avm2/globals/flash/external/external_interface.rs, core/src/external.rs, core/src/player.rs, desktop/src/backends/external_interface.rs, tests/tests/external_interface/mod.rs, tests/tests/external_interface/tests.rs, web/src/external_interface.rs
Instead of getting a method then calling it, we just call things directly now. We also can now only have one Provider instead of many, but realistically there's no case in which multiple providers can peacefully coexist as they'll be conflicting with methods.
=> core: Clean up ExternalInterface a little

core/src/display_object/edit_text.rs, core/src/html/test.rs, core/src/html/text_format.rs
That parameter was unused, its value was always `None`.
=> text: Remove `new_tf` from `FormatSpans::replace_text`

.github/workflows/test_web.yml, web/packages/selfhosted/wdio.conf.ts
Just pushing to see whether it will work.
=> Separate web testing into per-browser runners

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, web/docker/Dockerfile
Following #17780.
See the changelog: https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v120
=> chore: Bump Binaryen (wasm-opt) to version 120

core/src/display_object/edit_text.rs
Adobe documentation refers to the 2px padding as the gutter.
=> text: Rename `INTERNAL_PADDING` to `GUTTER`

core/src/debug_ui/display_object.rs, core/src/display_object/edit_text.rs, core/src/html/layout.rs
These were originally used for some calculations, but now they have been replaced by proper bounds.
When reworking the layout, I added proper bounds (named `bounds`), and renamed the original bounds to `interior_bounds` in order to preserve the old behavior in some places. As of now, we're ready to drop the interior bounds, as replacing them with proper bounds works and all tests pass.
Areas where this PR changes the calculated values (by a bit):
* layout metrics (getTextExtent),
* maxscroll,
* bottom scroll,
* positions of links in text.
=> text: Remove layout line & layout box interior bounds

core/src/display_object.rs, core/src/display_object/edit_text.rs, render/src/matrix.rs
This is a refactor that aims at code simplification and deduplication of logic. Specifically, it introduces the idea of layout coordinate space and implements transforms from local coordinate space to layout coordinate space and vice-versa.
By using these transforms it's easier and less error-prone to get coordinates within text.
This also simplifies text field rendering, pushing only one transform onto the stack instead of two.
After implementing this, I'm fairly certain that `is_link_at` is also broken, as it doesn't take into account translation resulting from bounds and it incorrectly compensates for the gutter. I'll leave this however for a future fix with tests.
=> text: Introduce layout coordinate space and transforms

core/src/backend/audio.rs, core/src/context.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/edit_text.rs, core/src/display_object/movie_clip.rs
... instead of doing this for each unloaded display object.
Fixes #18327.
Fixes #18181.
Fixes #18057.
Fixes #17718.
Fixes #17395.
This should fix #17059 as well... but I'm not sure where the issues are supposed to be. 😅
I also checked against the files mentioned in #17016 and can confirm that they continue to stop sounds as expected. However, I was unable to test #16947 due to the web server being down. For #963, I tested it on [FlashArch](https://flasharch.com/en/archive/play/2f4ee6ce445533f1f46a1ec8090e463f), since the file appears to be no longer accessible on the official site.
[Super Monkey Ball Mini](https://wondertrio.com/games/monkeyball/index.html) is an interesting test case, as it experienced both issues in sequence:
- Before …
=> core: Stop sounds attached to an unloaded root movie

core/src/font.rs, core/src/html/layout.rs
This patch simplifies code, as text height is not needed anymore after recent text refactors.
=> text: Return text width only in `Font::measure`

core/src/debug_ui/display_object.rs, core/src/display_object/edit_text.rs
* Add "Relayout" action
* Add "Font Type"
* Add "Condense White"
* Add "Always Show Selection"
* Add HTML Text editor
<image src="https://github.com/user-attachments/assets/86245c8e-2f92-492e-bf22-fb866b5ebd15" height="400"/>
=> debug_ui: Improve EditText

core/src/player.rs, desktop/assets/texts/en-US/main_menu.ftl, desktop/src/gui/menu_bar.rs
Fast-paced animations can be hard to investigate with the debug tools, as one needs to suspend the playback at exactly the right time.
To alleviate this, this PR adds the `Controls > Step Once` menu command (shortcut: Ctrl+Space), which allows advancing a suspended movie one frame at a time. Sounds are suppressed while stepping, to prevent unpleasant "sound bursts".
=> desktop: Add `Controls > Step Once`, for frame-by-frame stepping 

Cargo.lock, Cargo.toml, core/Cargo.toml, deny.toml, desktop/Cargo.toml, desktop/src/gui/controller.rs, desktop/src/gui/movie.rs, desktop/src/util.rs, render/wgpu/src/context3d/current_pipeline.rs, render/wgpu/src/descriptors.rs, render/wgpu/src/filters/bevel.rs, render/wgpu/src/filters/blur.rs, render/wgpu/src/filters/color_matrix.rs, render/wgpu/src/filters/displacement_map.rs, render/wgpu/src/filters/glow.rs, render/wgpu/src/pipelines.rs, render/wgpu/src/pixel_bender.rs
This lets us drop a whole bunch of (duplicated) dependencies, just look at Cargo.lock!
Currently using egui master.
=> render: Update wgpu to 23

core/src/backend/navigator.rs, desktop/src/backends/navigator.rs, desktop/src/backends/ui.rs, desktop/src/cli.rs, desktop/src/gui/dialogs/open_dialog.rs, desktop/src/gui/dialogs/preferences_dialog.rs, desktop/src/player.rs, desktop/src/preferences.rs, desktop/src/preferences/read.rs, desktop/src/preferences/write.rs, frontend-utils/src/backends/navigator.rs, web/src/builder.rs, web/src/navigator.rs
This PR moves open links behavior preference from launch options (which was settable before running each SWF) to the preferences (which is settable at any point in time and is persistent).
Additionally, this PR changes the default to "confirm". Users who don't want the confirmation popup to be displayed all the time can disable it, and others will have an additional layer of security on by default.
Opening links without confirmation is unsafe because:
1. It shares your IP address and other information.
2. It might be used to leak sensitive information in the URL.
By having the confirmation dialog on by default, users will have a chance to check if the link is safe before opening it.
Fixes https://github.com/ruffle-rs/ruffle/issues/17432.
CC @n0samu
@torokati44 This PR changes a bit the …
=> desktop: Move open URLs mode from launch options to preferences

web/eslint.config.js, web/packages/core/README.md, web/packages/core/src/internal/player/impl_v1.ts, web/packages/core/src/internal/player/inner.tsx, web/packages/core/src/internal/player/ruffle-player-element.tsx, web/packages/core/src/public/player/index.ts, web/packages/core/src/public/player/legacy.ts, web/packages/core/src/public/player/player-element.ts, web/packages/core/src/public/player/v1.ts, web/packages/demo/src/player.tsx, web/packages/extension/src/player.ts, web/packages/selfhosted/README.md, web/packages/selfhosted/test/integration_tests/external_interface/test.ts, web/packages/selfhosted/test/js_api/exposed.ts, web/packages/selfhosted/test/js_api/load.ts, web/packages/selfhosted/test/js_api/metadata.ts, web/packages/selfhosted/test/utils.ts, web/src/external_interface.rs, web/src/lib.rs
Bikeshedding time, here's the chance to decide what the "v1 api" looks like before we lock it in.
The only change so far is that I've added a specific method for calling EI, vs the very easy-to-break and implicit "the method will exist, trust me". I'm awaiting feedback before touching anything else.
Whilst this is "version 1" (`PlayerV1` interface), if we never add a V2 that's totally fine. `ruffle()` is the same as `ruffle(1)`.
Things to consider for each existing member of the API:
- Is anything a property that should be a method?
- Is anything a method that should be a property?
- Should we rename anything, or change arguments?
=> web: Add `ruffle()` (Version 1) API

web/packages/core/src/internal/player/inner.tsx
This includes a few vaguely related changes:
1) Many functions that relate to the save manager and don't rely on any parts of the `InnerPlayer` have been pulled out into external functions, taking a queue from already existing external functions like `parseBoolean` and `parseAllowScriptAccess`. These functions include `saveFile`, `base64ToArray` (which has also been slightly simplified), `base64ToBlob`, and `isB64SOL`.
2) `isB64SOL` has been changed to more accurately check for SOL data, using logic from https://www.sans.org/blog/local-shared-objects-aka-flash-cookies/
3) Each row of the save table has been changed to a tsx component called SaveRow, instead of using so much direct DOM manipulation.
=> web: Use tsx for save manager rows and use more accurate check for SOL

core/src/avm2.rs, core/src/avm2/object.rs
In some rare edge cases (registering hundreds of DOs per frame), this gave me 1fps->10fps improvement.
This is still sometimes quadratic and could be improved even further by storing some ordered hashset, but this would cost extra memory and it hasn't shown to be _that_ perf critical in real content so far (or rather: in big enough content we have bigger issues :P ).
=> avm2: Use fast pointer comparison for broadcast-list dupe checks

Cargo.lock, render/wgpu/src/buffer_builder.rs, render/wgpu/src/surface.rs, render/wgpu/src/surface/commands.rs
This fixes #18317 and should help a lot with any movie that does multiple blends on the same frame (unless they're nested). For me, it reduces VRAM of that game during loading down from **13 GB** to just shy of **500 MB**.
Graphics memory requirement goes from `(size of stage) * (number of total blends)` to just `(size of stage) * 1` for most cases.
Imagine a hypothetical draw list:
DrawRect, DrawCircle, BlendTrivial(DrawTriangle), BlendComplex(DrawStar), DrawSmilyFace
Before it would do this:
- DrawTriangle into a temp buffer A
- DrawStar into a temp buffer B
- DrawRect, DrawCircle, DrawTempBufferA all as one render pass
- DrawTempBufferB (as one render pass)
- DrawSmilyFace as one render pass
This meant for every (not nested) blend, we needed that many temp textures.
With this change, …
=> wgpu: Perform blends as-needed, instead of ahead of time. Reduces memory usage for multiple blends significantly

frontend-utils/src/bundle.rs
It makes it easier to see what's wrong with the bundle.
=> frontend_utils: Make Ruffle Bundle errors more verbose

Cargo.lock, render/wgpu/src/buffer_builder.rs, render/wgpu/src/surface.rs, render/wgpu/src/surface/commands.rs
Reverts ruffle-rs/ruffle#18692
Due to https://github.com/ruffle-rs/ruffle/issues/18734
=> Revert "wgpu: Perform blends as-needed, instead of ahead of time. Reduces memory usage for multiple blends significantly"

core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/events.rs, core/src/avm2/globals/array.rs, core/src/avm2/globals/flash/display/movie_clip.rs, core/src/avm2/globals/flash/events/EventDispatcher.as, core/src/avm2/globals/flash/events/event_dispatcher.rs, core/src/avm2/globals/function.rs, core/src/avm2/globals/json.rs, core/src/avm2/globals/string.rs, core/src/avm2/globals/vector.rs, core/src/avm2/object.rs, core/src/avm2/object/class_object.rs, core/src/avm2/object/dispatch_object.rs, core/src/avm2/object/function_object.rs, core/src/avm2/object/responder_object.rs, core/src/avm2/object/xml_list_object.rs, core/src/avm2/object/xml_object.rs, core/src/avm2/regexp.rs, core/src/avm2/value.rs, core/src/external.rs, core/src/player.rs, core/src/socket.rs, core/src/timer.rs
Specifically, we can now directly call and construct `Value`s, as a step toward removing PrimitiveObject.
A microbenchmark shows no significant perf impact.
=> avm2: Refactor TObject call and construct

core/src/avm2/globals/flash/display/DisplayObject.as, core/src/avm2/globals/flash/display/InteractiveObject.as, core/src/avm2/globals/flash/geom/Transform.as, core/src/avm2/globals/flash/geom/transform.rs
Improved stubs:
* `InteractiveObject.softKeyboardInputAreaOfInterest`
* `Transform.matrix3D`
* `Transform.perspectiveProjection`
* `Transform.concatenatedColorTransform`
Updated API versioning:
* `DisplayObject.blendShader`
=> avm2: Improve some stubs, add API versioning

swf/src/read.rs
This didn't cause long-term memory use, but contributed to peak mem use before preloading started.
This also can help wasm, since the wasm heap never drops in size.
=> swf: Memcpy the swf header away instead of creating an entire new Vec

.github/dependabot.yml, Cargo.lock, deny.toml, desktop/Cargo.toml
It was pinned before because conflicts would sometimes introduce multiple tracy clients, but we have cargo-deny for that now...
=> chore: Update tracy and allow bots to update it from hereon

core/src/bitmap/bitmap_data.rs
This prevents a a scenario where when a cpu-dirty texture is uploaded for the first time, we accidentally upload it twice.
This is nontrivial work, but I don't think this'll save any major real-world fps (I imagine the upload itself is faster than us sending the call with data to wgpu) or memory.
In a firefox profile of a microbenchmark it _did_ spend ~20% of time in `pixels_rgba()` of the 2nd upload, but for some reason with the PR, the total jank barely decreased; probably because the profile didn't account for gpu time itself.
=> core: Set BitmapData as synced after texture creation

web/packages/core/src/internal/player/inner.tsx, web/packages/core/src/plugin-polyfill.ts
I've not tested this, but it may fix https://github.com/ruffle-rs/ruffle-rs.github.io/issues/177.
=> web: On browsers which support it, specify the type of audio Ruffle uses

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, Cargo.lock, Cargo.toml, web/README.md, web/docker/Dockerfile
Hopefully https://github.com/ruffle-rs/ruffle/pull/18397 can be reverted after: https://github.com/ruffle-rs/ruffle/pull/18399
Also, this will make one commit unnecessary in the upcoming https://github.com/ruffle-rs/ruffle/pull/18761#issuecomment-2499393501.
=> chore: Bump wasm-bindgen to 0.2.97

core/src/avm1/globals/array.rs
Fixes #18109
Speeds up sorting
```as
var arr = [];
var i = 0;
while(i < 3000)
{
arr.push({key:i});
i++;
}
flash.external.ExternalInterface.call("console.log",arr[0]);
var startDate = new Date();
flash.external.ExternalInterface.call("console.log","Sorting started at: " + startDate);
arr.sortOn("key",Array.DESCENDING | Array.NUMERIC);
var endDate = new Date();
flash.external.ExternalInterface.call("console.log","Sorting ended at: " + endDate);
flash.external.ExternalInterface.call("console.log",arr[0]);
var duration = endDate.getTime() - startDate.getTime();
flash.external.ExternalInterface.call("console.log","Sorting duration (ms): " + duration);
```
In this example:
Recursion qsort duration: 347ms
Iterative qsort duration: 271ms
=> avm1: Replace recursion with iterative `qsort`

Cargo.lock
Dependabot couldn't do it. This will hopefully turn CI green again.
See: https://github.com/ruffle-rs/ruffle/security/dependabot/88
=> chore: Bump hashbrown to 0.15.2 to resolve an advisory

Cargo.lock, Cargo.toml, core/Cargo.toml, render/Cargo.toml, video/software/Cargo.toml
~~Our "jpegxr" crate is still to be updated, because it doesn't have Dependabot set up.~~
EDIT: Done.
=> chore: Switch to thiserror 2.0.4 where possible

core/build_playerglobal/src/lib.rs, core/src/avm2/events.rs, core/src/avm2/globals/flash/display/loader.rs, core/src/avm2/globals/flash/display/shader_parameter.rs, core/src/avm2/globals/flash/display/shape.rs, core/src/avm2/globals/flash/display/sprite.rs, core/src/avm2/globals/flash/events/event_dispatcher.rs, core/src/avm2/globals/flash/geom/transform.rs, core/src/avm2/globals/flash/utils/timer.rs
A follow-up to #18747, as proposed on Discord.
The generated code now looks like this:
```rs
mod slots {
mod flash_utils_timer {
pub const _timerId: u32 = ...;
pub const _delay: u32 = ...;
}
// ...
}
```
This makes usage terser, as most files only need access to the slots of a single AS3 class, which can then be imported as `use avm2::globals::slots::the_class as slots`.
=> avm2: Group generated AS3 field slot constants by package

core/src/tag_utils.rs, swf/src/types/color.rs, swf/src/types/rectangle.rs
The default `Debug` was producing too much output for those classes to make debugging them feasible.
=> core: Reimplement `Debug` for some structs

core/src/avm2/filters.rs, core/src/avm2/globals/flash/filters/BevelFilter.as, core/src/avm2/globals/flash/filters/BitmapFilter.as, core/src/avm2/globals/flash/filters/BlurFilter.as, core/src/avm2/globals/flash/filters/ColorMatrixFilter.as, core/src/avm2/globals/flash/filters/ConvolutionFilter.as, core/src/avm2/globals/flash/filters/DisplacementMapFilter.as, core/src/avm2/globals/flash/filters/DropShadowFilter.as, core/src/avm2/globals/flash/filters/GlowFilter.as, core/src/avm2/globals/flash/filters/GradientBevelFilter.as, core/src/avm2/globals/flash/filters/GradientGlowFilter.as, core/src/avm2/globals/flash/filters/ShaderFilter.as
This removes the last few easy-to-replace uses of `get_public_property`
=> avm2: Use slot access in filter code

Cargo.lock, Cargo.toml, desktop/Cargo.toml
Manually extracted from https://github.com/ruffle-rs/ruffle/pull/18617 (which got superseded by https://github.com/ruffle-rs/ruffle/pull/18644, and later https://github.com/ruffle-rs/ruffle/pull/18647), because these needed a little extra attention.
Let's do a `@dependabot unignore rfd` and `@dependabot unignore ashpd` after this. Referencing https://github.com/dependabot/dependabot-core/issues/10286 again.
----
Bumps the cargo-minor group with 2 updates in the / directory:
| Package | From | To |
| --- | --- | --- |
| [rfd](https://github.com/PolyMeilex/rfd) | `0.15.0` | `0.15.1` |
| [ashpd](https://github.com/bilelmoussaoui/ashpd) | `0.9.2` | `0.10.2` |
Updates `rfd` from 0.15.0 to 0.15.1
- [Release notes](https://github.com/PolyMeilex/rfd/releases)
- …
=> build(deps): bump the cargo-minor group across 1 directory with 2 updates (`rfd` and `ashpd`)

Cargo.lock
Since Dependabot still doesn't do this.
No added or removed dependencies, only edges between them.
Note that `cargo update` now always has to be followed by `cargo update idna_adapter --precise 1.0.0`, since #18598.
=> chore: Bump crate versions in Cargo.lock

Cargo.lock, Cargo.toml
Doing it manually because Dependabot fricked it up in https://github.com/ruffle-rs/ruffle/pull/18993 by changing some windowsy crate versions, causing type mismatches.
See: https://github.com/gfx-rs/wgpu/releases/tag/v23.1.0
=> chore: Bump naga to 23.1.0

Cargo.lock, Cargo.toml, core/Cargo.toml, deny.toml, desktop/Cargo.toml
It just got released today, with the PR in it that we need (https://github.com/emilk/egui/pull/5330).
See: https://github.com/emilk/egui/releases/tag/0.30.0
=> desktop: Switch to the egui 0.30.0 release from git master

web/package-lock.json
Notably, this fixes https://github.com/advisories/GHSA-mwcw-c2x4-8c55 (CVE-2024-55565) by bumping `nanoid` to `3.3.8`.
=> chore: Do an `npm update` to fix a nanoid advisory

web/docker/Dockerfile
- binaryen xz is no longer stored on disk, instead being piped directly to tar
- only extract wasm-opt (the only file we're interested in)
- locate wasm-opt using wildcard, instead of keeping path in sync with version number.
we're doing the same with sh.rustup.rs below.
=> web: Reduce docker build IO

core/src/avm2/globals/flash/text/engine/text_block.rs, core/src/display_object/edit_text.rs
Using the term TLF (Text Layout Framework) is technically incorrect, as TLF is a high level library written in AS, compared to FTE (Flash Text Engine) being the low-level API that TLF uses. `TextLine` is a part of FTE, not TLF.
See <https://docs.ruffle.rs/en_US/as3/dev/WS9dd7ed846a005b294b857bfa122bd808ea6-8000.html>
See <https://docs.ruffle.rs/en_US/as3/dev/WSb2ba3b1aad8a27b0-1b8898a412218ad3df9-8000.html>
See <https://docs.ruffle.rs/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/package-detail.html>
=> text: Refer to `TextLine` as FTE, not TLF

core/src/avm2/e4x.rs
Reverts ruffle-rs/ruffle#19073
Can only be re-merged after https://github.com/ruffle-rs/ruffle/pull/18399, which itself needs other PR(s): https://github.com/ruffle-rs/ruffle/pull/18399#issuecomment-2514682267
The suggested code has only been available in stable since Rust 1.82: https://doc.rust-lang.org/std/option/enum.Option.html#method.is_none_or
=> Revert "chore: Fix a nightly `clippy::unnecessary_map_or` lint"

desktop/packages/linux/rs.ruffle.Ruffle.desktop.in, desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml.in
First of all, I know how this might looks, and I don't wish to sound "insulting" or petty. :)
I know you're all proud rustaceans, and you should be, because Rust is a great programming language. Be proud of your project, Ruffle is amazing! :D
But... was it necessary to put "rust" as a keyword in the .desktop file? To me the end user shouldn't care about what programming language was used to develop Ruffle... besides, it is already mentionned in the package description and it messes up my start menu when I type "rust"...
However don't worry, I wouldn't mind much if you choose to reject my PR. Have a great day.
=> Removed "rust" as a keyword in the .desktop

core/src/avm1/globals/transform.rs, core/src/display_object/edit_text.rs, core/src/font.rs, core/src/html/layout.rs, render/canvas/src/lib.rs, render/src/bitmap.rs, render/src/lines.rs, render/src/matrix.rs, render/webgl/src/lib.rs, render/wgpu/src/surface/commands.rs, swf/README.md, swf/examples/writing.rs, swf/src/read.rs, swf/src/test_data.rs, swf/src/types/twips.rs, swf/src/write.rs
It's a refactor that replaces `Twips` instantiations with respective constants. Some instantiations in tests (by `Twips::new`) were left intact as they seem to focus on the pure numerical value instead of semantically the number of twips.
=> refactor: Use constants from `Twips` where appropriate

desktop/src/gui.rs
Since we're using tokio we can easily migrate save dialogs to async ones, that do not require another thread to be handled.
* Fixes https://github.com/ruffle-rs/ruffle/issues/19130
=> desktop: Use async dialogs when saving files

core/src/html/layout.rs
* Progresses https://github.com/ruffle-rs/ruffle/issues/12257
This is based on the behavior of Flash: when no device font is available, Flash falls back to a monospace font for the following fonts:
* Consolas
* Courier
* Courier New
* NSimSun
Checked all default fonts of Windows and MacOS.
=> core: Handle font fallback for more known monospace fonts

core/src/bitmap/operations.rs, flv/src/tag.rs, render/src/pixel_bender.rs, swf/src/write.rs, video/software/src/decoder/screen.rs
Not including https://github.com/ruffle-rs/ruffle/pull/19073 of course, see https://github.com/ruffle-rs/ruffle/pull/19075.
=> chore: Apply fixes for beta `clippy::precedence` lint

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, web/README.md, web/docker/Dockerfile, web/package.json, web/packages/core/tools/build_wasm.ts
~~I'm not sure whether this itself will be controversial. By itself, this update changes nothing in the development or CI pipelines by default.~~
~~Instead, it adds an environment variable, `BUILD_WASM_MVP`, which when set will cause `npm run build:dual-wasm` and/or `npm run build:repro` to create a truly vanilla WASM module by using nightly Rust to disable all the WebAssembly extensions. With this set, the version of Ruffle that gets built can run on Pale Moon and Safari versions as old as 14.1.~~
~~What this doesn't do (yet) is use this environment variable on CI or in the Firefox Docker script. Doing that is a matter of debate. Once we unpin CI from Rust 1.81, if we don't use this environment variable on CI, Ruffle will stop working on those older browsers. We can use this on CI …
=> web: Make npm run build:dual-wasm create an MVP vanilla WASM module and make the default WASM module be with extensions

.github/workflows/release_nightly.yml
Reverts ruffle-rs/ruffle#18397.
To be merged once https://github.com/rustwasm/wasm-bindgen/pull/4213 is merged and released, so https://github.com/rustwasm/wasm-bindgen/issues/4227 can be fixed properly.
Also referencing https://github.com/rustwasm/wasm-bindgen/issues/4211.
=> Revert "ci: Freeze rustc for nightly web builds to 1.81.0"

core/src/avm2/e4x.rs
This is https://github.com/ruffle-rs/ruffle/pull/19073 again, after having been reverted by https://github.com/ruffle-rs/ruffle/pull/19075.
To be merged only after https://github.com/ruffle-rs/ruffle/pull/18399.
=> chore: Fix a nightly `clippy::unnecessary_map_or` lint

web/packages/core/src/internal/player/inner.tsx, web/packages/core/src/internal/ui/panic.tsx, web/packages/core/texts/en-US/messages.ftl
~~This is somewhat the antithesis of https://github.com/ruffle-rs/ruffle/pull/18528. That PR keeps Ruffle running on browsers without reference types support.~~ This shows a better error on browsers without reference-types support when only the with-extensions WASM module is available for use.
~~Merging https://github.com/ruffle-rs/ruffle/pull/18399 will break Ruffle on Safari versions below 15 and Pale Moon. We can keep Ruffle working on those browsers, or we can officially designate them to be unsupported.~~
=> web: Improve error when WASM extensions are unsupported but only the module which uses them is available

desktop/Cargo.toml, desktop/src/backends/ui.rs
Using async IO means we're not blocking the main thread and the content doesn't freeze while reading.
In theory, Ruffle should use only async IO, as otherwise the main thread will be blocked by every bit of IO performed. According to my knowledge this is the first instance of using async IO in Ruffle.
Things to consider:
* apparently `tokio::fs` is slow: https://github.com/tokio-rs/tokio/issues/3664,
* do we want to use `tokio::fs`, or `async-fs` (or something else) so that we are compatible with other runtimes (referring specifically to `frontend_utils`).
=> desktop: Use async IO for file browsing in AVM

core/src/debug_ui/display_object.rs
=> debug_ui: Add horizontal & vertical scroll to EditText

web/packages/extension/src/background.ts
I prefer using `utils` whenever possible, but sometimes DefinitelyTyped makes that harder than it should be. This should let #19206 be merged I think.
=> extension: Update declarativeNetRequest rules using the chrome namespace

core/src/avm2/activation.rs, core/src/avm2/object/proxy_object.rs, core/src/avm2/optimize.rs
`op_has_next` should push `false`, not `0` when `cur_index` is negative, and Op::URShift should push the uint type in the optimizer, not the int type.
=> avm2: Fix URShift in optimizer and hasnext in interpreter when passed a negative index

.cargo/config.toml, Cargo.toml, web/packages/core/src/internal/builder.ts, web/packages/core/src/internal/player/inner.tsx, web/packages/core/src/load-ruffle.ts, web/packages/core/tools/build_wasm.ts, web/packages/core/tools/set_version.ts
Instead of the one with extensions enabled.
A continuation of https://github.com/ruffle-rs/ruffle/pull/19198.
=> web: Qualify the vanilla (MVP) WASM module with a name suffix

Cargo.lock
Making sure that the tracy-client and idna_adapter stuff remains unbroken.
=> chore: Run `cargo update` carefully

core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/function.rs, core/src/avm2/optimize.rs
This speeds up `getlocal`/`setlocal` by about 10%
=> avm2: Store locals on AVM stack instead of per-Activation RegisterSets

core/src/avm2/globals/flash/text/engine/ElementFormat.as, core/src/avm2/globals/flash/text/engine/TextLine.as
Stubbed methods:
* `ElementFormat.getFontMetrics`
* `TextLine.getAtomBidiLevel`
* `TextLine.getAtomCenter`
* `TextLine.getAtomGraphic`
* `TextLine.getAtomTextBlockBeginIndex`
* `TextLine.getAtomTextBlockEndIndex`
* `TextLine.getAtomTextRotation`
* `TextLine.getAtomWordBoundaryOnLeft`
=> avm2: Stub more methods from FTE

Cargo.lock, swf/Cargo.toml
I don't think we do anything more here - no changelog, no anything.
I'm just gonna run `cargo publish` after merging.
I also looked through commit list, I think this is the only possibly incompatible change: https://github.com/ruffle-rs/ruffle/pull/17030
=> swf: Bump version to 0.2.2 for crates.io publish

desktop/src/app.rs
This patch associates the main window created by Ruffle with the Ruffle application by its ID.
This fixes issues on some desktops (KDE, Wayland) where the window is not being recognized as Ruffle.
* Fixes https://github.com/ruffle-rs/ruffle/issues/19303
* Supersedes https://github.com/ruffle-rs/ruffle/pull/19304
=> desktop: Associate Ruffle window with Ruffle

core/src/events.rs, desktop/src/cli.rs, web/Cargo.toml, web/eslint.config.js, web/packages/core/src/internal/builder.ts, web/packages/core/src/public/config/default.ts, web/packages/core/src/public/config/load-options.ts, web/src/builder.rs, web/src/lib.rs
Mostly just a proof of concept right now. This doesn't actually support defining the button to keycode mappings yet. I suspect we want to think a bit deeper about how that configuration would look like before adding it  to the Ruffle API.
=> web: Support gamepad button input

core/src/debug_ui/display_object.rs
Without this patch, Ruffle was displaying empty labels for objects without a name.
=> debug_ui: Fix summary of objects without a name

core/src/avm1/globals/file_reference.rs, core/src/avm1/globals/shared_object.rs, core/src/avm2/globals/flash/net/shared_object.rs, core/src/avm2/globals/xml_list.rs, core/src/debug_ui/movie.rs, core/src/html/layout.rs, core/src/html/text_format.rs, frontend-utils/src/lib.rs
See: https://github.com/ruffle-rs/ruffle/actions/runs/12819112889/job/35746103823?pr=19251#step:6:1045
https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
=> chore: Address nightly clippy lints `double_ended_iterator_last` and `len_zero`

core/src/avm2/activation.rs
Extracted from https://github.com/adrian17/ruffle/tree/avm2-interpreter-loop .
I've seen the wildcard cause the compiler to generate slightly worse code, like extra range checks on the enum discriminant before jumping into the jump table.
=> avm2: Avoid wildcard in op dispatch

core/src/avm2/activation.rs, core/src/avm2/op.rs, core/src/avm2/optimize.rs, core/src/avm2/verify.rs
This should shrink `Activation::run_actions`
This removes the ops `getglobalscope`, `getglobalslot`, `callsupervoid`, `pushnan`, and `pushbyte`- instead, we now use `getouterscope`/`getscopeobject`, `getouterscope`/`getscopeobject`+`getslot`, `callsuper`+`pop`, `pushdouble`, and `pushshort`.
=> avm2: Replace complex ops with simpler ops

.github/ISSUE_TEMPLATE/error_report.md
GitHub seems to be prepending the default title to the title generated by Ruffle, resulting in issues titled "Error error on..."
=> github: Remove default title for error reports

core/src/player.rs, desktop/src/app.rs
This makes delta time more accurate and somewhat mitigates the winit busy loop issue.
=> desktop: Use nanosecond precision for dt when ticking

core/src/debug_ui.rs, core/src/debug_ui/avm1.rs, core/src/debug_ui/avm2.rs, core/src/debug_ui/common.rs, core/src/debug_ui/display_object.rs
This patch adds a way of displaying tabs for native objects. In this case it makes it easier to debug AVM1 style sheets.
Also some code is refactored so that functions used in multiple files are moved into `common.rs`.
=> debug_ui: Add Style Sheet tab for AVM1 objects

Cargo.lock, core/macros/Cargo.toml, core/macros/src/lib.rs, core/src/avm1/activation.rs, core/src/avm2/activation.rs, core/src/context.rs, core/src/string.rs, core/src/string/common.rs, core/src/string/context.rs, core/src/string/interner.rs
Add an explicit form `istr!(context, "string")` that can be used when no `activation` variable is in scope; it supports more context types through the new `HasStringContext` trait.
Modify `CommonStrings` to hold `AvmAtom`s instead of `AvmString`s, and add the `atom!` macro.
=> core: Allow `istr!` to be used in more places

desktop/src/app.rs
Fixes #16700
This is how the main window looks at its smallest size:
=> desktop: Make the main window at minimum wider than the menu bar

core/src/avm1/activation.rs, core/src/avm1/flv.rs, core/src/avm1/function.rs, core/src/avm1/globals/array.rs, core/src/avm1/globals/as_broadcaster.rs, core/src/avm1/globals/button.rs, core/src/avm1/globals/color_matrix_filter.rs, core/src/avm1/globals/convolution_filter.rs, core/src/avm1/globals/file_reference.rs, core/src/avm1/globals/gradient_filter.rs, core/src/avm1/globals/key.rs, core/src/avm1/globals/mouse.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm1/globals/movie_clip_loader.rs, core/src/avm1/globals/selection.rs, core/src/avm1/globals/stage.rs, core/src/avm1/globals/string.rs, core/src/avm1/globals/style_sheet.rs, core/src/avm1/globals/system_ime.rs, core/src/avm1/globals/text_field.rs, core/src/avm1/globals/text_format.rs, core/src/avm1/object/array_object.rs, core/src/display_object/edit_text.rs, core/src/external.rs
`ArrayObject` construction now requires an activation, so add `ArrayObjectBuilder` to simplify the process: it allows grabbing what we need from the activation (the interned `length` property name, and the array prototype) without running afoul of the borrow checker.
=> avm1: Don't use a static `AvmString` for AVM1 array's length property

core/src/avm1/runtime.rs
* Fixes https://github.com/ruffle-rs/ruffle/issues/18952
* Fixes https://github.com/ruffle-rs/ruffle/issues/17191
* Fixes https://github.com/ruffle-rs/ruffle/issues/17072
* Fixes https://github.com/ruffle-rs/ruffle/issues/16733
* Fixes https://github.com/ruffle-rs/ruffle/issues/16430
* Fixes https://github.com/ruffle-rs/ruffle/issues/16129
Turns out that sometimes objects pending removal do not have a parent.
I wasn't able to reproduce it, but it happens as we can see in error reports.
Semantically this should be fine, as we mainly operate on the parent here, but it's hard to be sure considering it's not reproducible. It's better than panicking for sure.
=> avm1: Do not unwrap parent when removing objects pending removal

core/src/avm1/globals/array.rs
=> avm1: avoid creating a temporary `Vec` in `Array.prototype.splice`

.github/workflows/release_nightly.yml
@danielhjacobs Proposes we hardcode to either the last general release or the RC so as to resolve the conflicting installs which are likely blocking the desktop builds. I would opt to stay with the general release for now.
=> ci: Use dotnet to install wix extensions

Cargo.lock, core/Cargo.toml, core/src/html/text_format.rs, core/src/xml/tree.rs
Replacing https://github.com/ruffle-rs/ruffle/pull/18406 with this, so Dependabot won't get confused...
Bumps the cargo-minor group with 1 update: [quick-xml](https://github.com/tafia/quick-xml).
Updates `quick-xml` from 0.36.2 to 0.37.0
- [Release notes](https://github.com/tafia/quick-xml/releases)
- [Changelog](https://github.com/tafia/quick-xml/blob/master/Changelog.md)
- [Commits](https://github.com/tafia/quick-xml/compare/v0.36.2...v0.37.0)
=> build(deps): bump quick-xml in the cargo-minor group

.github/workflows/release_nightly.yml
Realized after looking into the approach to this more closely that just the base package should be pinned. The toolset extensions need to continue to be added globally to the cache as they were since we're not actually coding in a .NET project.
=> Version pinning just the wix base

core/src/events.rs, core/src/input.rs, core/src/player.rs
This refactor simplifies code and is a first step towards tidying up and unifying input handling across platforms.
The most important improvement is the addition of `InputEvent`, which represents a mapped `PlayerEvent` related to input. It proves to be useful even now by discarding gamepad events and having click index present at all times. In the future this will make it possible to pass information about keys in `PlayerEvent` without any knowledge about Flash Player (so no `KeyCode`).
=> refactor: Add InputEvent

Cargo.lock, Cargo.toml, core/Cargo.toml, render/Cargo.toml, render/wgpu/Cargo.toml
This is 2/3 of https://github.com/ruffle-rs/ruffle/pull/19549, removing `ashpd` and `tempfile` bumps from it, to avoid the nasty `rand`/`getrandom`/`zerocopy`/etc. duplications.
Bumps the cargo-minor group with 4 updates in the / directory:
| Package | From | To |
| --- | --- | --- |
| [clap](https://github.com/clap-rs/clap) | `4.5.29` | `4.5.30` |
| [smallvec](https://github.com/servo/rust-smallvec) | `1.13.2` | `1.14.0` |
| [quick-xml](https://github.com/tafia/quick-xml) | `0.37.0` | `0.37.2` |
| [lru](https://github.com/jeromefroe/lru-rs) | `0.12.5` | `0.13.0` |
Updates `clap` from 4.5.29 to 4.5.30
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/clap-rs/clap/releases">clap's releases</a>.</em></p>
<blockquote>
<h2>v4.5.30</h2>
<h2>[4.5.30] - …
=> build(deps): bump the cargo-minor group across 1 directory with 4 updates

render/naga-agal/src/builder.rs, render/wgpu/src/backend.rs, render/wgpu/src/context3d/mod.rs, render/wgpu/src/descriptors.rs, render/wgpu/src/lib.rs, render/wgpu/src/pipelines.rs, render/wgpu/src/pixel_bender.rs, render/wgpu/src/surface/target.rs, render/wgpu/src/target.rs
- Use array methods instead of collecting to a vector first
- Remove `Arc`s around `wgpu` objects thanks to wgpu 24 improvements
=> Small improvements to render crates

render/wgpu/src/context3d/current_pipeline.rs, render/wgpu/src/context3d/mod.rs
=> render: Remove `Rc` around `wgpu` objects

core/src/avm2/globals/flash/display/loader_info.rs, core/src/avm2/object/loaderinfo_object.rs
Partially addresses https://github.com/ruffle-rs/ruffle/issues/14455 .
The window now kinda works, though it's slow, leaks memory (known unload() issues) and sometimes hangs after throwing:
```
2025-02-14T22:19:50.642618Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject { type: "getUserEnvironment", class: src.com.gaiaonline.FishTank.events::DataConnectorEvent, ptr: 0x2a5c77646f0 } to handler FunctionObject(FunctionObject { ptr: 0x2a5c5b73e00, name: "src.com.gaiaonline.FishTank.services::SpecialEventManager/onGetSettings()" }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: events)
at src.com.gaiaonline.FishTank.services::SpecialEventManager/onGetSettings()
at flash.events::EventDispatcher/dispatchEventInternal()
at …
```
=> AVM2: Partially support parentAllowsChild when domains match

Cargo.lock, Cargo.toml
Should fix hopefully all instances of https://github.com/ruffle-rs/ruffle/issues/19278 that appeared after we bumped to v23.
Same with all Android errors with this style: https://github.com/ruffle-rs/ruffle-android/issues/338
=> render: Switch to wgpu fork with backported GLES limits fix

core/src/display_object/avm1_button.rs, core/src/display_object/avm2_button.rs, core/src/display_object/edit_text.rs, core/src/display_object/graphic.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/text.rs
...and the corresponding `FooStatic` structs to `FooShared`.
This better represents the semantics, and avoids conflation with the `'static` lifetime (in fact, these structs sometimes contain GC'd data).
Intended as preliminary work for a future PR removing `GcCell` usage from the movie clip code, which may introduce a new internal `struct MovieClipStatic: 'static` that would conflict with the currently existing `struct MovieClipStatic<'gc>`.
=> core: Rename display objects' `static_data` field to `shared`

core/src/avm2/globals/flash/net/Socket.as
Fixes a noticed regression from https://github.com/ruffle-rs/ruffle/pull/17119 .
=> avm2: Set correct version to Socket::timeout

core/src/events.rs, core/src/input.rs, core/src/player.rs, desktop/src/gui/context_menu.rs, web/src/lib.rs
Implementing IME requires passing events which are not Copy, so this refactor makes it easier to implement IME.
=> refactor: Make events not Copy

core/src/input.rs
It's unused and I think it has never been used.
=> core: Remove unused last_text_control

frontend-utils/src/bundle/source.rs
When an IO error occurs, be more verbose and include the inner error in the message, that makes it easier to debug issues.
=> frontend_utils: Be more verbose on IO bundle errors

desktop/src/app.rs, desktop/src/gui/controller.rs
This refactors moves the logic of mapping window position to movie position into one common method.
=> desktop: Map window to movie position explicitly

core/src/avm1/function.rs, core/src/avm1/globals/bevel_filter.rs, core/src/avm1/globals/blur_filter.rs, core/src/avm1/globals/color_matrix_filter.rs, core/src/avm1/globals/convolution_filter.rs, core/src/avm1/globals/displacement_map_filter.rs, core/src/avm1/globals/drop_shadow_filter.rs, core/src/avm1/globals/file_reference.rs, core/src/avm1/globals/glow_filter.rs, core/src/avm1/globals/gradient_filter.rs, core/src/avm1/globals/xml.rs, core/src/avm1/object/stage_object.rs, core/src/avm1/object_reference.rs
This refactor replaces `GcCell` with `Gc` and uses interior mutability instead.
By getting rid of `GcCell`, we don't have to lock every time we do anything with the object.
=> avm1: Replace `GcCell` with `Gc` in AVM1 structs

web/packages/extension/src/content.ts, web/packages/extension/src/ruffle.ts
If there are no other changes in Safari 16+, this PR will fix #10981
=> web: Fix extension not working in Safari 16 (close #10981)

core/src/display_object/edit_text.rs
`EditText` is a pointer already, no need to reference it.
=> core: Remove double pointers in `EditText`

core/src/debug_ui/display_object.rs
When not searching, show all objects irrespectively of their name or whether they have a name at all.
=> debug_ui: Show all objects when not searching

core/src/avm2/globals/flash/display/bitmap.rs, core/src/display_object/bitmap.rs
This refactor replaces `GcCell` with `Gc` and uses interior mutability instead.
By getting rid of `GcCell`, we don't have to lock every time we do anything with the object.
=> core: Replace `GcCell` with `Gc` in `Bitmap`

core/src/display_object.rs, core/src/display_object/loader_display.rs, core/src/display_object/morph_shape.rs
This refactor replaces `GcCell` with `Gc` and uses interior mutability instead.
By getting rid of `GcCell`, we don't have to lock every time we do anything with the object.
=> core: Replace `GcCell` with `Gc` in `LoaderDisplay` & `MorphShape`

Cargo.lock, Cargo.toml, core/Cargo.toml, desktop/Cargo.toml
Reverts/replaces https://github.com/ruffle-rs/ruffle/pull/19512.
Changelogs:
- https://github.com/emilk/egui/releases/tag/0.31.1
- https://github.com/gfx-rs/wgpu/releases/tag/v24.0.2
=> chore: Bump `egui` to `0.31.1`, switch back to mainline `wgpu` `24.0.2`

deny.toml
Basically https://github.com/gfx-rs/wgpu/pull/7301.
There's nothing explicitly wrong with this crate, and since it's an indirect dependency, with depending crates not eager/willing to replace it, there's not much else we can do.
=> chore: Ignore advisory about `paste` being unmaintained

core/src/avm1/activation.rs, core/src/avm1/globals/object.rs, core/src/avm1/globals/system_ime.rs, core/src/avm1/value.rs, core/src/avm2/domain.rs, core/src/avm2/globals/Date.as, core/src/avm2/globals/class.rs, core/src/avm2/globals/date.rs, core/src/avm2/globals/flash/ui/keyboard.rs, core/src/avm2/globals/number.rs, core/src/avm2/globals/object.rs, core/src/avm2/globals/xml.rs, core/src/avm2/namespace.rs, core/src/backend/audio.rs, core/src/context.rs, core/src/display_object/interactive.rs, core/src/loader.rs, core/src/string/avm_string.rs
This saves an allocation every time we create an AvmString pointing to a static string
=> core/avm1/avm2: Add `AvmString::new_ascii_static` and use it

web/packages/core/src/internal/ui/static-styles.css
Useful when the Ruffle instance is smaller than the text of the Panic screen, such as on a Flash-based website with small elements.
=> web: Allow scrolling the panic screen

core/src/avm2/error.rs
Because on `i686-unknown-linux-gnu` for example, its 16 bytes, and the Android app is built for that target as well.
Fixes a regression introduced in https://github.com/ruffle-rs/ruffle/pull/19716.
Unblocks https://github.com/ruffle-rs/ruffle-android/pull/410.
See: https://github.com/ruffle-rs/ruffle-android/actions/runs/13898078735/job/38883161245?pr=410#step:6:57.
Resembles https://github.com/ruffle-rs/ruffle/pull/11263.
All the other similar asserts (except in the `wstr` crate) use `<=` instead of `==` as well.
=> avm2: Make the size constraint on Value be an upper bound

web/Cargo.toml, web/packages/core/src/internal/player/inner.tsx, web/packages/core/texts/en-US/messages.ftl, web/src/lib.rs
Intended to fix this comment in https://github.com/ruffle-rs/ruffle/issues/1905#issuecomment-1030111132
=> web: Reload with canvas when webglcontextlost and 8+ instances exist

Cargo.lock, core/src/context.rs, core/src/display_object/edit_text.rs, core/src/events.rs, core/src/input.rs, core/src/player.rs, desktop/Cargo.toml, desktop/assets/texts/en-US/preferences_dialog.ftl, desktop/src/app.rs, desktop/src/custom_event.rs, desktop/src/gui/controller.rs, desktop/src/gui/dialogs/preferences_dialog.rs, desktop/src/player.rs, desktop/src/preferences.rs, desktop/src/preferences/read.rs, desktop/src/preferences/write.rs
* Progresses https://github.com/ruffle-rs/ruffle/issues/1778
The basic IME support includes displaying popups in roughly the right position, and handling IME commit events without preediting yet.
Tested manually with Anthy (no automated tests yet due to lack of preediting).
IME preference is also added to the GUI (disabled by default):
=> desktop: Implement basic IME support

render/wgpu/src/backend.rs
Should fix the regression once and for all, hopefully :)
=> wgpu: Lower max_color_attachments limit to 4

Cargo.lock, core/src/avm1/activation.rs, core/src/avm1/object.rs, core/src/avm1/property_map.rs, core/src/avm2/dynamic_map.rs, core/src/avm2/filters.rs, core/src/avm2/object.rs, core/src/avm2/property_map.rs, core/src/debug_ui/handle.rs, core/src/display_object.rs, core/src/display_object/container.rs, core/src/display_object/interactive.rs, core/src/font.rs, core/src/library.rs, core/src/loader.rs, core/src/local_connection.rs, core/src/net_connection.rs, core/src/socket.rs, core/src/string/context.rs, core/src/string/interner.rs, core/src/timer.rs, deny.toml, ruffle_gc_arena/Cargo.toml, ruffle_gc_arena/src/gc_cell.rs, ruffle_gc_arena/src/gc_weak_cell.rs
Notable changes:
- `Collect::trace` is now generic over the tracing context: this makes the `CollectCell` abstraction used in the string interner unsound (as `Collect::trace` can now be, in principle, called at any time). As such, this is replaced by a simpler `RefCell`.
- `gc-arena` upgraded its `hashbrown` dependency to `0.15`, but we need to stay on `0.14` because we use `RawTable` (in the AVM2 `DynamicMap` and in the string interner). The work-around is to manually implement `Collect` on these types.
- `gc-arena` improved its pacing algorithm; there are no API changes, but we should investigate the performance impact before merging.
=> core: update `gc-arena` to latest `master`

web/package-lock.json
Applies `npm audit fix` suggestion
This only upgrades `@babel/helpers` packages, so shouldn't be a big deal
Vulnerability:
@babel/helpers  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
=> web: Fix vulnerability for upstream dependency

desktop/assets/texts/en-US/preferences_dialog.ftl, desktop/src/gui/dialogs/preferences_dialog.rs
This patch fixes a typo and removes unnecessary strings.
I'll fix up the translations in Crowdin when this lands.
=> desktop: Fix translations for IME preferences

Cargo.lock, core/src/avm1/activation.rs, core/src/avm1/globals/date.rs, core/src/avm2/globals/toplevel.rs
This would sooner or later bite us in the bottom anyway: https://github.com/ruffle-rs/ruffle-android/actions/runs/14034450723/job/39289142906?pr=419
See also:
- https://github.com/jhpratt/deranged/issues/17
- https://github.com/jhpratt/deranged/issues/18
- https://github.com/time-rs/time/issues/736
=> chore: Bump `time` and `deranged`, avoid `PartialOrd` ambiguity

.github/workflows/release_nightly.yml, .github/workflows/test_extension_dockerfile.yml, .github/workflows/test_web.yml, web/docker/Dockerfile
https://github.com/WebAssembly/binaryen/pull/7394:
> Given the big speedup in our official release binaries for Linux, this seems useful to get to users quickly.
https://github.com/WebAssembly/binaryen/pull/7378:
> fixes performance problems, especially on heavily multi-threaded workloads (many functions, high core count machines)
=> chore: Bump Binaryen (wasm-opt) to version 123

web/packages/core/src/internal/player/inner.tsx, web/packages/selfhosted/test/integration_tests/context_menu_position/test.ts
This patch adds support for RTL context menu. The context menu will use RTL when the preferred language of the user is RTL.
This patch will work only for browsers supporting `Intl.Locale.getTextInfo`, which sadly does not include Firefox.
=> web: Add support for RTL context menu

core/src/display_object/movie_clip.rs
The `RUNNING_CONSTRUCT_FRAME` and `POST_INSTANTIATED` were mistakenly set to the same value, probably due to a botched rebase.
Hopefully, this doesn't appear to have caused any bugs, but let's fix it just to be sure (who knows? maybe it fixes something).
=> core: Fix conflated flags in `MovieClipFlags`

core/src/avm1/globals/movie_clip.rs, core/src/debug_ui/display_object.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/edit_text.rs, core/src/display_object/graphic.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs, core/src/display_object/text.rs, core/src/drawing.rs, render/src/shape_utils.rs, swf/src/read.rs, swf/src/types/rectangle.rs
`Rectangle<Twips>` is cheap to copy, being only 16 bytes, so requiring an explicit `.clone()` call is unnecessary ceremony.
Has the nice side-effect of replacing some `RefCell`s by `Cell`s.
=> core: make `swf::Rectangle` `Copy`

core/src/display_object/container.rs
Unfortunately sometimes the render list and the depth list become desynchronized.  When swapping children this caused panics.
I haven't been able to reproduce those scenarios, but it's better to leave the render/depth list messed up than to panic in this case.
* Fixes https://github.com/ruffle-rs/ruffle/issues/19944
* Fixes https://github.com/ruffle-rs/ruffle/issues/19911
* Fixes https://github.com/ruffle-rs/ruffle/issues/19640
* Fixes https://github.com/ruffle-rs/ruffle/issues/19583
* Fixes https://github.com/ruffle-rs/ruffle/issues/19535
* Fixes https://github.com/ruffle-rs/ruffle/issues/19406
* Fixes https://github.com/ruffle-rs/ruffle/issues/19150
* Fixes https://github.com/ruffle-rs/ruffle/issues/19116
* Fixes https://github.com/ruffle-rs/ruffle/issues/19101
* Fixes …
=> avm1: Do not panic when swapping children on depth/render list desync

web/packages/core/src/plugin-polyfill.ts, web/packages/selfhosted/test/polyfill/spoofing/test.ts
To make JSON.stringify work with `navigator.plugins` and `navigator.mimeTypes` we have to make sure all _enumerable_ properties are non-cyclic.
It seems like in a normal browser e.g. `navigator.mimeTypes["application/pdf"]` (all names) and `navigator.plugins["PDF Viewer"]` are not enumerable. So I switched to using `Object.defineProperty` for those.
To hide our internal private variables I switched those to [ECMAScript Private Fields](https://www.typescriptlang.org/docs/handbook/classes.html#ecmascript-private-fields). This also prevents them from being enumerated of course.
`RufflePlugin` didn't use getters so I fixed this as well for consistency with the browser `Plugin` type.
Fixes #19957
=> web: Improve navigator.plugins and navigator.mimeTypes so they can be used with JSON.stringify

web/package-lock.json, web/package.json, web/packages/selfhosted/package.json
5.99.0 has regressions: https://github.com/webpack/webpack/issues/19394
Unsure if it's causing issues for us, but figured an upgrade cannot hurt. Perhaps relates to #20045, but no actual idea nor any idea how to test that.
=> web: Bump webpack to 5.99.5

web/packages/core/src/internal/i18n.ts
While the custom Map is only defined once, it seems to fairly frequently be defined while this loop is running. See also https://github.com/ruffle-rs/ruffle/pull/19939#discussion_r2021244480.
=> web: Check if custom Map is defined as fluent loop is iterating

.github/workflows/release_nightly.yml
#19767 was not meant to affect this.
May be unrelated to https://github.com/ruffle-rs/ruffle/actions/runs/14392606559/job/40362550974#step:11:49 so we should look into that too.
=> ci: Build dual-wasm for selfhosted/demo/docs

core/src/avm1.rs, core/src/avm1/activation.rs, core/src/avm1/globals/text_field.rs, core/src/avm1/globals/transform.rs, core/src/avm1/object.rs, core/src/avm1/object/script_object.rs, core/src/avm1/object/stage_object.rs, core/src/avm1/object_reference.rs, core/src/avm1/runtime.rs, core/src/avm1/scope.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/edit_text.rs, core/src/display_object/movie_clip.rs, core/src/display_object/video.rs, core/src/timer.rs
The display objects (`Avm1Button`, `EditText`, `MovieClip`, `Video`) are directly stored as `NativeObject` variants of their `ScriptObject`s, and the `StageObject`-specific data (namely, the AVM1 text field binding list) is moved directly inside the DO structs.
After this, only `SuperObject` will be left as a `Object` variant.
=> avm1: migrate `StageObject` to `NativeObject`

Cargo.lock, video/external/Cargo.toml, video/external/src/backend.rs, video/external/src/decoder.rs, video/external/src/decoder/webcodecs.rs, web/Cargo.toml, web/src/builder.rs
A continuation of https://github.com/ruffle-rs/ruffle/pull/14654.
Not really done yet, just pushing for visibility, and so that it doesn't get forgotten.
~_(Just look at the commit history lol.)_~
Due to this API being based on callbacks, this currently adds at least one additional (video) frame of delay as compared to a synchronous decoder, such as OpenH264 on desktop. I think this should be acceptable.
It would be possible to wire the callback straight from the browser through the video backend to the renderer backend, to update the texture immediately (off the regular frame pacing schedule), but I think that would be a bit too complicated, and could potentially result in less smooth playback.
Mostly works, in Chrome and in Firefox 129+.
I don't think this could be problematic at all …
=> web,video: Add H264 decoding using the WebCodecs API

video/external/src/decoder/openh264.rs
Thought for a second there was something wrong with Ruffle saving the OpenH264 files only to realize it just always printed the message.
=> video/external: Don't say we are downloading OpenH264 when we use the cached version

core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/error.rs, core/src/avm2/function.rs, core/src/avm2/method.rs, core/src/avm2/object/class_object.rs, core/src/avm2/script.rs, core/src/avm2/value.rs, tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/MultipleCatchBlocks2/test.toml, tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/MultipleCatchBlocksArgument/test.toml, tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_17/test.toml, tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_2/test.toml
This makes bytecode method calls with `call_method` about 30-40% faster and any other method calls 10-20% faster.
The unchecked function fix closes #12346.
=> avm2: Avoid allocating when calling a method

web/packages/core/tools/set_version.ts
The editor showed a little squiggly underneath it. I don't like squigglies in my code.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#the_difference_between_substring_and_substr
=> web: Replace deprecated `String.substr` with `String.substring`

desktop/build.rs
Remove setting the `nightly` cfg option from build.rs, as it's not used.
=> desktop: Remove unused `nightly` cfg

web/packages/core/src/load-ruffle.ts
The legacy WASM initialization API now triggers a console warning:
```text
"using deprecated parameters for the initialization function; pass a single object instead"
```
So migrate to the new one
```js
// Before (deprecated):
wasm_bindgen(your_array_buffer); 
// After (recommended):
wasm_bindgen({ module_or_path: your_array_buffer });
```
=> web: Migrate WASM initialization to use module_or_path parameter

web/packages/core/src/internal/player/inner.tsx, web/packages/core/src/internal/player/ruffle-embed-element.ts, web/packages/core/src/internal/player/ruffle-player-element.tsx
Not added to `config`/`options` as `align` itself is deprecated for `embed`/`object` elements - the same can be accomplished with the appropriate CSS.
=> web: Support align embed/object attribute (part of #4258)

.github/workflows/release_nightly.yml, desktop/build.rs, web/packages/core/tools/set_version.ts, web/packages/extension/webpack.config.js, web/packages/selfhosted/webpack.config.js
That way we can differentiate easily between a local build and an official release. It's also the first step towards supporting stable releases.
The CI part is untested, I believe I provided the channel everywhere it's needed, but we'll have to make sure after publishing a nightly.
=> build: Set a different channel for local builds

web/package-lock.json
Fixes: https://github.com/ruffle-rs/ruffle/security/dependabot/102
Dependabot choked on it: https://github.com/ruffle-rs/ruffle/actions/runs/14590927990/job/40925812658#step:3:264 😒
=> chore: Bump `http-proxy-middleware` version in `web/package-lock.json`

web/packages/core/tools/set_version.ts, web/packages/extension/webpack.config.js
Before this patch every channel besides nightly used the version as version name.  This patch adds the channel to version name, so that it's easier to identify the version.
=> web: Include channel in version name if not stable

core/build_playerglobal/src/lib.rs, core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/call_stack.rs, core/src/avm2/class.rs, core/src/avm2/error.rs, core/src/avm2/function.rs, core/src/avm2/globals/Function.as, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/function.rs, core/src/avm2/globals/global_scope.rs, core/src/avm2/globals/null.rs, core/src/avm2/globals/void.rs, core/src/avm2/method.rs, core/src/avm2/object/class_object.rs, core/src/avm2/object/function_object.rs, core/src/avm2/optimizer/optimize.rs, core/src/avm2/script.rs, core/src/avm2/verify.rs
`Method` is now a single struct (stored behind a Gc). We store separate native and bytecode method info in a `MethodKind` enum.
=> avm2: Shrink Method to 8 bytes by unifying BytecodeMethod and NativeMethod

desktop/src/gui/controller.rs
Source Han Sans is another popular CJK font that has native font names and uses glyphs according to the locale (not sure if  ruffle supports it, but e.g. Firefox supports it so it makes things easier for me than Noto Sans CJK).
WenQuanYi Zen Hei is an old Chinese font and maybe someone still has only it.
PS: I hope ruffle could use fontconfig rather than hardcode more & more font names...
=> desktop: more fallback cjk fonts for Linux

desktop/src/gui/controller.rs
Before this patch, we were loading only one font, based on the OS and language selected. This approach was not perfect, as the UI can have characters from multiple fonts, irrespectively of selected language.
This patch changes the way fonts are loaded, and provides multiple fallback fonts for different categories of characters (Korean, Chinese, Japanese, etc.).
This patch makes it possible to see characters from all categories at the same time in UI irrespectively of selected language. Additionally, it adds Hebrew and Arabic fonts.
Before:
After:
It's a follow-up to https://github.com/ruffle-rs/ruffle/pull/20210
=> desktop: Fix missing characters in UI

web/packages/extension/src/background.ts, web/packages/extension/src/content.ts, web/packages/extension/src/ruffle.ts, web/packages/extension/webpack.config.js
No browser specific setting exists for Chrome but this raises the minimum version for it to 102 for the extension. Minimum Safari extension version unchanged as it was already bumped to 16.4 previously.
Edit: In the future, we should be able to remove script injection altogether, as soon as Windows 7 - 8.1 support is dropped by Mozilla.
=> extension: Stop injecting scripts on any browser except Firefox 127 and below

web/packages/core/src/current-script.ts, web/packages/extension/manifest.json5, web/packages/extension/src/background.ts, web/packages/selfhosted/js/ruffle.js
Review by commit.
- We can re-use exclude_matches from the manifest
- Prevent DOM clobbering problems with document.currentScript
=> web: Two small improvements

core/src/avm1/activation.rs, core/src/avm1/globals/button.rs, core/src/avm1/globals/color.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm1/globals/transform.rs, core/src/avm1/object/stage_object.rs, core/src/avm2/globals/flash/display/display_object.rs, core/src/avm2/globals/flash/display/display_object_container.rs, core/src/avm2/globals/flash/geom/transform.rs, core/src/context.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/avm2_button.rs, core/src/display_object/container.rs, core/src/display_object/edit_text.rs, core/src/display_object/loader_display.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs, core/src/frame_lifecycle.rs, core/src/loader.rs
This refactor simplifies code and makes some methods not require mutability and GC context.
=> core: Put some DisplayObject properties in a Cell

core/src/avm1/activation.rs, core/src/avm1/globals/stage.rs, core/src/avm1/object/stage_object.rs, core/src/avm2/globals/flash/display/stage.rs, core/src/context.rs, core/src/debug_ui/display_object.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs, core/src/player.rs
This refactor simplifies code and makes some methods not require mutability and GC context.
=> core: Put some Stage properties in a Cell

core/src/avm1/activation.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm2/globals/flash/display/display_object.rs, core/src/avm2/globals/flash/display/movie_clip.rs, core/src/avm2/globals/flash/display/sprite.rs, core/src/debug_ui/display_object.rs, core/src/display_object.rs, core/src/display_object/movie_clip.rs, core/src/player.rs
This refactor simplifies code and makes some methods not require mutability and GC context.
Frame related properties are left intact, because they would require a significant amount of additional code to be generated. We'll have to think about something smarter for them.
=> core: Put some MovieClip properties in a Cell

video/external/src/decoder/webcodecs.rs
It's not like I didn't have enough time to clean up https://github.com/ruffle-rs/ruffle/pull/16794 ... :roll_eyes:
=> nit: Be consistent with tracing macro usage in webcodecs.rs

core/src/streams.rs
https://github.com/ruffle-rs/ruffle/pull/16244 couldn't have fixed this too, because it was done in between https://github.com/ruffle-rs/ruffle/pull/14654 (which added this code) being created and merged.
I'm not aware of any actual problems that this fixes; it just caught my eye; but it looks logical to me.
=> video: Also invalidate bitmap cache after decoding AVC (H.264) video frames

web/packages/extension/assets/options.html
Call me a hair-splitter all you want, but this has bothered me since forever...
I know about English and its rules, but this is the name of a project, and it's confusing among all those other Ws that should actually be upper-case.
_Jeez, so much effort and resource use for a single letter change..._
=> web/extension: nit: "Wgpu" -> "wgpu"

core/src/debug_ui.rs, core/src/debug_ui/display_object.rs, desktop/assets/texts/en-US/main_menu.ftl, desktop/src/gui/menu_bar.rs
- Add scene and label selection menu buttons to the table header
- Add a top menu action to quickly open the root `MovieClip`, if it exists
This provides quick access the "main" frame list, to quickly seek to interesting parts of a movie.
On demand, I can split this into two pull requests, but hopefully they both make sense to merge.
https://github.com/user-attachments/assets/87120124-42e5-4814-9ceb-36f091a7e992
=> debug_ui: More frame list related improvements

video/external/src/decoder/openh264.rs
Some comments were outdated, untidy, or lacking.
And I agree that panicking on some unsupported video file is not ideal, but at least we have a chance of knowing whether those actually exist in the wild!
=> video/openh264: Clean up comments a bit, also assert on number of SPSs

web/packages/extension/assets/_locales/en/messages.json, web/packages/extension/assets/options.html
They would have proven useful for me at least twice now during local testing.
Also, I always see them in this order, not as they currently are.
=> web/extension: Also add "debug" and "trace" log levels as options

Cargo.lock, core/Cargo.toml, core/src/avm2/filters.rs, core/src/backend/audio.rs, core/src/backend/navigator.rs, core/src/backend/ui.rs, core/src/lib.rs, core/src/player.rs, desktop/src/gui/controller.rs, exporter/src/main.rs, render/Cargo.toml, render/canvas/src/lib.rs, render/src/backend.rs, render/src/bitmap.rs, render/src/filters.rs, render/src/pixel_bender.rs, render/webgl/src/lib.rs, render/wgpu/src/backend.rs, render/wgpu/src/context3d/mod.rs, render/wgpu/src/lib.rs, render/wgpu/src/mesh.rs, render/wgpu/src/pixel_bender.rs, tests/framework/src/environment.rs, tests/tests/environment.rs, tests/tests/shared_object/mod.rs, web/src/builder.rs, web/src/lib.rs
Now that Rust supports trait upcasting, the direct dependency on `downcast-rs` isn't needed anymore.
`downcast-rs` still appears to be transitively used by `wayland-backend`, so I haven't removed it from the `LICENSE.md` list.
=> core/render/web: replace uses of the `Downcast` trait with `Any`

core/src/avm2/globals/flash/media/video.rs, core/src/display_object/movie_clip.rs, core/src/display_object/video.rs
=> core: Replace GcCell with Gc in Video

core/src/avm1/globals/netstream.rs, core/src/loader.rs, core/src/streams.rs
=> core: Replace GcCell with Gc in NetStream

core/src/player.rs
This patch makes sure shared objects are flushed when Player is dropped. Specifically, it fixes shared objects not being saved on desktop properly.
* Fixes https://github.com/ruffle-rs/ruffle/issues/20191
=> core: Flush shared objects on Player drop

exporter/src/main.rs
Ruffle supports AVM2 movies pretty well now. Phasing out the `--skip-unsupported` option, but leaving it as a hidden option for backward compatibility.
=> exporter: Phase out `--skip-unsupported` option

.github/workflows/release_nightly.yml
We're building them anyway so I suppose it doesn't hurt to release them, though I'm open to opinions. Based on a user on Discord using super old hardware with a modern browser whose hardware actually doesn't allow the with extensions module to work.
=> ci: Release dual-wasm extensions as assets

.github/workflows/release_nightly.yml, .github/workflows/test_rust.yml, README.md
Testing on the `rust:1.86` docker image, I built `ruffle_desktop` with `cargo build --release`, installing any missing packages
that caused a build error.
Then I checked which of the listed dependencies are installed:
```
dpkg -l libasound2-dev  libxcb-shape0-dev  libxcb-xfixes0-dev  libgtk-3-dev  libudev-dev  libxcb-xinput-dev  libxcb-xkb-dev  libxcb-cursor-dev  default-jre-headless cmake g++
dpkg-query: no packages found matching libxcb-shape0-dev
dpkg-query: no packages found matching libxcb-xfixes0-dev
dpkg-query: no packages found matching libgtk-3-dev
dpkg-query: no packages found matching libxcb-xinput-dev
dpkg-query: no packages found matching libxcb-xkb-dev
dpkg-query: no packages found matching libxcb-cursor-dev
dpkg-query: no packages found matching cmake …
```
=> docs: Remove Linux dependencies that don't seem to be required anymore

core/src/bitmap/bitmap_data.rs, core/src/debug_ui/display_object.rs
This patch fixes a crash when the bitmap had no pixels (e.g. it was disposed) and adds some debug properties for bitmaps.
=> debug_ui: Improve Bitmap tab

tests/tests/swfs/avm2/color_matrix_filter/test.toml, tests/tests/swfs/avm2/convolution_filter/test.toml, tests/tests/swfs/avm2/edittext_align/test.toml, tests/tests/swfs/avm2/edittext_getlinemetrics/test.toml, tests/tests/swfs/avm2/edittext_underline/test.toml
Some tests no longer require approximations.
=> chore: Remove approximations from some tests

core/src/avm1/globals/text_field.rs, core/src/avm1/globals/text_format.rs, core/src/avm2/globals/flash/text/engine/text_block.rs, core/src/avm2/globals/flash/text/text_field.rs, core/src/debug_ui/display_object.rs, core/src/display_object/edit_text.rs
=> core: Get rid of GcCell in EditText

web/src/builder.rs
We don't support non-Unicode names, and in case such name appeared, we failed to register it properly.
* Progresses https://github.com/ruffle-rs/ruffle/issues/20292#issuecomment-2836494332
=> web: Fix registering TTF fonts with non-Unicode names

desktop/packages/linux/rs.ruffle.Ruffle.desktop, desktop/packages/linux/rs.ruffle.Ruffle.desktop.in
It's useful setting this as a fallback, if the `.desktop` file is not named the same as app ID (`rs.ruffle.Ruffle.desktop`).
As flatpaks always name their `.desktop` files as `app-id.desktop`, they are not affected.
As a bonus, another XDG desktop standard is respected.
This is useful for user-wide package managers which name their `.desktop` files differently to not collide with existing `.desktop` files (like [AM AppImage Manager](https://github.com/ivan-hc/AM)).
According to my tests, `wmclass` is the same in both Wayland & X11, so this works well.
Ending result is that Ruffle associates the window & icon correctly, even if `.desktop` file is named differently, while not causing any regressions.
=> desktop: Linux - add `StartupWMClass` to the desktop file

core/src/avm2/class.rs, core/src/avm2/globals/flash/geom/Transform.as, core/src/avm2/globals/global_scope.rs, core/src/avm2/object/class_object.rs, core/src/avm2/optimizer/optimize.rs, core/src/avm2/script.rs
Closes #17495
We now verify that overrides of methods use the same return type as the method they override, which allows us to make use of the return type of all methods in the optimizer.
Box2d stats:
```
ConstructSuper -> Pop: 70%
FindPropStrict -> GetScriptGlobals: 82.71%
FindPropStrict -> GetOuterScope: 9%
FindPropStrict -> GetScopeObject: 8.28%
FindProperty -> GetOuterScope: 5.66%
FindProperty -> GetScopeObject: 94.33%
InitProperty -> SetSlot: 6.3% (-2.19%)
InitProperty -> SetSlotNoCoerce: 90.95% (+2.19%)
InitProperty -> CallMethod: 2.73%
SetProperty -> SetSlot: 8.07% (-1.72%)
SetProperty -> SetSlotNoCoerce: 73.88% (+1.72%)
SetProperty -> CallMethod: 2.4%
GetProperty -> GetSlot: 88.89%
GetProperty -> CallMethod: 0.47%
CallProperty -> CallMethod: 83.26%
CallProperty -> CoerceUSwapPop: …
```
=> avm2: Use return type of methods in optimizer

Cargo.lock, core/Cargo.toml
This pulls in https://github.com/ruffle-rs/rust-flash-lso/pull/74 (and https://github.com/ruffle-rs/rust-flash-lso/pull/75), although I'm not sure what significance either would bear...
=> chore: Bump rust-flash-lso to latest git master

.github/workflows/test_rust.yml
This reverts https://github.com/ruffle-rs/ruffle/pull/16390 and https://github.com/ruffle-rs/ruffle/pull/16682, as https://github.com/dtolnay/linkme/issues/94 is claimed to be fixed by https://github.com/rust-lang/rust/pull/137685. See also: https://github.com/dtolnay/linkme/pull/88 and then https://github.com/dtolnay/linkme/pull/112.
=> ci: Remove lld workaround for linkme

core/src/avm1/function.rs, core/src/avm1/object/super_object.rs, core/src/utils.rs
=> avm1: Remove `Gc` indirection for `SuperObject`

core/src/display_object/movie_clip.rs, core/src/library.rs, core/src/loader.rs
Additionally, preloading now modifies the existing `MovieClipShared` instance instead of swapping a clone on each `preload` call.
This means that duplicating a partially-preloaded `MovieClip` will return a clip sharing the preload state. This seems "more correct" to me (as it means that both clips will properly finish preloading), but I haven't tested this in FP.
EDIT: Added a further refactoring that moves most of the tag preloading methods to `MovieClipShared`, as they mostly don't need access to the actual MC instance.
=> core: Remove `GcCell` usage in `MovieClipShared`

Cargo.lock, tests/framework/Cargo.toml, tests/framework/src/options.rs
Multiple image checks are useful when we want to test more than one tolerance/max_outliers configurtion at one time.
For instance, we might want to check that the image has 0 outliers for tolerance 128, and 10 outliers for tolerance 5.
The configuration above would be written as:
```
[[image_comparisons.output.checks]]
tolerance = 128
max_outliers = 0
[[image_comparisons.output.checks]]
tolerance = 5
max_outliers = 10
```
Filters are useful when e.g. the given check only applies to a specific
platform. It's very common that a test output looks different on
different platforms. With filters we can write specific checks for
specific platforms instead of increasing tolerance for all of them.
An example configuration might look like this:
```
[[image_comparisons.output.checks]]
filter = …
```
=> tests: Add support for multiple checks for an image & filters

Cargo.lock, Cargo.toml, desktop/Cargo.toml
https://github.com/rust-windowing/winit/releases/tag/v0.30.11
https://github.com/gfx-rs/wgpu/releases/tag/v24.0.4
https://github.com/gfx-rs/wgpu/releases/tag/v24.0.5
With `wgpu` 25 also being out now, I just don't trust Dependabot at this point...
=> chore: Bump winit and wgpu patch versions

.github/workflows/release_nightly.yml, .github/workflows/test_rust.yml, tests/tests/swfs/avm1/mcl_target_jpg/test.toml, tests/tests/swfs/avm1/movieclip_begin_gradient_fill/test.toml, tests/tests/swfs/avm1/movieclip_line_gradient_style/test.toml, tests/tests/swfs/avm2/blend_shader_luma_lighten/test.toml, tests/tests/swfs/avm2/pixelbender_dithering/test.toml, tests/tests/swfs/avm2/stage3d_bitmap/test.toml, tests/tests/swfs/avm2/stage3d_ignore_sampler_override/test.toml, tests/tests/swfs/avm2/stage3d_raytrace/test.toml, tests/tests/swfs/avm2/stage3d_texture/test.toml, tests/tests/swfs/avm2/stage3d_texture_bytearray/test.toml, tests/tests/swfs/avm2/stage3d_texture_bytearray_compressed_alpha/test.toml, tests/tests/swfs/avm2/stage3d_texture_bytearray_compressed_raw_alpha/test.toml, tests/tests/swfs/visual/drawing_api/gradient_focal_point/test.toml, tests/tests/swfs/visual/edittext/edittext_border_filters/test.toml, tests/tests/swfs/visual/filters/displacement_map/test.toml, tests/tests/swfs/visual/gradient_issue_9892/test.toml, tests/tests/swfs/visual/shumway_acid_tests/acid_bitmap_fill/test.toml, tests/tests/swfs/visual/shumway_acid_tests/acid_bitmap_fill_2/test.toml, tests/tests/swfs/visual/shumway_acid_tests/acid_color_0/test.toml, tests/tests/swfs/visual/simple_shapes/gradients/focal_radial/test.toml
GitHub added new runners with ARM processors, and we are able to easily build binaries for AArch64 that way!
Let's see how well this works!
=> build: Build binaries for Linux AArch64

core/src/library.rs
This shouldn't change anything; according to my analysis, the "missing characters on looking up export" bug should be fixed. This patch only gets rid of the unwrap() and introduces better error handling in case something breaks in the future.
* Fixes https://github.com/ruffle-rs/ruffle/issues/16648
* Fixes https://github.com/ruffle-rs/ruffle/issues/16355
* Fixes https://github.com/ruffle-rs/ruffle/issues/16288
* Fixes https://github.com/ruffle-rs/ruffle/issues/16127
* Fixes https://github.com/ruffle-rs/ruffle/issues/15799
=> core: Assert that a character exists for each export

core/build_playerglobal/src/lib.rs, core/src/avm2.rs, core/src/avm2/activation.rs, core/src/avm2/function.rs, core/src/avm2/globals.rs, core/src/avm2/globals/Class.as, core/src/avm2/globals/Function.as, core/src/avm2/globals/Math.as, core/src/avm2/globals/Namespace.as, core/src/avm2/globals/QName.as, core/src/avm2/globals/README.md, core/src/avm2/globals/String.as, core/src/avm2/globals/Toplevel.as, core/src/avm2/globals/VectorDouble.as, core/src/avm2/globals/VectorInt.as, core/src/avm2/globals/VectorObject.as, core/src/avm2/globals/VectorUint.as, core/src/avm2/globals/XML.as, core/src/avm2/globals/XMLList.as, core/src/avm2/globals/flash/display/Graphics.as, core/src/avm2/globals/flash/display/loader_info.rs, core/src/avm2/globals/flash/media/SoundTransform.as, core/src/avm2/globals/flash/system/application_domain.rs, core/src/avm2/globals/flash/utils.as, core/src/avm2/globals/math.rs, core/src/avm2/method.rs, core/src/avm2/object/domain_object.rs, core/src/avm2/op.rs, core/src/avm2/optimizer/optimize.rs, core/src/avm2/script.rs
This allows us to optimize some calls to native functions when
1. the function has a `[Ruffle(FastCall)]` annotation,
2. the arguments are of the correct count and type, and
3. the class of the value the function is being called on is `final`.
For example, `Math.abs` runs more than twice as fast with this PR as it does on current `master`. From my testing, in most SWFs, 5-20% of calls that would be `CallMethod` are now `CallNative`.
Box2d stats:
```
ConstructSuper -> Pop: 70%
FindPropStrict -> GetScriptGlobals: 82.67%
FindPropStrict -> GetOuterScope: 8.96%
FindPropStrict -> GetScopeObject: 8.36%
FindProperty -> GetOuterScope: 5.66%
FindProperty -> GetScopeObject: 94.33%
InitProperty -> SetSlot: 6.28%
InitProperty -> SetSlotNoCoerce: 90.98%
InitProperty -> CallMethod: 2.73%
SetProperty -> …
```
=> avm2: Speed up some native calls

web/Cargo.toml, web/packages/core/src/internal/player/inner.tsx, web/packages/core/texts/en-US/messages.ftl, web/src/lib.rs
The `unload` event is deprecated, and Chrome even plans to remove support for it entirely:
https://developer.chrome.com/docs/web-platform/deprecating-unload
The `pagehide` event is now used as a replacement. A side effect of this change, however, is that it makes pages eligible for the back/forward cache (bfcache): as a result, instances of Ruffle may no longer be recreated from scratch when navigating back to the page, but instead "revived" from their previous state. When this happens, the following message is displayed to the user:
Closes #19704.
=> web: Switch from `unload` to `pagehide` event

core/src/display_object/movie_clip.rs, core/src/loader.rs
This refactor makes it easier to get rid of `GcCell`.
=> core: Use Cells & RefCells where possible in MovieClipData

core/src/font.rs, core/src/library.rs
This refactor makes the scope of the Collect impl narrower so that it's less probable to make a mistake and leave out a field from the impl.
=> core: Narrow the scope of Library's unsafe Collect impl

core/src/avm2/globals/flash/geom/PerspectiveProjection.as, core/src/avm2/globals/flash/geom/perspective_projection.rs, core/src/avm2/globals/flash/geom/transform.rs, render/src/perspective_projection.rs
Continued from https://github.com/ruffle-rs/ruffle/pull/19670
Continue to https://github.com/ruffle-rs/ruffle/pull/19405 ?
This PR refactors flash.geom.PerspectiveProjection computation logics from ruffle_core to ruffle_render.
We can use those later from inside ruffle_render.
=> avm2: Move PerspectiveProjection computation to render crate

core/src/backend/log.rs, core/src/context.rs, core/src/display_object/movie_clip.rs, scanner/src/logging.rs, tests/framework/src/backends/log.rs, tests/tests/swfs/avm1/placeobject_occupied_depth/output.txt, web/src/log_adapter.rs
Simulating traced Flash Player warnings improves our tests, because we can assert on certain code paths taken in our implementations.
=> core: Add avm_warning for simulating traced FP warnings

core/src/context.rs, core/src/display_object/avm1_button.rs, core/src/display_object/container.rs, core/src/display_object/loader_display.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs
We only need the movie to know whether the container is in AVM1 or AVM2 mode, so just store a boolean instead.
=> core: don't store the `SwfMovie` in `ChildContainer`

core/src/avm1/globals/bitmap_data.rs, core/src/avm1/globals/color_transform.rs, core/src/avm1/globals/shared_object.rs, core/src/avm1/globals/transform.rs, core/src/avm1/globals/xml.rs, core/src/avm1/globals/xml_node.rs, core/src/avm1/object.rs, core/src/avm1/object/script_object.rs, core/src/avm2/e4x.rs, core/src/xml/tree.rs
After this, we have six uses of GcCell left:
- AVM2 `VTable`, `Class`, `Domain`, and `TranslationUnit`;
- `BitmapDataWrapper`
- `MovieClip`
=> core,avm1,avm2: Remove more uses of GcCell

core/src/avm1/globals/local_connection.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm2/activation.rs, core/src/avm2/e4x.rs, core/src/avm2/globals/flash/display/bitmap_data.rs, core/src/avm2/globals/flash/display/loader.rs, core/src/avm2/globals/flash/display/loader_info.rs, core/src/avm2/globals/flash/display3D/context_3d.rs, core/src/avm2/globals/flash/net/local_connection.rs, core/src/avm2/globals/flash/net/shared_object.rs, core/src/avm2/globals/flash/net/xml_socket.rs, core/src/avm2/globals/toplevel.rs, core/src/avm2/globals/xml.rs, core/src/avm2/object/loaderinfo_object.rs, core/src/avm2/object/local_connection_object.rs, core/src/avm2/value.rs, core/src/context.rs, core/src/debug_ui.rs, core/src/display_object/avm2_button.rs, core/src/display_object/graphic.rs, core/src/display_object/movie_clip.rs, core/src/external.rs, core/src/loader.rs, core/src/player.rs, core/src/streams.rs
The name "swf" was ambiguous, because in case of a child SWF file, it won't reference that file, but the root SWF, even if the update context is passed to objects from the child SWF.
=> core: Rename `UpdateContext::swf` to `root_swf`

Cargo.lock, core/src/avm2/activation.rs, core/src/avm2/class.rs, core/src/avm2/function.rs, core/src/avm2/globals/flash/display/graphics.rs, core/src/avm2/method.rs, core/src/avm2/optimizer/optimize.rs, core/src/avm2/verify.rs, core/src/character.rs, core/src/display_object/movie_clip.rs, core/src/drawing.rs, core/src/font.rs, core/src/library.rs, render/src/shape_utils.rs, ruffle_gc_arena/Cargo.toml
When a field is only set once, using `OnceCell<T>` is better/clearer than `RefCell<Option<T>>`.
=> core: use `OnceCell/Lock`s where possible

core/src/avm1/globals/bitmap_data.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/avm2_button.rs, core/src/display_object/bitmap.rs, core/src/display_object/container.rs, core/src/display_object/edit_text.rs, core/src/display_object/graphic.rs, core/src/display_object/interactive.rs, core/src/display_object/loader_display.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs, core/src/display_object/text.rs, core/src/display_object/video.rs
Display objects are already a pointer, no need to take a pointer to a pointer.
=> core: Remove double self pointers

core/src/avm1.rs, core/src/avm1/globals/xml.rs, core/src/avm1/globals/xml_node.rs, core/src/avm1/object.rs, core/src/avm1/xml.rs, core/src/avm1/xml/iterators.rs, core/src/avm1/xml/tree.rs, core/src/xml.rs
`custom_unescape` was being used by AVM2 XML code, so I moved it to the toplevel `xml.rs`
=> core/avm1: Move AVM1-specific XML code into AVM1

core/src/avm2/amf.rs, core/src/avm2/class.rs, core/src/avm2/globals/avmplus.rs, core/src/avm2/globals/null.rs, core/src/avm2/globals/void.rs, core/src/avm2/object/class_object.rs, core/src/avm2/optimizer/optimize.rs, core/src/avm2/script.rs, core/src/avm2/value.rs, core/src/avm2/vtable.rs, core/src/debug_ui/avm2.rs, tests/tests/swfs/avm2/weird_superinterface_properties/test.toml
To avoid having to put (almost) every `VTable` field behind a `OnceLock`, this also changes the `Class/ClassObject` vtable initialization logic to fully replace the vtable object instead of mutating it in place.
=> avm2: remove `GcCell` in `VTable`

core/src/bitmap/bitmap_data.rs
`Vec::clear` doesn't actually free the backing memory, so replace with an empty vec instead.
=> core: properly free memory in `BitmapData::dispose`

tests/framework/src/test.rs
This patch adds some context, because without it the error messages are meaningless.
=> tests: Improve error messages when parsing {input,socket}.json

core/src/avm1/activation.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm2/globals/flash/display/sprite.rs, core/src/display_object/graphic.rs, core/src/display_object/movie_clip.rs
All display objects are now plain `Gc`s, which will allow future refactoring towards using `HasPrefixField` to handle the inheritance tree (as was done for AVM2 `Object`s)
=> core: Finish porting `MovieClip` away from `GcCell`

core/src/avm1/runtime.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/bitmap.rs, core/src/display_object/edit_text.rs, core/src/display_object/graphic.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/text.rs, core/src/display_object/video.rs
Only AVM1 MovieClips can execute AVM1 framescripts, so there's no reason to put non-`MovieClip` display objects in the AVM1 exec list, and no reason to have it defined as part of `DisplayObjectBase`.
=> avm1: Move the global execution linked list from `DisplayObjectBase` to `MovieClip`

core/src/avm2/error.rs, core/src/avm2/filters.rs, core/src/avm2/globals/Array.as, core/src/avm2/globals/VectorDouble.as, core/src/avm2/globals/VectorInt.as, core/src/avm2/globals/VectorObject.as, core/src/avm2/globals/VectorUint.as, core/src/avm2/globals/array.rs, core/src/avm2/globals/vector.rs, core/src/avm2/globals/vector_double.rs, core/src/avm2/globals/vector_int.rs, core/src/avm2/globals/vector_object.rs, core/src/avm2/globals/vector_uint.rs, core/src/avm2/value.rs, tests/tests/swfs/from_avmplus/as3/Vector/some/test.toml, tests/tests/swfs/from_avmplus/as3/Vector/some_initializers/test.toml
Completes #12321.
Also factored out some code into a separate function for the 1006 and 1034 errors as a bonus.
=> avm2: fix coercion to function error for Vector.some and Array.some

core/Cargo.toml, core/src/avm2/globals/flash/display3D/textures/texture.rs, core/src/avm2/object/context3d_object.rs, core/src/bitmap/bitmap_data.rs, core/src/bitmap/operations.rs, core/src/character.rs, core/src/debug_ui/avm2.rs, core/src/debug_ui/display_object.rs, render/canvas/src/lib.rs, render/src/backend.rs, render/src/backend/null.rs, render/src/bitmap.rs, render/src/utils.rs, render/webgl/src/lib.rs, render/wgpu/src/backend.rs, video/src/frame.rs
This is done by making `render::Bitmap` capable of holding borrowed pixel data, and by changing `core::bitmap::Color`'s internal representation to be compatible with what the render backend expects.
Slightly pessimizes `setPixel` & friends, as they now need to convert the ActionScript color representation (BGRA) into RGBA; this could be fixed by switching renderers to use BGRA internally, but I'm not sure how much work this represents or if it is even possible.
=> core/render: avoid copying pixels on bitmap CPU -> GPU syncs

core/src/avm2/globals/Date.as, core/src/avm2/globals/date.rs, core/src/avm2/object/date_object.rs, tests/tests/swfs/from_avmplus/ecma3/Exceptions/date_001_rt/test.toml, tests/tests/swfs/from_avmplus/ecma3/Exceptions/date_002_rt/test.toml, tests/tests/swfs/from_avmplus/ecma3/Exceptions/date_003_rt/test.toml, tests/tests/swfs/from_avmplus/ecma3/Exceptions/date_004_rt/test.toml
Replaces https://github.com/ruffle-rs/ruffle/pull/21030 .
Hopefully same approach could be also used to implement the same behavior for other classes doing this: `Function, MethodClosure, Error, Array, RegExp`. (note: `MethodClosure` is absent in Ruffle)
=> avm2: Make Date.prototype an instance of Date

.cargo/config.toml, tests/tests/swfs/from_avmplus/ecma3/JSON/regress/test.toml, tests/tests/swfs/from_avmplus/recursion/xml_functions/test.toml
Some tests require a bigger stack to pass.
=> tests: Increase minimum stack size

core/src/avm2/error.rs, core/src/avm2/globals/toplevel.rs, tests/tests/swfs/from_avmplus/regress/bug_538107/test.toml
Functions `decodeURI` and `decodeURIComponent` should not fail on invalid UTF-16 sequences.
See https://bugzilla.mozilla.org/show_bug.cgi?id=538107
=> avm2: Fix `decodeURI` failing on invalid UTF-16 sequences

.github/scripts/release.py, .github/workflows/release_nightly.yml
This PR adds publishing commits for nightly, but _only on tags_, not on the main branch.
* Downstreams can use the proper version (instead of having always 0.1.0, currently our builds have the proper version set)
* Downstreams don't have to work around including the version in metainfo (this PR does not implement that, but it makes it possible)
* The logic of creating a release commit for both stable and nightly can be the same (assuming we'll go forward with stable releases)
By downstreams I mean mostly Flatpak (but also build-from-source AURs, etc.).
TL;DR It makes maintaining Flatpak (and other downstreams) easier & reduces differences between release binaries and Flatpak (and other downstreams).
```
* <- nightly C
|
*
|
* <- nightly B
|
*
|
*
|
* <- nightly A
|
*
```
```
* <- nightly …
```
=> ci: Publish release commits for nightly

Cargo.lock, Cargo.toml, core/src/avm2/globals/flash/display/shader_job.rs, render/Cargo.toml, render/canvas/src/lib.rs, render/pixel_bender/Cargo.toml, render/pixel_bender/src/disassembly.rs, render/pixel_bender/src/lib.rs, render/pixel_bender/src/parser.rs, render/pixel_bender/src/tests.rs, render/src/backend.rs, render/src/backend/null.rs, render/src/filters.rs, render/src/lib.rs, render/src/pixel_bender.rs, render/src/pixel_bender_support.rs, render/webgl/src/lib.rs, render/wgpu/src/backend.rs, render/wgpu/src/filters/shader.rs, render/wgpu/src/pixel_bender.rs, render/wgpu/src/surface.rs
Pixel Bender parser, disassembly, and tests are pretty self contained, and can be used without the rest of the render crate, so move it to its own `pixel_bender` crate.
This will be very useful for https://github.com/ruffle-rs/ruffle/pull/21058.
=> render: Move Pixel Bender stuff to its own crate

web/packages/demo/src/navbar/samples.tsx
We don't define a type for the Ruffle logo SWF in swfs.json. That means its type is undefined, not null.
This fixes the Ruffle Logo entry not appearing in the Sample SWF dropdown (regressed by #20448)
=> demo: Check if SWF sample type is undefined, not null

core/macros/src/lib.rs, core/src/avm2/object.rs, core/src/display_object.rs, core/src/display_object/container.rs, core/src/display_object/interactive.rs
...and change the expansion of `#[no_dynamic]` to:
- be less error-prone, by triggering a compile-time error if the user tries to override a `#[no_dynamic]` method in a trait impl;
- produce better code, by moving the method body to the `enum` trait impl and delegating to it in the default method definition.
This reduces the size of the (desktop) release binary by ~150kB.
-------------------
Example of the new code generation:
```rs
#[automatically_derived]
#[doc(hidden)]
mod __TInteractiveObject_do_not_override {
pub trait NoDyn<'no_dyn> {}
impl NoDyn<'_> for () {}
}
pub trait TInteractiveObject<'gc>:
'gc + Clone + Copy + Collect<'gc> + Debug + Into<InteractiveObject<'gc>>
{
fn mouse_enabled<'no_dyn>(self) -> bool
where
(): __TInteractiveObject_do_not_override::NoDyn<'no_dyn>,
{
let mut …
```
=> core: Add `#[no_dynamic]` to many methods in `TDisplayObject` (and its subtraits)

.github/workflows/release_nightly.yml, .github/workflows/test_rust.yml, .github/workflows/test_web.yml
This is more just to see whether anything will fail a month from now...
See: https://github.blog/changelog/2025-07-31-github-actions-new-apis-and-windows-latest-migration-notice/#windows-latest-image-label-migration
=> ci: Switch Windows GHA runners to windows-2025

core/src/avm1/globals/bitmap_data.rs, core/src/avm1/globals/displacement_map_filter.rs, core/src/avm1/object.rs, core/src/avm2/globals/flash/display/bitmap.rs, core/src/avm2/globals/flash/display/bitmap_data.rs, core/src/avm2/globals/flash/display3D/textures/texture.rs, core/src/avm2/object.rs, core/src/avm2/object/bitmapdata_object.rs, core/src/avm2/object/context3d_object.rs, core/src/bitmap/bitmap_data.rs, core/src/bitmap/operations.rs, core/src/debug_ui/display_object.rs, core/src/display_object/bitmap.rs, core/src/loader.rs
This does make `bitmap_data.rs` uglier (it now has three copies of `fn height()` and similar methods), but on the other hand:
- The new names are clearer
- Most two-phase construction and `GcCell` handling are abstracted away:
```rs
// before
let bitmap_data = BitmapData::new_with_pixels(...);
let bitmapdata_wrapper = BitmapDataWrapper::new(GcCell::new(mc, bitmap_data));
let bitmapdata_avm2 = BitmapDataObject::from_bitmap_data_internal(..., bitmapdata_wrapper);
// after
let bitmapdata = BitmapData::new_with_pixels(mc, ...);
let bitmapdata_avm2 = BitmapDataObject::from_bitmap_data_internal(..., bitmapdata);
```
- It's a nice middle step towards future BitmapData refactors (including possibly data sharing), possibly without having to touch all these places again.
=> core: Rename BitmapData->BitmapRawData, wrap it in new BitmapData

core/src/display_object.rs
On certain architectures (e.g. 32-bits Android), `f64`s are only 4-aligned, so we need to increase the alignment of `DisplayObjectBase` to always match with its subclasses.
=> core: Force correct alignment for `DisplayObjectBase`

core/src/avm1/globals/button.rs, core/src/avm1/globals/movie_clip.rs, core/src/avm1/globals/text_field.rs, core/src/avm1/globals/video.rs, core/src/avm2/globals/flash/display/bitmap.rs, core/src/avm2/globals/flash/display/bitmap_data.rs, core/src/avm2/globals/flash/display/interactive_object.rs, core/src/avm2/globals/flash/display/movie_clip.rs, core/src/avm2/globals/flash/media/video.rs, core/src/avm2/globals/flash/text/engine/text_line.rs, core/src/avm2/globals/flash/text/static_text.rs, core/src/avm2/globals/flash/text/text_field.rs, core/src/avm2/object/loaderinfo_object.rs, core/src/context_menu.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/avm2_button.rs, core/src/display_object/bitmap.rs, core/src/display_object/edit_text.rs, core/src/display_object/graphic.rs, core/src/display_object/loader_display.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs, core/src/display_object/text.rs, core/src/display_object/video.rs, core/src/player.rs, core/src/prelude.rs, exporter/src/lib.rs
Like #21052, but for display objects.
=> core: Reduce `TDisplayObject` boilerplate

render/src/bitmap.rs
Previous function
```rust
pub fn for_region(x: u32, y: u32, width: u32, height: u32) -> Self {
let a = (x, y);
let b = (x.saturating_add(width), y.saturating_add(height));
let (min, max) = ((a.0.min(b.0), a.1.min(b.1)), (a.0.max(b.0), a.1.max(b.1)));
Self {
x_min: min.0,
y_min: min.1,
x_max: max.0,
y_max: max.1,
}
}
```
Did make sure that x_max and y_max could not be less then x_min and y_min. But this is already ensured because saturating_add won't wrap around and the arguments to the function (width, height) will never be negative since they're unsigned.
This commit removes the extra checks while keeping the functionallity equal.
=> core: Make code more readable for PixelRegion (nit)

.config/nextest.toml
The test is flaky:
* https://github.com/ruffle-rs/ruffle/actions/runs/17018310796/job/48243817289
* https://github.com/ruffle-rs/ruffle/actions/runs/17109193806/job/48526039895
=> chore: Mark `avm2/stage3d_errors_atf` test as flaky

.github/workflows/download_translations.yml, .github/workflows/upload_texts.yml
To avoid these situations:
- https://github.com/ruffle-rs/ruffle/actions/runs/17138673876/job/48620893530
- https://github.com/ruffle-rs/ruffle/actions/runs/17138737889/job/48621278812
=> chore: Update package index before installing tools in l10n GHA workflows

desktop/packages/linux/aur/ruffle-nightly-bin/PKGBUILD
With this change the AUR package will now support ARM64
* Fixes https://github.com/ruffle-rs/ruffle/issues/21273
=> Updated PKGBUILD file to support Arm64

.github/workflows/test_rust.yml, Cargo.lock, tests/Cargo.toml, tests/framework/src/test.rs, tests/tests/regression_tests.rs
Known failures do not contribute to coverage, because we do not verify their output, instead we only check if they start passing.
This PR adds the `RUFFLE_TEST_OPTS` variable, which can contain Ruffle tests specific options separate from `cargo test` (specifically `--ignore-known-failures`). In the future it can also contain e.g. test filtering capabilities (slow/fast tests).
=> ci: Ignore known failures when running coverage

core/src/avm2/object/local_connection_object.rs, tests/tests/swfs/from_shumway/localconnection/test.toml
This is probably not quite correct, but with a proper error constructor, there's an extra 'Error: ' in the error text, failing the test. Hopefully someone knows the proper way to do this
=> avm2: Correct error text in LocalConnectionObject::run_method

core/src/avm2/object/function_object.rs, tests/tests/swfs/from_avmplus/ecma3/Expressions/e11_6_1_3/test.toml, tests/tests/swfs/from_avmplus/ecma3/Expressions/e11_6_2_1/test.toml, tests/tests/swfs/from_avmplus/ecma3/FunctionObjects/e15_3_1_1_1_rt/test.toml, tests/tests/swfs/from_avmplus/ecma3/FunctionObjects/e15_3_2_1_1_rt/test.toml, tests/tests/swfs/from_avmplus/ecma3/FunctionObjects/e15_3_5_2_rt/test.toml
Functions should apparently be set as their own constructors, at least according to the tests.
=> avm2: Set functions as their own constructors

tests/tests/swfs/from_shumway/avm1/hitarea/input.json, tests/tests/swfs/from_shumway/avm1/hitarea/test.toml
The input.json of this test was wrong, it rolled cursor over a wrong area, which caused the test to pass despite Ruffle not handling hitArea properly.
=> tests: Fix from_shumway/avm1/hitarea

core/src/debug_ui/domain.rs
This PR fixes duplicate widget ID warnings in the DomainListWindow debug panel caused by reusing the same IDs for multiple domains and classes in egui.
- Wraps each Domain and Class in a unique ui.push_id scope based on the pointer address.
- Ensures that CollapsingState and CollapsingHeader widgets have unique IDs per frame.
- Removes the "First use / Second use of widget ID" warnings in the debug UI.
- Does not affect SWF execution or domain memory handling; purely a debug UI fix.
This improves readability and usability of the debug panel, especially when inspecting large SWFs with multiple domains and classes.
=> debug_ui: Fix egui widget ID collisions in DomainListWindow

.github/workflows/test_rust.yml
Currently SWF tests coverage cannot cover some files, that's why this patch excludes them from tests.
=> ci: Exclude unrelated crates from coverage

desktop/src/gui/controller.rs
Mmapping system fonts used by SWFs proved to be successful, so do the same with GUI fonts.  This patch improves memory usage on desktop.
Tests on my system showed memory usage drop of around 300 MB.
=> desktop: Mmap GUI fonts instead of loading them into memory

core/src/avm2/events.rs, core/src/avm2/globals/flash/display/display_object.rs, core/src/avm2/globals/flash/display/display_object_container.rs, core/src/avm2/globals/flash/display/loader_info.rs, core/src/avm2/globals/flash/display/simple_button.rs, core/src/avm2/globals/flash/display/sprite.rs, core/src/avm2/globals/flash/display/stage.rs, core/src/avm2/object/event_object.rs, core/src/debug_ui/display_object.rs, core/src/display_object.rs, core/src/display_object/avm1_button.rs, core/src/display_object/avm2_button.rs, core/src/display_object/bitmap.rs, core/src/display_object/container.rs, core/src/display_object/edit_text.rs, core/src/display_object/graphic.rs, core/src/display_object/interactive.rs, core/src/display_object/loader_display.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/stage.rs, core/src/display_object/text.rs, core/src/display_object/video.rs, core/src/focus_tracker.rs, core/src/player.rs
This also adds a method `TDisplayObject::object2_or_null` to reduce boilerplate
See #19522
=> chore: Make `TDisplayObject::object2` return `Option<StageObject>`

core/src/avm2/globals/flash/display3D/context_3d.rs, core/src/avm2/object/context3d_object.rs, web/src/lib.rs
It doesn't make sense to accept self by reference for `Context3DObject` and `RuffleHandle`.
=> refactor: Clean up references to Copy objects

tests/README.md
Reformat docs & add missing test.toml options
=> tests: Document missing test.toml options

web/packages/core/texts/en-US/context_menu.ftl
This fixes case in context menu entries. In English it should be title case.
=> web: Use title case for context menu entries

core/src/avm2/error.rs, core/src/avm2/globals/namespace.rs, core/src/avm2/regexp.rs, core/src/avm2/specification.rs, core/src/debug_ui/avm1.rs, core/src/display_object/edit_text.rs, core/src/display_object/morph_shape.rs, core/src/display_object/movie_clip.rs, core/src/display_object/text.rs, core/src/focus_tracker.rs, core/src/font.rs, core/src/html/text_format.rs, desktop/src/app.rs, desktop/src/cli.rs, desktop/src/gui/theme.rs, desktop/src/log.rs, desktop/src/preferences/storage.rs, desktop/src/util.rs, render/src/utils.rs, swf/src/types.rs, swf/src/types/color_transform.rs, swf/src/write.rs
This PR covers the rest of cases where we referenced trivially copyable objects.
=> refactor: Do not reference trivially copyable objects

core/src/display_object/movie_clip.rs, core/src/display_object/text.rs, core/src/display_object/video.rs, render/naga-agal/src/builder.rs, render/pixel_bender/src/disassembly.rs, swf/src/avm1/write.rs
For realsies now, I missed some last time :(
It doesn't make sense to reference trivially copyable objects, so just remove references to them when not needed.
=> refactor: Fix the rest of references to trivially copyable objects

Cargo.toml, core/src/avm2/specification.rs, render/naga-agal/src/builder.rs
This lint will check if we're referencing trivially copyable objects.
=> chore: Enable `trivially_copy_pass_by_ref` clippy lint

web/packages/selfhosted/wdio.conf.ts
The level "info" produces a lot of spam. Each message sent between the browser and the client is logged as info. Changing it to "warn" preserves important output only, including console logs.
=> web: Change log level to "warn" for tests

core/src/avm2/method.rs, core/src/avm2/traits.rs, core/src/avm2/value.rs, swf/src/avm1/types.rs, swf/src/avm1/write.rs, swf/src/avm2/types.rs, swf/src/avm2/write.rs, swf/src/types.rs
It's better to pass small objects as value than to reference them.
=> swf: Implement Copy for small types

web/packages/selfhosted/test/integration_tests/context_menu/test.ts, web/packages/selfhosted/test/integration_tests/context_menu_escaping_body/test.ts, web/packages/selfhosted/test/integration_tests/context_menu_position/test.ts, web/packages/selfhosted/test/integration_tests/external_interface/test.ts, web/packages/selfhosted/test/integration_tests/keyboard_input/test.ts, web/packages/selfhosted/test/integration_tests/missing_default_fonts/test.ts, web/packages/selfhosted/test/integration_tests/mouse_wheel_avm2/test.ts, web/packages/selfhosted/test/integration_tests/programmatic_events/test.ts, web/packages/selfhosted/test/integration_tests/url_rewrite_rules/test.ts, web/packages/selfhosted/test/polyfill/object_flashvars/test.ts, web/packages/selfhosted/test/polyfill/object_flashvars_in_url/test.ts, web/packages/selfhosted/test/utils.ts
Before this patch there could be potential race conditions on traces if they were produced asynchronously by the SWF. The old logic waited for any trace and then asserted on all available traces, which meant that we could include some unintended traces or assert before all traces have been produced.
The new approach ensures that we wait for as many traces as we need.
=> web: Improve asserting on traces in tests
