ruffle-rs/ruffle

- web/js-src/element.js
- web/js-src/ruffle-embed.js
- web/js-src/ruffle-object.js
I've added bugfixes for the way Newgrounds dynamically adds objects to the page. This allows Newgrounds to work in Ruffle (when it decides to serve a Flash object).
Another branch, which isn't ready to PR yet, will allow self-hosting Ruffle. It will also add an extension opt-out and interdiction control so that sites can indicate how much, if any, they want Ruffle to work with them. I expect Newgrounds to use those functions, so this PR won't be testable after that functionality is merged.
> Newgrounds support

- core/src/avm1.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/movie_clip.rs
- core/src/avm1/object.rs
- core/src/avm1/value.rs
- core/src/backend.rs
- core/src/backend/navigator.rs
- core/src/player.rs
- core/tests/integration_tests.rs
- desktop/Cargo.toml
- desktop/src/main.rs
- desktop/src/navigator.rs
- web/Cargo.toml
- web/src/lib.rs
- web/src/navigator.rs
This is a draft PR for interactions between ActionScript and the browser - namely GetURL, in it's various forms. ~~It relies on @Dinnerbone's PR #52 in order to work - please do not consider merging this PR in unless that PR has already been merged. It is technically independent of the WebExtension PR but isn't very useful without it. (I've been testing on a temporary merged branch of this PR and #53.)~~
The following are implemented:
- ~~Parsing of returned form data as new AVM1 locals~~
GetURL functionality which implies the loading or execution of remote SWF content into a sprite, legacy `_layer` target, or movie clip is currently considered out of scope for this PR. Such functionality issues warnings in the console if used. (Rationale: We don't have test cases for this yet, I don't …
> AVM1 browser interactions

- core/src/avm1.rs
- core/src/backend/audio.rs
- core/src/backend/audio/decoders.rs
- core/src/backend/audio/decoders/adpcm.rs
- core/src/backend/audio/decoders/mp3.rs
- core/src/backend/audio/decoders/pcm.rs
- core/src/movie_clip.rs
- desktop/Cargo.toml
- desktop/src/audio.rs
- desktop/src/main.rs
- web/src/audio.rs
* Remove the dependency on `rodio` on desktop; only use `cpal` and `sample` instead
* Support looping and start/end points in event sounds
* Support `StopSounds`/`stopAllSounds()` action
> Remove rodio dependecy; support looping sounds

- core/src/backend/audio.rs
- core/src/movie_clip.rs
- desktop/src/audio.rs
- web/src/audio.rs
Implements the "sync" setting on Flash event sounds:
* Event always plays the sound (independent of the timeline)
* Start plays the sound only if there is not already an instance of the sound playing
* Stop will stop any active instances of a particular sound.
> Implement "Event/Start/Stop" event sounds

- core/src/avm1/globals/math.rs
As per @Dinnerbone 's suggestion in https://github.com/ruffle-rs/ruffle/issues/67, assuming I understood correctly. A lot of these values come out at something nice/a constant exists for (0.0, PI, PI/2 etc), happy to use those instead of just calling the f64 method if preferred, although feels like we might end up in the same situation & need approx crate as in my previous PR.
> Fix math tests

- core/src/avm1.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/movie_clip.rs
- core/src/avm1/object.rs
Nothing uses them yet, but we will need to change any versioned global method to use it.
Opening a PR before then in case anyone else wants to go make that change, and to avoid conflicts in Object
> Allow for dynamic properties in Object

- core/Cargo.toml
- core/src/matrix.rs
This PR is intended to add testing around the contents of matrix.rs.
I've pulled in the approx crate in order to test in a way that shouldn't fail on slightly different setups.
A couple of things I've assumed in the tests and I just wanted to check is desired behaviour; 
- The `invert_not_possible` tests. First of all flash's built in use of this should always be invertible so should not occur. However you can create matrix of any values in AS. The all 0 case gives NaN as every result. In flash from my brief testing it gave the identity matrix back. The other case gives Infinities; in flash it gives something different (I can't remember the result will update this PR with the result if it's important). In my PR I've assumed current behaviour is desired, but can update if it's not.
- …
> Add matrix tests

- core/src/movie_clip.rs
- swf/src/read.rs
From the spec:
> The DefineText2 tag is almost identical to the DefineText tag. The only difference is that Type 1 text records contained within a DefineText2 tag use an RGBA value (rather than an RGB value) to define TextColor.
[p171](https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf)
So this is basically the same as the existing functions with that small change. I have also renamed the existing `DefineText` functions to have `_1` at the end to follow the convention used elsewhere. 
Tested this with [DefineText2-MX.swf](https://github.com/ruffle-rs/ruffle/blob/master/swf/tests/swfs/DefineText2-MX.swf). Result before changes was a blank canvas and the following output:
```
[2019-10-04T21:13:41Z ERROR ruffle_core::library] Tried to instantiate non-registered …
```
> DefineText2 Support

- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/function.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/object.rs
- core/src/avm1/scope.rs
- core/src/avm1/value.rs
- core/src/movie_clip.rs
- core/src/player.rs
- core/src/tag_utils.rs
- swf/src/read.rs
This PR constitutes an implementation of activation objects, scope chains, and user-defined functions for ActionScript 1/2 (AVM1) code. User functions are defined as a reference to some part of the SWF they were loaded from, as well as the version of that SWF (so we can emulate version-specific behavior).
> AVM1 DefineFunction support

- core/src/font.rs
- core/src/text.rs
Per SWF19, shape coordinates in DefineFont3 are at 20x the size of
DefineFont1/2.
> core: Render DefineFont3 at proper size (fixes #47)

- core/Cargo.toml
- core/src/avm1.rs
- core/src/avm1/function.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/movie_clip.rs
- core/src/avm1/object.rs
- core/src/avm1/scope.rs
This adds a dependency on enumset, as I think it's so much more ergonomic than `true, false, false` everywhere.
The three property attributes `DontEnum`, `ReadOnly` and `DontDelete` are implemented and correctly set (as far as I can tell) for all places that set properties right now. It includes tests to ensure they're behaving correctly, too.
A side effect of this is that I also made virtual properties enumerable, they weren't previously.
> Added object property attributes

- swf/src/avm1.rs
- swf/src/avm1/read.rs
- swf/src/avm2/read.rs
- swf/src/error.rs
- swf/src/lib.rs
- swf/src/read.rs
- swf/src/write.rs
* Custom swf::error::Error type added to handle various errors
in SWF parsing.
* Invalid parsing of tags/AVM1 ops results in a Error::ParseError
that can include info about the underlying failure.
* Implement Display for these errors. Output descriptive
names for the tag/opcode when it fails to parse.
* Handle out of bounds reads in avm1::Reader::read_slice.
Previously this would panic, now it returns an io::Error.
Closes #85.
> Improve error handling in SWF parsing

- core/src/player.rs
- swf/Cargo.toml
- swf/src/read.rs
- swf/src/types.rs
Some SWFs are compressed incorrectly, often with incorrect
compressed/uncompressed lengths, causing the zlib decoders
to vomit if you try to decompress them fully. However, often times
the data still decompresses all the way to the End tag, and we
still want to try to play it even if it's corrupt.
Now these errors only omit a warning, and we'll continue to run
the SWF.
Addresses #86.
> swf: Try to recover from incorrect zlib streams

- core/src/backend/render.rs
- core/src/bitmap.rs
- core/src/character.rs
- core/src/lib.rs
- core/src/library.rs
- core/src/movie_clip.rs
- desktop/src/render.rs
- web/src/render.rs
Converts the Bitmap character to a proper display object. This can
be instantiated directly in a PlaceObject tag in SWFv9 movies,
compared to the previous versions which indirectly references
bitmaps from Shape tags.
> core: Add Bitmap display object

- core/Cargo.toml
- core/src/player.rs
- swf/Cargo.toml
- swf/src/lib.rs
- swf/src/read.rs
- swf/src/write.rs
Fixes #90.
LZMA decoding still has some issues, but this should at least get the lzma feature compiling again.
Also enables the feature by default on desktop. (Need a pure Rust implementation for wasm).
> swf: Fix compiling with lzma feature

- core/src/avm1.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/test_utils.rs
- core/src/avm1/value.rs
Implements `Boolean`, `Number` and `isNaN` functions. I have a few more more or less ready to go but wanted to limit this PR to check the general approach first.
Some functions behave differently (e.g. `as_bool`) depending on the swf version. As these functions are not coming from within avm1.rs but globals.rs I needed to make this public so that it can be passed into Value, however maybe there is a nicer way to do this?
I assume this function (and the others such as `as_bool` and `as_string`) is meant to behave as flash would convert a value to string, as opposed to for purely internal use. I originally implemented the string section to follow ECMA-262 9.3 ToNumber. However, experimentally, it looks like `"Infinity"` doesn't go to `Number(Infinity)` and whitespace isn't trimmed (any …
> Implementations of some global functions

- core/src/backend/audio/decoders.rs
- core/src/backend/audio/decoders/adpcm.rs
- core/src/tag_utils.rs
- desktop/src/audio.rs
- web/src/audio.rs
Fixes stream sounds with ADPCM compression.
Stream sounds usually are the same as an event sound, but with the audio data distributed across the frames of the a `MovieClip` in `SoundStreamBlock` tags. However, ADPCM is an exception, where each `SoundStreamBlock` contains a duplicated ADPCM audio header. The previous code was reading this header as audio data, causing corrupt sound. Now the decoder is reset for each block, causing the header to be re-parsed, and the sound to play correctly.
> audio: Fix corrupt playback of ADPCM stream sounds

- core/src/player.rs
- desktop/src/main.rs
The timing on desktop was causing the movie to run too slow,
causing it to get out of sync. Now it should run at the correct
speed.
> desktop: Improve animation sync

- core/src/backend/render.rs
- desktop/src/render.rs
The premultiplied alpha was not properly considered when there was
a color transform on a bitmap. Now the shader unmultiplies the
alpha before applying the color transform, and the remultiplies it.
Fixes some artifacts on bitmaps in https://www.newgrounds.com/portal/view/124117 on the desktop player.
> desktop: Fix incorrect rendering of bitmaps w/ color transforms

- core/src/avm1.rs
- core/src/avm1/movie_clip.rs
- core/src/backend/audio.rs
- core/src/display_object/movie_clip.rs
- core/src/player.rs
- desktop/src/audio.rs
- web/src/audio.rs
- web/src/lib.rs
* Initial implementation of syncing "stream" sounds with their MovieClip timeline. The stream automatically stops and restarts when the MovieClip stops/seeks.
* Skip the initial "SeekSamples" samples in MP3-encoded event sounds to account for encoder delay.
* More accurate looping event sound behavior.
TODO:
* Handle SeekSamples value when MovieClips run a goto.
* Keep player in sync with stream audio if frames are dropped.
* Clean up web audio backend (will try moving everything over to `ScriptProcessorNode`).
> audio: Improve audio sync

- core/src/backend/audio.rs
- desktop/src/audio.rs
- web/Cargo.toml
- web/src/audio.rs
Implements event sound envelopes for the `StartSound` tags. Created in the Flash IDE by setting the "Effect" on an event sound instance. Does not apply to stream sounds because the effect gets baked into the stream.
> audio: Event sound envelopes

- core/src/avm1.rs
- core/src/avm1/tests.rs
Due to some recent cleanups, there's a double-borrow panic in `locals_into_form_values`. This causes certain Homestar Runner menus to panic - as well as anything that uses `getURL` or `ActionGetUrl`. This adds a regression test and bug fix.
> Form values regression

- core/src/backend/render.rs
- core/src/display_object/movie_clip.rs
- core/src/library.rs
- desktop/src/render.rs
- web/src/render.rs
Some SWFs have empty JPEGTables tags. The code now ignores these. Split out the JPEGTables handling code into `backend::render::glue_tables_to_jpeg` and cleaned this up to avoid potential out-of-bounds indexing.
Fixes #116
> core: Handle empty JPEGTables tags (fix #116)

- desktop/src/audio.rs
- desktop/src/main.rs
Some more quick fixes due to the updated API in winit 0.20.
* Using cpal with the latest winit was crashing immediately on Windows due to https://github.com/RustAudio/cpal/pull/348. I moved to cpal initialization code into another thread to workaround this.
* Properly use the new `ControlFlow` API introduced in winit. Previously it was using `ControlFlow::Poll` along with `sleep` which caused a busy-loop on windows. Now I use `ControlFlow::WaitUntil`.
> desktop: Fixes for winit 0.20

- core/Cargo.toml
- core/src/avm1.rs
- desktop/Cargo.toml
When you turn on the feature `avm_debug`, Ruffle will start tracing all actions & stack history. Example output:
```
[2019-11-20T23:04:49Z DEBUG ruffle_core::avm1] Stack push 0: Value::Number(100.0)
[2019-11-20T23:04:49Z DEBUG ruffle_core::avm1] Stack push 1: Value::Number(150.0)
[2019-11-20T23:04:49Z DEBUG ruffle_core::avm1] Action: Subtract
[2019-11-20T23:04:49Z DEBUG ruffle_core::avm1] Stack pop 1: Value::Number(159.0)
[2019-11-20T23:04:49Z DEBUG ruffle_core::avm1] Stack pop 0: Value::Number(100.0)
[2019-11-20T23:04:49Z DEBUG ruffle_core::avm1] Stack push 0: Value::Number(50.0)
```
This is intended to help debug avm1 actions, and figure out where that pesky Unknown is coming from.
> AVM debug tracing

- core/src/avm1.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/test_utils.rs
- core/src/avm1/value.rs
This cleans up tests by creating a reusable `test_method` macro, which takes an object and a method name.
It also allows tests to check results per-version.
> Test improvements

- core/src/avm1/globals.rs
- core/src/avm1/value.rs
~This will look much prettier, and be easier to both read & write more once ruffle-rs#143 is merged in.~
There we go :)
> Add more Number(x) tests, and corrected primitive_as_number to match

- web/js-src/ruffle-imports.js
- web/src/audio.rs
`AudioBuffer.copyToChannel` does not work on Safari, so switch to
using `getChannelData` to fill the audio buffers.
Limitations in wasm-bindgen prevent us from actually modifying the
data returned by `getChannelData` on the Rust side, so import a JS
function to fill the audio buffer (js-src/ruffle-imports.js).
> web: Avoid `copyToChannel` on Safari

- swf/src/avm2/read.rs
- swf/src/avm2/types.rs
- swf/src/avm2/write.rs
- swf/src/test_data.rs
SWF obfuscaters will produce an opcode stream that can contain invalid data/not tightly packed ops, so we should not try to parse the opcodes ahead of time. Instead return the method bodies as a byte buffer.
The SWF in question also uses some undocumented ops which we will eventually need to impelement (see https://www.free-decompiler.com/flash/docs/as3_pcode_instructions.en.html), but this will fix the panic for now.
Fixes #156.
> avm2: Don't immediately parse ABC opcode. (#156)

- core/src/avm1.rs
- core/src/player.rs
Also warn and clear the stack if it is not empty after every AVM execution.
> avm1: Fix some issues with stack over/underflow

- core/src/avm1.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/mouse.rs
- core/src/avm1/listeners.rs
- core/src/avm1/value.rs
- core/src/context.rs
- core/src/player.rs
This should let us create the other system listener types with a macro and few lines of registration.
> Refactor system listeners into a reusable system

- core/src/avm1/globals/mouse.rs
- core/src/backend/input.rs
- desktop/src/input.rs
- desktop/src/main.rs
- web/src/input.rs
- web/src/lib.rs
As #204 is in, this will no longer be super annoying to have.
The return value logic looks like a mistake, but it's what the documentation says.
I initially had this in `InputBackend` as I figured "mouse is input", but ultimately both implementations needed to work over their renderer counterparts, and in the future we need a "set this movieclip to be a hand or a pointer", so renderer made sense.
> Implement Mouse.show() and Mouse.hide()

- core/src/avm1.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/sound.rs
- core/src/avm1/object.rs
- core/src/avm1/sound_object.rs
- core/src/backend/audio.rs
- core/src/display_object/movie_clip.rs
- desktop/src/audio.rs
- web/src/audio.rs
This implements basics of the AVM1 Sound object:
* Sound.attachSound
* Sound.start
* Sound.stop (partial)
* Sound.duration
This is enough for support of most games, and will fix missing sounds in, for example, Alien Hominid and Marvin Spectrum.
Full implementation is a little involved; Particularly, you can attach a Sound object to a particular movie clip, allowing you to adjust the volume/pan of all sounds of that MC and its children. Each display object has a sound transform that gets concatenated similar to their normal display transform.
Also, Sound.position will require a new audio backend method. On Web, this will be annoying because the Web Audio API doesn't provide an easy way to get the position of an `AudioBufferSourceNode`.
> avm1: Rough pass of Sound object

- web/extension/webpack.config.js
- web/js-src/load-ruffle.js
This PR transitions the WebExtension build system to a standard Webpack configuration very similar to the self-hosted version of Ruffle.
Previously, the WebExtension used webpack only to aggregate JavaScript modules, and a separate `build.sh` would manually invoke WASMPack in `no-modules` mode. At some point in the past, `build.sh` was removed and it's functionality replaced with a series of Webpack plugins that resulted in the same build product output. Shortly thereafter (29754ea), the extension stopped being buildable, because a `wasm-bindgen` JS snippet was added to the project. This was then merged without issue as our CI system does not appear to build the extension. However, you can't use JS snippets in `no-modules` mode, which is why we can't build the extension.
I originally …
> Use Webpack to build and package Ruffle WASM file in extension

- swf/src/avm1/read.rs
- swf/src/avm1/write.rs
- swf/src/test_data.rs
Adobe's documentation has the flags in opposite order to what they should be. This fixes that.
> Fix misparsing of `ActionGetURL2`.

- core/src/avm1/globals.rs
- core/src/avm1/globals/key.rs
- core/src/backend/input.rs
- desktop/src/input.rs
- web/src/input.rs
This implements the following of #257:
I'm not even going to try to touch `getAscii` right now. Ouch. Someone else can feel free...
No tests for these because we still don't have a good way to test input, and the constants are just constants.
> Implemented more of Key

- core/src/lib.rs
- web/Cargo.toml
- web/src/render.rs
This PR fixes worst-case performance when drawing large numbers of shapes to the stage per frame (e.g. text). In a particularly bad case (HSR Toons Page) this PR goes from seconds-per-frame to 60fps.
Performance was increased largely due to two improvements made to rendering:
1. Replacing the SVG-in-an-image rendering mode with directly invoking `Canvas` draw commands
2. Avoiding the use of canvas filters whenever possible
First, the SVG rendering path. Previously, each shape in the SWF would be converted into an SVG, then into a `data:` url as part of an image, and then we used `drawImage` commands, canvas transforms, and color filters to manipulate the shape as the SWF rendering model allows. This is adequate for small numbers of shapes; however, each `drawImage` triggers multiple paint …
> Shape-drawing performance improvements

- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
When a movie clip or button is used as a mask, the masking will be
disabled if that object has no children; the maskee will be
completely visible. However, an empty movie clip inside an empty
movie clip successfully masks!
An EditText can also not be used as a masker (although it can be
wrapped inside a movie clip, and then the text successfully masks).
Add a `TDisplayObject::allow_mask` trait method that will
return whether the object can be used as a mask.
This fixes characters not being visible in Dad 'n' Me.
> core: Empty objects can not be used as a mask

- core/src/backend/audio/decoders.rs
- core/src/display_object/movie_clip.rs
Fixes #222, stream audio prematurely ending on desktop.
Fixes #370, stream audio stopping when the clip naturally loops.
> audio: Stream audio fixes

- core/src/display_object/movie_clip.rs
Stops a clip's stream sound when it is removed from the scene graph.
> core: Stop stream sounds when a clip is removed

- core/src/backend/input.rs
- core/src/player.rs
- desktop/src/input.rs
- web/src/input.rs
It doesn't feel like Flash without having the hand cursor display
when hovering over buttons. First pass at implementing this;
core communicates which mouse cursor to use via
`InputBackend::set_mouse_cursor`.
TODO: Hand cursor only displayed for Button display objects
currently. Movie clips should also display this when they are in
"button mode" (when a button mouse event is set on them in AVM1,
or `buttonMode` property in AVM2).
> input: Change cursor on button hover, add InputBackend::set_mouse_cursor

- core/src/events.rs
- core/src/player.rs
- desktop/src/input.rs
- web/src/lib.rs
Implement `keyUp` clip event, which uses basically the same logic as `keyDown`.
Fixes #339.
> core: Implement keyUp event

- core/src/loader.rs
- core/src/player.rs
- core/src/tag_utils.rs
Fixes for various errors caused by the merging of `moviefetch`, as suggested by @Herschel. These should fix #410 and #411, at least to the point of no longer panicking.
This PR does the following:
- Makes `SwfMovie::from_data` a falliable method (e.g. returns `Result`). Previously, it would either panic (due to a copy-pasted `unwrap`) or just log an error and attempt to play an empty movie; both of which are the wrong behavior and also inconsistent with each other. Callers of this method now handle the error properly depending on the context.
- Fix a race condition in which a premature `Load` event triggered by the clip would cancel all in-progress loads. Now, loads will only be removed from the list if they have already completed (either by replacing the movie in question or by erroring …
> LoadManager resiliency

- web/js-src/ruffle-embed.js
- web/js-src/ruffle-object.js
- web/js-src/ruffle-player.js
If an embed tag or object tag is missing the Flash MIME type/ActiveX class attribute, Ruffle will check if the source file ends with the ".swf" extension to determine whether it's a Flash embed. This matches current browser behavior.
Additionally, toss out any errors when trying to copy attributes from the embed to the Ruffle element. Previously, bogus attributes would throw in `setAttribute` and cause Ruffle to error out.
Fixes #457.
> web: Polyfill is more lenient with embed and object tags (fix #457)

- web/js-src/polyfills.js
- web/js-src/public-api.js
Addresses #464. Use `document.getElementsByTagName` to find all
object and embed tags in the document. For dynamic content,
we keep these live collections around, and re-check them whenever
a MutationObserver fires.
Also enables the dynamic content polyfill by default.
> web: Simplify polyfill code

- web/src/render.rs
If a page was reloaded, bitmaps in canvas shapes could be cached, causing incorrect rendering. This seems to occur because of the image being decoded immediately when it's cached, as opposed to asynchronously when not (image.naturalWidth will be 0 vs non-zero). This applied to shapes using the newer canvas command rendering path.
Tweak the creation order of the canvas pattern to avoid this issue.
> web: Fix #412, incorrect bitmap rendering when cached

- web/js-src/plugin-polyfill.js
- web/js-src/public-api.js
Fix a few issues preventing Ruffle from getting along with SWFObject.
First, we install our plugin version spoof immediately when the Ruffle script first executes. This also requires the Ruffle script tag to be before the SWFObject script tag.
Secondly, the MIME type description for the plugin spoof was changed to match Flash; previously it had an additional "Ruffle" text that broke the SWFObject version parsing.
> web: Make polyfill work with SWFObject (fix #448)

- core/src/avm1/globals.rs
- core/src/avm1/globals/button.rs
- core/src/avm1/globals/display_object.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/display_object/button.rs
First implementation of Button object. Hook up to the button
display object and run onRelease etc. methods as appropriate.
Pull out common display object methods into globals::display_object.
> avm1: Implement Button object

- core/src/avm1.rs
Anything other than `for (v in object)` should just not enumerate and continue as normal.
> avm1: Don't crash when enumerating non-objects, it's a silent fail

- core/src/player.rs
- desktop/src/main.rs
- web/src/lib.rs
Don't call `render` from `Player::tick`; instead, require the
frontends to explicitly call `render` when they wish to redraw.
The frontend can query `Player::needs_render` to see if the stage
is dirty and needs a redraw. Update desktop and web to use this
new method.
This fits better with the newer winit event loop model, which
requires explicitly calling `request_redraw`, and should avoid
spurious renders.
> core: Clean up core loop

- Cargo.lock
- Cargo.toml
- render/common_tess/src/lib.rs
- render/webgl/Cargo.toml
- render/webgl/shaders/bitmap.frag
- render/webgl/shaders/color.frag
- render/webgl/shaders/color.vert
- render/webgl/shaders/gradient.frag
- render/webgl/shaders/texture.vert
- render/webgl/src/lib.rs
- web/Cargo.toml
- web/common/Cargo.toml
- web/common/src/lib.rs
- web/src/lib.rs
This adds a WebGL1 rendering backend for use on web.
* Moved render backends to subcrates in the top-level `render` directory because backends may share common code and potentially work on multiple platforms
* `lyon` based tessellation code was moved to `render/common_tess` and is used by both the desktop and WebGL backends
* This also paves the way for a WebGPU backend which could be used on both desktop and web (#14)
* Opinions welcome (is this a good organization for the render backends? Should we do this for all backends? Should we just cram the tessellation stuff into `core`?)
Needs general testing, and still some TODOs:
-  [x] No "Click to Play"/play button; will start with a blank screen, click on it to start the movie
> WebGL render backend

- .circleci/config.yml
- .github/workflows/test_build.yml
This also increases the test coverage away from just Ubuntu / Node 10 / Rust Stable, to a matrix of:
- OS: Ubuntu, Mac, Windows
- Node: 10 LTS, 12 LTS
- Rust: Stable, Beta, Nightly
It seems that a full test suite takes about 10 minutes, as opposed to the 60 minutes today with the circleci setup.
Rust nightly builds are setup to not fail the overall workflow, however betas will. Today, it seems we are failing beta Clippy checks - I'll submit a separate PR for that.
I left the existing publish steps on circleci for now. We can change that over later.
> Switch PR & commit testing to use Github Actions

- web/extension/build/js/lv0.js
- web/extension/build/manifest.json
In my testing, this causes the extension to load ruffle somewhere in the middle of the head as the document is being loaded, rather than at the end of the head after the document is finished loading, which seems to be enough to fix this issue. This fix adds `"load_at": "document_start"` to the `manifest.json`, which makes `lv0.js` run as soon as the page starts loading. `lv0.js` was modified to use a `MutationObserver` & insert the extension setup code & ruffle.js in 2 script tags, 1 after the other. The `MutationObserver` was necessary because, on Chrome, Chromium, & Chromium-based browsers, scripts loaded at `document_start` run before the head element is loaded, causing script insertions to either fail when trying to insert into the head or not work when inserted directly into the …
> Load ruffle extension at start of page load(fixes #501 & #448 with extension)

- core/src/backend/render.rs
- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/font/text_format.rs
- core/src/player.rs
- core/src/shape_utils.rs
- render/canvas/src/lib.rs
- render/common_tess/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
- swf/src/types.rs
(+1 small core utility method)
The drawing API ultimately comes down to a DistilledShape, instead of a Shape, which is basically the output of the previous `swf_shape_to_paths` method. Shape was the swf-specific encoding of the same data, but drawing API is one layer of abstraction removed.
I've also merged begin_frame and clear because in wgpu, they're the same action - we ended up clearing twice.
> Small render API improvements

- core/src/avm1.rs
- core/src/avm1/debug.rs
- core/src/player.rs
The shortcut is `CTRL+ALT+V`. It's structured to be similar to the output that Flash produces.
Right now it's printing lots of builtins because we aren't properly marking our builtins as `DontEnum`/etc. We're also hit quite hard by #66.
> Add keyboard shortcut to dump every variable

- web/js-src/ruffle-embed.js
- web/js-src/ruffle-object.js
This addresses #542 in some cases(with SWFObject). Also, I found that this unbreaks Google Docs, Sheets, &c. because they have a momentarily inserted flash object with no src or data attribute.
> Don't polyfill elements with no src or data attributes

- core/src/avm1/value.rs
- swf/src/write.rs
Casting floats-to-int could be treacherous in Rust, and it is currently undefined behavior on stable if the value wasn't representable in the target type. A PR just landed in nightly that defines these to saturate. This broke a few things in our code that were incorrectly relying on this undefined behavior.
Fix these methods to avoid undefined behavior and properly handle the edge cases. Fixes #579.
See:
https://doc.rust-lang.org/1.22.1/book/first-edition/casting-between-types.html#numeric-casts (old behavior)
https://github.com/rust-lang/rust/pull/71269
https://github.com/rust-lang/rust/issues/10184
> core: Fix undefined wrapping behavior triggered by Rust nightly (fix #579)

- web/js-src/ruffle-player.js
- web/js-src/shadow-template.js
- web/src/lib.rs
If the WebGL renderer creation failed further along (after the `getContext` call), then Ruffle would not successfully fallback to the Canvas backend because only a single context may be created on a canvas, with no direct way to destroy a previous context.
This moves the HTML canvas from the HTML template to be created by the Rust code. Each backend will recreate the canvas when it tries to instantiate.
> web: Fallback to canvas render backend in more cases (fix #545)

- render/wgpu/src/lib.rs
- render/wgpu/src/utils.rs
Gradient spread modes and focal point were implemented in the shader, but the uniforms were not hooked up. Now these should function as expected.
> wgpu: Hook up gradient spread mode and focal point

- web/extension/build/js/lv0.js
Per #600 & this from @kmeisthax : 
"Also, the code tracks which polyfills have been launched and refuses to launch them again
so it's probably unneeded"
> Remove unneded code from lv0.js

- core/src/backend/render.rs
- core/src/display_object/movie_clip.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
I didn't do this for register_shape as I couldn't find a way that would fail today. We ignore broken segments but don't spoil the whole shape.
> Make RenderBack::register_bitmap* methods return a Result

- web/packages/core/src/version-range.js
- web/packages/core/test/version-range.js
Neither of the methods worked before, which means all of our version negotiations would have always failed. Not sure how having both the extension & selfhosted works today, with that in mind.
> web: Made VersionRange actually work, and add tests for it

- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
- core/src/events.rs
- core/src/player.rs
Adds support button-style event handlers (such as `onPress` and `onRelease`) to movie clips. This allows many more movies and games to advance beyond the preloader (for example, https://www.newgrounds.com/portal/view/592902), because putting onRelease handlers on a movie clip is common.
MovieClips support all button functionality and turn into "button mode" when a button event is added to them, either via `on(...)` or by setting a method property like `clip.onRelease`. When in button mode, they can grab mouse focus even when obscured and also show the hand cursor when hovered (by default). 
* `ButtonEvent` is removed and replaced with `ClipEvent` (which also contains all button events)
* Some cleanup of the clip event firing. There is still more work to do here, but this is allows a …
> core: Support button event handlers on MovieClips

- web/packages/demo/www/index.html
- web/packages/demo/www/index.js
This commit adds HTML Opt-Groups separating Games and Animations on the web demo sample dropdown menu. There are also a few tiny styling changes. Mainly the addition of a transition duration to the logo image, as well as changing "max-device-width" to "max-width" on a media query so that the "mobile" view is shown if you scale down the window on desktop browsers.
> Added Opt-Groups for Web Demo

- core/src/avm1/globals/string.rs
Fixes #633 
Changed ```>``` to ```>=``` so 0 is considered a valid index
> core: Fix incorrect String.charCodeAt bounds check (close #633)

- web/packages/core/src/polyfills.js
- web/packages/selfhosted/test/polyfill/classic_frames_injected/test.js
- web/packages/selfhosted/test/polyfill/iframes_injected/test.js
The frame polyfill wasn't working if the ruffle script was loaded after the frame & it wouldn't call the original `onload` handler if one was set.
> Fix frame polyfill

- core/src/display_object/movie_clip.rs
- core/src/player.rs
- swf/src/read.rs
This should help with the occasional issue we get about avm2 content.
> core: Print swf version on startup, and warn when we run into avm2

- web/packages/demo/www/index.js
The indexing into the list of sample SWFs could be incorrect
depending on the order of the JSON data. Now we store the SWF info
directly on the option element for easy access, regardless of order.
> demo: Fix incorrect sample SWF loading

- desktop/src/main.rs
When opening a `.swf` file through a file association (open with), an unnecessary command line window is shown. This removes that extraneous window.
> Remove unnecessary command line window on Windows

- core/src/avm1.rs
- core/src/avm1/debug.rs
- core/src/avm1/function.rs
- core/src/avm1/globals/array.rs
- core/src/avm1/globals/color.rs
- core/src/avm1/globals/function.rs
- core/src/avm1/globals/matrix.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/globals/object.rs
- core/src/avm1/globals/point.rs
- core/src/avm1/globals/rectangle.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/listeners.rs
- core/src/avm1/object.rs
- core/src/avm1/scope.rs
- core/src/avm1/script_object.rs
- core/src/avm1/sound_object.rs
- core/src/avm1/stage_object.rs
- core/src/avm1/super_object.rs
- core/src/avm1/test_utils.rs
- core/src/avm1/value.rs
- core/src/avm1/value_object.rs
- core/src/avm1/xml_attributes_object.rs
- core/src/avm1/xml_idmap_object.rs
- core/src/avm1/xml_object.rs
- core/src/display_object/movie_clip.rs
- core/src/font/text_format.rs
- core/src/player.rs
This reduces the boilerplate of simply accessing values quite a lot.
This will totally merge conflict with #670 - I'll rebase whichever one comes second :)
> Handle ReturnValue silently in most APIs

- web/packages/selfhosted/test/polyfill/utils.js
- web/packages/selfhosted/wdio.conf.js
This will fix #657
After extensive research we eventually discovered that all of the time is being spent downloading ruffle.js from the local test server, not actually executing anything. We'll need to investigate that, but we can at least rest a little easy knowing that we're not doing anything crazy bad.
> Increase polyfill test timeout to 30 seconds

- core/src/player.rs
Thanks to #676, we have a version string. _root also has a $version property that should mirror `System.capabilites.version`.
This allows Nanaca Crash to boot.
> core: Set $version on root

- core/src/avm1/globals/sound.rs
- core/src/backend/audio.rs
- core/src/backend/audio/decoders.rs
- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
- desktop/src/audio.rs
- web/src/audio.rs
Remove `unimplemented` calls when encountring unsupported codecs
such as Nellymoser. Instead, return an Error that can be
gracefully handled.
Fixes #549. Allows Nanaca Crash to progress further in-game.
> audio: Don't panic on unimplemented codecs

- core/src/avm1/value.rs
Clippy added a new lint that we can't actually fix until the 'or_patterns' syntax is stabilized. Let's just ignore it. And also ignore the fact that we can't ignore it on stable. 👀
> Fix clippy on nightly

- web/src/audio.rs
This would incorrectly stop all audio nodes whenever a Stop sound
event was encountered.
> web: Fix WebAudioBackend::stop_sounds_with_handle (fix #752)

- .gitattributes
Right now it thinks we're part AngelScript, and gives incorrect syntax highlighting
> chore: Mark .as files as ActionScript on github

- core/src/string_utils.rs
In IB, `swf_char_to_lowercase` is easily the top entry on a profile, getting roughly 15-20% of samples. It does a binary search for every character, for every string, in every case insensitive property access.
This change brings down total runtime of case insensitive accesses by ~5x on wasm.
Long term, it might be a good idea to adapt avmplus code? https://github.com/adobe/avmplus/blob/master/core/StringObject.cpp#L1955
> Add a fast path for ASCII case conversions

- core/src/avm1/script_object.rs
- core/src/avm1/stage_object.rs
- core/src/avm1/value.rs
- core/src/html/text_format.rs
- core/src/property_map.rs
- core/src/xml/namespace.rs
- core/src/xml/tree.rs
Nothing incredible, but there's a few places we're allocating Strings and we don't need to be. PropertyMap, for example, very rarely needs ownership of Strings so everything passing in an allocated new String is just a waste.
> Reduce String allocations

- core/src/avm1/activation.rs
- core/src/avm1/function.rs
Per the comments in #767
This reduces the size of `Executable` to 16 bytes, down from 128. It is often cloned, such as once on every function call.
> Made Executable::Action take in a Gc to Avm1Function

- core/src/display_object/movie_clip.rs
- swf/src/read.rs
The tag parsing code in `core` vs. the parsing code in `swf` has gotten a little muddled about who is responsible for slicing the tag data when parsing the SWF. The `swf` functions expect the underlying reader to contain the tag data only, but `core` will often call the `swf` functions with a reader containing the entire SWF data. This can cause huge memory usage as many tags without an explicit length would read data to the end of the SWF instead of the end of the tag (see #808).
As a stop-gap, this adjusts the tag parsing in `MovieClip` to make a sub-reader with a slice of the tag data, avoiding unbounded reads. TODO: The next task will be to go through `swf` and change it to operate on [u8] slices instead of arbitrary streams, which should clean this up better.
> core: Limit tag parsing to slice of tag data

- Cargo.lock
- desktop/Cargo.toml
- desktop/src/main.rs
Remove #![windows_subsystem = "windows"], which launched us as a
GUI app on win32. A GUI app has the side effect of hiding output to
stdout/stderr when launched from the command-line.
Since Ruffle is primarily still a CLI interface, let's revert back to a console
win32 app so that we can display output. Instead, we can hide the console
if we detect we were not launched from the
command line.
This does have the side effect of having the console window appear for a
moment on startup even when launched from the destkop, but this seems to be
the best thing to do on Windows for now. Maybe we'll revisit this when we have more of a GUI.
(see https://devblogs.microsoft.com/oldnewthing/20090101-00/?p=19643).
> desktop: Revert to console app on Win32

- core/src/avm1/activation.rs
We should probably add features to the test matrix.
> avm1: Fix compile error when using avm_debug flag

- core/src/avm1/globals.rs
The following weren't being collected, so if anything used them they could segfault:
```rust
pub color_transform: Object<'gc>,
pub context_menu: Object<'gc>,
pub context_menu_item: Object<'gc>,
```
Let's just derive all the collects, there's no reason this needs to be custom.
> Fix gc unsoundness with missing collects in SystemPrototypes

- core/src/avm1/string.rs
Example:
>Stack push 6: String(AvmString { source: Owned("hybrid") })
> Made AvmString debug actually show contents of the string

- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/function.rs
- core/src/avm2.rs
- core/src/avm2/activation.rs
- core/src/avm2/object.rs
- core/src/player.rs
Defaults to off, but I figure this should probably be a command-line argument or API argument later.
This (ab)uses constant functions to make sure that code is compiled out when the feature is turned off.
> Allow toggling avm_debug output on and off with ctrl+alt+d

- CONTRIBUTING.md
- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/fscommand.rs
- core/src/avm1/function.rs
- core/src/avm1/globals/load_vars.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/object.rs
- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/sound.rs
- core/src/avm1/globals/stage.rs
- core/src/avm1/globals/system.rs
- core/src/avm1/globals/system_security.rs
- core/src/avm1/globals/text_field.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
- core/src/lib.rs
- core/src/player.rs
Changes:
- Variable dumping is now locked behind `avm_debug` as the cost of `avm_debug` isn't as high anymore
- New error/warn printing when `avm_debug` is enabled, to show where the error/warn happened
- Updated instructions for debugging ActionScript in documentation
Example of new errors/warnings:
>Object method onLoadInitHandler is not callable -- in broadcastMessage / onLoadInit(string, movieclip) / [Anonymous](string, movieclip) / dispatchEvent(object) core.ruffle.js:1:36557
>
>Cannot enumerate Undefined -- in broadcastMessage / onLoadInit(string, movieclip) / [Anonymous](string, movieclip) / dispatchEvent(object) / dispatchQueue(object, object) / [Anonymous](object) / onGlobalCrumbsLoaded(object) / setWorldCrumbs(undefined)
> Debugging improvements - warnings, errors, documentation

- core/src/player.rs
I fixed an unfortunate bug caused by some of the initialization changes I made in `movieorigin`. This ensures there is always a root movie, so the user can't catch the player half-initialized.
> Fix crash when user presses "play" way too quickly.

- web/packages/extension/build/_locales/en/messages.json
- web/packages/extension/build/_locales/es/messages.json
- web/packages/extension/js/settings.js
I overlooked this one message when creating the extension settings pull request(adding the infrastructure for internationalization & Spanish translations was included). Also, we should probably try to get a few people on board to translate the extension into other languages.
> Add "Settings Saved" to locales

- Cargo.lock
- desktop/Cargo.toml
- desktop/build.rs
- desktop/src/main.rs
- exporter/Cargo.toml
- exporter/src/main.rs
- scanner/Cargo.toml
- scanner/src/main.rs
`structopt` has been merged into `clap`, so move the desktop apps over to `clap` 3.0 beta. Additionally, add the Git revision to the desktop version info (addressing #574).
> desktop: Switch to clap 3.0 and add Git commit to version info

- web/packages/selfhosted/test/polyfill/pdf/test.js
It's been working for a couple months, but I just forgot to remove the `.skip` from the call.
> Enable pdf test, which works now

- web/packages/core/src/shadow-template.js
Removes highlight when tapping/holding on a Ruffle instance.
> web: Prevent mouse/tap highlighting on player (fix #861)

- core/src/html/text_format.rs
- core/src/xml/namespace.rs
- core/src/xml/tree.rs
Small fixes for a few issues with HTML parsing:
* Fix for duplicated characters when parsing HTML entities (#1026)
* Add support for numeric HTML entities, decimal and hex (#1026)
* HTML entities are case insensitive
* If an invalid HTML entity is parsed, output the text as-is
* HTML tags/attributes are case insensitive (#1021) (different Flash version could emit differently cased HTML).
The true fixes for these would involve rolling a specific HTML parser; for example, opening and closing tags with different cases would currently still break.
> text: Fix some issues with HTML parsing

- desktop/src/main.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/utils.rs
Help output now reads:
```
Ruffle 0.1.0-nightly (6bff48d6 2020-08-25)
Mike Welsh <mwelsh@gmail.com>
USAGE:
ruffle_desktop.exe [OPTIONS] <FILE>
ARGS:
<FILE>    Path to a flash movie (swf) to play
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-g, --graphics <graphics>    Type of graphics backend to use. Not all options may be supported by your current
system. Default will attempt to pick the most supported graphics backend [default:
default]  [possible values: default, vulkan, metal, dx12, dx11]
-p, --power <power>          Power preference for the graphics device used. High power usage tends to prefer
dedicated GPUs, whereas a low power usage tends prefer integrated GPUs. Default will
pick the best device depending on the status of …
```
> Add graphics options to desktop CLI

- .github/workflows/release_nightlies.yml
Leaving circleci nightly script for now. We can remove it later if we want to, after this proves it works out.
I've set it up to not make a release if there's no commit that day, to avoid release spam in periods of inactivity.
It also doesn't upload the files to the s3 bucket. I don't know if that's something we'll want to keep?
Also no demo. I'm not sure if we should do that here or in another repo (we could host the demo in https://github.com/ruffle-rs/ruffle-rs.github.io perhaps?), but it's not something people would actively download so it didn't fit putting on a release page.
> Release nightlies through github releases

- core/src/property_map.rs
String hashing for property/variable accesses are still one of the biggest things on profiles.
On my Firefox profiles, this change drops time spent hashing by half and total time spent in tick() by 10%. Also makes Meat Boy slightly - but noticeably - less choppy on my machine (still not anywhere near fluid though).
> Use fnv hash in property_map.

- .github/workflows/release_nightlies.yml
Author is when it was actually made but committer is when it was actually added to the branch.
> Fix nightly generation not triggering if an older PR lands

- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/avm2/globals.rs
- core/src/backend.rs
- core/src/backend/log.rs
- core/src/context.rs
- core/src/player.rs
- core/tests/regression_tests.rs
- desktop/src/main.rs
- exporter/src/main.rs
- web/packages/core/src/ruffle-player.js
- web/packages/selfhosted/test/polyfill/embed_default/test.js
- web/packages/selfhosted/test/polyfill/embed_insensitive/test.js
- web/packages/selfhosted/test/polyfill/embed_missing_type/test.js
- web/packages/selfhosted/test/polyfill/object_MIME_insensitive/test.js
- web/packages/selfhosted/test/polyfill/object_clsid_insensitive/test.js
- web/packages/selfhosted/test/polyfill/object_data/test.js
- web/packages/selfhosted/test/polyfill/object_default/test.js
- web/packages/selfhosted/test/polyfill/object_ie_only/test.js
- web/packages/selfhosted/test/polyfill/object_missing_type/test.js
- web/packages/selfhosted/test/polyfill/object_missing_type_and_classid/test.js
- web/packages/selfhosted/test/polyfill/object_unexpected_string/test.js
- web/packages/selfhosted/test/polyfill/object_wrong_type/test.js
- web/packages/selfhosted/test/polyfill/utils.js
- web/src/lib.rs
- web/src/log_adapter.rs
This will let us test things for reals in the browser soon (ie ExternalInterface or params), and could be a useful API to expose.
Primary difference between this and capturing via `log` is that you can't capture per movie that way.
One thought for consideration: Could we scrap `log` entirely (in ruffle_core) and make all warnings etc go through the backend, so we can provide all info per-movie and include fancier things like location in movie as a structural part of the message? Is that a terrible idea?
> Add trace capturing API to core & web, and use it in browser based tests

- web/packages/core/src/ruffle-object.js
- web/packages/core/src/ruffle-player.js
- web/packages/core/src/shadow-template.js
- web/src/lib.rs
If a panic happens (either a rust hard panic, or something that makes a specific player unusable) then this screen will show up:
If you click on "view error details", you'll get a big dump that you can copy paste from:
The hope is that users won't ever see this, of course, but we should make it as easy as possible to identify and report any scenario that makes this happen.
If it's a full rust panic, then we poison ruffle on this page and prevent further players from being made - the reason being, the panic probably caused us to be in a bad state and may not have even had a player trigger it at all. We shouldn't take the risk that the next player works, and do what we can to put this in the users face so they can come report it to us.
Future goals should be to fill out the details even …
> Add a panic screen for web

- core/src/backend/render.rs
- core/src/display_object/edit_text.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
| Name | Old | New | Expected |
| ---- | --- | --- | -------- |
| [edittext_align](https://raw.githubusercontent.com/ruffle-rs/visual-tests/86f2d6baf205c43fe2075f818ef5066542e3d1bd/tests/text/edittext_align/test.swf) | ![](https://raw.githubusercontent.com/ruffle-rs/visual-tests/86f2d6baf205c43fe2075f818ef5066542e3d1bd/tests/text/edittext_align/actual.png) | ![](https://user-images.githubusercontent.com/317625/93266097-e57e1300-f7a9-11ea-8a49-c910c749fcdf.png) | ![](https://raw.githubusercontent.com/ruffle-rs/visual-tests/86f2d6baf205c43fe2075f818ef5066542e3d1bd/tests/text/edittext_align/expected.png) |
| [edittext_bullet](https://raw.githubusercontent.com/ruffle-rs/visual-tests/86f2d6baf205c43fe2075f818ef5066542e3d1bd/tests/text/edittext_bullet/test.swf) | …
> Mask texts to hide overflows

- core/src/html/text_format.rs
Previously color defaulted to 0% alpha, causing text to be
invisible if the text field did not specify a defualt color.
> text: Default color for text spans should be black

- core/src/avm1/globals/sound.rs
The functions are just stubs currently so this shouldn't change any
behavior.
> core: Fix registered function names for Sound object

- render/webgl/shaders/gradient.frag
- render/webgl/src/lib.rs
Increase the number of colors allowed in gradients allowed by WebGL to 15. Also clamp the color count to 15 in case we get too many colors (previously would panic). Addresses #1214.
> webgl: Bump gradient color count to 15

- render/webgl/Cargo.toml
- render/webgl/src/lib.rs
- web/src/lib.rs
* Clamp the MSAA sample count to the amount returned by WebGL MAX_SAMPLES constant. This was intended already, but the value was mistakenly not used in the renderbuffer creation.
* Return an error if WebGL fails to create the multisampled renderbuffer. Previously this failed silently, and the WebGL backend tried to run but couldn't render. Returning an error allows us to fallback to the canvas backend. 
Addresses #1185, allowing it to fall back to canvas. However, in that specific case, the renderbuffer creation somehow fails even though MAX_SAMPLES indicates we have support for the MSAA mode. This still requires investigation (why does it fail? Maybe we can fall back to 2x or no AA instead of bailing out all the way to the canvas backend).
> webgl: Return error if MSAA renderbuffer cannot be created

- core/src/backend/audio.rs
- core/src/player.rs
- desktop/src/audio.rs
- web/packages/core/src/ruffle-player.js
- web/src/audio.rs
- web/src/lib.rs
Adds a suspend_audio method to compliment prime_audio on WebAudioBackend, as well as logic in player.rs on the set_is_playing method to suspend audio when is_playing is set to false. Exposes pause method for the ruffle player in JavaScript with logic to display the play button when paused.
I'm always learning! So please let me know if I need to fix something.
I tested the pause by adding a pause button to the web demo page with a click event. Something like this below:
```html
<button id="pause">Pause</button>
<script>
document.getElementById("pause").addEventListener("click", function() {
document.getElementById("player").pause()
}, false);
</script>
```
> web: Add pause method for web player

- core/src/avm1/activation.rs
- core/src/avm1/fscommand.rs
- core/src/loader.rs
This fixes #1145 and it's cinematic 24FPS DDoS attacks. Or at least it should - @Toad06 pls confirm.
Notably, this behavior was already covered by the tests, but the buggy implementation broke the failure mechanism on the test. I have no idea how to improve the test to work around this, but I can manually confirm that it no longer tries to load a file every *frame* in the movie in http://www.annie-cordy.com/disco/discographie80.html.
This covers both `GetUrl` and `GetUrl2`, both of which use empty URLs to signal an unload. Ruffle's load manager semantics are just different enough to make that little hack not work, so we have to just check for empty URLs in both actions.
> Actually unload movies when we get an empty URL in GetURL & GetURL2

- Cargo.lock
- desktop/Cargo.toml
- desktop/src/audio.rs
- exporter/Cargo.toml
sample renamed into dasp. Switch to this crate and also use the
latest git revision, where I submitted some PRs to fix compiler errors on nightly.
Also remove unnecessary sample dependency in exporter Cargo.toml.
> chore: Switch from sample to dasp crate

- web/packages/core/src/polyfills.js
- web/packages/selfhosted/test/polyfill/crossorigin_broken_cors/expected.html
- web/packages/selfhosted/test/polyfill/crossorigin_broken_cors/index.html
- web/packages/selfhosted/test/polyfill/crossorigin_broken_cors/test.js
- web/packages/selfhosted/test/polyfill/utils.js
In my testing, this fixes #1138
My frame polyfill code incorrectly assumed that the frame polyfill would only fail @ 1 point in the polyfilling process & I put a `try{...}catch(){...}` statement there. We can't polyfill cross-origin frames from within the site unfortunately(a limitation imposed by the browser), so the best we can do is catch the error(The extension can load into all frames with an option in the `manifest.json`).
> Add more try/catch's to stop error spam crashing sites(fix #1138)

- .github/workflows/release_nightlies.yml
- README.md
- web/packages/demo/README.md
Upload the nightly web demo to GitHub Pages via GitHub Actions pushing to https://github.com/ruffle-rs/demo as opposed to using to upload to S3.
> ci: Upload nightly web demo to GitHub Pages

- README.md
It makes the badges more compact.
> Remove "Github Actions" from badges because we don't use circleci anymore

- Cargo.lock
- core/src/backend/render.rs
- core/src/display_object.rs
- core/src/display_object/edit_text.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/Cargo.toml
- render/wgpu/src/lib.rs
- render/wgpu/src/pipelines.rs
Change the usage of the stencil buffer to avoid running out of stencil bits when too many nested masks are active. This could be seen in some movies/games like Achievement Unlocked.
Use the increment/decrement stencil ops to indicate masked areas. Each level of masking increments the stencil buffer in the masked area. This also cleans things up on wgpu which requires us to make pipeline states in advance; now we only need a few stencil states for masking as opposed to hundreds.
This does require an extra draw of the mask to decrement the stencil buffer when the mask is popped. `RenderBackend::deactivate_mask` was added to handle this; any draw between `deactivate_mask` and `pop_mask` should decrement the stencil value (on backends that care about it). TODO: We could get away with drawing …
> render: Fix masking issues on wgpu/webgl backends

- Cargo.lock
I know there's bug fixes in, for example, gfx-memory - so let's take what's out.
> chore: Run `cargo update` and pull in newer versions of dependencies

- web/package-lock.json
- web/package.json
- web/packages/core/webpack.config.js
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
The two breaking changes were:
* Removal of `jsonpFunction`, unique naming is now automatic (see https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-unique-naming)
* wasm must be explicity enabled via `experiments.syncWebAssembly` (https://webpack.js.org/configuration/experiments/)
* TODO: How does this differ from `experiments.asyncWebAssembly`? Can we use that instead?
> chore: Bump to webpack 5

- desktop/src/executor.rs
- desktop/src/task.rs
A task in our executor would never return to the `Ready` state if it yielded, causing it to never complete once pending. Reset the task to the ready state once it wakes so that it can continue to make progress.
> desktop: Switch task to ready state on wake

- Cargo.lock
- core/src/loader.rs
- desktop/Cargo.toml
- desktop/src/main.rs
- desktop/src/navigator.rs
Loads movies via URL when possible.
Proxies for HTTP and HTTPS can be set via --http-proxy and --https-proxy respectively.
> desktop: Support URL paths and Proxy options

- web/packages/core/webpack.config.js
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
Fixes #1354.
webpack5 added automatic publicPath detection (see https://webpack.js.org/migrate/5/). Our JS code tries to do automatic path detection on its own (public-path.js), which may have been conflicting with this. I was unable to produce the specific error locally, but it seems to have something to do with the way drupal dynamically inserts the script element (using jquery replaceWith?). The page in #1354 also uses a manually set `public_path` config setting for Ruffle.
Disable the automatic detection in all of the webpack configs for now, which should match the webpack 4 behavior.
> web: Disable automatic publicPath in webpack configs

- desktop/src/audio.rs
- web/src/audio.rs
An issue in the generational-arena crate (https://github.com/fitzgen/generational-arena/issues/30) allowed stale references to remain valid after a `clear`. This would sometimes cause sounds to not be removed in the WebAudio backend. Added a workaround, and added a Drop impl to the WebAudio backend to consistently clean up sound instances.
> audio: Fix for sounds not stopping (fix #1315)

- core/src/context.rs
- core/src/display_object.rs
- core/src/player.rs
If a masker is placed inside a masker, the inner mask is inactive and
instead renders as normal, masked by the outer mask. Properly
handle this case on the core side by only pushing new masks if we
are not currently drawing the mask stencil.
Maskee inside maskee still functions as expected. (i.e., a clip
using a mask  can be masked itself).
> core: Properly handle masker-inside-masker (fix #1347)

- core/src/backend/audio/decoders/pcm.rs
It looks like the mono and stereo cases were mistakenly swapped for uncompressed 8-bit sounds `PcmDecoder::next`.
This pull request simply swaps them to the correct order.
Particularly, this bug affected the ring sound in [Ultimate Flash Sonic](https://www.newgrounds.com/portal/view/151706), which is uncompressed and 8-bit.
> core: Fix uncompressed 8-bit sounds

- Cargo.lock
- swf/Cargo.toml
- swf/src/avm1/read.rs
- swf/src/avm1/types.rs
- swf/src/test_data.rs
While switching swf to return slices, I noticed ActionPush was
potentially allocating a huge vector by mistake (it was allocating based on `end_pos` and not `length`).
Switch to SmallVec<[Value; 4]> to fix this and avoid the
allocation in general (this was fairly high up in the profiler).
TODO: Return an iterator instead of any sort of vec.
> avm1: Switch to SmallVec for ActionPush

- web/packages/core/.eslintrc.json
- web/packages/core/src/ruffle-player.js
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
Now the menu will look like this on nightlies:
This commit exposes a big issue we have in our build system for web stuff right now. Technically core and selfhosted aren't building and packaging - the end users (selfhosted, extension and demo) are. Need to revisit that.
> web: Include git details into the build

- README.md
Add line to the Readme stating that the Visual C++ Redistributable is required for Ruffle Desktop on Windows
> Add Visual C++ Redist info

- core/src/display_object/movie_clip.rs
Renders drawing API behind siblings in the same clip.
Along with #1483 this fixes the rest of the rendering problems in the non-AS3 widgets in #1098
> avm1: Swap rendering order of MovieClip

- web/packages/extension/build/_locales/en/messages.json
- web/packages/extension/build/_locales/es/messages.json
@Justin-CB did a great work translating Ruffle into Spanish.
I hope some polishing could make it better.
I also replaced `...` with `…` (the proper Unicode character) in both English and Spanish.
BTW, are there other translation files than this one?
Many thanks for your good work.
> improve the Spanish translation

- web/src/lib.rs
Don't panic if LocalStorage fails to be created.
> web: Fail gracefully if LocalStorage is unavailable (fix #1590)

- core/src/avm1/activation.rs
- core/src/tag_utils.rs
From what I've heard on the grapevine, obfuscation tools like to do some dirty, nasty tricks and hide AVM1 code inside of unknown tags. This code is later accessed by backwards references outside of the current function data stream. We obviously fail to handle such references as we dutifully check bounds whenever indexing embedded data streams (e.g. an AVM1 function). This results in obfuscated code returning immediately.
This PR relaxes the bounds check so that any valid substream of the decoded SWF data is allowed to be constructed, even if it lies outside the current one. We still treat execution beyond the end of the current stream boundary as an implicit return; but otherwise illegal backwards references are now allowed, as well as defining functions or with/try scopes inside of …
> Relax bounds checks when executing AVM1 code

- core/src/display_object/button.rs
In https://github.com/ruffle-rs/ruffle/issues/1603, I found a situation where a button could trigger a rollout event, even after moving to a frame where the button isn't loaded anymore.
After looking around the codebase a bit, it seems like there is a [check meant to prevent this situation.](https://github.com/ruffle-rs/ruffle/blob/master/core/src/player.rs#L770), but it seems like this check wasn't working because - unlike all other kinds of display object - the Button doesn't actually have a line in its unload function that flags it as removed.
As far as I can tell, after this change the behaviour does now match what flash player does.
> core: Fix issue where unloaded buttons can still trigger mouse rollout events (close #1603)

- web/packages/core/src/ruffle-player.js
The `maxX` and `maxY` calculation assumed the player covers the whole viewport. Now it takes into account `rect.width` and `rect.height`.
Also, I noticed that the context menu doesn't work well in touch devices. Maybe we should consider disabling it for such devices?
> web: Improve context menu positioning

- swf/src/read.rs
- swf/src/write.rs
Even though `onClipEvent(construct)` was added in SWFv7, it is not version-gated and will still run in an SWFv6 file in a v7+ player. Some out-of-spec SWFs in the wild actually rely on this. Remove the SWF version check to allow the event to run.
Fixes #1424.
> swf: Allow construct clip events in SWFv6

- core/src/display_object/movie_clip.rs
Avoid a panic on truncated SWFs where the final tag does not have enough data. Fixes panic in #1583.
> core: Avoid panic on truncated SWF (fix #1583)

- web/packages/core/src/shadow-template.js
Should resolve https://github.com/ruffle-rs/ruffle/issues/1669
This should make the alignment correct on all browsers. `position: absolute` is relative to nearest ancestor that has `position: absolute | relative`. In this case it's parent has it set so this should mean it goes to correct position regardless.
> Fix play button alignment in web

- web/packages/demo/README.md
- web/packages/demo/www/index.js
Resolves https://github.com/ruffle-rs/ruffle/issues/1642
Allows the specification of an initial file via ?file=synj1.swf. If no match is found, it will instead just use the first demo. When doing so I also noticed the README.md was slightly out of date so have updated accordingly. Happy to split off into a separate PR.
> Allow file selection via query params in web demo

- web/packages/core/src/config.ts
- web/packages/core/src/index.ts
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/demo/www/index.js
`player.load("url")` == `player.load({url: "...."})`
`player.load({data: ....})`
Also options like parameters, autoplay and muteOverlay are now options of the load - but can be inherited from the player or from global.
> Merge streamSwfUrl and streamSwfData into a singular 'load' method

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
- Fonts are no longer inherited, Arial is used instead
- Play button is smaller and shares same styling as unmute button
- Context menu text is always aligned to the left, added drop shadow for visibility
- Panic screen text displays in white instead of black (it's much easier to read this way)
- CSS is cleaner and less redundant
Opinions on the new play button and context menu styling are welcome.
> Refinements to meta user interface (attempt 2)

- core/src/player.rs
Use millisecond timestamp from `chrono::DateTime` to seed the RNG as this is available on all platforms.
Longer term, it might be good to have a `PlayerBuilder` that takes care of wiring up the `Player` along with seeding the RNG.
Fixes #1182.
> core: Seed RNG with timestamp (fix #1182)

- core/src/display_object/edit_text.rs
This fixes #1193
As far as I can tell, the correct behaviour on invalid xml (which html is being coerced into) is to stop where the error occurred and not parse any further. That's what this does now.
> Fix panic loading 'invalid-ish' html in text fields

- web/packages/core/src/ruffle-object.ts
- web/packages/selfhosted/test/polyfill/embed_missing_src/expected.html
- web/packages/selfhosted/test/polyfill/embed_missing_src/index.html
- web/packages/selfhosted/test/polyfill/embed_missing_src/test.js
- web/packages/selfhosted/test/polyfill/object_clsid_with_embed/expected.html
- web/packages/selfhosted/test/polyfill/object_clsid_with_embed/index.html
- web/packages/selfhosted/test/polyfill/object_clsid_with_embed/test.js
- web/packages/selfhosted/test/polyfill/object_default/expected.html
- web/packages/selfhosted/test/polyfill/object_default/test.js
- web/packages/selfhosted/test/polyfill/object_flashvars/expected.html
- web/packages/selfhosted/test/polyfill/object_flashvars/index.html
- web/packages/selfhosted/test/polyfill/object_flashvars/test.js
- web/packages/selfhosted/test/polyfill/object_flashvars_in_url/expected.html
- web/packages/selfhosted/test/polyfill/object_flashvars_in_url/test.js
- web/packages/selfhosted/test/polyfill/object_missing_data/expected.html
- web/packages/selfhosted/test/polyfill/object_missing_data/index.html
- web/packages/selfhosted/test/polyfill/object_missing_data/test.js
- web/packages/selfhosted/test/polyfill/object_missing_type/expected.html
- web/packages/selfhosted/test/polyfill/object_missing_type/test.js
- web/packages/selfhosted/test/polyfill/object_missing_type_and_classid/expected.html
- web/packages/selfhosted/test/polyfill/object_unexpected_string/expected.html
- web/packages/selfhosted/test/polyfill/object_unexpected_string/test.js
- web/packages/selfhosted/test/polyfill/object_wrong_type/expected.html
- web/packages/selfhosted/test/polyfill/object_wrong_type/test.js
The standard method of embedding an SWF uses an embed-inside-object, and would incorrectly get polyfilled twice, creating two Ruffle instances:
```
<object>
<param name="movie" value="TrailForSnail.swf" />
<embed src="TrailForSnail.swf" />
</object>
```
This was especially noticeable with the new autoplay functionality. Avoid copying over embed tags from within a polyfilled object tag.
> web: Avoid double polyfilling embed-inside-object

- core/src/display_object/movie_clip.rs
StreamSoundBlock tags should be ignored when the MC is stopped. Fixes #1719.
> core: Don't run stream sounds when stopped (fix #1719)

- web/packages/core/src/ruffle-object.ts
- web/packages/selfhosted/test/polyfill/object_with_ruffle_embed/expected.html
- web/packages/selfhosted/test/polyfill/object_with_ruffle_embed/index.html
- web/packages/selfhosted/test/polyfill/object_with_ruffle_embed/test.js
```
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
<param name="movie" value="file.swf" />
<embed src="file.swf">
</object>
```
With the recent changes, the above code converts `<embed>` to `<ruffle-embed>`, letting `<object>` unchanged. However, if anything was appened to the DOM, the MutationObserver would take a look at the tag again: as the `<embed>` tag no longer exists, it would polyfill the `<object>`, changing it to `<ruffle-object>`.
This is particularly noticeable in #1744: scroll down to "Bravais Lattice Structures" and hit F5.
This PR prevents polyfilling `<object>` tags that already contain a `<ruffle-embed>`.
> web: Don't polyfill object tags already containing a ruffle-embed

- web/packages/extension/build/_locales/es/messages.json
The word "loaded" was missing in the sentence.
> Update messages.json missing word in ES translation

- web/packages/extension/build/settings.htm
It's based on the code for the pop-up settings and uses popup.js instead of settings.js (so no more save button is needed). I don't know if settings.js is required anymore but I kept it anyway.
> web: Revamp settings page

- core/src/avm1/globals/key.rs
- core/src/backend/input.rs
- desktop/src/input.rs
- web/src/input.rs
- web/src/lib.rs
Initial implementation of `Key.getAscii()`, which returns the ASCII value of the last pressed key.
This allows [Peasant's Quest](https://homestarrunner.com/disk4of12.html) to be playable.
Unfortunately winit keyboard events do not yet provide the API to easily implement this correctly (see https://github.com/rust-windowing/winit/issues/753) -- we need something like web `KeyboardEvent.key` that can provide us with the printed representation of a key on both press and release -- so this is implemented sub-optimally on desktop currently. I'm also unsure of the exact behavior of the Flash Player with international key layouts (seems like it works like the deprecated web `KeyboardEvent.which`, that respects international layout for ASCII characters, but reverts to QWERTY for non-ASCII?).
> avm1: Implement Key.getAscii

- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
Buttons should not fire their events when they are invisible (importantly `keyPress` events). Fixes #1521.
> avm1: Don't fire button events when invisible (fix #1521)

- web/packages/extension/build/_locales/sv/messages.json
I'm mildly uncertain about is whether it should be sv or sv_SE, but I went with the former as that's how other locales did it.
> i18n: Add Swedish

- core/src/display_object/movie_clip.rs
Remove `unimplemented!` on DefineFont4 tags and warn instead. Still will not function (AVM2 #1368 and FTE/TLF support) but avoid panicking. Fix panic in #1805.
> core: Don't panic on DefineFont4

- core/src/backend/render.rs
Remove another call to `unimplemented!` to avoid potential panics.
> core: Remove unimplemented! in decode_define_bits_lossless

- Cargo.lock
- desktop/Cargo.toml
- desktop/src/main.rs
Alternative to #1816 using https://github.com/jdm/tinyfiledialogs-rs
I found no problems with the switch.
Introduce file dialogs if no FILE argv is passed.
Use altered version of tiny file dialogs due to https://github.com/jdm/tinyfiledialogs-rs/issues/19
> desktop: Add file dialogs to Ruffle if no FILE argv V2 (close #1774)

- core/src/display_object/morph_shape.rs
Remove a potential panic in the shape tween interpolation.
> core: Remove panic in morph shape lerp

- web/src/input.rs
We were checking for byte length == 1 instead of # of characters to determine if KeyboardEvent.key was a printable character.
Thanks to @JMcKiern for pointing this out. Fixes part of #1802.
> web: Properly handle multibyte characters in text input

- core/src/avm1/globals/sound.rs
The second argument of `Sound.start`, `loops`, can be greater than `std::u16::MAX`, but previously greater values were treated as 1.
Ideally, the solution is to respect those values, but since `SoundInfo` holds a `u16`, a short-term solution is to treat them as `std::u16::MAX` instead.
Extracted from #1445 since this commit is unrelated.
> avm1: Improve loops treatment in Sound.start

- web/packages/extension/build/popup.html
This sets the background color of the sliders in the extension to `#a0a0a0` when unchecked. The aim is to make it clear whether or not the option is enabled.
Let me know if there's a better color.
**Before:**
**After:**
> web: Make slider color change if slider is checked

- web/packages/core/src/ruffle-player.ts
It is discouraged to use closed shadow DOM.
This makes it open.
> Open shadow DOM

- web/src/lib.rs
Remove incorrect key up events from being fired during key down. I believe this was a copy-paste flub from #1769.
Fixes #1886.
> web: Fix spurious keyUp events (fix #1886)

- CONTRIBUTING.md
I was having issues with getting the avm_debug feature to work. It turns out that I was incorrectly reading `RUST_LOG=warn,ruffle_core=debug` in CONTRIBUTING.md as two separate commands: `RUST_LOG=warn` and `ruffle_core=debug`. It should just be one command. 
This pr adds double quotes to the command to make this clearer: `RUST_LOG="warn,ruffle_core=debug"`. 
I understand that setting an environment variable using double quotes works in both bash and PowerShell. **However, it doesn't work in Command Prompt with `set`.**
> docs: Add double quotes to RUST_LOG to improve clarity

- core/src/avm1/globals/text_field.rs
- core/src/display_object/edit_text.rs
Remove TextField::attach_virtual properties, as properties are
on the prototype, not the textfield itself.
Use the `with_text_field_props` macro for these properties.
Also remove `get_` prefix from most getters to match naming
conventions.
> avm1: Move TextField properties to prototype

- swf/src/read.rs
Rust 12-09 nightly changed the working dir of doctests to be the
workspace root instead of the subcrate root. This broke the
doctests for swf. Now do some setup to ensure the same working
directory on both stable and nightly.
cc https://github.com/rust-lang/cargo/pull/8954
> chore: Fix swf doctests working directory

- web/src/lib.rs
Call window.focus() on mouse down to ensure the player receives
subsequent key/mouse events when it is inside a frame.
> web: Ensure parent window/frame gets focus on click (fix #1704)

- Cargo.lock
- exporter/src/main.rs
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- render/wgpu/Cargo.toml
- render/wgpu/src/bitmaps.rs
- render/wgpu/src/globals.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/pipelines.rs
- render/wgpu/src/target.rs
- web/Cargo.toml
- web/common/Cargo.toml
* `js-sys` and `wasm-bindgen` are now the currently latest releases.
* `wgpu` is not updated to the current master because it breaks things up.
> chore: Update some dependencies

- core/src/avm1/globals/movie_clip.rs
- core/src/display_object.rs
- core/tests/regression_tests.rs
MovieClip._lockroot should now work for AS1/2. This fixes #1124.
Some notes:
1. Differently from the [documentation](https://open-flash.github.io/mirrors/as2-language-reference/), the `_lockroot` property is `false` by default, not `undefined`. This change reflects actual SWF functionality, not the docs.
2. The `_lockroot` property is not defined in the [SWF format specs](https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf) so it doesn't have a formal `GetProperty` index.
3. Tests introduced in #1815 are now active.
As usual, comments welcome. This introduces some new functionality (that the ability to _keep_ some flags when loading a movie into another movie) so I want to make sure I'm not disrupting the architecture too much.
> core: Implement MovieClip._lockroot in avm1

- CONTRIBUTING.md
I noticed that `tests:` was used in a number of commits (eg 852f26bdeb029cef9bd072674b3edf03642a34b1, 457d707ec24433ce6ca814da99bc89a5e2770305, c018ac065c7e007ea5e42fae90cbb66e7bc98f4e) but it was missing from the list in CONTRIBUTING.md
> docs: Add `tests` to list of commit prefixes

- web/packages/core/src/ruffle-player.ts
- web/packages/selfhosted/test/polyfill/pdf_with_get/expected.html
- web/packages/selfhosted/test/polyfill/pdf_with_get/index.html
- web/packages/selfhosted/test/polyfill/pdf_with_get/test.js
I think this should be better and more reliable, as mentioned in https://github.com/ruffle-rs/ruffle/pull/1281#issuecomment-706362765.
Also, a code like `<object data="fake.pdf?a=foolme.swf"></object>` is currently detected as an SWF and converted to a `ruffle-object`. The PR fixes this case and adds another test.
> web: Detect swf extension using the `URL()` constructor

- core/src/backend/navigator.rs
- desktop/src/main.rs
- desktop/src/navigator.rs
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
- web/src/navigator.rs
Alternative to #1897 using `Url` arguments instead.
I must confess, I think I prefer #1897 so far, but I'll leave that to review to decide.
> web: Fix cors issues with http (close ruffle-rs#1486) alternative

- web/packages/core/src/ruffle-player.ts
This automatically fills in the issue report so that the user doesn't have to copy-paste the error details from Ruffle to GitHub. Closes #1753 
Let me know if there is a better Issue Title.
Also, it could be worth including a description from the user perhaps?
For example:
```
[Please explain what was happening when you encountered the error]
```
> web: Add query string to `Report Bug` link

- web/packages/core/src/globals.d.ts
- web/packages/core/src/load-ruffle.ts
- web/packages/core/src/public-api.ts
- web/packages/core/src/public-path.ts
- web/packages/extension/.eslintrc.json
- web/packages/extension/js/index.js
- web/packages/extension/js/lv0.js
The web extension currently declares the `runtime_path` variable in the global scope (`extension/js/lv0.js`): this is causing self-hosted builds to be detected as the web extension, because the `fetchRuffle` function assumes that if this variable is set, then we are executing inside the extension (`core/src/load-ruffle.ts`).
- Ruffle script is now injected in an asynchronous function (lv0.js), restoring a previous behavior (https://github.com/ruffle-rs/ruffle/blob/42d724292fc09e7d139df4603963e4229b0983a1/web/extension/build/js/lv0.js). 
- `runtime_path` is renamed to `ruffleRuntimePath` to help preventing conflicts with external scripts.
- Some recent changes in `core/src/public-api.ts` have been reverted. For instance, `prevRuffle?.constructor.name === PublicAPI.name` wasn't checking the …
> web: Fix extension and self-hosted builds conflicting with each other

- core/src/display_object/edit_text.rs
- core/src/font.rs
- core/src/html/layout.rs
- core/src/html/text_format.rs
- core/src/string_utils.rs
As discussed in #1802, typing a multibyte character into a text input was broken. The first issue was solved in #1860 but there were numerous occasions where characters were expected to be single bytes. This pr fixes that by changing any references to text to deal in character space rather than byte space.
I'm aware that `get_byte_pos()` adds an O(n) performance hit. However, as far as I can tell, there is no way around this and slow is better than incorrect!
Since the faux device font doesn't include any multibyte characters, I provide this swf for testing. It embeds 2000+ typewriter glyphs and sets `TextField.embedFonts = true;`.
[text_input_embeddedfonts.zip](https://github.com/ruffle-rs/ruffle/files/5684773/text_input_embeddedfonts.zip)
This pr will close #1802
> core: Extend text input to accept multibyte characters (closes #1802)

- Cargo.lock
- core/src/tag_utils.rs
- swf/Cargo.toml
- swf/src/lib.rs
- swf/src/read.rs
- swf/src/write.rs
Pure Rust decoder that functions on desktop and wasm (thanks to @gendx!)
Enable lzma feature by default.
TODO: Switch to lzma-rs streaming API when stable on crates.io.
Currently decodes entire stream at once.
> swf: Use lzma-rs for LZMA SWFs (fix #405)

- core/src/html/layout.rs
- core/src/library.rs
- core/src/player.rs
Move device font from Library to MovieLibrary since it should be global to the player. This allows the device font to work correctly when a movie loads other SWFs. Fixes #1995.
> core: Move device font to Library (fix #1995)

- Cargo.lock
- core/Cargo.toml
- core/src/avm1/activation.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/object/bitmap_data.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/avm2/globals/math.rs
- web/Cargo.toml
`gen_range` now takes a `Range`. Closes #2028.
> chore: Bump to rand 0.8

- web/packages/core/src/js-polyfills.ts
- web/packages/core/src/load-ruffle.ts
Some libraries (especially `prototype.js`) overrides the `Array.prototype.reduce` method in a way that doesn't match the specification, causing Webpack to crash. This PR adds code to override the method again and prevent issues. The polyfill used is from the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#Polyfill).
Fixes #1507, #1630, #1830, #1865, #2011, #2042, #2049 (lots of duplicates here, they're almost all related to `prototype.js`).
> web: Prevent crashes caused by external libraries

- web/packages/core/src/js-polyfills.ts
Following https://github.com/ruffle-rs/ruffle/pull/2051#issuecomment-748685349, let's add a special case to the `Array.prototype.reduce` polyfill to maintain compatibility with `prototype.js`. The previous PR didn't break anything on the known affected sites, as these sites use versions where the `reduce` method is defined but not used anywhere. However, [an older version of the library](http://prototypejs.org/assets/2007/1/18/prototype.js) uses the method in another function, which has the potential to break things. This can also prevent issues with user-defined code.
> web: Update polyfill to maintain compatibility with prototype.js

- core/src/avm1/globals/shared_object.rs
- desktop/src/main.rs
- desktop/src/storage.rs
- web/src/lib.rs
- web/src/storage.rs
On web, SharedObjects were being keyed by the website URL; however, this was causing issues both with query parameters (#855, #2046) and with loaded movies. In the Flash Player, SharedObjects are keyed by the SWF's URL.
Switch to using the SWF's URL, and implement the localPath and secure parameters in `SharedObject.getLocal`. By default, the full SWF path is used, but supplying a local path allows you to make the SharedObject accessible to more paths on the same domain (for example, a local path of `/` will allow the object to be accessible by all SWFs on the same domain).
This also affects storage on desktop; for example, data from a local SWF is now stored in `userdata/ruffle/localhost/path/to/file.swf/sharedObjectName`. This should more closely match the Flash Player (compare the …
> core: Use movie URL for SharedObject path

- core/src/backend.rs
- core/src/backend/ui.rs
- core/src/player.rs
- core/tests/regression_tests.rs
- desktop/src/main.rs
- desktop/src/ui.rs
- exporter/src/main.rs
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
- web/src/lib.rs
- web/src/ui.rs
Alternative to #1982 
Look at showing warnings in Ruffle for #1978
> Add ability to show dialogs in Ruffle (show on top of player in web)

- render/wgpu/src/target.rs
Unmap buffer to prevent panic when capturing frame.
> exporter: Fix panic when using --frames (fix #1614)

- core/src/display_object/edit_text.rs
This pr makes a number of changes related to the selection of text in TextFields:
- 6f3251a4e7ec3673b6d4706295a387994b5cbcce changes the caret color to match the text color.
- 4aa535f0b95d4c8618660d630aafef61d9f9b295 renders a selection as white text with black background.
- d4e5a1f4b1e744e8156a9329e07db55a050ec371 fixes a spelling mistake ("adjustmnet" -> "adjustment").
- eaa3533e7872c43eb207c51604d31017cbf34be4 changes the behaviour of pressing left <kbd>&#8592;</kbd> or right <kbd>&#8594;</kbd> when there is text selected. Previously, if `4..6` was selected, pressing left would move to `3` instead of correctly moving to `4`.
- e70478ecc5c63077df7e3a4866ebf3916de86e64 fixes a bug with the selection when text is split across multiple lines.
Note that the height of the selection box (and …
> core: TextField selection fixes

- core/src/player.rs
- desktop/src/main.rs
- exporter/src/main.rs
- render/wgpu/src/lib.rs
Add --timedemo for benchmarking, which will run the given SWF as quickly as possible for 5000 frames or the end of the root timeline, whichever comes first. The total duration will be output upon completion.
This will be useful for measuring improvements to the renderers.
TODO: This should be used with an SWF without preloaders (stop actions), otherwise the demo will just render the same frame 5000 times. A method to force the main timeline to play could be useful.
> desktop: Add --timedemo benchmark

- core/src/display_object/movie_clip.rs
- core/src/events.rs
`onKeyDown` and `onKeyUp` should only fire on a movie clip when it has focus, via an explicit `Selection.setFocus` call, or when highlighted via Tab in button mode (both TODO). Note that the instance `onClipEvent(keyDown)` fire regardless of focus.
Fixes #2120.
> core: onKeyUp/Down method handlers fire only if clip has focus (fix #2120)

- core/src/display_object/edit_text.rs
- render/webgl/src/lib.rs
* `draw_rect` was sometimes not working properly on mobile, because the same VAO was shared for bitmapped quads and colored quads; this happened to work on desktop because the attribute locations were the same, but on mobile this was not the case. Quick fix is to make separate VAOs for bitmapped quads and colored quads. Fixes #1834 (and hopefully #900).
* The textfield stencil mask was drawn slightly offset when being cleared., Clear the proper area, which fixes some artifacts (fixes #1496, #1554).
> render: Fix some issues with text rendering

- desktop/src/main.rs
- render/wgpu/src/lib.rs
On desktop, don't render while the window is minimized.
In the wgpu backend, don't panic if swap chain fails to grab a
texture. Instead recreate the swap chain and bail on the current
frame. This may get cleaned up in upstream wgpu at some point,
but we should probably not render when minimized regardless.
Fixes panic when minimizing with the wgpu vulkan backend (#2065).
> desktop: Don't render while minimized

- README.md
Renamed the "Nightly Builds" section to "Using Ruffle", added info about the web demo, and added link to the "Using Ruffle" wiki page
> Added link to the Using Ruffle wiki page

- core/src/avm1/globals/shared_object.rs
* Fix incorrect name used for cached SharedObjects (fix #2149)
* Use dummy URL for SharedObject path when movie URL is unavailable (fix #2150)
Thanks to @Toad06 and @adrian17 for the tips!
> avm1: Fix issues with SharedObjects

- core/src/display_object/edit_text.rs
Text fields without variables would return as unbound in
EditText::try_bind_text_field_variable, causing them to be added
to the unbound textfield list even though they had no variable
setting. Return successful bidning by default to avoid adding
these textfields to the unbound list.
> core: Fix memory leak caused by unbound text variables

- web/packages/core/src/js-polyfills.ts
- web/packages/core/src/load-ruffle.ts
When the native `Window` function is overridden, a code like `window instanceof Window` (used in wasm-bindgen) always returns false or causes a TypeError. As a consequence, Ruffle crashes.
To fix that, this PR adds a new JS polyfill that tries to override `Window` again using `window.constructor`.
Fixes #2156.
> web: Prevent crash when native `Window` function is overridden

- web/packages/demo/www/index.html
The popup window will only display the files that match this criteria.
Could help prevent issues like #2169 in the future.
> demo: Only accept .swf and .spl extensions when selecting a local file

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/globals/bitmap_filter.rs
- core/src/avm1/globals/rectangle.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/context.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
- core/src/player.rs
Turned out it's already in Avm1 struct, so this patch is mostly just mechanical conversion of `context.system_prototypes` to `context.avm1.prototypes`.
This reduces size of UpdateContext by over 1kB and significantly speeds up some games with lots of calls; in N v1.2, my FPS counter improved from 35-50FPS to 50-70FPS.
> Remove redundant SystemPrototypes from UpdateContext.

- core/src/backend/render.rs
- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/drawing.rs
- core/src/library.rs
- render/canvas/src/lib.rs
- render/common_tess/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/shapes.rs
Pass the movie library to `register_shape` methods so that bitmap
charcter IDs can be resolved immediately on the proper SWF.
This fixes #2037, which cause incorrect bitmaps to be used when
multiple movies were loaded.
> render: Pass library to RenderBackend::register_shape (fix #2037)

- render/webgl/src/lib.rs
`draw_rect` should use mult_color instead of add_color because the vertex color is white. Fixes #2189.
> webgl: Use mult color for draw_rect (fix #2189)

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/object/bitmap_data.rs
This makes the right-scrolling background particles of [z0r.de/7463](https://z0r.de/L/z0r-de_7463.swf) work, fixing 1/3 of #2073.
I've tested this code manually with [a couple different parametrizations](https://gist.github.com/torokati44/96a24e15b0ba2c9db1e9ddde2aae5721), the visual results always exactly matched that of Adobe Flash Player.
I'm not sure if any of this is supposed to be added as some actual test cases, and if so, exactly how - I personally used `mtasc` to build the `.swf`s.
Performance-wise I tried to avoid any redundant range checks (hence the `unwrap`), and conversions to/from premultiplied alpha format.
_(There might be faster ways to do this, especially if there is something of a `memcpy`-like intrinsic on `Vec`s of simple types, with selectable operation order, but …
> Implement BitmapData.scroll()

- core/src/backend/audio/decoders/adpcm.rs
Due to the way equation `(magnitude + 0.5) * step / 2^(bits_per_sample - 2)` was approximated in ADPCM implementation linked from SWF documentation, the results can differ by [`0`, `bits_per_sample - 1`]. This results in variable audio artefacts, as can be heard in [these files](https://drive.google.com/drive/folders/1YYce0XjutZqmrTLCbw6q1C6AfNqoJPxL?usp=sharing).
```python
bits_per_sample = 4
data = 1
magnitude = 1
step = 7
################# (1)
delta = (magnitude + 0.5) * step / 2**(bits_per_sample - 2)
print(delta) # delta == 2.625 or 2 when cast to int
################# (2)
delta = step >> 3
if magnitude & 4:
delta += step
if magnitude & 2:
delta += step >> 1
if magnitude & 1:
delta += step >> 2
print(delta) # delta == 1
```
The differance between deltas is caused due to sum of …
> core: ADPCM decoder produces less artefacts

- core/src/avm1/activation.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/context.rs
- core/src/player.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/1020.
Ping @Dinnerbone as the original idea came from him. Please check if my reasoning in the comments is sound :) 
Also feel free to bikeshed conditions for incrementing `time_offset`.
This came out more elegant than I expected, but still feels a bit brittle.
In particular, we now need to remember to apply `time_offset` whenever we calculate current date visible to script. I did it in the opcode and avm1 Date constructor, but the same will need to be applied in avm2 Date (and possibly other places in the future?).
Also, as explained in the comment, this causes a subtle incompatibility in regards to timers; in Flash, a blocking busy loop would affect timeout/interval callbacks, but here it does not. However, 1. it was already similarly …
> Fake passage of time to fool busy-loop frame limiters

- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
`<embed src="file.swf" type="application/x-shockwave-flash"  allowscriptaccess="always" />`
Ruffle would currently ignore the `allowscriptaccess` attribute in the above tag. This PR fixes this issue.
Reported by nosamu on Discord.
> web: Read the `allowScriptAccess` property from `embed` tags

- Cargo.lock
- core/Cargo.toml
- core/src/backend/audio/decoders/adpcm.rs
> chore: Update bitstream-io to 1.0.0

- web/packages/core/src/ruffle-player.ts
`<embed src="file.swf" style="visibility:hidden;" />`
This code doesn't hide the file in the current builds because the `container` div is set to `visibility: visible`. To remove this override, the PR changes the div visibility from "visible" to an empty string.
`autoplay: "invalidValue"`
When the `autoplay` option is set to an incorrect value, the value remains unchanged and doesn't default to one of the expected values ("auto" in this case) in the current builds. Same goes for `unmuteOverlay`. The PR ensures a fallback to the default value.
> web: Fix minor issues in `ruffle-player.ts`

- web/Cargo.toml
This is not full debug into, just symbol names section:
https://github.com/WebAssembly/binaryen/blob/master/src/tools/optimization-options.h#L128
Downside: release wasm is bigger by ~10% (currently 3.88MB -> 4.26MB) for all users
Upsides:
- meaningful stack traces on the "something went wrong!" screens, simplifying early analysis of new issues (eg `wasm:wasm-function[1463]:0x272b18` -> `<ruffle_core::display_object::edit_text::EditText as ruffle_core::display_object::TDisplayObject>::unload`),
(unfortunately in practice this only helps in Firefox, as Chrome's error stack appears to have limited depth and only shows `panic!()`'s inner frames)
- you can now easily profile demo page or extension using chrome/firefox profilers.
> Add symbol names to optimized wasm files

- render/webgl/src/lib.rs
Needed to support u32 index buffers. Fixes black screen regression on iOS in 1/06 nightly build.
> webgl: Request OES_element_index_uint extension on WebGL1

- Cargo.lock
- core/Cargo.toml
- core/src/backend/render.rs
- core/src/backend/ui.rs
- core/src/config.rs
- core/src/lib.rs
- core/src/player.rs
- desktop/src/main.rs
- desktop/src/ui.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
- web/Cargo.toml
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/demo/www/index.js
- web/src/lib.rs
- web/src/navigator.rs
- web/src/ui.rs
This PR adds a new "letterbox" setting for web:
* `off`: No letterboxing. Matches Flash behavior. Areas outside the movie stage will be visible.
* `fullscreen`: Letterboxing is only done in fullscreen mode.
* `on`: Letterboxing will always occur when the container aspect ratio doesn't match the movie's aspect ratio.
On web, this defaults to "fullscreen", because we should match the appearance of native Flash in a web page, but we still activate it in fullscreen mode because it will usually look better.
On desktop, this still defaults to "on", because it will usually look better, as most content isn't designed to show outside the stage area. (TODO: Make this user-configurable on desktop).
The demo page turns letterboxing on to match the previous behavior.
`RenderBackend::draw_letterbox` …
> web: Add letterbox setting

- web/packages/core/src/ruffle-player.ts
The stack error is sometimes very long, so long that the generated URL could trigger a 414 error on Github. This is especially true on Firefox: for instance, this problem happens with the game in #2280. With PR #2305, this will likely happen more often, so we need to strip the stack error from the URL.
> web: Prevent "414 URI Too Long" error on Github when reporting bugs

- core/src/lib.rs
- desktop/src/main.rs
- desktop/src/ui.rs
This PR adds Alt+Enter as a keyboard shortcut to toggle fullscreen.
Should more or less fix #186.
The major downside here is that the player will never receive events for Alt+Enter. I see 3 alternatives:
1. Choose a different (less common) keyboard shortcut - but I think Alt+Enter is rare enough.
2. Continue passing those events to the player - but this may cause unintended behavior.
3. Add the fullscreen option to a context menu, so it doesn't interfere with any player events - but winit doesn't support context menus out-of-the-box.
> desktop: Add fullscreen keyboard shortcut

- core/src/lib.rs
- desktop/src/main.rs
A follow-up for #1510:
* Include a missing commit (because of force-push).
* Add <kbd>Esc</kbd> shortcut to exit fullscreen, like Flash Player.
* Prevent entering/exiting fullscreen repeatedly by holding <kbd>Alt</kbd>+<kbd>Enter</kbd>.
> desktop: Fullscreen fixes

- Cargo.lock
- desktop/src/main.rs
- render/wgpu/Cargo.toml
Winit's WindowBuilder will sometimes create a window whose size is
smaller than requested. Therefore, instead of assuming the actual
window size is requested size * scaling, just check what the true
size is. (window.inner_size() also takes scaling into account.)
This fixes at least one issue where rendering would fail on Windows
with the Vulkan backend due to the incorrect size being used.
~~On a side note: winit is apparently limiting the window size to the screen resolution. This pull request doesn't change that behaviour, because when [I tried to do so](https://github.com/MrCheeze/ruffle/commit/e4cae4f23974a9b22b31c93bd5da52171a6e4401) it ended up causing crashes in the DX11 backend for unclear reasons. But I think this change is valuable enough on its own.~~
> desktop: Fix rendering when window is has unexpected size (close #1631)

- core/src/player.rs
- web/packages/core/src/load-options.ts
- web/src/lib.rs
This is an attempt to fix #2321.
I'm not that experienced with TypeScript either; and I'm not sure if I put the new field and methods in the right places in all files - both regarding to into which struct, and in which order relative to the already existing fields.
Also the names might not be the best. Feel free to scrutinize/criticize!
Finally, should I also add a new command line argument for the desktop version to provide the same functionality?
> Add a config option to disable the message about ActionScript 3 support

- core/src/backend/navigator.rs
- desktop/src/navigator.rs
- web/src/lib.rs
- web/src/navigator.rs
This PR is a bit experimental for me as it implies changes on the Rust side, which is a language I'm absolutely not familiar with. But I feel like I had to give it a try. :) Hope it's not too bad. Here are the changes:
- Fix #1102: `window.location().assign(&window_url);` refreshes the page if the URL is an empty string. To match Flash's behavior (which does nothing in this situation), the PR just checks if `window_url` is all but an empty string. Also, it appears that an URL only containing blank spaces defaults to "./" in Flash, so I've added this special case as well.
- Fix #2214: Upgrading to HTTPS could lead the browser to display a security warning on sites that don't use a certificate, so this PR only enables the upgrade to HTTPS when Ruffle has to deal with forms. Speaking of …
> web: Fixes and improvements in `navigate_to_url`

- core/src/display_object/button.rs
* Allow mouse picking to check children of the button, allowing cases of button-inside-button to work.
* Don't recreate all children when changing button state. Instead, children that exists in both the previous and current states should persist.
Fixes #2354.
> core: Fix various issues with buttons

- core/src/avm1/globals/object.rs
Apparently there are some even less documented flags that affect property visibility depending on SWF version? And there are some games in the wild that use it.
This fixes the crash in https://github.com/ruffle-rs/ruffle/issues/2464 and lets the game screen show up (though not much more, as it just loops infinitely).
> In ASSetPropFlags, don't crash on flags > 7

- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/context.rs
- core/src/display_object/movie_clip.rs
- core/src/player.rs
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
* Change `Player::background_color` to an `Option`.
* If this is not set, the first `SetBackgroundColor` tag encountered sets the background color of the player.
* Otherwise, the SWF background color is ignored and the supplied color is used.
* Note that this is a slight improvement from previous behavior (#1100); a child SWF can set the background color if the parent SWF is missing a SetBackgroundColor tag. This matches behavior in the official Flash Player (tested via hex-edited SWFs).
* Add `backgroundColor` option to the web settings, allowing the user to override the SWF background color.
* The polyfill now understand the `bgcolor` HTML attribute on Flash embeds, setting the background color appropriately.
Fixes #2135.
> web: Add backgroundColor option

- core/src/avm1.rs
- core/src/avm1/globals/as_broadcaster.rs
- core/src/display_object/edit_text.rs
This PR implements `TextField.addListener()`, `TextField.removeListener()`, `TextField.broadcastMessage()`, `TextField._listeners`, and `TextField.onChanged()`. This closes #2297 and checks off more boxes on #280.
It works by calling `AsBroadcaster.initialize()` on newly created `TextField`s, which seems to match Flash's behavior. The new `EditText::on_changed()` method is called whenever the text changes and broadcasts the `onChanged` event to all listeners.
There are a couple of other small changes:
- `AsBroadcaster::broadcast_message()` no longer warns if a listener does not have a handler for the given event.
- `Avm1` now exposes `broadcaster_functions` through a public method.
This is my first contribution to Ruffle -- or to any open-source project, for that matter -- so feedback is …
> avm1: Implement listeners and onChanged for TextField (close #2297)

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/object/bitmap_data.rs
This adds the main content (left-scrolling foreground image) to [z0r.de/7463](https://z0r.de/L/z0r-de_7463.swf), solving another third of #2073.
This should also help with #2240, although other missing features seem to block this from making any difference there.
I tried to test this implementation with a variety of different parameter sets, using this test script: [BitmapCopyPixels.as](https://gist.github.com/torokati44/efd3c97d15ca51b1242af63a1f2adb2e)
Which produces this image in the Adobe player:
There is at most 1 value of difference from this in any channel of any pixel when run in Ruffle, as shown in this exaggerated difference image:
These are most likely rounding errors or other slight imprecisions. I don't find these to be too big of an issue.
The output is visually exactly the …
> Implement BitmapData.copyPixels()

- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
Switch to debug_assert! instead of assert! in mask checks to avoid
panicking (#1347). This will render incorrectly and still needs
to be fixed, but we should fail gracefully and avoid killing the
entire player.
> render: Avoid asserts in masking state

- .github/workflows/release_nightlies.yml
- README.md
This is to prevent errors about missing `VCRUNTIME140_1.dll` etc without forcing the users to install the redistributables themselves.
You can see other projects doing the same:
https://github.com/rustwasm/wasm-pack/commit/d6146b25a580de72487c17aceab896b859df546e
https://github.com/bytecodealliance/wasmtime/commit/8ce68732f68197dedd47bbfeea5f83b43c23fe7a
I built Ruffle with this and confirmed that it launches without errors on a W8.1 laptop without redistributables and a freshly installed W10 VM, where the previous Ruffle releases couldn't launch.
However, neither the laptop nor the VM had sufficient graphics acceleration support, so all games ran with just a white window - so technically I didn't check if it 100% works on a modern machine without the redistributables. Would be nice if …
> Build windows binaries with crt-static

- .github/workflows/release_nightlies.yml
- .github/workflows/test_web.yml
- .gitignore
- web/Cargo.toml
- web/README.md
- web/packages/core/package.json
This should resolve the CI failures of #2173 which are caused by `wasm-opt` crashing.
I tried this patch on top of those changes, and all the checks passed.
The crash happens because the last release of `wasm-pack` (v0.9.1) was a long time ago (see: https://github.com/rustwasm/wasm-pack/issues/951 and https://github.com/rustwasm/wasm-pack/issues/929, among others), and it's hardcoded to use `binaryen` (incl. `wasm-opt`) version either 78 or 90 (the latter according to @adrian17) and it is not able to use any other `wasm-opt`, for example one in `$PATH` (see: https://github.com/rustwasm/wasm-pack/blob/v0.9.1/src/wasm_opt.rs#L50-L68).
Sadly, `wasm-opt` in this version trips up on the bounds checks in the `idct_channel` function, as found out by @kmeisthax. To me it seems that the crash was …
> web: Drop wasm-pack, invoke wasm-bindgen and wasm-opt directly from npm

- web/packages/core/package.json
- web/packages/core/src/load-ruffle.ts
- web/packages/demo/package.json
- web/packages/demo/webpack.config.js
- web/packages/extension/package.json
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/package.json
- web/packages/selfhosted/webpack.config.js
Use `--target web` in wasm-bindgen and file-loader for WASM files,
allowing wasm-bindgen's built-in fallback from
WebAssembly.instantiateStreaming to instantiate to function.
file-loader spits out the WASM file directly in the output folder,
and imports will resolve to the URL, so that we can load the file
directly, avoiding webpack's built-in wasm loaders.
This allows Ruffle to function on web servers even if they serve
WASM files with the incorrect MIME type, fixing one of our biggest
support problems (#400, #1458). There is some performance impact
on loading with the fallback, but it seems minimal to me and is preferable
to not working at all.
Perhaps someone with more webpack/JS experience can look this over and verify that everything makes sense.
> web: Fallback to instantiate with improper MIME type

- Cargo.lock
- web/Cargo.toml
- web/packages/core/src/load-options.ts
- web/packages/demo/www/index.js
- web/src/lib.rs
New default in API is "error".
Demo page uses "warn".
I'd also love to set "warn" in extension, but I couldn't actually found the config in extension's source. Any hints?
> Allow configuring log level on web

- web/packages/core/src/globals.d.ts
- web/packages/core/src/load-ruffle.ts
- web/packages/core/src/ruffle-player.ts
This PR is intended to help users of the selfhosted build, when Ruffle fails to initialize. To do so, new error messages are implemented.
Messages likely need to be improved. I also wonder if there's a better way to detect certain errors (eg. 404 and CORS). If this gets merged, we'll have to mention about the CORS issue on the wiki.
> web: Display helpful errors when Ruffle fails to initialize

- swf/src/read.rs
- swf/src/write.rs
The Flash specs say that focal gradients must be in DefineShape4 tags, but they still seem to work fine in early DefineShape tags in the player. Remove this check to allow for out-of-spec SWFs.
Fixes #2730.
> swf: Don't error on focal gradients in DefineShape tags (fix #2730)

- core/src/avm2/activation.rs
This makes it easy to see when the error is a result of something in the
"flash" package being unimplemented.
> core: Print full multiname for "Property does not exist" errors

- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
- swf/src/read.rs
- swf/src/test_data.rs
- swf/src/types.rs
- swf/src/write.rs
Now that we depend on `bitflags`, we can take advantage of it to convert some `HashSet` of enums to bit fields.
This eliminates the need to convert from/to their binary representation, as `bitflags` does this by itself.
> swf: Convert HashSet to bitflags

- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/function.rs
- core/src/avm1/globals/array.rs
- core/src/avm1/globals/load_vars.rs
- core/src/avm1/globals/matrix.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/rectangle.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/value_object.rs
- core/src/avm1/value.rs
AFAIK this change shouldn't change any observable behaviors?
This seems reasonable in general (now these objects are _actually_ pooled, and removes a bunch of work from `action_push`), and is another step towards pre-hashing constant strings like property names in the future.
What positively surprised me, is that apparently `AvmString::new` called on nearly every ActionPush was a major source of `gc-arena` GC pressure in some games. For example, in Meat Boy on FF wasm, this change reduced time spent in `gc_arena.collect_debt()` by 2-3x and - on my PC - improved the game from "slightly choppy most of the time" to "smooth most of the time" :)
Second commit makes `avm1::Value` `Copy`, as all its fields are `Copy`. This generates better code, but I'm not sure if you like the less explicit …
> Preallocate AVM1 constant pool values

- desktop/Cargo.toml
- desktop/build.rs
`embed-resource` is designed to run on all machines and only include the binary when the end binary is for Windows
> desktop: Fix windows cross compilation of assets

- core/src/display_object/edit_text.rs
Don't hold on to a borrow inside `on_changed` to avoid panics if the `onChanged` handler also tried to modify the text field.
Fixes #2788, #2809.
> core: Avoid panic in EditText::on_changed (fix #2809)

- web/packages/demo/www/index.js
The fix in https://github.com/ruffle-rs/ruffle/issues/2416 now causes the player to duplicate to 2 instances, because `container.children[0]` seems to select some sort of 'overlay' element, and not the player that it should be deleting. `container.querySelector('#player')` should however select the first player instance, to correctly remove it from the page.
> Fixes duplicating player issue on website demo page

- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
Fixes #1977.
This PR adds a new config called `contextMenu` that controls whether or not to show a context menu when right-clicking a Ruffle instance.
I did some refactors along the way, <s>including removal of the unused `Ruffle.prototype.config` member</s>.
A follow-up PR needs to handle #1972 by defaulting to `false` on mobile instead of always `true`.
> web: Add config to enable/disable context menu

- .github/workflows/release_nightlies.yml
- .github/workflows/test_web.yml
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- web/Cargo.toml
- web/common/Cargo.toml
wasm-bindgen released a new version 0.2.70, but this caused CI to choke because the wasm-bindgen and wasm-bindgen-cli verisons must match exactly (https://github.com/ruffle-rs/ruffle/pull/2845/checks?check_run_id=1764454473). wgpu-rs has a dependency on =0.2.69, so the wasm-bindgen version couldn't be used.
Given that the versions must match exactly, let's depend on the exact version itself both for wasm-bindgen in Cargo.toml, and cargo install wasm-bindgen-cli on CI so that this doesn't break randomly as versions get bumped. When we want to update wasm-bindgen, we must explicitly do so and update the version in these places.
> chore: Lock wasm-bindgen and wasm-bindgen-cli to 0.2.69

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
I'm not claiming to be anywhere near good at design :) But after several questions on Discord, it feels to me like the simulated context menu should look a bit closer to native ones, to be less jarring to users used to Flash.
Separator support code may be ugly, but I imagine this all will need to be refactored for ActionScript context menus anyway.
Before vs after on light and dark backgrounds:
Comparison with browsers' context menus:
> Redesign the web context menu a bit

- core/src/backend/render.rs
Fixes z0r 4167 and 6009.
Technically it would be slightly more efficient to store them as grayscale, something like:
```rust
pub enum BitmapFormat {
L8(Vec<u8>), // grayscale
L8a(Vec<u8>), // grayscale + alpha
Rgb(Vec<u8>),
Rgba(Vec<u8>),
}
```
But IMO that'd be a lot of extra logic in decoding and all render backends, for a relatively minor case. But let me know if you want it that way instead.
> Support grayscale JPEGs

- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
This resolves https://github.com/ruffle-rs/ruffle/issues/347. It modifies `ruffle-player.ts` to detect when the tab is inactive using the browser's [visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API). It also adds a `is_playing()` function to the public API in `web/src/lib.rs`. This is to allow the player to only resume playback if the animation wasn't already paused.
I considered whether there should be an option on the player to turn off this pausing, but since it is not currently possible to continue playing the frames in the background, and catching up may not be feasible, disabling this would produce incorrect behavior. 
It may make sense to revisit toggling this behavior when frame playback is controlled on a worker as mentioned here: …
> web: Pause player when tab is inactive (close #347)

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/object/bitmap_data.rs
- core/src/bitmap.rs
- core/src/bitmap/turbulence.rs
- core/src/lib.rs
This aims to help with #2240, although that is still blocked by `BitmapData.draw` (also by `merge`, but that doesn't seem to be enough in itself).
Also should improve #2295, but without `BitmapData.paletteMap`, it actually regresses a bit - at least visually.
I tested these changes with lots of different parameter combinations, using [this ActionScript code](https://gist.github.com/torokati44/c1b5a859d7c96bb4022ac36ed493b2f4), which I compiled with `mtasc` into [this .swf](https://github.com/ruffle-rs/ruffle/files/5865428/BitmapPerlinNoise.zip).
This produces the following image:
**EDIT:**
I managed to "fix" the rounding when converting the floating point values to `u8` in all cases.
Now, when taking the example `.swf` above, and making four variations of it: Setting the `transparency` …
> Implement BitmapData.perlinNoise()

- desktop/assets/ruffle_desktop.rc
This PR adds some nice resources to [`desktop/assets/ruffle_desktop.rc`](https://github.com/ruffle-rs/ruffle/blob/master/desktop/assets/ruffle_desktop.rc), including [version information](https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource) and copyright notice.
Based on Windows docs and Chromium's [`chrome_version.rc.version`](https://chromium.googlesource.com/chromium/src/+/master/chrome/app/chrome_version.rc.version).
> desktop: Improve ruffle_desktop.rc

- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
- web/src/audio.rs
- web/src/lib.rs
When using the JavaScript API, `allowScriptAccess` can only be defined this way:
```
let player = ruffle.createPlayer();
player.allowScriptAccess = true;
player.load({
url: "file.swf",
parameters: "myflashvar=blahblah",
};
```
This doesn't seem really consistent considering the options in the `load()` method.
This PR allows `allowScriptAccess` to be set like this:
```
let player = ruffle.createPlayer();
player.load({
url: "file.swf",
parameters: "myflashvar=blahblah",
allowScriptAccess: true,
};
```
The default value remains unchanged (always false on the JS API).
> web: Move `allowScriptAccess` to `BaseLoadOptions`

- core/src/avm1/activation.rs
- core/src/avm1/fscommand.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/external.rs
- core/tests/regression_tests.rs
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
This PR provides an implementation of `fscommand()` for older AS1 Flash movies.  In my case, I have SWF files that use `fscommand()` to  communicate with a host application for the purpose of UI.
To support this using a web page, an `onFSCommand` callback was added.  This receives the command and arguments, and returns `true` if the command is handled.
> Implement fscommand as a callback

- core/src/backend/ui.rs
- core/src/player.rs
- desktop/src/ui.rs
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
- web/src/lib.rs
- web/src/ui.rs
Proposed on Discord, seems like a lot of users are having trouble with this message: `This SWF contains ActionScript 3 which is not yet supported by Ruffle. The movie may not work as intended.`
A few alternatives, some mine, some from Discord, please suggest more / better wording!
- Shortened: `This content is not yet supported by Ruffle.`
- Catering to new users: `Flash Player has been removed from browsers starting 2021. This content is not yet supported by the Ruffle emulator.`
- With timeframe: `This content contains ActionScript 3 which is not yet supported by Ruffle, and will take at least several months.`
- Extended information: `[...]. This just means that it's not done yet, the devs are working on it, it will take some time.`
- Very verbose: `Flash Player has been removed from …
> Change "ActionScript 3 not supported" message

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- PKGBUILD
Resolves #2246.
@Herschel I think the best way is that you generate a new private/public key pair, then add the private key as a secret and send me the public key so I can add it in the AUR.
> Publish nightly builds to the AUR

- Cargo.lock
- core/Cargo.toml
- core/src/backend/audio/decoders.rs
- core/src/backend/audio/decoders/nellymoser.rs
- desktop/src/audio.rs
- web/src/audio.rs
Based on [`nellymoserdec.c`](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/nellymoserdec.c) of FFmpeg, which is itself based on `nelly2pcm`.
Fixes #1121, fixes #1118 and partially #5, #929, #1839.
> Implement Nellymoser decoder

- .github/workflows/release_nightly.yml
I was mistakenly thought that `KSXGitHub/github-actions-deploy-aur@v2` is equivalent to `KSXGitHub/github-actions-deploy-aur@v2.2.3`.
> ci: Fix publish AUR package job

- Cargo.lock
- core/Cargo.toml
See https://github.com/tafia/quick-xml/issues/255
> Revert "build(deps): bump quick-xml from 0.20.0 to 0.21.0"

- core/src/font.rs
- core/src/library.rs
I stumbled upon this while researching https://github.com/ruffle-rs/ruffle/issues/3088 ; evaluating fonts for text was copying an entire Glyph (with all its ShapeRecords) for every char of a text. I also noticed this in some other games (N updates a text every frame during loading), but it's nothing major there.
Simple thing to improve and cleanup :) But TBH, I don't really understand why Font methods were written to take `self` in the first place.
> Don't copy Glyphs around; make Font methods take &self

- desktop/src/navigator.rs
It might not succeed.
This unwrap crashes the Newgrounds Meat Boy flash on desktop.
Instead, use unwrap_or_default with an empty path. This will cause
the read to fail, but it's better than crashing the whole program.
The unwrap crash is reproducible with the Meat Boy flash from Newgrounds.
> Don't unwrap url to file path conversion

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
- Fixes #3079 and #3081.
- No longer displays a grey pixel in the bottom left corner of the file (this currently happens once per file).
- Use `ChildNode.removeChild()` instead of `ChildNode.remove()` which is unfortunately overriden by the "prototype.js" library and creates issues (eg. clicking "Run anyway" currently doesn't work [on this file](https://www.nytimes.com/elections/2008/results/president/map.html)).
> web: Miscellaneous fixes

- web/packages/core/package.json
This might be highly `bash`-specific.
I don't know how many people make web builds from other, incompatible shells...
If anyone has a more universal solution, feel free to adjust this.
The logic in this is that after the note about unsuccessful invocation is printed, the script checks if the `GITHUB_ACTIONS` environment variable is _not_ set to `true`, and only succeeds (letting the build continue) then.
> web/build: Make successful wasm-opt invocation mandatory on GitHub Actions

- core/src/avm1/globals/movie_clip.rs
- core/src/display_object.rs
- core/src/display_object/bitmap.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/text.rs
This fixes some (but not all) of the rendering bugs in #1098 
@Dinnerbone offered to make some tests as I have no idea where to even start with that
> avm1: Implement MovieClip.setMask - #17 #263

- render/common_tess/src/lib.rs
- render/wgpu/src/utils.rs
Some recent changes with lyon's API could cause Ruffle to draw extra
strokes when it sees two Move commands in a row -- an extra zero-length
stroke would appear. Let's merge adjacent Move commands in the
tessellator to avoid this issue.
(TODO: Add an example to visual_tests).
For example:
```
mc.lineStyle(10, 0);
mc.moveTo(10, 10);
mc.lineTo(10.5, 10);
mc.lineStyle(10, 0xff0000);
mc.moveTo(10, 30);
mc.lineTo(10.5, 30);
```
Previously:
Correct:
> core: Fix stroke artifacts when using drawing API

- swf/src/string.rs
- swf/src/types.rs
Updated the documentation for SwfStr, Twips, Color, and Rectangle. It's only a couple of types, but this should bring the relevant docs more in line with what Rust recommends (e.g., code examples for everything, even if trivial).
I'll probably try to beef up the documentation of other areas as well in future pull requests.
> docs: Update some documentation in the swf library

- core/src/backend/navigator.rs
- desktop/src/navigator.rs
- web/src/navigator.rs
Do a case-insensitive check for the `javascript:` scheme when allowScriptAccess is false. Fixes #3132.
Also move `run_script` to be a method directly on `WebNavigatorBackend` since it will be unused by desktop.
TODO: Definitely should have a web test for all `allowScriptAccess` affected APIs.
> web: Use case-insensitive check for detecting javascript scheme

- core/src/avm1/activation.rs
It was a bit weird, that `action_get_property` was borrowing mutably and `action_set_property` immutably :) I'm assuming it was a mistake?
Seems to fix the panic in Adobe Presenter in https://github.com/ruffle-rs/ruffle/issues/3199 .
(note: I actually still don't know where the second borrow came from.)
> Don't mutably borrow display_properties for reading

- swf/src/read.rs
- swf/src/types.rs
- swf/src/write.rs
For completeness' sake.
The `DefineVideoStream` header format table in the SWF spec (v19) does not mention this (might be an oversight), but the one for `VideoFrame` does.
> swf: Add VideoCodec::ScreenVideoV2 variant

- core/src/avm1/activation.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/date.rs
- core/src/avm1/globals/math.rs
- core/src/avm1/globals/number.rs
- core/src/avm1/globals/point.rs
- core/src/avm1/globals/rectangle.rs
- core/src/avm1/globals/sound.rs
- core/src/avm1/globals/string.rs
- core/src/avm1/value.rs
- core/src/avm2/activation.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/math.rs
- core/src/avm2/value.rs
- core/src/ecma_conversions.rs
- core/src/shape_utils.rs
- core/tests/regression_tests.rs
- desktop/src/audio.rs
- swf/src/types/matrix.rs
- web/src/lib.rs
The Rust documentation considers numeric constants prefixed with `std::` as deprecated.
For example: https://doc.rust-lang.org/std/u16/constant.MAX.html.
> chore: Avoid deprecated constants

- Cargo.lock
- core/Cargo.toml
- core/tests/regression_tests.rs
Knowing that "hey, this place logged a warning" makes it a lot easier (for me) to spot mistakes
> core: Enable logging in regression tests

- core/src/avm1/globals.rs
- core/src/avm1/globals/video.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/flash.rs
- core/src/avm2/globals/flash/media.rs
- core/src/avm2/globals/flash/media/video.rs
- core/src/backend.rs
- core/src/backend/video.rs
- core/src/backend/video/software.rs
- core/src/character.rs
- core/src/context.rs
- core/src/display_object.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/video.rs
- core/src/library.rs
- core/src/player.rs
- core/tests/regression_tests.rs
- desktop/src/main.rs
- exporter/src/main.rs
- swf/src/read.rs
- web/src/lib.rs
As requested I have extracted all of the non-codec Video support - a fresh display object, associated AVM stubs, and so on. This PR will recognize video tracks in an SWF, store them, and then generate errors as it has no codecs to work with. I've also reorganized the H.263 PR to be downstream of this one. Merging that PR will also merge this one.
I expect the person working on libav VP6 integration (szooloo on Discord but I don't know their Github username) to also make use of this base PR.
As this contains no codecs there should be no patent exposure from merging it.
> Video base/stub impls

- core/src/avm1/activation.rs
- core/src/avm2/activation.rs
- core/src/context.rs
Neither of these impls are actually used.
As a result of this change, several fields in `avm2::Activation` became
unused. I assumed that these fields will become used as more of avm2 is
implemented, so I suppressed the warnings for now
> Remove `Collect` impls from `Activation` and `UpdateContext`

- core/src/display_object/edit_text.rs
The documentation was a bit misleading :)
Fixes https://github.com/ruffle-rs/ruffle/issues/3292.
> Make EditText.border and EditText.background independent

- Cargo.lock
- core/Cargo.toml
- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/globals/date.rs
- core/src/avm1/object/date_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/sound_object.rs
- core/src/avm1/property.rs
- core/src/avm1/scope.rs
- core/src/avm1/value.rs
- core/src/avm2/property.rs
- core/src/avm2/slot.rs
- core/src/backend/audio.rs
- core/src/character.rs
- core/src/context.rs
- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/text.rs
- core/src/external.rs
- core/src/loader.rs
- core/src/player.rs
- core/src/xml/error.rs
Currently, a large number of unsafe `Collect` impls are written manually. In addition to being verbose, the impls risk being out-of-date if additional fields are added to the target struct/enum, leading to unsoundness.
Recent changes to `gc-arena` make it possible to use `#[derive(Collect)]` in many more cases.
This PR removes the majority of manual `Collect` impls, replacing them with `#[derive(Collect)]`. A few impls cannot currently be removed, since they need to iterate over foreign container types (e.g. `SmallVec`) which do not themselves implement `Collect`.
This is currently blocked on https://github.com/kyren/gc-arena/pull/9.
> Replace most manual `Collect` impls with `#[derive(Collect)]`

- web/packages/core/src/shadow-template.ts
- web/packages/demo/www/index.css
- web/packages/demo/www/index.js
Restore changes reverted in #3311, which were originally introduced in #3239.
The problem was a mistaken removal of `position: relative;` in `:host`.
I tested the web demo and http://www.dnai.org/ (reported to be broken in #3305), they seem OK.
> web: Reland style changes in #3239

- web/packages/core/src/ruffle-player.ts
Avoid some excessively long URLs in our GitHub issue headings.
> web: Strip query params from URL in GitHub issue titles

- core/src/lib.rs
- desktop/src/audio.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
- swf/src/read.rs
- web/src/audio.rs
Mostly disable `inconsistent_struct_constructor` and `manual_map` lints.
> chore: Appease clippy

- core/src/avm1/activation.rs
- core/src/avm2/activation.rs
- core/src/display_object/movie_clip.rs
- swf/src/avm1/read.rs
- swf/src/avm2/read.rs
- swf/src/error.rs
- swf/src/extensions.rs
- swf/src/lib.rs
- swf/src/read.rs
- swf/src/string.rs
- swf/src/tag_code.rs
- swf/src/types.rs
Refactor a few things in `swf`, no functional changes
> chore: Cleanup swf parsing

- Cargo.lock
- render/wgpu/Cargo.toml
- render/wgpu/src/pipelines.rs
Bump to wgpu 0.70. Please test on your machine!
Two issues so far:
* Naga validation does not deal with push constants at the moment and throws a validation error on our shaders. Disable validation for now per suggestions from wgpu team.
* Vulkan validation layer spew (see https://github.com/gfx-rs/wgpu/issues/1172 and https://github.com/gfx-rs/wgpu/issues/1175#issuecomment-767702911):
```
VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-03210 (-872316813)] : Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-03210 ] Object 0: handle = 0xd468e0000001651, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xcc018073 | VkRenderPassBeginInfo: Image view #1 created from an image with usage set as 0x11, but image info #1 used to create the framebuffer had usage set as 0x10 The Vulkan …
```
> chore: Bump to wgpu 0.70

- web/package-lock.json
- web/package.json
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
Remove clean-webpack-plugin dependency, which is no longer required because `output { clean: true }` was added in recent Webpack versions. This avoids some incompatibilities I was hitting with recent Webpack versions.
> web: Remove clean-webpack-plugin dependency

- web/package-lock.json
- web/package.json
- web/packages/core/package.json
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
As of #2482, `web/packages/core/package.json` uses `move-file-cli` in its `build:wasm-opt` script. I think it's unnecessary, as it seems to work without it by letting `wasm-opt` optimize `ruffle_web_bg.wasm` in-place.
@torokati44 Am I missing something?
> web: Get rid of move-file-cli

- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
This should fix masks still being active after either their maskee clip or the mask itself are removed via removeMovieClip().
> avm1: Clear masker/maskee properties when using removeMovieClip()

- core/src/avm1/function.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
- core/src/avm2/object.rs
- core/src/avm2/object/custom_object.rs
- core/src/avm2/object/script_object.rs
- core/src/avm2/object/stage_object.rs
- core/src/avm2/regexp.rs
- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
- core/src/html/layout.rs
- core/src/loader.rs
These are pure mechanical changes:
1. Take advantage of the `set` method that `bitflags` offers. For example:
```rust
if value {
flags |= Flags::FOO;
} else {
flags -= Flags::FOO;
}
```
Becomes:
```rust
flags.set(Flags::FOO, value);
```
2. Remove unused `MutationContext` parameters.
3. Rename remaining `MutationContext` parameters from `context` to `gc_context`.
> chore: Random cleanups

- core/src/avm1/activation.rs
These are the changes from https://github.com/ruffle-rs/ruffle/issues/3525#issuecomment-791077972.
Fixes #3501 and #3525, and perhaps #3532 too.
I haven't found any AVM2 content in the reports about this regression. I looked through the AVM2 part of the changes in dad21d43, and found no similar mistake at a first glance.
The problem was most likely with negative relative offsets, as the "rest" of the slice was always there. And these might not be very common.
> Fix regression in AVM1 seeking

- render/webgl/src/lib.rs
Change `Gl::MIRRORED_REPEAT` to `Gl::REPEAT` for the wrapping parameter in repeating bitmaps. Fixes #3591.
I'm not sure this is the right fix, but from what I've seen, this is correct.
Here's an example that now renders correctly in the WebGL backend: [repeating_bitmap.zip](https://github.com/ruffle-rs/ruffle/files/6118096/repeating_bitmap.zip)
> web: Fix repeating bitmap textures rendering

- swf/src/avm2/read.rs
- swf/src/extensions.rs
Variable-length integers are defined to be encoded by up to 5 bytes. But AVM2 reader can read beyond that, if the 5th byte also happens to have a continuation bit set.
`read_encoded_u32` already reads this correctly (it's the same implementation as `read_u30`, just with the 5 bytes limit), so the best course of action is to just deduplicate them.
The tests are copied from the `read_encoded_u32()` test.
(side note: currently in AVM2 reader, `read_u30()` is used wherever u30 _or_ u32 values are being read. Not sure if there is a functional difference, but even if there isn't, it'd be nice to refactor it for clarity)
Fixes https://github.com/ruffle-rs/ruffle/issues/3605 , probably also https://github.com/ruffle-rs/ruffle/issues/2404 and others.
> Fix AVM2 reader not reading variable-length numbers correctly

- core/src/avm1/activation.rs
In some games (meat boy) `instant::now()` was taking 10+% of tick time (and that wasn't even the full recorded overhead of the check), so this still needed to be tuned down. In the future, if other actions become faster, this might need to be tuned down even more.
Why "10+ times"? Because if a small function runs between 200 and 2000 actions, its # of checks will drop to 0.
That raises a side question: should `actions_since_timeout_check` be stored in Context instead of Activation? In practice, I feel like this isn't an issue, as even if an inifinite loop span across a deep call stack, the outermost frame with the loop will amass 2000 actions at _some_ point, right? So the current approach of storing in Activation might even be better as it decreases the frequency of checks without making …
> Reduce frequency of timeout checks by 10+ times

- web/packages/core/src/globals.d.ts
- web/packages/core/src/load-ruffle.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/extension/.eslintrc.json
- web/packages/extension/js/index.js
- web/packages/extension/js/lv0.js
- web/packages/extension/js/util.js
Pulled out from #3426.
Define `__webpack_public_path__` in injected extension script and use `publicPath()` similarly to how selfhosted currently does.
The only behavioral effect should be as mentioned in https://github.com/ruffle-rs/ruffle/issues/3426#issuecomment-787480902, but I don't see it much a problem because none of the errors should really happen in the extension.
> web: Use publicPath() instead of ruffleRuntimePath

- core/src/avm1/globals/movie_clip.rs
Prevent panic when no arguments are passed to MovieClip.setMask, fixes #3298, #3348
> avm1: Fix #3298

- core/tests/regression_tests.rs
Noticed that the `regression_tests` rebuilds were actually taking quite long.
This change reduces rebuild time after editing `regression_tests.rs` from 30s to 10s. Looks like the compiler isn't a fan of thousands of small closures :)
> Speed up builds of regression tests

- web/src/navigator.rs
Fixes the bug described in #3444 by parsing the URL before checking what scheme it is using. Also, instead of running javascript url's by injecting the code in the page, it will now use it like a normal url.
> web: Fix URL sanitizing

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
Continuing from the work in #3160:
* Hide Android navigation bar in fullscreen mode using `navigationUI: "hide"` (fixes #1698).
* Fix content size when fullscreen on Safari (the content would not fill the screen).
> web: Full screen fixes for mobile and Safari

- core/src/backend/audio/decoders.rs
- core/src/backend/audio/decoders/mp3.rs
Previously `cargo build --no-default-features` failed because then neither implementation of `Mp3Decoder` is chosen.
Fix that by not handling mp3 sounds at all in that case.
> core: Fix build without default features

- core/src/avm1/function.rs
- core/src/avm1/object.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
- core/src/player.rs
Follow-up for #3860.
1. Replace all old `proto`/`set_proto` implementations by the new `proto_value`/`set_proto_value` in all `TObject` implementations on a one-by-one basis.
2. Delete `proto`/`set_proto` and rename `proto_value`/`set_proto_value` to `proto`/`set_proto` for more concise code.
This brings us close to a complete migration. Remaining changes are `ScriptObject::object`, `ScriptObject::array`, `ScriptObject::object_cell` etc.
> avm1: Migrate to primitive prototypes (step 2)

- core/src/avm1.rs
- core/src/avm1/object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/timer.rs
Follow-up for #3867.
Migrate `search_prototype` to primitive prototype.
This is the last step, as I don't think migrating `ScriptObject::object`, `ScriptObject::array`, `ScriptObject::object_cell` worth it.
> avm1: Migrate to primitive prototypes (step 3)

- desktop/src/navigator.rs
- web/src/navigator.rs
This PR fixes a bug where Ruffle does not actually check the status code of the files it fetches, the correct behavior is for Ruffle to only return "Ok" if the status code is in the range of 200-299. Fixes #2787
> web/desktop: Check the HTTP status code of requests

- Cargo.lock
- desktop/Cargo.toml
Remove some unused dependencies, and the redundant version specifier of [`dasp`](https://github.com/RustAudio/dasp).
> desktop: Cleanup Cargo.toml

- web/packages/core/src/register-element.ts
Related to #3729.
This changes the infinite loop to
- only catch errors coming from `window.customElements.define`
- throw any errors that aren't `NotSupportedError`
I assumed that if the custom elements don't get registered Ruffle doesn't work so throwing the error is about the only sensible thing, but I may be mistaken.
One other possibility is changing `while (true)` to `while (tries < 999)` (or some other large number) to remove the possibility of an infinite loop.
One other possibility might be to avoid the try-catch by using `customElements.get` instead. That would keep the infinite loop, but avoid the try-catch that caught unwanted errors.
> web: crash out of infinite loop if not NotSupportedError

- core/src/backend/render.rs
`data` could be shorter than 4 bytes.
Fixes #2371.
Fixes #2908.
> core: Fix panic in `remove_invalid_jpeg_data`

- render/canvas/src/lib.rs
This sounds common-sense correct, and it does fix https://github.com/ruffle-rs/ruffle/issues/2403 , but I didn't check if it breaks/fixes anything else.
> canvas: Update_texture should update in-place, not insert

- web/packages/core/src/ruffle-player.ts
Set a flag as soon as a touch event is seen to disable the context menu. This prevents the context menu from appearing from a long press and interfering with gameplay on touch devices.
This does mean there is no way to display the context menu on mobile, but this is preferable to interfering with gameplay until we decide on an alternative way to trigger it. The context menu will also be disabled in corner cases where, for example, a laptop has both a mouse and touch.
Fixes #1972.
> web: Disable context menu from touch events

- web/packages/extension/assets/css/player.css
- web/packages/extension/assets/player.html
- web/packages/extension/manifest.json
- web/packages/extension/src/background.js
- web/packages/extension/src/player.js
- web/packages/extension/webpack.config.js
Fixes #2167.
Tested on Chrome and Firefox.
TODO: Currently saving the page (e.g. using Ctrl+S) downloads the HTML page instead of the playing SWF. After some experiments with the [`chrome.downloads`](https://developer.chrome.com/docs/extensions/reference/downloads/) API, it seems to be somewhat possible to download the SWF instead, but under some limitations (e.g. The "Save As..." dialog still suggests the name of the HTML page, saving the SWF outside of the Downloads directory might not be possible). Also I didn't check if/how it's possible on Firefox and Safari.
> web: Handle direct SWF links

- core/src/avm1/globals/load_vars.rs
- core/src/avm1/globals/xml.rs
Should fix #3942, progresses on #2986.
Heavily inspired by the corresponding behaviour in LoadVars.
The spec says that `contentType` is used as the `content-type` header; I found it was ignored and `application/x-www-form-urlencoded` used no matter what.
Flash sends particular headers by default; I just left it doing whatever the current implementation does. The XML sent isn't byte-for-byte identical to Flash but I figured that is probably a Ruffle bug.
Examples of a request: request, headers, body
Flash:
```
HTTP 1.1 POST /xml/send_and_load
{
referer: 'http://localhost:8080/xml/send_and_load',
'content-type': 'application/x-www-form-urlencoded',
'content-length': '34',
'user-agent': 'Shockwave Flash',
host: 'localhost:8080',
'cache-control': 'no-cache'
}
<translate text="Hello, world!" …
```
> avm1: XML sendAndLoad

- .github/workflows/release_nightly.yml
Missed this part the first time around. Ensure the workflow has access to the environment variables for signing the Mozilla extension.
Add the "workflow_dispatch" event to the exceptions of the activity check (so I can manually run the nightly build!).
> ci: Add Mozilla add-on variables

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- Cargo.lock
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- render/wgpu/Cargo.toml
- render/wgpu/src/lib.rs
- render/wgpu/src/pipelines.rs
- render/wgpu/src/target.rs
- render/wgpu/src/utils.rs
- web/Cargo.toml
- web/README.md
- web/common/Cargo.toml
Bump wasm-bindgen to 0.2.73, and wgpu to the latest master.
The latest wgpu master unpins the wasm-bindgen version, so it no longer forces us to stick with an older version. I was hoping the new [feature resolver in Rust 1.51](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver) might help with this, but I was still hitting the same problem of wgpu pinning our wasm-bindgen version, so let's get the wgpu from master. This lets us bump our wasm-bindgen version. There are also API changes in wgpu that are helpful to fix sooner than later.
> chore: Bump wasm-bindgen and wgpu versions

- core/src/avm1/object/transform_object.rs
This is now possible thanks to #2415.
> avm1: Return an unboxed undefined in `TransformObject` constructor

- web/packages/core/src/ruffle-player.ts
This removes the "Report Bug" link from the error case in which WebAssembly code generation is disallowed by the host's content security policy, because there's nothing we can do to fix that, and directs people to the wiki instead.
The [wiki section](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-wasm-csp) I created and link to here is currently a bit barebones, but can be expanded upon later.
> web: Handle errors from content security policies which block WebAssembly

- web/packages/demo/www/index.css
The upload file button was hidden on mobile phones with screens smaller than or equal to 600px. Here's how this looks on 320px (the generally agreed upon minimum width to design for).
Edit: The look is unchanged by the second commit. "display: table;" and "display: block;" were functionally identical in this case, but "display: block;" is the more logical choice.
> Demo: Allow small screens to still upload local files

- web/packages/demo/README.md
For the sake of the links working in https://github.com/ruffle-rs/demo
> demo: Use absolute URLs for links in README

- core/src/avm2/globals/flash/display/displayobject.rs
It feels like this would be in a better place inside `::from_movie`, but then I'd have to pass in the entire `activation`, and I haven't seen similar anywhere else.
Should I still move it in there?
I also tried to check for any other instance of the same mistake, but don't know enough of this part of the project to really recognize any.
This resolves an error in https://z0r.de/3068 ([SWF](https://z0r.de/L/z0r-de_3068.swf)), that happens when a frame script calls `addEventListener` on `root.loaderInfo`, which then finds the `dispatch_list` property inherited from `EventDispatcher` to be `Undefined`.
> Call the super initializer of LoaderInfo after construction

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/object/bitmap_data.rs
This will eventually help with https://github.com/ruffle-rs/ruffle/issues/2240.
Tested visually using this code: https://gist.github.com/torokati44/a56c961788597a203edbe45ff999ce7b
Compiled into: [BitmapMerge.zip](https://github.com/ruffle-rs/ruffle/files/6340038/BitmapMerge.zip)
As well as with a few other variations of the transparency property of the source and destination bitmaps, and the `channelOptions` parameter of the `perlinNoise()` call used to fill them.
The test as linked above produces this output in Adobe Flash Player:
The difference of the output of Ruffle from that is, **remapped from 0..2 to 0..255**:
The formula used is pasted directly from the AS2 reference.
I might play around with different rounding options to get the results to match closer.
> avm1: Implement BitmapData.merge()

- web/package-lock.json
- web/packages/core/src/load-ruffle.ts
- web/packages/demo/package.json
- web/packages/demo/webpack.config.js
- web/packages/extension/manifest.json5
- web/packages/extension/package.json
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/package.json
- web/packages/selfhosted/webpack.config.js
Key changes:
* Migrate the deprecated [`file-loader`](https://webpack.js.org/loaders/file-loader/) to [asset modules](https://webpack.js.org/guides/asset-modules/) as suggested.
* Convert the extension's `manifest.json` to [JSON5](https://json5.org/), which is a more flexible superset of JSON. It supports comments, trailing commas and more nice features that JSON doesn't support.
> web: General improvements

- Cargo.toml
Turn on cargo's new [feature resolver v2](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver), added in Rust 1.51.0. Don't know if this will have any effect, but it will be default in Rust 2021 edition. Let's try it a little early to see if it breaks anything.
> chore: Switch to new cargo resolver

- core/src/player.rs
- core/tests/regression_tests.rs
Disable script timeout by default in debug builds. This was annoying me when attaching a debugger.
Tests set the timeout value explicitly, so no effect on tests. Bump the test timeout value a bit because CI is sometimes hitting it.
> core: Disable script timeout in debug builds

- web/packages/extension/src/content.ts
#4092 was not proper because `document.xmlVersion` doesn't exist in Firefox.
So use another method to detect XML documents as described in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlVersion).
Really fixes #4090.
> extension: Avoid script injection in XML documents

- Cargo.lock
- render/wgpu/Cargo.toml
Bumping wgpu in b31b00c6d639148a3833dfb121f24f54507101b4 seems to have broken the Metal backend on macOS:
```
wgpu error: Validation Error
Caused by:
In Device::create_render_pipeline
Internal error in stage VERTEX: Error compiling the shader "\"Compilation failed: \\n\\nprogram_source:33:39: error: use of undeclared identifier \\\'_2\\\'\\n    _.gl_Position = (_1.view_matrix * _2.world_matrix) * metal::float4(_e23.x, _e23.y, 0.0, 1.0);\\n                                      ^\\n\""
thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/runner/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/50e0577/src/backend/direct.rs:1942:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort trap: 6
```
Bumping again to the latest master works, at …
> wgpu: Bump to latest master

- .github/workflows/release_nightly.yml
- PKGBUILD
* Specify `--package ruffle_desktop` on the desktop builds to avoid extraneous compiling
* Move the web build into its own job so it can run parallel with the desktop jobs.
* Make a build for Apple Silicon Macs, and generate universal binaries
* Build matrix includes both `x86_64-apple-darwin` and `aarch64-apple-darwin` targets.
* A following job takes both binaries and [lipo](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary)s them into a universal binary (needs testing)
* Make a 32-bit Windows build (`i686-pc-windows-msvc` target)
Questions/TODO:
* ~I don't have an M1 Mac, so need someone to verify the binary actually works~ (a friend verified that M1 works, thanks!)
* Do we want a 32-bit Windows build? There has been at least one or two issues …
> ci: Refactor nightly release script

- web/package-lock.json
- web/package.json
- web/packages/core/package.json
Update package.json and package-lock.json.
Remove `@types/source-map` dependency as it is deprecated, and the deprecation warning says it is no longer needed.
> chore: Bump JS packages

- core/src/display_object/video.rs
Fixes the too small image in [z0r.de/6812](https://z0r.de/6812) ([SWF](https://z0r.de/L/z0r-de_6812.swf)) and [z0r.de/6813](https://z0r.de/6813) ([SWF](https://z0r.de/L/z0r-de_6813.swf)).
For any reasonable testing, the commits in #2173 and/or #3004 are needed.
> Correctly draw videos that have different bounds than the size of their actual frame data

- core/src/avm1/globals/stage.rs
- core/src/avm2/globals/flash/display/stage.rs
- core/src/display_object/stage.rs
- core/src/player.rs
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
Supported:
- - [x] `Stage.showMenu` in AVM1
- - [x] `Stage.showDefaultContextMenu` in AVM2 (note: didn't check if this shares the underlying flag with AVM1)
- - [x] partial `ContextMenu.builtInItems` support (see below)
Not supported, out of MVP scope:
- - [ ] only supported on top-level movie clip (supporting .menu on arbitrary InteractiveObjects would require bigger rework of finding hovered items)
- - [ ] currently AVM1 only
- - [ ] "menu" property is read as an ordinary AS property lookup, while it should probably be retrieved from the Rust object directly via trait method. I think this might as well be done after InteractiveObject refactor? (as that's where menu property resides)
- - [ ] generally the code looks kinda ugly
Also no tests.
Playing with this PR exposes some bugs when …
> Basic context menu playback control items MVP

- Cargo.lock
- web/Cargo.toml
- web/src/lib.rs
Start some much needed clean up of the Rust code on the web. Remove all unwraps and avoid panics in web/lib.rs.
This should help avoid many of the panics we see in issues, e.g.: #3083, #4116, #4149... The root issues still need investigation, but mostly seems to be a) Ruffle trying to execute code after an instance has been destroyed, or b) a code loop between the Ruffle web instance and core that results in a double borrow panic. We should be able to gracefully ignore these.
* Add convenience methods for grabbing the Ruffle web instance.
These methods make the code much nicer to read and also avoid panics/unwraps when borrowing
`RefCell`/`Mutex`.
* Use `warn_on_error` to avoid unwraps from web APIs.
Future PRs
* Clean up the JS event management code on the Rust side. I picture something …
> web: Remove unwraps from Rust glue

- Cargo.lock
- core/Cargo.toml
- core/src/backend/audio/decoders.rs
- core/src/backend/audio/decoders/mp3.rs
- web/Cargo.toml
- web/src/audio.rs
Remove the unused puremp3 dependency. Possibly replace with https://github.com/pdeljanov/Symphonia if/when start actually decoding MP3 ourselves on web.
> chore: Remove puremp3 feature

- CONTRIBUTING.md
Some notes about tests, mostly so the `mtasc` information is more accessible, but also I think it helps to note down what's required for tests instead of letting people figure it out by convention.
There are lots of other `.as` files in the tests, some folders have both a `.as` and a `.fla` file, but I don't know what's going on there so I just documented the ones I understood.
> docs: test guidelines

- desktop/src/main.rs
Change width/height CLI paramters to `f64`, and also clamp window
size to minimum of 1x1 to prevent panics from invalid window
dimensions.
> desktop: Fix window size calculation

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
GitHub Actions runners updated to Ubuntu 20.04, so run apt-get
update to ensure we can install our Linux dependencies (namely
libasound2).
> ci: Run apt-get update

- web/packages/core/src/ruffle-player.ts
This time I made sure the `String.fromCharCode` actually made its way into final .js :)
Also swapped out ☑ for ✓ (will better fit when it's moved to the left at some point, I think)
> Fix context menu checkmark in web builds

- swf/src/types/fixed.rs
Use `#[cfg_attr(debug_assertions, should_panic)]` to ensure that
the tests only expect to panic in debug builds.
Fixes #4313.
> tests: Fix swf::Fixed tests in --release (fix #4313)

- swf/src/string.rs
The string will now be surrounded with quotes (`"`), non-ASCII characters (UTF-8 or not) will be escaped in hexadecimal form (`\xNN`) and ASCII control characters will be escaped (`\x01`, `\n`, `\t`).
This brings the result closer to the output of `str`'s `Debug`.
> swf: SwfStr: reimplement `Debug` with `std::ascii::escape_default`

- core/src/avm1/globals/movie_clip.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
Use bitflags for `HitTestOptions`, and store a few common presets as constants.
> core: Use bitflags for HitTestOptions

- core/src/avm2/class.rs
- core/src/avm2/method.rs
- core/src/avm2/regexp.rs
- core/src/avm2/script.rs
- core/src/avm2/traits.rs
- core/src/collect.rs
- core/src/display_object/video.rs
- core/src/html/layout.rs
- core/src/lib.rs
No longer necessary, it is possible to mark individual fields
as `#[collect(require_static)]`.
> core: Remove collect::CollectWrapper

- core/src/html/layout.rs
If a textfield has word wrapping enabled, is very small in size and
tries to layout a single character onto it, the layout code can run into
an endless loop where it's creating new lines and trying to fit the text
again.
If text doesn't fit at the start of a line, it won't fit on the next
either, so abort and display the whole text span on the line. Text will
be cut-off.
This can be reproduced with a AS2 file like this:
class Test {
static var app : Test;
function Test() {
_root.createTextField("tf",0,0,0,6,20);
_root.tf.text = "0";
_root.tf.wordWrap = true;
}
static function main(mc) {
app = new Test();
}
}
Build it with `mtasc -main -header 10010030 test.as -swf test.swf`
---
Noticed this issue here: https://www.newgrounds.com/portal/view/463278 …
> Fix endless loop when layouting text

- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
There's currently no way to completely disable the unmute overlay when `autoplay` is `on`: setting `unmuteOverlay` to `hidden` doesn't show the overlay but still requires an interaction if the browser prevents the AudioContext from starting (this is the intended behavior).
To bypass this, the PR adds a new `none` value to the `unmuteOverlay` option (which should only be used with files that don't play any audio since there's no way to resume it if the browser prevents the AudioContext from starting).
> web: Add a `none` value to completely disable the unmute overlay

- render/canvas/src/lib.rs
Fix alpha calculation regression on canvas backend. The change to using fixed point internally means alpha is already normalized.
> canvas: Fix alpha calculation in canvas renderer

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/globals/context_menu.rs
- core/src/avm1/globals/shared_object.rs
In favor of `ScriptObject::object` and `ScriptObject::array`, which always succeed.
> avm1: Remove unnecessary calls to create_bare_object

- core/src/avm1/function.rs
- core/src/avm1/globals/object.rs
- core/src/avm1/object.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
`add_property_with_case`, `set_watcher` and `remove_watcher` already take an `activation`, from which the `gc_context` can be retrieved.
> avm1: Remove unnecessary gc_context parameters

- core/src/context_menu.rs
Previously `cargo build --no-default-features` failed because then `serde` was not found.
Fix that by not implementing serde's traits in that case, similarly to `config.rs`.
> core: Fix build without serde feature

- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/timer.rs
- core/src/avm2/globals/flash/display/loaderinfo.rs
- core/src/display_object.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/video.rs
- core/src/library.rs
- core/src/loader.rs
- core/src/player.rs
- core/src/tag_utils.rs
- desktop/src/main.rs
- exporter/src/main.rs
- swf/examples/reading.rs
- swf/examples/writing.rs
- swf/src/read.rs
- swf/src/test_data.rs
- swf/src/types.rs
- swf/src/write.rs
- tests/tests/regression_tests.rs
- web/packages/core/src/movie-metadata.ts
- web/packages/selfhosted/test/js_api/metadata.js
- web/src/lib.rs
When reading an SWF, search the first few SWF tags for FileAttributes and SetBackgroundColor tags and return this with the other header metadata.
Motivation:
* This metadata is generally useful when using `swf` as a crate, and there have been a few feature requests about it. See for example swfchan displaying background color information.
* In particular, the AS3 flag in FileAttributes is useful to know as early as possible. This significantly cleans up a lot of Ruffle code that seemed unsure about the AVM type of the movie. Specifically I'd like to move toward `Player` having `Avm1` and `Avm2` inside an enum, so only one can exist at a time.
Changes:
* HeaderExt contains all of the normal header info, in addition to the FileAttributes/SetBackgroundColor info.
* Add various accessors to …
> swf: Add swf::HeaderExt with additional info

- core/src/avm1/object/bevel_filter.rs
- core/src/avm1/object/bitmap_data.rs
- core/src/avm1/object/blur_filter.rs
- core/src/avm1/object/color_matrix_filter.rs
- core/src/avm1/object/color_transform_object.rs
- core/src/avm1/object/convolution_filter.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/date_object.rs
- core/src/avm1/object/displacement_map_filter.rs
- core/src/avm1/object/drop_shadow_filter.rs
- core/src/avm1/object/glow_filter.rs
- core/src/avm1/object/gradient_bevel_filter.rs
- core/src/avm1/object/gradient_glow_filter.rs
- core/src/avm1/object/shared_object.rs
- core/src/avm1/object/sound_object.rs
- core/src/avm1/object/transform_object.rs
- core/src/avm1/object/value_object.rs
This add two knobs to the `impl_custom_object!` macro:
- `set(...)`, for using a specific prototype in the `set` method;
- `bare_object(...)`, for objects that are convertible to a raw object type.
> [avm1] extend impl_custom_object! to reduce boilerplate

- web/packages/core/package-lock.json
- web/packages/core/src/js-polyfills.ts
- web/packages/core/src/plugin-polyfill.ts
Should allow #4468 to pass.
The `declare global`s for `PluginArray` and `MimetypeArray` should be enough for that, I just saw some other places in the same area that could be cleaned up a bit. I can revert those if desired.
> web: improve typescript types

- web/README.md
Very minor docs update: the node versions used by actions were updated in #2974, but the docs weren't.
> docs: correct tested node versions

- core/src/avm1/function.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/object.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
* Add `TObject::set_local` so `TObject::set` is never overridden. Also `ScriptObject::internal_set` is now split to `TObject::set` and `ScriptObject::set_local`.
* Make `TObject::get_local` return `None` when the property doesn't exist, instead of relying on `TObject::has_own_property` to tell that (because `StageObject::has_own_property` doesn't return `true` for all names handled by `StageObject::get_local`).
> avm1: Refactor TObject

- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/text.rs
- core/src/library.rs
PR #4540 allowed shapes to replace their inner art handles via
replace PlaceObject tags. This can also happen for morph shapes and
static texts.
Add MorphShape::replace_with and Text::repalce_with. This fixes the
incorrect art in main menu buttons of Super Mario 63.
> core: Allow MorphShapes and Texts to be replaced via PlaceObject

- web/packages/demo/www/index.html
Fix #2910
I'm fairly sure the code in [ruffle-rs/ruffle-rs.github.io/_includes/head.html](https://github.com/ruffle-rs/ruffle-rs.github.io/blob/master/_includes/head.html) never applied on the demo page. Even back when the demo page was not part of its own repo, I did not see an include statement on it, even in the initial commit: [ruffle-rs/ruffle-rs.github.io/demo/index.html@`479675a`](https://github.com/ruffle-rs/ruffle-rs.github.io/blob/479675ad142cc97847a63f1acb038ab055fefb42/demo/index.html).
I also created https://github.com/ruffle-rs/ruffle-rs.github.io/pull/52 to remove the unneeded code from `head.html`.
> demo: Add favicon to demo page

- core/src/avm1/activation.rs
- core/src/avm2/activation.rs
- core/src/display_object.rs
Instead prefix the unused variables with an underscore.
> chore: Avoid unused_variables annotations

- core/src/avm1/globals/movie_clip.rs
- core/src/display_object.rs
- core/src/display_object/movie_clip.rs
- core/src/events.rs
* Rename movie_clip::ClipAction to movie_clip::ClipEventHandler.
* Store the swf::ClipEventFlag event flags that trigger the event
directly in the event handler. Previously we split up any event
that had multiple event flags into separate events. Now these
can be kept as a single event.
* Remove `MovieClip::has_button_event`, and instead store the
union of all event flags in `MovieClip::clip_event_flags`. This
will be useful for other cases in the future.
> core: Use swf::ClipEventFlag in stored clip event handlers

- core/src/avm1/activation.rs
- core/src/avm1/function.rs
- core/src/avm1/globals/array.rs
- core/src/avm1/globals/as_broadcaster.rs
- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/globals/color_matrix_filter.rs
- core/src/avm1/globals/context_menu.rs
- core/src/avm1/globals/convolution_filter.rs
- core/src/avm1/globals/gradient_bevel_filter.rs
- core/src/avm1/globals/gradient_glow_filter.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/string.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/object.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
- core/src/display_object/edit_text.rs
- core/src/external.rs
- core/src/html/text_format.rs
The current `TObject` array methods have some wrong assumptions about AVM1:
* An `Array` can have a negative length:
```as
var a = new Array(-1);
trace(a.length); // -1
```
* Although getting `length` doesn't invoke getters added using `addProperty`, it still might throw an exception because of `valueOf`:
```as
var o = { length: { valueOf() { trace("in valueOf"); throw "error"; } } };
Array.prototype.push.call(o); // traces "in valueOf"
trace("unreachable"); // not reached because of exception
```
* Similarly, setting `length` doesn't invoke setters added using `addProperty`, but it still invokes watchers which might throw an exception:
```as
var o = {};
o.watch("length", function() { trace("in watcher"); throw "error"; });
Array.prototype.push.call(o, 0); // traces "in watcher" …
```
> avm1: Rewrite TObject array methods

- core/src/player.rs
I originally missed its existence and only realized this when randomly browsing documentation :)
> avm1: Call ContextMenu.onSelect before preparing context menu items

- core/src/avm1/globals/matrix.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/backend/render.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/drawing.rs
- core/src/library.rs
- render/canvas/src/lib.rs
- render/common_tess/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
Implements `MovieClip.beginBitmapFill`. Also removes the dependency of the render backends on `MovieLibrary`. This will allow for more decoupling later to improve compile times.
> avm1: Implement MovieClip.beginBitmapFill

- core/src/avm1/activation.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm2/globals/flash/display/stage.rs
- core/src/display_object.rs
- core/src/display_object/stage.rs
The quality setting is still unused by Ruffle, but this implements the getters/setters so that the setting is stored and proper values are returned to user code. We could pass this along to the renderer and actually act on it. For example, enforcing no bitmap smoothing when quality is `Low`, which may be used by some pixel art movies.
* Add `display_object::stage::StageQuality` enum.
* `display_object::Stage::quality`/`set_quality` controls the value.
* Wire up AVM1 `_quality` property, `_highquality` property, and `ToggleHighQuality` op.
* Wire up AVM2 `Stage.quality`.
> core: Implement Stage quality properties

- core/src/backend/render.rs
Looks like a simple omission.
I've seen cases (#4392) where `out_data.len()` is 35MB, but `out_data.capacity()` reaches 67MB, so that could help there a little bit - isn't anywhere close to solving it ofc.
> Preallocate bitmaps for remaining cases in decode_define_bits_lossless

- core/src/avm1/object/stage_object.rs
- core/src/backend/audio.rs
Store the `_soundbuftime` value inside `AudioManager`. This setting still has no effect in Ruffle, but the value will be properly stored and returned.
> avm1: Wire up _soundbuftime

- core/macros/src/lib.rs
- core/src/avm1.rs
- core/src/context.rs
- core/src/display_object.rs
- core/src/ecma_conversions.rs
- core/src/events.rs
- core/src/font.rs
- core/src/matrix.rs
- core/src/player.rs
- core/src/shape_utils.rs
Reviewed and fixed some minor spelling/grammar related issues within the documentation of 'core' files.
(Note: Just trying to get more experience with GitHub contributions with low-risk changes.)
> core: Fix documentation spelling

- core/src/avm1/globals/shared_object.rs
This fixes the stack overflow in https://github.com/ruffle-rs/ruffle/issues/4631 (after you change locations after getting the crowbar early on)
Note: if there ever was a special case in FP where it _did_ somehow serialize some contents of MovieClips, this will break saving this.
In particular, I haven't tested custom AS classes deriving from MovieClip, as... I don't really know how :( Feel free to block this if you think this needs to be checked first.
> avm1: Don't attempt to serialize MovieClips

- core/src/avm1/activation.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/scope.rs
- core/src/display_object.rs
- core/src/display_object/container.rs
- core/src/display_object/graphic.rs
- core/src/display_object/movie_clip.rs
- core/src/library.rs
- core/src/loader.rs
- core/src/player.rs
- swf/src/types.rs
* Prefer "MovieClip" in comments.
* Prefer "mc" for variable names.
> chore: Avoid spelling "movieclip"

- web/package-lock.json
- web/package.json
- web/packages/core/.mocharc.json
- web/packages/core/package.json
- web/packages/core/test/tsconfig.json
- web/packages/core/test/version-range.ts
- web/packages/core/test/version.ts
Along with some cleanups, fix the integration of mocha with ES modules using the workaround from [here](https://github.com/mochajs/mocha-examples/tree/master/packages/typescript#es-modules.).
The [`cross-env`](https://www.npmjs.com/package/cross-env) package is for both Unix and Windows systems support.
Closes #4630.
> web: Cleanup tests

- web/packages/core/package.json
Since #3111, `wasm-opt` became mandatory on GitHub Actions. But the check whether we run on GitHub Actions is Bash-specific, and fails on Windows. That means builds on Windows without `wasm-opt` always fail.
As a workaround, use the trick from https://gist.github.com/prail/24acc95908e581722c0e9df5795180f6 to run the check only on Unix, and skip it on Windows:
```
echo ; [ \"$GITHUB_ACTIONS\" != true ] # > nul
```
On Unix, `echo` does nothing, the check runs, and the rest is considered a comment.
On Windows, `echo` prints everything until the `> nul`, which suppresses the print by redirection, making the whole statement effectively a no-op.
Fixes #3162.
> web: Fix build without wasm-opt on Windows

- core/src/avm1/activation.rs
The current version just doesn't make any sense.
The fixed version is akin to the `target.starts_with("_level") && target.len() > 6` line a bit earlier in this file.
> Fix minor bug/typo in `action_get_url_2`

- render/wgpu/src/clap.rs
This way, if one's card only supports DX11, they don't need to explicitly pass `-g dx11`.
> desktop: Add DX11 to default graphics backends

- desktop/src/main.rs
(The inversion with `dont` is there because I couldn't find a Clap feature to make a true-by-default flag. (Python has this as `action='store_false')`))
> desktop: Add a flag to disable AS3 warning popup

- web/packages/core/src/ruffle-player.ts
I'd still prefer replacing it with a page like https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#addressing-a-compileerror, but this should work.
> web: Remove error report link from could not download wasm module

- Cargo.lock
- core/Cargo.toml
- core/src/backend/audio/decoders/pcm.rs
- web/Cargo.toml
Extract a `read_sample` method to avoid code duplication, and use the [`byteorder`](https://docs.rs/byteorder/1.4.3/byteorder/) crate as already done in other places.
> core: Refactor PCM decoder a bit

- web/packages/core/src/ruffle-player.ts
i fully intended to press "run anyway" just to see what happened, and it was annoying that Ruffle took me to another page so i had to re-load the flash.. (from a page with 10 seconds worth of ads before playing the flash, even)
> open "not yet supported more info" in new tab

- swf/src/avm1/read.rs
- swf/src/avm1/write.rs
Each function is reduced to just 3 opcodes on x86: https://godbolt.org/z/n6q6zxnh6
WebAssembly benefits as well: https://godbolt.org/z/fcETE9GYn
This should improve load-time performance because `read_f64_me` is used frequently (for each AVM1 double constant).
> swf: Optimize `read_f64_me` and `write_f64_me`

- web/.eslintrc.json
- web/README.md
- web/package-lock.json
- web/package.json
- web/packages/core/package.json
- web/packages/core/src/.eslintrc.json
- web/packages/demo/webpack.config.js
- web/packages/extension/src/.eslintrc.json
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
* Remove `buildProduction` as it was equivalent to `build`.
* Fix `build:avm_debug` and change it to `build:debug`, which also disables Webpack optimizations.
Fixes #4480.
Supersedes #4726.
> web: Fix and cleanup npm build scripts

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- Cargo.lock
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- web/Cargo.toml
- web/README.md
- web/common/Cargo.toml
1. Remove unused `wasm-bindgen-test` dependency - It's unclear how/whether it was used at all in the past...
2. Bump `wasm-bindgen` to 0.2.74 - Also bump its helper crates (`js-sys`, `wasm-bindgen-futures`) to the latest versions, except for `web-sys` which seems to be locked by wgpu to one version before the latest (0.3.50).
> chore: Bump wasm-bindgen to 0.2.74

- core/src/avm1/object/bitmap_data.rs
It was regressed in #4822 when changed to use `flat_map`. But currently Rust emits suboptimal code for such case. For now use `Vec::with_capacity` manually to avoid unnecessary re-allocations.
> avm1: Fix performance regression in `BitmapData::pixels_rgba`

- core/src/avm1/globals/shared_object.rs
Instead, rely on the `TObject::as_*` methods to tell what kind the serialized object is.
> avm1: Don't rely on prototypes during serialization

- web/packages/core/src/load-ruffle.ts
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
Use wasm-bindgen's built-in loader instead of relying on Webpack.
This allows to no longer declare .wasm files as resource assets in each `webpack.config.js`.
Also the bundled JS is a bit smaller (e.g. demo is now ~88KB vs. ~90KB before).
> web: Simplify .wasm loading

- web/packages/core/src/load-ruffle.ts
- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
This reverts commit 66bfff7687e4885eb6b0a9699b06ce806a3ba579.
Reason: It stops using `publicPath` for the .wasm location, and instead assumes the .wasm is always in the same directory as the .js. But from some reason ridesims.com fetches the .js manually and injects a <script> tag with the source code inline, so the .js doesn't know its origin URL.
> Revert "web: Simplify .wasm loading"

- CONTRIBUTING.md
This corrects the link to the *Commit Message Guidelines* section in the `CONTRIBUTING.md` file
Sorry in advance if I've done anything wrong, this is my first time opening a PR for this project, found this minor mistake while reading through the doc.
> docs: Fix CONTRIBUTING.md table of contents link

- .github/workflows/test_rust.yml
The [kisak-mesa PPA](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) removes older versions of the `mesa-drivers` package, so installing an exact version fails in the CI.
Remove the version requirement so this doesn't happen.
I also considered limiting to something more general: 21.1 or 21, say. I think given the state of the repository those will eventually fail as well, so it's better to leave it at the edge and keep going, updating the code if any breaking changes occur.
> fix: remove the version requirement for mesa drivers

- core/src/backend/ui.rs
- core/src/loader.rs
- desktop/src/ui.rs
- web/packages/core/src/polyfills.ts
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
- web/src/ui.rs
Things left to do:
- ~~write a nice user-facing message~~
- test a bit more? I only tested it on http://www.nitrome.com/games/faultline/ and tested other cases by flipping the conditions in code
- the `isExtension` check seems to work, but not sure if `setIsExtension()` is the best way to do it design-wise
- ~~decide on Rust-layer design, not sure which is better:~~
- ~~current: `Loader` panics, then the JS panic handler optionally calls `displayCorsWalkaroundMessage()` if walkaround conditions are met~~
- alternative: `Loader` calls `player.ui.display_cors_walkaround_message()` without panicking, then the JS function falls back to `panic()` if walkaround conditions aren't met
Also: it appears that all `Loader::Error` cases are eaten by `spawn_future` and turned into just `log::error`? …
> Extension: Sidestep CORS issues by offering to load the SWF in a tab

- web/packages/core/src/ruffle-player.ts
- web/packages/extension/src/player.ts
~~Draft, because it builds on top of the `isExtension` feature from https://github.com/ruffle-rs/ruffle/pull/4665 . After that gets accepted, this also will be merge-able.~~
Just a small piece of helpful info for triage :)
EDIT: also added this into to the context menu version string.
> web: add isExtension info to panic info and context menu version string

- swf/README.md
Like the previous ones, inspired by the examples but using more generic filenames.
> docs: update swf README to have working examples

- web/packages/core/src/ruffle-player.ts
This can be used by someone who expects it to indicate when the swf is fully loaded, without fear that that functionality will change in the future (which means it will need to be changed when streaming support is added). Based on https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadeddata_event.
**Edit:** This builds on top of #4084, so there are some important things to note. First, that PR said RufflePlayer.readyState was supposed to mimic the media APIs. However, https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState has 5 possible values, not just 3. I'm not saying Ruffle should duplicate that, but loadeddata triggers when the ready state is HAVE_CURRENT_DATA for media elements, so it may not be the best name for the event for the RufflePlayer, …
> web: Add a loadeddata event, which triggers when loadedmetadata does for now

- core/src/avm1.rs
- core/src/avm1/error.rs
- swf/src/avm1/opcode.rs
- swf/src/avm1/read.rs
- swf/src/error.rs
- swf/src/tag_code.rs
Flash continues in such case, so just warn instead of failing.
Fixes #3060.
> swf: Ignore length mismatch in `read_action`

- web/packages/core/src/ruffle-player.ts
Compare the appearance of http://www.juegosjuegos.com/embed/witch-creator on Chrome to its appearance on Firefox. On Firefox, the error message is "Error message: wasm validation error: at offset 158589: bad type", and there is a Report Bug button. On Chrome, the error message is "Error message: WebAssembly.instantiate(): unknown section code #0x2f @+4405019" and there is no report bug button. There were two options to fix this:
1) Check if the message includes "webassembly.instantiate" or "wasm validation error", not just "webassembly.instantiate"
2) Assume every CompileError that does not include the message "disallowed by embedder" is caused by a botched deployment.
I went with option 2, as I believe that is actually accurate. If I am mistaken, I can switch to option 1. Mozilla's docs …
> web: Link all CompileErrors to wiki without a report bug button

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- Cargo.lock
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- web/Cargo.toml
- web/README.md
- web/common/Cargo.toml
Also bump its helper crates (js-sys, wasm-bindgen-futures) to the latest versions, except for web-sys which seems to be locked by wgpu to 0.3.50.
> web: Bump wasm-bindgen to 0.2.75

- Cargo.lock
- core/Cargo.toml
Fixes CI breakage caused by ruffle-rs/rust-flash-lso merging in the `ruffle` branch we were depending on.
> chore: Update `flash-lso`'s dependent commit ID

- web/packages/demo/www/index.js
It seems Mobile Safari on iOS refuses to allow selection of any files when the "accept" attribute doesn't contain any file types it recognizes. To fix this, detect when the demo is running on an iOS device and remove the "accept" attribute from the file input in that case.
Fixes: 2d0c76c06f58 ("demo: Only accepts .swf and .spl files")
Please note that I don't do web development very often, so I'm not really up-to-date on best practices. If this code snippet works better in some other place, or if there's a better way to fix this issue, please let me know.
> demo: Fix local file uploads on iOS

- core/src/player.rs
Seems like a main swf is doing loadMovie on another swf. The second swf calls mouse.hide(), runs, and runs loadMovie on the original to _root without calling mouse.show().
I assume that when a movie is reloaded to root it should reset whether the mouse is visible.
I'd like an opinion of whether my assumption and the placement of the assignment are correct.
> core: Reset mouse visible when loading movie to root (Fixes #4358)

- core/src/html/layout.rs
- core/src/html/text_format.rs
Another `rustc` release, another weird clippy lint in nightly that contradicts one in stable.
> CI FIXES / Clippy compliance with latest nightly compiler

- web/packages/extension/manifest.json5
- web/packages/extension/webpack.config.js
Firefox doesn't know the manifest [`version_name`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version_name) key, so it shows a warning when loading the extension (#5053).
So define `version_name` only for the "generic" variant, along with a nearby cleanup of using regular property assignments instead of `Object.assign`.
> extension: Fix warning on Firefox

- Cargo.lock
- core/Cargo.toml
- core/src/backend/render.rs
- render/canvas/Cargo.toml
- render/canvas/src/lib.rs
- render/webgl/Cargo.toml
I'm not sure about the `data.resize(info.buffer_size(), 0);` line. It appears in the [docs](https://docs.rs/png/0.17.0/png/) like the right thing to do.
> chore: Bump png from 0.16.8 to 0.17.0

- web/packages/core/src/ruffle-player.ts
Fix #4980, while still keeping in mind the intention of #3967. Tested with the helicopter game (#1972). After a quick appearance of the menu, it is simple enough to click "Hide this menu", and then the game functions fine from then on.
Note: There is no way, currently, to re-enable the context menu after disabling it. The one way I could think of was appending a small div with an "Enable context menu" button above a corner of the ruffle player after disabling the context menu, but that would have potentially obscured controls or text or graphics. However, I still think this is better than hiding the context menu altogether on mobile devices, as it is useful (especially the full screen option) more often than not.
> web: Re-enable context menu on mobile, with option to disable

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/events.rs
- core/src/avm2/globals/flash/events/mouseevent.rs
I should note that there is very little here; the test file I was using crashed because of something likely unrelated to `MouseEvent`. Nevertheless, it was recommended that I submit this PR.
This PR adds `MouseEvent`'s class with a partial instance constructor as well as the constant property `MouseEvent.CLICK`. This PR has no tests currently as I am unable to build AS3 files.
I may be able to work on this more after the other bug gets fixed.
> avm2: Initial MouseEvent stubs

- desktop/src/main.rs
Fixes a panic that happens in debug mode when running ruffle on the latest version. These settings don't need to be case insensitive because they don't take a value
> desktop: Fix clap settings

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- Cargo.lock
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- web/Cargo.toml
- web/README.md
- web/common/Cargo.toml
As usual, also bump its helper crates (js-sys, wasm-bindgen-futures) to the latest versions, except for web-sys which is locked by wgpu to 0.3.50.
> web: Bump wasm-bindgen to 0.2.76

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/backend/video.rs
- core/src/backend/video/software.rs
- desktop/Cargo.toml
- desktop/src/main.rs
- web/Cargo.toml
This PR comprises a pure-Rust software H.263 decoder, a new backend type for interfacing with all future video decoders, and a very basic implementation of the `Video` display object type, only suitable for playing embedded video streams with no interactivity.
I'm marking this as a draft PR because people are already testing this branch, so I might as well announce it properly and get it into CI. The decoder is horribly badly optimized - even in release mode 480p video takes 8-16x longer to decode than ffmpeg. I ultimately want to write GPU shaders that do most of the per-pixel maths, but if I can get the CPU side to decode 480p video then I think this will be good.
I've explicitly designed the Video Backend to be able to support external video decoding APIs, mostly so that Desktop can …
> H.263 decoder + initial video support

- .github/workflows/test_rust.yml
In my understanding, this is needed for https://github.com/ruffle-rs/ruffle/pull/5106 to pass checks.
> dev: Make beta builds non-required

- .github/workflows/test_rust.yml
Didn't run this yet, so let's see how the PR gets built.
Reduces Rust build matrix size from 9 to 5 combinations.
> dev: Only test nightly rustc on ubuntu

- .github/workflows/test_rust.yml
By setting a dummy value for `$XDG_RUNTIME_DIR`.
It's not pretty, but the tests seem to also pass this way.
I was just annoyed by these little meaningless notes appearing on every PR check.
> Silence some warning notes on GitHub checks

- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
Only run workflows if particular files change. In particular, avoid running the rust workflow for web-only changes (and avoid running any workflow for documentation changes)
Run the rust workflow on changes to:
* the rust workflow
* Any .rs file
* Any Cargo.toml
Run the web workflow on changes to:
* Any .rs file or Cargo.toml (to pick up changes to ruffle_core)
* Anything in web/ except for documentation
> dev: run workflows only if certain file paths change

- core/src/avm1/activation.rs
- core/src/avm1/object/stage_object.rs
So instead of always returning `Ok` from all getters, simply return a `Value`.
> avm1: `DisplayGetter` cannot fail

- core/src/player.rs
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
The menu attribute functions the same as Stage.showMenu. This does not fix a recently discovered issue with Stage.showMenu (it is only supposed to hide built-in context menu items, but currently also hides custom context menu items). I did not touch show_menu's current functionality.
Tested with the menu on http://www.dnai.org/. The built-in context menu items are hidden on that page, but they are still visible on http://www.dnai.org/a/ which lacks a menu attribute. When testing, if using Chrome, make sure the extension is taking precedence by checking that the context menu says extension, which it seems to often not do in Chrome for reasons unknown to me.
> web: Support menu embed/object attribute (part of #4258)

- swf/src/read.rs
- swf/src/types.rs
- swf/src/write.rs
Re-number the `ClipEventFlag` enum members to match how they actually appear in a SWF. This allows much simpler read/write operations.
Also, gracefully handle malformed ClipActions that are only 1 or 0 bytes, as it seems that Flash accepts those too.
> swf: Take advantage of `ClipEventFlag` bit pattern

- core/src/display_object/container.rs
Part-way through the docstring, a comment is used instead of a triple slash.
> chore: fix docstring

- desktop/src/audio.rs
It was initialized on a separate thread since 6178dd9, as a workaround for Windows.
But now thanks to RustAudio/cpal#597, this is no longer needed, and cpal can be initialized on the same thread as before.
Plus small cleanups.
> desktop: Revert cpal initialization on a separate thread

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/events.rs
- core/src/avm2/globals/flash/events/keyboardevent.rs
- core/src/avm2/globals/flash/events/progressevent.rs
- remaining constants for MouseEvent
- KeyboardEvent constants
- ProgressEvent constants
This is mostly to let scripts progress a bit further and try to slightly reduce log spam in my test SWFs.
In practice it doesn't really help much, as a lot of `addEventListener` calls end with `TypeError: undefined is not an Object` anyway.
> avm2: Add more Event class stubs and constants

- .github/workflows/test_rust.yml
Resurrecting the earlier version of #5106, now that beta builds are no longer required.
> dev: Only test beta rust on ubuntu

- core/src/backend/navigator.rs
- desktop/src/navigator.rs
- web/packages/core/src/ruffle-player.ts
- web/src/navigator.rs
This fixes the issue @albertstill brought up when asking in #5026 about the base parameter. I've had several issues in the original pull request - mostly because I assumed a few things I shouldn't have and didn't check throughly enough.
1. The web impl fetch function now uses resolve_relative_url for relative urls so base url would be taken into account - this should be fine, right?
2. base can now accept directories as well as full URLs.
3. this.swfUrl is passed into stream_from instead of options.url - this is because options.url can be relative and we don't want ruffle to apply the base url to the swf url (this.swfUrl is the calculated full url of options.url).
4. resolve_relative_url changed to non mut self because why not?
> web: fix base parameter

- core/src/backend/audio.rs
It seems like Flash stores sound transform values in 30-bit unsigned integers:
* In general, negative values are equivalent to their absolute value.
* Specifically, 0x40000000, -0x40000000 and -0x80000000 are equivalent to zero.
Plus a small cleanup.
Fixes the "marching" sound in #5126, which roughly does the following:
```as
var s = new Sound();
s.attachSound("marching");
s.setPan(NaN);
s.start();
```
Previously this played a terrible noise in Ruffle, while it plays normally in Flash as if no transform is applied.
> audio: Store sound transform values in 30-bit integers

- core/src/avm1/function.rs
- core/src/avm1/globals/matrix.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/object.rs
- core/src/avm1/object/array_object.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/object/xml_idmap_object.rs
`get_local` is basically equivalent to `get_local_stored` that also handles virtual getters. So instead handle virtual getters in `search_prototype`. This allows to inline the `get_local_sub` helper methods into the implementations of `get_local_stored`.
The remaining usages of `get_local` were not exactly correct as they all should ignore virtual getters. This change solves this as well by using `get_local_stored` that ignores virtual getters.
> avm1: Remove `TObject::get_local` in favor of `TObject::get_local_stored`

- web/packages/core/src/config.ts
- web/packages/core/src/globals.d.ts
- web/packages/core/src/load-ruffle.ts
- web/packages/core/src/polyfills.ts
- web/packages/core/src/public-path.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/demo/webpack.config.js
- web/packages/extension/src/globals.d.ts
- web/packages/extension/src/player.ts
- web/packages/extension/src/ruffle.ts
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/js/.eslintrc.json
- web/packages/selfhosted/js/ruffle.js
- web/packages/selfhosted/webpack.config.js
In #4922 I tried to simplify the .wasm loading by using wasm-bindgen's built-in loader instead of relying on Webpack.
This allows to no longer declare .wasm files as resource assets in each `webpack.config.js`.
However it turned out to be problematic because it stopped respecting the `publicPath` config for the .wasm location, and instead assumed it is always in the same directory as the .js, which is not always the case. So the change was reverted in #4936.
This is a redo of the change, with fixes - the `publicPath` config is taken into account in `load-ruffle.ts`, which now sets `__webpack_public_path__` instead of each package (selfhosted, extension, demo).
However this removes the `publicPaths` config, but it should be fine as long as nobody uses it.
> web:  Reland "Simplify .wasm loading"

- core/src/player.rs
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/src/lib.rs
Good test for salign (recently mentioned in Discord):
https://deconcept.com/
If anyone knows a good test for scale, let me know. I tested it locally and it seems to work. According to #4601, quality does nothing currently in Ruffle, but I still added support for it since implementing all three of these attributes followed the exact same process so it made sense to do so.
To be added to [the Wiki](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#list-of-options):
> `salign` A string with a default value of "". This controls the position of the movie after scaling to fill the viewport and crops it as needed. The default alignment is centered. T, L, B, and R mean top, left, bottom, and right respectively. Can technically be any number of T's, L's, B's, and R's in any order, but the …
> web: Support salign, quality, & scale embed/object attributes (part of #4258)

- core/src/avm2/object.rs
After #4827 went in, I looked at the other places `#[allow(unused_mut)]` was used to see if the same fix could be applied, but it looks like the allowance and the mut can be removed entirely, so I've done that.
> dev: remove allow unused mut and corresponding mut

- web/packages/core/src/ruffle-player.ts
I realized from looking at other code that this was probably the case, tested it in Basilisk, and confirmed it to be true.
> web: Menu embed/object attribute true value is case-insensitive

- web/src/navigator.rs
Finally found example where base parameter is not ending in "/" thanks to @danielhjacobs.
https://aq.battleon.com/game/web?launchtype=medium
I think just adding the slash is the easiest way of bypassing the weird way url::parse works.
> web: support no trailing slash in base parameter

- web/packages/core/tsconfig.json
- web/packages/extension/tsconfig.json
We're already using way beyond this in Web API, so bump this to avoid some ugly async/await polyfills.
> chore: Bump TypeScript config to es2017

- core/src/avm1/activation.rs
- core/src/avm1/value.rs
* Change its return type to `Option<bool>`.
* Use Rust's `f64::partial_cmp` to compare two numbers, which should be more efficient.
> avm1: Simplify `Value::abstract_lt`

- core/src/avm2/activation.rs
I'd hope these never made it into any real code, but there's no harm in having them.
> avm2: implement bkpt, bkptline, timestamp as no-ops

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- web/Cargo.toml
- web/README.md
- web/common/Cargo.toml
As usual, also bump its helper crates (`js-sys`, `wasm-bindgen-futures`) to the latest versions, except for `web-sys` which is locked by wgpu to 0.3.50.
> web: Bump wasm-bindgen to 0.2.78

- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
Bring in the OR filtering from #5212, but have the required builds "run" (with a blank step).
> dev: have required builds 'run'

- core/src/avm1.rs
- core/src/avm1/activation.rs
`impl Into<Value<'gc>>` might create templatized functions leading to unnecessary code bloat.
So instead use just `Value<'gc>` parameters and add `.into()` in callers where needed.
> avm1: Avoid `impl Into<Value<'gc>>` parameter in `Avm1::push`

- core/src/avm1.rs
> avm1: Don't warn in case a method doesn't exist

- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
Unlike regular enums, const enums are completely removed during compilation, and as such are zero-cost in bundle size terms.
<s>However, it is not possible to query the possible values of a const enum, so revert the `autoplay` and `unmuteOverlay` validation logic, which I guess shouldn't make a big difference.
@Toad06, since you introduced that validation in #2299, maybe you can say why it's important?</s>
> web: Mark TypeScript enums as const

- core/macros/src/lib.rs
- core/src/matrix.rs
- core/src/transform.rs
- swf/src/avm1/read.rs
- swf/src/avm1/write.rs
- swf/src/avm2/read.rs
- swf/src/avm2/write.rs
- swf/src/read.rs
- swf/src/write.rs
Also note the `// XXX` comment about a potential typo / copy-paste error found by accident.
> chore: Fix nightly clippy lint: clippy::if_then_panic

- tests/tests/regression_tests.rs
This is a follow-up/continuation of https://github.com/ruffle-rs/ruffle/pull/5400.
I still can't get these warnings on my nightly clippy installation, so these instances were missed.
> Allow the if_then_panic clippy lint in one more place

- core/src/avm2.rs
- core/src/avm2/activation.rs
- core/src/avm2/value.rs
Because primitive types are still object values, it's necessary to coerce them into objects. This is accomplished via `PrimitiveObject`, which represents an immutable non-object value in contexts where object methods are needed. However, this means that the `Value` machinery can represent the same value by one of two ways, which necessitates kludges like `is_boxed_primitive`.
To avoid that, we're going to unbox primitives where feasible. The most obvious chokepoint is stack pushes, as this is the only way that user instructions can access values. So every call to `push` also checks for a primitive, and unboxes it at that point. This also means we don't need `is_boxed_primitive` anymore.
(For those wondering how user code would even *get* a `PrimitiveObject`, consider that those types have …
> avm2: Always unbox primitives on the stack.

- Cargo.lock
- Cargo.toml
- LICENSE.md
- core/Cargo.toml
- core/src/backend/video/software.rs
- desktop/Cargo.toml
- web/Cargo.toml
This is an alternative to https://github.com/ruffle-rs/ruffle/pull/3004.
In contrast to that:
- This is a pure Rust solution, with no reliance on `clang`, no iffy FFI, no funky business with adding a quasi-libc on web, and no CI troubles.
- It is much smaller in the WASM build: only an increase of about 90k, instead of 700k (or 240k even without libswscale).
This is more in line with what the H.263 decoder added, which was about 80k, although that was including the colorspace conversion code.
- Uses `h263-rs-yuv` for the colorspace conversion.
Most likely as a result of this, it is measurably slower, at least on web. See for example: https://z0r.de/2289
Merging https://github.com/ruffle-rs/h263-rs/pull/13 (then bumping the crate git ref) and https://github.com/ruffle-rs/ruffle/pull/5225 …
> Add VP6[A] video decoding support

- Cargo.lock
- core/Cargo.toml
To reap the benefits of PRs merged since the currently locked version:
- https://github.com/ruffle-rs/h263-rs/pull/4
- https://github.com/ruffle-rs/h263-rs/pull/7
- https://github.com/ruffle-rs/h263-rs/pull/10
- https://github.com/ruffle-rs/h263-rs/pull/12
- https://github.com/ruffle-rs/h263-rs/pull/13
> chore: Bump h263-rs and h263-rs-yuv git refs

- core/src/avm1/globals/text_field.rs
- core/src/avm1/globals/text_format.rs
- core/src/avm1/object.rs
- core/src/avm1/object/text_format_object.rs
- core/src/html/layout.rs
- core/src/html/text_format.rs
- swf/src/types.rs
`TextFormat` objects differ from regular objects in that
`TextField.setTextFormat` and `TextField.setNewTextFormat` accept
only the former, and ignore the latter.
Also, `TextFormat.prototype` has native accessors that coerce the
values on get/set.
> avm1: Introduce `TextFormatObject`

- core/src/html/text_format.rs
* Fix a typo introduced in #5611 - `texformatormat` -> `texformat`.
* Remove handling of "br" and "sbr" tags - Seems like Flash just ignores them.
> html: Small tweaks

- core/src/html/text_format.rs
This partially reverts commit 2119ce9821936e8309d22eafc492f3e9329b0c0a, only restoring "sbr" tags handling because Flash seems to ignore only "br" tags.
> html: Restore handling of "sbr" tags

- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/extension/assets/_locales/en/messages.json
- web/packages/extension/assets/_locales/es/messages.json
- web/packages/extension/assets/options.html
- web/packages/extension/assets/popup.html
- web/packages/extension/src/common.ts
- web/packages/extension/src/content.ts
- web/packages/extension/src/player.ts
- web/packages/extension/src/utils.ts
Self-hosted:
window.RufflePlayer.config = {
showSwfDownload: true,
...
}
Extension:
Added toggle "Show SWF download in context menu". Wording up to debate.
By default, there is no download button. However, a download button appears when showSwfDownload is set to true or extension toggle is on.
Since I added this to the popup extension toggles and not just the settings page (like log level and unsupported content warnings), i18n messages are perhaps more important, so I'd appreciate i18n help (https://github.com/ruffle-rs/ruffle/tree/master/web/packages/extension/assets/_locales; settings_show_swf_download) from international contributors.
Intended to supersede #1889.
> web: Give toggleable option to download swfs in extension/selfhosted config

- core/src/html/text_format.rs
* Restore handling of "br" tags - This fully reverts commit 2119ce9. Seems like Flash does handle "br" tags, but ignores them under some unknown circumstances (e.g. setting `htmlText` in AVM1). For now handle "br" tags unconditionally.
* Handle self-closing tags - "br" and "sbr" tags can appear in a self-closing form (i.e. `<br />`). Commit 3cab464026c02bd22ce5b7464604a786bd1c1ab5 forgot to handle this.
Fixes #5658.
> html: Fixes

- render/canvas/Cargo.toml
- render/canvas/src/lib.rs
Flash always uses the even-odd fill rule, whereas canvas defaults to
nonzero.
Specify the fill rule explicitly in both `swf_shape_to_canvas_commands`
and `swf_shape_to_svg`.
Fixes the text issue in #5616.
> canvas: Fill using the even-odd rule

- web/packages/extension/webpack.config.js
Fixes #5699.
It was hoped that adding this restriction would let the extension be reviewed sooner, but this didn't happen. Remove it so that people who want to use older versions can still use the extension.
> web: remove firefox extension version restriction

- core/src/avm2/class.rs
- core/src/avm2/names.rs
- core/src/avm2/object.rs
- core/src/avm2/object/class_object.rs
- core/src/avm2/object/script_object.rs
First commit simplifies `do_trait_lookup` to fit better the use cases it currently does. Validation was already handled by `validate_class()` too.
(Ideally, `do_trait_lookup` in its current form shouldn't exist, as non-initialization code should either pull instantiated traits (once _these_ are refactored :D ), or not need to do so at all (like `instance_method()` - by the time we call it, we should already have access to the unbound method trait in the caller))
Second simply merges two calls, to reduce number of hashmap lookups from in `get_property` "around 5-6" to "around 4-5" :) 
Third assumes that we should usually compare names before comparing namespaces.
> avm2: minor perf-oriented refactors/simplifications

- core/Cargo.toml
(AFAIK the only reason it's not a default is compatibility with older rustc.)
> build: Use the 'union' SmallVec feature for minor memory savings

- core/src/avm1/globals/bevel_filter.rs
- core/src/avm1/globals/blur_filter.rs
- core/src/avm1/globals/convolution_filter.rs
- core/src/avm1/globals/displacement_map_filter.rs
- core/src/avm1/globals/drop_shadow_filter.rs
- core/src/avm1/globals/glow_filter.rs
- core/src/avm1/globals/gradient_bevel_filter.rs
- core/src/avm1/globals/gradient_glow_filter.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm2/globals/flash/display/graphics.rs
- core/src/bounding_box.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
`clamp` is a bit more efficient, in both runtime and size terms.
> chore: Replace `min` + `max` with `clamp`

- core/src/backend/audio.rs
- core/src/display_object.rs
The fix in #5218 wasn't sufficient; 30-bit arithmetic should be used
along all the way when calculating an effective sound transform.
For example, a sound transform composited by volumes `-0x80000000` and
`25` should end up as effectively 0, whereas previously it would have
been calculated as `-0x80000000 * 25 / 100 = -0x20000000`, which is a
30-bit integer that hasn't been truncated.
Fixes #5655.
> audio: Calculate sound transform values using 30-bit integers

- core/src/avm2.rs
- core/src/avm2/activation.rs
- core/src/avm2/class.rs
- core/src/avm2/domain.rs
- core/src/avm2/events.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/display/bitmapdata.rs
- core/src/avm2/globals/object.rs
- core/src/avm2/globals/qname.rs
- core/src/avm2/globals/regexp.rs
- core/src/avm2/globals/vector.rs
- core/src/avm2/names.rs
- core/src/avm2/object.rs
- core/src/avm2/object/array_object.rs
- core/src/avm2/object/bytearray_object.rs
- core/src/avm2/object/class_object.rs
- core/src/avm2/object/dictionary_object.rs
- core/src/avm2/object/proxy_object.rs
- core/src/avm2/object/script_object.rs
- core/src/avm2/object/vector_object.rs
- core/src/avm2/property_map.rs
- core/src/avm2/scope.rs
- core/src/avm2/script.rs
- core/src/avm2/traits.rs
- core/src/display_object/movie_clip.rs
This PR aims to improve the performance of AVM2 property operations by restructuring `PropertyMap`. This type is no longer an alias for a hashmap keyed by `QName`, but instead stores values in a two-level structure of local name and `Namespace`. This is done under the assumption that local name conflicts across namespaces are rare. To further exploit this we also store conflicting names in a `SmallVec` with inline size 1. This saves on both allocations and hash lookups.
The structure of this map also makes it far easier to get the information that multiname resolution needs to work - namely, a list of all namespaces that a local name may appear in. `resolve_any` is gone, instead replaced with a method that returns *all* matching namespaces. This allows us to just check that list against …
> avm2: Multiname resolution performance improvements

- core/src/string/ops.rs
After merging the big string refactor, I noticed some performance regressions on AVM2; I was able to fix them as follows:
- Hash bytes as bytes. This allows us to use `hash.write` in the common case of ASCII-only strings. Wide strings *cannot* use this, as wide strings with ASCII-only contents need to hash identically to byte strings. Hence, we still need to iterate over the whole string, which is still slower in that case.
- Short-circuit string compare. In other words, when comparing for string equality, we first check for pointer equality. This was motivated by speeding up bucket scans in hashtable lookups.
> string: Hash and Eq performance improvements

- core/src/display_object/morph_shape.rs
The comparsion `start_change.move_to != end_change.move_to` doesn't make sense, because even if they are identical, the positions need to be updated.
Fix #2886.
> core: Fix a bug in `MorphShapeStatic::register_ratio`

- Cargo.lock
- desktop/Cargo.toml
This is a fixed version of https://github.com/ruffle-rs/ruffle/pull/5801.
> chore: Bump winit to 0.26.0, run `cargo update` to resolve conflicts

- core/src/backend/render.rs
- core/src/display_object/movie_clip.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
- Rename `register_bitmap_jpeg_3` to `register_bitmap_jpeg_3_or_4`.
- Unify `define_bits_jpeg_3` and `define_bits_jpeg_4`.
> core: Cleanup DefineBitsJpeg

- swf/src/types.rs
* Map 3 to `GradientSpread::Pad`
* Map 2 and 3 to `GradientInterpolation::Rgb`
Fix #1505.
> swf: Fix reserved gradient values handling

- core/src/string/ops.rs
- core/src/string/tests.rs
This fixes a bug in `WStr::offset_in`:
```rs
let source = WStr::from_units(b"abcdef");
let a = source[2..];
let b = source[..3];
// Fail: Some(2) != None
assert_eq!(a.offset_in(b), None);
```
> string: Correctly return None in `WStr::offset_in` for overlapping WStrs

- core/src/shape_utils.rs
- swf/src/read.rs
- swf/src/test_data.rs
- swf/src/types.rs
In some extreme cases, this can save up to 500-600MB (`Infiltrating the complex` on wasm).
This is the most bang-for-the-buck minimal change, but there are even better approaches possible (structure-of-arrays for another 100MB savings, or... optimize parsing and just pull ShapeRecords from the swf on the fly)
> swf: Box ShapeRecord::StyleChange variant

- core/src/avm1/globals/function.rs
- core/src/avm1/globals/object.rs
`Function.prototype` doesn't have its own `toString` method, but
rather inherts it from `Object.prototype`. So remove `Function.prototype.toString`
and move its logic to `Object.prototype.toString`.
> avm1: Remove `Function.prototype.toString`

- web/packages/core/src/ruffle-player.ts
Fixes #5698.
Ruffle does a React-style property check using the State to determine whether it's full screen or not, and using escape (or a manual `document.exitFullscreen()`) can cause that to go out of sync with reality, and the fix here is to listen to the `fullscreenchange` event and set Ruffle's fullscreen setting accordingly if it's exiting full screen.
> web: allow entering fullscreen after using escape to exit

- web/packages/demo/webpack.config.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
Webpack warns on assets larger than 250KB by default. Our WebAssembly module exceeds this limit by far (it's a few MBs).
> web: Suppress Webpack's size limit for .wasm files

- core/src/avm1/globals.rs
- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/globals/xml_node.rs
- core/src/display_object/edit_text.rs
- core/src/xml/tests.rs
- core/src/xml/tree.rs
This reduces the file size of the previous `xml.rs` file, and makes
the code a bit more organized.
> avm1: Split `XML` and `XMLNode` definitions

- render/canvas/Cargo.toml
- render/canvas/src/lib.rs
- web/packages/extension/manifest.json5
This is supposed to fix #5379, and make video playback in general much faster with the canvas backend.
By avoiding PNG and base64 compression and encoding (then decoding and decompression by the browser) every time a texture is updated.
I'm uncertain about the lazy caching of the `data_uri`, as the whole bitmap array needs to be `mut` for this;
perhaps simply computing it every time it is needed (which is, I have no idea how often) would be better.
> Make rendering raw bitmaps faster with the canvas backend

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash.rs
- core/src/avm2/globals/flash/display.rs
- core/src/avm2/globals/flash/display/interactiveobject.rs
- core/src/avm2/globals/flash/display/nativemenu.rs
- core/src/avm2/globals/flash/ui.rs
- core/src/avm2/globals/flash/ui/contextmenu.rs
- core/src/display_object/interactive.rs
Just enough for this to work (which is what a lot of content ends up doing):
```
mc.contextMenu = new ContextMenu();
mc.contextMenu.hideBuiltInItems();
```
> avm2: Add a basic ContextMenu stub

- web/packages/extension/src/player.ts
Fixes http://iqtest.dk/main.swf (after clicking the second Start button, which loads another swf), probably others. Update to #5144, which I believe worked prior to #5290.
> extension: Fix base for direct swf links

- core/src/avm1/globals/key.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/backend/ui.rs
- core/src/context.rs
- core/src/display_object/edit_text.rs
- core/src/events.rs
- core/src/player.rs
- desktop/src/main.rs
- desktop/src/ui.rs
- web/src/lib.rs
- web/src/ui.rs
`InputManager` encapsulates the common logic that previously the `UiBackend`s used to implement.
Pulled out from #4644.
> core: Introduce `InputManager`

- core/src/avm2/activation.rs
Actually, the reality is much more complex: (assuming 32-bit FP build):
```
var num_val : uint = 0x0FFFFFFF;
trace(getQualifiedClassName(num_val)); // int
var num_val : uint = 0x10000000;
trace(getQualifiedClassName(num_val)); // Number
```
(Not to mention, FP does "live" conversions, like `trace(getQualifiedClassName(1.5 + 1.5)); // int`)
(_Not to mention_, well... `uint` as a primitive doesn't actually exist in AVM2; all integral values are `int`s, and `uint` type exists only for typechecking purposes)
```
trace(getQualifiedClassName(uint.MIN_VALUE)); // int
trace(getQualifiedClassName(uint.MAX_VALUE)); // Number
trace(getQualifiedClassName(new uint())); // int
trace(getQualifiedClassName(new int())); // int
```
So this PR doesn't really fix much; just changes the `op_convert_u/i` …
> avm2: Set correct(-ish) value type in op_convert_u/i

- core/src/avm1/globals/array.rs
- core/src/avm1/globals/as_broadcaster.rs
- core/src/avm1/object/array_object.rs
It was always passed as `Some`, so there's no reason for allowing
`None`.
> avm1: Make `ArrayObject` proto non-`Option`

- render/canvas/src/lib.rs
Values outside the range of 0 and 1 are ignored in canvas, unlike Flash that clamps them.
Fixes #5593.
> canvas: Clamp alpha values

- Cargo.lock
- core/Cargo.toml
To make use of the recently merged https://github.com/ruffle-rs/h263-rs/pull/15.
> chore: Bump h263-rs git reference

- core/src/avm1/globals/xml.rs
- core/src/avm1/object.rs
- core/src/avm1/object/xml_object.rs
Previously Ruffle's AVM1 runtime incorrectly permitted calling `XML` functions on `XMLNode` objects. For example:
```as
var xml = new XML("<a><b></b></a>");
trace(XML.prototype.createElement.call(xml.firstChild, "aaa")); // traces "undefined" in Flash, but "<aaa />" in Ruffle before this commit.
```
Disallow this by re-introducing `XmlObject` and using it to represent `XML` objects (rather than `XmlNodeObject` that represents also `XMLNode` object), and check for it in all `XML` builtins.
> xml: Cleanup (part 2)

- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/text.rs
- core/src/font.rs
- core/src/player.rs
Motivating examples:
https://www.newgrounds.com/portal/view/561860?emulate=flash
https://frepy.eu/games/Frepy15ee/
And possibly some other big SWFs.
These happen to have full fonts with (tens of) thousands of characters, that are all tessellated and loaded to GPU (on wgpu/webgl) at launch time.
This patch makes them register lazily, which can save up to 1-2GB of memory and speed up initial load by 2-3x. This can also reduce runtime GC pauses on Chrome (which tbh I'd consider a Chrome bug...).
This also makes the "glyph as shape" load lazily, as it's only used for collision detection.
Technically this can worst-case slightly increase memory use; previously we only long-term stored the "glyph as shape" and the GPU buffer; now, assuming every lazy load gets reached, we will store the …
> core: register non-ascii fonts lazily

- core/src/avm1/globals/xml.rs
- core/src/xml/document.rs
- core/src/xml/tests.rs
- core/src/xml/tree.rs
This is a pure non-functional refactor that moves `XmlNode::replace_with_str` to `XmlDocument`, as it only makes sense to call this method on document roots. Besides that, it enables some further simplification (see 2nd commit).
> xml: Cleanup (part 3)

- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/globals/xml_node.rs
- core/src/xml/document.rs
- core/src/xml/error.rs
- core/src/xml/tests.rs
- core/src/xml/tree.rs
This PR removes the non-AS2-compatible XML node types (comments and `DOCTYPE` declarations), because:
1. Comments are not included in the string representation, nor visible through the DOM methods, which effectively means they doesn't exist. On the other hand, the `DOCTYPE` declaration is not visible through DOM methods, but it should appear in the string representation. However, it doesn't both before and after this PR.
2. Due to significant differences between the XML implementations of AVM1 and AVM2, it makes more sense to have two separate implementations (as Flash did). Therefore, there's no reason for storing information that will never be observable to AVM1.
> xml: Cleanup (part 5)

- .github/ISSUE_TEMPLATE/error_report.md
- web/packages/core/src/ruffle-player.ts
The `error-report` label was not being added to error reports submitted by panics in the web player, despite the `labels` query parameter in the URL. Users do not have triage/write access to the repo, which is required by GitHub to add a label to an issue, so the label was never added. Note that the issue creation page may actually lie and display the `error-report` label, but the label will disappear once the issue is submitted.
Add an issue template for error reports with the `error-report` label. This template is now added to the issue URL, which automatically adds the tag regardless of the user's access level.
> chore: Add error-report issue template

- core/src/avm1/globals/xml.rs
- core/src/loader.rs
Since they are identical (they both load the URL as a string, then
fire the `onHTTPStatus` and `onData` events). In fact, AVM1's
`XML.prototype.load` and `LoadVars.prototype.load` functions are
both defined as `ASnative(301, 0)`, so they invoke the same native
code under the hood.
> core: Unify `Loader::Xml` into `Loader::LoadVars`

- core/src/backend/audio.rs
- core/src/backend/audio/decoders.rs
- core/src/backend/audio/mixer.rs
- core/src/context.rs
- core/src/display_object/movie_clip.rs
- core/src/player.rs
- web/src/audio.rs
This is a proof-of-concept first pass at syncing animation and audio playback when an embedded audio stream is playing. These streams are formed by `SoundStreamBlock` SWF tags and cause the Flash Player to skip frames in an attempt to keep the audio and video in sync.
* Get the current time of the primary audio stream from the `AudioBackend`.
* We consider the first "stream" sound to be the primary stream; typically only one stream is playing anyway.
* Get the animation time of the clip that owns the audio stream.
* Animation time is `(clip.current_frame() - stream.start_frame) / clip.movie().frame_rate`.
* Compare audio time to animation time. If they differ by some threshold, adjust the playback speed to compensate.
* Speed up or slow down the player by adding an offset to …
> audio: Sync animation with embedded audio streams

- core/src/avm2/object.rs
- core/src/avm2/object/array_object.rs
- core/src/avm2/object/bitmapdata_object.rs
- core/src/avm2/object/bytearray_object.rs
- core/src/avm2/object/class_object.rs
- core/src/avm2/object/date_object.rs
- core/src/avm2/object/dictionary_object.rs
- core/src/avm2/object/dispatch_object.rs
- core/src/avm2/object/domain_object.rs
- core/src/avm2/object/event_object.rs
- core/src/avm2/object/function_object.rs
- core/src/avm2/object/loaderinfo_object.rs
- core/src/avm2/object/namespace_object.rs
- core/src/avm2/object/primitive_object.rs
- core/src/avm2/object/proxy_object.rs
- core/src/avm2/object/qname_object.rs
- core/src/avm2/object/regexp_object.rs
- core/src/avm2/object/script_object.rs
- core/src/avm2/object/sound_object.rs
- core/src/avm2/object/soundchannel_object.rs
- core/src/avm2/object/stage_object.rs
- core/src/avm2/object/textformat_object.rs
- core/src/avm2/object/vector_object.rs
- core/src/avm2/object/xml_object.rs
After https://github.com/ruffle-rs/ruffle/pull/5791 , prototypes are always ScriptObjects* , so only its `derive()` was ever called. This means that `new MyOldStyleObject()` will always produce a ScriptObject.
For reviewers: only real change is in `function_object.rs` :)
(* there's an exception we don't have implemented but also don't test for: Function.prototype is itself a function. I'm still keeping this out of scope)
> avm2: Remove Object::derive() machinery for AS3 prototypes

- .cargo/config.toml
- .github/workflows/release_nightly.yml
- web/README.md
- web/package.json
- web/packages/core/package.json
- web/packages/core/src/load-ruffle.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/core/tsconfig.json
- web/packages/extension/tsconfig.json
- web/src/lib.rs
This includes, "unblocks", and extends https://github.com/ruffle-rs/ruffle/pull/5225.
Also adds dynamic fallback to an additional, non-extension-enabled WebAssembly module, mostly for compatibility with ~poor~ Safari.
~The `simd128` extension is not yet directly utilized by us (it possibly is by some dependencies), but I have a few ideas where to use it, improving video decoding performance significantly.~
**EDIT**: The `simd128` feature should help a lot with the color conversion of both H.263 and VP6 videos since https://github.com/ruffle-rs/h263-rs/pull/15 got merged. The IDCT in the H.263 decoder could also potentially benefit from it with some tweaking, but I haven't found/made any speedups there yet.
This also roughly (but not quite) doubles both the time it takes to build the web …
> web: Build two WASM modules, with/without extensions, load the appropriate one

- web/packages/extension/manifest.json5
- web/packages/extension/webpack.config.js
In Chrome, `unsafe-eval` was needed in the extension Content Security Policy for Wasm compilation. Other browsers seemed to work regardless of this setting.
Unfortunately, this CSP setting causes the extension to get flagged in the Mozilla Add-On Marketplace, which discourages the use of `unsafe-eval`. Chrome specifically has a `wasm-eval` for allowing Wasm in extensions, so let's switch to that instead.
The CSP spec has added a `wasm-unsafe-eval` setting, and Chrome will deprecate `wasm-eval` eventually; we may need this for all browsers as they start to support it.
https://github.com/w3c/webappsec-csp/pull/293
> extension: Change unsafe-eval to wasm-eval in CSP

- .github/workflows/release_nightly.yml
- web/packages/core/package.json
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/npm-package.json5
- web/packages/selfhosted/package.json
- web/packages/selfhosted/webpack.config.js
Publish nightly releases as part of the CI, so Ruffle can be easily integrated into a website using a CDN (such as jsDelivr). It would also be easier for websites to keep up-to-date, as NPM auto-updates the `latest` tag to refer to the latest release.
A dedicated `package.json` is used for the published NPM package, because `ruffle-selfhosted` depends on the private 
`ruffle-core` package, which shouldn't be published.
Also, the `version` field must monotonically increase. So Webpack auto-fills it to be `0.1.0-nightly.YYYY.MM.DD`. This format satisfies a couple of needs:
* Newer nightly releases should take precedence over older ones.
* Stable releases (e.g. `1.0.0`) should take precedence over nightly ones.
* `secrets.NPM_TOKEN` needs to be added. @Herschel I think only you have access …
> web: Publish npm package

- Cargo.toml
- web/packages/core/package.json
A bit of an improvement over #5834.
This avoids always nuking the build cache (twice) when running `npm run build:dual-wasm`.
While `wasm-opt` is still doing the work twice, that is a lot faster and less "harmful" - not cache-polluting.
A somewhat related note: I _think_ `\\\"$CARGO_FEATURES\\\"` causes the `--features`  argument to be passed as literally `$CARGO_FEATURES` to `cargo`. Does it then substitute the envvar internally?
EDIT: FWIW setting `CARGO_FEATURES=whatever` for `npm run ...` does work, at least on Linux, so I guess it's okay.
> web: Add custom profiles to separate the build cache for the two wasm modules

- .github/workflows/release_nightly.yml
Scoped packages are private by default and require a paid plan for orgs. Switch to public.
> chore: Publish npm package publicly

- core/src/display_object/movie_clip.rs
- core/src/loader.rs
- core/src/player.rs
`onLoadInit` is queued after all `DoAction`s of the loaded clips.
That is, if clip1, clip2, clip3 are loaded in the same frame
(in this order), then actions will be executed as follows:
* `DoAction` of clip3
* `DoAction` of clip2
* `DoAction` of clip1
* `onLoadInit` of clip3
* `onLoadInit` of clip2
* `onLoadInit` of clip1
Previously, those were incorrectly executed as follows:
* `DoAction` of clip3
* `onLoadInit` of clip3
* `DoAction` of clip2
* `onLoadInit` of clip2
* `DoAction` of clip1
* `onLoadInit` of clip1
Discovered while working on #6004. Will add tests for this PR in #6004.
> avm1: Fix `onLoadInit` event order

- .github/workflows/release_nightly.yml
Otherwise `release.zip` is included in the package files.
> ci: Publish npm package before packaging selfhosted

- web/packages/core/src/public-path.ts
CDNs allow omitting the filename:
* https://unpkg.com/@ruffle-rs/ruffle
* https://cdn.jsdelivr.net/npm/@ruffle-rs/ruffle
That caused `currentScriptURL` to be determined incorrectly:
```js
new URL(".", "https://unpkg.com/@ruffle-rs/ruffle").href
// "https://unpkg.com/@ruffle-rs/"
```
If the filename is omitted, append a slash to prevent the last
component from being dropped:
```js
new URL(".", "https://unpkg.com/@ruffle-rs/ruffle/").href
// "https://unpkg.com/@ruffle-rs/ruffle/"
```
> web: Fix `publicPath` when loaded from a CDN

- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/avm2/globals/flash/display/loaderinfo.rs
Chalk another one up for the AS3 documentation lying. Or me misinterpreting it.
Any movie clip that isn't the root of a movie will give you the root clip's loader info, rather than throwing an error.
In a similar vein, the Stage's loader info actually has a few extra properties that can be read from it that we were also assuming couldn't. `url`, `bytes`, and `parameters` all work and return the same data that the root clip does.
> AVM2: `loaderInfo` can be read from child movie clips, `stage.loaderInfo` allows access to `url`, `bytes`, and `parameters`

- CONTRIBUTING.md
Fixes the path to tests folder in `CONTRIBUTING.md` to keep consistency with the actual folder structure of the project.
> doc: Fix path to tests folder

- Cargo.lock
- render/wgpu/Cargo.toml
- render/wgpu/shaders/common.wgsl
- render/wgpu/shaders/gradient.wgsl
- render/wgpu/src/bitmaps.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/pipelines.rs
Bump to wgpu 0.12. Allows wgpu backend to work again on Firefox Nightly and Chrome Canary.
* ``[[block]]`` removed from shaders (removed from WGSL spec).
* Update `wgpu::BindingType::Sampler` and `wgpu::RenderPipelineDescriptor` to match latest wgpu API.
* Add padding to `GradientUniforms` (I tried `#[repr(align(16))]`, but bytemuck didn't like this)
> chore: Bump to wgpu 0.12

- .github/workflows/release_nightly.yml
* Add support for publishing Chrome Extension.
* Secrets are set on Ruffle org for Chrome and Mozilla extension publishing.
* Let's try doing this nightly; we may have to manually switch this off or switch to weekly if we get flagged for manual review (particularly on Mozilla).
TODO future PRs:
I'd like to organize things a little better by possibly splitting into more workflows; for example, the web nightly build can be its own workflow, and possibly the extension builds, too. Can use [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) and [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) to re-use the common parts.
> ci: Publish Chrome and Firefox extensions nightly

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
Switch to macOS 11 runner and remove hack for compiling for Apple Silicon on macOS 10 runners.
> ci: Remove macOS 10 hack

- core/src/avm1/activation.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/avm2/globals/flash/display/simplebutton.rs
- core/src/display_object.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/avm2_button.rs
- core/src/display_object/bitmap.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/stage.rs
- core/src/display_object/video.rs
- core/src/loader.rs
- core/src/player.rs
`display_object` was always equivalent to `self`, there's no need to pass both.
> core: Remove unnecessary parameter from `post_instantiation`

- .github/workflows/release_nightly.yml
Supply FIREFOX_EXTENSION_ID var to the web build step to ensure this gets correctly populated in the manifest.json.
> ci: Fix publishing of Firefox extension

- core/src/events.rs
Fixes #5577 and #5958, these files stop triggering the actions of invisible buttons.
I have to admit that I'm not sure about this fix, it was made based on the following lines that already use `intersects`:
https://github.com/ruffle-rs/ruffle/blob/d9bedffb9f9a00ea7ad38db0edca527952ed5d33/core/src/display_object/movie_clip.rs#L1700-L1708
> core: Fix detection of button events

- .github/workflows/release_nightly.yml
Move the `if` condition that tests for the Ruffle official repository
to the job-level, so all steps of that job are skipped, rather than
only the publish step itself. This should have a very little effect,
but I just randomly noticed it.
> ci: Skip `publish-aur-package` job on forks

- web/packages/extension/src/background.ts
When the user clicks the "Open in a new tab" button, the extension's internal `player.html` page opens, with a URL parameter `?url=[the SWF URL]`. Right now, this URL parameter is not properly encoded. This causes a problem when we get to https://github.com/ruffle-rs/ruffle/blob/master/web/packages/extension/src/player.ts#L14:
> `const swfUrl = url.searchParams.get("url");` 
Because the value of the "url" parameter was not properly encoded, any `&` character in the SWF URL would be interpreted as the start of a *new* parameter, instead of being part of the actual SWF URL. So anything after the first `&` symbol in the SWF URL would be chopped off.
On Itch.io Flash pages such as https://rarykos.itch.io/hug-me-im-cold, the SWF URL contains several important parameters - if they are not …
> extension: URL-encode the SWF URL for the player page

- desktop/src/main.rs
The "exit fullscreen" shortcut was swallowing Escape presses on desktop. Allow the Escape press to reach the content.
Long term we'll probably want a setting that allows for enabling/disabling Ruffle's shortcuts, because content may have its own escape/alt+enter/etc. behavior.
> desktop: Don't swallow Escape key (fix #6135)

- Cargo.lock
- core/Cargo.toml
- core/src/matrix.rs
- tests/tests/regression_tests.rs
Just a bit of cleanup, as https://github.com/brendanzab/approx/pull/72 recently got merged, and a fixed version released.
> chore: Bump approx to 0.5.1, remove clippy lint suppressions

- web/packages/selfhosted/README.md
A nearly identical change to #4063, this time for the sake of links working on https://www.npmjs.com/package/@ruffle-rs/ruffle.
> selfhosted: Use absolute URLs for links in README

- .github/workflows/test_rust.yml
`runner.os` is a little more descriptive. But unfortunately, it cannot be used in `job.name`.
> ci: Use `runner.os` over `matrix.os`

- .cargo/config.toml
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/value.rs
- core/src/backend/audio/decoders/mp3.rs
- core/src/display_object/stage.rs
- core/src/lib.rs
- core/src/matrix.rs
- exporter/src/main.rs
- swf/src/types/matrix.rs
- web/src/lib.rs
Currently it is not directly possible to configure lints for the entire workspace via TOML, which forced us to repeat `#![allow]` blocks in each crate.
embark pointed out this workaround to configure lints at the workspace level via RUSTFLAGS:
https://github.com/EmbarkStudios/rust-ecosystem/issues/22#issuecomment-947011395
Remove the common `#![allow]` blocks and switch to this method for global lint config. I was also able to remove a few `allows` that are no longer problematic.
Temporarily allow `needless_borrow` lint to fix CI. This lint is buggy pending this fix:
https://github.com/rust-lang/rust-clippy/pull/8355
> chore: Add .cargo/config.toml for workspace-level lint config

- .github/workflows/test_web.yml
Test is currently broken because of this issue: actions/setup-node#411
> ci: Temporarily disable Windows Node 14 test

- core/src/drawing.rs
- core/src/shape_utils.rs
Ruffle didn't honor the proper rendering order of fills and strokes, causing issues such as #6129. Ruffle was storing the paths associated with each stroke style in a map, but this causes the final draw order to be arbitrary. Instead, for each layer, Flash draws the fills and strokes in order of their style ID -- all fills are drawn first, then strokes. This doesn't necessarily match the order of shape record commands in the data.
This is mainly noticeable with large overlapping strokes of different colors. It affects fills as well, although Flash will almost always export art with non-overlapping fills on each layer.
* In `ShapeConverter`, change the `FnvHashMap` storing the style's paths to a `Vec` and iterate in order.
* In `Drawing`, merge the separate list of fills and lines into a …
> core: Fix incorrect fill and stroke rendering order (fix #6129)

- core/src/display_object/avm1_button.rs
- core/src/display_object/movie_clip.rs
Fixes #6169 and [this sample](https://github.com/ruffle-rs/ruffle/files/7966764/sample.zip).
> avm1: Fire `onReleaseOutside` event even when the button is invisible

- .github/workflows/test_web.yml
Upgrading to npm 8.4 on Windows is currently broken: https://github.com/npm/cli/issues/4341
This was avoided by disabling tests on Windows Node 14 in #6167.
Re-enable them by staying on npm 8.3 instead.
> ci: Temporarily avoid npm 8.4

- core/src/display_object/avm1_button.rs
- core/src/display_object/avm2_button.rs
- core/src/display_object/movie_clip.rs
- core/src/player.rs
> avm1: Change the cursor to arrow when the `enabled` property is set to false on a button

- core/src/avm1/globals.rs
`random` only compiles to `Action::RandomNumber`.
```
trace(typeof _global.random); // "undefined" in Flash, "function" in Ruffle
trace(_global.random(33)); // "undefined", an integer in Ruffle
```
> avm1: Remove `random` from globals

- core/src/avm1/globals/array.rs
I'm not absolutely sure why it solves the problem.
Also call the sort function with a primitive `this`, which is now possible thanks to #6108.
> avm1: Fix nightly build error

- core/src/avm2/activation.rs
- swf/src/avm2/read.rs
There is an option in reading the op code of the swf lib but the value can never be None. So I removed the option on the read_op method.
> avm2: Fix invalid option

- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/globals/xml_node.rs
- core/src/xml/tree.rs
* Don't use `quick_xml::Writer` for formatting the XML, being much
more simple.
* Return `WString` instead of `String`, reducing `to_utf8_lossy()`
calls except when the string needs to be escaped (attribute values
and text contents).
> xml: Refactor `XmlNode::into_string`

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
Per https://github.com/actions/virtual-environments/issues/4856,
`windows-latest` will default to `windows-2022` soon (not later than
March, 6). Since it seems like we still run on `windows-2019`, force the
migration by specifying `windows-2022` explicitly.
Since https://github.com/actions/virtual-environments/pull/5050 is
merged, this should fix the failing Web tests on mismatched Chrome and
chromedriver versions.
TODO: Once `windows-latest` defaults to `windows-2022` (again, March, 6),
change back to `windows-latest`.
> ci: Migrate to Windows Server 2022

- core/src/avm1/globals/xml.rs
- core/src/avm1/object/xml_object.rs
- core/src/avm1/value.rs
The only use of `last_parse_error` was in the `XML.prototype.status`
property, where it was converted into a number. Avoid storing it by
storing just the number.
Split from #6315 to ease code review.
> avm1: Store `status` in `XmlObject`, instead of `ParseError`

- core/src/xml/error.rs
- core/src/xml/tree.rs
Instead of returning a `Result` which is anyway always handled with
a `log::warn!()`, simply `log::warn!()` in place of errors.
Split from https://github.com/ruffle-rs/ruffle/pull/6315 to ease code review.
> xml: Silently fail in `set_{prev,next}_sibling`

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
- Cargo.lock
- LICENSE.md
- desktop/Cargo.toml
- desktop/src/main.rs
- desktop/src/ui.rs
- web/LICENSE.md
Extract just the `tinyfiledialogs` -> `rfd` change from #5086.
Fixes #6256.
> desktop: swap out tinyfiledialogs for rfd

- Cargo.lock
`Cargo.lock` seems to got broken by #6265.
Fix it using `cargo generate-lockfile`.
> chore: Re-generate `Cargo.lock`

- Cargo.lock
- core/Cargo.toml
- core/src/avm1/globals/shared_object.rs
- core/src/avm2/globals/json.rs
- core/src/config.rs
- core/src/context_menu.rs
- web/Cargo.toml
The `json` crate seems unmaintained, and recently also causes compile errors with stable Rust 1.59.0. On the other hand, `serde_json` is very maintained and more popular.
There were 2 usages of `json`:
1. AVM1 used it for a legacy `SharedObject` format. As it turns out to never been working, it's now removed.
2. AVM2 used it for its `JSON` implementation. Here `serde_json` is used instead.
However, from some reason a cyclic package dependency has introduced by this change. For now use a workaround from: https://github.com/tkaitchuck/aHash/issues/95#issuecomment-903560879 (I didn't find any better solution)
> core: Replace `json` with `serde_json`

- core/src/avm1/globals/xml.rs
- core/src/avm1/globals/xml_node.rs
- core/src/xml/error.rs
- core/src/xml/tree.rs
This brings us closer towards removing `Error` entirely (#6315):
* `Error::TextNodeCantHaveChildren` was in fact unreachable.
* `Error::CantRemoveNonChild` is avoided by turning `remove_child` into `remove_node`, such that there's no way of trying to remove a non-child of a node.
> xml: Remove 2 more `Error` enum members

- web/packages/core/src/ruffle-player.ts
This is a small PR, which adds a little property called isPlaying that is true if the movie is playing, and is false if the movie is paused. I wasn't able to find a thing like this in the Ruffle API already, so I added it, since needed a feature like this for a website I am working on, and I thought I'd submit it here just incase it is helpful.
By the way, I am quite new to this whole project/repo, so if I did anything wrong here please let me know. Thanks!
> web: Add `isPlaying` property to rufflePlayer

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/swf-file-name.ts
- web/packages/core/test/swf-file-name.ts
Any query string parameters in the SWF URL would be inserted into the `download` parameter as a filename suggestion, which would convert the actual filename in strange ways (e.g. `574241_DiamondNGSP.swf?123` -> `574241_DiamondNGSP.swf 123.swf123`).
This change ignores any query string parameters, avoiding that problem.
> fix: don't include query parameters in downloaded SWF name

- core/src/avm1/globals/xml_node.rs
- core/src/avm1/object/xml_object.rs
- core/src/xml/error.rs
- core/src/xml/tree.rs
Remove all remaining `Error` enum members, leaving only `Error::InvalidXml`. This allows us to replace `Error` with `quick_xml::Error`, as shown in #6315.
> xml: Remove remaining `Error` enum members

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
Revert #6297. This can wait until migration is finished (March 6 per https://github.com/actions/virtual-environments/issues/4856), but since https://github.com/actions/virtual-environments/pull/5129 was merged this can be merged immediately since that updated Windows-2019 to Chrome 98. Required check needs a change once again (from either @kmeisthax or @Herschel).
> ci: Use windows-latest again

- core/src/avm2/globals/date.rs
We now declare these methods in the 'http://adobe.com/AS3/2006/builtin'
namespace. This corresponds to the 'AS3' namespace modifier shown on the
docs page: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Date.html
Previously, we would fail to lookup these methods, since the namespace
used by the SWF would not match the namespace defined by Ruffle.
> Declare AVM2 'Date' class methods in the AS3 namespace

- core/src/avm2/object/script_object.rs
This will make these errors easier to debug.
> Display `Muliname` when trying to lookup a non-public property

- core/src/avm2/globals/flash/display/loaderinfo.rs
The actual property name is `loaderURL` - it looks like
a typo was made when this was originally defined in Ruffle.
> Change property definition from `loaderUrl` to `loaderURL`

- web/packages/core/src/ruffle-player.ts
Related to #6395.
This PR adds a specific error message that pops up when the user has the "Enhance your security on the web" setting enabled on Microsoft Edge, which disables `.WASM` files from loading. 
Screenshot of the error message:
The "More Information" link goes to [here](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#edge-webassembly-error).
> web: Add specific error message for disabled WASM on Microsoft Edge

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/display.rs
- core/src/avm2/globals/flash/display/loader.rs
- core/src/avm2/globals/flash/net.rs
- core/src/avm2/globals/flash/net/url_request.rs
- core/src/avm2/globals/flash/ui.rs
- core/src/avm2/globals/flash/ui/keyboard.rs
- core/src/avm2/globals/flash/utils.rs
- core/src/avm2/globals/flash/utils/timer.rs
This PR adds the following class stubs:
* 'flash.display.Loader'
* 'flash.net.URLRequest'
* 'flash.ui.Keyboard'
* 'flash.utils.Timer'
These are needed for 'This is the Only Level TOO' (though we'll need
actual implementations to get this game past the loading screen).
> Add more AVM2 'flash.' class stubs

- core/src/avm2/array.rs
- core/src/backend/audio/decoders/mp3.rs
- core/src/color_transform.rs
- core/src/matrix.rs
- core/src/string/buf.rs
- render/canvas/src/lib.rs
- render/wgpu/src/uniform_buffer.rs
This commit does the same as 36353df7f741feadeebc89f3361c6adb980bda09,
cleaning up any leftovers and new code added since.
> chore: Stop using traits available in prelude

- render/webgl/src/lib.rs
If `gl.drawingBufferWidth` returns `0`, then a `clamp` in
`WebGlRenderBackend::set_viewport_dimensions` hits an assertion that
`1 <= self.gl.drawing_buffer_width()` is `false`. I was able to
reproduce this on Chrome by creating many dummy WebGL contexts until
Ruffle's one is lost, and then resize the Ruffle player, but this may
happen in other cases as well.
Fix this by allowing `renderbuffer_width` and `renderbuffer_height`
to be `0`. From basic testing, this seems harmless.
Should fix all the following issues: https://github.com/ruffle-rs/ruffle/issues?q=is%3Aissue+is%3Aopen+set_viewport_dimensions
> webgl: Avoid clamp assertion

- core/src/avm1/activation.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/avm2/globals/flash/utils.rs
- core/src/backend/navigator.rs
- core/src/context.rs
- core/src/player.rs
- desktop/src/navigator.rs
- web/Cargo.toml
- web/src/navigator.rs
`core` already depends on the `instant` crate which abstracts
`std::instant::Instant` and polyfills it on Web. Use it to replace
`NavigatorBackend::time_since_launch` in order to make `NavigatorBackend`
a little smaller and more simple.
> core: Remove `NavigatorBackend::time_since_launch`

- .github/workflows/release_nightly.yml
Guess who forgot to check if the packager task actually clones the Git repo I'm referencing?
> Fix broken macOS nightly build

- .github/workflows/release_nightly.yml
Noticed I forgot this step too when testing some codesigning stuff. I thought `actool` creates the target directory but it doesn't.
> chore: App bundle also needs a Resources directory.

- web/packages/core/src/ruffle-imports.ts
`AudioContext.getOutputTimestamp` returns incorrect values in
Safari 15.1+, and this would cause movies with 'stream' sounds to
soft-lock because the calculated audio position would barely
progress.
See:
https://developer.apple.com/forums/thread/696356
Change the output timestamp calculation to use
`AudioContext.currentTime` instead.
> web: Fix hangs on Safari by avoiding getOutputTimestamp

- desktop/Cargo.toml
This feature allows `RUST_LOG` to include a regex filter. While
it's nice to have, it's not worth over 440KB added to the release
binary. `grep` / `findstr` are great and even better alternatives.
> desktop: Disable `env_logger`'s `regex` feature

- core/src/avm2/class.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/display/framelabel.rs
- core/src/avm2/globals/flash/display/scene.rs
In both `FrameLabel` and `Scene`, we define multiple
'public property / private slot' pairs.
The public property has a getter which delegates to the private
property. There is no setter for the property, ensuring that
the private slot can only be modified from within Ruffle itself.
This PR adds a macro `define_indirect_properties` to abstract over
this pattern. Currently, it only supports the read-only property
pattern - however, it could be extended in the future to generate
a setter that invokes a caller-provided callback function.
This needs to be a macro (rather than a method) so that we can
generate a function with the property name hard-coded into it.
Using a closure that references an upvar will not work, since
`Method::from_builtin` requires a function pointer.
> Add `define_indirect_properties` helper macro for property/slot pairs

- core/src/display_object/edit_text.rs
Small fix for #5648, assuming it's correct.
> avm1: Apply autosize to a new `EditText` from an SWF `DefineEditText` tag

- web/package.json
- web/packages/demo/package.json
- web/packages/demo/webpack.config.js
*  Copy `swfs.json` to `dist` directory - Currently it doesn't work at all. I have no idea if it got broken at some point.
* Rename `serve` command to `start` - Allows running `npm start` inside the `demo` directory. `npm run demo` in the `web` directory should still work as usual.
> demo: Small improvements

- core/src/string/buf.rs
WString's Drop impl didn't actually drop anything.
> wstr: fix memory leak

- Cargo.lock
- core/Cargo.toml
- core/src/backend/navigator.rs
- scanner/src/execute.rs
- tests/tests/regression_tests.rs
Make it a thin abstraction layer over either the `futures` or `wasm-bindgen-futures`
crates, as already done in `render/wgpu/src/uniform_buffer.rs`,
instead of a hand-made single-thread executor.
Ideally this would also be usable on desktop, but I didn't manage to
get `LocalPool` working with `winit` (it needs to post a task to the
`EventLoopProxy` as a wake procedure).
> core: Re-implement `NullExecutor`

- core/src/avm1/globals/xml_node.rs
- core/src/xml.rs
- core/src/xml/tree.rs
The difference between element nodes and text nodes is very minor.
So instead of representing them by two distinct enum members, make
`XmlNodeData` a single unified struct that can represent both. A new
`node_type` field is introduced, in order to still distinguish
between element and text nodes. Also, Ruffle made some incorrect
assumptions, which are now corrected, including:
* Nodes can have any arbitrary `u8` type. This is resolved by the
introduction of the `node_type` field which is a `u8`.
* Text nodes can have children. This is resolved by simply not checking
for text nodes in `append_child` etc.
> xml: Make `XmlNodeData` a struct

- core/src/avm1/activation.rs
- core/src/avm1/globals/load_vars.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/globals/xml.rs
- core/src/loader.rs
- core/src/player.rs
This PR moves all `navigator.fetch()` calls to `Loader`. This will allow moving the logic of `NavigatorBackend::resolve_relative_url` and `NavigatorBackend::pre_process_url` to there as well. Then, we'll be able to create a new `ExternalNavigatorBackend` without specifying a movie URL, which will help improving Ruffle on desktop by not requiring a movie URL on startup.
> core: `Loader` cleanup

- LICENSE.md
- core/Cargo.toml
- core/macros/Cargo.toml
- desktop/Cargo.toml
- render/canvas/Cargo.toml
- render/common_tess/Cargo.toml
- render/webgl/Cargo.toml
- swf/Cargo.toml
- web/LICENSE.md
- web/common/Cargo.toml
- web/packages/demo/LICENSE_MIT
- web/packages/extension/LICENSE_MIT
- web/packages/selfhosted/LICENSE_MIT
Updating authors metadata and copyright notices to mention Ruffle LLC.
I assign to Ruffle LLC all rights, title, and interest to copyrights of my personal contributions to Ruffle, effective March 26, 2022.
See attached PDF for full copyright assignment and legalese:
[CopyrightAssignment.zip](https://github.com/ruffle-rs/ruffle/files/8356351/CopyrightAssignment.zip)
All other contributors continue to have copyright over their own contributions; no change there.
> chore: Update copyright

- core/src/avm1/value.rs
```
var o = new Object();
o.toString = undefined;
trace(String(o)); // "[type Object]"
function f() {}
trace(String(f)); // "[type Function]" (returns "[type Object]" in the current builds)
```
> avm1: `String(function)` returns `[type Function]`

- web/src/audio.rs
Doc comments are ignored here and can generate warnings, so change to regular comments.
> chore: Remove doc comments from extern blocks

- render/canvas/src/lib.rs
Since Rust 1.45, the `as` keyword performs a saturating cast when
casting from float to int. Therefore the `clamped_u8_color` function
is useless, and `as` can be simply used instead.
> canvas: Remove `clamped_u8_color` function

- .github/workflows/release_nightly.yml
- desktop/assets/macOSEntitlements.plist
This PR adds a codesigning step to the macOS bundler, using the same methodology as in [this blog post](https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions).
It requires three new secrets:
* `APPLE_DEVELOPER_IDENTITY` - the ID of the Developer ID cert (the 10-letter string you see in parenthesis in Keychain Assistant or `security find-identity`)
* `APPLE_DEVELOPER_KEY` - The Developer ID signing key and certificate itself, exported from Keychain Assistant in `.p12` format and then base64 encoded
* `APPLE_DEVELOPER_KEY_PASSWORD` - Unlock key for the above secret. `.p12` files have to have a decryption key, so this secret needs to be populated.
All of these are ultimately derived from a Developer ID cert that I need @Herschel to generate for me, which is …
> Codesign macOS bundles

- .github/workflows/release_nightly.yml
This enables notarization. I tested the process on my local machine and it was entirely painless; in fact the current nightly is already notarized if you're online. This also adds stapling so it should work offline as well.
Since we need to talk to Apple's developer servers, this introduces another three secrets:
* `APPLE_ID` - The username of an Apple ID to log into. Must be a member of `APPLE_TEAM`.
* `APPLE_APP_PASSWORD` - An app-specific password to authenticate `notarytool` with.
* `APPLE_TEAM` - The Team ID to notarize under. Must be the same team used to issue the Developer ID cert stored in `APPLE_DEVELOPER_KEY`.
Fortunately I was able to do this myself. This documentation is purely for anyone who needs to rotate these credentials.
This also sets a lower `MACOSX_DEPLOYMENT_TARGET` …
> macOS notarization & set minimum macOS version

- render/wgpu/src/lib.rs
- render/wgpu/src/target.rs
The `image` crate removed `Bgra` in version 0.24.0:
https://github.com/image-rs/image/blob/master/CHANGES.md#version-0240
So stop using it, and start using `Rgba` instead. The affected code
is mostly only relevant for tests (image capturing), however there was
a real usage of `wgpu::TextureFormat::Bgra8Unorm` in `build_descriptors`,
which is now changed to `wgpu::TextureFormat::Rgba8Unorm`. Seems harmless
at a glance, though it might have some implications, as the reason
for choosing `Bgra8Unorm` in the first place is that per the `wgpu`
documentation, the only formats that are guaranteed are `Bgra8Unorm`
and `Bgra8UnormSrgb`:
https://docs.rs/wgpu/0.10.1/wgpu/struct.SurfaceConfiguration.html#structfield.format
Should allow #6328 to be merged.
> wgpu: Switch `Bgra` over to `Rgba`

- .github/workflows/release_nightly.yml
- desktop/Cargo.toml
- desktop/assets/macOSEntitlements.plist
- desktop/src/navigator.rs
Enable App Sandbox on the release version of Ruffle.
This implies one major user-facing change: playing movies that load external files from the filesystem requires picking the containing directory. To facilitate this, we introduce a new `sandbox` feature that tells the user what the movie is trying to do, and asks if they want to allow it. This should be minimally disruptive.
Currently I'm only enabling the following two sandbox entitlements:
* `com.apple.security.files.user-selected.read-only` - Ability to open file pickers and get access to files picked through them.
* `com.apple.security.network.client` - Ability to open *outgoing* network connections. AFAIK this should allow HTTP movie loads from desktop but I haven't tested this yet. It should also work with #5160 and similar …
> macOS App Sandbox

- web/packages/core/src/ruffle-object.ts
- web/packages/selfhosted/test/polyfill/object_double_object/expected.html
- web/packages/selfhosted/test/polyfill/object_double_object/index.html
- web/packages/selfhosted/test/polyfill/object_double_object_classid/expected.html
- web/packages/selfhosted/test/polyfill/object_double_object_classid/index.html
- web/packages/selfhosted/test/polyfill/object_double_object_classid/test.js
Fixes the second part of #2220 and closes the issue.
> web: Only polyfill `<object>` with `classid` when it doesn't contain another polyfillable object tag

- core/src/display_object/video.rs
This SWF contains a video stream with zero frames, which caused a divide-by-zero in `Video::seek`.
> core: Fix divide-by-zero in Video::seek (fix #6605)

- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/loader.rs
- core/src/player.rs
Remove the preload step that would pre-create the shapes for each morph shape ratio on SWF load. Instead, lazily crate the shapes as they are needed. We already do similar for the drawing API, so it doesn't seem necessary to create these shapes ahead of time.
This removes a large amount of complex code from `MovieClip::preload`, as all timelines had to be scanned to determine what ratios of a morph shape were used.
> core: Remove morph shape preloading

- web/packages/extension/src/background.ts
If a frame directly loaded an SWF, it would not display in Ruffle.
Add `subframe` to the types intercepted by the `onHeaderReceived`
event in the background script so that Ruffle will display the SWF
in the frame.
Fixes #6582.
> extension: Allow loading SWFs in frames (fix #6582)

- core/src/backend/audio/mixer.rs
Integer math was used when calculating a sound's start/endpoints,
because it was assumed that the sound sample rate was always an
even divisor of 44100Hz. However, some third party tools can embed
MP3s with other samples rates, such as #6569 which has a 16000Hz
MP3. This could also occur for dynamically loaded MP3s. This
results in the sound starting at an incorrect position.
Use floating point math to ensure the correct position is
caluclated.
Fixes #6569.
> desktop: Use floats for audio start/endpoints calculation (fix #6569)

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
- Cargo.lock
- core/Cargo.toml
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- render/wgpu/Cargo.toml
- web/Cargo.toml
- web/README.md
- web/common/Cargo.toml
As usual, also bump its helper crates (`js-sys`, `web-sys` and
`wasm-bindgen-futures`) to the latest versions.
> web: Bump wasm-bindgen to 0.2.80

- core/src/avm1/value.rs
Closes #6286.
This also fixes `int(String)` in SWFv4 when the string is something like "345ABC" (it now returns 345).
[Here is a test](https://github.com/ruffle-rs/ruffle/files/8446418/swf4_test.zip) made with JPEXS (includes the .swf, code as .txt and output) that could eventually be added (a .fla would be better but I don't know if the Flash editor would let you use `ToNumber` as this action code was only added in SWFv5).
> avm1: Fix `Number(String | Object)` in SWFv4

- web/src/lib.rs
- web/src/navigator.rs
It's shorter and should be more efficient (allocates an uninitialized
buffer instead of a zeroed one).
> web: Use `Uint8Array::to_vec()` over `Uint8Array::copy_to()`

- core/src/avm1/globals/xml.rs
- core/src/avm1/globals/xml_node.rs
- core/src/avm1/object/xml_node_object.rs
- core/src/avm1/object/xml_object.rs
- core/src/avm1/value.rs
- core/src/ecma_conversions.rs
- core/src/xml.rs
- core/src/xml/tree.rs
Unify the previous 3 creation methods to a single `XmlNode::new`.
This allows supporting arbitrary `nodeType` values passed to the
`XMLNode` constructor.
> xml: Refactor `XmlNode` creation methods

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/avm2/globals/flash/filters.rs
- core/src/avm2/globals/flash/filters/bitmapfilter.rs
- core/src/avm2/globals/flash/filters/glowfilter.rs
This gets 'Rolling Hero' further in the startup process,
since it just tries to set a filter on an object.
> avm2: Add stubs for `BitmapFilter`, `GlowFilter`, and `DisplayObject.filters`

- core/src/avm1/value.rs
- core/src/ecma_conversions.rs
This PR is an attempt at formatting floating-point numbers, trying to match what Flash does in AVM1. For instance:
- `(0.7 - 0.5)` equals to 0.19999999999999996 but is formatted as 0.2 (as the number of decimals is 15 at most).
- `100000.12345678912` is formatted as 100000.123456789 (the number of decimals is decreased here because of the number of digits in... the whole part).
There are unfortunately some cases that still fail with this PR:
- `0.8000000000000005` should be 0.800000000000001 but this PR formats it as 0.8.
- `0.8300000000000005` should be 0.83 but this PR formats it as 0.830000000000001.
[Here's a test](https://github.com/ruffle-rs/ruffle/files/8409951/numbers_test.zip) showing the improvements and the cases that are still incorrect.
There's definitely room for improvement …
> avm1: Format floating-point numbers

- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/selfhosted/test/polyfill/embed_youtube/expected.html
- web/packages/selfhosted/test/polyfill/embed_youtube/index.html
- web/packages/selfhosted/test/polyfill/embed_youtube/test.js
- web/packages/selfhosted/test/polyfill/object_youtube/expected.html
- web/packages/selfhosted/test/polyfill/object_youtube/index.html
- web/packages/selfhosted/test/polyfill/object_youtube/test.js
More accurate alternative to #6520. Fix #4030 and fix #6504.
This behavior is explained by https://wiki.mozilla.org/QA/Youtube_Embedded_Rewrite. See https://bugzilla.mozilla.org/attachment.cgi?id=8707266&action=diff and https://hg.mozilla.org/mozilla-central/rev/5125dbdcbcb2 for implementation in Firefox. See https://chromium.googlesource.com/chromium/src.git/+/e0135598f6bf547463bc943100da4574c5f89930%5E!/ for implementation in Chromium.
~~Edit: My 2nd commit is because this only happen for embeds.~~
Edit: I now change the src for Youtube Flash embeds on http to https if the window is on https and upgradeToHttps is not false, which is technically inaccurate behavior, but I thought was better anyway.
> web: Don't polyfill YouTube Flash embeds

- Cargo.lock
- core/Cargo.toml
- core/src/backend/audio/decoders.rs
- core/src/backend/audio/decoders/adpcm.rs
- core/src/backend/audio/decoders/mp3.rs
- core/src/backend/audio/decoders/nellymoser.rs
- core/src/backend/audio/decoders/pcm.rs
- core/src/backend/audio/mixer.rs
This feature stopped building with the bump to symphonia 0.5, which
added a `Sync` bound to its traits.
* Add `Sync` bounds to our own internal audio traits to match.
* nellymoser::Decoder was also tweaked to add a Sync bound.
* Lock the nellymoser dependency to a specific git commit.
> audio: Fix symphonia feature

- core/src/avm1/globals/movie_clip.rs
- core/src/avm2/globals/flash/display/graphics.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/morph_shape.rs
- core/src/drawing.rs
- core/src/html/layout.rs
- core/src/shape_utils.rs
- render/canvas/src/lib.rs
- render/common_tess/src/lib.rs
- swf/src/read.rs
- swf/src/test_data.rs
- swf/src/types.rs
- swf/src/write.rs
Clean up `swf::LineStyle` and add support for strokes with gradient and bitmap styles (LineStyle2) on all backends.
* Remove `LineStyle::color`, instead using `FillStyle::Color` to indicate solid color.
* Store `LineStyle::flags` bitflags instead of separate bools/values.
* Add builder-style getters/setters methods for ease of use.
* Fix misnamed `ALLOW_CLOSE` flag to `NO_CLOSE.`
* Clean up  `common_tess::ShapeTessellator::tessellate_shape`
* Handle gradient/bitmap strokes in `common_tess` and `canvas` backends.
> render: Handle gradient/bitmap strokes

- core/src/display_object.rs
- core/src/display_object/stage.rs
- core/src/player.rs
- render/canvas/src/lib.rs
- render/webgl/shaders/color.frag
- render/webgl/shaders/gradient.frag
- render/webgl/src/lib.rs
- render/wgpu/shaders/color.wgsl
- render/wgpu/shaders/common.wgsl
- render/wgpu/shaders/gradient.wgsl
- render/wgpu/src/pipelines.rs
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/src/lib.rs
* Change wgpu/WebGL shaders to output premultiplied alpha.
* Browser engines themselves work in premultiplied alpha, so output this for proper alpha blending on a transparent canvas.
* This will help with #6629 because Flash bitmaps are stored with premultiplied alpha.
* Add "wmode" Flash embed parameter to web config.
* Currently only "transparent" has an effect.
* Perhaps we can simulate "window" vs. "opaque" using something like `z-index: 999`.
* "gpu"/"direct" will always be ignored.
Fixes #1752.
> web: Support transparent wmode

- core/src/backend/render.rs
Use integer arithmetic, which is more accurate and efficient.
> render: Improve CMYK to RGB conversion

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash.rs
- core/src/avm2/globals/flash/accessibility.rs
- core/src/avm2/globals/flash/accessibility/accessibilityproperties.rs
A lot of z0r loops complained about it being missing.
Now they don't, even if it does nothing.
I'm not sure whether there's a point in calling `super_init` in `instance_init` in this case, and whether this class should have the `FINAL` attribute as well.
EDIT: @adrian17 answered that it shouldn't be `FINAL`, and that technically `super_init` should indeed always be called, even if in this case it most likely does nothing.
> avm2: Stub flash.accessibility.AccessibilityProperties

- .github/workflows/release_nightly.yml
`actions/download-artifact` puts the asset in the wrong spot, which means we generate an app extension with no resources. This generates an extension that reliably crashes Safari in infinite recursion if you try to load it. This PR fixes the command that builds the appex bundle to copy from the place `download-artifact` puts the ZIP.
> Fix Safari web extension

- web/packages/core/src/public-api.ts
Cloudflare's Rocket Loader script [prevents the DOMContentLoaded event from firing](https://dev.to/hollowman6/solution-to-missing-domcontentloaded-event-when-enabling-both-html-auto-minify-and-rocket-loader-in-cloudflare-5ch8), which was preventing Ruffle's public API from initializing. Work around this by listening for the `readystatechange` event instead.
Fixes #2254 and #6583.
> web: Fix compatibility with Rocket Loader

- core/src/avm2/activation.rs
- core/src/avm2/events.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/array.rs
- core/src/avm2/globals/flash/display/bitmap.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/avm2/globals/flash/display/displayobjectcontainer.rs
- core/src/avm2/globals/flash/display/movieclip.rs
- core/src/avm2/globals/flash/display/simplebutton.rs
- core/src/avm2/globals/flash/display/stage.rs
- core/src/avm2/globals/flash/events/eventdispatcher.rs
- core/src/avm2/globals/flash/events/mouseevent.rs
- core/src/avm2/globals/flash/media/sound.rs
- core/src/avm2/globals/flash/text/textfield.rs
- core/src/avm2/globals/function.rs
- core/src/avm2/globals/json.rs
- core/src/avm2/globals/string.rs
- core/src/avm2/globals/vector.rs
- core/src/avm2/names.rs
- core/src/avm2/object.rs
- core/src/avm2/object/class_object.rs
- core/src/avm2/object/script_object.rs
- core/src/avm2/value.rs
- core/src/display_object/movie_clip.rs
This PR attempts to remove all "undefined is not an Object" and "null is not an Object" errors by replacing `coerce_to_object` calls with `as_object` throughout the project.
There are only two remaining calls to `coerce_to_object`, mostly to facilitate the use of `PrimitiveObject`. Our new programming guidelines are:
* If you want an object, use `as_object`, and return an appropriate error if you get `None`.
* If you want a primitive value, use the various `coerce_*` functions to get one.
> AVM2: Get rid of all "undefined is not an Object" and "null is not an Object" errors

- web/packages/selfhosted/wdio.conf.js
Bump mocha's timeout from 60 secs to 120 secs to attempt to improve the reliability of our Windows node tests.
> ci: Bump mocha timeout length

- core/src/avm2/property_map.rs
- core/src/backend/audio.rs
Per the rust-analyzer diagnostic: https://rust-analyzer.github.io/manual.html#replace-filter-map-next-with-find-map
> chore: `.filter_map(..).next()` -> `.find_map(..)`

- core/src/display_object.rs
- core/src/display_object/movie_clip.rs
- swf/src/types.rs
* Stub out the following PlaceObject parameters and corresponding properties in `DisplayObject`:
* Blend mode
* Cache-as-bitmap
* Background color
* Improve accuracy of PlaceObject behavior.
* Some properties only take effect on initial creation of an object: name, clip depth, clip actions, ...
* Attempts to modify these properties in a subsequent PlaceObject are ignored.
* Move initialization of these properties from `DisplayObject::apply_place_object` to `MovieClip::instantiate_child`.
* Also removed these from `GotoPlaceObject::merge` (because they can't be modified after initial creation)
* This should have no effect on most content, because Flash IDE would generally not export modify PlaceObject tags in this way, instead doing a RemoveObject followed by a fresh PlaceObject tag if …
> core: Stub out remaining PlaceObject data

- .github/workflows/test_web.yml
For unknown reasons, tests on the Windows web build continue to be flaky on GitHub CI. Disable them for now. Tests continue to be run on Ubuntu.
> ci: Don't test web build on Windows

- core/src/backend/navigator.rs
- core/src/loader.rs
- desktop/src/navigator.rs
- web/src/navigator.rs
Previously, loaded movies had their URL the same as the requested URL. However this is incorrect, as they should have the final response URL, obtained after any redirects.
Solve this using a newly-introduced struct `Response`, which holds both response body bytes and response URL. Then, use it as the URL of loaded movies. In the future, `Response` could also hold the HTTP response code, instead of treating any fetch error as 404, if that makes sense.
Also, inline per-implementation `NavigatorBackend::resolve_relative_url` into `NavigatorBackend::fetch`, because no one else uses the resolved request URL anymore, which nicely simplifies the `NavigatorBackend` interface a bit.
> core: Use response URL for loaded movies

- core/src/backend/navigator.rs
- core/src/tag_utils.rs
The remaining caller was `SwfMovie::from_path`, which is now changed
to be simpler, and a little stricter (panics if `Url::from_file_path`
fails, though it shouldn't happen with canonicalized paths).
> core: Remove `url_from_relative_path`

- web/packages/core/src/ruffle-embed.ts
- web/packages/core/src/ruffle-object.ts
- web/packages/core/src/ruffle-player.ts
`Element` is a slightly more general type, which is more common than
`HTMLElement`, and it satisfies our needs in most cases.
> web: Prefer using `Element` over `HTMLElement`

- core/src/avm2/globals/flash/text/textfield.rs
There's already a `has_background` field on the underlying object
data, so we can just map this property to it.
> Implement `TextField.background` getter/setter

- render/webgl/shaders/bitmap.frag
- render/webgl/shaders/color.frag
- render/webgl/shaders/color.vert
- render/webgl/shaders/gradient.frag
- render/wgpu/shaders/bitmap.wgsl
- render/wgpu/shaders/color.wgsl
- render/wgpu/shaders/gradient.wgsl
Clamp the alpha value to [0.0, 1.0] before premultiplying in shaders to avoid colors getting out of wack when alpha isn't [0.0, 1.0]. Also a tiny optimization to the color shader to move the color adjustment from the fragment stage to the vertex stage.
Fixes #6954.
> render: Clamp alpha in shaders (fix #6954)

- render/webgl/shaders/bitmap.frag
- render/webgl/shaders/color.vert
- render/webgl/shaders/gradient.frag
The latter seems to not exist in GLSL.
This is a fixup for #6959, in accordance with https://github.com/ruffle-rs/ruffle/pull/6959#issuecomment-1125829201=.
> webgl: Use `clamp(x, 0.0, 1.0)` instead of `saturate(x)`

- core/src/avm1/property_decl.rs
This was recently added in https://github.com/rust-lang/rust/pull/96150
Some of the `__version` rules are currently unused, but I assume
that we still want to keep them for potential future use.
> Allow new `unused_macro_rules` lint on `declare_properties`

- core/src/avm2/globals/flash/events/eventdispatcher.rs
So that it can run before constructors if necessary.
Due to various quirks of how timeline-initiated symbols interact with AVM2, it is possible for user code to gain a reference to uninitialized objects (especially `SimpleButton` which doesn't initialize until after `exitFrame`). It is still possible to attach event handlers to them that fire correctly, and movies expect to be able to.
This is a part of #5876 that I'm breaking out into a separate PR since it really has nothing to do with the difficult-to-review parts.
> avm2: Make dispatch list initialization lazy

- Cargo.lock
- render/canvas/Cargo.toml
- render/canvas/src/lib.rs
This is an attempt to remove the SVG drawing paths from the canvas renderer. The SVG path is necessary because the canvas drawing API does not easily support all of the features Flash needs, such as arbitrarily transformed gradients. In those cases, we were falling back to generating an SVG image and drawing that to the canvas (SVG has all of the necessary features). However, this is problematic because the browser's loading of the SVG image is async, which causes a delay between when we create the shape and when we can actually draw it to a canvas (#6969). It's also quite a bit slower.
For the case of "simple" gradients (no skewing in the transform), we can use the `CanvasGradient` directly. For complex cases, we can push the gradient transform with `canvas.transform`, and then draw the …
> canvas: Use canvas drawing commands for gradients

- web/packages/core/package.json
The web build script in `core\package.json` sets the `RUSTFLAGS`
env var, which overrides any settings in `.cargo/config.toml`.
Add `-Aunknown_lints` to these `RUSTFLAGs` to squelch a stray
`unused_macro_rules` warning.
> chore: Allow unknown_lints in web build

- Cargo.lock
- render/canvas/Cargo.toml
They're now unused thanks to #6975.
Also remove the `crate-type` field from `Cargo.toml`. I'm not sure
exactly what it does and why it was introduced, but seems working
without it.
> canvas: Remove some unused dependencies

- .github/workflows/test_rust.yml
Per https://doc.rust-lang.org/cargo/commands/cargo-test.html#manifest-options,
`cargo --locked` assumes that `Cargo.lock` is up-to-date, and otherwise
exits with an error.
Besides the nice validation, this might hopefully speed-up CI a bit.
This could be done on Web as well, but I'm not sure what's the best
way of doing it.
> ci: Run cargo in locked mode

- .cargo/config.toml
- web/packages/core/package.json
Also add a note to `.cargo/config.toml` about `RUSTFLAGS` in `web/peckage.json`.
This is a fixup of #6989.
> chore: Allow `unknown_lints` in both WASM modules

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm2/globals/flash/display/bitmapdata.rs
- core/src/backend/render.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
* Handle greyscale and greyscale+alpha PNGs in `render::decode_png`.
* Add a `Bitmap::from_data` constructor that asserts that bitmap data has the expected length. Zero-pad or truncate the data to ensure the correct length.
* This shouldn't happen, but let's do this to ease any burden on the backend in case our decoding screws up somehow.
* For example, the canvas backend was panicking before greyscale was handled, because the data was an incorrect length.
> core: Handle greyscale PNGs

- core/src/avm2/events.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/events.rs
- core/src/avm2/globals/flash/events/errorevent.rs
- core/src/avm2/globals/flash/events/securityerrorevent.rs
- core/src/avm2/globals/flash/events/textevent.rs
- core/src/avm2/object/event_object.rs
- core/src/loader.rs
I ruined the commit history of #7025, so re-implement it. I believe collaborators can squash and merge, but it's easier for me to work with a normal branch as opposed to a messed up branch if I need to make any changes.
Implement the methods and constants for ErrorEvent, TextEvent, and SecurityErrorEvent and update IOErrorEvent to use proper inheritance.
> avm2: Add more Event classes' methods and properties

- core/src/avm1/globals/xml.rs
- core/src/avm1/object/xml_object.rs
- tests/tests/regression_tests.rs
Store just the XML declaration string itself, rather than the attributes
it consists of. Then simply return it in ActionScript's `XML.xmlDecl`
property, without using `quick_xml::Writer` at all. This also matches
Flash behavior by capturing the XML declaration as-is, preserving
whitespaces, quotes, casing etc.
> avm1: Simplify `XML.xmlDecl`

- core/src/display_object/stage.rs
- core/src/player.rs
- desktop/src/main.rs
Adds the `--fullscreen` flag.
This can be especially useful with launchers or scripts, e.g. Steam.
With the current behavior a black window opens until the content loads, ideally the window shouldn't be shown but I think that's outside the scope of this pr, and will probably depend on how we choose to do UI going forward.
> desktop: Add fullscreen command line option

- render/canvas/Cargo.toml
- render/canvas/src/lib.rs
Reimplement masking on the canvas backend using the native [`CanvasRenderinContext2d.clip`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clip) method.
When I first implemented masking in canvas, I didn't think `clip` could handle all of the nuances of Flash masking, so I ended up with a hacky+slow solution of drawing to off-screen canvases and using `globalCompositeOperation` to blend onto the main canvas. But I think we can handle nearly all of the cases natively using `clip` now:
* [`clip(Path2D)`](https://caniuse.com/mdn-api_canvasrenderingcontext2d_clip_path_parameter) is now supported in all major browsers.
* Strokes aren't considered when masking. Originally I was worried that strokes could mask content as well, which would be impossible with `clip`. But …
> canvas: Reimplement masking

- render/canvas/src/lib.rs
* Remove `BitmapDataStorage` as its no longer necessary, and store the bitmap canvas/context in `BitmapData` instead.
* Store the `Bitmap` RBGA buffer in the canvas backend. Previously this was thrown away when converted to `ImageData`, but this causes the glitchy pixels mentioned in:
https://github.com/ruffle-rs/ruffle/pull/7026#issuecomment-1133669200
https://github.com/ruffle-rs/ruffle/pull/6975#issuecomment-1127942520
* `ImageData` does not copy the buffer passed to it, so store it to keep it alive. See:
https://github.com/rustwasm/wasm-bindgen/issues/2445
> canvas: Remove `BitmapDataStorage` and fix lifetime of bitmap data

- swf/src/write.rs
The implementation of `write_debug_id` was previously
not writing the header, causing a malformed SWF to be produced
whenever a `DebugId` tag was included.
> Write out tag header for `DebugId` tag

- render/wgpu/src/lib.rs
These arguments were being passed in the wrong order, leading to a crash
when the width and height are not equal.
> Fix swapped 'width' and 'height' in wgpu `register_bitmap_raw`

- core/src/display_object/edit_text.rs
- core/src/transform.rs
- swf/src/types/matrix.rs
* Mark some `swf::Matrix` functions as `const` - Because why not?
* Use `swf::Matrix::translate` in more places - Replace direct instatiations of `swf::Matrix` where only `tx` and `ty` are specified, and other fields are default. This results in a slightly more shorter, readable code.
> swf: `Matrix`-related cleanups

- core/src/backend/render.rs
- render/canvas/src/lib.rs
- render/common_tess/src/lib.rs
* Remove dead `srgb_to_linear` function in `canvas`. There's another similar function in `core/src/backend/render.rs`.
* Move remaining `srgb_to_linear` function from `core` to `common_tess`, since it's the only user of it. Also make it mutate the float array parameter instead of returning a new one, just to simply things a bit.
> render: Move `srgb_to_linear` to `common_tess`

- web/packages/extension/manifest.json5
Sites such as godaddy.com and a bank referenced in #2158 do not allow users to sign in with the Ruffle extension active.
While we are uncertain of the cause, the best option may be to simply prevent Ruffle from executing on these domains.
> Add exclusions for sites broken by extension

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/avm2/globals/flash/filters.rs
- core/src/avm2/globals/flash/filters/blurfilter.rs
This stubs out BlurFilter, adds properties to GlowFilter,
and make the getter for  DisplayObject.filters return
an empty array instead of Undefined.
This is all of the filter-related code that 'Solarmax'
needs in order to reach the main screen (combined with
other unrelated changes I have yet to submit)
> avm2: More filter-related stubs

- .github/workflows/test_web.yml
- web/README.md
Which is the "current" release per https://nodejs.org/en/about/releases/.
This is in order to be prepared for potentially incoming breaking changes.
> web: Run tests on Node.js 18

- core/build_playerglobal/src/lib.rs
In order to reduce builtins size even further.
> avm2: Pass `-optimize` to `asc`
