- desktop/src/render.rs
This changes gradients to allow more than 8 colors.
> Fix issue #6

- Cargo.toml
- README.md
- desktop/Cargo.toml
- scanner/Cargo.toml
- scanner/src/main.rs
Right now this just checks for "is the swf valid & do the tags read successfully", but we can expand the capabilities later. Having a way to check if a bunch of swfs start, or stop, successfully parsing is a very neat thing!
> Added a bulk swf scanning tool

- core/src/avm1.rs
I forgot this somewhere in the last batch of mega-PRs, somehow...
There's technically a test for this but it's somewhere in the massive Object Prototyping PR that I'm currently trying to cut into manageable pieces.
> Implement `ActionEnumerate2`.

- core/src/display_object.rs
- core/src/player.rs
This is a PR against #129 to make that PR work.
> chore: Change to no_drop from empty_drop for new gc-arena

- web/src/render.rs
This makes #137 compile again.
> Fix compilation when using png 0.15.1

- .dependabot/config.yml
Untested because there's no way for me to test this... 🤔
> Add dependabot checking for javascript (in web)

- core/src/avm1/script_object.rs
- core/src/avm1/stage_object.rs
- core/src/avm1/test_utils.rs
- core/src/context.rs
- core/src/display_object.rs
- core/src/display_object/movie_clip.rs
- core/src/player.rs
Manually tested, unsure how to properly make automated tests for events yet.
> Implemented mouse coordinates & events

- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
- swf/src/read.rs
This plays sounds whenever a button is hovered/clicked. Fixes
gun sounds in Pico's School.
> core: Handle DefineButtonSound SWF tag

- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
- swf/src/read.rs
- swf/src/test_data.rs
- swf/src/types.rs
- swf/src/write.rs
Used to alter color of items in buttons in very very old SWF content. Anyone know of content that uses this in the wild?
> core: Implement DefineButtonCxform SWF tag

- core/src/avm1.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/script_object.rs
- core/src/avm1/test_utils.rs
- core/src/bounding_box.rs
- core/src/context.rs
- core/src/display_object.rs
- core/src/display_object/button.rs
- core/src/player.rs
This is used by a lot of older games.
> avm1: Implement StartDrag/EndDrag

- web/Cargo.toml
- web/src/lib.rs
Allows dragging etc. to properly work on mobile.
> web: Use pointer events on web

- core/src/avm1/globals/math.rs
This should finish everything left open on #260
> avm1: Implement remainder of Math

- core/src/avm1/value.rs
Add these methods that will explicilty coerce a value to an int,
following the wrapping behavior in the ECMAScript specs (ToInt32,
ToUInt32, ToUInt16).
This also fixes an off-by-one error for negative numbers in the
previous implementation.
These will call `valueOf` if necessary. AVM code that requires an
integer will probably use one of these (`coerce_to_i32` usually).
> avm1: Add Value::coerce_to_i32/u32/u16 methods

- web/demo/www/index.html
Edited styling for web demo page to look more like the https://ruffle.rs homepage.
> Spruced up Web Demo Page

- web/js-src/ruffle-player.js
When Ruffle replaces a Flash embed, the width/height of the embed
are copied over to CSS of the Ruffle element. "px" was being
appended even if the dimensions were a % value, which CSS rejected.
Try to be a little smarter about parsing out the HTML dimension
attributes (HTML is more lenient). Append "px" only if the value
isn't a percentage.
Fixes #433.
> web: Handle percentage dimensions in polyfill (fix #433)

- core/src/xml/tests.rs
Not a huge deal but it kept annoying me by adding noise when running tests. :D
> Removed debug code from a test

- core/src/backend/render.rs
- core/src/player.rs
- desktop/src/render.rs
- web/js-src/ruffle-player.js
- web/js-src/shadow-template.js
- web/src/lib.rs
- web/src/render.rs
Add a nicer play button to replace the "Click to Play" screen. Replace it with a simple HTML+CSS button in `shadow-template.js`. Someone with more web design skill is welcome to improve this -- doing something simple for now because anything is an improvement over a horrendous gray "Click to Play".
Needed for #520.
> web: Add nicer play button

- web/demo/www/index.html
- web/demo/www/index.js
- Mobile styling changes for web demo page on mobile devices. Now the sample dropdown will show up on smaller devices.
- Fixed bug with random selection of SWF files.
> Web Demo Mobile Styling Changes + Bug Fix

- core/src/player.rs
- core/src/tag_utils.rs
- core/tests/regression_tests.rs
- desktop/src/main.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/utils.rs
- web/src/lib.rs
This annoyed me a little. It's also prepwork for taking screenshots of movies; we need to know their width/height to create a buffer before we can create a renderer.
> Create desktop window with proper width/height

- web/js-src/shadow-template.js
Use inline svg inside of the play button div instead of base64-encoded background svg & use css filter to lighten play button rather than swapping svg's.
> Simplify Play Button Code

- README.md
> Added documentation for extension in readme

- Cargo.lock
- Cargo.toml
- README.md
- core/src/backend/navigator.rs
- core/src/backend/render.rs
- core/src/context.rs
- desktop/src/main.rs
- exporter/Cargo.toml
- exporter/src/main.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/target.rs
This is the first step towards #523. Also might be a solution for #328.
Usage is documented in readme. 
I think the next step from here is to figure out how to collect swfs, routinely run this in batch against them, and ideally compare them against knowns. I didn't want to hold up getting "something" before we have the whole process in place though.
> Added swf-to-png exporter tool

- desktop/src/main.rs
When creating the viewport on desktop, the window DPI was not taken
into account, which may result in a blank screen until resized
(reported in #548). The window dimensions are now converted to
physical coordinates before passing them to the renderer.
> desktop: Set viewport dimensions based on physical size

- render/wgpu/src/target.rs
We had our channels mixed up, whoops.
> render: Fix wgpu captures being the wrong image format

- web/package-lock.json
It looks like a package that wasn't updated has a vulnerability. I ran the command `npm audit fix` to update the package.
> Run npm audit fix

- .circleci/config.yml
Oops! Thanks for noticing, @Justin-CB :D
This will fix #617
> Fix circleci release script

- exporter/src/main.rs
Add flag `--scale` to scale the output with a specified factor. Also add flag `--width` and `--height` to override the output width and height, respectively. The scaling factor is applied after the width and height is set. Eg if you set width to 100 and scaling factor to 2.0 the result will have a width of 200px.
The implementation is not optimal and slightly confusing considering the following: the output is not stretched, if the aspect ratio is wrong then black margins are added. Also if only width is added then the height will not be scaled to keep the aspect ratio, rather it will use the document height instead.
Input on alternative ux would be appreciated.
> exporter: Add cli flags to specify output size

- core/src/backend/render.rs
Tested with [this newgrounds animation](https://www.newgrounds.com/portal/view/126209), which oddly is already switched to using Ruffle on newgrounds even though it crashes today.
How it should look (original Flash player):
How it looks in Ruffle with this PR:
The snail on the left is rgb15, the image on the right is a regular jpg. We're about 1 unit off on components on the rgb15, but that's also true on the jpg so I don't consider it a problem.
> Implement RGB15 PNGs

- web/packages/core/src/ruffle-embed.js
- web/packages/core/src/ruffle-object.js
- web/packages/selfhosted/test/polyfill/embed_insensitive/expected.html
- web/packages/selfhosted/test/polyfill/embed_insensitive/index.html
- web/packages/selfhosted/test/polyfill/embed_insensitive/test.js
- web/packages/selfhosted/test/polyfill/object_MIME_insensitive/expected.html
- web/packages/selfhosted/test/polyfill/object_MIME_insensitive/index.html
- web/packages/selfhosted/test/polyfill/object_MIME_insensitive/test.js
- web/packages/selfhosted/test/polyfill/object_and_embed/expected.html
- web/packages/selfhosted/test/polyfill/object_clsid_insensitive/expected.html
- web/packages/selfhosted/test/polyfill/object_clsid_insensitive/index.html
- web/packages/selfhosted/test/polyfill/object_clsid_insensitive/test.js
- web/packages/selfhosted/test/polyfill/object_data/expected.html
- web/packages/selfhosted/test/polyfill/object_data/index.html
- web/packages/selfhosted/test/polyfill/object_data/test.js
This fixes the case where the MIME type or clsid match case-insensitively & fixes #856
> Fix object polyfill

- core/src/avm1/globals.rs
- core/src/avm1/globals/movie_clip.rs
`getURL` exists on `MovieClip.prototype`, not `_global`. For example, _root.getURL should work.
Fixes #804.
> avm1: Move getURL to MovieClip.prototype (fix #804)

- core/src/display_object/morph_shape.rs
Radial gradients were not accounted for in morph shapes.
Addresses #591.
> core: Support radial gradients in morph shapes

- core/src/avm1/globals.rs
Implement `_global.isFinite`, and also mark all `_global` properties as `DontEnum`.
> avm1: Implement isFinite

- core/src/avm1/globals.rs
- core/src/avm1/globals/key.rs
- core/src/avm1/listeners.rs
- core/src/player.rs
Implement Key.addListener et al.
> avm1: Implement Key listeners

- core/src/avm1/value.rs
- core/src/avm2/names.rs
- core/src/avm2/script_object.rs
- core/src/avm2/value.rs
- core/src/display_object/movie_clip.rs
- core/src/xml/tree.rs
Fix new nightly clippy lint asking for `matches!`
> chore: Use matches! to fix clippy lint

- web/packages/core/src/polyfills.js
- web/packages/core/src/public-api.js
- web/packages/core/src/source-api.js
This was discussed in the past & I found it not terribly hard to implement.
> Change polyfills to single true/false setting

- core/src/avm1.rs
- core/src/avm1/globals/as_broadcaster.rs
- core/src/events.rs
- core/src/player.rs
- desktop/src/main.rs
- web/Cargo.toml
- web/src/lib.rs
Implement onMouseWheel listener for both desktop and web (cc #262, #923).
> avm1: Implement mouse wheel event

- core/src/avm1/activation.rs
- core/src/avm1/globals/load_vars.rs
- core/src/avm1/tests.rs
- core/src/backend/navigator.rs
- core/src/lib.rs
- desktop/src/navigator.rs
- web/src/navigator.rs
This makes ridesims.com work :D
Fixes #1004
> Preserve order in GetURL requests

- core/src/player.rs
The `fake_root` did not have an object, which could cause the
player to panic if the SWF was not completely loaded when playing.
Calling `post_instantiate` ensures that this dummy root has an
object.
> core: Call post_instantiate on initial empty root (fix #946)

- README.md
> Change build badges to github actions

- web/src/audio.rs
Sounds were not being removed from the instance list when they
completed playing. This could also cause StartSound tags with
NoMultiple set to not play, because the previous sound was presumed
to be playing.
Fixes part of #1245.
> web: Remove sound instances upon completion

- web/src/lib.rs
Previously any mouse button would be interpreted as a click in Ruffle.
> web: Only fire mouse events for left clicks (fix #1361)

- core/src/avm1/activation.rs
Now it'll only check for timeouts every 200 (arbitrary number, we'll see how it goes) actions on the same Activation.
> Ratelimit timeout check to help ease performance

- web/src/audio.rs
The onended handler was mistakenly removing the handle to the sound definition instead of the specific sound instance. Fixes #1405.
> web: Fix incorrect handle used in audio ended handler (fix #1405)

- web/packages/core/src/ruffle-player.js
- web/packages/core/src/shadow-template.js
Super basic thing but let's get of visibility on the project 😉 
Custom items, including the "built in items", will come next. Will take a fair bit of wiring up.
> web: Add basic right click menu, only has About Ruffle link so far

- render/wgpu/src/lib.rs
Resolve the multisampled frame buffer once at the end of the frame, instead of after in every draw (oops!).
> wgpu: Resolve MSAA once at frame end (fix #1427)

- core/src/display_object/button.rs
> core: Fix double borrow in button post_init - fixes #1450 and #1190

- web/packages/extension/build/_locales/ja/messages.json
This PR adds a Japanese translation.
> i18n: Add Japanese

- web/packages/core/src/ruffle-player.js
- web/packages/core/src/shadow-template.js
- web/packages/demo/www/index.html
- web/src/lib.rs
This PR adds a fullscreen item to the right-click context menu.
Should complete "Fullscreen button" in #4.
> web: Add fullscreen context menu item

- web/packages/core/src/ruffle-player.js
This makes a proper error appear when the issue is MIME type.
> Fixed mime issue detection

- core/src/display_object/movie_clip.rs
A panic could occur when a text field was removed while it had focus, due to both the `unload` handler of the clip running, and the focus tracker running it's `onSetFocus` handler.
Move `remove_child_from_exec_list` and `goto_remove_object` up to `MovieClip` to allow them to granularly release the borrows when firing the unload/focus handlers.
> core: Avoid borrow panic when text is removed (fix #1580)

- render/common_tess/src/lib.rs
- render/wgpu/src/lib.rs
If the miter limit is smaller than lyon's minimum value, fall back to beveled line joins.
> render: Avoid assert from lyon with small miter limits (fix #1194)

- Cargo.lock
- core/Cargo.toml
- core/src/xml/tree.rs
Bump quickxml to 0.20. Fix small breaking change in `Writer::write_event`
> chore: Bump quickxml to 0.20

- core/src/lib.rs
- render/canvas/src/lib.rs
- render/webgl/src/lib.rs
- render/wgpu/src/lib.rs
- swf/src/read.rs
Appease clippy for 11-24 nightly build. Allow unnecessary_wraps lint in core, fix it in other crates.
> chore: Appease clippy, squelch unnecessary_wraps lint

- desktop/src/main.rs
Should hopefully fix Dwedit's issue on discord.
> desktop: Potentially fixed panic when windows can't make a path absolute

- Cargo.lock
- core/Cargo.toml
- core/src/loader.rs
This adds support for BOM.
Fixes #921.
> core: Use encoding_rs in load_vars_loader

- web/packages/core/src/shadow-template.ts
I missed this in #1711, sorry!
> web: Explicitly define font size of context menu

- web/packages/selfhosted/.eslintrc.json
- web/packages/selfhosted/test/polyfill/swf_object/expected.html
- web/packages/selfhosted/test/polyfill/swf_object/index.html
- web/packages/selfhosted/test/polyfill/utils.js
- web/packages/selfhosted/test_assets/swfobject.js
> tests: Add SWFObject.js polyfill test

- web/packages/extension/build/_locales/de/messages.json
A small contribution to a great project.
> Create german version of messages.json

- web/packages/extension/build/_locales/fr/messages.json
> Create messages.json FR translation

- render/webgl/src/lib.rs
Avoid panics from too-small/too-big renderbuffer sizes.
* Decouple the renderbuffer size from the canvas size.
* Clamp the renderbuffer size between 1 and `WebGLRenderingContext.drawingBufferWidth`/`Height`. Generally the `drawingBufferWidth` sizes will match the canvas viewport size; however, the browser does its own clamping of the GL viewport (for example, if the canvas is huge), and these values represent the actual dimensions of the canvas's frame buffer. We should clamp our own framebuffers to match, otherwise we are making huge textures for no reason.
This should fix crashes when the canvas has no size (resize the demo window until the movie disappears), and hopefully address some crashes from zooming in (needs testing).
Possibly addresses #1264, #1538, #1605, #1686.
> webgl: Clamp renderbuffer dimensions to sane values

- core/src/avm1/globals/button.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/display_object/button.rs
- core/src/display_object/movie_clip.rs
Implement Button.enabled and MovieClip.enabled. Also some misc code cleanup.
Fixes button issues in #1374.
> avm1: Implement Button/MovieClip.enabled

- core/src/avm1/globals/shared_object.rs
Specifically handle arrays when serializing SharedObject data in order to preserve its array-ness.
Fixes #1363.
> core: Handle serializing arrays in SharedObjects

- core/src/avm2/activation.rs
Implemented `Swap` according to [this list](https://www.free-decompiler.com/flash/docs/as3_pcode_instructions.en.html).
This is my first time doing a pull request and working on public repos, so there's a big chance I did something wrong.
> Added AVM2 op "Swap"

- web/packages/extension/build/_locales/hu/messages.json
> i18n: Add Hungarian translations

- web/packages/core/README.md
- web/packages/selfhosted/README.md
- web/packages/selfhosted/test/polyfill/classic_frames_injected/index.html
- web/packages/selfhosted/test/polyfill/classic_frames_provided/index.html
- web/packages/selfhosted/test/polyfill/iframes_injected/index.html
- web/packages/selfhosted/test/polyfill/iframes_provided/index.html
> web: Update docs and tests

- core/src/display_object/bitmap.rs
Fix Incorrect Collect implementation causing issues such as #2009.
> core: Fix Collect impl for BitmapData (fix #2009)

- web/src/lib.rs
Flush shared objects when the page unloads. Allows data to save when there isn't an explicit call to `flush`. Fixes #2046.
> web: Flush shared objects on page unload (fix #2046)

- desktop/src/navigator.rs
- web/src/navigator.rs
Don't panic when fetching an invalid URL. Fixes #2187.
> desktop: Avoid panic on fetching invalid URLs (fix #2187)

- core/src/avm2/events.rs
- core/src/html/dimensions.rs
- core/src/types.rs
- core/src/vminterface.rs
Fix latest nightly clippy lints (prefer From to Into).
> chore: Appease clippy

- core/src/avm1/globals/bitmap_data.rs
This is the lazy, quick, dirty, inefficient, but easy way out to fix #2243.
The proper solution would be to have two methods:
- one for the aliasing case, which operates solely on `self`, and which would have to pay attention to the order of iteration in both dimensions (similar to how it's in `scroll`)
- one for the non-aliasing case, which is basically what's there now 
I'm just not sure that would be worth it, as opposed to this little inefficiency for a questionably common case.
> core/avm1: Handle object aliasing in BitmapData.copyChannel by cloning

- core/src/display_object/movie_clip.rs
> Ignore SetBackgroundColor in child movie clips

- web/packages/core/src/shadow-template.ts
- web/packages/demo/package-lock.json
- web/packages/demo/package.json
- web/packages/demo/webpack.config.js
- web/packages/demo/www/index.css
- web/packages/demo/www/index.html
- web/packages/demo/www/index.js
Refactor (mostly) the demo code to be more readable and cleaner.
> web: General refactor

- web/src/lib.rs
Fixes #1263. Should also resolve #876, as I believe this was the same problem.
> web: Remove event listeners when a Ruffle instance is destroyed

- core/src/avm1/globals/shared_object.rs
- core/src/display_object/movie_clip.rs
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ).
> spelling fixes

- web/package-lock.json
- web/packages/demo/www/index.css
- web/packages/demo/www/index.html
- web/packages/demo/www/index.js
Fixes #2223, and partially #2576.
> demo: Add drag-and-drop functionality

- desktop/src/main.rs
Basically just copied from [what alacritty is doing](https://github.com/alacritty/alacritty/blob/530de00049c2afcc562d36ccdb3e6afa2fe396a5/alacritty/src/main.rs).
There are two functional changes:
- When launching normally, you no longer see a console window quickly flashing
- When launching via. console, the program is detached (but still logs to the console, and you can still CTRL+C to kill it)
I can't seem to find a way to keep the program attached to the console, while not marking it a "console application", and getting the ugly flashing. So I would argue this change is the best alternative, given that this is ultimately a client application, not a commandline tool for developers.
> desktop: Change Windows Subsystem to not launch unnecessary console

- desktop/src/main.rs
I don't have that much experience, so can't verify that this actually works
> desktop: Also use flashvars parameters when running local files

- desktop/src/audio.rs
The points in an SWF sound envelope are always in 44.1KHz. The
desktop audio backend would end up using this points in the sound's
sample rate, often causing the envelope to be delayed.
Now the envelope is applied after resampling to the output sample rate, and the positions
are scaled from 44.1KHz to the output sample rate.
> desktop: Fix sound envelopes to use proper positions

- core/src/shape_utils.rs
- desktop/src/audio.rs
- swf/src/avm1/read.rs
- swf/src/read.rs
- swf/src/string.rs
- web/src/audio.rs
Purged a few instances of `unsafe`, lest they proliferate! 😉
> Remove a bit of unsafe

- core/src/avm1/object.rs
- core/src/avm1/object/bitmap_data.rs
- core/src/avm1/object/super_object.rs
- core/src/backend/storage.rs
- core/src/player.rs
- swf/src/read.rs
Some random cleanups I collected over time.
> Small cleanups

- .github/ISSUE_TEMPLATE/bug_report.md
> correct minor typo (space before comma)

- web/src/audio.rs
If `setPan`/`setTransform` were used on a mono sound, they would only play out of one channel. The Web Audio API would still return a `channelCount` of 2 in this case because of the way the `channelCount`/`channelCountMode` parameters work, and the backend would wire up the nodes assuming it was stereo. Instead, let's explicitly store whether we've made a stereo output.
Fixes #3017.
> web: Fix panning of mono sounds (fix #3017)

- render/webgl/shaders/bitmap.frag
- render/webgl/shaders/color.frag
- render/webgl/shaders/color.vert
- render/webgl/shaders/gradient.frag
- render/webgl/shaders/texture.vert
Fixes issues relating to text rendering (#900) and other artifacts
on iOS.
> webgl: Use highp precision when available

- .github/workflows/release_nightly.yml
- .github/workflows/test_web.yml
> ci: Fix web build

- core/src/player.rs
See comment in commit for details.
Currently Ruffle turns every movie that's consistently "slightly slower than expected FPS" into "5x worse than expected FPS".
z0r.de already fixed it on its fork by force-setting `MAX_FRAMES_PER_TICK = 1`. This patch basically does the same thing, but smarter - Ruffle still can run multiple "frames" at a time, but only if it thinks that based on past `run_frame()` timings, it can afford it within a single frame. This was @Herschel 's idea :)
In practice, the proposed video decoders are slow enough on wasm that `max_frames_per_tick()` will always return 1 for 99% of content. Same with most games (except, for example, Fancy Pants).
Oh, and I didn't test this on desktop; just on web.
> Core: Avoid framerate dropping down 5x if frames can't be handled in time.

- web/packages/core/src/js-polyfills.ts
`Reflect` is supposed to have much more methods, but I implemented just enough for code to stop crashing; if more is needed, hopefully it should be easy to add.
Unfortunately this doesn't make any game work, as they all have secondary issues :/
https://github.com/ruffle-rs/ruffle/issues/2406 - now fails on CORS
https://github.com/ruffle-rs/ruffle/issues/2427 - now fails on CORS
https://github.com/ruffle-rs/ruffle/issues/2585 - now fails on CORS
https://github.com/ruffle-rs/ruffle/issues/2948 - now fails on CORS
https://github.com/ruffle-rs/ruffle/issues/2388 - SWF on the login screen loads, but only displays a black screen, while log shows lots of warnings with `Cannot enumerate Undefined` etc. I didn't try logging in to game ofc.
https://github.com/ruffle-rs/ruffle/issues/2471 - can't …
> Minimal polyfill of window.Reflect

- core/src/display_object/movie_clip.rs
> Make disabled MovieClips handle more events

- web/packages/core/src/load-options.ts
- web/src/lib.rs
(close #1773)
Disclaimer: I am not a Rust programmer. This probably works, but as I also am not a Flash programmer, I have no easy way to test it.
> web: Add maxExecutionDuration to Config (close #1773)

- web/package.json
- web/packages/core/src/shadow-template.ts
- web/packages/demo/webpack.config.js
- web/packages/demo/www/index.css
- web/packages/demo/www/index.html
- web/packages/demo/www/index.js
- web/packages/extension/webpack.config.js
- web/packages/selfhosted/webpack.config.js
General refactoring and cleanup to the web code.
Noticeable changes:
* Disabled the loading of a random SWF file when visiting the demo page, as it was somewhat annoying.
* Added a "Select a demo or drag an SWF" prompt to fill up the empty space. I initially imagined an image accompanying the text, but didn't manage to implement that properly. Suggestions for improvements are welcome.
* Reordered the webpack configs to match the order of the examples in the official [documentation](https://webpack.js.org/configuration/).
* General cleanup of CSS files.
> web: General refactoring

- web/packages/core/src/shadow-template.ts
- web/packages/demo/www/index.css
- web/packages/demo/www/index.js
Revert some of the style changes in #3239.
Address #3305.
> web: Revert style changes in #3239

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
Fix some regressions from #3332 (sorry...):
* Fixes #3356.
* Fixes #3358.
> web: Fix regressions

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/object/bitmap_data.rs
Given this test file: [BitmapPaletteMap2.as](https://gist.github.com/torokati44/db2d3653cff54251899cd18f272bf5d6) ([BitmapPaletteMap2.zip](https://github.com/ruffle-rs/ruffle/files/6021646/BitmapPaletteMap2.zip)) 
The output of Flash Player is:
And the difference of that and what Ruffle shows:
This time, the range of the difference image is **NOT** remapped, so those red/blue pixels are really that different!
I couldn't figure out the reason for this, it might be the not perfectly matching conversion of colors to/from premultiplied alpha representation.
In this test, the mapping is effectively applied many times over (because of the in-place operation, and the positive offset), so the errors might be amplified. After a single application, the mismatch is hopefully not quite this stark. …
> Implement BitmapData.paletteMap()

- Cargo.lock
- render/webgl/Cargo.toml
- render/webgl/src/lib.rs
This avoids unsafe code, and reduces code size a bit.
> webgl: Use bytemuck

- core/src/backend/render.rs
Each row should be padded to 2.
Fixes the first picture in [Definitive guide to FPS!](https://www.newgrounds.com/portal/view/201217).
> render: Fix RGB15 bitmaps decoding

- core/src/player.rs
> Run `update_drag` earlier in the update cycle.

- core/src/avm1/globals.rs
Should fix https://github.com/ruffle-rs/ruffle/issues/4003 .
> Add missing clearTimeout()

- web/packages/demo/www/index.html
Add a forgotten `class="hidden"` for `#author-container` in #3806.
> demo: Small fix

- web/packages/extension/src/content.js
> extension: Avoid script injection in XML documents

- Cargo.lock
- render/wgpu/Cargo.toml
- render/wgpu/src/globals.rs
- render/wgpu/src/lib.rs
wgpu 0.8 released, bump to it and remove the git dependency.
> chore: Bump to wgpu 0.8

- CONTRIBUTING.md
Putting the Ruffle side of https://github.com/ruffle-rs/ruffle/pull/4066#issuecomment-824474527 into the docs so it's easier to look up.
> docs: note how to print trace statements

- desktop/src/main.rs
This adds two optional parameters, --width and --height, which allow the user to specify a desired physical window width and height to be used. If only one of the two parameters is present, the other will be deduced from it and the movie's aspect ratio.
If neither are present, the window's size is set to the movie's logical size, in accordance with the behaviour before this change.
> desktop: add parameters to specify window size

- core/src/avm1/activation.rs
- core/src/avm1/function.rs
- core/src/avm1/globals.rs
- core/src/avm1/globals/bevel_filter.rs
- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/globals/boolean.rs
- core/src/avm1/globals/button.rs
- core/src/avm1/globals/context_menu.rs
- core/src/avm1/globals/convolution_filter.rs
- core/src/avm1/globals/display_object.rs
- core/src/avm1/globals/drop_shadow_filter.rs
- core/src/avm1/globals/glow_filter.rs
- core/src/avm1/globals/gradient_bevel_filter.rs
- core/src/avm1/globals/gradient_glow_filter.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/sound.rs
- core/src/avm1/globals/system.rs
- core/src/avm1/globals/text_field.rs
- core/src/avm1/globals/text_format.rs
- core/src/avm1/globals/xml.rs
- core/src/avm1/object.rs
- core/src/avm1/value.rs
- core/src/html/text_format.rs
They happen to be identical, and `swf_version` is more idomatic.
> avm1: Replace `current_swf_version` with `swf_version`

- Cargo.lock
Bump rustfft to 5.1.1, which fixes this issue affecting our nightly build:
https://github.com/ejmahler/RustFFT/issues/74
> chore: Bump rustfft

- desktop/src/main.rs
> desktop: Refactor main.rs

- web/packages/extension/assets/_locales/ko/messages.json
This PR adds a korean translation.
> i18n: Add Korean

- web/packages/extension/assets/_locales/ro/messages.json
This PR adds a Romanian translation.
> i18n: Add Romanian

- core/src/display_object/movie_clip.rs
Previously these were used because the methods were on `MovieClipData` instead of `MovieClip`, but now they are no longer necessary.
> avm1: Remove extraneous self parameters from MovieClip methods

- core/src/display_object/movie_clip.rs
- core/src/library.rs
- swf/src/read.rs
- swf/src/test_data.rs
- swf/src/types.rs
- swf/src/write.rs
Use bitflags for `swf::FileAttributes`.
> swf: Use bitflags for FileAttributes

- core/src/display_object.rs
- core/src/display_object/movie_clip.rs
> fix: read visible from PlaceObject

- core/src/avm1/function.rs
- swf/src/avm1/read.rs
- swf/src/avm1/types.rs
- swf/src/avm1/write.rs
Replace the long list of bools with bitflags.
> swf: Use bitflags for Function flags

- web/packages/core/src/ruffle-player.ts
Fix #3679
Note: Failing tests are due to the clippy lint needless_borrow, not anything I changed.
> web: Link to information about CompileErrors when CompileErrors occur

- core/src/display_object/movie_clip.rs
Support magical button labels on movie clips.
Progresses on #4261: avm1 only.
Fixes #3821.
> core: support magic button labels for avm1

- web/packages/extension/assets/_locales/hu/messages.json
Should I provide explanations and reasoning for each of the changes?
I'm not sure how this could be reviewed by anyone not speaking this language...
Although Google Translate (back to English) might help a bit.
> web: Improve Hungarian translations

- web/packages/core/src/public-api.ts
- web/packages/core/src/register-element.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/version-range.ts
> web: Fix lint warnings

- Cargo.lock
- core/Cargo.toml
- core/src/avm1/globals/selection.rs
- core/src/avm1/value.rs
- core/src/avm2/value.rs
- core/src/html/layout.rs
Take advantage of some new features introduced in Rust 1.53.0 recently: https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html
> chore: Use Rust 1.53.0 features

- core/src/backend/audio/decoders/adpcm.rs
Store samples and steps as `i16` instead of `i32`.
Fixes #4660.
> core: Fix ADPCM decoding

- core/src/avm1/globals/color.rs
- core/src/avm1/globals/color_transform.rs
- core/src/avm1/object/bitmap_data.rs
- core/src/avm2/globals/flash/display/stage.rs
- core/src/backend/render.rs
- core/src/display_object/morph_shape.rs
- core/src/html/text_format.rs
- render/webgl/src/lib.rs
- swf/src/avm2/read.rs
- swf/src/avm2/write.rs
- swf/src/types.rs
> chore: Use from_le_bytes in more places

- core/src/avm2/activation.rs
Exact same logic as in avm1.
This speeds up avm2 core interpreter by ~2x.
> avm2: Do timeout check every 2000 actions, same as avm1

- core/src/avm1/function.rs
- core/src/avm1/object/bitmap_data.rs
- core/src/avm2/class.rs
- core/src/avm2/globals/array.rs
- core/src/avm2/globals/flash/display/movieclip.rs
- core/src/avm2/globals/flash/events/event.rs
- core/src/avm2/globals/function.rs
- core/src/avm2/object/function_object.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
- core/src/html/layout.rs
- core/src/html/text_format.rs
- core/src/xml/tree.rs
- render/canvas/src/lib.rs
- swf/src/avm1/read.rs
- swf/src/avm2/read.rs
- swf/src/read.rs
- swf/src/write.rs
This avoids unnecessary re-allocations and thus should improve performance in both memory and time terms.
> chore: Reserve capacity for vectors

- core/src/html/layout.rs
- fixes bullet and margin interaction
- fixes line heading - max font size is reset every new line
- fixes adding a bullet for every line break instead of every explicit one
Still has an issue where an additional bullet is added. Will explain more in original issue.
> core: Fixes several text edit font and bullet issues (parts of #1167)

- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
As discussed on Discord, speed up actions by running linting before tests.
> dev: check formatting before running tests

- core/src/backend/audio/decoders/adpcm.rs
The maximum possible value of delta is 63483, so it needs to be
declared as u16.
Fixes #5030
I didn't make a testcase because it seems that headless ruffle doesn't play sound, unless I'm doing something wrong.
> core: fix integer overflow in ADPCM decoder

- web/packages/extension/src/content.ts
More info at: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables
> web: Allow migration to TypeScript 4.4

- web/src/navigator.rs
I couldn't reproduce the error - managed to play the game start to end. But from the error location, it seems to be that array_buffer failed. Not to say that the player will do much with this error but at least it won't panic.
> web: check array_buffer promise result for failure (Fixes #5128 panic)

- desktop/src/main.rs
* Fix #5252 by passing `multiple_occurrences = true`.
* Remove `case_insensitive = true`.
* Reformat comments a bit.
> desktop: Refactor clap settings

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/display.rs
- core/src/avm2/globals/flash/display/bitmapdata.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/avm2/globals/flash/display/ibitmapdrawable.rs
This was easy.
This PR mainly improves hierarchy, it does not add any significant functionality.
> avm2: IBitmapDrawable stub

- web/src/audio.rs
> web: don't panic if failing to create an audio buffer

- web/packages/demo/www/index.js
> demo: Add visual indicator to file picker for dragging and dropping

- render/webgl/src/lib.rs
These logs perform somewhat expensive evaluation (crossing the Wasm-
JS boundary). So use the cheaper `log_enabled!()` macro to avoid
evaluation if the relevant log level is not enabled.
> web: Guard logs behind a `log_enabled!()` macro

- core/src/display_object/avm2_button.rs
Identified by [Kukininja](https://discord.com/channels/610531541889581066/614855396468719619/887088066341244958) on the 13th, don't want to forget about it.
> avm2: fix button typo

- core/src/avm1/activation.rs
- core/src/avm1/value.rs
Make it return `bool` instead of a `Value` that can be either `true` or `false`.
> avm1: Simplify `Value::abstract_eq`

- web/packages/extension/assets/options.html
- web/packages/extension/src/common.ts
- web/packages/extension/src/content.ts
- web/packages/extension/src/player.ts
- web/packages/extension/src/popup.ts
- web/packages/extension/src/ruffle.ts
- web/packages/extension/src/utils.ts
Depends on #5351.
Fixes #5320.
> extension: Add an option to ignore unsupported content warnings

- web/packages/extension/src/background.ts
- web/packages/extension/src/common.ts
- web/packages/extension/src/content.ts
- web/packages/extension/src/player.ts
- web/packages/extension/src/popup.ts
- web/packages/extension/src/utils.ts
See commit messages for details.
> extension: Various refactors/fixes

- core/src/avm2/globals/flash/display/sprite.rs
`Sprite`s are superclasses of `MovieClip`, so this is safe.
In the future, if we do decide to implement sprites with a less resource-intensive display object type, we can replace this code.
> avm2: Stub the `Sprite` constructor as just creating a `MovieClip`.

- swf/src/read.rs
This fixes the "failed to fill whole buffer" message and the "skip" text not displaying on
http://www.dbconsultoresdemani.com.ar/ingles/index.htm
https://www.dbconsultoresdemani.com.ar/ingles/intro.swf
> swf: Support font layout without swf7 fields

- core/src/backend/video/software.rs
I found a while ago that in this (slightly [NSFW]) file [[z0r.de/386](https://z0r.de/L/z0r-de_386.swf)] I get a whole bunch of `InvalidData` errors between frames 90 and 150, then a few more between 450 and 460.
I asked Kostya, the author of the VP6 decoder (from NihAV), and according to him, these are so-called "skip frames", with no actual data in them. And indeed, they are 0 bytes long. His advice was to simply skip them in the demuxer and keep the output frame unchanged.
The effect was already this, except that there was an error logged for each of these skip frames, and the decoder tried to seek-through all the way from the preceding keyframe when trying to decode the frames following these - until the next keyframe.
Instead, let's recognize that there is nothing to be done in these …
> video/vp6: Skip any skip frames instead of logging an error

- core/src/avm1.rs
- core/src/events.rs
- core/src/player.rs
- desktop/src/main.rs
- desktop/src/ui.rs
- web/src/ui.rs
Pulled out from #4644.
Should not cause any behavioral change.
> chore: Cleanup keys handling

- core/src/html/text_format.rs
`quick-xml` returns an `Err` for invalid attributes (e.g. unquoted).
Handle such errors by ignoring the HTML completely and return an
empty string instead, as Flash does.
Fix #5789.
> html: Handle attribute errors gracefully

- CONTRIBUTING.md
Minor grammatical fix in the contribution guide
> docs: Fix grammar in CONTRIBUTING.md

- core/src/avm2.rs
- core/src/avm2/activation.rs
- core/src/avm2/array.rs
- core/src/avm2/globals/array.rs
- core/src/avm2/globals/boolean.rs
- core/src/avm2/globals/flash/display/movieclip.rs
- core/src/avm2/globals/flash/display/shape.rs
- core/src/avm2/globals/flash/display/sprite.rs
- core/src/avm2/globals/function.rs
- core/src/avm2/globals/int.rs
- core/src/avm2/globals/number.rs
- core/src/avm2/globals/uint.rs
- core/src/avm2/globals/vector.rs
- core/src/avm2/object.rs
- core/src/avm2/object/primitive_object.rs
- core/src/avm2/slot.rs
- core/src/avm2/value.rs
This PR implements Copy for the AVM2 Value, that way we don't have to do anymore explicit clones.
> avm2: Derive Copy for Value

- core/src/avm2/script.rs
Tiny refactor; it simply doesn't make much sense for these to be hashmaps, as these are intended to be tables with known valid ID ranges and quick access. No logic was changed aside from changing storage type.
I do have ideas for bigger changes (like: maybe strings shouldn't be lazy pooled at all, and loaded eagerly instead? And pooling multinames, maybe namespaces too), but I intentionally wanted this one to be trivial to review.
This is independent from #5791.
(though I tested it on top of #5791, where it shaved a modest 5% of runtime and... 50kB of wasm size; I guess the hashmap template instantiations are heavy.)
> avm2: Use Vec instead of HashMap for loaded constants

- core/src/display_object/video.rs
This is how it's "supposed to" work, according to the docs (and common sense as well), but more experimentation is needed to determine how and why exactly Flash Player actually enables smoothing on videos.
In Flash Player, on my hand-crafted tiny test videos, this flag worked as expected; but when enabling this flag on videos in SWFs found in the wild, it did nothing, the picture stayed pixelated.
> Wire in DefineVideoStream smoothing flag to the renderer

- core/src/avm2/activation.rs
- core/src/avm2/class.rs
- core/src/avm2/method.rs
- core/src/avm2/names.rs
- core/src/avm2/script.rs
- core/src/avm2/traits.rs
- core/src/avm2/value.rs
- swf/src/avm2/types.rs
Both commits are just tiny cleanups found while investigating optimization opportunities :)
Also fixed a not-working-property `Copy` derive for `Index`.
> avm2: minor function-related cleanups

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/ui.rs
- core/src/avm2/globals/flash/ui/mouse.rs
Just another small thing that I've seen some content trip on.
> avm2: Add Mouse.hide(), Mouse.show()

- core/src/html/text_format.rs
> core: fix wide string handling in html::text_format

- core/src/backend/video/software/decoders/vp6.rs
This fixes https://github.com/ruffle-rs/ruffle/issues/5911, and most likely https://github.com/ruffle-rs/ruffle/issues/5874 as well.
The panic itself happens several frames later than the issue first appears; once the decoder gets properly confused as a result of Ruffle feeding it with data incorrectly.
I just forgot to add the skipping of the alpha offset to the preload phase, which I did do for the decode phase.
This way, most likely, all frames were reported as keyframes (since the highest bit of the most significant byte of the alpha offset is very unlikely to be `1` - no single frame in the wild should be over 2^23 bytes long encoded), so upon seeking, any necessary "frame sweeping" was not performed.
And most likely, until now, no content seeked any VP6A video in a non-sequential …
> Fix keyframe detection on Vp6WithAlpha videos

- core/src/avm1/globals/xml.rs
- core/src/avm1/globals/xml_node.rs
- core/src/avm1/object/xml_node_object.rs
- core/src/xml/document.rs
- core/src/xml/tree.rs
These are also non-functional changes, that get rid of a decent amount of code.
> xml: Cleanup (part 4)

- core/src/avm1/globals/text_format.rs
- core/src/avm1/object/text_format_object.rs
Use `text_format_mut` instead.
> avm1: Remove `TextFormatObject::set_text_format`

- core/src/backend/ui.rs
- core/src/events.rs
- core/src/player.rs
- desktop/src/main.rs
- web/src/lib.rs
This is a simplified restoration of #4644.
Fixes #4603.
> core: Handle mouse events in `InputManager`

- web/packages/demo/package.json
The switch to 8081 seems like a leftover from #5250.
Return to the default 8080.
> demo: Serve on default port

- core/src/html/text_format.rs
> core: Fix get_text_format bullet return value

- README.md
* Improve build status and Discord badges.
* Add npm and AUR badges.
> chore: Update badges in `README.md`

- core/src/html/layout.rs
Adds a boolean to check either if the line is empty and with this information not appending a bullet at the beginning of the line.
However I've reached a strange solution, where I need to verify if the text line is not empty, and if it's not, the code should not append the bullet to it, it will leave to the next line (very strange behavior) to append, this next line will be a `\n`, so will generate a empty text and then append.
I'm not confident with this fix, if @Herschel could take a look and say some thoughts about it, I would appreciate, as a rookie Rustacean, this fix maybe don't make sense on the project perspective.
Fixes #6072 
TODO:
> core: Fix bullet append from html (fix #6072)

- core/src/avm1/globals.rs
`trace` compiles to `Action::Trace` but also exists on `_global`.
```
trace(typeof _global.trace); // "function" in Flash, "undefined" in Ruffle
```
---
Here is a sample made with JPEXS: [global_trace_test.zip](https://github.com/ruffle-rs/ruffle/files/8048458/global_trace_test.zip) (includes a .fla)
It would be interesting to check in Flash Professional if:
- this actually logs anything. JPEXS outputs the traces but the Flash projector debugger doesn't write anything to "flashlog.txt".
- if the CRLF behaviour is the same as #5738 (JPEXS and the Flash projector debugger are a bit different here).
> avm1: Add `trace` to globals

- core/src/avm1/globals/sound.rs
Found this out while working on #6307.
This can also be observed when changing a line in the [avm1 sound test](https://github.com/ruffle-rs/ruffle/tree/master/tests/tests/swfs/avm1/sound):
```
var sound1 = new Sound(clip);
var sound2 = new Sound("_root.clip"); // Same as clip or /:clip
var sound3 = new Sound();
trace("sound1.setVolume(50)");
sound1.setVolume(50);
trace("sound2.getVolume(): " + sound2.getVolume()); // must trace "50"
```
> avm1: Allow strings in `new Sound(target)`

- core/src/player.rs
Fixes #5561 and actually affects a bunch of files.
This PR tries to reproduce the behaviour of Flash Player when interacting with a button:
- If the button that is pressed or released no longer exists in the next frame, update the cursor to arrow.
- In every other case, the cursor doesn't change until the user interacts with the mouse again.
For some reason, the latter behaviour is not consistent in Flash Player across the plugin and the projector: the plugin only accepts a mouse move as a new interaction while the projector also accepts a button input. This PR implements the behaviour of the projector.
There also seems to have a few unknown exceptions to the first rule, for instance in [Zed](https://uploads.ungrounded.net/89000/89118_zed.swf) (click "begin quest" then observe the …
> core: Display the appropriate mouse cursor after interacting with a button

- core/src/avm1/activation.rs
- core/src/avm1/error.rs
- core/src/avm1/function.rs
- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/globals/color.rs
- core/src/avm1/globals/display_object.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/globals/sound.rs
- core/src/display_object.rs
> avm1: Simplify `TDisplayObject::avm1_root()`

- swf/src/read.rs
Previously, the offset table and code table offset were completely
ignored. But as it seems, Flash does look into these offsets in
order to avoid exceedingly reading glyph shapes. For now, avoid
exceedingly reading empty and 1-byte glyph shapes, and add debug
assertions that verify the correctness of the offset table and code
table offset, to help diagnosing related bugs in the future.
Fixes #1560, #3115.
> swf: Add minimal offset table enforcement in `DefineFont2/3`

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/geom.rs
- core/src/avm2/globals/flash/geom/matrix.rs
This implements the `a, b, c, d, tx, ty` properties,
as well as the constructor, `identity`, and `scale` methods.
> Add initial implementation of `Matrix`

- desktop/src/main.rs
I think older Rust versions couldn't handle this, but I may be wrong.
Anyway, now it works and is more straight-forward.
> desktop: Access `App` fields directly

- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- web/Cargo.toml
Remove unused ones, sort them alphabetically and wrap to 120 columns
per line.
> web: Cleanup `web-sys` features

- core/src/avm1/object/xml_object.rs
- core/src/xml/tree.rs
Move its logic to `from_start_event`, where `XmlNode`s are created.
> xml: Inline `update_id_map`

- .github/workflows/release_nightly.yml
> chore: Forgot a `-` in the codesigning instructions

- core/src/backend/render.rs
When decoding PNG/GIF data, convert the image to premultiplied
alpha so that it plays nicely with the renderer.
This applies to both dynamically loaded images and to PNG/GIF data
embedded inside a DefineBitsJPEG tag. This is in contrast to
DefineBitsLossless and DefineBitsJPEG tags w/ alpha, which are
already premultiplied in the SWF.
Also remove unnecessary clamps now that Rust defines casts as
saturating.
Fixes #6559.
> core: Pre-multiply alpha when loading PNG/GIF data (fix #6559)

- core/src/avm2/class.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/display.rs
- core/src/avm2/globals/flash/display/nativemenuitem.rs
- core/src/avm2/globals/flash/events.rs
- core/src/avm2/globals/flash/events/contextmenuevent.rs
- core/src/avm2/globals/flash/events/ioerrorevent.rs
- core/src/avm2/globals/flash/ui.rs
- core/src/avm2/globals/flash/ui/contextmenu.rs
- core/src/avm2/globals/flash/ui/contextmenuitem.rs
These are the ones we needed for `you have to burn the rope`.
> Avm2: More class stubs

- core/src/avm2/object.rs
This
```rs
if let Some(x) = refcell.borrow().get_something() { // x is not a reference, say: just an i32
// lock is held here
refcell.borrow_mut(); // panic
}
```
behavior is a really silly footgun, we had this kind of issue several times by now :( I wonder if clippy could somehow catch this, might send them a feature request...
Anyway, this fixes the panic in https://github.com/ruffle-rs/ruffle/issues/6575 . Might also fix the panics in https://github.com/ruffle-rs/ruffle/issues/6153 and https://github.com/ruffle-rs/ruffle/issues/6311 , but I didn't test these - I'm just guessing from similar kind of error.
> avm2: Do not borrow Object's lock just to get the bound method

- core/src/backend/render.rs
> render: Implement `CMYK32` jpeg pixel format

- core/src/avm1/activation.rs
Resolves #6307.
`loadVariablesNum` currently has issues that can be observed in different ways.
---
1- With minor changes in the [avm1 loadvariablesnum test](https://github.com/ruffle-rs/ruffle/tree/master/tests/tests/swfs/avm1/loadvariablesnum):
Frame 1:
`loadVariablesNum("testvars.txt",2,"GET"); // Load variables on _level2.`
Frame 3:
```
if(this.loaded !== undefined) // This evaluates to true in Ruffle with the current builds and traces unexpected values.
{
trace("this.loaded !== undefined");
trace(this.loaded); // "Hurray"
trace(_root.loaded); // "Hurray"
trace(_level0.loaded); // "Hurray"
trace(_level2.loaded); // undefined
stop();
}
else if(_level2.loaded !== undefined) // Instead this should run and traces the following values.
{
trace("_level2.loaded !== undefined"); …
```
> avm1: Fix `loadVariablesNum` / `Action::GetUrl2`

- core/src/loader.rs
- core/src/player.rs
- desktop/src/main.rs
- exporter/src/main.rs
- scanner/src/execute.rs
- tests/tests/regression_tests.rs
- web/src/lib.rs
Move the `Arc::new` to within the function.
> core: Change `Player::set_root_movie` to accept a `SwfMovie`

- desktop/src/navigator.rs
Unify the sandboxed and non-sandboxed cases.
> desktop: De-duplicate file reading code

- .github/workflows/test_rust.yml
- core/src/backend/audio/decoders/mp3.rs
- web/src/lib.rs
Run clippy with all features enabled to ensure that every feature compiles and avoid rot.
> ci: Run clippy with all features

- core/src/avm1/globals.rs
- core/src/avm1/globals/accessibility.rs
Trying to fill out the remaining missing AVM1 classes. Stub out AVM1 `Accessibility` class.
> avm1: Add Accessibility stub

- core/src/backend/render.rs
PNGs with 16-bit samples were not being normalized to 8-bit, screwing up their
appearance.
Add the `STRIP_16` transformation using `Transformations::normalize_to_color8()`,
which is equivalent to `Transformations::EXPAND | Transformations::STRIP_16`.
Also warn in case `png` outputs a color type other than `Rgb` and `Rgba`.
Due to the `EXPAND` transformation, this may be only `Grayscale` or
`GrayscaleAlpha`. `Indexed` is converted to either `Rgb` or `Rgba`.
Fixes #6662.
> render: Strip 16-bit PNG samples to 8-bit

- core/src/avm1/function.rs
- core/src/avm1/object.rs
- core/src/avm1/object/array_object.rs
- core/src/avm1/object/custom_object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm1/object/xml_attributes_object.rs
- core/src/avm1/value.rs
It can be simply determined in `Value::type_of`.
> avm1: Remove `TObject::type_of`

- desktop/src/executor.rs
It became stable on Rust 1.60.0.
> desktop: Use `Arc::new_cyclic`

- core/src/avm1/globals.rs
- core/src/avm1/globals/local_connection.rs
This fixes the sitelock on https://www.bubblebox.com/play/3326/flood-runner-4.htm .
I didn't test it on https://github.com/ruffle-rs/ruffle/issues/6227 or https://github.com/ruffle-rs/ruffle/issues/988, because in my understanding it'd need to be hosted on original domain for this to work. (unless they are hosted and I just didn't notice?) So feel free to give me more links to test if you know any.
> avm1: Implement LocalConnection.domain()

- core/src/avm1/globals/array.rs
> avm1: Remove a stale TODO

- web/packages/demo/www/index.css
- web/packages/demo/www/index.html
- web/packages/demo/www/index.js
> demo: Style the local file selector and sample file select

- core/src/backend/render.rs
Flash Player seems to zero out 0% alpha pixels in a DefineBitsJPEG3 tag, ensuring they are invisible even if the image is not correctly using pre-multiplied alpha.
Fixes #6893.
I'll try to verify this behavior a little more thoroughly later tonight -- I'm wondering if DefineBitsLossless tag does this as well.
> core: Clamp color values in DefineBitsJPEG3 tags (fix #6893)

- core/src/avm1/activation.rs
> avm1: Tiny cleanup in `Activation::set_target`

- web/packages/demo/www/index.css
- web/packages/demo/www/index.html
> demo: Fix styling on mobile devices

- core/src/display_object/movie_clip.rs
- swf/src/read.rs
Where possible, return the specific data type instead of the generic
`Tag` type. Most reader methods do this already, so this brings the
rest in-line.
> swf: Return concrete data types in `Reader` methods

- core/src/backend/navigator.rs
- core/src/tag_utils.rs
Fix warnings caused by desktop-only code.
> web: Fix some warnings

- core/src/avm2/globals/flash/text/textfield.rs
- core/src/avm2/globals/string.rs
This is relied on by SteamBirds
(https://www.kongregate.com/games/weasello/steambirds)
> Define `String.fromCharCode` as both a public and AS3 method

- core/src/avm1/globals/movie_clip.rs
- core/src/avm2/globals/flash/display/stage.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/stage.rs
- core/src/html/layout.rs
- render/common_tess/src/lib.rs
- swf/src/types.rs
And use them where possible, to improve code readability.
> swf: Introduce `Color::BLACK` and `Color::WHITE`

- render/canvas/src/lib.rs
* Remove the hack to work around Firefox incorrectly managing `feColorMatrix` filter that we use for color transforms. This seems to have been fixed in Firefox and no longer necessary (#38).
* Remove no longer used `pixelated_property_value`.
> canvas: Remove Firefox color transform hacks

- core/src/player.rs
An attempt at fixing [Bubble Bees](http://www.ferryhalim.com/orisinal/g2/bubble.htm) and [Bungee Bear](http://www.ferryhalim.com/orisinal/g2/bear.htm).
Mouse inputs (left clicks) often don't work as expected in these games. This is because interactions rely on a button that is part of a draggable object. In Flash Player, the button always remains clickable even if the mouse cursor doesn't hover the button. In Ruffle, the button is only clickable if the mouse cursor hovers the button (this is easy to notice as the cursor flashes between states of arrow and pointer). This PR tries to fix this behavior.
Here are some [edited files](https://github.com/ruffle-rs/ruffle/files/8690795/bbee.zip) I used for testing.
> avm1: Make draggable buttons always clickable

- core/src/display_object/movie_clip.rs
In several places, we read some data from a tag, and then pass
the original tag length to `resize_to_reader`. This is incorrect -
the provided length is used an an offset from the current position
in the reader, so we will extend past the end of the current tag if
we've already read some bytes.
In practice, this doesn't appear to cause any problems - AVM bytecode
has internal length fields, which end up ensuring that we will never
try to read past where the slice *should* end. However, if a `DoAbc`
tag is the last tag in the file, then we'll end up trying to use
`resize_to_reader` with an offset past the end of the movie.
This commit subtracts the number of already-read bytes from `tag_len`,
to ensure that we always construct a correctly-sized `SwfSlice`
> Correctly calculate the length passed to `resize_to_reader`

- web/packages/core/src/ruffle-player.ts
Replace it with "Update Ruffle" instead. This could be useful in the future (eg. when AVM2 support lands) considering we still have bug reports from builds released in January 2021 which are likely duplicates or already fixed issues. I set up the limit to 6 months but this could be lowered.
Bonus: Also displays whether the browser/device has touch support to make the distinction between iPad and Mac easier ([User Agent in Safari on iPadOS](https://developer.apple.com/forums/thread/119186)).
> web: Disable "Report bug" link if build is outdated

- desktop/src/custom_event.rs
- desktop/src/main.rs
Use `Player::fetch_root_movie` for loading the root movie, as an
early preparation for chunked loading.
> desktop: Fetch root movie asynchronously

- swf/src/read.rs
Fixes #7098
Some SWF appear to have a PlaceObject3 tag with
`HAS_CACHE_AS_BITMAP` set, but the tag ends without
including the corresponding 'is_bitmap_cached' byte.
> swf: Handle incorrect 'PlaceObject3' tag

- CONTRIBUTING.md
Make some general adjustments, and better document how to compile
ActionScript tests.
> docs: Improve `CONTRIBUTING.md`

- core/src/avm1/activation.rs
- core/src/avm1/globals/load_vars.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/globals/xml.rs
- core/src/avm2/globals/flash/net/url_loader.rs
- core/src/backend/navigator.rs
- core/src/loader.rs
- core/src/player.rs
- desktop/src/main.rs
- desktop/src/navigator.rs
- web/src/lib.rs
- web/src/navigator.rs
Which holds both a URL and what was `RequestOptions` formerly.
> core: Introduce `Request`

- core/src/avm2.rs
- core/src/avm2/activation.rs
- core/src/avm2/method.rs
> avm2: Inline `Activation::run_stack_frame_for_script`

- render/wgpu/src/pipelines.rs
It is essentially a unification of `create_color_pipeline`, `create_bitmap_pipeline`
and `create_gradient_pipeline`.
> wgpu: Introduce `create_shape_pipeline`

- core/src/backend/audio.rs
- core/src/backend/audio/mixer.rs
This fixes the panic on https://www.newgrounds.com/portal/view/579233/format/flash?emulate=flash
> audio: Avoid panic with supposed MP3s that are too small

- core/src/avm2/globals/flash/display/loaderinfo.rs
- core/src/avm2/globals/flash/display/shape.rs
- core/src/avm2/globals/flash/text/textfield.rs
- core/src/context.rs
- core/src/display_object.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/bitmap.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/stage.rs
- core/src/display_object/video.rs
- core/src/lib.rs
- core/src/library.rs
- core/src/player.rs
- core/src/tag_utils.rs
- core/src/vminterface.rs
- exporter/src/main.rs
Simply use `is_action_script_3()` instead.
> core: Remove `AvmType`

- Cargo.lock
- swf/Cargo.toml
- swf/README.md
Bump and publish new version of `swf` crate.
> swf: Bump version 0.2

- core/src/avm2/globals/flash/display/displayobjectcontainer.rs
- core/src/avm2/globals/flash/filters/BlurFilter.as
- core/src/avm2/globals/flash/text/textfield.rs
This gets Solarmax to the main level select screen
(once BitmapData.draw support is added)
> Miscellaneous stubs

- core/build_playerglobal/src/lib.rs
Not having java installed is a pretty common reason compiling fails for people, and the error message isn't very helpful. This PR just makes the error message more helpful.
> core: Add better error message when java could not be found

- core/src/avm1/globals/movie_clip.rs
- core/src/avm2/globals/flash/display/displayobject.rs
- core/src/display_object.rs
- swf/src/types/twips.rs
The core functionality and AVM2 bindings were implemented in #7739.
> avm1: Implement `MovieClip.scrollRect`

- swf/src/read.rs
Differentiate between the cases using a new `has_alpha` boolean
parameter.
> swf: Merge `read_color_transform_no_alpha` into `read_color_transform`

- core/src/avm2/activation.rs
We already have `&mut self` available whenever we write to it,
and we never made use of the `Clone` impl. As far as I can tell,
we don't have any unimplemented features that would require a `GcCell`.
> avm2: Remove `GcCell` from `local_registers`

- core/src/avm1/globals/text_field.rs
- core/src/avm2/globals/flash/text/textfield.rs
- core/src/display_object/edit_text.rs
> text: Store background and border colors as `swf::Color`

- render/webgl/src/lib.rs
`width` and `height` are already stored in `Bitmap`, so simply use a `WebGlTexture` directly.
> webgl: Remove `Texture` wrapper

- core/src/display_object/bitmap.rs
We now have a `MutationContext` available, so this doesn't need to be done in `run_frame`
> core: Update dirty BitmapData before rendering

- core/src/avm1/value.rs
Use `Value::to_primitive` instead.
> avm1: Remove `Value::to_primitive_num`

- swf/src/read.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/3365 , https://github.com/ruffle-rs/ruffle/issues/8156 .
> swf: treat empty gradients as solid black color

- core/src/avm2/globals/flash/display/graphics.rs
This is needed by Pixel Legions
> avm2: Stub Graphics.beginBitmapFill

- render/webgl/src/lib.rs
As @adrian17 and others discussed in discord, webgl leaks vertex array and buffers on replace_shape. I think his pull request should deal with that and hopefully make us see less UnableToCreateVAO crashes.
> webgl: vertex array, buffer and texture cleanup

- swf/src/types.rs
- swf/src/types/bevel_filter.rs
- swf/src/types/blur_filter.rs
- swf/src/types/color_matrix_filter.rs
- swf/src/types/convolution_filter.rs
- swf/src/types/drop_shadow_filter.rs
- swf/src/types/glow_filter.rs
- swf/src/types/gradient_bevel_filter.rs
- swf/src/types/gradient_glow_filter.rs
> swf: Extract filters to separate files

- render/webgl/src/lib.rs
Previously, we were ignoring changes to the scale factor.
> webgl: Update 'viewport_scale_factor' field

- desktop/src/navigator.rs
Fix #8315 by changing Desktop Fetch to use "/" with relative URL's (without a base) to emulate flash.
> Fix #8315 by checking for relative URL without a base

- core/src/avm2/globals/flash/display/displayobject.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/8311 .
Same getRect limitations as in AVM1, see comment.
Also I noticed that well... FP behaves weirdly when we call various method including `getBounds` on DOs with no inner content; pretty sure we don't replicate this weirdness correctly. But given it's a general DO issue and not specific to AVM2, it's not in scope here.
> avm2: Support DO.getBounds, (partial) getRect

- web/packages/core/src/js-polyfills.ts
> web: Add `has` and `ownKeys` methods to the `Reflect` polyfill

- core/src/avm1/globals/array.rs
Avoided code duplication in avm1 array.rs as asked
I learned rust for this project so I hope everything is working as expected.
no tests failed with cargo test --all.
> avm1: Avoid code duplication in Array.splice

- web/packages/extension/assets/_locales/it/messages.json
translates messages.json for the localization in Italian language
> add italian localization to the browser extension

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
Reverts ruffle-rs/ruffle#8666
Attempt to fix CI failures.
> Revert "ci: Upgrade Node 12 actions workflows"

- core/src/avm2/globals/flash/text/textfield.rs
Reverts ruffle-rs/ruffle#8649
Attempt to fix CI failures.
> Revert "avm2: Implement `TextField` scrolling parameters"

- .github/workflows/release_nightly.yml
- .github/workflows/test_rust.yml
- .github/workflows/test_web.yml
~~Don't merge yet. I'll give it a week or until a different source is found for the CI issues. If the CI issues clear by themselves, I'll close this PR and introduce each commit as its own PR one at a time to more accurately check which one breaks CI and fix it.~~
~~If they don't clear on their own in a week, I'll assume they're unrelated and this is safe to merge.~~
Now also fixes CI by disabling the Linux image tests.
> ci: Upgrade Node 12 actions workflows

- web/packages/extension/assets/_locales/zh_TW/messages.json
> extension: add traditional-chinese localization

- web/packages/extension/assets/_locales/zh_TW/messages.json
> extension: Add warn_on_unsupported_content translate in zh_TW

- core/src/avm2/globals/flash/net/sharedobject.rs
> avm2: Stub SharedObject.close

- web/packages/core/src/build-info.ts
- web/packages/core/src/index.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/source-api.ts
- web/packages/extension/assets/css/popup.css
- web/packages/extension/assets/popup.html
- web/packages/extension/src/popup.ts
Change the compile time "macros" such as `%VERSION_NUMBER%` to be contained in only one file `build-info.ts`.
Closes #8021
> web: Add version number requested in #8021

- core/src/avm2/globals/flash/net/sharedobject.rs
Gets [Accurate Slapshot](http://www.notdoppler.com/accurateslapshot.php) and [Track the Ball](http://www.notdoppler.com/tracktheball.php) loading to the main menu.
> avm2: Stub SharedObject.clear and SharedObject.size

- core/src/display_object/movie_clip.rs
Currently, the `LoaderInfo` `init` event can fire too early in AVM2 movies. This PR fixes this by delaying setting the `INITIALIZED` flag until we finish constructing the first frame for the first time.
According to the AS3 documentation, LoaderInfo is not supposed to fire `init` until after the first frame has constructed and its frame scripts have run. However, we reused the `INITIALIZED` flag from AVM1; checking every `exitFrame` to see if we need to fire `init` based on that flag. Because `run_frame` does *not* check `frames_loaded` (that's done later, in `run_frame_internal`), it always sets `INITIALIZED` regardless of if frame 1 has actually run - which causes the premature `init` event.
While we do also send AVM1 `onLoad` events too early as well, I don't believe you can actually …
> core: Don't fire init events on AVM2 until the first `frameConstructed` event

- README.md
See https://github.com/badges/shields/issues/8671
> docs: Update badge URLs in README

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/utils/Proxy.as
- core/src/avm2/globals/flash/utils/proxy.rs
- core/src/avm2/globals/globals.as
Also realized that isAttribute is supposed to be implemented - doesn't matter until we get XML<->AVM2 integration in.
> avm2: Convert Proxy to AS3

- web/packages/core/src/ruffle-player.ts
Selfhosted builds of Ruffle will now detect CORS errors when loading Ruffle files or SWF files, and direct webmasters to the appropriate FAQ entry (which I just created).
This commit also updates the download link for the Ruffle desktop app to point to the Ruffle website.
> web: Add CORS panic error message with FAQ link

- core/src/avm2/globals/flash/display/Loader.as
Stub `flash.display.Loader.unload`.
> Stub flash.display.Loader.unload

- render/canvas/src/lib.rs
- render/src/commands.rs
- render/webgl/src/lib.rs
The wgpu backend no longer needs this.
> Remove lifetime parameter from CommandHandler

- web/package-lock.json
- web/package.json
- web/packages/selfhosted/package.json
Cherry-pick #9002, #9003, #9004, plus update the remaining `wdio` dependencies in a single commit, since they require each other.
> web: Bump dependencies

- core/src/avm1/activation.rs
- core/src/avm1/globals/bitmap_data.rs
- core/src/avm1/globals/local_connection.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm1/globals/movie_clip_loader.rs
- core/src/avm1/globals/object.rs
- core/src/avm1/globals/shared_object.rs
- core/src/avm1/globals/sound.rs
- core/src/avm1/globals/text_format.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm2/globals/flash/display/loader.rs
- core/src/avm2/globals/flash/net/shared_object.rs
- core/src/backend/audio.rs
- core/src/display_object.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/avm2_button.rs
- core/src/display_object/bitmap.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/graphic.rs
- core/src/display_object/loader_display.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/stage.rs
- core/src/display_object/text.rs
- core/src/display_object/video.rs
- core/src/loader.rs
- core/src/player.rs
This removes a bunch of unwraps!
> core: Drop Option<> from TDisplayObject::movie()

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/avm1/function.rs
- core/src/avm2/function.rs
- core/src/avm2/scope.rs
- core/src/player.rs
- render/Cargo.toml
- render/canvas/Cargo.toml
- render/webgl/Cargo.toml
- render/wgpu/Cargo.toml
This required small changes to some Debug impls that were missed in #8964.
> Bump `gc-arena` to current master, take 2

- render/wgpu/src/buffer_pool.rs
This should hopefully workaround the buffer bug issue, yet again, whilst push constants are in use.
> wgpu: Keep globals cache across the buffer pool

- render/src/utils.rs
1) Previously we were removing the first occurrence of the invalid 0xFFD9FFD8 byte sequence in JPEG data, but this would break the JPEG if it happened to contain this byte sequence elsewhere (for example, EXIF data). Instead, properly parse the JPEG markers searching for the invalid marker sequence. Fixes #8775.
2) Sometimes JPEGs can be lacking the final 0xFFD9 EOI marker that marks the end of the image. I suspect some JPEG optimizers might remove this to save a few bytes. Flash and most JPEG viewers still display this, but `jpeg-decoder` errors. Glue on the EOI marker if its missing to convince `jpeg-decoder` to decode these cases. Fixes #4209.
> core: Fix handling of some invalid JPEG data (fix #4209, #8775)

- .github/workflows/release_nightly.yml
Does it work? That's a great question and I'm glad you asked.
> ci: Change activity check to something less error prone possibly

- .github/workflows/release_nightly.yml
Reverts ruffle-rs/ruffle#9208
Applies new fix
> ci: Revert nightly fix

- core/src/avm2/globals/flash/text/textfield.rs
Allows some Papa games to move to character selection
> avm2: added TextField.restrict stub

- core/src/avm2/globals/flash/display/stage.rs
Fracuum is playable thanks to Stage.fullScreenSourceRect Stub
> avm2: added Stage.fullScreenSourceRect stub

- scanner/src/analyze.rs
> reduce some indents.

- Cargo.lock
- Cargo.toml
- exporter/src/main.rs
- render/naga-agal/Cargo.toml
- render/wgpu/Cargo.toml
- render/wgpu/shaders/bitmap.wgsl
- render/wgpu/shaders/common.wgsl
- render/wgpu/shaders/copy.wgsl
- render/wgpu/shaders/copy_srgb.wgsl
- render/wgpu/shaders/gradient/common.wgsl
- render/wgpu/shaders/gradient/mode/focal.wgsl
- render/wgpu/shaders/gradient/mode/linear.wgsl
- render/wgpu/shaders/gradient/mode/radial.wgsl
- render/wgpu/src/backend.rs
- render/wgpu/src/buffer_pool.rs
- render/wgpu/src/context3d/mod.rs
- render/wgpu/src/shaders.rs
- render/wgpu/src/target.rs
- tests/tests/regression_tests.rs
We're relying on unreleased changes, so we depend on the latest commit from their repository.
> Move back to upstream wgpu repository

- core/src/avm2/globals/flash/events/MouseEvent.as
Basically a direct copy of https://github.com/ruffle-rs/ruffle/pull/7653
Edit: Fixes an issue with http://new.weedtowonder.org/ (see https://github.com/ruffle-rs/ruffle/issues/8006)
> avm2: Stub MouseEvent.updateAfterEvent

- core/src/avm2/globals/flash/display/displayobject.rs
> Stub opaque background for DisplayObject.

- Cargo.lock
- core/build.rs
- core/build_playerglobal/Cargo.toml
- core/build_playerglobal/src/lib.rs
- core/build_playerglobal/src/main.rs
- core/src/avm2/globals.rs
- core/src/avm2/globals/__ruffle__/logging.as
- core/src/avm2/globals/flash/display/Loader.as
- core/src/avm2/globals/flash/events/MouseEvent.as
- core/src/avm2/globals/flash/events/TimerEvent.as
- core/src/avm2/globals/flash/net.as
- core/src/avm2/globals/flash/net/FileReference.as
- core/src/avm2/globals/flash/net/FileReferenceList.as
- core/src/avm2/globals/flash/net/LocalConnection.as
- core/src/avm2/globals/flash/net/URLRequest.as
- core/src/avm2/globals/flash/utils/Dictionary.as
- core/src/avm2/globals/toplevel.rs
- core/src/avm2/stubs.rs
- core/src/stub.rs
@Bale001 wanted to look into using metadata for this but until then here's a direct approach!
> The Great Restubbening - part 2: Actionscript

- core/src/config.rs
- desktop/src/main.rs
> desktop: Add --letterbox option

- core/build_playerglobal/src/lib.rs
- core/src/avm2.rs
- core/src/avm2/globals.rs
- core/src/display_object/movie_clip.rs
- swf/src/avm2/read.rs
- swf/src/read.rs
- swf/src/tag_code.rs
- swf/src/types.rs
- swf/src/write.rs
No test, was too hard to construct 😅
> Support older DoAbc tag (72)

- desktop/src/main.rs
> desktop: Support flashvars passed via URL parameters

- desktop/src/main.rs
Addresses https://github.com/ruffle-rs/ruffle/issues/9571#issuecomment-1430122594
> desktop: Support `file` URLs

- .github/workflows/release_nightly.yml
Use a GitHub output parameter, rather than an environment variable, as described in:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Refactor activity check

- core/src/avm2/globals/flash/display/Loader.as
Stubs flash.display.Loader.close.
> Stub Loader.close

- .github/workflows/release_nightly.yml
> web: Use the CORRECT extension ID in the version seal

- core/src/avm2/globals/flash/system/System.as
This progresses Papas Scooperia
Now almost all Papas games have the same issue - https://github.com/ruffle-rs/ruffle/issues/9539
> Stub System.pauseForGCIfCollectionImminent

- web/packages/core/src/ruffle-player.ts
Supersedes https://github.com/ruffle-rs/ruffle/pull/9575
> web: Allow context menu to work on iOS using PointerEvents

- core/src/avm2/globals/flash/system/Capabilities.as
These are needed by Steambirds: Survival
> avm2: Stub Capabilities.manufacturer and Capabilities.language

- core/src/avm2/globals/flash/media/soundmixer.rs
This results in 128 times fewer calls to the builtin `cosf` function.
While this is still the most naive implementation with two simple nested loops (so no recursive Cooley-Tukey-style `N*log(N)` complexity[^1]), and it does not even seem to autovectorize much; the main bottleneck was the `cos` computation, not the number of multiplications.
The recently added unit test still passes of course, as there was no meaningful change made to the main algorithm itself.
The improved performance can be seen best on web, with these loops:
- https://z0r.de/L/z0r-de_7812.swf
- https://z0r.de/L/z0r-de_7855.swf
For example, z0r 7812 before:
And after:
[^1]: https://www.youtube.com/watch?v=nmgFG7PUHfo
> avm2: Use a lookup table for cosine in `SoundMixer.computeSpectrum()`

- desktop/src/main.rs
Closes #9346 
My first PR, so any comments, suggestions, etc. are appreciated.
> desktop: min and max window size for ruffle

- web/packages/extension/assets/_locales/ja/messages.json
Japanese translation files have been updated.
> i18n: Update Japanese locale files

- core/src/avm2/globals/flash/profiler.as
- core/src/avm2/globals/globals.as
Progresses Transformice (#8937), which now needs `StyleSheet`.
> avm2: Stub flash.profiler.showRedrawRegions

- web/packages/extension/assets/_locales/en/messages.json
- web/packages/extension/assets/_locales/ja/messages.json
Added translation of settings screen(en/ja)
> i18n: Added translation of settings screen

- desktop/src/main.rs
As suggested, use `WindowEvent::ModifiersChanged` instead.
> desktop: Avoid deprecated `KeyboardInput::modifiers`

- core/src/avm2/globals/flash/text/TextField.as
- core/src/avm2/globals/flash/text/text_field.rs
> avm2: Stub TextField.condenseWhite

- core/src/avm2/globals/flash/system/Capabilities.as
- core/src/avm2/globals/flash/system/System.as
These are needed for Solarmax 2
> avm2: Implement Capabilities.isDebugger and stub System.disposeXML

- desktop/src/main.rs
This was being completely ignored
> desktop: Actually use 'quality' flag

- core/src/avm2/globals/flash/display/BitmapData.as
- core/src/avm2/globals/flash/display/bitmap_data.rs
This progresses Kingdom Rush (after #9894). It doesn't actually need it implemented.
> avm2: Stub BitmapData.hitTest

- core/src/avm2/globals/flash/concurrent/Mutex.as
I missed this property because it isn't in the AS3 docs
> avm2: Add Mutex.isSupported property

- web/packages/extension/tools/sign_xpi.js
> web: Fix copy-pasted code that breaks in sign_xpi.js

- core/src/avm2/globals/flash/display/Stage.as
- core/src/avm2/globals/flash/display/stage.rs
> avm2: Stub Stage.fullScreenWidth and fullScreenHeight

- core/src/avm2/activation.rs
- core/src/avm2/method.rs
The `Option<GcCell<'gc, Option<ClassObject<'gc>>>>,` is kinda silly yeah.
Long term we'll need more mutability for 1. parameter types, 2. bytecode optimization, so this'll be refactored anyway.
(And well long term this class should be created at load time, mostly not lazily)
For a microbenchmark:
```
function f(x){
var a, b, c, d, e;
if (x == 1) { // never true, but the `newactivation` opcode is run on function entry
var f = function(){} // never runs
f();        
}
}
// repeatedly called:
f(0);
```
On FF speeds up 4x, on Chrome 8x (???).
(for the record, recreating the class was like ~8% of time in `road of the dead`)
> avm2: Store the activation class on method

- Cargo.lock
- core/Cargo.toml
- core/src/avm2/regexp.rs
> core: Update regress to version 0.5

- core/src/avm2/globals/flash/display/Loader.as
This gets 400 Years (#8752) into gameplay (after some upcoming PRs are merged).
> avm2: Stub Loader.unloadAndStop

- core/src/avm2/globals/flash/display/BitmapData.as
- core/src/avm2/globals/flash/display3D/Context3D.as
These are needed by Fancy Pants World 4
> avm2: Stub generateFilterRect, setStencilReferenceValue, and setSamplerStateAt

- core/src/avm2/globals/flash/text/TextFormat.as
- core/src/avm2/globals/flash/text/TextFormatDisplay.as
- core/src/avm2/globals/flash/text/text_format.rs
- core/src/avm2/globals/globals.as
Along with #10044, this gets [Atomic Puzzle 2](http://www.notdoppler.com/atomicpuzzle2.php) into the first level.
> avm2: Add TextFormatDisplay class and stub TextFormat.display property

- core/src/avm2/globals/string.rs
All of these methods need to exist on `String.prototype`
> avm2: Implement String.prototype methods + valueOf

- web/src/audio.rs
This is meant to address #10067.
> web/audio: Add a warmup period before increasing buffer size

- core/src/avm2/globals/flash/display/bitmap.rs
- core/src/avm2/globals/flash/display/display_object.rs
- core/src/avm2/globals/flash/display/display_object_container.rs
- core/src/avm2/globals/flash/display/graphics.rs
- core/src/avm2/globals/flash/display/interactive_object.rs
- core/src/avm2/globals/flash/display/simple_button.rs
- core/src/avm2/globals/flash/display/sprite.rs
- core/src/avm2/globals/flash/display3D/context_3d.rs
- core/src/avm2/globals/flash/display3D/index_buffer_3d.rs
- core/src/avm2/globals/flash/display3D/vertex_buffer_3d.rs
- core/src/avm2/globals/flash/events/event_dispatcher.rs
- core/src/avm2/globals/flash/text/font.rs
- core/src/avm2/globals/flash/text/text_field.rs
Just a few classes for now, taking advantage of the new ParametersExt
> Simplify parameter usage in bitmap, display_object, graphics & others

- core/src/avm2/globals/flash/display/DisplayObject.as
- core/src/avm2/globals/flash/display/Stage.as
> avm2: Stub DisplayObject.accessibilityProperties

- Cargo.lock
- video/software/Cargo.toml
To _actually_ fix #10117 via https://github.com/ruffle-rs/h263-rs/pull/48.
> chore: Bump h263-rs

- core/src/avm2/globals/flash/net.as
> avm2: Stub flash.net.sendToURL

- core/src/avm2/globals/flash/text/TextField.as
- core/src/avm2/globals/flash/text/text_field.rs
> avm2: Stub TextField.mouseWheelEnabled

- core/src/avm2.rs
- core/src/avm2/activation.rs
- core/src/avm2/error.rs
- core/src/avm2/events.rs
- core/src/display_object/movie_clip.rs
- core/src/external.rs
- core/src/timer.rs
Split off from https://github.com/ruffle-rs/ruffle/pull/9402
> Log full avm2 errors when they fall through root level activations

- core/src/avm2/globals/flash/xml/XMLDocument.as
- core/src/avm2/globals/flash/xml/XMLNode.as
- core/src/avm2/globals/flash/xml/XMLNodeType.as
- core/src/avm2/globals/globals.as
Stubs the `flash.xml` package.
> avm2: Stub legacy XML

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm2/globals/flash/display/bitmap_data.rs
- core/src/bitmap/bitmap_data.rs
Mostly avoiding repeat dirty state handling & bounds checks for tight loops
> Bunch of BitmapData optimisations

- core/src/avm2/globals/flash/ui/Mouse.as
Volt Connect 2 looks fully playable
https://github.com/ruffle-rs/ruffle/issues/8769
> avm2: Stub Mouse.registerCursor and Mouse.unregisterCursor

- core/src/avm2/activation.rs
> avm2: Make `resolve_parameters` throw an AVM error

- .github/workflows/test_web.yml
- exporter/src/main.rs
- render/wgpu/src/backend.rs
- render/wgpu/src/utils.rs
- tests/tests/util/runner.rs
- web/packages/core/package.json
As suggested in https://github.com/ruffle-rs/ruffle/pull/6935#pullrequestreview-967181111.
> ci: Deny warnings on Web

- core/src/display_object.rs
> chore: fix typo in display_object.rs

- core/src/font.rs
- render/canvas/src/lib.rs
- render/src/backend.rs
- render/src/backend/null.rs
- render/webgl/src/lib.rs
- render/wgpu/src/backend.rs
Use just `RenderBackend::register_shape` instead.
> render: Remove `RenderBackend::register_glyph_shape`

- core/src/avm2/globals/flash/net/XMLSocket.as
- core/src/avm2/globals/globals.as
There is a draft PR #8188 for a real implementation, but in the meantime the stubbed version is useful for Coaster Racer and maybe other games using FlashConnect.
> avm2: Stub flash.net.XMLSocket

- core/src/avm2/globals/flash/display/BitmapData.as
- core/src/avm2/globals/flash/display/bitmap_data.rs
Oh hi there.
This is my humble attempt to start contributing to your wonderful project. Saw some bug report in your Discord and decided to try to fix for it. `BitmapData.paletteMap()` is already implemented for AVM1, so my work was to copy-paste all the stuff and make it actually work. I hope that'll do!
> Add AS3 implementation of BitmapData.paletteMap

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm2/globals/flash/display/bitmap_data.rs
- core/src/bitmap/operations.rs
This should be faster than doing it manually, in theory
> Use actual clone() method to clone BitmapDatas

- core/src/avm2/e4x.rs
When we were using a fork of quick-xml, we modified the actual unescape method. Now that we're using the crates.io release again, we need to go through our `custom_unescape` function.
> avm2: Use custom_unescape wherever we unescape XML

- core/src/avm2/globals/flash/security/X500DistinguishedName.as
- core/src/avm2/globals/flash/security/X509Certificate.as
- core/src/avm2/globals/globals.as
> avm2: Add X509 certificate classes

- core/src/avm2/globals/flash/media/sound.rs
With this we get #10377 playable.
> avm2: Improve the Sound::extract stub

- web/src/lib.rs
Cuts down on some needless verbosity.
> web: Use serde rename_all rule

- web/packages/core/src/plugin-polyfill.ts
This should fix #10037 (at least, for cloudflare protection).
> web: Avoid triggering cloudflare checks

- web/packages/extension/assets/_locales/zh_CN/messages.json
Extension: Update simplified Chinese translation
Signed-off-by: yangyangdaji <1504305527@qq.com>
Co-authored-by: ForeverInfinity <79129834+ForeverInfinity@users.noreply.github.com>
Resolve https://github.com/ruffle-rs/ruffle/pull/10548#discussion_r1157055143
Close https://github.com/ruffle-rs/ruffle/pull/10548
> Extension: Update simplified Chinese translation

- web/package-lock.json
- web/packages/extension/.eslintrc.yaml
- web/packages/extension/jsconfig.json
- web/packages/extension/package.json
- web/packages/extension/tools/.eslintrc.yaml
- web/packages/extension/tools/package.json
- web/packages/extension/tools/sign_xpi.js
- web/packages/extension/tools/zip.js
- web/packages/extension/webpack.config.js
This would have caught #10351.
> extension: Check tools using TypeScript

- .github/workflows/release_amo.yml
This may or may not work depending on how the underlying Action deals with environment variables, or doesn't.
> web: When building the extension, provide the GitHub token to GitHub CLI

- core/src/display_object/edit_text.rs
Addresses https://github.com/ruffle-rs/ruffle/pull/10533#issuecomment-1505970692
> core: Allow focusing selectable EditText fields

- core/src/avm2/globals/flash/text/TextField.as
This allows #2666 to finish loading.
> avm2: Stub TextField.useRichTextClipboard

- core/src/avm2/globals/flash/display/Stage.as
> avm2: nit: stageWidth/Height should be of int type

- web/packages/demo/www/index.js
> demo: Use forceScale option

- web/packages/extension/assets/_locales/zh_CN/messages.json
Extension: Update Translate (Chinese Simplified)
>  Extension: Update Translate (Chinese Simplified)

- core/src/avm2/globals/flash/display/display_object_container.rs
This progresses #9211 after #10694.
Fixes #10291.
> avm2: Throw AVM error for validate_remove_operation in DisplayObjectContainer.

- core/src/avm2/object.rs
- core/src/avm2/object/array_object.rs
- core/src/avm2/object/bitmapdata_object.rs
- core/src/avm2/object/bytearray_object.rs
- core/src/avm2/object/class_object.rs
- core/src/avm2/object/context3d_object.rs
- core/src/avm2/object/domain_object.rs
- core/src/avm2/object/index_buffer_3d_object.rs
- core/src/avm2/object/loaderinfo_object.rs
- core/src/avm2/object/namespace_object.rs
- core/src/avm2/object/primitive_object.rs
- core/src/avm2/object/program_3d_object.rs
- core/src/avm2/object/qname_object.rs
- core/src/avm2/object/regexp_object.rs
- core/src/avm2/object/soundchannel_object.rs
- core/src/avm2/object/stage_object.rs
- core/src/avm2/object/textformat_object.rs
- core/src/avm2/object/texture_object.rs
- core/src/avm2/object/vector_object.rs
- core/src/avm2/object/vertex_buffer_3d_object.rs
- core/src/avm2/script.rs
> avm2: Make TObject.install_instance_slots take a MutationContext

- web/packages/core/src/ruffle-player.ts
> web: No context menu on iOS if finger moves too far on long-press

- core/src/display_object/avm1_button.rs
Instead of manually shifting bits.
> core: Use `BitFlags::iter`

- desktop/src/navigator.rs
> desktop: Handle relative URLs in navigate_to_url

- CONTRIBUTING.md
- README.md
- crowdin.yml
- web/packages/extension/assets/_locales/fr/messages.json
- web/packages/extension/assets/_locales/ja/messages.json
- web/packages/extension/assets/_locales/ko/messages.json
- web/packages/extension/assets/_locales/pt_PT/messages.json
- web/packages/extension/assets/_locales/zh_TW/messages.json
This enables the crowdin-ci to work in the directory, and soon we can try the automatic PR integration too.
Crowdin project can be found at https://crowdin.com/project/ruffle
> Add Crowdin configuration

- web/packages/extension/assets/options.html
- web/packages/extension/assets/player.html
> extension: Display favicon

- core/src/avm2/error.rs
- core/src/avm2/filters.rs
- core/src/avm2/globals/flash/display/bitmap_data.rs
- core/src/avm2/globals/flash/display/display_object.rs
- core/src/avm2/globals/flash/display/graphics.rs
- core/src/avm2/globals/flash/display/stage.rs
- core/src/avm2/globals/flash/display3D/context_3d.rs
- core/src/avm2/globals/flash/text/text_format.rs
Also converts a lot of error-2008s to AVM errors.
> avm2: Use a make_error_2008 function

- web/packages/core/src/load-options.ts
- web/packages/extension/assets/_locales/en/messages.json
- web/packages/extension/assets/options.html
- web/packages/extension/src/common.ts
- web/src/lib.rs
Fixes #10840 .
The changes have been tested lightly manually.
> extension: Add option for setting `playerVersion`

- web/packages/core/src/ruffle-player.ts
it's not supposed to be editable. ref https://github.com/ruffle-rs/ruffle/pull/10819#issuecomment-1529977894
> make panicText readonly

- render/wgpu/src/backend.rs
Quick fixup for #10909 (written by @relrelb)
> render: Fix wgpu renderer name

- web/src/lib.rs
Small changes mostly extracted from #10835. Git really messes up displaying the diff, but all this does is:
- Return the actual error if we fail to create a player for any reason (such as failing to create a renderer). This makes the panic screen slightly more informative.
- Move the `#[cfg` lines above their respective `match` arms (slightly cleaner style)
- Move the "Unrecognized renderer name" error to a more logical location
> web: Tiny refactor of preferred renderer code

- core/src/avm2/globals/date.rs
1. Date should have a call handler.
2. Date should have a static length property.
There is one issue remaining with Date: `new Date(undefined)` should be `Invalid Date` instead of returning the same thing as `new Date()`.
> avm2: Date related fixes

- core/src/display_object/avm1_button.rs
Previously, a separate `ButtonAction` was stored for each `ButtonActionCondition`. However, this can be eliminated using `bitflags`.
> core: Don't duplicate `ButtonAction`s

- render/wgpu/src/backend.rs
Tested by forcing the max size to 1024 and things work great, just not as pretty as they otherwise would be.
There's other approaches to solving this and they all have their pros and cons:
- This way (resize with cubic filter): not the prettiest for pixel art, mostly works as expected though
- Using a different filter: might make some art look better than others
- Using & stitching multiple textures: would make all art look better but significantly complicate rendering
- Trying to identify which region of the texture is used (ie individual draw calls in a mesh), and only using those: complicates things but may look better in some cases
Ultimately, this should be better than nothing for minimum fuss.
Note that webgl backend currently ignores the system limits and for some reason they don't …
> wgpu: Resize textures if they're bigger than the system supports

- web/packages/core/src/config.ts
- web/packages/core/src/load-options.ts
- web/packages/core/src/ruffle-player.ts
> web: Configuration to disable context menu on touch

- web/packages/core/texts/en-US/save-manager.ftl
Some users are confused about what a "sol" is (see https://discord.com/channels/610531541889581066/1099002553661919232/1105851375126069260).
> web: Simplify a source string

- core/src/avm1/globals/button.rs
- core/src/avm1/globals/movie_clip.rs
- core/src/avm2/globals/flash/display/sprite.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/movie_clip.rs
This is a follow-up to #10865.
> avm1: `button.useHandCursor` can hold any value

- core/src/avm2/globals/flash/net/SharedObject.as
> avm2: Stub SharedObject.setProperty

- swf/src/read.rs
[Sample](https://github.com/ruffle-rs/ruffle/files/11468224/swfv0.zip) (hex-edited)
> swf: Bail out if swf version is 0

- web/packages/extension/manifest.json5
- web/packages/extension/src/popup.ts
Attempt at fixing #11098 as per https://github.com/ruffle-rs/ruffle/issues/11098#issuecomment-1552649360.
Supersedes #11099.
> extension: Remove "tabs" permission

- exporter/src/main.rs
When using - as an output filename. Only supports single-frame output.
I haven't done it, but maybe it should imply --silent.  
Alternatively, messages could be printed to stderr.
I am not a Rust developer, please do submit changes if the code is bad in some way.
> exporter: Support outputting to stdout

- tests/tests/util/options.rs
> Improve visual testing somewhat

- core/src/avm2/globals/flash/display/bitmap_data.rs
(Edited to also refactor 5 extra places in the code, to a total of 8 places refactored - Edited again to add 1 extra place to a total of 9, for `pixel_dissolve()`).
The code should contain no change in behavior. The ~~8~~ 9 places in the code that has been replaced should be exactly the same apart from variable names.
There are two functions that might use this new function that have not been implemented yet, namely `pixel_dissolve()` and `generate_filter_rect()`.
There are two other places and functions in the code where similar pieces of code exist, and where the API for the functions are similar having the `sourceRect:Rectangle` (from [`BitmapData`](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html)) parameter, namely:
`apply_filter()` …
> avm2: Minor refactoring of duplicated code.

- core/src/avm2/globals/flash/system/Worker.as
- core/src/avm2/globals/globals.as
> avm2: Stub Worker

- core/src/avm2.rs
When we iterate over the orphan list to run frame lifecyle methods, the orphan list may be modified (e.g. an event listener creates a new orphan object). To ensure that we iterate over all of the orphans originally present, this commit wraps the orphan list in an `Rc` (just like we do for the render list). Modifications to the list use `Rc::make_mut`, and iteration operates on a clone of the `Rc`.
> avm2: Wrap orphan list in an `Rc` for correct iteration behavior

- core/src/avm2.rs
This ensures that we don't keep the underlying listener object alive after all event listeners (including broadcast listeners) have been unregistered.
> avm2: Use WeakObject in `broadcast_list`

- core/src/player.rs
Previously `last_mouse_position` was updated irrespectively of whether the dragged object was inside or outside the constraint box. Change it follow mouse deltas, after clamping is performed.
Fixes #11254.
> core: Fix drag constraint with `lockCenter` set to `false`

- core/src/avm2/globals/flash/geom/PerspectiveProjection.as
- core/src/avm2/globals/flash/geom/Transform.as
Progresses #9956. (Still shows nothing but a black screen though, sadly)
> avm2: Improve PerspectiveProjection stub

- web/src/navigator.rs
> web: Disabling `allowScriptAccess` also prevents opening URLs in the same tab

- Cargo.lock
- core/Cargo.toml
- core/src/avm1.rs
- core/src/avm1/activation.rs
- core/src/avm1/debug.rs
- core/src/avm1/globals/load_vars.rs
- core/src/avm1/globals/shared_object.rs
- core/src/avm1/object.rs
- core/src/avm1/object/script_object.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/object/super_object.rs
- core/src/avm2.rs
- core/src/avm2/globals/flash/display/display_object.rs
- core/src/bitmap/bitmap_data.rs
- core/src/debug_ui.rs
- core/src/debug_ui/avm1.rs
- core/src/debug_ui/avm2.rs
- core/src/debug_ui/display_object.rs
- core/src/debug_ui/handle.rs
- core/src/debug_ui/movie.rs
- core/src/display_object.rs
- core/src/display_object/movie_clip.rs
- core/src/external.rs
- core/src/library.rs
- core/src/player.rs
- desktop/assets/texts/en-US/main_menu.ftl
- desktop/src/gui.rs
- swf/src/write.rs
> Many more debug UI features

- tests/tests/swfs/avm2/stage3d_fractal/test.toml
- tests/tests/swfs/avm2/stage3d_raytrace/test.toml
- tests/tests/swfs/avm2/stage3d_sampler/test.toml
- tests/tests/swfs/avm2/stage3d_texture/test.toml
- tests/tests/swfs/stage3d/sampler_odd_size/test.toml
This makes the tests pass on my machine
> tests: Increased tolerance of stage3d tests

- core/src/avm2/globals/flash/display.rs
- core/src/avm2/globals/flash/display/AVM1Movie.as
- core/src/avm2/globals/flash/display/avm1movie.rs
- core/src/avm2/globals/globals.as
This progresses Kongregate Rainbogeddon and the game mentioned in #9319, which next needs some Crossbridge/Alchemy fixes, as well as mixed AVM support.
> avm2: Stub AVM1Movie

- core/src/avm1/globals/convolution_filter.rs
- core/src/avm1/globals/displacement_map_filter.rs
- core/src/debug_ui.rs
- core/src/display_object.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/stage.rs
- core/src/display_object/text.rs
- core/src/html/layout.rs
- core/src/html/text_format.rs
- render/canvas/src/lib.rs
- render/src/tessellator.rs
- swf/src/types.rs
- swf/src/types/color.rs
> swf: Make Color Copy

- core/src/debug_ui.rs
- core/src/debug_ui/display_object.rs
- core/src/debug_ui/display_object/search.rs
- core/src/debug_ui/handle.rs
- core/src/player.rs
- desktop/assets/texts/en-US/main_menu.ftl
- desktop/src/gui.rs
- desktop/src/gui/controller.rs
https://github.com/ruffle-rs/ruffle/assets/317625/40baa1e4-4b3d-4578-a99d-1b409555d3b6
> core: Add debug feature to find display objects by mouse

- render/naga-pixelbender/src/lib.rs
- render/wgpu/src/pixel_bender.rs
This could really be a single f32 (or even a boolean), but wgpu on web requires a minimum size of 16 bytes for uniforms.
> wgpu: Use a vec4f for pixelbender ZEROED_OUT_OF_RANGE_MODE_INDEX

- core/src/avm2/activation.rs
- core/src/avm2/function.rs
> avm2: Clean up Activation a little

- render/wgpu/src/filters.rs
This eliminates the console spam produced when an object with an unsupported filter was onscreen.
> wgpu: Only log 'unsupported' warning once per filter type

- core/src/display_object.rs
And warn only once per bitmap. Fixes #11908.
> core: Fix panic from oversized bitmap warning

- web/packages/core/src/ruffle-player.ts
This reverts ea78bf2d3983b525b61861eae7e8fbb715ace272 and restores @danielhjacobs's original, working approach from #10950.
> web: Fix broken touch detection

- core/src/avm2/globals/flash/globalization/CurrencyFormatter.as
fixes Rogue Soul 2 https://github.com/ruffle-rs/ruffle/issues/10176
> avm2: Stub flash.globalization.CurrencyFormatter.format

- render/wgpu/src/pixel_bender.rs
The shader expects an array of i32s, but we were writing bitcasted f32s to the array.
> wgpu: Correctly pass PixelBender int params to shader

- render/naga-pixelbender/src/lib.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/11844
> naga-pixelbender: Implement Opcode::Fract

- core/src/display_object/movie_clip.rs
This makes a Character available for a SymbolClass to link with
> core: Use a slightly better DefineFont4 stub

- core/src/avm1/globals/button.rs
> avm1: Implement Button.filters

- core/src/avm2/globals/flash/system.as
- core/src/avm2/globals/flash/system.rs
- core/src/external.rs
- core/src/player.rs
- desktop/src/backends/external_interface.rs
- tests/README.md
- tests/tests/external_interface/mod.rs
- tests/tests/util/fs_commands.rs
- tests/tests/util/mod.rs
- tests/tests/util/runner.rs
- web/src/lib.rs
Also implements avm2 `fscommand()` function.
> tests: Implement fscommand("quit")

- core/src/avm2/object/xml_list_object.rs
This doesn't really enable any new functionality, but prevents throwing Errors for things that are allowed in Flash/ECMA-357.
> Make XMLList set_property_local (aka [[put]]) less error happy

- core/src/avm2/globals/flash/display/Loader.as
This can just delegate to LoaderInfo
> avm2: Implement Loader.uncaughtErrorEvents

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/build_playerglobal/Cargo.toml
- core/macros/Cargo.toml
- render/Cargo.toml
- web/Cargo.toml
This is basically https://github.com/ruffle-rs/ruffle/pull/12449, but without https://github.com/ruffle-rs/ruffle/pull/12410.
> chore(deps): lock file maintenance rust dependencies

- desktop/src/app.rs
- desktop/src/cli.rs
- desktop/src/gui/controller.rs
> desktop: Allow disabiling top menu

- render/webgl/shaders/gradient.frag
As described in #10517, Flash Player applies color transforms on each gradient record, and then blends between those transformed colors.
> webgl: Apply color transform on gradient records

- core/src/avm2/globals.rs
- core/src/avm2/globals/flash/ui/ContextMenu.as
- core/src/avm2/globals/flash/ui/ContextMenuBuiltInItems.as
- core/src/avm2/globals/flash/ui/context_menu.rs
- core/src/player.rs
- desktop/src/gui.rs
This allows you to complete Stage 7 in This Is The Only Level 3.
Unfortunately doesn't help with #10493.
> Implement context menu events for AVM2

- .gitignore
- web/.gitignore
This has bugged me for years and I kept not getting around to it
> chore: Add .idea to gitignore

- render/src/utils.rs
> render: fix jpeg cmyk to rgb

- core/src/avm2/globals/flash/display/BitmapData.as
- core/src/avm2/globals/flash/display/bitmap_data.rs
- core/src/display_object/edit_text.rs
Basically copied from avm1.
Makes #12377 playable, progresses #9623 (doesn't crash anymore)
> avm2: implement BitmapData.merge

- core/src/backend/ui.rs
- core/src/streams.rs
- desktop/src/backends/ui.rs
- desktop/src/player.rs
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
- web/packages/extension/manifest.json5
- web/src/lib.rs
- web/src/ui.rs
~~Draft since once a video is opened it cannot be closed or dismissed with current code.~~
[Screencast from 2023-08-04 11-02-41.webm](https://github.com/ruffle-rs/ruffle/assets/29206584/44a22311-0c91-4e8f-a28f-e708892afb1f)
> core/desktop/web: Play unsupported videos with browser

- core/src/streams.rs
NetStreams are different from other secondary assets - for some reason NetStream URLs are relative to the SWF URL, not the page URL. This makes the videos play in the [Super Mario Galaxy Wii microsite](http://web.archive.org/web/20100603072248id_/http://www.nintendo.com/sites/supermariogalaxy/).
> core: Use root movie URL as base for relative NetStream URLs

- tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/UserDefinedErrorsPackageWithoutMatchingCatch/Test.as
- tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/UserDefinedErrorsPackageWithoutMatchingCatch/testpackage/TryAndCatchBlockWithUserDefinedErrorsWithoutMatchingcatch.as
- tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/UserDefinedErrorsPackageWithoutMatchingCatch/testpackage2/Box.as
- tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/UserDefinedErrorsPackageWithoutMatchingCatch/testpackage2/BoxDimensionException.as
- tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/UserDefinedErrorsPackageWithoutMatchingCatch/testpackage2/BoxOverflowException.as
- tests/tests/swfs/from_avmplus/as3/Statements/Exceptions/UserDefinedErrorsPackageWithoutMatchingCatch/testpackage2/BoxUnderzeroException.as
> tests: Rename some files because windows is dumb and they're too long

- core/src/avm1/globals/button.rs
- core/src/avm1/globals/text_field.rs
> avm1: Hook up Button.cacheAsBitmap and TextField.filters

- web/packages/extension/src/player.ts
Address https://github.com/ruffle-rs/ruffle/pull/12873#discussion_r1301398953
> extension: Remove unnecessary lambda functions

- web/packages/extension/src/background.ts
[From this blog post](https://adguard-vpn.com/en/blog/mv3-browser-extension.html):
> In Manifest V2 environment, it didn't matter where in the code the event listener was located – its registration could occur asynchronously because the background page was always running and never restarted.
> 
> In Manifest V3 the service worker is restarted when an event occurs. In this case, in order for the event to hit the listener, it must be registered at the top level of the code (synchronously).
This fix is needed for the "Open in new tab" button to work even when the service worker has been suspended (which happens after 30 seconds of inactivity)
> extension: Register listeners synchronously at top level of service worker

- core/src/avm2/error.rs
- core/src/avm2/globals/int.rs
- core/src/avm2/globals/number.rs
- core/src/avm2/globals/uint.rs
- core/src/avm2/value.rs
- tests/tests/swfs/from_avmplus/as3/RuntimeErrors/Error1004MethodInvokedOnIncompatibleObj/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/e/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/ln10/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/ln2/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/log10e/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/log2e/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/pi/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/sqrt1_2/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/sqrt2/test.toml
- tests/tests/swfs/from_avmplus/as3/Types/Number/visibility/v15/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Exceptions/number_001_rt/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Exceptions/number_002_rt/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Number/e15_7_4_2_1_rt/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Number/e15_7_4_2_2_rt/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Number/e15_7_4_3_1_rt/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Number/e15_7_4__1_rt/test.toml
- tests/tests/swfs/from_avmplus/ecma3/Number/e15_7_4_rt/test.toml
Unfortunately this regresses one test because namespace versioning is not yet implemented.
> avm2: Various correctness improvements to Number, int, and uint

- web/packages/core/src/i18n.ts
- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
> web: Remove all occurences of innerHTML (except in test files)

- core/src/avm2/globals/array.rs
> avm2: Implement Array.insertAt

- core/src/display_object/edit_text.rs
- core/src/display_object/text.rs
- core/src/drawing.rs
- core/src/font.rs
Dependencies for TTF rendering
> core: Various small Font and Glyph refactors

- core/src/display_object/movie_clip.rs
> core: fix typo in movie_clip.rs

- core/src/avm2/e4x.rs
- core/src/avm2/e4x/is_xml_name.rs
- core/src/avm2/globals/toplevel.rs
- core/src/avm2/globals/xml.rs
- core/src/avm2/object/xml_object.rs
Small code cleanup after #12993 and #13041.
> avm2: Small XML code cleanup

- core/src/avm2/globals/namespace.rs
- core/src/avm2/value.rs
After #13179 is merged...
Progresses #12462
Progresses #10972
Progresses #10175
Progresses #10173
Progresses #9551
Progresses #9232
Progresses #7866
They all need TLF features (stubs) afterwards.
> avm2: Namespace improvements

- web/packages/core/src/ruffle-player.ts
Simple fix pulled out from #13030
> web: Fix deletion order of dynamicStyles rules

- core/src/avm2/globals/xml.rs
- tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_6/test.toml
- tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_7/test.toml
> avm2: Implement support for indexes in xml.child()

- render/wgpu/src/pipelines.rs
- render/wgpu/src/surface.rs
- render/wgpu/src/surface/commands.rs
- render/wgpu/src/surface/target.rs
This is a stencil-only texture, not a depth buffer. Setting `depth_ops` to `None` also makes us compatible with WebGPU (the wgpu crate doesn't yet validate this).
> wgpu: Rename DepthBuffer to StencilBuffer and stop providing depth_ops

- web/packages/core/src/ruffle-player.ts
- web/packages/core/src/shadow-template.ts
- web/packages/core/texts/en-US/messages.ftl
Edit: This is the original screenshot, new Screencast is here: https://github.com/ruffle-rs/ruffle/pull/13357#discussion_r1342766440
> web: Display a pop-up about hardware acceleration when it's disabled

- render/naga-agal/src/builder.rs
We weren't covering all cases, which resulted in an attempt to AccessIndex on a scalar, or write a scalar directly to a vector local.
> nagal-agal: Fix detection of writing a scalar to a destination

- core/src/avm2/object/xml_object.rs
Fixes test `e11_6_1` when combined with #13255.
> avm2: Fix handling of XMLList when set as attribute value

- swf/src/write.rs
I'm gonna think about a possible test later :)
> swf: Fix writing of an all-zeros curve ShapeRecord

- core/src/avm2/globals/flash/text/TextRenderer.as
> avm2: Fix missing stub imports in TextRenderer.as

- .github/workflows/release_nightly.yml
- web/Cargo.toml
- web/docker/Dockerfile
The CI stuff is untested (we have no real way of testing that without actually running it), please sanity check in review.
> web: Make jpegxr optional on web but enabled by default by CI

- Cargo.toml
- render/Cargo.toml
> nit: Clean up Cargo.toml files slightly (remove unnecessary `version =` maps)

- core/src/avm2/globals/flash/display/graphics.rs
A stub message is good enough.
> avm2: Replace culling panic messages with stub messages

- core/src/avm2/e4x.rs
- core/src/avm2/object/xml_object.rs
So Haxe's uses `o.hasOwnProperty(field)` and `o[field]` to lookup attributes as strings on XML objects.
We can support this by manually re-parsing the multiname in get_property_local. `has_own_property` doesn't have an activation, which makes this difficult. I temporarily solved this by adding the hasOwnProperty method explicitly to the XML class, which was missing anyway.
I tried adding an activation parameter to has_own_property before, but gave up because it required a lot of other changes to pass an activation around.
Fixes #12765 (still unplayable slow) and fixes #10228
> avm2: XML objects must support lookups like "@attr"

- core/src/avm2/globals/flash/display/display_object_container.rs
I still need to write tests for this
> avm2: Implement DisplayObjectContainer.getObjectsUnderPoint

- web/packages/core/src/ruffle-player.ts
It doesn't in Pale Moon: https://forum.palemoon.org/viewtopic.php?f=70&t=30040&p=241167&hilit=navigator.clipboard#p241165
> web: Check navigator.clipboard exists before using it

- swf/src/write.rs
Previously, `swf` crate always wrote out the action offset, but this should be 0 when there are no actions.
> swf: Fix writing of a DefineButton2 with zero actions

- Cargo.lock
- LICENSE.md
- core/Cargo.toml
- core/src/avm1/activation.rs
- core/src/avm2/globals/flash/utils.rs
- core/src/backend/audio.rs
- core/src/context.rs
- core/src/display_object/interactive.rs
- core/src/player.rs
- web/Cargo.toml
- web/LICENSE.md
See for rationale: https://github.com/sebcrozet/instant/issues/52
`winit` and `egui` have done this already:
https://github.com/rust-windowing/winit/pull/2836
https://github.com/emilk/egui/pull/3296
> core,web: Replace `instant` with `web-time`

- core/src/avm2/globals/xml.rs
- core/src/avm2/object/xml_list_object.rs
- tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_3/v10/test.toml
Currently not ready due to https://github.com/ruffle-rs/ruffle/issues/13676
> avm2: Reimplement XML.appendChild in terms of [[Get]] and [[Put]]

- core/src/avm2/e4x.rs
- core/src/avm2/globals/XML.as
- core/src/avm2/globals/xml.rs
Progresses https://github.com/ruffle-rs/ruffle/issues/12054. These function don't have `prototype` variants.
> avm2: Stub undocumented XML notification functions

- core/src/avm2/globals/XML.as
- core/src/avm2/globals/xml.rs
- tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_33/test.toml
> avm2: Implement XML.setChildren

- core/src/avm2/globals/flash/events/DataEvent.as
> avm2: `DataEvent` fixes

- core/src/avm2/globals/flash/accessibility/AccessibilityImplementation.as
With this PR, W2W Chapter 3: Hybrid Vigor (http://new.weedtowonder.org/hybrid.html) now finishes loading without throwing any errors.
> avm2: Add `AccessibilityImplementation.accDoDefaultAction`

- core/src/avm2/object/xml_object.rs
> amv2: Simplify XmlObject get_enumerant_name

- core/src/avm2/globals/vector.rs
- core/src/lib.rs
- core/src/string/interner.rs
- exporter/src/main.rs
- render/src/matrix.rs
https://rust-lang.github.io/rust-clippy/master/index.html#/items_after_test_module
https://github.com/ruffle-rs/ruffle/actions/runs/6847251655/job/18615197010
> chore: Appease clippy-beta

- web/packages/demo/www/index.js
- web/packages/extension/src/player.ts
Fixes https://github.com/ruffle-rs/ruffle-rs.github.io/issues/176
See https://stackoverflow.com/a/62979491
> demo/extension: Expand iPad check to work for iPadOS 13+

- core/src/avm2/globals/flash/ui/ContextMenu.as
- core/src/avm2/globals/flash/ui/ContextMenuClipboardItems.as
- core/src/avm2/globals/globals.as
Slightly progresses #10173.
Next error there is back to being TLF related.
> avm2: Add ContextMenu clipboard related properties

- core/src/avm2/globals/flash/net/url_loader.rs
- core/src/loader.rs
Also fixes some minor issues with `URLLoader.load`. This progresses Cocolani registration.
> avm2: Implement `URLLoaderDataFormat.VARIABLES`

- desktop/src/backends.rs
- desktop/src/backends/fscommand.rs
- desktop/src/player.rs
> dekstop: Support `quit` and `fullscreen` fscommands

- Cargo.lock
- core/Cargo.toml
- core/build_playerglobal/Cargo.toml
- desktop/Cargo.toml
- render/Cargo.toml
- render/wgpu/Cargo.toml
- swf/Cargo.toml
- tests/framework/Cargo.toml
- tests/input-format/Cargo.toml
- tests/socket-format/Cargo.toml
- web/Cargo.toml
See: https://github.com/ruffle-rs/ruffle/pull/14186#issuecomment-1826992203
> fix(deps): update rust dependencies

- core/src/avm2/globals/flash/text/engine/TextLine.as
- core/src/avm2/globals/flash/text/engine/text_line.rs
Improves #14326. We have some related code in apply_format in text_block.rs.
> avm2: Implement TextLine::textWidth and TextLine::textHeight

- render/wgpu/src/context3d/current_pipeline.rs
The offsets for bound attributes can overlap, which caused us to compute the total size incorrectly. Fix this check to take overlapping into account.
> wgpu: Fix overly strict assertion for setVertexBufferAt

- core/src/avm1/globals.rs
- core/src/avm1/globals/netconnection.rs
Progresses https://github.com/ruffle-rs/ruffle/issues/12327 a little bit.
At least the video holder is no longer flung to the right continuously.
> core/avm1: Stub NetConnection

- core/src/avm2/globals/flash/display/InteractiveObject.as
This improves #14294. Creating an account doesn't work, but login seems to be possible, but I don't have any valid credentials.
> avm2: Stub InteractiveObject needsSoftKeyboard and softKeyboardInputAreaOfInterest

- core/src/avm1.rs
- core/src/avm1/globals/netconnection.rs
- core/src/display_object/movie_clip.rs
- core/src/frame_lifecycle.rs
- core/src/stub.rs
> core/avm1: Improve some stubs

- desktop/src/gui/controller.rs
> desktop: Fix egui scaling

- core/src/backend/ui.rs
- core/src/library.rs
- desktop/src/backends/ui.rs
- tests/framework/src/backends/ui.rs
- web/src/ui.rs
> core: Some prep work for native font loading

- core/src/avm2/metadata.rs
- desktop/src/backends/navigator.rs
- exporter/src/main.rs
- ruffle_gc_arena/src/gc_cell.rs
- ruffle_gc_arena/src/gc_weak_cell.rs
The one in `ruffle_gc_arena` is as per our discussion with @kyren on Discord.
The rest is according to what clippy says, making up hopefully not entirely nonsensical names for the new bindings.
> chore: Fix beta clippy lints

- Cargo.lock
- Cargo.toml
- core/src/string/interner.rs
- ruffle_gc_arena/Cargo.toml
- ruffle_gc_arena/src/gc_weak_cell.rs
This was fairly painless - I hope nothing breaks.
> chore: Upgrade `gc-arena` to 0.5.0

- core/src/avm2/globals/flash/text/TextField.as
> avm2: Stub more TextField getLine methods

- core/src/avm2/globals/flash/events/KeyboardEvent.as
- core/src/events.rs
- desktop/src/util.rs
- web/src/lib.rs
> core: Support F13..F24 keys

- core/src/display_object/edit_text.rs
This commit fixes issues with caret and selection rendering:
1. They had the wrong height and were rendered lower than expected for some fonts and sizes.
2. The caret was not being rendered at all when there was no text, but only when the text was set earlier and then deleted.
3. The selection was rendered with translate_x=-1, which caused overlap over some glyphs.
This PR fixes #10478.
| Flashplayer   | Before        | After |
|:-------------:|:-------------:|:-----:|
| ![image](https://github.com/ruffle-rs/ruffle/assets/1507072/ff5ce618-eef8-4e2c-998b-9fd3d363ebee) | ![image](https://github.com/ruffle-rs/ruffle/assets/1507072/f80c6542-eba9-49b4-b071-5efc6fb8a603) | ![image](https://github.com/ruffle-rs/ruffle/assets/1507072/ed4e3a89-ac84-47db-846a-dff5f897fba5) |
| …
> core: Fix caret and selection rendering

- core/src/html/layout.rs
> core: Provide a better fallback for Ming typefaces

- core/src/avm2/globals/flash/net.rs
> avm2: Throw null param error in navigateToURL

- core/src/display_object/edit_text.rs
Caret now blinks only when idle. This matches the behavior of flashplayer (mostly) and improves usability, as users expect to see the caret at all times when doing something with it.
<table>
<thead>
<tr>
<th rowspan="2">Action</th>
<th colspan="3">Caret behavior</th>
</tr>
<tr>
<th>Flashplayer</th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>Idle</td>
<td>Blinks (~1094 ms<sup>&ast;</sup>)</td>
<td>Blinks (1000 ms)</td>
<td>Blinks (1000 ms)</td>
</tr>
<tr>
<td>Place</td>
<td>Resets blinking</td>
<td>Blinks</td>
<td>Resets blinking</td>
</tr>
<tr>
<td>Move</td>
<td>Resets blinking</td>
<td>Blinks</td>
<td>Resets blinking</td>
</tr>
<tr>
<td>Backspace</td>
<td>Resets blinking</td>
<td>Blinks</td>
<td>Resets blinking</td>
</tr>
<tr>
<td>Delete</td>
<td>Resets blinking</td> …
> core: Improve caret blinking behavior

- .github/workflows/track_merged_prs.yml
> ci: Use right auth token for tracking merged PRs

- core/src/avm2/globals/XML.as
- core/src/avm2/globals/xml.rs
> avm2: Stub XML::namespaceDeclarations

- core/src/avm2/activation.rs
Should fix the test failure @Dinnerbone noticed on wasm.
(I didn't get to test it myself due to temporary pc difficulties)
> avm2: Fix possible overflow in address calculations

- core/src/avm2/globals/flash/display/Stage.as
> avm2: Stub Stage colorCorrection and colorCorrectionSupport

- core/src/avm2/globals/XML.as
- core/src/avm2/globals/xml.rs
> avm2: Stub XML::inScopeNamespaces

- core/src/avm2/globals/flash/desktop/Clipboard.as
- core/src/avm2/globals/globals.as
This makes the "Get Save Password" button in Phoenotopia work. (#9226)
> avm2: Stub flash.desktop.Clipboard

- core/src/avm2/globals/flash/display/simple_button.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/avm2_button.rs
- core/src/display_object/movie_clip.rs
Slowly getting rid of more `GcCell` usages.
> Use inner mutability instead of `GcCell` in `Avm1Button` and `Avm2Button`

- core/src/display_object/avm2_button.rs
> avm2: Don't forget to set the state in `Avm2Button::set_state`

- core/src/avm1/globals/bitmap_data.rs
- core/src/avm2/globals/flash/display/bitmap_data.rs
- core/src/avm2/globals/flash/display/shader_job.rs
- core/src/avm2/globals/flash/display3D/textures/cube_texture.rs
- core/src/avm2/globals/flash/display3D/textures/rectangle_texture.rs
- core/src/avm2/globals/flash/display3D/textures/texture.rs
- core/src/bitmap/bitmap_data.rs
- core/src/bitmap/operations.rs
- core/src/debug_ui/avm2.rs
- core/src/display_object/bitmap.rs
- render/canvas/src/lib.rs
- render/src/backend.rs
- render/src/backend/null.rs
- render/src/bitmap.rs
- render/webgl/src/lib.rs
- render/wgpu/src/backend.rs
- render/wgpu/src/lib.rs
This should reduce the resource cost of BitmapData.draw() a fair bit, most impactful on webgl
> wgpu: Don't submit for every single BitmapData.draw()

- core/src/avm2/value.rs
Minor improvement to #10560. I couldn't find any content that used number comparison in a tight loop like Evoland did for integer comparison, so I didn't add the special-case.
> avm2: Add fast path for `Value::abstract_lt`-ing two integers

- .dockerignore
I don't have the courage to merge this in the next 12 hours...
EDIT: I'm no longer afraid.
See rationale in the newly added file.
> chore: Add a `.dockerignore` file

- web/package-lock.json
- web/package.json
- web/packages/core/package.json
- web/packages/extension/package.json
This is https://github.com/ruffle-rs/ruffle/pull/15049, just without the `chai` (and `chai-html`) bump.
> chore(deps): update node.js dependencies

- core/src/avm2/amf.rs
- core/src/avm2/globals.rs
> Deserialize AMF dictionary

- .github/workflows/test_rust.yml
This isn't supposed to change anything _effectively_, only clean up the .yml a bit.
> ci: Split lints into their own job

- desktop/src/executor.rs
This patch makes TaskHandle reference the executor by a weak reference. Prior to this change, there was a possibility of a resource leak, where the executor, its tasks, and resources held by them were not properly dropped due to existing references to the executor.
This manifested by e.g. unclosed sockets after reload, which required the whole program to be restarted in order to be closed properly.
> desktop: Prevent resource leak on reload

- web/src/navigator.rs
This patch ensures that sockets are closed properly. Without it, when the application-end of the socket was closed, the other end was left intact, and the socket was not closed.
> web: Close sockets properly

- .github/workflows/test_extension_dockerfile.yml
- web/docker/Dockerfile
It works: https://github.com/torokati44/ruffle/actions/runs/8147706175/job/22269010275 \o/
> ci,web: Total Firefox extension reproducibility checking, now with 100% more `wasm-opt`!

- core/src/avm2/optimize.rs
This unifies `ValueType::Number` and `ValueType::Class(classes.number)` (etc) to a single representation (that's analogous to avmplus's abstract optimizer's abstract value), so that primitive-based optimizations can happen more consistently.
This also refactors `astype` optimization to be more conservative, which replaces the previous fix from https://github.com/ruffle-rs/ruffle/pull/15341/commits/c6e3eaad02341f262b3a6b23510946bf79111595 .
There's obviously lots of relatively low-hanging fruit: remaining numerical ops, function return types etc. A lot of current type propagation tries to be careful and conservative where it probably doesn't need to be. In particular, we should be testing for inheritance instead of type equality more.
(One thing I still haven't fully figured out is the …
> avm2: unify abstract type propagation

- core/src/avm2.rs
- core/src/avm2/verify.rs
- core/src/player.rs
- desktop/src/cli.rs
- desktop/src/player.rs
Might be useful if we ever suspect a bug in the optimizer.
Feel free to bikeshed on naming or cli stuff :D
> avm2: Provide an option to disable the optimizer

- core/src/avm2/globals/XML.as
Fixes #15609
Fixes #11380 (again)
> avm2: Fix some parameter types and signatures for XML

- core/src/avm2/object/script_object.rs
- wstr/src/parse.rs
- wstr/src/tests.rs
Checked that it fixes online save loading in Armor Games.
> wstr: Fix parsing of '+'

- core/src/debug_ui/display_object.rs
This helps with debugging mouse-pick bugs
> debug_ui: Show mouseEnabled/mouseChildren/doubleClickEnabled

- frontend-utils/src/backends/executor.rs
- frontend-utils/src/backends/navigator.rs
This fixes the deadlocks on desktop when enough requests are made.
Seems to be the best option I can think of, really. #15981 does kinda patch over it but the things will never end up executing due to the tokio budget system (we should still bring that in anyway though, it covers a different kind of deadlock)
> frontend-utils: Don't use tokio tasks inside ruffle's executor

- frontend-utils/src/backends/executor.rs
It means "I've done more than one task this frame".
Cool. Good job. I'm proud of you.
> frontend-utils: Don't spam 'Double polling'. It's meaningless.

- frontend-utils/src/backends/executor.rs
- frontend-utils/src/backends/executor/task.rs
Related to #15045: fixed a deadlock on desktop during opening a file. Also should fix deadlocks on Android.
3d04971a was the first approach to eliminating deadlocks caused by waking a task from another one. A task may also try to wake itself, and that case was unfortunately not covered.
This patch rewrites the `AsyncExecutor` to use an async channel for queuing tasks instead of a flag. Using a flag required holding a lock for a task which was problematic when a task needed to be awoken. A flag also required doing a full search through tasks each poll, which could be ineffective.
Changes from this PR should be tested thoroughly before merging. Things to watch out for:
1. Performance issues, although in theory this code should be faster, there could be some edge cases I did not think of.
2. …
> frontend-utils: Get rid of deadlocks in AsyncExecutor

- web/packages/extension/manifest_firefox.json5
- web/packages/extension/manifest_other.json5
- web/packages/extension/src/background.ts
> extension: Add exclusions for Time4Learning and Edgenuity

- CONTRIBUTING.md
- README.md
Just some small problems that tripped me up recently.
> docs: Fix scanner command and broken mtasc links

- frontend-utils/src/recents/write.rs
Panic found by @kjarosh on Discord.
> frontend-utils: Do not panic when recent limit is zero and file is empty

- core/src/debug_ui/display_object.rs
- core/src/focus_tracker.rs
> debug_ui: Add interactive tab order list

- core/src/avm2/globals/avmplus.as
- core/src/avm2/globals/avmplus.rs
With this patch, Burrito Bison now works all but flawlessly in my testing, aside from some choppy music!: http://onemorelevel.com/static/games3/burritobison.swf
Fixes #10143.
This is my first contribution to this amazing project, I'm wondering what is the simplest way to create a test for this?
---
Note: the SWF on Newgrounds linked in #10143 issue gives this error screen when testing locally (haven't tried compiling the extension and testing on the web but that may resolve it):
The SWF I linked above works great.
> Implement `describeType(null)` stub

- core/src/bitmap/bitmap_data.rs
- core/src/debug_ui/display_object.rs
This lets us view a bitmap directly from the debug ui. We cache an egui texture handle on the `BitmapData` itself, and invalidate it whenever the BitmapData gets changed.
> debug_ui: Render bitmap in new 'Bitmap' display object tab

- core/src/avm2/globals/flash/external/ExternalInterface.as
- core/src/avm2/globals/flash/external/external_interface.rs
- core/src/external.rs
- desktop/src/backends/external_interface.rs
- tests/tests/external_interface/mod.rs
- web/packages/core/src/ruffle-player.ts
- web/src/lib.rs
> avm2: Implement ExternalInterface.objectID

- core/src/avm2/flv.rs
> avm2: Implement FLV Date to Avm2Value conversion

- core/src/avm2/optimize.rs
This is mostly just improvements to the `int` type in the optimizer.
Box2d stats:
```
FindPropStrict -> GetScriptGlobals : 62.18%
FindPropStrict -> GetOuterScope : 7.76%
FindPropStrict -> GetScopeObject : 8.24%
FindProperty -> GetOuterScope : 2.83%
FindProperty -> GetScopeObject : 94.34%
InitProperty -> SetSlot : 40.93%
InitProperty -> SetSlotNoCoerce : 44.51%
SetProperty -> SetSlot : 25.52% (-3.15%)
SetProperty -> SetSlotNoCoerce : 42.66% (+3.15%)
SetProperty -> CallMethod : 1.57%
GetProperty -> GetSlot : 67.31%
GetProperty -> CallMethod : 0.34%
CallProperty -> CallMethod : 41.13%
CallPropVoid -> CallMethod : 74.24%
Coerce -> Nop : 49.78%
CoerceD -> Nop : 81.34%
CoerceB -> Nop : 8.11%
CoerceU -> Nop : 50% (+17.54%)
CoerceI -> Nop : 33% (+31%)
ReturnValue -> ReturnValueNoCoerce : 71.56% …
```
> avm2: Minor optimizer improvements

- desktop/src/gui/controller.rs
This patch adds proper handling for `SurfaceError`s that may happen when calling `get_current_texture()`, instead of always panicking.
This fixes random crashes, e.g. when the GPU took too long to render a frame, or when the surface has unexpectedly changed.
Fixes https://github.com/ruffle-rs/ruffle/issues/16698, fixes https://github.com/ruffle-rs/ruffle/issues/16576, fixes https://github.com/ruffle-rs/ruffle/issues/16336, fixes https://github.com/ruffle-rs/ruffle/issues/16304, fixes https://github.com/ruffle-rs/ruffle/issues/16302, fixes https://github.com/ruffle-rs/ruffle/issues/16213, fixes https://github.com/ruffle-rs/ruffle/issues/16116, fixes https://github.com/ruffle-rs/ruffle/issues/16053, fixes https://github.com/ruffle-rs/ruffle/issues/16009, fixes …
> wgpu: Prevent random crashes on desktop by handling SurfaceErrors properly

- web/packages/extension/src/background.ts
See https://developer.chrome.com/docs/extensions/reference/api/runtime#type-OnInstalledReason
> extension: Only show onboarding page on first install

- web/packages/extension/tools/submit_xpi.ts
See for relevant API docs:
https://mozilla.github.io/addons-server/topics/api/addons.html#versions-list
I did try this on one of my own extensions, it will probably do what it seems it should do.
Note to @evilpie:
> **file.status** _(int)_ - The [status](https://mozilla.github.io/addons-server/topics/api/addons.html#version-detail-status) for the file.
This line is wrong on the page above, it's a _(string)_.
> web/extension: Check last version on AMO, skip submission if not yet approved

- core/src/avm2/globals/flash/display/DisplayObject.as
> avm2: FP10 version DisplayObject rotationX/Y/Z and scaleZ

- web/packages/extension/tools/submit_xpi.ts
Fixup for #16918. D'oh.
It work'dn't: https://github.com/ruffle-rs/ruffle/actions/runs/9727948148/job/26848111148#step:6:16
> web/extension: Fix AMO submission status checking

- .github/workflows/release_nightly.yml
See https://github.com/KSXGitHub/github-actions-deploy-aur/releases/tag/v2.7.2 and https://github.com/ruffle-rs/ruffle/actions/runs/9769589687/job/26969733404
> actions: Update KSXGitHub/github-actions-deploy-aur

- web/packages/extension/manifest.json5
Change made from GitHub web UI on phone and completely untested. See https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest for info and please test.
> extension: Switch to declarativeNetRequestWithHostAccess

- .github/workflows/download_translations.yml
I'm going to save @torokati44 so many minutes.
> ci: Make the crowdin PR with the rufflebuild user

- web/packages/core/src/ruffle-player.tsx
Fixes https://github.com/ruffle-rs/ruffle/issues/17001.
This exact change was suggested by @danielhjacobs on Discord.
> web: Fix all context menu items appearing disabled

- core/src/backend/audio.rs
- core/src/display_object.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/avm2_button.rs
- core/src/display_object/edit_text.rs
- core/src/display_object/movie_clip.rs
Definitely not every case, but I think we have a lot of issues to work through here.
Slightly impossible to add tests for this :(
Fixes #9795
Fixes #7447
Fixes #14663
Fixes #963
Fixes #2473
Fixes #16947
> avm1: Fix some cases of audio looping or not stopping

- frontend-utils/src/backends/navigator.rs
Turns out that some hosts will try to connect to the black hole address instead of failing instantaneously, so this patch replaces that address with a loopback address with an unlikely to be used port.
> frontend-utils: Use a loopback address for tests on Linux

- .github/workflows/test_web.yml
Reverts ruffle-rs/ruffle#17169
> Revert "ci: Temporarily pin to Node 22.4"

- core/src/bitmap/turbulence.rs
- core/src/loader.rs
- scanner/src/scan.rs
See for example: https://github.com/ruffle-rs/ruffle/actions/runs/10058530166/job/27801842401?pr=17230
> chore: Fix new beta lint `clippy::manual_inspect`

- core/src/debug_ui/avm2.rs
> debug_ui: Add a tab for AVM2 array contents

- web/package-lock.json
- web/package.json
I'm sorry if you've had enough of this stuff for a year, @danielhjacobs ... :no_mouth:
> web: Do an `npm update`, remove `chromedriver` dependency

- desktop/Cargo.toml
This is an alternative to #17393.
> desktop: Enable LZMA feature by default

- desktop/assets/texts/ko-KR/main_menu.ftl
- desktop/assets/texts/ko-KR/preferences_dialog.ftl
- desktop/assets/texts/ko-KR/settings.ftl
- web/packages/extension/assets/_locales/ko/messages.json
- web/packages/extension/assets/_locales/pl/messages.json
New Crowdin pull request with translations
> chore: Update translations

- README.md
> chore: Add Flathub badge to README

- core/build_playerglobal/src/lib.rs
- core/src/avm2/activation.rs
- desktop/src/gui/dialogs/bookmarks_dialog.rs
- web/src/navigator.rs
Just so they don't keep me up at night...
> chore: A couple typo fixes in comments here and there

- core/src/avm2/object/sound_object.rs
Fixes https://github.com/ruffle-rs/ruffle/issues/16478
This game checks the maximum audio channels by calling Sound.play on the same audio in a while loop until it ends. 
SoundManager already handles a max of channels played but this works only if the Sound is already loaded, in case it's not loaded yet they are enqued. As the while loop does not permit the audio to be loaded it will result in enqueuing an infinite amount of sounds to be played.
Limiting to the maximum makes the game load and play with audio as the count of channels with this orthodox method succeed.
> Avoid enqueue Sound.play infinite amount of times - Fix #16478

- web/packages/core/src/internal/player/inner.tsx
Right-clicking over the context menu no longer re-positions it, and can now trigger menu item actions.
As a result of these changes, the below issue is now fixed:
https://github.com/user-attachments/assets/95612841-4f76-4317-b678-f326a18bd354
In addition, left-clicking a non-clickable part of the context menu no longer closes it.
> web: Improve context menu right-click behavior

- desktop/src/gui.rs
- desktop/src/gui/menu_bar.rs
> desktop: Make shortcuts work in fullscreen and no-gui mode

- .github/workflows/release_nightly.yml
See Also: https://docs.npmjs.com/generating-provenance-statements#about-npm-provenance
> chore: generate provenance statements for nightly npm package

- render/wgpu/src/filters/blur.rs
- web/README.md
> chore: fix some comments

- core/src/socket.rs
Example:
```actionscript
socket.connect("127.0.0.1" + unescape("%00") + "this part is ignored, flash stops at the null byte")
```
Flash truncates at any null byte - likely a low level method thinking it's getting a cstring. This emulates the truncation behaviour, fixing a Habbo connection issue from Discord.
No tests because our test suite won't run into this, it ignores hosts and everything is local.
> core: Truncate socket host by null bytes

- .github/workflows/release_nightly.yml
> build: Freeze rustc for nightly builds to 1.80.1

- core/src/avm2/globals/flash/sensors/Accelerometer.as
> avm2: Stub flash.sensors.Accelerometer completely

- desktop/assets/texts/en-US/network_access_dialog.ftl
- desktop/assets/texts/en-US/open_url_dialog.ftl
We do not want to question the user's intent, we want to ask what their intent is.
That will unfortunately invalidate all translations :(
CC @Dinnerbone @torokati44
> desktop: Update dialog texts to ask for intent

- .github/workflows/download_translations.yml
There is no reason this should be necessary, but it seems like it probably is :shrug:
> ci: Create PR for downloading translations then add labels

- .github/workflows/download_translations.yml
As per https://github.com/ruffle-rs/ruffle/pull/18136#issuecomment-2388055769
CC @torokati44 @danielhjacobs
> ci: Add comment explaining adding labels after creating a PR

- Cargo.lock
- desktop/Cargo.toml
- desktop/src/dbus.rs
- desktop/src/gui/theme.rs
That's a refactor that simplifies our code a lot.
I would appreciate some tests to make sure it does not break anything.
> desktop: Use ashpd for dbus communication

- web/packages/extension/manifest.json5
- web/packages/extension/src/background.ts
> extension: Don't run scripts on chewy.com

- .github/workflows/download_translations.yml
- .github/workflows/upload_texts.yml
These might come in handy later...
> ci: Add manual dispatch and artifact upload to Crowdin sync actions

- .github/workflows/release_nightly.yml
- .github/workflows/test_extension_dockerfile.yml
- .github/workflows/test_web.yml
- Cargo.lock
- Cargo.toml
- web/README.md
- web/docker/Dockerfile
> chore: Bump `wasm-bindgen` to `0.2.95`

- core/src/debug_ui/display_object.rs
Narrower table and more information!
> debug_ui: Improve span list for text fields

- tests/framework/src/runner.rs
This makes it easier to compare values and see which one failed.
> tests: Print comparison when approximation assertion fails

- core/src/debug_ui/display_object.rs
This tab shows important information of the button, e.g. its states.
This helps in debugging https://github.com/ruffle-rs/ruffle/issues/14326.
> debug_ui: Add Avm2Button tab

- core/src/debug_ui/display_object.rs
This patch adds the possibility to view the whole text format for a given text span, or the default one of the text field.
<image src="https://github.com/user-attachments/assets/493e9fc1-8561-4b0d-984d-be83d5fdda76" height="300"/>
<image src="https://github.com/user-attachments/assets/aa8f99ca-514d-42a8-a7ee-3284912e9df6" height="300"/>
> debug_ui: Show text format on hover in EditText

- core/src/display_object/edit_text.rs
> text: Remove EditText::line_width

- core/src/avm2/globals/flash/display/DisplayObject.as
- core/src/avm2/globals/flash/display/InteractiveObject.as
New stubs:
* `DisplayObject.globalToLocal3D`
* `DisplayObject.local3DToGlobal`
* `InteractiveObject.requestSoftKeyboard`
> avm2: Add some more stubs

- .github/workflows/release_nightly.yml
- .github/workflows/test_extension_dockerfile.yml
- .github/workflows/test_web.yml
- web/README.md
- web/docker/Dockerfile
See: https://nodejs.org/en/about/previous-releases
> chore: Update Node.js, LTS: 20 -> 22, Active: 22 -> 23

- core/src/debug_ui/display_object.rs
It shows position, scale, rotation, relative to the world.
> debug_ui: Add information about world matrix to position tab

- core/src/avm2/e4x.rs
See: https://github.com/ruffle-rs/ruffle/actions/runs/12491833684/job/34858335657?pr=19061#step:6:1037
> chore: Fix a nightly `clippy::unnecessary_map_or` lint

- web/packages/extension/src/background.ts
>  extension: Fix types which are changed in latest @types/chrome 

- core/src/avm2/object/stylesheet_object.rs
- core/src/debug_ui/avm2.rs
- core/src/debug_ui/display_object.rs
A follow up to https://github.com/ruffle-rs/ruffle/pull/19143.
> debug_ui: Show StyleSheet in EditText

- web/package-lock.json
Because Dependabot doesn't do it.
> chore: Run `npm update`

- Cargo.lock
- render/Cargo.toml
- video/software/Cargo.toml
No functional changes expected.
> chore: Bump h263-rs git ref to latest master

- desktop/src/app.rs
Should fix #19343
This bug did not affect opening files after application startup since LoadingState is never set back to Loading again.
> desktop: Set LoadingState to Loaded even when window is maximized

- desktop/src/app.rs
This patch simplifies the code for setting control flow by always requesting a wait till the next frame time.
The busy loop was caused by the fact that winit was leaving wait requests with timestamps in the past, which caused us to not update the control flow as a wait was requested earlier.
Thanks @madsmtm for helping us with this fix.
Testing shows that we're now producing a reasonable number of ticks per second, and idle CPU usage has dropped significantly.
> desktop: Fix busy loop in winit

- desktop/packages/linux/rs.ruffle.Ruffle.desktop.in
- desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml.in
> desktop: Add Ruffle to the Emulator category

- .github/workflows/release_nightly.yml
- .github/workflows/test_extension_dockerfile.yml
- .github/workflows/test_web.yml
- web/docker/Dockerfile
See: https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v122
> chore: Bump Binaryen (wasm-opt) to version 122

- core/src/avm1/globals.rs
- core/src/avm1/globals/system.rs
- core/src/avm1/object/stage_object.rs
- core/src/avm1/property_decl.rs
- core/src/avm1/runtime.rs
And make the code shorter as a bonus!
> avm1: remove static `AvmString` usage in globals initialization

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- deny.toml
- desktop/Cargo.toml
- desktop/src/backends/ui.rs
- desktop/src/gui/controller.rs
- desktop/src/gui/dialogs/preferences_dialog.rs
- exporter/src/main.rs
- render/naga-agal/src/builder.rs
- render/naga-pixelbender/src/lib.rs
- render/wgpu/src/backend.rs
- render/wgpu/src/context3d/mod.rs
- render/wgpu/src/lib.rs
- render/wgpu/src/pixel_bender.rs
- render/wgpu/src/surface/target.rs
- render/wgpu/src/target.rs
- tests/tests/environment.rs
~~Mostly for testing for now, I guess.~~
see: https://github.com/gfx-rs/wgpu/releases/tag/v24.0.0 and https://github.com/gfx-rs/wgpu/releases/tag/v24.0.1
egui 0.31.0 is also out now: https://github.com/emilk/egui/releases/tag/0.31.0
> desktop: Update to wgpu 24.0.1 and egui 0.31.0

- .github/workflows/release_nightly.yml
https://github.com/wixtoolset/issues/issues/8033
https://github.com/wixtoolset/issues/issues/8033#issuecomment-2659659783
https://docs.firegiant.com/wix/tools/wixexe/#wix-extension-command-extension
> ci: Pin the wix extensions as well

- core/src/avm2/multiname.rs
- render/src/bitmap.rs
- video/software/src/decoder/vp6.rs
As seen here, for example:
https://github.com/ruffle-rs/ruffle/actions/runs/13394267785/job/37409223046?pr=19557
> chore: Fix beta clippy lints `manual_div_ceil` and `unneeded_struct_pattern`

- core/src/display_object/edit_text.rs
Turns out that sometimes `try_bind_text_field_variable` is executed when we don't have a parent.
* Fixes https://github.com/ruffle-rs/ruffle/issues/18601
* Fixes https://github.com/ruffle-rs/ruffle/issues/15466
> core: Do not panic on missing parent in text variable binding

- web/package-lock.json
I guess part of this will be covered by Dependabot when it triggers for this repo too in a couple hours...
> chore: Run `npm update` in `web/`

- core/src/avm2/globals/flash/globalization/CurrencyFormatter.as
Stubbed properties have the default values for locale en-US.
> avm2: Stub `flash.globalization.CurrencyFormatter`

- core/src/debug_ui/display_object.rs
Replaces the current egui::Grid based layout, which tanks performance due to rendering everything.
Also adds a "Track current frame" checkbox to always scroll to the current frame. Makes it more convenient to keep track of where we are.
> debug_ui: Put frame list inside egui_extras::Table

- .github/workflows/release_nightly.yml
That username has been changed.
> ci: Use josStorer instead of 1466587594

- web/packages/core/src/current-script.ts
- web/packages/core/src/index.ts
- web/packages/extension/src/content.ts
- web/packages/extension/src/global.d.ts
- web/packages/extension/src/messages.ts
- web/packages/extension/src/ruffle.ts
Part 1-3 of #20255, which @evilpie thought contained too many changes. I still plan to make the other change. Supersedes #19664. Best reviewed by commit.
> extension: Fix extension on Safari 16+

- core/src/display_object/text.rs
> core: Replace GcCell with Gc in Text

- core/src/display_object/graphic.rs
> core: Replace GcCell with Gc in Graphic

- core/src/display_object/stage.rs
> core: Replace GcCell with Gc in Stage

- core/src/avm2/globals/flash/system/Capabilities.as
Add missing properties and methods along with version constraints.
> avm2: Stub flash.system.Capabilities

- core/src/streams.rs
Adding `NetStreamSource` makes it easier to reset buffer-related data. Instead of individually resetting fields, all appropriate fields are inside `NetStreamSource`, which can be replaced wholly.
> core: Add `NetStreamSource` for better buffer management

- core/src/avm2/globals/flash/globalization/CurrencyFormatter.as
Fix missing imports.
* Fixes https://github.com/ruffle-rs/ruffle/issues/20371
> avm2: Fix CurrencyFormatter stubs

- .editorconfig
It makes sure we're using consistent text style across the repository.
> chore: Add basic .editorconfig

- desktop/src/gui/blit.wgsl
- render/webgl/shaders/bitmap.frag
- render/webgl/shaders/gradient.frag
- render/wgpu/shaders/bitmap.wgsl
- render/wgpu/shaders/common.wgsl
- render/wgpu/shaders/gradient.wgsl
Reformat shaders: fix some obvious formatting errors and fix .editorconfig violations.
> chore: Reformat shaders

- web/packages/core/src/internal/ui/panic.tsx
Load failed is the iOS failed to fetch error: https://stackoverflow.com/a/77129454
> web: Add panic case for iOS SWF fetch failure

- render/canvas/src/lib.rs
* Fixes https://github.com/ruffle-rs/ruffle/issues/20467
* Fixes https://github.com/ruffle-rs/ruffle/issues/18834
* Fixes https://github.com/ruffle-rs/ruffle/issues/15795
* Fixes https://github.com/ruffle-rs/ruffle/issues/13995
* Fixes https://github.com/ruffle-rs/ruffle/issues/12599
> render: Do not render empty bitmap in canvas renderer

- web/packages/selfhosted/test/integration_tests/external_interface/test.ts
- web/packages/selfhosted/test/integration_tests/programmatic_events/test.ts
- web/packages/selfhosted/test/integration_tests/url_rewrite_rules/test.ts
- web/packages/selfhosted/test/js_api/exposed.ts
- web/packages/selfhosted/test/js_api/load.ts
- web/packages/selfhosted/test/js_api/metadata.ts
- web/packages/selfhosted/test/utils.ts
This is no longer necessary following https://github.com/webdriverio/webdriverio/pull/14465
> web: Remove as unknown from tests that no longer need that

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/debug_ui/display_object.rs
- deny.toml
- desktop/Cargo.toml
- desktop/src/cli.rs
- desktop/src/gui/controller.rs
- desktop/src/gui/dialogs/bookmarks_dialog.rs
- desktop/src/gui/menu_bar.rs
- exporter/src/main.rs
- render/naga-agal/src/builder.rs
- render/naga-agal/src/varying.rs
- render/naga-pixelbender/src/lib.rs
- render/wgpu/src/backend.rs
- render/wgpu/src/pipelines.rs
- render/wgpu/src/utils.rs
- tests/tests/environment.rs
We may have to remove wgpu tracing (at least temporarily):
- https://github.com/emilk/egui/pull/6744
- https://github.com/emilk/egui/pull/6860
- https://github.com/gfx-rs/wgpu/issues/5974
- https://github.com/gfx-rs/wgpu/pull/5897
- https://github.com/gfx-rs/wgpu/issues/5121
> chore: Update to wgpu 25 and egui git main

- core/src/avm2/activation.rs
- core/src/avm2/error.rs
- core/src/avm2/globals/array.rs
- core/src/avm2/object.rs
- core/src/avm2/object/script_object.rs
- core/src/avm2/object/vector_object.rs
- core/src/avm2/value.rs
- core/src/avm2/vector.rs
- tests/tests/swfs/from_avmplus/as3/Vector/fixed_length/test.toml
- tests/tests/swfs/from_avmplus/as3/Vector/initializer_expressions/test.toml
- tests/tests/swfs/from_avmplus/as3/Vector/nonindexproperty/v10/test.toml
- tests/tests/swfs/from_avmplus/as3/Vector/nonindexproperty/v11/test.toml
- tests/tests/swfs/from_avmplus/as3/Vector/optimization_tests/test.toml
- tests/tests/swfs/from_avmplus/as3/Vector/vectorIndexRangeExceptions/test.toml
These are unlikely to have any impact on real code, but they let 7 avmplus tests pass (progress on #12321). We also now have a fast path for setting integer properties on vectors.
> avm2: Vector indexing improvements

- core/src/avm1/value.rs
- core/src/display_object/avm1_button.rs
- core/src/display_object/graphic.rs
- core/src/display_object/morph_shape.rs
- core/src/display_object/movie_clip.rs
- core/src/display_object/stage.rs
- core/src/display_object/text.rs
- core/src/font.rs
- core/src/html/dimensions.rs
- core/src/library.rs
- core/src/system_properties.rs
- desktop/src/gui/locale.rs
- render/canvas/src/lib.rs
- render/naga-agal/src/types.rs
- render/webgl/src/lib.rs
- render/wgpu/src/mesh.rs
- render/wgpu/src/surface/target.rs
- render/wgpu/src/utils.rs
- web/src/audio.rs
- web/src/ui.rs
Remove some dead code and unnecessary `allow(dead_code)` attributes.
> chore: Clean up dead code

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/pixel_bender.rs
- render/Cargo.toml
- render/naga-pixelbender/src/lib.rs
- render/wgpu/Cargo.toml
- render/wgpu/src/pixel_bender.rs
It looks like the usage of Result in that file was completely for nothing, no function ever returned an Err anywhere :sweat_smile:
I have even more refactors in mind, but I wanted to make the PR reviewable.
> pixelbender: Remove Result usage, minor code improvements

- web/Cargo.toml
- web/common/Cargo.toml
> chore: Minor Cargo.toml fixes

- core/src/avm2/globals/string.rs
- tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_7_2/test.toml
- tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_8_3/test.toml
> Improve String.lastIndexOf and String.split accuracy

- render/wgpu/src/context3d/mod.rs
Avoids allocating a temporary Vec when the texture needs to be padded.
> render: Always copy directly to wgpu buffer in `CopyBitmapToTexture`.

- core/src/avm2/globals/Object.as
- core/src/avm2/globals/object.rs
Object is also being constructed when called.
> avm2: Use ConstructOnCall on Object

- tests/tests/swfs/from_avmplus/README.md
- tests/tests/swfs/from_shumway/README.md
Add README for from_shumway and fix headings in from_avmplus's README.
> tests: Update READMEs for ported tests

- core/src/avm2/activation.rs
- core/src/avm2/value.rs
> avm2: Use the fast path for Value::Number integers in op_get_property_fast/op_set_property_fast

- core/src/debug_ui/movie.rs
- Improve Know Movie List in debug UI by replacing Grid with TableBuilder.
- - Auto Adjust with content/row size. 
- - Better scrolling.
- Improve search and button layout by making it more responsive.
- - Auto Adjust with widow resize.
> debug_ui: Improve movie list display responsiveness 

- desktop/assets/texts/th-TH/network_access_dialog.ftl
- web/packages/extension/assets/_locales/es/messages.json
- web/packages/extension/assets/_locales/fi/messages.json
- web/packages/extension/assets/_locales/th/messages.json
Split from https://github.com/ruffle-rs/ruffle/pull/21671; contains only reviewed & non-controversial translations.
> chore: Update translations from Crowdin

- core/src/avm2/activation.rs
This allows `array[i1 * i2 + i3]` to use an int-indexing fast path, instead of coercing a float to string and then parsing it back.
In https://github.com/ruffle-rs/ruffle/issues/11935 , for me in "generating world" it speeds up from ~4.5s to 2.8s.
This does slightly hurt code that just do regular float multiplies, but it shouldn't be noticeable.
> avm2: Add an int*int -> int path to help other fast paths

- web/packages/extension/manifest.json5
> extension: Don't run on Kick

- core/src/avm2/globals/flash/display/MovieClip.as
> avm2: Add stubs for MovieClip.trackAsMenu

- web/packages/selfhosted/test/integration_tests/mouse_wheel_avm2/test.ts
This will hopefully help in debugging flakiness of this test.
> web: Merge assertions in integration_tests/mouse_wheel_avm2

- web/packages/selfhosted/test/utils.ts
This should improve debuggability of tests in runners.
> web: Log traces into the console during tests
