core/src/avm2/object.rs
core/src/avm2/object/class_object.rs
core/src/avm2/script.rs
core/src/avm2/vtable.rs

~~The only reason this is a draft, is because I want to test this on more GH issues first.~~ I'm also admittedly not 100% sure this is entirely correct (but feels way better by instinct).
This is supposed to fix https://github.com/ruffle-rs/ruffle/issues/5897 , https://github.com/ruffle-rs/ruffle/issues/7079 and possibly all issues involving the panic
```
panicked at 'called `Option::unwrap()` on a `None` value', core/src/avm2/object.rs:308
```
The issue was that "top-level functions" (scripts containing `method trait`s*) were created while resolving vtable of the global object, which is subtly different than resolving vtables of normal classes, as the `global`'s class is weird. In general, since all the global objects belong to the same class but have different vtables and scopes, this …

avm2: Pull methods' scopes from vtable, not class

---

core/src/display_object/movie_clip.rs

AS3 display objects *always* get `added` and `addedToStage` events, even the root movie clip. We actually add the root clip *before* its constructor runs, so it will miss those events. This minor hack fixes that by checking if we just constructed the root clip and, if so, fires those events.
There are no tests because the only tests that revealed this behavior are part of #5876 and test other behaviors

AVM2: Manually fire late `added`/`addedToStage` events on root clips

---

core/src/avm2/globals/flash/net/url_loader.rs

This ensures that a sealed subclass can still access it.

avm2: Declare 'dataFormat' property on URLLoader

---

core/src/avm2.rs
core/src/avm2/activation.rs
core/src/avm2/class.rs
core/src/avm2/globals.rs
core/src/avm2/globals/flash/events/eventdispatcher.rs
core/src/avm2/object/array_object.rs
core/src/avm2/object/bitmapdata_object.rs
core/src/avm2/object/bytearray_object.rs
core/src/avm2/object/class_object.rs
core/src/avm2/object/date_object.rs
core/src/avm2/object/dictionary_object.rs
core/src/avm2/object/dispatch_object.rs
core/src/avm2/object/domain_object.rs
core/src/avm2/object/event_object.rs
core/src/avm2/object/function_object.rs
core/src/avm2/object/loaderinfo_object.rs
core/src/avm2/object/namespace_object.rs
core/src/avm2/object/primitive_object.rs
core/src/avm2/object/proxy_object.rs
core/src/avm2/object/qname_object.rs
core/src/avm2/object/regexp_object.rs
core/src/avm2/object/script_object.rs
core/src/avm2/object/sound_object.rs
core/src/avm2/object/soundchannel_object.rs
core/src/avm2/object/stage_object.rs
core/src/avm2/object/textformat_object.rs
core/src/avm2/object/vector_object.rs
core/src/avm2/object/xml_object.rs
core/src/display_object/stage.rs

No functional changed intended.
During this work, I noticed some minor inconsistencies (pretty sure `(function(){}).prototype` shouldn't be class-less - in fact I kinda doubt the entire idea of "class-less ES3 objects"; also most "bare objects" probably shouldn't be bare) but I didn't fix them here; I left TODOs for these.
tldr of the changes:
- removed `SystemPrototypes`, as 99% of time we can use `class.prototype()`, and the other times (in `globals.rs`) we happen to have access to prototype objects at hand anyway
- folded all the similar weird object creation functions (`ScriptObject::bare_object/object/instance/bare_instance`) into one more explicit `ScriptObject::custom_object` with the intention to _not use it at all_ outside of low-level code
- introduced a simpler API …

AVM2: Remove SystemPrototypes, refactor ScriptObject creation API

---

Cargo.lock
core/src/avm1/globals/bitmap_data.rs
core/src/avm1/object/bitmap_data.rs
core/src/backend/render.rs
core/src/bitmap/bitmap_data.rs
render/canvas/Cargo.toml
render/canvas/src/lib.rs
render/webgl/Cargo.toml
render/webgl/src/lib.rs
render/wgpu/Cargo.toml
render/wgpu/src/lib.rs

Currently, all three render backends hold on texture-related
resources indefinitely (`register_bitmap` pushes to a `Vec`,
and never removes anything). As a result, the resources used
by the render backend (which may include GPU memory) will grow
over time, even if the corresponding `BitmapData` has been deallocated.
This commit adds a new `unregister_bitmap` method, which is called from
`BitmapData.dispose`. All render backs are changed to now use an
`FnvHashMap<BitmapHandle, _>` instead of a `Vec`, allowing us to
remove individual entries.
Currently, we only call `unregister_bitmap` in response to
`BitmapData.dispose` - when `BitmapData` is freed by the
garbage collector, `unregister_bitmap` is *not* called.
This will be addressed in a future PR.

Free render backend resources on `BitmapData.dispose`

---

core/src/config.rs
core/src/display_object/stage.rs
core/src/font.rs
swf/src/types.rs

It's available since stable Rust 1.62.0.

chore: `derive(Default)` for enums

---

core/src/events.rs
core/src/loader.rs

Fixes part of #2693: triggering `onClipEvent(data)` makes the buttons visible and clickable but the text will always display "Exercice 1" - I believe this is the same issue as #2181 which has nothing to with onData.
I made [this test](https://github.com/ruffle-rs/ruffle/files/9005721/test_ondata.zip) which passes when run manually but fails when added to `regression_tests.rs` for some reason.

avm1: Fire `onData` function and event when calling `loadVariables`

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
Cargo.lock
core/Cargo.toml
exporter/src/main.rs
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
render/wgpu/shaders/bitmap.wgsl
render/wgpu/shaders/color.wgsl
render/wgpu/shaders/common.wgsl
render/wgpu/shaders/copy_srgb.wgsl
render/wgpu/shaders/gradient.wgsl
render/wgpu/src/lib.rs
render/wgpu/src/pipelines.rs
render/wgpu/src/target.rs
render/wgpu/src/uniform_buffer.rs
tests/tests/regression_tests.rs
web/Cargo.toml
web/README.md
web/common/Cargo.toml
web/src/lib.rs

Based on the work in #6717, plus additional adaptions mentioned in
https://github.com/gfx-rs/wgpu/blob/master/CHANGELOG.md#wgpu-013-2022-06-30,
and more not-mentioned but required changes.
Also bump `wasm-bindgen` to `0.2.81` (along with its helper crates), as
required by the new `wgpu` version.
Note that I don't fully understand some of the required changes, notably:
* `wgpu::PresentMode::Mailbox` no longer works on my machine (Windows 11) -
The `wgpu` documentation says that `wgpu::PresentMode::Fifo` is the
only guaranteed to be supported, so I switched over to it instead.
* `self.staging_belt.recall()` doesn't return a `Future` anymore -
I assume it became synchronous so I simply removed the `executor`
from there.

wgpu: Bump to `0.13.0`

---

render/common_tess/src/lib.rs
render/webgl/src/lib.rs
render/wgpu/src/lib.rs

Adjust `common_tess` to add an additional `mask_index_count` to
draws. This is used to not render strokes when drawing a shape as
a mask stencil.
Fixes #7027.

webgl/wgpu: Omit strokes when drawing a mask stencil

---

core/src/avm1/globals/bevel_filter.rs
core/src/avm1/globals/displacement_map_filter.rs
core/src/avm1/globals/gradient_bevel_filter.rs
core/src/avm1/globals/gradient_glow_filter.rs
wstr/src/buf.rs
wstr/src/ptr.rs

Similarly to how `str` implements `ToOwned`, and `From<&str> for String` forwards to `to_owned()`.
This will allow defining `Cow<WStr>`.

wstr: Implement `ToOwned` for `WStr`

---

web/packages/core/src/ruffle-player.ts

The [HTML `<base>` tag](https://www.w3schools.com/TAGs/tag_base.asp) changes the base URL of all relative links on a page, including links in `src` attributes of `embed` tags and `movie` params of `object` tags. Ruffle was using `document.location.href` to construct relative SWF URLs, which does not account for the document base being changed by the `<base>` tag. Use `document.baseURI` instead.
Fixes #7357.

web: Construct relative SWF URLs using document base

---

core/src/avm1/value.rs
core/src/avm2/property.rs
render/canvas/src/lib.rs
render/common_tess/src/lib.rs
render/wgpu/src/lib.rs

Though https://github.com/rust-lang/rust-clippy/pull/8355 has been
merged, it seems to still report false-positives on nightly channel.
For now just fix the instances reported by stable clippy, and keep
`needless_borrow` allowed.

chore: Fix `needless_borrow` clippy lints

---

web/packages/demo/README.md
web/packages/demo/www/index.css
web/packages/demo/www/index.html
web/packages/demo/www/index.js

**Requires new swfs.json!** See changes to the demo README.
Change the Sample SWF dropdown to reflect that the Ruffle logo is shown by default:
Remove the "None" option from the dropdown and the associated placeholder HTML/CSS. When a local SWF file is loaded, the dropdown will appear blank.
Add support for an optional `config` for each SWF in swfs.json. Also make the `type` value optional; if omitted, the SWF will be shown above the Animations and Games in the dropdown.
Also change the styling of the local file input to make it tabbable.

demo: Improve Sample SWF dropdown

---

core/src/avm2/regexp.rs

`char_indicies()` isn't really needed because the position is never
used.
So use the simpler `chars()` method instead.

avm2: Small cleanup in `RegExp::effective_replacement`

---

core/src/avm1/globals/movie_clip.rs
core/src/shape_utils.rs
render/canvas/src/lib.rs

Render strokes with the proper width in the canvas backend:
* Stroke width gets scaled based on the shape's transform and line style scaling settings
* Minimum 1 pixel width (1 twip hairline strokes get scaled to 1 pixel)
TODO:
Fixes the line widths in #751 in the canvas backend.

canvas: Scale stroke width based on shape transform

---

web/packages/core/src/ruffle-player.ts

When `displayRootMovieDownloadFailedMessage()` shows the CORS workaround screen, it should also hide the loading screen, otherwise the CORS workaround screen won't actually be visible.

web: Hide loading screen when root movie download fails

---

core/src/display_object.rs
swf/src/types/twips.rs

Use regular subtraction, since it should never overflow.
Also remove `swf::Twips::saturating_sub`, which is now unused.

core: Don't use `saturating_sub` for `width` / `height`

---

web/packages/core/src/index.ts
web/packages/core/src/public-api.ts
web/packages/core/src/source-api.ts
web/packages/demo/www/index.js
web/packages/extension/src/player.ts
web/packages/extension/src/ruffle.ts
web/packages/selfhosted/js/ruffle.js

As a first step towards a simpler Web API, convert `SourceAPI` from
a class to a constant object, under the assumption that `SourceAPI`
isn't a public Ruffle API and as such is safe to be changed.
As a result the different `ruffle-core` users don't need to construct
a new `SourceAPI` instance before calling `PublicAPI.negotiate()`.

web: Make `SourceAPI` a singleton

---

core/src/avm1/globals/movie_clip.rs

Instead of a directly initialzed `Matrix`.

avm1: Use `Matrix::scale`

---

render/webgl/src/lib.rs

This basically reverts #5737 and #6458 for the WebGL backend, which
regressed a bug where setting the style `display: none;` to a Ruffle
player logged many WebGL warnings to the console. This happened
because `renderbuffer_width` and `renderbuffer_height` were set to zero,
leading to problems when trying to pass them to WebGL APIs.
Avoid such situation by ensuring that `renderbuffer_width` and
`renderbuffer_height` are at least `1`, exactly as done before.
Also add a comment that explains why `.clamp()` isn't used.
Fixes #1264.

webgl: Avoid zeroing `renderbuffer_{width,height}`

---

core/src/display_object/edit_text.rs
core/src/transform.rs

Simply use `Matrix::translate` directly, which is more explicit and
intuitive.

core: Remove `From<Position<Twips>> for Transform`

---

Cargo.lock

This works around https://github.com/pdeljanov/Symphonia/issues/148, hopefully making the CI pass for https://github.com/ruffle-rs/ruffle/pull/7470.

chore: Run `cargo update`

---

core/src/backend/audio.rs
core/src/backend/audio/decoders/mp3.rs
core/src/display_object/movie_clip.rs
web/Cargo.toml
web/packages/core/src/ruffle-imports.ts
web/src/audio.rs

* Add a new `WebAudioMixerBackend` that uses the `AudioMixer` on web, outputting the audio stream via a pair of `AudioBufferSourceNode`s.
* Use [`symphonia`](https://github.com/pdeljanov/Symphonia) for MP3 decoding on web.
This gives consistent audio between the web and desktop builds.  On web, it should significantly improve loading performance and memory usage, as the AudioMixer can decode the audio on demand, as opposed to decoding completely on load using `decodeAudioData`. This also allows us to simplify some of the preloading code, as the API was contorting itself to deal with SoundStreamBlock data within the limitations of WebAudio.
Performance may be more intensive during playback as audio is decoded on the fly and not leveraging the browser's native audio capabilities. Underruns …

web: Decode and mix audio via Rust

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
Cargo.lock
core/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
web/Cargo.toml
web/README.md
web/common/Cargo.toml

As usual, also bump its helper crates (`js-sys`, `web-sys` and
`wasm-bindgen-futures`) to the latest versions.

web: Bump wasm-bindgen to 0.2.82

---

Cargo.lock
web/Cargo.toml

Both `byteorder` and `fnv` are no longer used since #4273.

web: Remove some unused dependencies

---

core/src/display_object/movie_clip.rs

Hi,
https://github.com/rust-lang/rust/pull/98835 fixes a rustc bug that makes it incorrectly accepts the following code:
```rust
fn test<'a: 'a>() { // 'a is longer than the entire function body
let f = |_: &'a str| {}; // expects an argument that lives as long as 'a
f(&String::new()); // the passed reference is shorter that `'a`
}
```
The crater run found that ruffle relies on this bug. I'm not sure when this change reaches stable, if ever, but it's better to not rely on such a bug. This PR tries to fix this.
If you have an opinion on this change, please let me know here or  by commenting on the PR.
You can install and test the toolchain locally by running the command: `rustup-toolchain-install-master cb1f7c96119295882e08b09b4bd01051669c071b`

don't rely on a rustc bug

---

.github/workflows/test_web.yml
Cargo.lock
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
web/Cargo.toml
web/common/Cargo.toml
web/packages/core/package.json

The [WebGPU spec removed `depth24unorm-stencil8`](https://github.com/gpuweb/gpuweb/pull/2950) texture format, and therefore `GpuTextureFormat::Depth24unormStencil8` binding is removed in `web-sys` 0.3.59.  The current published `wgpu` crate still expects this to exist.
`wgpu` master has updated (https://github.com/gfx-rs/wgpu/pull/2813), but we have to wait for a new version to be published. Thus is the life of relying on an unstable API. :-)
Adjust CI to ensure that the web tests build with --all-features to avoid this in the future.

web: Rollback to web-sys 0.3.58

---

swf/src/avm2/read.rs

this change follows section 4.5 of https://www.adobe.com/content/dam/acom/en/devnet/pdf/avm2overview.pdf (dead link, use an archive)

avm2: Fix parsing of methods with more than 127 arguments

---

core/src/avm2/object.rs
core/src/avm2/property.rs
core/src/avm2/vtable.rs

Calling `get_trait` copies the returned `Property`, so the caching
we performed in `PropertyClass` was never actually getting used.
Instead, we now store our `PropertyClass` values in a `Vec`
indexed by slot id. `set_property` and `init_property` now perform
coercions by going through the `VTable,` which writes the updated
`PropertyClass` back into the array.

avm2: Store PropertyClass in `VtableData`

---

core/src/backend/audio/mixer.rs

The same way as it is done in `decoders::make_decoder()`.
Fixes the regression caused by #4273 on https://z0r.de/3682 as reported in https://github.com/ruffle-rs/ruffle/issues/7524#issuecomment-1200464340.

audio: Handle `AudioCompression::UncompressedUnknownEndian` in `AudioMixer`

---

core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/avm2/globals/flash/display/loader.rs

With these changes, https://www.newgrounds.com/portal/view/432872 _almost_ works - as in, the game area actually loaded and animated correctly. With exceptions:
- I needed to modify the swf to disable mochiads (we need more URL/Loader related stubs for this to not crash)
- Without `KeyboardEvent` plugged in, you can't actually do anything after starting the game
The `BitmapData` implementations are copied from AVM1; I also dropped the alpha bitmap support from `copyPixels` for now.

avm2: Several minor implementations and stubs

---

core/src/avm1/activation.rs
core/src/avm1/globals/load_vars.rs
core/src/avm1/globals/movie_clip.rs
core/src/backend/navigator.rs
desktop/src/navigator.rs
web/src/navigator.rs

Make the `target` parameter just a `String` instead of an `Option<String>`.
`None` is not needed as it's totally equivalent to an empty string.

core: Require `target` in `NavigatorBackend::navigate_to_url`

---

core/src/bitmap.rs
scanner/src/ser_bridge.rs
swf/src/types.rs
wstr/src/common.rs
wstr/src/parse.rs
wstr/src/pattern.rs

Fixes some warnings when running `cargo doc`, specifically some bare urls and broken intra doc links.

Fix warnings with cargo doc

---

core/src/avm1/activation.rs

This fixes the neopets score submission, #7337
There's probably a bunch more edge cases surrounding these but I don't have the capability to make an extensive test suite at the moment.

avm1: loadMovieNum with blank url is an unload, not a load

---

core/src/avm1/activation.rs
core/src/context.rs
core/src/player.rs

We're missing cases (like #554) where the infinite loop is across multiple AVM activations. They'll eat all the memory and crash, instead of being caught by our timeout check.
This seems to match the Flash Player's behaviour more closely too.
(also hi <3)

core: Track 'actions since timeout check' globally

---

Cargo.lock
core/src/lib.rs
exporter/Cargo.toml
exporter/src/main.rs
render/wgpu/src/globals.rs
render/wgpu/src/lib.rs
render/wgpu/src/uniform_buffer.rs
tests/tests/regression_tests.rs

This changes the Descriptor in wgpu to be immutable and global again, and that allows exporter to reuse it in multiple threads. This speeds it up... a bunch. :D
Error handling is a bit wonky because we're still using `Box<dyn std::error::Error>` a bunch of places in core - that needs to change at some point. I convert them to strings here, just so it can be `Send`.
A possible future change that this unlocks is to reuse a single Descriptor on web, to skip a bit of needless overhead on pages with more than one swf loaded.

exporter: Multithread exports of directories

---

core/src/avm1/activation.rs
core/src/avm1/globals/movie_clip.rs
core/src/player.rs

Fixes https://github.com/ruffle-rs/ruffle/issues/7587 .
The issue was that the script does
```js
startDrag(obj,0);
stopDrag();
return eval(obj._dropTarget);
```
and we never got the opportunity to call `update_drag()` to set `obj._dropTarget`. I tested that FP7 sets `obj._dropTarget` after `stop` was called (but, weirdly, not immediately after `start` was called).

avm1: Update drag in stopDrag() in case it wasn't called before

---

.github/workflows/test_rust.yml

In order to prevent future warnings on malformed documentation comments.

ci: Check documentation

---

core/src/avm2/object/class_object.rs
core/src/avm2/object/script_object.rs

Before: `ClassObject(GcCell(Gc { ptr: 0x7f69f8300a28 }))`
After:  `ClassObject { name: flash.net::URLRequest, ptr: 0x7fe9cc2e7820 }`

avm2: Show class name in `ClassObject` Debug impl

---

core/src/avm2/globals/flash/net/URLRequest.as

This allows Wonderputt to get further (it deliberately assigns
'null' to 'URLRequest.data'). We throw an exception for any other
value, to prevent confusing errors caused by attempting an
unexpected request to a web server with a missig body.

avm2: Stub URLRequest.data

---

core/src/avm2/globals/flash/system/application_domain.rs

Many of the class property defintiions were wrong -
instance methods were defined as class properties,
and class properties were defined as instance properties.

avm2: Fix ApplicationDomain property declarations

---

core/src/player.rs

Hopefully after this change, any differences between two images of a movie will be caused by changes in Ruffle only

core: Use fixed seed when using deterministic feature

---

exporter/src/main.rs
render/wgpu/src/lib.rs
render/wgpu/src/target.rs
tests/tests/regression_tests.rs

Hard to give test cases for this as it's very hardware dependent.

wgpu: Avoid panics when attempting to create a texture larger than the device supports

---

core/src/avm2/globals/flash/events/TimerEvent.as

This is the last stub needed for Wonderputt to reach the
main game screen.
As far as I know, ActionScript cannot observe a frame being rendered,
so implementing this method isn't actually necessary for correctness.
The benefit of implementing this would be to make certain animations
appear smoother, since we'll render changes to the scene without
needing to wait for the next frame. However, actually rendering
*immediately* after the event would require some refactoring -
we have a `&mut UpdateContext` while running timers, but we'd need
to bail out and obtain a `&mut Player`.

avm2: Stub TimerEvent.updateAfterEvent

---

core/src/backend/navigator.rs
web/Cargo.toml
web/src/navigator.rs

Store `base_url` as `Option<Url>` instead of `Option<String>`, so
we don't need to parse it on each URL resolve.

web: Refactor `WebNavigatorBackend`

---

web/src/audio.rs

Avoid stuttering on some browser & hardware configurations.

web: Bump audio buffer size to 4096

---

Cargo.lock
wstr/Cargo.toml
wstr/src/buf.rs
wstr/src/common.rs
wstr/src/ptr.rs

Shrink WString to 16 bytes on 64-bits targets by introducing an explicit `WStrMetadata` type that is always 4 bytes wide, even on 64-bits targets.
Note the trickier logic in `WString::from_buf`, to properly handle the case where the capacity is above the maximum allowed length.

wstr: Make WString 16 bytes on all targets

---

swf/src/avm2/types.rs

https://github.com/rust-lang/rust-clippy/issues/8867 is fixed, and
a false positive is no longer reported.

swf: Remove `#[allow(clippy::derive_partial_eq_without_eq)`

---

.github/workflows/release_nightly.yml
.github/workflows/test_rust.yml
.github/workflows/test_web.yml

Because GitHub is really slow in moving the `ubuntu-latest` alias over to `22.04`, and it's starting to cause issues with the desktop build.
This is an attempt to resolve #7222 according to the recent discussion on Discord.

ci: Explicitly use `ubuntu-22.04` image for all CI workflows

---

render/src/utils.rs
render/wgpu/src/target.rs

The captured WGPU texture uses premultiplied alpha.
This image gets saved as a PNG, so it should use straight alpha.
Note that all of our current image tests have 'alpha = 1.0' for all
of the pixels, so this currently has no effect.

wgpu: Convert from premultiplied to straight alpha when capturing image

---

core/src/display_object.rs
render/webgl/src/lib.rs
render/wgpu/src/pipelines.rs

Got a little too zealous in #7484. Avoid blend modes except ADD and SUBTRACT until they can be implemented properly.

render: Disable most blend modes

---

core/Cargo.toml
core/src/display_object/movie_clip.rs
tests/Cargo.toml

Ruffle keeps track of all movie clips' timelines via a struct member called `tag_stream_pos`. This is updated whenever a clip runs a frame, loops back to the start, or is given a goto command from script code, and should always point to the end of the current frame's tags (with some exceptions). If this invariant is broken, the tag stream is said to have *desynchronized*. The timeline no longer works correctly in the presence of fast-forwarding operations until a rewind occurs. The current implementation of AVM2 timeline operations suffers from a number of goto-related bugs that trigger desyncs.
This PR adds a new feature called `timeline_debug`, analogous to the `avm_debug` feature that prints out every stack operation. When enabled, `timeline_debug` will print out every goto, as well as …

core: Add `timeline_debug` feature that logs all gotos and asserts if they desync

---

core/src/backend/audio.rs
core/src/backend/audio/mixer.rs
core/src/player.rs
web/packages/core/src/ruffle-player.ts
web/src/lib.rs

It was requested by folks on Discord a couple times. Would also come in handy if we ever add a volume slider to extension or context menu.
Downside: this is not a _master_ player volume, it's the stage volume - it can be overridden by the movie with a simple AS `new Sound().setVolume(100);`. In the future, we might want the Player API to be able to set both "stage-visible volume" and "master player (invisible to AS) volume" independently.

web: Allow modifying stage volume via JS

---

core/src/avm1/activation.rs
core/src/avm2.rs
core/src/backend/audio/decoders.rs
core/src/binary_data.rs
core/src/display_object/avm1_button.rs
core/src/display_object/movie_clip.rs
core/src/display_object/video.rs
core/src/tag_utils.rs

This removes a bunch of unwraps. We had no good way of handling the None cases - but in theory operating on an empty slice is completely fine (and a technically valid situation regardless).
Although I can't reproduce these issues anymore, this fixes:
Fixes https://github.com/ruffle-rs/ruffle/issues/2737
Fixes https://github.com/ruffle-rs/ruffle/issues/5006
Fixes https://github.com/ruffle-rs/ruffle/issues/5830
Fixes https://github.com/ruffle-rs/ruffle/issues/6736

core: Made SwfSlice methods always return something valid

---

core/src/avm2/globals/flash/display/stage.rs
core/src/display_object/stage.rs
core/src/font.rs
core/src/lib.rs
core/src/player.rs
desktop/src/main.rs
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/webgl/src/lib.rs
render/wgpu/src/lib.rs
render/wgpu/src/target.rs
tests/tests/regression_tests.rs
web/src/lib.rs

Previously, the viewport height and width were stored in
both `Stage` and the `RenderBackend`. Any changes to the viewport
dimensions (e.g. due to window resizing) needed to be updated in both
places to keep our handling of the viewport consistent.
This PR adds a new `ViewportDimensions` type, which holds the
width, height, and scale factor. It is stored inside the
`RenderBackend` impl, and is retrieved using the newly added
method `RenderBackend.get_viewport_dimensions`. After a `Player`
has been constructed, any code that needes access to the viewport
dimensions will ultimate go through this method.
Unfortunately, `Stage` needs to use the viewport dimensions
in `build_matrices`. Therefore, any code modifying the viewport
dimensions should go through `player.set_viewport_dimensions`, …

core: Only store viewport dimensions in `RenderBackend`

---

core/src/avm2/globals/flash/net/URLRequest.as

This was missed when I added 'method'

avm2: Set URLRequest.method default to GET

---

core/src/display_object/edit_text.rs

This PR fixes the way word-wrap text boxes are rendered. Here are some "before-and-after" snapshots demonstrating the effects of this fix for the game "Sonny":

core: Fix incorrect rendering of word-wrap text boxes (close #1095)

---

tests/Cargo.toml
tests/tests/regression_tests.rs

This should speed up developer workflows when working on non-image
related changes. CI will still run all image tests.

tests: Only require `ruffle_render_wgpu` dependency with 'imgtests'

---

core/build_playerglobal/src/lib.rs
core/src/avm2.rs
core/src/avm2/globals.rs
core/src/display_object/movie_clip.rs
core/src/tag_utils.rs
swf/src/read.rs
swf/src/types.rs
swf/src/write.rs

Extract `swf::Reader::read_do_abc()` which, as the name suggests,
reads a `DoAbc` tag, and use it before calling to `Avm2::load_abc`.
Finally, introduce `DoAbcFlag` using `bitflags`.
This greatly simplifies the ABC loading code.

swf: Simplify `DoAbc` tag handling

---

core/src/font.rs
core/src/library.rs
core/src/player.rs

It is always called with the same known data, which should parse
successfully.

core: Make `Player::load_device_font` infallible

---

core/build_playerglobal/src/lib.rs
core/src/avm2/globals.rs
core/src/avm2/globals/Math.as
core/src/avm2/globals/Toplevel.as

Declare `NaN`, `Infinity` and `undefined` in ActionScript, similarly
to how `avmplus` does in its `actionscript.lang.as`.
Note that `null` is only removed, without an ActionScript declaration,
as it seems like `avmplus` neither declares it. Probably `null` is
only usable as a compile-time constant.

avm2: Port toplevel constants to ActionScript

---

web/packages/core/src/ruffle-player.ts

Edit: No longer clashes with #7534. Now just adds a new context menu item, and adds metadata to the panic info. The function that displayed the orange warning screen was removed in the third commit. That commit can be reverted if that function is desired, but "Copy Debug Info" fulfills a similar purpose.

web: Add metadata to error info and add Copy Debug Info context menu item

---

web/packages/core/src/config.ts
web/packages/core/src/load-ruffle.ts
web/packages/core/src/polyfills.ts
web/packages/core/src/public-api.ts
web/packages/core/src/public-path.ts
web/packages/core/src/ruffle-object.ts
web/packages/core/src/ruffle-player.ts
web/packages/core/tsconfig.json
web/packages/extension/src/utils.ts
web/packages/extension/tsconfig.json

Configure [`importsNotUsedAsValues`](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues)
to `error`, and switch from `import` to `import type` where needed.
Also remove the `strict` configuration, as it's inherited from
`@tsconfig/recommended`.

web: Disallow imports not used as values

---

core/src/avm2/globals/array.rs

Previously, it was only declared in the AS3 namespace. However,
some SWFs look it up as a public method.

avm2: Declare 'Array.concat' as a public method

---

core/src/avm2/globals.rs
core/src/avm2/globals/flash/events/KeyboardEvent.as
core/src/player.rs

The 'charCode' and 'keyCode' properties are now implemented
on `KeyboardEvent`
The input injection code we use does not support keyboard events,
so we can't yet write a regression test for this. However,
both 'You need to burn the rope' and 'This is the Only Level TOO'
now properly handle keyboard events with this PR.

avm2: Fire KeyboardEvent.KEY_UP and KeyboardEvent.KEY_DOWN

---

web/packages/core/src/ruffle-player.ts

It won't work anyway, since the Clipboard API doesn't work in insecure contexts.

web: Don't add debug info to context menu in insecure context

---

core/Cargo.toml
core/src/backend/audio.rs
core/src/backend/audio/decoders.rs
core/src/backend/audio/mixer.rs
desktop/Cargo.toml
web/Cargo.toml

Shaves up to 3 seconds from test time for me, because we were compiling a lot of dependencies that we didn't need.
I wanted to go with a separate crate like render & video, but it's a little too tangled in our code right now.
Benchmarks:
| Command          | Mean [s] | Min [s] | Max [s] | Relative |
|:-----------------|---:|---:|---:|---------:|
| `cargo test`     | 96.985 ± 0.430 | 96.231 | 97.940 |     1.00 |
| + without mp3    | 96.574 ± 0.386 | 96.067 | 97.416 |     0.99 |
| + without nelly  | 95.431 ± 0.946 | 94.551 | 97.471 |     0.98 |
| + without audio  | 94.184 ± 0.199 | 93.848 | 94.417 |     0.97 |

core: Make audio backend more optional

---

core/src/avm1/globals/movie_clip.rs
core/src/display_object/container.rs

The `less_than` parameter remained just `Depth::MAX` since #7199,
which makes it useless. As such it can be removed.

core: Simplify `DisplayObjectContainer::highest_depth`

---

Cargo.lock
core/src/bitmap/bitmap_data.rs
core/src/display_object.rs
core/src/display_object/bitmap.rs
core/src/display_object/edit_text.rs
core/src/display_object/stage.rs
render/Cargo.toml
render/src/bitmap.rs
render/src/bounding_box.rs
render/src/transform.rs

It was only used to make structs `#[derive(gc_arena::Collect)]`, and
generally it doesn't make much sense that `render` needs to be GC-aware.
So instead annotate `render` fields in `core` with `#[collect(require_static)]`.

render: Remove `gc-arena` dependency

---

web/packages/core/package.json
web/packages/core/src/load-ruffle.ts

This may or may not help with the startup hang introduced by #7777 on some platforms.
And in general could improve the performance of any WASM<->JS calls by some margin.
According to this doc: https://docs.google.com/spreadsheets/d/1jT05jtyun8KFDMZWGjqtqprqJpKkdvC0zfq0aHcAxVE/edit#gid=0 (linked from https://github.com/WebAssembly/website/issues/187#issuecomment-1222992930),
this extension has been available since the following browser versions:
Chrome 96, Firefox 79, Safari (Desktop) 15, iOS Version 15

web: Also enable the "reference-types" feature in the build with WASM extensions

---

core/src/avm2/globals/flash/display/displayobject.rs

This allows the loaded ArmorGames API swf to run in
'This is the only level too'

avm2: Stub DisplayObject.mask getter/setter

---

core/src/backend/audio/decoders.rs

This should fix #7524.
Regression testing in progress, re: #5486 #6546
(Sorry for being so terse for now, I just had to get this out of my brain ASAP.)

core/mp3: More lenient MP3 buffer underrun detection

---

core/src/timer.rs

... instead default to `false`, to not cancel the timer. This might result in an error message spam in some cases, but it follows the "execution never stops due to an error" philosophy that AVM2 operates under, based on what I read on Discord.
This removes an `unwrap` added in #7428.
Should fix: https://github.com/ruffle-rs/ruffle/issues/7516,  https://github.com/ruffle-rs/ruffle/issues/7517, and https://github.com/ruffle-rs/ruffle/issues/7824

core: Don't panic when an error occurs in an AVM2 timer callback

---

core/src/avm1/globals/movie_clip.rs
core/src/avm1/globals/transform.rs
core/src/avm2/globals/flash/display/displayobject.rs
core/src/avm2/globals/flash/geom/transform.rs
core/src/display_object.rs
core/src/display_object/avm1_button.rs
core/src/display_object/avm2_button.rs
core/src/display_object/edit_text.rs

Change `set_matrix` and `set_color_transform` to accept owned structs,
instead of references. This allows callers that already have an owned
struct to pass it directly, thus saving an unnecessary borrow + clone.
This also aligns with other methods, such as `set_sound_transform`,
which currently accepts an owned struct.

core: Avoid some clones of `Matrix` and `ColorTransform`

---

core/src/avm2/globals/Date.as
core/src/avm2/globals/Vector.as
core/src/avm2/globals/flash/events/ShaderEvent.as
core/src/avm2/globals/flash/utils/Dictionary.as

As per our (not so) recent Discord discussion.
EDIT: Plus some related cleanup following #7597.

avm2: Fix the stub for `Vector` + some related cleanup

---

core/src/avm2.rs
core/src/avm2/activation.rs
core/src/avm2/class.rs
core/src/avm2/method.rs
core/src/avm2/multiname.rs
core/src/avm2/property_map.rs
core/src/avm2/script.rs
core/src/avm2/traits.rs

This is a relatively major redesign of Multiname design.
Changes:
- ABC Multinames are now pooled.
- ABC-pooled Multinames can now be "uninitialized" ("lazy"), which means they shouldn't be used for lookups until the value/namespace are read from the AVM stack. (previously, this role was filled by matching on the "raw" AbcMultiname.) This produces a new Multiname instead of mutating existing one.
- Multinames with a single namespace now hold it without a `vec` - meaning, `QName`->`Multiname` conversions are effectively free.
Good:
- noticeable perf improvements - previously the box2d demo took 20-25% of time loading multinames, and all this work got removed.
- greatly simplified `multiname.rs` - we went from four `match`es on `abc_multiname` to one, and the complexity of resolving …

Avm2: refactor Multinames, pool them in TranslationUnit

---

desktop/Cargo.toml

Deprecate minimp3 for MP3 decoding and switch to symphonia on desktop by default. This allows both desktop and web to use the same MP3 decoder for consistent behavior.
Let's see how this works out for a week or so, then we can remove the minimp3 feature.
Fixes #7070.

audio: Switch to symphonia by default

---

core/src/display_object/edit_text.rs
core/src/html/text_format.rs
swf/src/read.rs
swf/src/test_data.rs
swf/src/types.rs
swf/src/write.rs

Clean up the massive set of bools used by `swf::EditText` and `core::edit_text::EditText`.
* Add `swf::EditTextFlag` for the bits used by the DefineEditText SWF tag.
* Add builder-like methods to `swf::EditText` to allow setting these flags and values.
* Add `core::edit_text::EditTextFlag` that extends this with additional flags used by core/ActionScript.
* Simplify `EditTextStatic` as it was mostly unused fields.
* Fix a bug where height should be read in DefineEditText when the `HAS_FONT_CLASS` flag is set.
Shaves off 8 bytes or so from `EditText`. This is a small step to make #7749 nicer.

text: Use bitflags for edit text flags

---

Cargo.lock
core/Cargo.toml
render/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml

This basically reverts #7254 for all `.toml` files, except for `wgpu`
where it's actually needed on both desktop and web.

chore: Remove unused `image` dependency

---

core/src/display_object/container.rs

An AVM2 movie can repeatedly remove and add a DisplayObject from/to a parent. This was causing SolarMax to stop working after advancing to the next level.

core: Mark DisplayObject as non-removed when added to display list

---

exporter/src/main.rs
render/wgpu/src/lib.rs
render/wgpu/src/target.rs
tests/tests/regression_tests.rs

When rendering offscreen, we want the resulting image to use premultiplied alpha, since the image will be stored in a texture.
However, when capturing an image in the exporter or test framework, we want to use straight alpha, so that the resulting image can be saved as a PNG.
Previously, we incorrectly used straight alpha everywhere, resulting in incorrect output when using BitmapData.draw with transparency.

render: Add `premultiplied_alpha` parameter for image capture

---

core/src/display_object/bitmap.rs

We only need to access bitmap_data to check if we need to update a dirty texture.

core: Render Bitmap even if bitmap_data is None

---

core/src/avm1/object/shared_object.rs
core/src/lib.rs
render/webgl/src/lib.rs
swf/src/lib.rs

In several cases, the current code seems preferable to the code required by `clippy::bool_to_int_with_if`. Let's suppress this for now to get the build passing, and decide later if this is something that we want to enable.

Fix Clippy lints and allow `clippy::bool_to_int_with_if`

---

core/src/avm2/activation.rs

The `multiname` is now a `Gc`, so we need to dereference it to get a useful Debug impl.

avm2: Fix "Property does not exist" error message

---

desktop/src/executor.rs

We were incorrectly skipping the call to `task.set_ready` if `self.waiting_for_poll` was set. The `waiting_for_poll` flag should only be used to avoid redundant messages being sent into the event loop.
This was causing us to ignore wakeups if more than one wakup arrived in between calls to `poll_all`.

desktop: Always mark task as ready on wake

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
Cargo.lock
core/Cargo.toml
render/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
web/Cargo.toml
web/README.md
web/common/Cargo.toml
web/src/lib.rs

As usual, also bump its helper crates (`js-sys`, `web-sys` and `wasm-bindgen-futures`) to the latest versions.
Due to https://github.com/rustwasm/wasm-bindgen/pull/3031, use the `serde-wasm-bindgen` crate as a replacement to the deprecated `JsValue::from_serde` function.

web: Bump `wasm-bindgen` to 0.2.83

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
Cargo.lock
core/Cargo.toml
render/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
web/Cargo.toml
web/README.md
web/common/Cargo.toml
web/src/lib.rs

This reverts commit 084b252030ffe68e60e62ea24592f3d87739c521.
See https://github.com/ruffle-rs/ruffle/actions/runs/3056873460/jobs/4931444458#step:8:391 and https://github.com/gfx-rs/wgpu/pull/2954; I assume we can't bump wasm-bindgen's helper crate web-sys until that PR is merged into a new wgpu release, and since wasm-bindgen always bumps with its helper crates, we can't bump wasm-bindgen either.

Revert "web: Bump `wasm-bindgen` to 0.2.83"

---

core/src/avm2/activation.rs

Turns out I screwed up the syntax for Cargo conditional comments and didn't notice. For at least two years.

avm2: Fix `avm_debug` not printing debugging information

---

core/src/avm2/globals/flash/display/sprite.rs

Turns out this got implemented in AVM1 after I did my initial round of properties on AVM2 display objects, and I didn't notice.

avm2: Impl `Sprite.useHandCursor`

---

core/src/display_object/movie_clip.rs

Here's an oversight from the chunked preloading PR: the root movie exists before the movie loads, and so it can get events before certain pieces of information are known. Such as its `SymbolClass`. `run_frame_internal` has a check to make sure the next frame has been processed before we try to run it, which gates off *almost* everything in the movie from happening, but not this one specific thing.
So we just make sure to check `frames_loaded` in `construct_frame` too.

avm2: Explicitly delay frame construction until the first frame is loaded.

---

swf/src/avm1/types.rs

Simply use `FunctionFlags::empty()` directly.

swf: Remove `impl Default for FunctionFlags`

---

core/src/avm2/activation.rs

These were debug-printing `Gc<Multiname>` instead of `Multiname`

avm2: Fix some `avm_debug!` calls.

---

core/src/avm2/object/error_object.rs

This is causing builds without the avm_debug feature to fail, because we now have code relying on this method existing even when we aren't building with avm_debug.
This needs to be merged ASAP or nightly will fail. Also, we should probably have a test without avm_debug enabled so this doesn't happen in the future.

avm2: Add non-debug version of ErrorObject::display_full

---

Cargo.lock
web/Cargo.toml
web/src/lib.rs

The `serde-serialize` feature is deprecated
(https://github.com/rustwasm/wasm-bindgen/pull/3031).
This solves a cyclic dependency error with aHash

Switch to `serde-wasm-bindgen` over `serde-serialize` feature

---

core/src/avm1/globals/movie_clip.rs
core/src/avm2/globals/flash/display/displayobject.rs
core/src/display_object.rs
core/src/display_object/edit_text.rs
core/src/html/dimensions.rs
core/src/html/test.rs
core/src/tag_utils.rs
render/src/bounding_box.rs
render/src/shape_utils.rs
swf/src/read.rs
swf/src/types.rs
swf/src/types/rectangle.rs
swf/src/write.rs

And make it generic, as a first step towards making it a general-purpose data structure for the whole codebase. Some potential replacements are:
* `BoundingBox` in `render/src/bounding_box.rs`.
* `BoxBounds` in `core/src/html/dimensions.rs`.
* Parameters to a bunch of `BitmapData` methods in `core/src/bitmap/bitmap_data.rs`.

swf: Extract `Rectangle` to a separate file

---

core/src/config.rs
web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/packages/core/src/public-path.ts
web/packages/core/src/ruffle-player.ts
web/src/lib.rs

Since `serde-wasm-bindgen` doesn't support `#[serde(default)]` (https://github.com/cloudflare/serde-wasm-bindgen/issues/20), we no longer able to deserialize a partial `Config` object. As a solution, take care to pass a full object from the TypeScript side.

web: Fix config with `serde-wasm-bindgen`

---

core/src/avm1/globals/movie_clip.rs
core/src/avm2.rs
core/src/avm2/bytearray.rs
core/src/avm2/error.rs
core/src/avm2/globals.rs
core/src/avm2/globals/flash/utils.rs
core/src/avm2/globals/flash/utils/ByteArray.as
core/src/avm2/globals/flash/utils/byte_array.rs
core/src/avm2/globals/json.rs
core/src/avm2/script.rs
core/src/library.rs

This PR removes almost all `impl From<T> for Error<'gc>` (except where `T` is `&str` or `String`), by favoring to throw ordinary ActionScript exceptions.
The goal is to get rid of `Error::RustError` completely, leaving `Error<'gc>` equivalent to `Value<'gc>`.
`&str` or `String` are deferred to a future PR since they are significantly more used.

avm2: Preliminary work to remove `Error::RustError`

---

render/wgpu/src/backend.rs
render/wgpu/src/commands.rs
render/wgpu/src/lib.rs

These are duplicates of fields in `Bitmap`

wgpu: Remove `width` and `height` fields from our `Texture` wrapper struct

---

core/src/avm1/value.rs

Reverts ruffle-rs/ruffle#7941.
Temporary measure to fix #8102 for the upcoming nightly release.

Revert "avm1: Remove `Value::to_primitive_num`"

---

render/webgl/shaders/gradient.frag
render/webgl/src/lib.rs

It wasn't been used since its introduction in fa5c09b0cd60c39ed71104d26fefa8ccd8ffb6a9.

webgl: Remove dead `u_num_colors`

---

core/src/avm2/globals/flash/display/displayobjectcontainer.rs
core/src/avm2/globals/flash/display/interactiveobject.rs

As it says on the tin.
I've implemented these as "functional stubs": i.e. we log a warning when they are used but return reasonable default values in the hopes that the movie in question will continue working. When we get proper support for accessibility we will need to implement these properties, too.

avm2: Stub `tabChildren`, `tabIndex`, and `tabEnabled`.

---

web/packages/extension/webpack.config.js

As explained in the [Chrome Developers documentation](https://developer.chrome.com/docs/extensions/mv3/manifest/incognito/), Chrome runs the extension in a single shared process by default, which prevented Ruffle's internal player page from loading in Incognito tabs. This message was shown instead:
The problem does not affect Firefox, and in fact, [Firefox does not support split incognito mode](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) at all; it refuses to load the extension if this value is present in its manifest. So we'll only use it for the Chrome extension, not the Firefox extension.

extension: Use split incognito mode in Chrome

---

core/src/avm2/globals/flash/display/DisplayObjectContainer.as
core/src/avm2/globals/flash/display/Loader.as

This doesn't actually change any behavior right now, but still is objectively a correct thing to do.

avm2: Fix typing of add/removeChild methods

---

core/src/avm2/globals/flash/display/movieclip.rs

Note: I didn't test that our Rust-level `enabled` has the same semantics in AVM1 and AVM2 - but at a glance, it should be more or less the same.

avm2: Add MovieClip::enabled

---

core/src/backend/audio/decoders.rs

Fixes regression caused by me in 85cf383c84de574b4517ff250cb9e7904e77f128 and fixes #8222

core: Don't desync on frames with no audio blocks.

---

core/src/display_object/bitmap.rs

render: Bail on attempts on panicking recursive render.

---

core/src/avm1/activation.rs
core/src/avm1/function.rs
core/src/avm1/globals.rs
core/src/avm1/globals/array.rs
core/src/avm1/globals/bitmap_data.rs
core/src/avm1/globals/boolean.rs
core/src/avm1/globals/date.rs
core/src/avm1/globals/matrix.rs
core/src/avm1/globals/number.rs
core/src/avm1/globals/object.rs
core/src/avm1/globals/point.rs
core/src/avm1/globals/rectangle.rs
core/src/avm1/globals/shared_object.rs
core/src/avm1/globals/string.rs
core/src/avm1/object/script_object.rs
core/src/avm1/property_decl.rs
core/src/avm1/value.rs

It was never `None`, except for 3 tests in `script_object.rs`, which now use `activation.context.avm1.prototypes().function`.

avm1: Require `fn_proto` in `FunctionObject::bare_function`

---

core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/avm2/globals/flash/filters/DisplacementMapFilter.as
core/src/avm2/globals/globals.as

Both were missing in #8163. Still not working completely though due to applyFilter not implemented and what I think are transparency issues.

avm2: BitmapData.perlinNoise and DisplacementMapFilter

---

core/src/display_object/loader_display.rs

While loaders themselves have no interactivity, they contain children, and thus need to implement `mouse_pick`. The default implementation of `mouse_pick` makes the entire object unpickable otherwise.

avm2: Loaders should not be opaque to mouse events.

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
Cargo.lock
core/Cargo.toml
render/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
render/wgpu/src/backend.rs
render/wgpu/src/descriptors.rs
render/wgpu/src/target.rs
tests/tests/regression_tests.rs
web/Cargo.toml
web/README.md
web/common/Cargo.toml
web/src/lib.rs

Also bump `wasm-bindgen` to `0.2.83` (along with its helper crates), and `raw-window-handle` to `0.5`, as now required.

wgpu: Bump to `0.14.0`

---

Cargo.toml
core/Cargo.toml
core/build_playerglobal/Cargo.toml
core/macros/Cargo.toml
desktop/Cargo.toml
exporter/Cargo.toml
render/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
scanner/Cargo.toml
swf/Cargo.toml
tests/Cargo.toml
tests/input-format/Cargo.toml
video/Cargo.toml
video/software/Cargo.toml
web/Cargo.toml
web/common/Cargo.toml
web/packages/extension/safari/Cargo.toml
wstr/Cargo.toml

This is possible since Rust 1.64.0: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds

chore: Extract Cargo `edition` to `[workspace.package]`

---

render/wgpu/src/backend.rs
render/wgpu/src/pipelines.rs
render/wgpu/src/surface.rs

Credit to @crumblingstatue.
Per `wgpu` documentation, the latter has wider support than the former.
Fixes #8295, #8296.

wgpu: Use `Depth32FloatStencil8` over `Depth24PlusStencil8`

---

core/src/display_object/bitmap.rs
core/src/display_object/movie_clip.rs
core/src/loader.rs
render/src/backend.rs

Change `Bitmap::new()` to accept a `ruffle_render::bitmap::Bitmap` directly, instead of `width`, `height` and `bitmap_handle`. As a consequence, all `RenderBackend::register_bitmap_*` methods are no longer necessary - we can use `ruffle_redner::utils::*` to obtain a `ruffle_render::bitmap::Bitmap` right before calling `Bitmap::new()`.

core: Simplify `Bitmap` creation

---

core/src/bitmap/bitmap_data.rs

This fixes the panic in Castaway (https://github.com/ruffle-rs/ruffle/issues/8016). 
I think in this particular game, the draw was only used for one of intro logos, so it's not really needed for gameplay.

render: Bail on attempts on panicking recursive render, part 2.

---

core/src/lib.rs
core/src/loader.rs
core/src/player.rs
desktop/src/main.rs

This adds a setting to Ruffle that allows disabling streaming playback.
This comes in three layers:
* `streaming` is the current behavior - tags are processed asynchronously and all movies run concurrently with loading. Preloaders work as intended.
* `delayed` - tags are processed asynchronously, but movies do not run until tag processing completes. Preloaders are skipped but the UI is not locked while movies load.
* `blocking` is the old behavior - tags are processed synchronously and movies start fully loaded. The UI locks until the movie finishes loading.
You can configure this on desktop with the `--load-behavior=xyz` flag and, on web, with the `loadBehavior` parameter on `RufflePlayer.load`.
The reason for this is a handful of movies that work, but have broken preloaders in Ruffle. …

Load behaviors / preload skip option

---

core/src/avm2/globals/flash/display/displayobject.rs

The underlying flag currently does nothing, but this allows SWFs to continue executing.

avm2: Implement DisplayObject.cacheAsBitmap

---

.github/workflows/test_web.yml
web/README.md

Per https://nodejs.org/en/about/releases/:
* Node.js 16 became "maintenance" and Node.js 19 became "current" on October 18.
* Node.js 18 will become "active LTS" on October 25.
In order prepare for potentially breaking changes, update the tested Node.js versions from 16 and 18 to 18 and 19.

web: Update Node.js versions

---

core/src/display_object/bitmap.rs

Together with the fix in https://github.com/ruffle-rs/ruffle/pull/8343 , this should fix the behavior of `var bitmap = addChild(new Bitmap())`.

avm2: Add missing set_object2 impl to Bitmap

---

core/src/loader.rs
core/src/player.rs
core/src/tag_utils.rs
desktop/src/main.rs

The desktop player now takes a `--spoof-url` argument, which overrides the movie URL provided to ActionScript. This does not affect non-root movies loaded through `Loader`.

core: Add root movie URL spoofing (desktop only).

---

core/src/player.rs

Changed "AVM Debugging turned off! Press CTRL+ALT+D to turn off again." into "AVM Debugging turned off! Press CTRL+ALT+D to turn on again." and "AVM Debugging turned on! Press CTRL+ALT+D to turn on again." into "AVM Debugging turned on! Press CTRL+ALT+D to turn off."

Fixed a typo in messages on pressing Ctrl+Alt+D

---

core/src/avm1/globals/movie_clip.rs
core/src/display_object/graphic.rs
core/src/display_object/movie_clip.rs

Extract `MovieClip::drawing` and `Graphic::drawing`, which return a non-`Option` `Drawing`. This avoids many `.unwrap()`s in AVM1.

core: `Drawing` cleanup

---

swf/src/avm1/read.rs

Newest Flash Player exits on unknown value types. However, older versions
(at least FP9) just ignore them and continue to the next value.
Follow the lenient behavior in order to support more content (e.g. #8389
doesn't work on newest Flash Player).
Fixes #8389.

avm1: Ignore unknown value type in `ActionPush`

---

web/packages/extension/tools/sign_xpi.js

`temp-dir` 3.0.0 is now pure ESM. As such, it no longer can be `require`d. To workaround this, use `await import` instead.
In the long-term, it might be worth converting the `sign_xpi.js` script itself to ESM.

web: Fix `temp-dir` upgrade

---

Cargo.lock
render/wgpu/Cargo.toml
render/wgpu/src/backend.rs
render/wgpu/src/pipelines.rs
render/wgpu/src/surface.rs

This reverts #8297. Instead, pin `wgpu-hal` and `wgpu-types` to include https://github.com/gfx-rs/wgpu/pull/3165, which fixes https://github.com/gfx-rs/wgpu/issues/3112.

wgpu: Use `Depth24PlusStencil8` again

---

core/src/backend/audio.rs
core/src/context.rs
core/src/display_object/avm1_button.rs
core/src/display_object/movie_clip.rs
core/src/loader.rs
core/src/player.rs

- Use a fixed-size array instead of a Vec for the queues
- Remove unwanted plurals in methods and types names

core: Small cleanups in ActionQueue

---

core/src/display_object/movie_clip.rs
swf/src/read.rs

`tag_length` isn't really necessary since each tag is read using a dedicated `swf::Reader`, which keeps track of the tag boundary internally.
As a result, `tag_len` can be avoided passed around many times in `movie_clip.rs`.

swf: Simplify read of `PlaceObject` tags

---

core/src/display_object/avm1_button.rs
core/src/display_object/avm2_button.rs
core/src/display_object/container.rs
core/src/display_object/edit_text.rs
core/src/display_object/interactive.rs
core/src/display_object/loader_display.rs
core/src/display_object/movie_clip.rs
core/src/display_object/stage.rs
core/src/prelude.rs

It is replaced by two accessor methods on the trait + default implementations of all other methods.

Remove impl_display_object_container! macro

---

Cargo.lock
core/src/avm2/globals/flash/media/soundmixer.rs
core/src/backend/audio.rs
core/src/backend/audio/mixer.rs
desktop/Cargo.toml
desktop/src/audio.rs

This should help with a number of z0r.de loops, such as: 2627, 5482, 6984, 7719, 7757, 7761, 7801, 7812, 7850, 7855, 7903, 7907
Here is a test file based on https://code.tutsplus.com/articles/render-an-mp3-audio-spectrum-in-flash-with-computespectrum--active-10808: (warning, loud beeps and boops after pressing the play button!)
[spectrumvis.zip](https://github.com/ruffle-rs/ruffle/files/9845577/spectrumvis.zip)
Some hints were also taken from:
https://web.archive.org/web/20120410195615/http://blog.benstucki.net/?p=60
Unfortunately the FFT still doesn't match what FP does, but at least the idea is the same.
If anyone has any ideas about how exactly their implementation is broken, that would be very much welcome.
The code is not particularly elegant or efficient yet either, but as a PoC I …

core,avm2,desktop: Implement `SoundMixer.computeSpectrum()`

---

core/src/loader.rs

```
var lv = new LoadVars();
lv.onData = function(src) {
if(src == undefined) {
trace("ERROR: " + src);
return undefined;
}
trace("OK: " + src);
};
lv.load("params.txt");
```
If params.txt exists but doesn't contain anything, `ERROR: undefined` is now traced. This matches Flash's behavior.
In master, `OK: ` was traced.

avm1: onData fails if the loaded data is an empty string

---

core/src/avm1/globals/context_menu.rs
core/src/avm2.rs
core/src/avm2/globals/flash/ui/ContextMenuBuiltInItems.as
core/src/avm2/globals/flash/ui/context_menu.rs
core/src/context_menu.rs
core/src/player.rs

The context menu logic is a bit more of a spaghetti because I tried to deduplicate and keep decent separation of concerns, but parts of it flip between being avm-dependent and universal.
It goes like this:
- get list of enabled builtin items (avm-dependent)
- build builtin items (universal)
- build custom items (avm-dependent)
I don't really know if there's an easier way to write this.
I left dispatching the actual 
menuSelect, menuItemSelect events unimplemented for now. Actually, what do you think about making all the custom items `enabled=false` to make it explicit for now?
Result:

core: Support AVM2 context menu (sans callbacks)

---

core/src/external.rs

For some reason, Flash Player returns "null" (as a string) in this situation.
Fixes the default text not being displayed on the city sign on [miniville.fr](https://web.archive.org/web/20070628203054/http://miniville.fr/).
---
JS:
`function getVal() { return "        "; }`
AS2:
```
var text = flash.external.ExternalInterface.call("getVal");
var r = "|";
r = r + text + "|";
r = r + typeof text + "|";
trace(r);
getURL("javascript:console.log(\'" + r + "\')","");
```
[Sample (SWF)](https://github.com/ruffle-rs/ruffle/files/10071100/externali.zip)

avm1: Fix `ExternalInterface.call` with blank strings in SWFv8

---

core/src/avm2/globals/flash/media/soundchannel.rs
core/src/backend/audio.rs
core/src/backend/audio/mixer.rs

A bit of a WIP, but works well enough.
For example, it improves the following z0r loops at least: 6268, 6411, 6565.
Unlike with #8356, I didn't make sure to decouple the window of time over which this peak is taken from the output stream of the backend, because it didn't seem as important here.

avm2,audio: Implement `SoundChannel.leftPeak` and `SoundChannel.rightPeak`

---

core/src/avm1/activation.rs
core/src/avm1/function.rs
core/src/avm1/globals/function.rs
core/src/avm1/object/stage_object.rs
core/src/avm1/runtime.rs
core/src/avm1/scope.rs
core/src/avm1/test_utils.rs
core/src/display_object/edit_text.rs
core/src/display_object/movie_clip.rs
core/src/external.rs
core/src/player.rs
core/src/timer.rs

- Remove unused `GcCell`s on `Activation` and `Scope`;
- Remove the `globals` parameter from `Activation::from_nothing`
- Reduce allocations in `Activation::from_nothing`:
- Pre-allocate the global scope on the `Avm1` context so that it can be reused;
- Reuse the global constant pool instead of allocating a new empty one; this doesn't matter as no bytecode is directly executed on a `from_nothing` activation without bringing its own constant pool.
------
`Activation::from_nothing` now does a single allocation (in `Scope::new_local_scope`), but I don't know if this can be removed.
Naïvely, an activation created with this method shouldn't be used to directly execute bytecode or to define locals, and so it should be fine to reuse directly the global scope (and indeed, the tests still pass …

AVM1: Some Activation cleanup

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/character.rs
core/src/display_object/movie_clip.rs
core/src/display_object/video.rs
core/src/library.rs
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/src/bitmap.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
render/wgpu/src/commands.rs
render/wgpu/src/lib.rs
render/wgpu/src/mesh.rs
render/wgpu/src/surface.rs
video/software/src/backend.rs

We only called `get_bitmap_pixels` when creating a `BitmapData` for an SWF-provided `Bitmap`. We now store the initial pixels in `Character::Bitmap`, and use them to initialize a `BitmapData` when needed.
This lets us simplify the wgpu backend, which no longer needs to store a `Bitmap` object. In addition to saving space for `BitmapData` objects that lack an SWF `Bitmap`, this will make it easier to move data from `bitmap_registry` into `BitmapHandle` itself.

render: Remove `get_bitmap_pixels` and store data in `Character::Bitmap`

---

.github/workflows/release_nightly.yml
.github/workflows/test_rust.yml
.github/workflows/test_web.yml

Do the simple v2 ---> v3 workflow upgrades in the first commit.
The second commit has the actions-rs/toolchain ---> dtolnay/rust-toolchain replacement to move away from the seemingly unmaintained https://github.com/actions-rs/toolchain and instead use https://github.com/dtolnay/rust-toolchain.
The third commit is an attempt to move away from the seemingly unmaintained https://github.com/actions-rs/cargo.
The fourth commit switches Swatinem/rust-cache to the more generic v2 instead of a specific revision.

ci: Upgrade Node 12 actions workflows

---

core/src/avm2/globals/flash/text/textfield.rs

(Not pictured: significant [graphical corruption](https://pooper.fantranslation.org/@kmeisthax/109435857655768366) and 10 second pixel transition times)
This implements textfield scrolling parameters, which were the last thing needed by `FlxText`. Flixel games that use text can now go in-game (though they run slow).
No tests are included since this just implements properties that were already present in AVM1. I couldn't find any tests for them in the AVM1 tests directory; if there were any I would have ported them over.

avm2: Implement `TextField` scrolling parameters

---

Cargo.lock
core/src/avm1/object/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/avm2/object/context3d_object.rs
core/src/bitmap/bitmap_data.rs
core/src/display_object/bitmap.rs
core/src/display_object/video.rs
core/src/drawing.rs
render/canvas/Cargo.toml
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/src/bitmap.rs
render/src/commands.rs
render/webgl/Cargo.toml
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
render/wgpu/src/commands.rs
render/wgpu/src/context3d/mod.rs
render/wgpu/src/lib.rs
render/wgpu/src/mesh.rs
render/wgpu/src/surface.rs
render/wgpu/src/target.rs
render/wgpu/src/utils.rs
video/software/src/backend.rs

Depends on https://github.com/ruffle-rs/ruffle/pull/8132, since `get_bitmap_pixels` doesn't go well with this approach.
`BitmapHandle` now holds `Arc<dyn BitmapHandleImpl>`. This allows us to move all of the per-bitmap backend data into `BitmapHandle`, instead of holding an id to a backend-specific hashmap.
This fixes the memory leak issue with bitmaps. Once the AVM side of a bitmap (`Bitmap`/`BitmapData`) gets garbage-collected, the `BitmapHandle` will get dropped, freeing all of the GPU resources associated with the bitmap.

core: Make `BitmapHandle` hold a trait object instead of an id

---

core/src/avm1/globals/convolution_filter.rs
core/src/avm1/globals/displacement_map_filter.rs
core/src/avm1/globals/drop_shadow_filter.rs
core/src/avm1/globals/glow_filter.rs
core/src/avm1/globals/gradient_bevel_filter.rs
core/src/avm1/globals/gradient_glow_filter.rs
core/src/types.rs

[Here is the file (.SWF)](https://github.com/ruffle-rs/ruffle/files/10105540/filters.zip) I used for testing.
<details>
<summary>View raw code</summary>
```
trace("ConvolutionFilter");
var x = new flash.filters.ConvolutionFilter();
trace(x.alpha);
x.alpha = NaN;
trace(x.alpha);
trace("");
trace("DisplacementMapFilter");
var x = new flash.filters.DisplacementMapFilter();
trace(x.alpha);
x.alpha = NaN;
trace(x.alpha);
trace("");
trace("DropShadowFilter");
var x = new flash.filters.DropShadowFilter();
trace(x.alpha);
x.alpha = NaN;
trace(x.alpha);
trace(x.strength);
x.strength = NaN;
trace(x.strength);
trace("");
trace("GlowFilter");
var x = new flash.filters.GlowFilter();
trace(x.alpha);
x.alpha = NaN;
trace(x.alpha);
trace(x.strength);
x.strength = NaN;
trace(x.strength);
trace(""); …
```

avm1: Various minor fixes in filters

---

render/canvas/src/lib.rs
render/webgl/src/lib.rs
render/wgpu/src/lib.rs

There were two issues:
1. We were accidentally calling `as_any` on `handle,` rather than `handle.0`
2. Calling `as_any` can invoke the wrong implementation, depending on what traits are in scope. We want the method implemented on the underlying type (`RegistryData`) to be used, but if `Downcast` is explicitly imported, then we appear to invoke it on the trait object `dyn BitmapHandleImpl` itself (using the fact that trait objects themselves implement `Any`). We now explicitly call the generated method on the trait object, which avoids this issue.

Fix BitmapHandle downcasting in webgl and canvas backends

---

core/src/display_object.rs
core/src/display_object/container.rs
core/src/player.rs

Only enabled with `--features=avm_debug`.
Example dump for a very simple preloader. Shows the AS class, DO name and DO type.
```
rel(0,0) abs(0,0) flash.display::Stage  Stage
rel(0,0) abs(0,0) Main root1 MovieClip
rel(360,260) abs(0,0) BLOCnog_fags101_fla::preloader_1 instance17 MovieClip
rel(-360,-260) abs(0,0) BLOCnog_fags101_fla::bg_1000_2 bg MovieClip
rel(0,0) abs(0,0) BLOCnog_fags101_fla::bgAni_10000_3 instance2 MovieClip
rel(0,0) abs(0,0) flash.display::Shape instance1 Graphic
rel(0,0) abs(170,359.55) flash.display::Shape instance3 Graphic
rel(-150,-130) abs(210,130) BLOCnog_fags101_fla::adcon_4 adBox MovieClip
rel(0,0) abs(210,130) flash.display::Shape instance4 Graphic
rel(0,0) abs(170,90) flash.display::Shape instance5 Graphic
rel(10,-206) abs(0,0) flash.display::SimpleButton …
```

core: debug: use ctrl+alt+f to dump DO render tree

---

.github/workflows/test_rust.yml

Since this PPA was only necessary back when we used `ubuntu-20.04` for CI, where `lavapipe` wasn't yet enabled in mesa.
This may or may not has had something to do with the SIGSEGVs we've seen recently, according to: https://github.com/lutris/lutris/issues/4581#issuecomment-1304638108
I hope this doesn't make the ongoing CI mess any worse. It could at least simplify and speed up tests a bit.

ci: Don't use a PPA for mesa (`lavapipe`) anymore on `ubuntu-22.04`

---

core/src/display_object/loader_display.rs

(Almost - this also requires a few method impls that @adrian17 also needs to PR)
Turns out our `Loader` display object was also missing `enter_frame`/`construct_frame` impls. All containers need to implement these methods or the objects put in them will freeze up.

core: `Loader` must pass enter/construct frame lifecycle events down

---

core/src/avm2/globals/flash/net.as
core/src/avm2/globals/flash/net.rs
core/src/avm2/globals/globals.as

This implements the most basic use of [flash.net.navigateToURL](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/package.html#navigateToURL()), opening the given URL.
Fixes errors logged when clicking on links, e.g. armor games logo in HitBox loader.

AVM2: Implement basic flash.net.navigateToURL

---

core/src/avm2/globals/flash/system.rs
core/src/avm2/globals/flash/system/System.as
core/src/avm2/globals/flash/system/system.rs
web/src/ui.rs

Implements [System.setClipboard()](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/system/System.html#setClipboard())
Fixes #8435

AVM2: Implement System.setClipboard

---

core/src/avm2/globals/flash/display/bitmapdata.rs

Fixes the panic in z0r 5360.
(this `disposed()` check is redundant, as `check_valid()` already did this earlier.)

avm2: Fix aliasing in BitmapData.copyChannel

---

web/packages/extension/webpack.config.js

Extension marketplaces recommend avoiding minifying JS code, as it does not provide benefit for local files and inhibits the review process.

extension: Disable minification

---

.github/workflows/release_nightly.yml

https://github.com/actions/create-release and https://github.com/actions/upload-release-asset also need to be replaced with https://github.com/softprops/action-gh-release, but I'm less sure about how to do that.
I assume replacing create-release would just involve changing `release_name` to `name` when replacing the action, but replacing upload-release-asset may involve something like https://github.com/softprops/action-gh-release/issues/203#issuecomment-1029848473

ci: Do simple numerical actions updates

---

Cargo.toml
core/Cargo.toml
core/build_playerglobal/Cargo.toml
core/macros/Cargo.toml
desktop/Cargo.toml
exporter/Cargo.toml
render/Cargo.toml
render/canvas/Cargo.toml
render/naga-agal/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
scanner/Cargo.toml
swf/Cargo.toml
tests/Cargo.toml
tests/input-format/Cargo.toml
video/Cargo.toml
video/software/Cargo.toml
web/Cargo.toml
web/packages/extension/safari/Cargo.toml
wstr/Cargo.toml

Use workspace inheritance added in Rust 1.64 to de-duplicate various settings across all packages.
Settings like `version`, `homepage`, etc. are shared among the entire workspace, so we can specify these once and inherit them.
* Most of these packages are meant to only be used by Ruffle, so we should use one `version` # for the entire workspace. 
* `swf` being an exception that is meant to be usable on its own.
* I kept any unique `authors` field.

chore: Inherit cargo metadata from workspace

---

Cargo.lock
LICENSE.md
core/Cargo.toml
core/src/backend/audio/decoders.rs
core/src/backend/audio/decoders/mp3.rs
core/src/backend/audio/mixer.rs
desktop/Cargo.toml
web/Cargo.toml
web/LICENSE.md

Remove the optional minimp3 feature now that symphonia is the default. Rename `symphonia` feature to `mp3`.
To be merged after a week or so once we've given some time for any regression to pop up in symphonia on desktop.

audio: Remove minimp3 feature

---

.github/workflows/release_nightly.yml

Google's OAuth flow changed and this additional client secret is now required for uploading the Chrome extension.

ci: Add OAuth client secret to chrome-extension-upload

---

web/src/lib.rs

Fixes panic screen not popping up when panicking code is triggered by mouse click.

web: Don't unnecessarily borrow-mut instance on mouse-down

---

core/src/avm1/activation.rs
core/src/avm1/function.rs
core/src/avm1/object/stage_object.rs
core/src/avm2/method.rs

Some were completely unused, while others could be replaced with a `#[derive(Collect)]`

core: Remove some manual `Collect` impls

---

core/src/avm2/globals/flash/display/Loader.as

Fixes #8905.
Fixes #8899.
Fixes #8958.

avm2: Throw error in Loader.unload stub

---

web/README.md

Our build process has required Java for a while, but we don't document this requirement as good as we could. This is a problem for people who need to build from scratch in a container (such as, say, extension reviewers).

docs: Document Java in the web version README, too

---

core/src/avm2/globals/flash/text/textfield.rs

Previous behaviour defaulted to undefined and applied the format to the range [0,0). The default should be -1, which applies the format to the full length of the TextField.
This fixes the text color in the windows that pop up when you click objects in [this flash](https://mrcheeze.github.io/homestuck-ruffle-tester/#00253). (Currently the text is displaying black and unreadable, with this fix it changes to white like it's supposed to.)

avm2: Fix calling setTextFormat without providing a beginIndex and endIndex

---

web/package.json

Because ChromeDriver was listed in Ruffle's devDependencies, it was impossible to build Ruffle Web without either installing Google Chrome Stable or manually removing the dependency from package.json, even though Chrome is only needed for running the tests. Moving the dependency to optionalDependencies causes npm to ignore the failure of the ChromeDriver installation during `npm install`. This makes Chrome no longer required to build Ruffle Web, but if Chrome is installed, ChromeDriver will still install as normal and the tests will still pass.

web: Make ChromeDriver dependency optional

---

core/src/avm1/globals/movie_clip.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/bitmap/bitmap_data.rs
core/src/display_object/bitmap.rs
core/src/display_object/graphic.rs
core/src/display_object/morph_shape.rs
core/src/display_object/movie_clip.rs
core/src/library.rs
render/src/bitmap.rs

This makes `Bitmap` delegate to `BitmapData` for
all of the bitmap-related information (handle, width, and height). As a result, we now unconditionally store a `BitmapData` in `Bitmap`.
As a result, swapping the underling `BitmapData` instance will automatically change the properties (and rendered image) of a `Bitmap`.
This required some refactoring in the render backends in order to get access to a `BitmapHandle` through `BitmapData`.

core: Store data in `BitmapData` instead of `Bitmap`

---

web/packages/core/src/shadow-template.ts

Sets line-height to default on Ruffle's shadow-root, preventing incorrect line-height inheritance from the document.
Fixes #8977.

Fix incorrect line-height being inherited on the self-hosted version

---

core/src/avm2/globals/flash/events/KeyboardEvent.as
core/src/player.rs

Based on [similar logic](https://github.com/ruffle-rs/ruffle/blob/664c67ea27ac98337fb7cb01b976c3b34cdd2164/core/src/avm2/object/event_object.rs#L127-L136) already existing in MouseEvent.
I also included controlKey as always having the same value, which [is not strictly correct](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/KeyboardEvent.html) (there are differences on Mac), but I figured was better than leaving it out entirely. I did not include commandKey at all, though.

avm2: Add ctrlKey, altKey, shiftKey, controlKey properties to KeyboardEvent

---

web/docker/Dockerfile
web/docker/docker_builds/.gitignore

per https://github.com/ruffle-rs/ruffle/issues/8799#issuecomment-1374391215 the addons.mozilla.org team had trouble building ruffle from source,
with this docker file, Ruffle can now be built with 4 commands, with the only prerequisites being git and docker:
```
git clone https://github.com/ruffle-rs/ruffle;
cd ruffle;
docker build --tag ruffle-web-docker -f web/docker/Dockerfile .;
docker cp $(docker create ruffle-web-docker:latest):/ruffle/web/packages web/docker/docker_builds/packages
```
and voila, you have 
```
$ file web/docker/docker_builds/packages/extension/dist/firefox_unsigned.xpi 
web/docker/docker_builds/packages/extension/dist/firefox_unsigned.xpi: Zip archive data, at least v1.0 to extract, compression method=store
```
hopefully this will make the addons.mozilla.org team's …

Dockerfile to build web

---

Cargo.lock
desktop/Cargo.toml
desktop/src/main.rs
render/wgpu/Cargo.toml
render/wgpu/src/backend.rs
render/wgpu/src/context3d/current_pipeline.rs
render/wgpu/src/context3d/mod.rs
render/wgpu/src/surface.rs
render/wgpu/src/target.rs

Screenshots of Ruffle in Tracy from my macbook where unfortunately the dpi scaling is all wonky:
Tracy ships binaries on windows, but is buildable from source on linux and mac. You can find it over at https://github.com/wolfpld/tracy.
The more spans we add, the more info will show up in tracy. We can even add custom plots in the future if we want to track other things like network usage or GC stats (if that's possible) or whatever.

desktop: Add tracy feature

---

render/wgpu/src/buffer_pool.rs
render/wgpu/src/surface.rs
render/wgpu/src/surface/commands.rs
render/wgpu/src/surface/target.rs

A modest 5% performance savings on heartcore on my pc with vulkan.

wgpu: Cache texture views along side their owned textures

---

core/src/backend/audio/decoders.rs
core/src/backend/audio/decoders/adpcm.rs
core/src/backend/audio/decoders/mp3.rs
core/src/backend/audio/mixer.rs
core/src/backend/navigator.rs
desktop/build.rs
desktop/src/main.rs
desktop/src/navigator.rs
desktop/src/storage.rs
desktop/src/ui.rs
render/canvas/src/lib.rs
render/src/lib.rs
render/src/shape_utils.rs
render/webgl/src/lib.rs
scanner/src/execute.rs
tests/tests/regression_tests.rs
video/src/lib.rs
web/packages/extension/safari/src/main.rs
web/src/audio.rs
web/src/lib.rs
web/src/navigator.rs

Part of the "let's stop panicking" effort. Absolutely not exhaustive for the whole codebase, but this removes all use of unwraps and disallows them going forwards, in the following crates:
- render
- render/webgl
- render/canvas
- web
- desktop
- video

Remove & disallow unwraps in various crates

---

web/packages/core/src/ruffle-player.ts

Ruffle was not warning users about loading SWFs over the `file:` protocol, instead displaying the generic "file no longer exists" error. This affected users who tried to open a local HTML file that loaded Ruffle from the CDN. This PR accounts for this case and simplifies the logic in `displayRootMovieDownloadFailedMessage`.

web: Warn about root movie fetch over file protocol

---

core/src/avm1/runtime.rs
core/src/player.rs

AVM1 bytecode may leave the operand stack unbalanced, and this will cause a slow memory leak if the stack is never cleared.

Clears the AVM1 stack after executing bytecode

---

core/src/avm2/globals/flash/display/sprite.rs

Fixes #8839
Fixes #8632
Fixes #8363
Fixes #9107
Fixes #8382
Fixes #8916

avm2: Fix start_drag with negative width or height

---

core/src/bitmap/bitmap_data.rs
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/src/bitmap.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
render/wgpu/src/context3d/mod.rs
render/wgpu/src/lib.rs
render/wgpu/src/target.rs
render/wgpu/src/utils.rs

This can significantly improve performance of games that use `BitmapData.draw()`, especially if they don't immediately read from the bitmap afterwards.
However, this PR now only includes the possibility to use it async, and actually making AVM1/2 use it async will be in a future PR.

render: Make render_offscreen non blocking

---

render/wgpu/shaders/buffer_bug_detection.wgsl
render/wgpu/src/backend.rs
render/wgpu/src/utils.rs

Until https://github.com/gfx-rs/wgpu/issues/3371 is fixed, this will allow us to use wgpu "most of the time".

wgpu: Detect if buffers are unusable on web and fail to create wgpu renderer if so

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/character.rs
core/src/display_object/movie_clip.rs
core/src/library.rs

Now that a `Bitmap` always stores a `BitmapData`, we can read the pixels directly from the `BitmapData`, instead of duplicating them in an `initial_data` field

core: Use BitmapData instead of separate `initial_data` field

---

core/src/display_object/interactive.rs

Due to a typo, the rollOver event was being fired as a mouseOut event instead. Also, the variable for the target of a rollOut event was misnamed as "rollover_target".
Fixes this little issue in Pursuit of Hat:
https://user-images.githubusercontent.com/71368227/212291896-5e8a0312-88e0-4074-aed7-1674c75ec390.mp4

avm2: Correct name of rollover event

---

Cargo.lock
render/wgpu/Cargo.toml
render/wgpu/src/backend.rs

This significantly decreases wgpu-webgl rendering time, and works around the buffer bug.

wgpu: Use a temporary wgpu fork that increases push constants limit on webgl

---

.github/workflows/test_rust.yml
.github/workflows/test_web.yml

This should help ease the action queue when rebasing or making changes to PRs. Basically, whenever a PR changes, the existing actions are cancelled as they're no longer relevant for the new changes.
Untested but taken straight from the github docs. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

ci: Cancel existing actions for PRs when new commits come in

---

render/wgpu/src/backend.rs
render/wgpu/src/utils.rs

This makes 8 passes of the test just to be safe, but from testing it appears that it always fails on pass 0. We can reduce the passes down to 4 or 2 or 1 later if we find it impacts performance, but let's be safe for now.

wgpu: Fix buffer bug detection

---

desktop/src/main.rs

Fixes #9172.
Tested on Windows. If anyone can check whether this works as expected on Linux and Mac, that would be great!

desktop: Add `.spl` to file dialog filter

---

swf/src/read.rs

Allows loading and playing Scaleform GFx files using Ruffle's existing functionality. Does not add support for any Scaleform-specific SWF tags, such as DefineSubImage (1008). I'm not sure if that is acceptable but I figured it's worth a shot.
Closes #9070.

swf: Accept Scaleform GFx header signatures

---

web/Cargo.toml

Let's do it? Any objections?
Newgrounds has been running an old build pre-optimisations and as far as we've seen, it's been great and only had the buffer bug, which #9133 deals with (they'll fall back to regular webgl).

web: Enable wgpu-webgl by default

---

render/wgpu/src/backend.rs
render/wgpu/src/mesh.rs

The game registers a texture that's too large on chrome&android (for some reason not firefox on the same devices). This is silently ignored in the webgl backend, so it didn't panic before. This makes it silently ignore it here too.

wgpu: Don't panic if rendering a None bitmap - fixes #9188

---

.github/ISSUE_TEMPLATE/crash_report.yml
Cargo.lock
core/src/avm2/call_stack.rs
core/src/player.rs
desktop/Cargo.toml
desktop/src/main.rs

When a panic happens:
Pressing Yes takes you to [this new issue template, prefilled](https://github.com/dinnerbone/ruffle/issues/new?assignees=&labels=bug&template=crash_report.yml&panic_text=panicked+at+%27wgpu+error%3A+Validation+Error%0A%0ACaused+by%3A%0A++++In+Device%3A%3Acreate_texture%0A++++Dimension+X+value+390000+exceeds+the+limit+of+16384%0A%0A%27%2C+C%3A%5CUsers%5CDinnerbone%5C.cargo%5Cgit%5Ccheckouts%5Cwgpu-e4487c3622394142%5Ca154700%5Cwgpu%5Csrc%5Cbackend%5Cdirect.rs%3A2962%3A5&operating_system=Windows+10.0.19044+%28Windows+10+Pro%29+%5B64-bit%5D&extra_info=Renderer%3A+wgpu%0AAdapter+Backend%3A+Vulkan%0AAdapter+Name%3A+%22AMD+Radeon+RX+6900+XT%22%0AAdapter+Device+Type%3A+DiscreteGpu%0AAdapter+Driver+Name%3A+%22AMD+proprietary+driver%22%0AAdapter+Driver+Info%3A+%2222.11.2%22%0AE …

desktop: Implement crash report dialog when a panic happens

---

core/src/avm2/globals/flash/text/textfield.rs
core/src/display_object/edit_text.rs

Handled with a simple check in text input handler. Will need to be careful around stuff like ctrl+v.
Only tested on the simplest possible case of
```as
tf = new TextField();
tf.maxChars = 5;
tf.type = "input";
```

avm2: Implement TextField.maxChars

---

.github/workflows/release_nightly.yml

This should hopefully fix nightly releases

ci: Ensure `GHA_REPO_ALIVE` starts off as true

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm1/object/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/avm2/object.rs
core/src/avm2/object/bitmapdata_object.rs
core/src/bitmap/bitmap_data.rs
core/src/display_object/bitmap.rs
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/src/bitmap.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
render/wgpu/src/descriptors.rs
render/wgpu/src/lib.rs

This allows us to avoid blocking immediately after a `BitmapData.draw` call. Instead, we only attempt to use the `SyncHandle` when performing an operation that requires the CPU-side pixels (e.g. BitmapData.getPixel or BitmapData.setPixel).
In the best case, the SWF will never explicitly access the pixels of the target BitmapData, removing the need to ever copy back the render backend image to our BitmapData. If the SWF doesn't require access to the pixels immediately, we can delay copying the pixels until they're actually needed, hopefully allowing the render backend to finish processing the BitmapData.draw operation in the backenground before we need the result.
Now that the CPU and GPU pixels can be intentionally out of sync with each other, we need to ensure that we don't accidentally …

Take two: Delay reading image back from render backend using `SyncHandle`

---

web/package.json

Running 'npm run build --workspaces' will run the 'build' script for all workspaces, even if one fails. Since all of the other workspaces depend on 'ruffle-core', running them after a ruffle-core build failure just produces useless errors in the CI logs.

web: Split out npm build of 'ruffle-core' from other npm modules

---

.github/workflows/release_nightly.yml
web/README.md
web/package.json
web/packages/core/tools/set_version.js

As per #8799 we need reproducible builds before Mozilla will let us back onto addons.mozilla.org. One of the largest differences between Mozilla's build and ours (save for the lack of dual-wasm) was version information, since Mozilla's reviewers are building from a source ZIP instead of a Git clone and they are building at a different time from us.
The solution is to... calculate all that information once and store it for later use. The resulting file is called `version_seal.json`. The plan is that source code submissions to Mozilla will be special "reproducible builds" archives with the version seal in them.
The version seal is only used when you specify reproducible builds with `npm run build:repro`, which also builds dual-WASM. The standard and dual-WASM builds will not use the version …

core: Allow sealing build information into the source ZIP for reproducibility.

---

.github/workflows/release_nightly.yml

chore: `npm ci` must run before any other Node scripts

---

Cargo.lock
core/Cargo.toml
core/build_playerglobal/Cargo.toml
core/src/backend/audio/decoders/mp3.rs
desktop/Cargo.toml
exporter/Cargo.toml
render/webgl/Cargo.toml
render/wgpu/Cargo.toml
scanner/Cargo.toml

This is the same as https://github.com/ruffle-rs/ruffle/pull/9270, plus fixing the clippy lint about a deprecated type alias, and also bumping some minor (transitive) package dependencies.

Update Rust dependencies

---

desktop/src/main.rs
web/src/lib.rs

Add key codes for Tab, Enter, Backspace and Numpad Enter
This fixes #8492 and #3696

desktop+web: Add missing key codes

---

.github/workflows/release_nightly.yml

Note that this does *not* attempt to filter out `node_modules` as per @Dinnerbone 's suggestion that we keep them installed in case NPM dies.

Include the whole project in the reproducible archive

---

render/src/backend.rs
tests/tests/util/options.rs

This will catch typos and misplaced options when modifying tests.

tests: Deny unknown fields when deserializing test.toml files

---

Cargo.lock
core/Cargo.toml

This deduplicates some dependencies, and removes
a future-incompat warning from `nom`.

core: Bump flash-lso to latest commit

---

web/packages/core/src/load-options.ts
web/packages/core/src/ruffle-player.ts
web/packages/demo/www/index.js
web/src/lib.rs

Implements the feature described in and closes #8448.
Fixes #8130.
To prevent abuse of this feature, the spoofed URL is constructed relative to the webpage's current URL, and the user can only specify the last path segment of the URL.

web: Construct SwfMovie with spoofed URL when loaded from data

---

CONTRIBUTING.md
core/src/display_object.rs

#8964 changed the format of debug strings of display objects from this:
`Stage(GcCell(Gc { ptr: 0x19c9ab557c8 }))`
To this:
`Stage { ptr: 0x205a1342bb0 }`
The change caused Ruffle's DO tree dumping code to crash, so I fixed it to handle the new format. And also added info about the keyboard shortcut to CONTRIBUTING.md since it wasn't there already.
Thanks to @Bale001 for suggesting a more resilient approach.

Fix DO render tree display and add info to CONTRIBUTING.md

---

Cargo.lock
video/software/Cargo.toml

To take advantage of https://github.com/ruffle-rs/h263-rs/pull/38.

chore: Bump h263-rs to latest master

---

.github/workflows/release_nightly.yml
web/package.json

This should fix the demo not building and the extension getting a version of `undefined`.
Turns out all the `process.env` stuff about package versioning only exists when you run under NPM - not just by being invoked by `node`.

web: Fix various version-seal related issues

---

Cargo.lock
desktop/Cargo.toml
desktop/src/audio.rs

`build_output_stream` now takes in a `timeout` parameter - I've passed in `None` to keep the current behavior.
cpal addded lots of new `SampleFormat` enum values. For now, I'm just returning an error if we encounter any of them - a quick test showed that desktop audio is still working on my Linux machine.

desktop: Bump cpal to 0.15.0

---

Cargo.lock
core/Cargo.toml
core/src/loader.rs
desktop/Cargo.toml
desktop/src/main.rs

Mention that SWFs can be loaded via URL as well as file path. And add a listing of the possible values for the `--load-behavior` option.

desktop: Improve --help messages

---

tests/tests/swfs/avm1/textfield_text/test.toml
tests/tests/swfs/avm2/bitmap_properties/test.toml

textfield_text was made before the .text property learn how to deal with html. It works now.
bitmap_properties was made before bitmapdata could persist any data. That's solved now.

tests: Enable tests that no longer need to be ignored

---

Cargo.lock
desktop/src/main.rs
render/Cargo.toml
render/src/bitmap.rs
render/src/tessellator.rs
render/src/utils.rs
render/wgpu/shaders/color.wgsl
render/wgpu/shaders/common.wgsl
render/wgpu/shaders/gradient/common.wgsl
render/wgpu/src/backend.rs
render/wgpu/src/buffer_builder.rs
render/wgpu/src/descriptors.rs
render/wgpu/src/layouts.rs
render/wgpu/src/lib.rs
render/wgpu/src/mesh.rs
render/wgpu/src/pipelines.rs
render/wgpu/src/shaders.rs
render/wgpu/src/surface.rs
render/wgpu/src/surface/commands.rs

In games with lots of individual meshes, like box2d demo, rendering is about 33% faster
Registration (or replacement) of meshes is about 60% faster
Heartcore is about 8% faster, but it doesn't have that many individual meshes

wgpu optimisations - vertex attributes and shared mesh buffers

---

renovate.json

Leaves any minor/major dependency updates (and any wasm-bindgen) to their own PR, as those are very likely to have some deprecated methods or breaking changes that need attention

chore: Update renovate to only group rust patch dependencies

---

core/src/avm2/property_map.rs
core/src/avm2/scope.rs
core/src/avm2/vtable.rs

Implements the ability for ScopeChain's to cache their results for better performance. Currently to avoid any problems with dynamic properties, caching is disabled for any ScopeChains that contain a `with` scope.

avm2: Implement ScopeChain caching

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/bitmap/bitmap_data.rs

If we're going to overwrite the CPU pixels with the result of a GPU operation, make sure the GPU texture is up to date with the latest CPU pixels. I've also renamed the method to `overwrite_cpu_pixels_from_gpu` to better reflect how it should be used.

core: Handle `DirtyState::CpuModified` in `overwrite_cpu_pixels`

---

core/src/avm2/globals/flash/media/sound.rs
core/src/avm2/globals/flash/media/soundchannel.rs
core/src/avm2/object.rs
core/src/avm2/object/sound_object.rs
core/src/avm2/object/soundchannel_object.rs
core/src/loader.rs

Flash supports calling `Sound.play`, `SoundChannel.stop`, and `SoundChannel.soundTransform` while a sound load is in progress (e.g. immediately after calling `Sound.load`).
To support this, we queue up information inside `SoundObject` and `SoundChannelObject` when a load is in progress. When a load completes, we trigger any queued `Sound.play` and `SoundChannel.stop` calls, and apply the most recent `SoundChannel.soundTransform`

core: Queue up Sound and SoundChannel methods during loading

---

core/src/avm1/globals/system.rs
core/src/lib.rs
core/src/player.rs
web/src/lib.rs

The Newgrounds API checks `Security.sandboxType` to see if it should run in debug mode or not (which determines whether or not medals can actually be unlocked).
For now, desktop continues to use `localTrusted` as the default, while web now uses `remote`. We might want to make this configurable at some point, but this should be good enough for now (and better match Flash's behavior).

core: Make SandboxType configurable, and set to 'remote' on web

---

core/src/avm2/globals/flash/display/displayobjectcontainer.rs
core/src/avm2/globals/flash/system/security.rs

Some stubs were of the wrong type.

Correct AVM2 stub types

---

renovate.json

This should fix the mess that is a wasm-bindgen update breaking every dependency PR

chore: Bundle wasm-bindgen and wasm-bindgen-futures updates together

---

core/src/backend/audio/mixer.rs
tests/Cargo.toml

This is an amendment to #9561.
I have no idea how this worked without this when running from the project root.
I also have no idea how it still worked without the `mp3` feature when running from within `tests`. I added that too, just to be sure.

Fix build when running tests from within `tests`

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/avm2/globals/flash/display/bitmapdata.rs
core/src/character.rs
core/src/display_object/movie_clip.rs
core/src/library.rs

Since `initial_data` was removed from `Character::Bitmap` in #9143, it now holds a single field. Move back to an unnamed field, which aligns with the other `Character` enum variants.

core: Use unnamed field in `Character::Bitmap`

---

core/src/avm2/globals/flash/events/eventdispatcher.rs

This is needed by "Steambirds: Survival"

avm2: Also register EventDispatcher methods in ns "flash.events:IEventDispatcher"

---

core/src/display_object/container.rs

This makes "Garfield's Comic Creator" properly show panels when you close the editor.

core: Set clipDepth to 0 when swapDepths affects a clip

---

core/src/avm2/globals/flash/events/TimerEvent.as
core/src/avm2/globals/flash/events/TouchEvent.as

They were missed in https://github.com/ruffle-rs/ruffle/pull/9279 .

avm2: Add missing imports

---

core/src/bitmap/bitmap_data.rs

I didn't test it extensively on real content, but I checked that on paper it should return exactly the same values - there are only 256*256 combinations after all.
On content heavy with `setPixels()`, on desktop I see 3-4x more fps and on web almost 2x more. Now, it's still a slow function in general (range checks on each pixel etc), but I saw it jump down from 40% of time to <20% of time in FF profiles.
Test code:
```rs
pub fn main() {
for alpha in 0..256 {
for color in 250..256 {
let a = alpha as f64 / 255.0;
let r1 = (color as f64 * a).round() as u8;
let r2 = ((color as u32 * alpha + 127) / 255) as u8;
if r1 != r2 {
println!("{} {} {} {}" , alpha, color, r1, r2);
}
}
}
}
```

core: Implement Color::to_premultiplied_alpha without floats

---

tests/tests/swfs/avm2/dictionary_access/Test.as
tests/tests/swfs/avm2/dictionary_delete/Test.as
tests/tests/swfs/avm2/dictionary_in/Test.as

Using Github's line ending conversion to CRLF. Github's online editor does this automatically, but it also shows the whole file as changed, even though the only manual change made was a single newline added in between two traces.

Remove ^M characters from Dictionary test

---

core/src/avm2/object/vector_object.rs

This makes Vector consistenht with the other implementations of `get_enumerant_name`. This also fixes a bug where AMF object serialization would loop all te way to `u32::MAX` when serializing a vector, because it would never see `Value::Undefined` and break.

avm2: Use Value::Undefined for out-of-range Vector enumerant index

---

core/src/avm2/globals/flash/display/displayobjectcontainer.rs

This progresses Papa's games (fixes #9539).
The error code is correct but the error messages are not the same as Flash's, I opted to keep our more descriptive ones until we discover that the exact text is needed one day.

avm2: Use avm errors for RangeErrors inside DisplayObjectContainer

---

core/src/player.rs

Prints information about the loaded SWF. Outputs:
- version
- resolution
- framerate
- url
fixes #8531

core: add framerate to SWF load log

---

web/.eslintignore
web/.prettierignore
web/.stylelintignore
web/packages/core/.gitignore
web/packages/core/package.json
web/packages/core/src/load-ruffle.ts
web/packages/core/src/ruffle-player.ts
web/packages/core/tools/set_version.js
web/packages/core/tsconfig.json
web/packages/extension/src/plugin-polyfill.ts

This aligns with the other packages.

web: Change `ruffle-core` output directory to `dist`

---

web/packages/core/.gitignore
web/packages/core/package.json
web/packages/core/tsconfig.json
web/packages/extension/tsconfig.json

This slightly improves TypeScript build times, and allows LSP to work across packages without building `ruffle-core`.
Official documentation at:
https://www.typescriptlang.org/docs/handbook/project-references.html

web: Use TypeScript project references

---

web/src/audio.rs
web/src/lib.rs

`Closure::new()` works on stable Rust since wasm-bindgen 0.2.81 (https://github.com/rustwasm/wasm-bindgen/pull/2891). Use it in place of `Closure::wrap()` for more concise code.

web: Use `Closure::new()`

---

web/packages/core/package.json

* Wrap comments to maximum 100 characters per line.
* Take advantage of npm pre & post scripts to logically separate between WebAssembly (pre)build, TypeScript build, and `set_version.js` postbuild. More info at: https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts
* Rename some scripts to improve clarity:
* `build:ruffle_web` -> `build:wasm-vanilla`
* `build:ruffle_web-wasm_extensions*` -> `build:wasm-extensions*`
* `build:cargo_bindgen_opt` -> `build:wasm`
* Reduce script duplication by introducing the `$WASM_BINDGEN_FLAGS` and `$WASM_OPT_FLAGS` environment variables.

web: Cleanup `build` script in `package.json`

---

swf/src/read.rs
swf/src/types.rs

Although in SWFv5 the 2nd byte is documented to be reserved (all 0), Flash does read it and treats it the same as for SWFv6.
Fixes #8620 (might also #7301, and #9592).

swf: Don't truncate `ClipEventFlag` in SWFv5

---

core/src/lib.rs
render/webgl/src/lib.rs
swf/src/lib.rs

Seems like Clippy no longer complains about it.

chore: Allow `clippy::bool_to_int_with_if`

---

web/packages/extension/assets/_locales/zh_TW/messages.json

[Nightly 2023-02-27 extensions](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2023-02-27) are broken and throw this error:
>Extension is invalid
>Loading locale file _locales/zh_TW/messages.json: SyntaxError: JSON.parse: expected double-quoted property name at line 65 column 1 of the JSON data

web: Fix broken extensions

---

core/src/avm2/globals/flash/display/Sprite.as
core/src/avm2/globals/flash/display/sprite.rs
core/src/display_object/movie_clip.rs

Stores it on the DisplayObject, but we don't actually use it for anything yet.
This progresses Kingdom Rush.

avm2: Implement Sprite.hitArea getter & setter

---

.github/workflows/test_rust.yml

We consistently get false-positives from nightly changes, so don't fail the build (but still print warnings).

ci: Don't fail the build on Nightly clippy lints

---

core/src/avm2/globals/flash/profiler/Telemetry.as
core/src/avm2/globals/globals.as

Adds a fake Telemetry class to fool SWF's that use it (like crossbridge generated SWF's). This implementation mimics when Telemetry is not connected to any server

avm2: Add Telemetry class

---

swf/src/avm2/read.rs
swf/src/avm2/types.rs
swf/src/avm2/write.rs

This shaves off one `usize` from the size of `Op`.

avm2: Shrink `Op` enum by using a `Box<[i32]>` in `LookupSwitch`

---

core/src/avm1.rs
core/src/avm1/clamp.rs
core/src/avm1/globals/array.rs
core/src/avm1/globals/convolution_filter.rs
core/src/avm1/globals/date.rs
core/src/avm1/globals/displacement_map_filter.rs
core/src/avm1/globals/drop_shadow_filter.rs
core/src/avm1/globals/glow_filter.rs
core/src/avm1/globals/gradient_bevel_filter.rs
core/src/avm1/globals/gradient_glow_filter.rs
core/src/avm1/globals/number.rs
core/src/avm1/globals/sound.rs
core/src/avm1/object/stage_object.rs
core/src/types.rs

Previously there were multiple implementations scattered across the codebase. Unify them to a single place, in a more "Rusty" way (now it's called via dot notation, rather than as a free function).

core: Introduce and use `F64Extension::clamp_to_i32`

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/bitmap/bitmap_data.rs

If our render backend doesn't support BitmapData.draw, then we shouldn't try to continue execution normally (in AVM2). Many SWFs rely on inspecting the resulting `BitmapData` to implement game logic, which will result in strange bugs if the draw wasn't actually performed.

core: Produce an error when BitmapData.draw call is unsupported

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap_data.rs

If we bail out early, we want to preserve the current GPU -> CPU sync.

core: Call `overwrite_cpu_pixels_from_gpu` just before we draw

---

.github/workflows/test_rust.yml
Cargo.lock

Clap macros no longer produce `#[deny]`, so clippy passes again on nightly.

chore: Bump clap to 4.1.8 and re-enable nightly clippy on CI

---

desktop/src/main.rs

When running ruffle through cmd.exe or Powershell on Windows, ruffle desktop detaches from console before printing any errors encountered during initialization:
This PR changes error handling on main so the error is printed on cli before the console detaches:
Tested on Windows (cmd.exe and powershell) as well as MacOS.

desktop: Handle errors before detaching from console on Windows cli

---

tests/README.md
tests/tests/swfs/avm2/stage3d_raytrace/test.toml
tests/tests/util/options.rs

The test seems to be flaky on warp
Also reduce the number of max outliers since the vast majority are just a delta of 1

tests: Ignore stage3d_raytrace on WARP

---

core/src/avm2/globals/flash/display/DisplayObject.as
core/src/avm2/globals/flash/display/Stage.as

Fixes the incorrect rendering of the loading bar on #9829.

avm2: Stub DisplayObject.scale9Grid

---

core/src/avm2/globals/string.rs

Progresses #9254 to the menu. It needs `unescape` next.

avm2: Implement String.toString

---

.github/renovate.json5

Renovate only updates the version range in dependencies, but when they're things like `^1.2.3` then it's only going to update it with a major release, not any patches or minor fixes. That's supposed to be the job of the package manager (cargo, npm) and lock files.
This makes Renovate update our lock file every week to allow the package managers to keep us up to date with any fixes, rather than them happening arbitrarily whenever someone happens to run `cargo update` or `npm install` locally and PRs that.
See also #9876

chore: Tell renovate to maintain lock files

---

core/src/events.rs

I've been implementing a [custom frontend for Ruffle](https://github.com/JesseTG/ruffle_libretro), and due to how I queue up input events I needed `PlayerEvent` to implement the `Clone` and `Copy` traits. This PR does so.

Derive `Clone` and `Copy` in `PlayerEvent`

---

web/package-lock.json

Contributes to (but doesn't close) #9876 
This gets rid of vulnerability warning after `npm install`

chore: Run `npm audit fix`

---

core/src/loader.rs

Depending on when loading completes, calling
`catchup_display_object_to_frame` might trigger an `addedToStageEvent` inside the loaded SWF. The event listener will expect the SWF content to have 'DisplayObject.stage' accessible, so we need to make sure that we've added our loaded content as a child of the `Loader` *before* any event handlers run.
I've been unable to come up with a self-contained test for this, but it's necessary for Bloons Tower Defense 5

avm2: Initialize LoaderStream and Loader child before catchup_display_object_to_frame

---

web/packages/extension/package.json
web/packages/extension/tools/sign_xpi.js

This PR attempts to add support for source upload on addons.mozilla.org, which is a necessary prerequisite to automating our extension submissions again.
The reason why this wasn't done before is that:
* We use Mozilla's `sign-addon` tool to upload the extension, and that uses API v4
* Source upload was only added in API v5 and `sign-addon` does not implement that API endpoint
* Nobody at Mozilla is currently interested in updating `sign-addon` for API v5 (in lieu of a major refactor)
We hack around that by manually issuing the v5 requests using the same `Client` class that `sign-addon` provides. I'm still not 100% sure that this is correct, however; because the v5 API endpoint requires a version ID and I'm not sure the v4 (or v5) signing endpoint returns a compatible ID. In fact, [the …

[DRAFT] web: Extension source upload

---

Cargo.lock
video/software/Cargo.toml

Just the usual dance, to take advantage of https://github.com/ruffle-rs/h263-rs/pull/45.
Also, while I'm there, update Cargo.lock (even though DependaBot should do it periodically now).

chore: Bump h263-rs

---

web/package-lock.json
web/package.json

From package NPM page:
> As of Stylelint v15 all style-related rules have been deprecated. If you are using v15 or higher and are not making use of these deprecated rules, this plugin is no longer necessary.
Stylelint was upgraded to 15.0.0 on 68078dc commit
This is what caused the dependency error on my previous PR

web: Remove `stylelint-config-prettier` package

---

core/src/avm2/globals/flash/text/TextField.as
core/src/avm2/globals/flash/text/text_field.rs

progresses Resort Empire https://github.com/ruffle-rs/ruffle/issues/9965
now it is blocked by unimplemented BitmapData.threshold

avm2: Stub TextField.alwaysShowSelection

---

web/src/audio.rs

~This is not done yet, just pushing for visibility.~
The goal is to:
- Make demanding content (especially on mobile) as stutter-free as possible
- Reduce latency on lighter content (or on powerful hardware) as much as possible

web/audio: Dynamic buffer size

---

Cargo.lock
Cargo.toml
render/naga-agal/Cargo.toml
render/wgpu/Cargo.toml
render/wgpu/src/target.rs

Now we don't need to depend on @Aaron1011's fork of `naga_oil` for newer `naga` version, nor do we need to patch `wgpu`'s dependency on it.

wgpu: Update to wgpu 0.15.1, naga 0.11.0, and naga_oil 0.5.0

---

core/src/bitmap/bitmap_data.rs
render/src/bitmap.rs
render/wgpu/src/backend.rs
render/wgpu/src/lib.rs
render/wgpu/src/utils.rs

Previously we'd turn it into a vec and then put that in a struct and then copy that over manually to Pixels.
Now we just read straight from the buffer directly.

render: Make retrieve_offscreen_texture pass the raw buffer

---

core/src/avm2.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/avm2/parameters.rs
core/src/avm2/value.rs

We currently have so many different ways of pulling out parameters from the function, and almost every single one is wrong. The "correct" way to do it tends to be extremely verbose.
This introduces common methods for **correctly** getting the value of a given type from the function parameters slice, and converts BitmapData to use it as an initial proof of concept.
It's still missing more useful functions like getting native object types (DisplayObject from an arg, for example), but it's already a significant improvement.

avm2: Introduce ParametersExt and use it inside bitmapdata

---

.github/workflows/test_web.yml

The newly released 19.8.0 is crashing

ci: Pin node to 19.7.0

---

web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/packages/core/src/load-ruffle.ts
web/packages/core/src/polyfills.ts
web/packages/core/src/public-api.ts
web/packages/core/src/public-path.ts
web/packages/core/src/ruffle-player.ts
web/packages/extension/src/ruffle.ts

As @n0samu noted on Discord:
> I don't think we actually have any TypeScript type definition that correctly defines the object passed to player.load
> and I guess we've been relying all this time on no one actually calling that function from TypeScript
> or finding a way to trick TypeScript into letting them do it
This lets `player.load(player.loadedConfig)` work. See https://github.com/ruffle-rs/ruffle/pull/10040/commits/ad02672890dba071ca765dde3d41c23b63392352

web: Remove Config object; it was never a correct type for the config

---

.github/workflows/test_web.yml

https://github.com/nodejs/node/releases/tag/v19.8.1 was released to fix the Node 19.8.0 issue.

ci: Use latest Node 19

---

desktop/src/ui.rs
web/packages/core/src/ruffle-player.ts

I think we're very close to the point of removing it entirely, but until then let's be a little more confident in our support.

chore: Update avm2 compatibility warning to be less severe

---

core/src/avm2/globals/flash/display3D/vertex_buffer_3d.rs
core/src/avm2/object/context3d_object.rs
core/src/avm2/object/vertex_buffer_3d_object.rs
render/src/backend.rs
render/wgpu/src/context3d/mod.rs

We were ignoreing 'data32PerVertex'.
To make the code clearer, I've renamed the variable to 'data32_per_vertex', and made it a 'u8' (as it has a maximum of 64)

avm2: Fix VertexBuffer3D.uploadDataFromByteArray size calculation

---

render/naga-agal/src/builder.rs

I had previously applied this fix to fragment shaders, but I forgot to apply it to vertex shaders as well.

naga-agal: Correctly access vertex shader FunctionArgument

---

Cargo.lock
core/Cargo.toml
core/src/avm2/globals/flash/media/soundmixer.rs

This should make it _even faster_ than #9657.
Now I'm really glad for #9561!
Benchmarking to be done.
Thanks to https://github.com/ejmahler/rust_dct/issues/13#issuecomment-1465340496!

core/avm2: Use an actual FFT library in `computeSpectrum`

---

core/src/avm2.rs
core/src/avm2/call_stack.rs
core/src/avm2/globals.rs
core/src/avm2/script.rs
core/src/display_object/movie_clip.rs
tests/tests/swfs/avm2/error_stack_trace/output.txt

This can help determine which DoAbc2 file contains the script initializer that appears in a stack trace (though the name can be empty).

avm2: Add DoAbc2 tag name to GlobalInit call stack node

---

core/src/avm2/globals/flash/display3D/context_3d.rs
core/src/avm2/object/context3d_object.rs
render/src/backend.rs
render/wgpu/src/context3d/mod.rs

None of these formats can currently be implemented correctly with wgpu, so we just use Rgba8Unorm instead.
The handling of opaque compressed textures is a little sketchy - it should work for 'normal' SWFs that upload an opaque BitmapData, but we might need to manually adjust the alpha values if

render: Support more Context3D texture formats

---

core/src/avm1/globals/movie_clip.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/avm2/globals/flash/display3D/textures/cube_texture.rs
core/src/avm2/globals/flash/display3D/textures/rectangle_texture.rs
core/src/avm2/globals/flash/display3D/textures/texture.rs
core/src/avm2/object/context3d_object.rs
core/src/bitmap/bitmap_data.rs
core/src/display_object/bitmap.rs
render/src/backend.rs
render/src/bitmap.rs
render/wgpu/src/context3d/mod.rs
render/wgpu/src/lib.rs

We don't need to perform a sync when getting the width/height, getting or setting the 'disposed' status, or uploading to a Context3D texture.
The Context3D change (using `copy_texture_to_texture` instead of relying on the CPU pixels) has the added advantage of avoiding a validation error when our source image row length isn't aligned to `COPY_BYTES_PER_ROW_ALIGNMENT`
This dramatically speeds up the Fancy Pants World 4 loading time (on a branch with my XML prs merged). Without this change, my machine spends around 10 seconds on a blank white screen after clicking 'Play'. With this change, the time spent on that screen is reduced to around 1-2 seconds.

core: Avoid several BitmapData GPU -> CPU sync

---

tests/tests/regression_tests.rs

This makes the test output much less verbose.

tests: Use 'warn' log level for wpgu crates in regression tests

---

web/packages/core/src/ruffle-player.ts

Instead deduplicating separators in `RufflePlayer.showContextMenu()` using DOM attributes, do it right in `RufflePlayer.contextMenuItems()`, using a simpler approach.

web: Simplify custom context menu separators logic

---

core/src/avm2/globals/flash/text/TextField.as

These are used in the Rust handler, but were not correctly set in the AS bindings, leading to errors such as "Attempted to call flash::text::TextField::getTextFormat with 2 arguments (more than 0 is prohibited)"

avm2: Fix TextField.getTextFormat arguments

---

web/packages/core/src/ruffle-imports.ts
web/src/lib.rs

See the description of https://github.com/ruffle-rs/ruffle/issues/9105.
`ExternalInterface.call("window.location.href.toString")`, for example, is a method that is sometimes used to get the current webpage url.
This does not work in ruffle currently, because we trigger the javascript code `Reflect.get(window.location.href, "toString")` (which fails because href is a primitive and not an object) instead of `window.location.href["toString"]` (which works correctly).
The only way I could find to fix this was to expose a helper method from javascript - wasm_bindgen doesn't have anything built-in which is *actually* equivalent to target[key].

web: Allow ExternalInterface.call to call methods of primitive types (close #9105)

---

render/wgpu/shaders/bitmap.wgsl
render/wgpu/src/pipelines.rs
render/wgpu/src/shaders.rs

When using the bitmap.wgsl shader for normal rendering, we need to saturate immediately after applying the color transformation to reproduce Flash Player's behavior. This makes the (possibly transformed) alpha value get multiplied by a in-range color, instead of a potentially out-of-range color.
However, Stage3D just applies a no-op color transformation, and should only saturate at the very end
(not after the intermediate division by the original alpha value).
To support both of these requirements, I've added in a new `early_saturate` ifdef that controls when we apply 'saturate'. We then compile the shader twice (once with early_saturate=true and once with early_saturate=false), and use the two versions in the right pipelines.
We could use a simpler shader for Stage3D - however, it can't …

render: Compile a different version of 'bitmap.wgsl' for Stage3D

---

core/src/avm2/globals/flash/net.rs
core/src/avm2/globals/flash/net/LocalConnection.as
core/src/avm2/globals/flash/net/local_connection.rs

We don't really have a way to test this right now, sadly. Implementation is the same as AVM1.
This fixes many site locks, like https://www.newgrounds.com/portal/view/546416

avm2: Implement LocalConnection.domain getter

---

core/src/avm2/globals/flash/events.rs
core/src/avm2/globals/flash/events/MouseEvent.as
core/src/avm2/globals/flash/events/TimerEvent.as
core/src/avm2/globals/flash/events/TouchEvent.as
core/src/avm2/globals/flash/events/mouse_event.rs
core/src/avm2/globals/flash/events/timer_event.rs
core/src/avm2/globals/flash/events/touch_event.rs

Implement `MouseEvent.updateAfterEvent` and `TimerEvent.updateAfterEvent`. Implementation is the same as AVM1, simply signaling that a render is requested. The various frontends handle as appropriate by checking `core.needs_render()`.

avm2: Implement `updateAfterEvent`

---

.github/workflows/release_nightly.yml

For some reason, the reproducible source archive upload is failing, so switch to an actually maintained workflow for now

chore: Switch to GH-CLI to upload reproducible source ZIP

---

core/src/avm2/object/xml_list_object.rs

Fixes double borrow error seen here: #10303
Prevented an error from being thrown due to a double borrow.

avm2: Fix double borrow when setting local XMLList property

---

core/src/avm2.rs
core/src/avm2/call_stack.rs
core/src/avm2/function.rs
core/src/avm2/globals/error.rs
core/src/avm2/object/error_object.rs

This PR actually does 2 things:
1. Reduces the size of `CallNode` from 56 bytes to 24 bytes. This was done to keep call stacks as small as possible for the next change. (this was done in the first commit)
2. Store the call stack in every error message when log level is set to `Info`, rather than when the `avm_debug` feature is enabled. However, if `avm_debug` is enabled, we store the call stack regardless of the log level. (this was done in the second commit)
I think this way is better because it allows people who do not want to build their own version of Ruffle to retrieve stack traces from error messages. Keep in mind that displaying a stack trace is slow, and storing it will also use a lot of extra memory, which is why it's important we only do this when the user manually sets the log …

avm2: Show stack traces in error messages when log level is `Info`

---

web/src/audio.rs

This is just a tiny belated fixup of #10095. I renamed this identifier, but apparently not everywhere.

web/audio: nit: Rename `probation_time` to `probation_elapsed` everywhere

---

web/packages/core/src/ruffle-player.ts

Shows the panic screen when Ruffle encounters a serious error loading the SWF file. Detects config parse errors - these are the most likely cause of Ruffle failing to load an SWF that exists. Previously, when Ruffle failed to parse the provided config, it would continue to display the loading splash screen, with no outward sign of what went wrong. This confused a user in the help channel recently.

web: Display config parse errors

---

core/src/display_object/graphic.rs
core/src/display_object/morph_shape.rs
core/src/drawing.rs
core/src/font.rs
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
render/wgpu/src/mesh.rs
render/wgpu/src/surface.rs
render/wgpu/src/surface/commands.rs

I realized that our current way of doing vector meshes will leak if the Drawing/Shape gets dropped, which can happen with movies that use the drawing API a lot.
This replaces ShapeHandle with the same system that BitmapHandle uses, and adds a custom Drop for WebGL to use (not needed on wgpu or canvas)

Don't leak Shape meshes in renderer

---

web/packages/extension/assets/css/common.css
web/packages/extension/assets/css/options.css
web/packages/extension/assets/css/popup.css

Nothing major but it should improve the presentation of the extension a little.
- Made the nightly watermark smaller and slightly transparent so it doesn't look as out-of-place
- Changed the hover animation of the Ruffle logo to a snappier pop-out animation
- Slightly increased spacing between options and Ruffle logo in options menu

web: Improve styling of extension pop-up, options menus

---

web/packages/core/src/plugin-polyfill.ts
web/packages/core/src/polyfills.ts
web/packages/extension/src/plugin-polyfill.ts

Finally found a way to make this work.

web: Don't polyfill with self-hosted Ruffle while extension is loading

---

web/.stylelintrc.yaml

Stylelint 15.0.0 deprecated `indentation`: https://stylelint.io/migration-guide/to-15 Prettier already enforces indentation, so it can be removed from `.stylelintrc.yaml`.

web: Remove deprecated `indentation` Stylelint rule

---

Cargo.lock
core/Cargo.toml
core/src/avm2/error.rs
core/src/avm2/value.rs
wstr/Cargo.toml
wstr/src/buf.rs

`static_assertions` seems unmaintained, and anyway `assert!()` is usable in `const` contexts since Rust 1.57.0:
https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#panic-in-const-contexts So simply use the suggested method instead.
Also the `rustversion` dependency is no longer needed because https://github.com/rust-lang/rust/pull/94075 already landed in stable.

chore: Remove `static_assertions` dependency

---

core/src/avm2/globals/flash/display/Graphics.as

This method should have eight arguments, not six.

avm2: Fix bad `Graphics.drawRoundRectComplex()` stub

---

tests/tests/swfs/avm2/json_stringify/output.txt
wstr/src/ops.rs

Calling `Hash::write_bytes` isn't guaranteed to be equivalent to a sequence of `Hash::write_u8`.
Additionally, make sure the hash is truly prefix-free by hashing the length first.
------
Fortunately, the two methods are implemented as equivalent in the hashers used in Ruffle (the `std` default hasher and `FnvHasher`), so there was no observable bug; still, we shouldn't rely on implementation details.

wstr: Revert incorrect optimization in hash calculation

---

core/src/display_object/movie_clip.rs

This makes the error message visible if the `Error` is an `AvmError` (e.g. `VerifyError`, `ReferenceError`).

avm2: Log error message instead of error object

---

web/packages/core/src/public-api.ts
web/packages/core/src/ruffle-player.ts
web/packages/extension/src/ruffle.ts

Also fixes #5696
Edit: This only works when the extension is the version of Ruffle that winds up taking precedence. If the self-hosted build takes precedence, the extension is not loaded until after RufflePlayer.load, and therefore the extension configuration is not available until then , so I can't take the toggles into account before loading content. The best way to ensure the extension loads early enough to take precedence in order to properly test this PR is to simulate a slow network connection using network throttling, as described in https://developer.chrome.com/docs/devtools/network/reference/#throttling and https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/throttling/index.html.

extension: Give precedence to toggles over default options (fixes #5825)

---

web/packages/core/package.json

Pass `--force` to tsc to always force a recompile of the TypeScript on build.
`tsc` won't rebuild the output JS if the source hasn't changed, but this would cause the version info in `build-info.js` to never get updated after an initial build. `tsc` only takes a second to run, so force a full rebuild.
Also, `tsc` won't even rebuild the output if you delete the output JS files. I hit this after wiping out the `dist` folder in an attempt to solve the above, only to be way more confused about all the errors when none of the JS rebuilt!

chore: Always rebuild TypeScript

---

core/src/display_object/container.rs

Right now this method panics if a previous child is not in a render list, which causes https://github.com/ruffle-rs/ruffle/issues/10314. I'm totally unsure about this one, because I don't yet understand what's going on here, but at least that Sponge Bobbity thing works now.
Anyway, it would be nice if someone could explain me why there's a references in depth array to MovieClips that are not in render list.

fix ChildContainer.replace_at_depth() panic

---

core/src/backend/audio.rs
core/src/context.rs
core/src/player.rs

Instead of queueing up these events in the `Activation`, we can fire them immediately by making `AudioManager::update_sounds` a freestanding method that takes in an `UpdateContext`

avm2: Fire soundComplete events immediately

---

core/src/avm2.rs
core/src/avm2/activation.rs
core/src/avm2/globals.rs
core/src/avm2/globals/flash/system/ApplicationDomain.as
core/src/avm2/globals/flash/system/application_domain.rs
core/src/avm2/globals/globals.as
core/src/avm2/globals/stubs.as
core/src/avm2/object.rs
core/src/avm2/object/domain_object.rs
core/src/avm2/script.rs
core/src/context.rs
core/src/display_object/movie_clip.rs
core/src/display_object/stage.rs
core/src/display_object/text.rs
core/src/external.rs
core/src/loader.rs
core/src/player.rs

Previously, the `ApplicationDomain` constructor ignored its argument, instead of constructing a new domain with the specified domain as the parent.
Additionally, we were incorrectly executing code with `Activation::from_nothing` in several places, causing `ApplicationDomain.currentDomain` to return the system domain instead of the correct parent domain. I've introduced a new method `Activation::from_domain`, which allows explicitly passing in the domain. Internally, we now store an `Option<Domain>`, and panic when calling `caller_domain` with a `None` domain. Several places in the codebase have been adjusted to pass in the correct domain.

avm2: Implement ApplicationDomain constructor and fix parent handling

---

swf/src/types/color.rs
swf/src/types/point.rs
swf/src/types/twips.rs

Pointed out on Discord. Add `#[inline]` to `Twips`, `Point`, and `Color` methods.

swf: Add some inlines

---

core/src/display_object/container.rs

Fixes the regression highlighted by nosamu in https://github.com/ruffle-rs/ruffle/issues/9493#issuecomment-1438194951 while making sure it doesn't break the game mentioned in #9604 (https://archive.org/details/comiccreator_swf).

core: Correct `swapDepths`

---

web/packages/extension/src/utils.ts

This also reduces the size of `content.js` from ~170 KB to ~15 KB by removing code duplication.
Fixes #9997.

web: Fix XML document detection

---

core/src/avm2/globals/flash/media/Video.as

At least `smoothing` is used by z0r.de loops 7428 and 7876.
Relevant docs: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/Video.html#propertySummary

avm2: Stub Video.deblocking and Video.smoothing

---

web/packages/core/src/shadow-template.ts

Remove nonfunctional CSS style. Add word-break style to prevent the save manager table from overflowing its container (and getting a horizontal scrollbar). 
**Before**:
**After**:

web: Small CSS fixups for save manager

---

web/packages/extension/src/.eslintrc.yaml

Use the `@typescript-eslint/no-restricted-imports` rule in order to prevent #10422 from regressing. Ideally we wouldn't need to specify each dependency of `content.ts` (i.e. `utils.ts` and `common.ts`), but I haven't found any better way.

extension: Disallow content script to import `ruffle-core`

---

core/src/avm2/regexp.rs

avm2: Fix panic in regexp when a wide empty string is used

---

CONTRIBUTING.md

This has come up a number of times on discord now so I figure we should be very explicit about this.
Also has a few other minor changes to CONTRIBUTING.md for debugging & tests info.

Add reverse engineering info to CONTRIBUTING.md

---

Cargo.lock
core/Cargo.toml
core/src/avm1/object/xml_object.rs
core/src/avm2/e4x.rs
core/src/html/text_format.rs
core/src/xml.rs
core/src/xml/tree.rs

I've moved our special entity handling logic into
a `custom_unescape` function. This lets us move off of our fork of `quick-xml` back onto the crates.io release

core: Update to latest quick-xml

---

web/packages/core/src/ruffle-player.ts

This should work when the extension config loads after the self-hosted config too:
```ts
(window.RufflePlayer.conflict["newestName"] === "extension" ||
(window.RufflePlayer as Record<string, unknown>)[
"newestName"
] === "extension")
```

web: Give proper precedence to extension config when it is used

---

core/src/avm2/globals/flash/display/bitmap_data.rs

Remove the stub mark from `BitmapData.lock` and `unlock` and add comments describing the Flash Player behavior.
These control whether Flash updates the stage dirty area for any bitmaps on the stage displaying the bitmap data. This only controls the Flash Player's redrawing behavior. There's no functional difference, and all `BitmapData` operations (`getPixel`, `draw`, etc.) always use the latest pixel data, whether `lock` was called or not.
Because Ruffle has no concept of a stage dirty area at present, these methods are intentionally no-ops, and I don't think there's a compelling reason to leave them as stubs. The rendering of any content that forgets to `unlock` would vary in the Flash Player as well. A locked bitmap will be redrawn the next time the Flash Player happens to redraw that …

avm2: Unstub `BitmapData.lock` and `BitmapData.unlock`

---

render/wgpu/src/surface.rs

I incorrectly changed this in #10373
Fixes #10380

wgpu: Fix filter texture copy size calculation

---

core/src/avm2/globals/QName.as
core/src/avm2/globals/RegExp.as

1. `QName` does not define `valueOf` on its prototype.
2. `RegExp`'s prototype should not be enumerable, and it should have a `toString` defined on its prototype (but _not_ as an `AS3` one).

avm2: QName and RegExp fixes

---

core/src/avm1/globals/external_interface.rs
core/src/avm2/globals/flash/external/external_interface.rs
core/src/external.rs
tests/tests/swfs/avm1/external_interface/output.txt
tests/tests/swfs/avm2/external_interface/output.txt
web/src/lib.rs

Fixes #8621. The behavior can be verified using [this sample](https://github.com/ruffle-rs/ruffle/files/11045693/externalUndefined.zip).

core: Make `ExternalInterface.call` support `undefined` values in browsers

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm1/globals/movie_clip.rs
core/src/avm1/object/bitmap_data.rs
core/src/avm2/filters.rs
core/src/avm2/globals/flash/display/bitmap.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/avm2/globals/flash/display/graphics.rs
core/src/avm2/globals/flash/display3D/textures/cube_texture.rs
core/src/avm2/globals/flash/display3D/textures/rectangle_texture.rs
core/src/avm2/globals/flash/display3D/textures/texture.rs
core/src/avm2/object.rs
core/src/avm2/object/bitmapdata_object.rs
core/src/bitmap/bitmap_data.rs
core/src/bitmap/operations.rs
core/src/display_object/bitmap.rs

We now exclusively use BitmapDataWrapper places and be explicit about syncing, which also shown that we were syncing in more places we didn't have to (like assigning to a Bitmap, or disposing)
Definitely more cleanups to be done but trying to take it piece by piece

core: BitmapData cleanups + slightly less syncs

---

render/wgpu/shaders/color.wgsl

The color is the same through the whole shape and doesn't change per pixel, so calculate the color in the vertex stage instead of the fragment stage.

wgpu: Slight optimization to color shader

---

Cargo.lock
core/src/bitmap/bitmap_data.rs
core/src/display_object/bitmap.rs
render/Cargo.toml
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/src/bitmap.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
video/software/Cargo.toml
video/software/src/backend.rs
video/software/src/decoder/h263.rs
video/software/src/decoder/screen.rs
video/software/src/decoder/vp6.rs
video/src/frame.rs

This will be useful for skipping conversion to RGBA where not absolutely needed - or even doing it in a hardware accelerated way by the renderer.

video: Make DecodedFrame able to hold frames in different formats

---

Cargo.lock
core/src/avm2/globals/array.rs
core/src/bitmap/bitmap_data.rs
core/src/display_object/bitmap.rs
core/src/display_object/edit_text.rs
render/Cargo.toml
render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/src/bitmap.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
video/software/Cargo.toml
video/software/src/backend.rs
video/software/src/decoder/h263.rs
video/software/src/decoder/screen.rs
video/software/src/decoder/vp6.rs
video/src/frame.rs

1. toString and toLocaleString should only be defined on the prototype.
2. concat should only be defined as an as3 and proto property, not as an instace property.
3. Array doesn't have a valueOf defined directly on it.
Progresses #9085 a little.

avm2: Array-related fixes

---

.github/workflows/release_amo.yml
.github/workflows/release_nightly.yml
web/packages/extension/tools/sign_xpi.js

This removes all extension upload related processes from nightlies - specifically addons.mozilla.org uploads. Unsigned nightlies will still be compiled and provided as normal.
A new weekly upload workflow has been added for actually submitting the latest nightly to Mozilla for addons.mozilla.org. Since we have automated source code submission, this should Just Work™ in one click, and I no longer need to add and remove the extension ID secret every time I want to turn extension upload off and on. The weekly upload process can also be triggered manually at any time if something should fail - it does not create any Git tags.

web: Split Firefox extension upload into a separate process

---

.github/workflows/release_amo.yml

Turns out that even a broken YAML file won't actually trip CI to warn you about merging in something that will break CI. GitHub Actions has no self-defense mechanism.

Unbreak CI

---

desktop/src/main.rs
desktop/src/navigator.rs

These options already existed on web. This makes them available in the desktop app as well.

desktop: Add base and max execution duration options

---

desktop/src/navigator.rs

On desktop, if the movie URL ended in an empty path segment (a slash), then the base URL used for loading relative URLs would be incorrect. For example, if the movie URL was `http://games.example.com/game2/`, then Ruffle would use `http://games.example.com/` as the base for relative fetches, when it should use `http://games.example.com/game2/`.

desktop: Fix loading relative URLs when movie URL ends in empty path segment

---

core/src/display_object/edit_text.rs

This is not a big change since the relevant parts are already in place:
https://github.com/ruffle-rs/ruffle/blob/c6298047d9815046541194d169d54881edc0dbf1/core/src/display_object/edit_text.rs#L138-L140
https://github.com/ruffle-rs/ruffle/blob/c6298047d9815046541194d169d54881edc0dbf1/core/src/display_object/edit_text.rs#L336-L343
https://github.com/ruffle-rs/ruffle/blob/c6298047d9815046541194d169d54881edc0dbf1/core/src/display_object/edit_text.rs#L1231-L1242
Fixes #9234.

core: Support `maxlength` attribute in EditText

---

core/src/avm1/globals/selection.rs
core/src/focus_tracker.rs
tests/tests/swfs/avm1/selection/output.txt

- `Selection.getFocus()` now returns a string on success, instead of an object. Our test logs the correct values because of the string coercion when using `trace`.
- `Selection.setFocus(str)` now accepts strings like `"focus"` or `"_root.focus"`. This fixes #2789.
- `Selection.setFocus(focus)` to a text field was giving the focus internally, however it wasn't possible to type anything on the keyboard. This can also be observed in the issue mentioned above. Note that it can be difficult to notice that the field has focus because of #2189 (now also happens on desktop on my end).
- `Selection.setFocus(focus)` now returns `true` on success, `false` on failure. I updated the test output to that end. Note that it's possible for `setFocus` to fail and return `false` if the file itself doesn't …

avm1: Fix some issues with `Selection.getFocus()` and `setFocus()`

---

core/src/avm2/globals/flash/filters/ColorMatrixFilter.as

This ensures that we call the normal Array concat method (or a method that overrides it). Some SWFs may define a *public* concat method in an Array subclass, with a different signature.
Fixes #10552

avm2: Call 'AS3::concat' in ColorMatrixFilter

---

.github/workflows/test_rust.yml
CONTRIBUTING.md
Cargo.toml

This makes the cargo command to run the player simpler:
`$ cargo run stuff.swf`
Instead of:
`$ cargo run --bin ruffle_desktop -- stuff.swf`
See: https://github.com/rust-lang/cargo/issues/7290

chore: Select "desktop" as the default workspace member

---

.github/workflows/release_amo.yml

The reason for this is twofold:
* Running the release at the same time as the build means we are likely to miss the actual XPI file we need to build. This is a race condition introduced by this being a different workflow that waiting a bit should at least paper over.
* While our policy was "release on Fridays", this was Friday in US time. Workflows are scheduled in UTC, so it was coinciding with the Thursday nightly.

web: Submit the extension at 2AM Saturday UTC.

---

web/packages/core/src/ruffle-player.ts

Fixes the context menu looking like this on iOS:
This was happening because Ruffle was unconditionally adding a separator before the "About Ruffle" menu item, even if there were no menu items before it.

web: Don't duplicate context menu separators

---

core/src/avm2/activation.rs

Unfortunately I couldn't get mxmlc to generate such bytecode for a test :/

avm2: Support `newcatch` with finally-scopes

---

core/src/display_object/container.rs

[A previous change](https://github.com/ruffle-rs/ruffle/pull/8944/files#diff-7b448c1d34980fdeb5c34bbaf557a6eb287d89d2bf091c943c46bbe00004c9ac) that was meant to only target AVM2 caused #7783 (an AVM1 game) to partially work by a total fluke.

core: Fix avm2 code interfering with avm1

---

video/software/src/decoder/vp6.rs

Specifically, when Y and A frame sizes differ. For some reason this being possible hasn't even occurred to me, it just happened to work before.
This regressed in 2ad4399 (#9753).
Fixes #10700.

video/vp6: Fix glitching with some VP6A videos

---

core/src/avm1/object_reference.rs
core/src/avm1/value.rs

Brings `Value` from 48 bytes to 24 bytes on 64-bits targets (and similarly for 32-bits).
This doesn't actually cost an extra allocation as we can replace an inner `Gc<Vec<_>>` by a `Box<[_]>` directly.

avm1: shrink `Value` by boxing `MovieClipReference`s

---

core/src/avm2/object/class_object.rs

This is the last of the low-hanging fruit that I could find.

avm2: Take a MutationContext instead of an Activation in ClassObject.install_class_vtable_and_slots

---

web/packages/core/typedoc.json

Now possible thanks to https://github.com/TypeStrong/typedoc/issues/2237.
This sorts our enums like [LogLevel](https://ruffle.rs/js-docs/master/enums/LogLevel.html) in source order while keeping the existing order for everything else.

web/docs: Display enums in source order

---

core/src/avm2/globals/flash/display/stage.rs
core/src/context.rs
core/src/player.rs
desktop/src/main.rs
web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/src/lib.rs

Implements the feature described in and closes #3276.
Provides an easy workaround for #9325.

core: Add frame rate config option

---

web/packages/extension/src/common.ts
web/packages/extension/src/content.ts
web/packages/extension/src/utils.ts

Omit config values from `DEFAULT_OPTIONS`, which are already part of `DEFAULT_CONFIG` in `ruffle-core`. Also use spread syntax to avoid naming each config that should pass to `ruffle-core`.

extension: Make `Options` extend `BaseLoadOptions`

---

web/packages/core/src/.eslintrc.yaml
web/packages/core/src/polyfills.ts
web/packages/core/src/public-api.ts
web/packages/core/src/ruffle-player.ts

* Extend from `plugin:jsdoc/recommended-typescript-error`, which is more suitable for TypeScript and errors by default.
* Remove default and disabled but passing rules.
* Configure `jsdoc/tag-lines` to match JSDoc style of current codebase.

web: Update JSDoc lint rules

---

web/packages/core/src/shadow-template.ts

Prevents Ruffle from inheriting page CSS, ensuring that it displays as expected. Prevents bugs like #8978 without needing to explicitly set every relevant style to its default value.

web: Don't inherit page CSS

---

web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/packages/core/src/ruffle-player.ts
web/src/lib.rs

The option 'max_execution_duration' previously only supported the type '{secs: number, nanos: number}'. Now it also supports using floating point numbers (and integers).
Default values have been changed to use floating point numbers.
**New pull request after I messed up git rebase and git force push** https://github.com/ruffle-rs/ruffle/pull/10818

web: Expand 'max_execution_duration' type in extension.

---

web/packages/core/src/ruffle-player.ts

Create a child element instead of setting innerHTML.
Fixes #10817.

Fix #10817

---

web/packages/extension/src/utils.ts

I noticed by accident that some configuration settings had not been initialized in the extension, this PR should fix it.
Before:
After:
("Preferred renderer" not being set is correct, since its default value is `null`).

web: Use default configuration in extension.

---

core/src/avm1/activation.rs
core/src/avm1/function.rs
core/src/avm2/globals/flash/utils.rs
core/src/display_object/edit_text.rs
core/src/display_object/movie_clip.rs
core/src/html/text_format.rs
core/src/string.rs
wstr/src/buf.rs
wstr/src/common.rs
wstr/src/lib.rs
wstr/src/ops.rs
wstr/src/ptr.rs

Various `wstr`-related refactorings extracted from my experimental string interning branch.

Clean up and expand `ruffle_wstr`'s API

---

web/packages/extension/assets/_locales/en/messages.json
web/packages/extension/assets/css/common.css
web/packages/extension/assets/options.html
web/packages/extension/src/common.ts

Add an option to the 'options' menu for the extension for setting the maximum execution time for Actionscript code.
Since this option is likely to be rarely changed by users, it has not been added to the 'popup' UI, only the 'settings' UI.
The changes only modify the CSS layout to a minor degree. I might look into making the UI layout CSS more robust in a later pull request, though no promises.
**This PR is for the same functionality as for #10787 , but from a separate branch and up to date with the newest changes.**

extension: Add option for setting max. exec. time

---

core/src/avm1/activation.rs
core/src/avm1/globals/movie_clip.rs
core/src/avm1/object/stage_object.rs
core/src/avm2/globals/flash/display/display_object.rs
core/src/avm2/globals/flash/display/sprite.rs
core/src/avm2/globals/flash/events/mouse_event.rs
core/src/avm2/object/event_object.rs
core/src/context.rs
core/src/display_object.rs
core/src/display_object/avm1_button.rs
core/src/display_object/avm2_button.rs
core/src/display_object/edit_text.rs
core/src/display_object/graphic.rs
core/src/display_object/interactive.rs
core/src/display_object/loader_display.rs
core/src/display_object/morph_shape.rs
core/src/display_object/movie_clip.rs
core/src/display_object/text.rs
core/src/drawing.rs
core/src/player.rs
core/src/prelude.rs
render/canvas/src/lib.rs
render/src/matrix.rs
swf/src/types/matrix.rs
swf/src/types/point.rs
swf/src/types/rectangle.rs

Convert nearly all instances of `(Twips, Twips)` (maybe besides in `shape_utils.rs`) to `swf::Point<Twips>`.
Fixes #6973.

chore: Use `swf::Point` in many places

---

web/packages/extension/src/player.ts
web/packages/extension/src/popup.ts

The problem seems to have been the inclusion of setting values that the previous equality function did not handle correctly. This function broadens the kinds of setting values that can be handled correctly.

extension: Fix popup setting changed reload detection.

---

core/src/avm1/activation.rs
core/src/avm1/object/stage_object.rs
core/src/avm2/globals/flash/display/display_object.rs
core/src/avm2/globals/flash/display/sprite.rs
core/src/display_object.rs
core/src/display_object/edit_text.rs
core/src/player.rs

`startDrag()` used to capture the offset between the mouse cursor and dragged object. This is buggy when the dragged object position is changed *while* being dragged, as the original offset no longer holds.
Change the dragging mechanism to be based purely on mouse deltas, eliminating said offset completely.
Fixes #10775.

core: Fix moving objects while being dragged

---

render/canvas/src/lib.rs
render/src/matrix.rs
swf/src/types.rs
swf/src/types/point.rs

Generally, when transforming a difference between two points, `p1` and `p2`, with a matrix `m`, we would like the following property to hold:
```
m * (p1 - p2) == m * p1 - m * p2
```
Unfortunately, it wasn't like this before, because matrices have a translation component, which is non-linear. In `m * p1 - m * p2`, the translations of `m * p1` and `m * p2` are the same and therefore cancel out each other. However, in `m * (p1 - p2)` the translation stays.
In order to preserve this property, introduce a new `PointDelta` type which is not subject to translation when transformed by a matrix.
For now, the following operations are supported:
* `Point - Point -> PointDelta`
* `Point + PointDelta -> Point`
* `Point += PointDelta`
* `Point - PointDelta -> Point`
* `Point -= PointDelta`
As a …

swf: Introduce `PointDelta`

---

web/packages/extension/assets/options.html

The shown UI value is hard-coded to be 32 when the internal value for `playerVersion` is `null`, but that should be alright, since it is guessed that the default value will continue being 32 for many years according to discussions elsewhere. And it should be easy to change or figure something else out if this does not hold for whatever reason.

extension: Add UI presentation for playerVersion default value.

---

web/packages/core/src/ruffle-player.ts

Fix wrong display of panic error details caused by #10819:

web: Fix panic error details display

---

web/packages/core/src/ruffle-player.ts

`.at()` is available since 92, while we still declare support for 87+.
note: I didn't build it to test it, I just tested the snippet.

web: Avoid array.at() for browser compatibility

---

render/canvas/src/lib.rs
render/src/backend.rs
render/src/backend/null.rs
render/webgl/src/lib.rs
render/wgpu/src/backend.rs
web/packages/core/src/ruffle-player.ts
web/src/lib.rs

Log which renderer-backend was actually used in the browser console.
This is basically the same as https://github.com/ruffle-rs/ruffle/pull/10903 , but without the toggle option for whether to warn or not if the actually used renderer is not the same as the preferred renderer.
Related to: https://github.com/ruffle-rs/ruffle/pull/10835 , https://github.com/ruffle-rs/ruffle/pull/10831 , https://github.com/ruffle-rs/ruffle/pull/10900 .
CC: @n0samu @relrelb .

extension: Log used renderer.

---

web/packages/extension/assets/_locales/de/messages.json
web/packages/extension/assets/_locales/en/messages.json
web/packages/extension/assets/_locales/es/messages.json
web/packages/extension/assets/_locales/fr/messages.json
web/packages/extension/assets/_locales/hu/messages.json
web/packages/extension/assets/_locales/it/messages.json
web/packages/extension/assets/_locales/ja/messages.json
web/packages/extension/assets/_locales/ko/messages.json
web/packages/extension/assets/_locales/nl/messages.json
web/packages/extension/assets/_locales/pt_PT/messages.json
web/packages/extension/assets/_locales/ro/messages.json
web/packages/extension/assets/_locales/ru/messages.json
web/packages/extension/assets/_locales/sv/messages.json
web/packages/extension/assets/_locales/tr/messages.json
web/packages/extension/assets/_locales/zh_CN/messages.json
web/packages/extension/assets/_locales/zh_TW/messages.json
web/packages/extension/assets/css/common.css
web/packages/extension/assets/css/options.css
web/packages/extension/assets/options.html
web/packages/extension/assets/popup.html
web/packages/extension/src/common.ts

Intended to supersede #10831, this PR does the following:
- Adds a collapsible "Advanced options" section to the extension settings page and moves less commonly used options there. (Thanks to @relrelb)
- Adds an "Automatic" option for preferred renderer in the extension settings page (Thanks to @iwannabethedev)
- Adds missing extension messages and improves wording for some existing ones. (Thanks to everyone who suggested these)
- ~~Adds an `enableFallbackRenderers` option that can be used to disable all fallback renderers. This is an attempt to address https://github.com/ruffle-rs/ruffle/pull/9904#discussion_r1174630515 in a way that I find more palatable than #10835. Even so, I would rather not add this option because I think its usefulness to developers is outweighed by the …

web: Various improvements to options

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/bitmap/bitmap_data.rs
core/src/bitmap/operations.rs
render/src/backend.rs
render/src/bitmap.rs
render/wgpu/src/backend.rs

Main optimizations:
- Removed in-loop checks for "is pixel inside bitmapdata" for most methods, only iterate pixels that are valid to begin with
- `BitmapData.copyPixels()` will do its best to find the fastest way to copy a region on the cpu, including just sometimes straight up replacing the entire `Vec<Color>` if it needs to
- `BitmapData.draw(anotherBitmapData)` will recognizes cases that are trivial copies and act like `copyPixels()`, and do those on the CPU efficiently too. This means we don't need to sync those draws back, so it can be really fast for games that just use BitmapData as a kind of staging texture.
A side effect of this is that **some** `BitmapData.draw()` will work on backends that don't current support it, as the renderer isn't involved.
I was originally trying to get …

BitmapData optimisations: faster copies (including draws that are copies)

---

core/src/avm2/globals/flash/net/Socket.as

I need stubs for `flush` and `writeBytes` for my tool [friedkeenan/tfm-secrets-leaker](https://github.com/friedkeenan/tfm-secrets-leaker) which overrides those methods.
I looked through the project to see how to make a test for stubbed methods but from my searches it did not seem like stubs are tested at all, so I neglected to add any tests. I can confirm though that it works.
Also it seems like there were some lines with only whitespace that my editor removed upon saving.

avm2: Stub rest of Socket's methods

---

core/src/compatibility_rules.rs

Kongregate used to serve their SWFs from chat.kongregate.com, and some games check for this specifically.
Fixes the omega catalog in [Learn to Fly 2](https://www.kongregate.com/games/light_bringer777/learn-to-fly-2).

core: Improve compatibility rule for Kongregate

---

core/src/avm2/globals/flash/system/system.rs
web/Cargo.toml
web/src/ui.rs

Closes #6476.
I also tried to address the TODO for the AVM2 `set_clipboard` but I wasn't able to find a way to retrieve the type of event that triggered the function call.

web: Support copying to clipboard

---

web/src/lib.rs

Upon panic, `Ruffle::destroy()` attempts to mutably borrow the thread-local `instances`. However, when a panic occurs, `instances` is already immutably borrowed by `Ruffle::with_core_mut()`. This causes the cleanup logic in `Ruffle::destroy()` to be skipped altogether, and as a consequence the animation handler continues to be fired, ultimately failing to borrow `instances` repeatedly. Each time a borrow fails, a console error is logged.
Fortunately the fix is extremely easy - `Ruffle::with_core{,_mut}` used to `drop(instance)` before running any potentially-panicking logic, exactly for the reason explained above. But those functions don't `drop(instances)`, which is subject to the same double-borrow risk. So as a fix simply add `drop(instances)` in both functions.
With this fix, "Unable …

web: Fix "Unable to lock Ruffle core" console spam after panic

---

desktop/src/main.rs

Simple addition to let desktop users adjust global audio volume when starting ruffle from the command line.

desktop: Add volume option to CLI

---

core/src/bitmap/operations.rs
render/src/bitmap.rs

With help from and credit to @Dinnerbone and @n0samu , we have a probable fix for #10955 .
Credit for https://github.com/ruffle-rs/ruffle/pull/11006/commits/19b6cf68a11a1111d48d59358d6a6f2e7fe4d1ae goes fully to @Dinnerbone .
I have run the game "Dont escape 3", and the introduction part of it works now, without any panics or rendering issues as far as I can tell.
See also https://github.com/ruffle-rs/ruffle/pull/10583 .
Fixes #10955 .
Fixes https://github.com/ruffle-rs/ruffle/issues/11007 .
Might fix https://github.com/ruffle-rs/ruffle/issues/11017 .

render/core: Fix of panic bug and rendering bug in #10955 .

---

web/package-lock.json
web/packages/core/package.json
web/packages/core/src/ruffle-player.ts

Clicking "Backup all saves (download all sols)" in the Save Manager currently triggers a download prompt for each available sol. This can be a bit annoying when you have dozens or hundreds of saves. This PR changes this behavior by placing the saves in a ZIP file.

web: Download all sols as single .zip

---

core/src/avm2/globals/flash/display/display_object_container.rs

For `display_object_container.validate_remove_operation`.

avm2: nit: Provide error number in error message

---

web/packages/core/tools/bundle_texts.js

Currently, translations can look broken if the page is not UTF-8 encoded:

extension: Fix encoding issues affecting translations

---

web/packages/extension/assets/_locales/en/messages.json
web/packages/extension/manifest.json5
web/packages/extension/src/popup.ts

In the current builds, when you open a SWF directly (say [Ultimate Flash Sonic](https://uploads.ungrounded.net/151000/151706_ultimate_sonic.swf)) and click the Ruffle icon in your browser, it says that "Ruffle cannot load on protected browser pages.". This PR fixes that minor issue.
A new string is also introduced to that end (let me know if the wording can be improved). I also wonder if we should change the string that mentions the "protected browser pages", since this notion may not be obvious for some users.

extension: Don't say that Ruffle cannot load on "player.html"

---

web/packages/selfhosted/webpack.config.js

This is a follow-up to #11023: I haven't paid attention earlier but the changes we made in this PR didn't actually affect self-hosted builds because Webpack default minification/obfuscation somehow reverts them.

web: Only minify ascii characters on selfhosted builds

---

web/packages/core/src/ruffle-player.ts

Apparently, in this situation, rather than throw a SecurityError as mentioned on https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage, localStorage is just null.

web: Fix localStorage check on Firefox when dom.storage.enabled is false

---

.github/workflows/download_translations.yml
.github/workflows/upload_texts.yml
crowdin.yml

100% untested.
~Needs a new secret added, `CROWDIN_PERSONAL_TOKEN`. Get this from https://crowdin.com/settings#api-key~ (This is done)
Pushes source texts when they land in master, and makes a new PR for translations if there is any new ones, once per day. If that's too much (I don't think they'll be that often) we can reconsider it.
The translation PRs are trivial and don't need reviewing really.

ci: Add crowdin github actions

---

render/src/shape_utils.rs
swf/src/types/twips.rs

Fixes #11077 .
Related PR: #11014 .
An automated test has been added.

Fix overflow bug in `shapeutils::winding_number_line()`.

---

web/packages/core/tools/bundle_texts.js
web/packages/extension/src/content.ts

Explained in https://github.com/ruffle-rs/ruffle/issues/11098#issuecomment-1552406624. I've tested that this fix works equally well for English, Korean and French locales on the following pages:
- http://www.futureexpress.net/ (mentioned on Discord)
- http://omoshiro.gozaru.jp/html/dare.html (#11056)
- https://www.ccdmd.qc.ca/fr/modules/diagnostics/ (originally showed garbled text like Toad's screenshot before his PR #11023, fixed by that PR and still works with this one)

extension: Set charset attribute of script tag instead of escaping characters

---

core/src/avm2/object/event_object.rs
core/src/display_object/interactive.rs

This matches the Flash Player documentation. Since we were manually traversing the displayobject hierarching when firing the event, we ended up firing duplicate events to parents because bubbling was enabled.

avm2: Set 'bubbles' to 'false' for rollOut and rollOver events

---

.github/workflows/release_nightly.yml

Resolves #11105. Tested on my branch and seems to be working perfectly: https://github.com/n0samu/ruffle/releases

ci: Use GitHub CLI instead of deprecated actions

---

core/src/avm2.rs
core/src/avm2/globals/flash/system.rs
core/src/avm2/globals/flash/system/Capabilities.as
core/src/avm2/globals/flash/system/capabilities.rs
core/src/player.rs

Eventually, code from #10469 can be reused to implement the rest of the `flash.system.Capabilities` getters.
Fixes #9180.

avm2: Work on flash.system.Capabilities

---

core/src/player.rs

AVM2 can handle a missing root movie, and AVM1 doesn't seem to rely on having a root movie during Stage initialization.

core: Don't create a fake root clip when instantiating Stage

---

tests/tests/swfs/avm2/audio_computespectrum/test.toml
tests/tests/util/runner.rs

With no separate thread and sleeping to worry about, this should make the `computespectrum` test 100% reproducible, and not take 10 seconds to run.
Should prevent spurious failures such as:
https://github.com/ruffle-rs/ruffle/actions/runs/4962589152/jobs/8880836781?pr=11027
Somehow I wasn't aware that this "push" style execution model is also available in the `AudioBackend` trait when I originally made that test... :upside_down_face:

tests: Make the audio backend tick every frame in the runner

---

.cargo/config.toml
core/src/backend/ui.rs
core/src/display_object/edit_text.rs
core/src/events.rs
core/src/player.rs
desktop/src/main.rs
desktop/src/ui.rs
web/Cargo.toml
web/packages/core/src/ruffle-player.ts
web/src/lib.rs
web/src/ui.rs

This is a rebase and update of #2081. The same TODO items still apply, but those would be for a possible future PR. I've moved the left/right arrow key handling into the same code path as the rest of the text control events. ~~I'm marking this PR as a draft because I plan to implement pasting from the clipboard on web - that's the main feature still missing. In the meantime, please provide your reviews/feedback!~~ I've implemented clipboard pasting on web!
https://github.com/ruffle-rs/ruffle/assets/71368227/abf6f939-1f8d-4faf-ad75-829d4da7d8ad
Fixes the save/load menus in #4817, Fixes part of #1891.

core: Implement handling of text control input

---

desktop/src/main.rs

Fixup for #11059, which broke left/right arrow key controls on desktop

desktop: Fire both KeyDown and TextControl events

---

render/naga-agal/src/builder.rs

We need to use the same logic that we use for `get_varying_pointer`, since the AGAL shader can access vertex inputs in any order.

agal: Correctly check vertex_input_expressions cache

---

core/src/avm2/globals/flash/ui/ContextMenu.as

Added setter for ContextMenu.builtInItems stub
fixes https://github.com/ruffle-rs/ruffle/issues/11053

avm2: Stub ContextMenu.builtInItems setter

---

core/src/avm2.rs

`.as_primitive()` doesn't get inlined because of the GcCell check and possible unwrap inside.
`push()` is hot enough that this actually makes a ~~noticeable~~ measurable difference on profiles (at least when combined with other optimizations).

avm2: Avoid a function call on every push()

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/bitmap/bitmap_data.rs
core/src/bitmap/operations.rs
render/src/bitmap.rs

This is a packed ARGB value, so it doesn't make sense for it to be signed.

core: Store Color as an u32 instead of a i32

---

desktop/assets/texts/en-US/main_menu.ftl
desktop/src/app.rs
desktop/src/gui.rs
desktop/src/gui/controller.rs
desktop/src/player.rs

Will come in handy with (not-yet-made) debugging overlays, to prevent values shifting all the time.
Also it's cool to just pause things.
I'm thinking a future option might be "pause in background" or something similar.

desktop: Add suspend/resume buttons

---

desktop/src/app.rs

Now, we only return `WaitUntil` if the player is running and actually can give us the wakeup time.

Desktop: Stop busy looping when idling

---

web/packages/core/src/ruffle-embed.ts
web/packages/core/src/ruffle-object.ts
web/packages/core/src/swf-utils.ts
web/packages/extension/src/background.ts

Closes #11050, by making the polyfill more lenient with the "application/octet-stream" and "binary/octet-stream" MIME types, as suggested by @n0samu in https://github.com/ruffle-rs/ruffle/issues/11050#issuecomment-1547507019.

web: Allow extra MIME types in the polyfill

---

desktop/src/gui/controller.rs

if the user is on light mode, use light menu bars and windows within egui - also handles changing modes when ruffle is running

[desktop] use light menus on light theme & detect changes

---

CONTRIBUTING.md

This clarifies some things that confused me when I was starting out, and should help new contributors.

docs: Add detailed instructions for running tests

---

desktop/src/app.rs
desktop/src/backends/ui.rs
desktop/src/custom_event.rs
desktop/src/gui.rs
desktop/src/gui/controller.rs
desktop/src/player.rs

Not a fan of how many layers I needed to go through hah ;D
Benefits:
- doesn't block the main thread anymore
- can be dismissed by clicking anywhere
- the link is actually clickable :)
Ideally this code can be later reused to replace the generic AS3 popup by a per-feature popup, but that's out of scope.
I didn't touch the other messages supported by the DesktopUiBackend.

desktop: rewrite AS3 warning popup in egui

---

core/src/avm2/globals/flash/display/Loader.as
core/src/avm2/globals/flash/display/loader.rs

Progresses #10960 and #9901- the clips now get unloaded, but sound continues playing because <s>the AS2 code to stop the sound never gets executed (mixed AVM).</s>the clips continue looping, even when being orphans.

avm2: Partial implementation of Loader.unload

---

.github/workflows/release_nightly.yml
PKGBUILD

Previously it was skipped, which isn't a good practice.

ci: Provide `sha512sums` in AUR package

---

.github/workflows/release_nightly.yml

`actions/download-artifact` cannot be used because only macOS artifacts are uploaded using `actions/upload-artifact`.
Instead use `gh release download`, which mirrors `gh release upload`.

ci: Fix artifact download for AUR package

---

core/src/avm2/activation.rs
core/src/avm2/globals/flash/display/loader.rs
core/src/avm2/globals/flash/system/application_domain.rs
core/src/avm2/globals/flash/utils.rs

There are only a few places where we actually need to use the `caller_domain`, so we don't actually need it available for most native method calls. This means that `Activation::from_nothing` can be used in the vast majority of cases without causing a panic later on.

avm2: Make `caller_domain` an `Option`, and call `expect` when actually needed

---

Cargo.lock
render/Cargo.toml
render/naga-agal/src/lib.rs
render/naga-agal/src/types.rs
render/wgpu/Cargo.toml
render/wgpu/src/context3d/current_pipeline.rs
render/wgpu/src/context3d/mod.rs

We use an `lru::LruCache` inside `ShaderModuleAgal`. This automatically gives us the proper garbage-collection behavior (when the Flash Program3D instance is garbage collected, we'll drop the `ShaderModuleAgal` and the cache).
The cache is keyed on the data needed to compile the shader (vertex attributes and sampler overrides). This lets us avoid shader recompilations when a Stage3D program repeatedly uses the same Program3D with different sampler overrides / vertex attribute formats.

wgpu: Cache compiled naga-agal shader module

---

desktop/assets/texts/en-US/main_menu.ftl
desktop/assets/texts/en-US/open_dialog.ftl
desktop/src/app.rs
desktop/src/cli.rs
desktop/src/gui.rs
desktop/src/gui/controller.rs
desktop/src/gui/open_dialog.rs
desktop/src/player.rs
desktop/src/time_demo.rs
desktop/src/util.rs

- Remember options across movie loads;
- using `Open`  will replace any options by the default options provided on the command-line;
- adds `Ctrl-Shift-O` as a shortcut;
- adds a `Clear all` button to the movie parameters section;
- The `Browse` button automatically opens in the current file's directory.
Also, adds a `File > Reload` menu command to quickly reload the current movie.

desktop: `Open Advanced` improvements

---

core/src/avm1/activation.rs
core/src/avm1/globals/movie_clip.rs
core/src/avm1/globals/movie_clip_loader.rs
core/src/avm2/globals/flash/display/loader.rs
core/src/avm2/object/loaderinfo_object.rs
core/src/loader.rs

`AVM2Data` was always provided with
`MovieLoaderEventHandler::Avm2LoaderInfo`, so we can unify them into a single enum.

core: Unify loader event handler and AVM2 data into MovieLoaderVMData

---

core/src/avm2/globals/flash/net.as

Along with #11465, this fixe s #10179.
Also progresses #9276, which needs `TextField.insertXMLText` next.

avm2: flash.net.getClassByAlias/registerClassAlias stub improvements

---

desktop/src/gui/open_dialog.rs

desktop: properly populate base and proxy URL fields from option struct

---

core/src/string/interner.rs

- we can now get a `&RawTable` from a `&HashSet`, meaning we can store a `HashSet` directly in the interner;
- `RawTable::iter_hash` now allows the removal of already-yielded elements during iteration, which simplifies `WeakSet::entry`

core: slightly simplify string interner by using new hashbrown APIs

---

web/packages/core/src/load-ruffle.ts

Re #11504, this may fix the issue, but I'm not certain (can't find a way to test the fix there).

web: Stop error if Fetch response lacks headers

---

core/src/avm2/globals/array.rs

Just a tiny fixup for something I noticed while looking into #11510

avm2: Throw AVM error in Array constructor

---

core/src/backend/ui.rs
desktop/src/backends/ui.rs
desktop/src/gui/controller.rs

Fixes #11255
Now the flash-set cursor is used when you're not interacting with the UI, and a UI-based cursor is used when you are.

desktop: Fix interaction between egui and ruffle cursors

---

core/src/display_object/stage.rs
core/src/lib.rs
core/src/player.rs
desktop/assets/texts/en-US/settings.ftl
desktop/src/cli.rs
desktop/src/gui/open_dialog.rs
desktop/src/player.rs
web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/packages/demo/www/index.js
web/packages/extension/src/player.ts
web/src/lib.rs

This is basically the same as #9406, except for `salign` instead of `scale`. It can be annoying when games position themselves in a corner of the screen - this allows users to force them to be centered (or move them to any corner, if for some reason they want to).
**Before**
**After**

core: Add options to set and force the stage alignment

---

Cargo.lock
Cargo.toml
core/Cargo.toml
desktop/Cargo.toml
render/Cargo.toml
render/wgpu/Cargo.toml
tests/Cargo.toml
tests/tests/regression_tests.rs
web/Cargo.toml
web/common/Cargo.toml

Previously, we weren't displaying any Ruffle logs when running tests.

tests: Enable tracing_subscriber in tests

---

core/src/avm2.rs
core/src/avm2/error.rs
core/src/avm2/events.rs
core/src/avm2/globals/error.rs
core/src/avm2/object/error_object.rs
core/src/display_object/container.rs
core/src/display_object/movie_clip.rs
core/src/external.rs
core/src/timer.rs

This lets us print the full error message and stack stacke in contexts where an Activation is not available, including the `Debug` impl.
The 'name' and 'error' fields are accessed using hardcodd slot ids. This is pretty hacky, but will work until we have better handling of slot properties.

avm2: Implement ErrorObject.display without using Activation

---

Cargo.lock
desktop/Cargo.toml

This fixes `thread 'main' panicked at 'span! without a running Client'` when enabling the `tracy` feature.

chore: Bump `tracing-tracy` to version-match `profiling`

---

render/canvas/src/lib.rs
render/webgl/src/lib.rs

This stops us from holding on to way more memory than we need to, and a small refactor split off from my upcoming cacheAsBitmap work

Canvas & webgl bitmap data cleanup

---

Cargo.lock
render/wgpu/Cargo.toml

Supersedes #11571 (and also #11572).

chore: Bump ouroboros to 0.17.0.

---

desktop/src/executor.rs
desktop/src/player.rs

It should probably have been renamed as part of, or shortly after, f0445d94b.

cleanup: Rename GlutinAsyncExecutor -> WinitAsyncExecutor.

---

web/packages/core/src/i18n.ts

Some websites add enumerable properties to Array,prototype, which causes spurious errors to be logged when we iterate through the array returned by `bundle.addResource`. That's because `for..in` iterates through all enumerable properties of any object. It's better practice to use `for..of` loops instead, and iterating through Object.entries also makes the code a little cleaner.
This stops the error spam in the console on Kongregate and the site from #11589. It doesn't fix the main problem in #11589 or fix loading localizations on Kongregate though. Localizations are broken on Kongregate because they override some methods on Array.prototype with broken implementations, according to Dinnerbone.

web: Use for..of instead of for..in loops

---

core/src/avm1/globals/matrix.rs

The comment for this function says that it
> returns the identity matrix if any of the `a`, `b`, `c`, `d`, or `tx` properties do not exist
but that wasn't the case.
Fixes #3721 which calls `pz[n].beginBitmapFill(tmp2);` without specifying an optional matrix argument.

avm1: Correct `matrix::object_to_matrix_or_default`

---

core/src/avm2/value.rs

This mostly just helps calling String methods, which unavoidably box the String and later call coerce_to_string->coerce_to_primitive on it. Saves some dynamic lookup+call work, saw it measurably reduce overhead on some swfs.
(Long term we should have another way (coerce only when called via prototype method, not class method) - and ofc ideally, not have it be boxed at all.)

avm2: Optimize coerce_to_primitive for boxed primitives

---

core/src/avm2/globals/flash/sampler.as
core/src/avm2/globals/flash/sampler/DeleteObjectSample.as
core/src/avm2/globals/flash/sampler/NewObjectSample.as
core/src/avm2/globals/flash/sampler/Sample.as
core/src/avm2/globals/flash/sampler/StackFrame.as
core/src/avm2/globals/globals.as

Fixes #8831 (though it has performance issues)
Some of the `flash.sampler` functions seem like they would be relatively easy to implement in Ruffle- there are a two which report the number of times getters/setters have been invoked, and one which checks if the given property is a getter/setter.

avm2: flash.sampler stubs

---

web/packages/core/src/current-script.ts
web/packages/core/src/polyfills.ts
web/packages/core/src/public-api.ts
web/packages/core/src/public-path.ts
web/packages/core/src/ruffle-player.ts
web/packages/core/src/source-api.ts
web/packages/extension/src/player.ts

This fixes 2 related problems:
1. The Ruffle extension was obeying the `publicPath` config option, even though it only makes sense for selfhosted Ruffle.
2. Ruffle's `isExtension` variable was only being set for polyfilled Ruffle elements, not for elements created with the JS API.
Fixes #11603.
Fixes #8413.
Also fixes the Ruffle player failing to load when the extension is enabled on [this page](https://www.eftelingfanzine.com/efteling-simulaties/bobbaan/) from #3284. (It's the same issue as #8413, but more easily/reliably reproducible).

web: Fix Ruffle extension failing to load when publicPath config is set

---

web/packages/core/src/load-ruffle.ts

This can be considered to get Pale Moon closer to working with Ruffle, though it still fails to load because Pale Moon has incomplete WASM support.
It's arguable whether we should concern ourselves with doing this, but it's simple, so my feeling is that it's a good idea. It's impossible to predict whether Pale Moon will have sufficient WASM support to run Ruffle first or support for ReadableStream first, but my feeling is it would be bad if this became the final blocker for Ruffle there.

web: Don't auto-panic on browsers without ReadableStream

---

core/src/display_object.rs
core/src/display_object/movie_clip.rs

In https://github.com/ruffle-rs/ruffle/commit/fc00ae8eb6 , filters are applied in MovieClip.instantiate_child, which is called when creating an object. But the proper place for this is in TDisplayObject.apply_place_object, which is called both by instantiate_child _and_ when modifying an existing object with PlaceObject.
This change has no visible effect on master (since filters are still invisible). But when combined with https://github.com/ruffle-rs/ruffle/pull/11702 , which enables filter rendering, it fixes a bug where filters do not display unless they were set up at the same time as their object was created.
Note: I notice there are still [two TODOs](https://github.com/ruffle-rs/ruffle/blob/6d77ff1fc41aa34848188aa79ddb8c283671df4a/core/src/display_object/movie_clip.rs#L4343-L4400) …

core: Apply filters when modifying an object, not just when instantiating

---

core/src/display_object/avm1_button.rs

Fixes #11706
Wasn't able to make a test that actually reproduced this

core: Don't hold a borrow on Avm1Button whilst adding children

---

render/wgpu/shaders/filter/blur.wgsl
render/wgpu/shaders/filter/color_matrix.wgsl
render/wgpu/shaders/filter/common.wgsl
render/wgpu/src/descriptors.rs
render/wgpu/src/layouts.rs
render/wgpu/src/lib.rs
render/wgpu/src/pipelines.rs
render/wgpu/src/surface.rs

This should make filters faster and fix the panic for setting push constants that aren't there after a browser optimizes them out

wgpu: Removed most uniforms from filters, they're not used or needed

---

desktop/build.rs

Fix incorrect linker arguments on windows when using gnu linker(ld.exe)
when not using msvc linker, the original build script will cause an error when building the desktop package

desktop,chore: Fix incorrect linker arguments on windows when using gnu linker(ld.exe)

---

render/wgpu/src/context3d/mod.rs

We can already get the foramt from the wgpu::Texture

wgpu: Remove 'TextureWrapper.format' field

---

core/src/avm2/function.rs

While this condition is rare, it occurs in crossbridge SWF's. This will make stack traces like the one in #10851 a lot more helpful.
The stack trace from that issue would now look like this:
```
at flash.utils::ByteArray/flash::utils::ByteArray::length()
at global/F_avm2_casRamLength()
at global/F___sys_mmap()
at global/F_mmap()
at global/F_pages_map()
at global/F_base_pages_alloc()
at global/F_base_alloc()
at global/F_arenas_extend()
at global/F_malloc_init()
at global/F_malloc()
at global/F__Znwj()
at global/F__Z16CreateGameObjectv()
at global/F_main()
at global/F__start1()
at com.adobe.flascc::CModule$/callI()
at com.adobe.flascc::CModule$/start()
at com.adobe.flascc::CModule$/startAsync()
at com.adobe.flascc::Console/enterFrame()
```

avm2: Use `method_name` as last resort if available in stack trace

---

core/src/bitmap/operations.rs

In the special case where y_min==y_max==(height-1), we would create a bad 'encompassing' region - subtracing one from the max would make it smaller than the min, causing `PixelRegion::encompassing_pixels` to treat it as the minimum, and add one to `height - 1`
There's no work to do when x_min==x_max or y_min==y_max, so we can also skip the sync and GC write in this case.

core: Bail out of operations::color_transform if [xy]_min==[xy]_max

---

core/src/display_object/video.rs

Fixes #11822 and #11823.
In the FLV PR (#10756) I moved the `decoded_frame` parameter from `VideoData` to `VideoSource::Swf` since it's only ever used for SWF video streams. However, the host structure in this case will be shared across all instances of a given `Video`, which is... very bad. In the case of the two above-mentioned bugs, multiple instances of the same video stream were overwriting their last decoded frame numbers and losing track of video decoder state. Even if it hadn't caused a panic it would have broken video seeking badly.
So I just moved it back to `Video`.
I also considered putting `VideoSource` behind a `Gc` to prevent similar bugs from happening, but we actually *do* need to be able to mutate the source during preload. During my failed attempt to do that, I spotted …

Fix post-FLV-merge regressions

---

web/package-lock.json
web/package.json
web/packages/core/package.json
web/packages/demo/package.json
web/packages/extension/package.json
web/packages/selfhosted/package.json

Also `npm install` to make sure `package-lock.json` is clean.
No idea why neither of the version-nudging bots did any of this.
This supersedes https://github.com/ruffle-rs/ruffle/pull/11840.

chore: Run `npm update --save` in `web`

---

Cargo.lock
render/Cargo.toml
render/src/lib.rs
render/src/renderdoc.rs

This feature is disabled by default. When enabled, you can use `ruffle_render::renderdoc::begin_frame_capture` and `ruffle_render::renderdoc::end_frame_capture` to manually trigger a RenderDoc frame capture (if Ruffle wasn't launched by RenderDoc, this logs an error).
This is very useful when debugging Stage3D/PixelBender bugs, as you can produce a capture containing only the relevant graphics calls.

render: Add 'renderdoc' feature/module for manual frame capture

---

desktop/src/main.rs

This redirects output from the `log` crate to `tracing`

desktop: Use `SubscriberInitExt::init` to capture `log` output

---

core/src/avm2/activation.rs
core/src/avm2/class.rs
core/src/avm2/domain.rs
core/src/avm2/globals/vector.rs
core/src/avm2/multiname.rs
core/src/avm2/object.rs
core/src/avm2/object/class_object.rs
core/src/avm2/object/vector_object.rs

The only generic class is `Vector`, which only has a single parameter. However, we currently store a list of type parameters in several places, which requires redundant checks that the list only has one entry.
Instead, we now store an `Option` everwhere except for `swf::Multiname::TypeName` (since the actual SWF format supports multiple type parameters). We still perform the same check when loading bytecode (the swf Multiname should only have at most one type parameter), but the rest of the codebase can deal with an `Option` instead.

avm2: Store at most a single type parameter in names/clasess

---

core/src/display_object/avm1_button.rs
core/src/display_object/avm2_button.rs

Makes some of the Papa's games look better (see https://github.com/ruffle-rs/ruffle/issues/9201#issuecomment-1517500384).
This should also fix the glow filter not applying to the buttons in https://github.com/ruffle-rs/ruffle/pull/11878#issuecomment-1619919537.

core: Correctly apply blend modes and filters from button records

---

Cargo.lock
desktop/Cargo.toml
desktop/src/gui/controller.rs

This is a rebase of #11370 with a commit added to fix font selection on Windows.

desktop: load cjk fallback fonts using fontdb

---

core/src/avm2/globals/flash/display/movie_clip.rs

avm2: Use the current SWF version instead of root SWF version in MovieClip.gotoAndPlay

---

core/src/avm2/activation.rs
core/src/avm2/globals.rs
core/src/avm2/globals/flash/display/display_object.rs

Another followup for https://github.com/ruffle-rs/ruffle/pull/11494 .
Converts some more code - `astype`/`istype` opcodes and exception type check - to use the domain instead of scoped lookups. This way we can kill old `resolve_class/type`.
The one remaining case is `resolve_definition(sc_name)` in `globals.rs`, but I unfortunately this is currently needed as we need a `ClassObject` there.
BTW, I think we forgot to mention that the original PR should have sped up a bunch of lookups, like for parameter types. This one also does this for these new opcodes - I tested that an `astype "XML"` microbenchmark speeds up by almost 2x with this change.

avm2: Replace Activation.resolve_type by domain lookup

---

core/src/avm2/object/context3d_object.rs
core/src/avm2/object/program_3d_object.rs
render/src/backend.rs
render/wgpu/src/context3d/current_pipeline.rs
render/wgpu/src/context3d/mod.rs
render/wgpu/src/context3d/shader_pair.rs

The bind group layout only depends on the texture registers (and 2D/cubemap type) accessed by the fragment shader, not on the runtime texture bound with Context3D. This means that we can build and cache it when we compile the AGAL program to a Naga module.
Since the bind group layout is used for the overall pipeline, I've refactored the shader caching code into `ShaderPairAgal`, which holds both the vertex and fragment shader bytecode, and compiles both in the `compile` function.

wgpu: Cache Program3D bind group layout

---

desktop/src/gui/controller.rs

I don't know if anyone tested CJK fonts on Linux, but it wasn't working for me without this change. Now all the following are working:
- LANG=ca_ES.UTF-8 cargo run --release --package=ruffle_desktop
- **LANG=zh_CN.UTF-8 cargo run --release --package=ruffle_desktop**
- **LANG=zh_TW.UTF-8 cargo run --release --package=ruffle_desktop**
- LANG=cs_CZ.UTF-8 cargo run --release --package=ruffle_desktop
- LANG=nl_NL.UTF-8 cargo run --release --package=ruffle_desktop
- LANG=fr_FR.UTF-8 cargo run --release --package=ruffle_desktop
- LANG=de_DE.UTF-8 cargo run --release --package=ruffle_desktop
- LANG=hu_HU.UTF-8 cargo run --release --package=ruffle_desktop
- LANG=id_ID.UTF-8 cargo run --release --package=ruffle_desktop
- LANG=it_IT.UTF-8 cargo run --release --package=ruffle_desktop
- …

Add more specific CJK font families for Linux

---

core/src/display_object.rs
core/src/display_object/movie_clip.rs

This should make the stack size commit of https://github.com/ruffle-rs/ruffle/pull/11261 unnecessary.
@Aaron1011 can you try it out please? I'm confident it'll work on desktop, but slightly worried about wasm-opt messing things up.

core: Mark stack-heavy DO functions as noinline

---

desktop/assets/texts/en-US/open_dialog.ftl
desktop/assets/texts/en-US/settings.ftl
desktop/src/gui/open_dialog.rs

I guess we missed this one before. Addresses #11967.
I also made a minor change to make the wording for removing movie parameters more consistent.

desktop: Add Letterbox option to Open Advanced dialog

---

swf/src/avm1/read.rs

Fixes #2717, fixes #9785 (both issues described).
I'm not sure how to write a test for this, apart from creating a SWF and manually hex-editing Action data.

swf: avm1: Ignore bad ActionTry opcodes and bad ConstantPool strings

---

render/wgpu/src/layouts.rs

This is required for webgpu support. We must have broken this some time ago and didn't realize, because push constants are on most devices

wgpu: Fix crash when not using push constants

---

desktop/src/app.rs
desktop/src/gui/controller.rs
desktop/src/util.rs
exporter/src/main.rs
render/wgpu/src/backend.rs
render/wgpu/src/descriptors.rs
tests/tests/util/environment.rs

This lets us track gpu resource usage.

desktop: Track wgpu stats in Tracy

---

core/src/display_object.rs

core: Fix cacheAsBitmap size limit & remove print statement

---

core/src/backend/ui.rs
core/src/player.rs
desktop/assets/texts/en-US/settings.ftl
desktop/src/app.rs
desktop/src/backends/ui.rs
desktop/src/cli.rs
desktop/src/custom_event.rs
desktop/src/gui.rs
desktop/src/gui/controller.rs
desktop/src/gui/open_dialog.rs
desktop/src/player.rs
web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/packages/core/src/ruffle-player.ts
web/packages/core/texts/en-US/messages.ftl
web/packages/extension/assets/_locales/en/messages.json
web/packages/extension/assets/options.html
web/src/lib.rs
web/src/ui.rs

We support more of AVM2 today than we did AVM1 back when it was added. I think it's time.
I thought about keeping the option there "just in case", being unused... but realistically the effort to detect and add new localized warnings feels too high.

core: Remove unsupported content warning

---

render/src/utils.rs
swf/src/types/color.rs

Some SWFs report unreasonable bitmap dimensions, and trying to reserve enough capacity for them always fails. To avoid panics, skip those bitmaps.
Fixes #1191
Fixes #2759
Fixes #10701

render: Skip unreasonably large bitmaps

---

Cargo.lock
core/Cargo.toml
core/build_playerglobal/Cargo.toml
core/macros/Cargo.toml
desktop/Cargo.toml
exporter/Cargo.toml
render/Cargo.toml
render/naga-agal/Cargo.toml
render/wgpu/Cargo.toml
scanner/Cargo.toml
web/Cargo.toml

This is https://github.com/ruffle-rs/ruffle/pull/12275, except with the `wgpu` and `naga` bumps removed.
Those will not be this trivial to update according to @Aaron1011.

chore(deps): lock file maintenance rust dependencies

---

Cargo.lock

I need this to be able to run clippy again 😅 (https://github.com/rust-lang/libz-sys/issues/143)

chore: Update libz-sys to 1.1.12

---

core/src/avm2/e4x.rs

Attempts to fix #12064. The comment node kind isn't required to fix the issue, but I've implemented it as well, since it's basically the same as CData, according to avmplus:
https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/XMLObject.cpp#L1176-L1192

core: Implement ToXMLString for Attribute and Comment node kind

---

core/src/avm2/globals/number.rs
tests/tests/swfs/avm2/from_avmplus/e4x/Global/e13_1_2_1/test.toml

This avoids getting into an infinite loop for some of the avmplus tests.

avm2: Special case Number.toString for Infinity and NaN

---

core/src/avm2/globals.rs
core/src/avm2/globals/void.rs
core/src/avm2/value.rs

Still gotta add a test for this.
Note that this as-is lets you do much more than intended, like `new void()` or `var T = void`, which FP doesn't support. Can't really fix this without the class refactor :c  
I don't think this is a major issue, but if you think this is a major risk after all, then we should go with some more targeted hack in type-related opcodes.

avm2: Add void type

---

core/src/debug_ui/display_object/search.rs

We need to scale the mouse position that egui gives us by the scale factor, in order to get in the format expected by our inverse view matrix

core: Fix debug_ui mouse search on HiDPI display

---

core/src/debug_ui/display_object.rs
core/src/debug_ui/display_object/search.rs

This confused me terribly.
Before (single item, `instance2`, collapsed/expanded):
After (same item collapsed/expanded):

debug_ui: Indent non-expandable items object- and display trees

---

core/src/drawing.rs
render/src/shape_utils.rs

Not likely to have any huge impact, but it'll tighten the bounds of anything glyphs with curves as we generate them this way

render: Calculate correct bounds for shapes containing curves

---

wstr/src/tests.rs
wstr/src/utils.rs

`split_ascii_prefix_bytes(b"abc")` should return `("abc", b"")`, not `("", b"abc")`
This doesn't affect correctness, but should increase performance of ASCII `String` -> `WString` conversions.
Kudos to @Adrian17 for catching this!

wstr: return correct result for `split_ascii_prefix_bytes(<ascii str>)`

---

render/wgpu/src/backend.rs

This is needed for the Android app (shameless plug: https://github.com/torokati44/ruffle-android :wink:) to remain functional after switching away from the app and back (i.e. activity suspend-resume).
See: https://github.com/gfx-rs/wgpu/issues/2302

render/wgpu: Add WgpuRenderBackend<SwapChainTarget>::recreate_surface().

---

core/src/avm1/property.rs
core/src/avm1/scope.rs
core/src/avm2/class.rs
core/src/avm2/events.rs
core/src/avm2/multiname.rs
core/src/avm2/object/class_object.rs
core/src/avm2/object/soundchannel_object.rs
core/src/avm2/object/textformat_object.rs
core/src/avm2/regexp.rs
core/src/backend/audio.rs
core/src/config.rs
core/src/context_menu.rs
core/src/display_object.rs
core/src/display_object/avm1_button.rs
core/src/display_object/avm2_button.rs
core/src/display_object/edit_text.rs
core/src/display_object/graphic.rs
core/src/display_object/interactive.rs
core/src/display_object/movie_clip.rs
core/src/display_object/stage.rs
core/src/display_object/text.rs
core/src/display_object/video.rs
core/src/drawing.rs
core/src/font.rs
core/src/html/dimensions.rs
core/src/html/layout.rs
core/src/html/text_format.rs
core/src/loader.rs
core/src/streams.rs
core/src/vminterface.rs

IMO we should try to go this way whenever possible.
It's also friendlier to compile times c:

core: Remove lots of uses of derive(Collect)

---

web/docker/Dockerfile
web/package.json
web/packages/core/tools/build_wasm.js

- JRE is now headless (and no JDK at all)
- use a minimal profile in rustup (as in: no docs/clippy)
- no `RUN rustup update` (anyone knows why it was there? Surely rustup installs recent version by default?)
- run `cargo clean` after the built artifact is moved to `dist/`
Result:
- ~0.7GB smaller image before we start building Ruffle
- ~1.1GB of space regained between vanilla and non-vanilla wasm builds (plus another 1.1GB at the end, but that shouldn't matter)
The next big thing would have been removing `miniconda` and pulling recent `binaryen` another way, that's another almost 1GB saved.
Would still like @kmeisthax to review and make sure it still reproduces with it (whether before or after merge).

build: Reduce disk use of reproducible docker builds

---

exporter/src/main.rs

If you used exporter to export a frame and accidently gave a path that dis not exist it would say: Output directory is required when exporting multiple files. instead of giving the error that the path does not exist.
I found that confusing so fixed that in this little pr.

Exporter: Updated the logic that gives a error message

---

web/packages/core/src/polyfills.ts
web/packages/core/src/public-api.ts
web/packages/core/src/ruffle-player.ts
web/packages/core/src/version.ts
web/packages/core/test/version.ts
web/packages/core/tools/set_version.js
web/packages/extension/src/content.ts
web/packages/extension/src/player.ts
web/packages/extension/src/utils.ts

Well, as best as I can.
There's a few issues at play:
1. Things loaded from different sources are different JS types, so we always saw another version of ruffle as a "conflict" and didn't consider it at all. This means that whatever loaded last would take over config, but whatever loaded first would still polyfill because nothing told it to stop.
2. Extension set every single option explicitly, which meant that selfhosted stuff would get overwritten if loaded first.
3. Identical versions (we're still `0.1.0`) compared the same so it was pretty arbitrary which one would win - I made it include the build date as a tie breaker.

web: Fix extension vs selfhost loading conflicts

---

web/packages/core/src/source-api.ts
web/packages/core/tools/set_version.js

Should fix submission of extension to the stores

web: Don't store the full semver version as the version name, just construct it when needed

---

web/packages/extension/manifest.json5

Problems reported in #11906 and in a Chrome Web Store review

extension: Add exclusions for Tuxedo Computers and Taobao

---

tests/tests/swfs/visual/shumway_acid_tests/acid_image/test.toml

See https://github.com/ruffle-rs/ruffle/actions/runs/5799719364/job/15720327826, https://github.com/ruffle-rs/ruffle/actions/runs/5805718377/job/15737266364, and their successful second attempts.

tests: Exclude WARP from shumway_acid_tests/acid_image, it was flaky

---

core/src/display_object.rs
core/src/display_object/avm2_button.rs
render/src/backend.rs
render/src/filters.rs
render/wgpu/src/backend.rs
render/wgpu/src/filters.rs
render/wgpu/src/filters/bevel.rs
render/wgpu/src/filters/blur.rs
render/wgpu/src/filters/displacement_map.rs
render/wgpu/src/filters/drop_shadow.rs
render/wgpu/src/filters/glow.rs
swf/src/types/bevel_filter.rs
swf/src/types/blur_filter.rs
swf/src/types/drop_shadow_filter.rs
swf/src/types/glow_filter.rs
tests/tests/swfs/visual/cache_as_bitmap/contains_grown_filter/test.toml

This should fix any remaining filter-cutoff issue, such as the glow in #11729 (https://github.com/ruffle-rs/ruffle/issues/11729#issuecomment-1632913648).

core: Fix filters being cut off when nested inside another cacheAsBitmap

---

web/packages/core/src/plugin-polyfill.ts
web/packages/extension/src/plugin-polyfill.ts

This should fix the cases where older ruffle would just stop working when it detected a newer version of the extension.
Instead of failing to work, those older versions will likely try and polyfill/etc themselves as they are incapable of version negotiation. It's better than nothing I guess. I'd still recommend people update to a version that does have functional negotiation though.

web: Remove ruffle extension detection plugin

---

core/src/avm2/globals/boolean.rs
tests/tests/swfs/from_avmplus/ecma3/Boolean/e15_6_3_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/Boolean/e15_6_3_1_3/test.toml
tests/tests/swfs/from_avmplus/ecma3/Boolean/e15_6_4/test.toml
tests/tests/swfs/from_avmplus/ecma3/Boolean/e15_6_4__1/test.toml
tests/tests/swfs/from_avmplus/ecma3/FunctionObjects/ecall_1/test.toml

Makes tests `e15_6_3_1`, `e15_6_3_1_3`, `e15_6_4`, `e15_6_4__1` and `ecall_1` pass.

 avm2: Boolean.valueOf and Boolean.toString default to false 

---

.github/renovate.json5

This is supposed to fix the issue mentioned in https://github.com/ruffle-rs/ruffle/pull/12474#issuecomment-1660590171.
That is caused by the separate lockFileMaintenance PRs fast-forwarding the lockfiles in themselves, but not the version spec in package.json. So the lockfile will be rolled back locally. Let's try to make the lockfiles be bumped together with the version specs for both Rust and JS, with a different solution than https://github.com/ruffle-rs/ruffle/pull/9884.
The previous goal of grouping only patch updates together, and having minor and major updates be their own separate PRs per package (83f88a6f3e6757993d09b6bc97303739f86d4c30) also didn't work, as can be seen in https://github.com/ruffle-rs/ruffle/pull/12474.

renovate: Remove separate lockFileMaintenance schedule, set rangeStrategy to bump.

---

.github/renovate.json5

The bot disabled itself due to #12522:
> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.
> 
> Location: .github/renovate.json5
> Error type: The renovate configuration file contains some invalid settings
> Message: `packageRules[0]: packageRules cannot combine both matchUpdateTypes and rangeStrategy. Rule: {"matchCategories":["rust"],"matchUpdateTypes":["patch"],"groupName":"Rust dependency patches","rangeStrategy":"bump","extends":["schedule:weekly"]}, packageRules[1]: packageRules cannot combine both matchUpdateTypes and rangeStrategy. Rule: {"matchCategories":["rust"],"groupName":"Rust dependencies","matchUpdateTypes":["major","minor"],"rangeStrategy":"bump","extends":["schedule:weekly" …

renovate: Merge patch and major-minor Rust update rules

---

core/src/avm2/globals/string.rs
tests/tests/swfs/from_avmplus/ecma3/GlobalObject/e15_1_2_5_3/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_3_2_3/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_11_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_12_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_2_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_2_rt/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_5_4/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_6_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/e15_5_4_8_2/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/toLocaleLowerCase/test.toml
tests/tests/swfs/from_avmplus/ecma3/String/toLocaleUpperCase5/test.toml
tests/tests/swfs/from_avmplus/ecma3/TypeConversion/e9_7/test.toml

Makes tests `e15_5_4`, `e15_5_4_2_1`, `e15_5_4_2_rt`, `e15_1_2_5_3`, `e15_ 5_3_2_3`, `e15_5_4_11_1`, `e15_ 5_4_12_1`, `e15_5_4_5_4`, `toLocaleLowerCase`, `toLocaleUpperCase5`, `e9_7`,  `e15_5_4_8_2` and `e15_5_4_6_1` pass.

avm2: String fixes

---

.github/renovate.json5

I _hope_ this will do what I want it to do...

renovate: Separate wgpu-related Rust dependencies into their own group

---

web/packages/extension/manifest_firefox.json5
web/packages/extension/manifest_other.json5

Searching for "Flash" doesn't really bring Ruffle up, especially not with a dozen "Flash Player" extensions that is ironically usually just an outdated ruffle + analytics/ads.
This helps alienate that a lot. It also helps teach people what Ruffle is, just seeing "Ruffle" doesn't explain to a random person what it is :D

web: Rename extension to 'Ruffle - Flash Emulator'

---

core/src/avm2/globals/flash/display/movie_clip.rs

This is needed because we don't have a way of checking the SWF version of the currently executing bytecode, only of the current clip, which can be different. AVM2's version-dependent behavior should depend on the SWF containing the current DoAbc(2) tag. This distinction matters for Nightflies since it executes code on an SWFv11 clip from SWFv10.
Fixes #11987.

avm2: More lenient SWF version check for invalid frame label behavior

---

.github/renovate.json5

Two commits are just keeping up with the times.
One was a base config rename: https://github.com/renovatebot/renovate/commit/f9e3e80e0c9c6a972d847f8740de5016a2bf698a
The other was recommended by the validator: https://docs.renovatebot.com/config-validation/
And the third one is to resolve `mocket`, `input-format` and `socket-format` (among others) not being updated.
See: https://github.com/renovatebot/renovate/discussions/23952

Renovate config migration, un-ignore `tests`

---

tests/tests/swfs/visual/shumway_acid_tests/acid_gradient_2/test.toml

This was the culprit for most of our recent Windows CI failures.

tests: Exclude WARP from running the acid_gradient_2 visual test (ported from Shumway)

---

web/packages/extension/src/content.ts

The content script doesn't have access to the `scripting` API, but it does have the ability to get the extension's manifest: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis

extension: Fix check for scripting permission

---

core/src/avm1/globals/movie_clip.rs
core/src/backend/audio.rs
core/src/backend/audio/decoders.rs
core/src/backend/audio/mixer.rs
core/src/buffer.rs
core/src/display_object/movie_clip.rs
core/src/lib.rs
core/src/loader.rs
core/src/streams.rs
desktop/src/backends/audio.rs
tests/tests/util/runner.rs
web/src/audio.rs

This PR adds a new set of types for managing data buffers in use by Ruffle's various backends:
* `Buffer` stores the whole of a given data stream, whether that be a SWF file, FLV file, MP3 file, and so on. Data ownership is shared. Mutability is limited to appending data to the end of the buffer.
* A `Slice` can be constructed from a range on the `Buffer`. Slices are guaranteed to always refer to the same data.
* The `Slice` can be indexed as a `[u8]` by turning it into a `SliceRef<'_>`. This is equivalent to holding a `&[u8]`.
* Data can be read from the `Slice` by turning it into a `SliceCursor` which implements `Read`.
* Multiple `Slice`s can be appended to a single `Substream`, which represents a single embedded data stream in a `Buffer`. The slice list in the `Substream` is also …

FLV audio +Buffer refactor

---

web/packages/extension/src/background.ts

It turns out that extension service workers are inactive when Chrome starts and only wake up when they receive an event.
This fixes the plugin polyfill not running on sites after Chrome is restarted until the service worker is woken up by an event. http://www.g2conline.org/ is a good site to test this on.

extension: Persist content script registration across sessions

---

web/packages/core/src/ruffle-player.ts

Fixes #9615. Thanks to @Toad06 for suggesting the fix.
This problem was getting annoying when testing the web demo locally.

web: Don't try to enter fullscreen if already in fullscreen & vice versa

---

Cargo.lock
video/software/Cargo.toml

To get the minor (and inconsequential, really) changes from https://github.com/ruffle-rs/nihav-vp6/pull/1.
Just basic housekeeping.

video/vp6: Bump nihav-vp6 crate git refs

---

Cargo.lock
Cargo.toml
core/src/avm1/globals/date.rs
core/src/avm1/globals/shared_object.rs
core/src/avm1/globals/text_field.rs
core/src/avm1/globals/text_format.rs
core/src/avm1/object.rs
core/src/avm1/object_reference.rs
core/src/avm2/activation.rs
core/src/avm2/globals/date.rs
core/src/avm2/globals/flash/text/text_format.rs
core/src/avm2/method.rs
core/src/avm2/object.rs
core/src/avm2/object/date_object.rs
core/src/avm2/object/textformat_object.rs
core/src/avm2/scope.rs
core/src/focus_tracker.rs
core/src/player.rs
ruffle_gc_arena/Cargo.toml

Some progress towards fully getting rid of the `GcCell` shim (and the `ruffle_gc_arena` façade crate).
Every commit is independent and could be split into its own separate PR, but the changes are straightforward enough that I don't think this is necessary.

core: Refactor away some `GcCell`s

---

web/packages/core/src/ruffle-player.ts

- Fix improper spacing around the "Open in a new tab" button due to wrongly structured HTML:
- Don't show a CORS error on the internal player page, which is not subject to CORS restrictions.

extension: Fix some minor issues

---

core/src/avm2/globals/flash/text/text_field.rs
core/src/avm2/parameters.rs

I suspect this is an issue throughout the codebase, but I'm fixing it where I found it.

avm2: Throw TypeError for null argument in TextField string property setters

---

.github/workflows/test_rust.yml
.github/workflows/test_web.yml

- The `|` glob operator does not actually work. As a workaround, switch to a fork of the paths-filter action that supports multiple exclude rules. (`dorny/paths-filter` does allow you to specify multiple exclude rules, but it matches *any* of them instead of *all* of them, which is useless for us.)
- Our exclude rule for markdown files was wrong - it only matched files in the top-level directory. Correct the rule to also match markdown files in subdirectories.
For more context, see:
- https://github.com/dorny/paths-filter/issues/135
- #5103
- #5212
- #5332

ci: Fix paths filter

---

Cargo.lock
render/Cargo.toml
video/software/Cargo.toml

No functional changes intended, just keeping up with the times (https://github.com/ruffle-rs/h263-rs/pull/51).

video,chore: Bump h263-rs git refs (and update Cargo.lock fully while there)

---

tests/tests/swfs/visual/shumway_acid_tests/acid_gradient_1/test.toml

Keeping on fighting the little fires around Windows CI.

tests: Exclude WARP from running the acid_gradient_1 visual test ported from Shumway

---

render/wgpu/src/context3d/mod.rs

There's nothing to do in this case, and we want to avoid trying to construct a `NonZeroU64` for the size.
Progresses https://github.com/ruffle-rs/ruffle/issues/12364

wgpu: Bail out early when trying to set empty program constants

---

core/src/display_object/movie_clip.rs

This is almost guaranteed to cause problems, so it shouldn't be a warning.

avm2: Log an error when a symbol class lookup fails

---

render/wgpu/src/context3d/mod.rs

This is not supported under webgl, and results in a panic "Tex storage 2D multisample is not supported" if we try to do it.

wgpu: Disable Context3D.setRenderToTexture MSAA on web

---

tests/tests/swfs/visual/shumway_acid_tests/acid_gradient_1/test.toml
tests/tests/swfs/visual/shumway_acid_tests/acid_gradient_2/test.toml
tests/tests/swfs/visual/shumway_acid_tests/acid_image/test.toml
tests/tests/swfs/visual/shumway_acid_tests/acid_large/test.toml

The little fires around flaky Windows CI might have made a :clown_face: of us, never being where we thought they were...
This reverts #12661, #12853, and #12970.
_Also, test systems that don't flush the test case name to stdout before doing anything with it are hella mid. /s_

tests: Exclude WARP from running acid_large, and allow acid_image and acid_gradient_* again

---

Cargo.lock
render/naga-pixelbender/Cargo.toml
render/naga-pixelbender/src/lib.rs
render/src/pixel_bender.rs

Some experimentation with Pixel Bender Studio shows that Opcode::Loop has a 23-byte payload. I haven't tried to figure out how to interpet the payload yet, but we can now skip over the opcode instead of bailing out entirely.

naga-pixelbender: Stub out Opcode::Loop

---

core/src/backend/audio/mixer.rs
core/src/player.rs
desktop/assets/texts/de-DE/main_menu.ftl
desktop/assets/texts/de-DE/volume_dialog.ftl
desktop/assets/texts/en-US/main_menu.ftl
desktop/assets/texts/en-US/volume_dialog.ftl
desktop/src/gui.rs
desktop/src/gui/controller.rs
desktop/src/player.rs
web/packages/core/src/ruffle-player.ts
web/packages/core/src/shadow-template.ts
web/packages/core/texts/de-DE/context_menu.ftl
web/packages/core/texts/de-DE/volume-controls.ftl
web/packages/core/texts/en-US/context_menu.ftl
web/packages/core/texts/en-US/volume-controls.ftl

This pull request adds volume controls to both desktop and web.
On desktop, they can be accessed through the menu bar, on web, through the right-click menu.
The volume controls contain a mute button and a slider from 0 to 100 in each.
The volume given to the player is adapted for logarithmic hearing.
On desktop, the volume controls are available, even if no SWF file is currently being played. When starting to play an SWF file, the current GUI volume controls are used.
Since the GUI volume controls use the PlayerOptions volume value as the default, this PR also fixes the issue that the PlayerOptions volume has previously not been adapted for logarithmic hearing.
The volume controls (and the options to open them) are multilingual. In this pull request, English and German translations have …

core: Add volume controls to desktop and web

---

.github/workflows/test_rust.yml
.github/workflows/test_web.yml

Should hopefully save us a couple minutes.
But yeah, we really should run less redundant tests on multiple platforms :/

CI: Lighter ci on windows and mac

---

Cargo.lock
Cargo.toml
core/Cargo.toml
desktop/Cargo.toml
render/naga-agal/src/builder.rs
render/naga-agal/tests/snapshots/wgsl__complex_fractal-2.snap
render/naga-agal/tests/snapshots/wgsl__complex_fractal.snap
render/naga-agal/tests/snapshots/wgsl__complex_raytrace-2.snap
render/naga-agal/tests/snapshots/wgsl__complex_raytrace.snap
render/naga-agal/tests/snapshots/wgsl__misc_opcodes-2.snap
render/naga-agal/tests/snapshots/wgsl__misc_opcodes.snap
render/naga-agal/tests/snapshots/wgsl__relative_load.snap
render/naga-agal/tests/snapshots/wgsl__shaders-2.snap
render/naga-agal/tests/snapshots/wgsl__shaders-3.snap
render/naga-agal/tests/snapshots/wgsl__shaders.snap
render/naga-pixelbender/src/lib.rs

This requires forked versions of several dependencies, and egui doesn't yet compile on wasm due to the `!Send/!Sync` wgpu changes.

render: Bump wgpu to 0.17 and naga to 0.13

---

core/src/avm1/globals/xml_socket.rs
core/src/font.rs

core: Convert two unused doc comments to normal comments

---

core/src/avm2/activation.rs
core/src/avm2/object.rs
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversions1_23/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsFalse/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsNaN/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsNeg1_23/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsNull/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsString/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsTrue/test.toml
tests/tests/swfs/from_avmplus/as3/Types/Conversions/ImplicitConversionsUndefined/test.toml

This was causing a bunch of implicit conversion test failures.
This technically makes test `from_avmplus/as3/Types/Int/wraparound` pass, but only in release mode due to debug mode integer overflow checks. (Which could be fixed with a simple `wrapping_add` function call).

avm2: Coerce value in set slot opcode

---

web/packages/core/src/ruffle-player.ts

There are still unsupported properties listed on https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement and https://developer.mozilla.org/en-US/docs/Web/API/HTMLEmbedElement but these are the most common ones.

web: Add width, height, and type to RufflePlayer (fix #13176)

---

core/src/avm2/globals/XML.as
core/src/avm2/globals/xml.rs

Improves #10510 (playable but slow). We still don't support [[InScopeNamespaces]] and actual non-empty prefixes.

avm2: Support node namespace in XML.namespace

---

core/src/avm1/globals/bitmap_data.rs
core/src/avm2/globals/flash/display/bitmap_data.rs
core/src/bitmap/bitmap_data.rs
core/src/bitmap/operations.rs

This caused the clone to be linked to the original, instead of being a completely independent BitmapData object.
Fixes https://github.com/ruffle-rs/ruffle/issues/13360

Fix BitmapData.clone accidentally re-using GPU texture

---

core/src/avm2/globals/flash/display3D/textures/Texture.as
core/src/avm2/globals/flash/display3D/textures/texture.rs

The Starling Benchmark was waiting for an event that never came.

avm2: Correctly fire `textureReady` event for async Texture uploads

---

Cargo.lock
Cargo.toml
render/wgpu/src/backend.rs

Since wgpu hasn't yet released a version with this feature, I manually backported it to the 0.17 branch.
This doesn't work on Windows (HLSL), but works on all other platforms.

render: Disable wgpu unused shader output check when possible

---

render/naga-agal/src/builder.rs

MathFunction::Inverse doesn't work on vectors.

naga-agal: Fix Opcode::Rcp implementation

---

render/src/atf.rs

We should be reading a big-endian U24.

render: Fix incorrectly reading U24 in ATF parsing

---

Cargo.lock
desktop/Cargo.toml
desktop/src/backends/navigator.rs

Both of these are handled automatically by the browser in the web backend. This makes the desktop client store cookies between requests (though they are discarded when the desktop player is closed), and set the "Content-Type" header based on the mime-type supplied in the URLRequest.

desktop: Handle cookies and Content-Type for HTTP requests

---

web/packages/core/src/ruffle-player.ts
web/packages/selfhosted/test/polyfill/percent-height-when-zero/expected.html
web/packages/selfhosted/test/polyfill/percent-height-when-zero/index.html
web/packages/selfhosted/test/polyfill/percent-height-when-zero/test.js

See https://bugzilla.mozilla.org/show_bug.cgi?id=810082#c65, the test file, and https://github.com/ruffle-rs/ruffle/pull/13030#issuecomment-1716314418. Supersedes #13030.

web: As appropriate use embed height mentioned in Mozilla bug 810082 c65

---

.github/workflows/release_nightly.yml
.github/workflows/test_rust.yml
desktop/Cargo.toml
tests/Cargo.toml
tests/README.md
tests/tests/swfs/avm2/stage3d_texture_bytearray/test.toml
tests/tests/util/options.rs

Still needs to be made optional for web.

make jpegxr more optional

---

Cargo.lock
core/Cargo.toml
core/build_playerglobal/Cargo.toml
desktop/Cargo.toml
exporter/Cargo.toml
render/Cargo.toml
render/naga-agal/Cargo.toml
render/wgpu/Cargo.toml
scanner/Cargo.toml
tests/Cargo.toml
tests/mocket/Cargo.toml

This is the same as https://github.com/ruffle-rs/ruffle/pull/13397, sans the `raw-window-handle` `0.5` -> `0.6` bump, which broke things.
Plus I threw in a `cargo update` for good measure.

chore: Update rust dependencies

---

core/src/avm2/globals/flash/geom/Matrix3D.as

Unfortunately, the OpenFL implementation has a TODO noting that their implementation doesn't match Flash, so getting this to work will require figuring out
how Flash does things.

avm2: Stub Matrix3D.pointAt

---

render/wgpu/src/context3d/current_pipeline.rs
render/wgpu/src/context3d/mod.rs

This fixes a panic when trying to render a texture with a type other than `TextureFormat::Rgba8Unorm`

wgpu: Correctly set format when rendering to Stage3D texture

---

render/naga-agal/src/builder.rs
render/naga-agal/src/types.rs

We had already stubbed these when set from ActionScript, but were were panicking when they were selected directly in the AGAL bytecode.

naga-agal: Stub anisotropic filters in opcodes

---

core/src/avm2/e4x.rs
core/src/avm2/globals/xml.rs
tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_29/v9/test.toml

This affects appendChild, prependChild, insertChildBefore, insertChildAfter.

avm2: Implement some obscure SWFv9 XML behavior

---

core/src/avm2/globals/flash/net/SharedObject.as

Fixes save points not working on #13426. The whole file is marked as changed because I formatted it according to the majority of the AS files (`public native` instead of `native public`, 4 spaces instead of 3 spaces, etc)

avm2: Implement SharedObject.setProperty

---

core/src/avm2/globals/flash/system/Worker.as

I noticed a subtle inconsistency in stack traces across Ruffle and FP.
FP:
```
ArgumentError: Error #2012: Worker$ class cannot be instantiated.
at Tests()
```
Ruffle:
```
ArgumentError: Error #2012: Worker$ class cannot be instantiated.
at flash.system::Worker()
at Tests()
```
<s>I believe FP has some sort of metadata on the class which throws the error where the class gets constructed, instead of actually running the constructor code. Note that this _does not_ apply to `TextJustifier` and `ContentElement`, which throw `Error #2012` when, for example, `new ContentElement(...)` is constructed instead of constructing a class that extends `ContentElement`.</s>
Nevermind, Adrian stated on Discord that the error logic should be in the instance allocator instead of running in the instance …

avm2: Throw ArgumentError when trying to construct `new Worker()`

---

Cargo.lock
core/Cargo.toml
core/build_playerglobal/Cargo.toml
core/macros/Cargo.toml
render/Cargo.toml
render/naga-agal/Cargo.toml
render/wgpu/Cargo.toml
swf/Cargo.toml
tests/Cargo.toml

The usual story, this fixes #13472 by updating `raw-window-handle` to `0.5.2` only, instead of to `0.6`.
Plus the essential `cargo update`.

fix(deps): update rust dependencies

---

.github/renovate.json5

So I can finally stop being the best bot:tm: (https://github.com/ruffle-rs/ruffle/pull/13487#issuecomment-1753976182).

renovate: Include winit, egui-winit, and raw-window-handle in the wgpu dep group

---

Cargo.lock
web/Cargo.toml
web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/src/lib.rs
web/src/navigator.rs

As WebSocket is not a normal TCP socket, it requires extra software like [`websockify`](https://github.com/novnc/websockify) on the server.
Unresolved questions:

web: Support for Sockets with WebSocket

---

.github/workflows/test_rust.yml

Since it's flaky, until we have a better way to handle this

ci: Don't run image tests on macOS

---

core/Cargo.toml
core/src/backend/ui.rs
core/src/font.rs
core/src/html/layout.rs
core/src/lib.rs
core/src/library.rs
core/src/player.rs
desktop/Cargo.toml
desktop/src/backends/ui.rs
exporter/Cargo.toml
tests/Cargo.toml
web/Cargo.toml
web/src/ui.rs

Peeled this out of my big font WIP.
The notable changes here are:
- There's an enum representing the "default" device fonts in Flash, ie `_sans` is `DefaultFont::Sans`.
- Each default font has a list of implementation font names, which currently is just `["Noto Sans"]` for each.
- Whenever a font is requested which doesn't already exist, it's treated as a device font and the UI backend is requested to load it
- The UI backend has a callback to register new fonts when prompted, and Player also has a method to register new fonts
I did a lot of back and forth on the designs of things before settling on this, and I fell down so many different rabbit holes. I'm brain dumping a bit below so that at least relevant research notes can be preserved before I inevitably try to forget the word "Font" …

core: Font refactoring to allow backends to provide device fonts

---

Cargo.lock
Cargo.toml

Now that https://github.com/gfx-rs/wgpu/pull/4222 is merged (but no v0.17.3 yet, and perhaps there never will be), we don't need to rely on our fork.
There is no compelling technical reason for this, other than it "looks more official".
Also I threw in a `cargo update`, because why not - I know RenovateBot will be triggered in a few hours, but it's not that good with managing `Cargo.lock`.

Switch back to the main wgpu repo

---

Cargo.lock
core/Cargo.toml

The previously referenced commit was originally part of https://github.com/RustAudio/dasp/pull/137.
The nightly compilation error it is supposed to fix (https://github.com/RustAudio/dasp/issues/136), isn't reproducible now, and it already wasn't in 2021: https://github.com/RustAudio/dasp/pull/155
This trims our dependency tree a little bit, since `dasp` `v0.11.0` is also an indirect dependency, as pointed out by #13576.

core: Switch dasp from a git revision to v0.11.0

---

core/src/avm2/globals/xml.rs
core/src/avm2/globals/xml_list.rs
tests/tests/swfs/from_avmplus/e4x/XML/e13_4_1/test.toml

Previously the call handlers would panic when given zero arguments.

avm2: Fix XML/XMLList call handlers

---

web/packages/core/src/index.ts
web/packages/core/src/load-ruffle.ts
web/packages/core/src/public-path.ts
web/packages/core/src/ruffle-player.ts

Originally meant to change how config was passed over to rust but rabbit holes in rabbit holes 😅

web: Remove a whole bunch of internal stuff from public API + documentation, and simplify loading a bit

---

core/src/avm2/activation.rs

Unlike strict_equals they were comparing with just `==`, which is not entirely correct, since objects like XmlObjects need special cases.
Found this while debugging test `e13_5_4_16`.

avm2: Fix ifstricteq and ifstrictne comparisons

---

.github/workflows/test_rust.yml
deny.toml

I'd like to get verification that the allowed/denied licenses are actually correct.
Also I haven't dared to deny duplicate crates, as there are a lot of them.

ci: Set up cargo-deny

---

.github/workflows/release_nightly.yml

Secrets are already configured.
In theory this should just skip every release whenever we're already in review.
In practice... we need to try and see.

ci: Release nightlies automatically to Edge

---

core/src/avm2/globals/flash/display3D/context_3d.rs

The name uses camel case, not snake case.

avm2: Fix setting frontAndBack culling

---

web/docker/Dockerfile
web/packages/extension/webpack.config.js

This should unblock the automatic Firefox add-on updates. Also remove an intentional 60 second delay from their build attempts.
Summary of changes:
- Add clang to the dependencies
- Migrate Node.js installation to their new recommended method
- Add some comments for each logical step
- Remove a redundant comment
- Remove some unnecessary semicolons
As for why the Node.js installation method was changed, see: https://github.com/nodesource/distributions#new-update-%EF%B8%8F

Update the Dockerfile for building the browser extensions

---

web/packages/extension/webpack.config.js

This is a fixup for https://github.com/ruffle-rs/ruffle/pull/13733.
I always confuse these things, and notice these minor mistakes an hour after merging. _Gosh hecking darn it!_

nit: Fix tool name in error message of extension build

---

web/packages/core/src/ruffle-player.ts

Apparently only Elements are trusted targets for the click event: https://w3c.github.io/uievents/#event-types-list. While https://w3c.github.io/pointerevents/ doesn't specify the trusted targets for pointer events, I assume they correspond to their mouse event counterparts.
See also https://forum.palemoon.org/viewtopic.php?f=70&t=30469&p=244953#p244955

web: Switch click and pointer events to act on element and not window

---

core/src/avm2/activation.rs
core/src/avm2/globals/xml.rs
core/src/avm2/globals/xml_list.rs
core/src/avm2/object/xml_list_object.rs
core/src/avm2/object/xml_object.rs
tests/tests/swfs/from_avmplus/e4x/XMLList/e13_5_4_4/test.toml

This behavior is required by #13677.
This is not mentioned in E4X specification and seems to be an `avmplus` quirk.
Unfortunately, this requires looking through all uses of XmlListObject::new, which use a Vec to set the children and make them use [[Append]] where mentioned in E4X specification.

avm2: Add target_dirty flag and use it to reevaluate target object

---

web/Cargo.toml

If we disable the default features on one line, why re-enable it manually on the next line...
And the default feature list of core is empty anyway, so it makes no difference anyway.

web: Clean up nonsensical feature setup of the ruffle_core dependency

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
web/packages/core/tools/build_wasm.js

We should do it this way according to @Dinnerbone.

chore: Add `--locked` to all `cargo build` invocations

---

core/src/avm2/activation.rs

I'd like to get this merged quickly so correct behavior can be implemented in #13756. If that PR adds a test that checks if `appendChild`/`prependChild`/etc do in fact use the current movie and not the root movie, there shouldn't be any need to add a test to this PR.
This should fix a case where `MC.gotoAndPlay/Stop` is used in a script initializer- before this PR, that would panic.

avm2: Correctly set `caller_movie` in `Activation::from_script`

---

web/packages/core/src/config.ts
web/packages/core/src/load-options.ts
web/packages/core/src/ruffle-player.ts
web/src/lib.rs
web/src/ui.rs

Each URL provided to this config option will *try* to eagerly load as a font source.
If the URL cannot load, it will be ignored (but a warning will print).
If the URL cannot parse into a valid font, it will be ignored (but a warning will print).
Right now it only supports fonts embeded inside SWFs. Any number of fonts can be inside a single SWF, but they need to be embedded with DefineFont2 and you need to make sure it's actually inside the swf (not stripped out by not being used).
A future PR will enable TTF/OTF support.
```js
window.RufflePlayer.config = {
fontSources: ["my-big-fonts.swf"]
}
```
There are 3 "default" device fonts in Flash. `_sans`, `_serif`, `_typewriter`. In Ruffle they are our Noto Sans fallback unless configured otherwise.
To change that, set:
```js …
```

web: Add defaultFonts and fontSources config options

---

core/src/avm2/object/xml_list_object.rs
tests/tests/swfs/from_avmplus/e4x/XML/e13_4_4_27/test.toml

This should fix #13800 and #13803. Thanks to `XML.appendChild` now using the `set_property_local` path, we get test coverage for free. :tada:

avm2: Allow assigning XML objects without a name (eg. text)

---

core/src/avm2/amf.rs
tests/tests/swfs/avm2/socket_read_write_object/test.toml

This fixes #12383
We should probably include it when doing not-objects later, maybe? But this spot is specifically `new Object()` which should have no type info included.

avm2: Don't add ClassDefinition to AMF0 objects

---

.github/workflows/test_extension_dockerfile.yml

This should check weekly that https://github.com/ruffle-rs/ruffle/pull/13733 didn't regress, and the Firefox extension is buildable by the Dockerfile.
The question is, who is going to notice if this fails, and in what way?
Also, should we try passing in the environment variables containing the relevant repo secrets, so the signing step is also checked?
See for an example invocation: https://github.com/torokati44/ruffle/actions/runs/6661108191/job/18103430036

ci: Test that the Dockerfile in web is able to build the browser extensions

---

core/src/avm2/globals/flash/display/BitmapData.as

As proposed by @Lord-McSweeney and ACKed by @Dinnerbone on Discord.

avm2: Remove default width and height values from BitmapData ctor

---

web/packages/core/src/config.ts
web/packages/core/src/ruffle-embed.ts
web/packages/core/src/ruffle-object.ts
web/packages/core/src/ruffle-player.ts
web/packages/demo/www/index.js
web/packages/extension/src/player.ts

The Ruffle configuration options are currently not working properly for polyfilled elements. This pull request fixes that.
A polyfilled element can have specific configuration options which overwrite the more general Ruffle configuration settings (e.g. the general Ruffle config).
There are several places (`RuffleEmbed::connectedCallback`, `RuffleEmbed::attributeChangedCallback` and `RuffleObject::connectedCallback`) which handle the config options given to a polyfilled element and load an SWF file each.
A new `getPolyfillOptions` function has been created and returns a `URLLoadOptions` object, containing only the options that have been set for the respective element. It is now used in all of these places, reducing duplicated code between these methods.
This fixes the following bugs:
- …

web: Fix Ruffle configuration not working properly for Polyfill elements and in the extension player

---

core/src/avm2/object.rs

This is a better default than using the lowest possible version, as it allows things like AMF deserialization to see all properties on the target object.
This only affects explicit Ruffle-side property setting - interpreted code will continue to use the namespace version determined by the SWF version.

Use VM_INTERNAL api version in helper methods

---

Cargo.lock
core/Cargo.toml

Update to https://github.com/ruffle-rs/rust-flash-lso/commit/f9526ea0e7e22cf5704972aa43c5b0f9e8896773

chore: Update flash-lso

---

render/src/tessellator.rs

Fixes #13519 and fixes #13172- I'm not sure if this is the right way to do it, though.

render: Reset `mask_index_count` in `ShapeTessellator::flush_draw`

---

core/src/avm1/globals/button.rs
core/src/avm1/globals/movie_clip.rs
core/src/avm2/globals/flash/display/DisplayObject.as
core/src/avm2/globals/flash/display/display_object.rs
core/src/display_object.rs
core/src/display_object/movie_clip.rs

This is a rebased version of the core, avm1, and avm2 parts of #10611, minus rendering.
~~This is a rebased version of #10611. Only minor changes done, like a typo fix, removing some back-and-forth changes, and turning the added visual test into an actually runnable test.~~
~~I'm not sure if `render_with_scaling_grid` is still needed with our current (caching, blending, filtering, masking, scrolling, etc.) renderer setup, or if only some part of it should be thrown out, or if it's even called from the right place.~~
~~Fixes #3302.~~
~~Improves, but does not fix, #13688.~~
~~Also related: #9829~~

core,avm1,avm2: Stub 9-slice scaling (`scale9Grid`)

---

core/src/avm2/filters.rs
core/src/display_object.rs
render/src/backend.rs
render/src/bitmap.rs
render/src/filters.rs
render/src/pixel_bender.rs

There seems to be a lot of games that do `mc.filters = [....]` every single frame, so this should remove the performance penalty that brings.

core: Don't invalidate when setting filters to the same value

---

core/src/avm2/object/xml_object.rs
tests/tests/swfs/from_avmplus/e4x/Expressions/e11_2_2/test.toml

Previously, iterating the XML object would iterate the prototype. This broke filtering expressions on XML objects, which should work.

avm2: Support enumeration for XML objects

---

Cargo.lock
core/Cargo.toml
core/src/avm2/amf.rs
core/src/avm2/globals/flash/net/net_connection.rs
core/src/avm2/globals/flash/net/shared_object.rs
core/src/avm2/globals/flash/net/socket.rs
core/src/avm2/globals/flash/utils/byte_array.rs

This preserves object identity across a serialization round-trip. Unfortunately, we don't currently implement this correctly in flash_lso, so I've added a stub message.
Once flash_lso is fixed, this code will start working. For now, it just allows us to detect (via the stub) if this is actually used by an SWF.

avm2: Re-use same AMFValue for the same Object ptr

---

core/src/avm2/globals/flash/text/engine/text_block.rs
core/src/display_object/edit_text.rs

Fix some vertical cutoff by resizing the `EditText` in `text_block::create_text_line` instead of resizing it in `EditText::relayout`, and ensure that TLF `EditText`s are not selectable (previously they were stealing the focus).

avm2: Small TLF fixes

---

Cargo.lock

Both of these had yanked versions, and self_cell had a security advisory

chore: Update ahash and self_cell

---

core/src/avm2/activation.rs
tests/tests/swfs/from_avmplus/ecma3/Statements/eswitch_004/test.toml
tests/tests/swfs/from_avmplus/ecma3/Statements/ewhile_002/test.toml

If Actionscript explicitly sets the property to 'undefined', we should still succeed.

avm2: Use 'has_own_property' to check for prop in 'resolve_definition'

---

core/src/avm2/e4x.rs
core/src/avm2/multiname.rs
core/src/avm2/object/xml_object.rs
tests/tests/swfs/from_avmplus/e4x/Regress/regress-263935/test.toml

Avmplus constructs a full `QName`, and uses the normal Multiname matching logic. This would be a large refactor, so I've just modified the existing method to properly handle multiple namespaces.
I've also included a closely related fix - we should only treat a multiname with the literal local name "@foo" as an attribute when the namespace is the empty public namespace. We were incorrectly reparsing multinames that contained multiple namespaces.

avm2: Improve E4XNode::matches_name

---

core/src/avm2/globals/flash/events/MouseEvent.as

Slightly progresses #10173 after #14037. Without this PR but with #14037, the error that appears when clicking anywhere on the animation (which full-screens the content in Ruffle but not in browser Flash) is about writing to the read-only property isRelatedPropertyInaccessible. With this PR, it's instead TLF/FTE related.

avm2: Make MouseEvent isRelatedPropertyInaccessible a getter/setter

---

core/src/avm2/activation.rs
core/src/avm2/e4x.rs
core/src/avm2/globals/flash/display/movie_clip.rs
core/src/avm2/globals/flash/text/font.rs

Supersedes #13492.
Fixes #14041 and fixes #13490.

avm2: Add `Activation::caller_movie_or_root` to default to root movie

---

core/src/display_object.rs
core/src/display_object/movie_clip.rs

This ensures that a re-entrant 'construct_frame' call (e.g. due to a goto or AVM2 button) does not end up marking a MovieClip as initialized too early.
This issue was causing us to run 'fire_init_and_complete_events' too early, firing Loader events before we had actually finished (and before the SWF had registered the relevant listeners).

avm2: Mark MovieClip as initialized in 'on_construction_complete'

---

core/src/display_object/morph_shape.rs

The issue:
* Morphing is done by lerping control points between a start and end shape.
* Control points are specified in twips, so lerp_twips is used.
* Twips are integers.
* lerp_twips converts the start and end twips to floats, does its math, and converts them back to integers.
* When converting the lerped float back to an integer, it uses "float as i32"
* This performs round-towards-zero.
* So if, due to FP inaccuracy, the result was -6.9999999, this would round to -6, not -7, which is a whole twip out.
* Sometimes this could cause lerp_twips(x, x, ...) != x
* There are only 20 twips to a pixel so this error compounds fast in complex paths.
The fix:
Use `.round() as i32` instead of `as i32`.
Example failure case:
```rust
let ratio: u16 = 17246;
let b = f32::from(ratio) / 65535.0;
let a …
```

core: fix lerp_twips sometimes being off-by-one due to FP error

---

README.md

This PR edits the HTML of the badges at the top of the README.
Also, this now links to the Web Test GitHub Actions workflow page for that specific link.

README.md: Avoid _ showing between image links at the top of the document

---

desktop/src/backends/external_interface.rs
desktop/src/player.rs

From what I can tell this `ExternalInterface.call("window.location.href.toString")` is probably the most common usage of the ExternalInterace API, for example in #12054, #8330 and others that I can't remember. I re-used the already existing `--spoof-url` parameter for this.

desktop: Add window.location.href spoofing to the fake ExternalInterface

---

core/src/avm2/globals/flash/system/Security.as
core/src/avm2/globals/flash/system/security.rs
core/src/context.rs
core/src/player.rs
desktop/src/player.rs
web/src/lib.rs

Improves #14028. 
I don't have a good way to test real Flash in a browser, so it would be interesting to know what `Security.pageDomain` returns exactly. The documentation mentions `http://www.example.com` so without a trailing slash.

avm2: Implement flash.system.Security pageDomain

---

core/src/lib.rs
core/src/player.rs
desktop/src/cli.rs
desktop/src/player.rs

We've now had two different bug reports involving Adobe AIR SWFs, so I'm going to go ahead and start adding a framework for AIR support.
This commit just adds a command-line option
`--player-mode <flash-player|air>` (defaulting to `flash-player`), and passes it along to the `Player`. The actual value is currently unused - in a follow-up PR, I'm going to implement namespace versioning for AIR.

core: Add PlayerMode::{FlashPlayer, AIR} for Adobe AIR support

---

core/src/avm2/globals.rs
core/src/backend/audio.rs
core/src/backend/audio/mixer.rs
core/src/context.rs
core/src/display_object/movie_clip.rs
core/src/player.rs

Just a bit of preliminary work and miscellaneous audio-related cleanup.

core/audio: Preparations for `SampleDataEvent` work

---

core/src/avm2/globals/flash/display3D/textures/Texture.as

The caller might modify the ByteArray immediately after the call, so we need to copy the ByteArray.
Fixes https://github.com/ruffle-rs/ruffle/issues/13990

avm2: Copy data for async loadCompressedTextureFromByteArray

---

web/packages/core/src/ruffle-player.ts

This seems like it fixes #14133 and makes #8348 load (though the content doesn't work properly). Likely fixes other MooTools issues too, but many of the reported issues are to do with content which has since been removed (including #6065, #2567, and #2463).
#9517 is not fixed. It uses a newer version of MooTools which likely has different issues. #8619 is not fixed; it doesn't seem to use MooTools at all anymore but it requests mixed content without proper CORS headers on the HTTPS page and on the HTTP page the SWF files can't be read either for some reason.

web: Use CustomEvent instead of Event for load events so MooTools works

---

.github/workflows/release_nightly.yml
.github/workflows/test_web.yml
Cargo.lock
render/Cargo.toml
render/canvas/Cargo.toml
render/webgl/Cargo.toml
web/Cargo.toml
web/README.md
web/common/Cargo.toml
web/docker/Dockerfile

See: https://crates.io/crates/wasm-bindgen/0.2.88

chore: Bump wasm-bindgen to 0.2.89 (0.2.88 got yanked)

---

web/packages/extension/README.md

The current link shows this yellow banner in non-Chrome browsers, while Chrome redirects to the new URL.

docs: Link to the new Chrome Web Store from README.md

---

web/packages/extension/tools/sign_xpi.js

See for reference:
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-create
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-compatibility-examples
The minimum version is from: https://github.com/ruffle-rs/ruffle/wiki#web

web: Mark the Firefox extension as compatible with Android upon AMO submission

---

render/naga-agal/src/builder.rs

In indirect mode, We need to increment the indirect_offset value
to load subsequent matrix rows.

naga-agal: Fix using matrix opcodes with indirect source register

---

web/packages/core/src/shadow-template.ts

58px is the padding-top of the video-holder (20px) plus the padding-top plus padding-bottom of the modal-area (16px each) plus the border-top plus border-bottom of the modal-area (3px each). Noticed this issue on the no longer in use webpage https://bioservers.org/ddnalc/dna_today/index.html.

web: Don't let video modal overflow RufflePlayer

---

.github/workflows/test_extension_dockerfile.yml
web/docker/Dockerfile

After some experimentation in the wrong direction (thanks for the ideas anyway @Dinnerbone!), the solution was right here: https://github.com/torokati44/ruffle/actions/runs/7064760895/job/19233434777
That `${{ always() && github.repository == 'ruffle-rs/ruffle' }}` looks weird, but I _hope_ it does what I mean.

web: Fix the Firefox extension builder Dockerfile

---

core/src/avm2/activation.rs
tests/tests/swfs/from_avmplus/as3/Types/Int/wraparound/test.toml

This fixes the `from_avmplus/as3/Types/Int/wraparound` test in `debug` mode too.
In `release` mode it already passed "accidentally".

avm2: Use explicitly wrapping integer arithmetic operations

---

web/packages/extension/tools/sign_xpi.js

A follow-up for https://github.com/ruffle-rs/ruffle/pull/14233.
Reason: https://github.com/ruffle-rs/ruffle/actions/runs/7067394881/job/19240696121#step:7:200

web/extension: Raise minimum Firefox version on Android to 121

---

core/src/display_object.rs
core/src/display_object/container.rs

Fixes #9522 and fixes #10633. I'm pretty sure that this will also f​ix #9886 and #13876, but I haven't created test SWFs for those.
Logic is from [Toad06's branch](https://github.com/ruffle-rs/ruffle/compare/master...Toad06:ruffle:unload_test), mentioned in #10633.
When merged, #14276 should include enough test coverage.

avm1: Correctly mark unloaded movies as unloaded instead of relying on clip depth

---

web/packages/extension/tools/sign_xpi.js

This basically reverts https://github.com/ruffle-rs/ruffle/pull/14278.
As pointed out by @danielhjacobs, yesterday's AMO submission still returned an error: "Unknown min app version specified"
This is because:
> Once extensions are generally available on Android on December 14, 2023, AMO will update the compatible version number for extension currently set to 121.0a1 to 120.0 in order to make these extensions available on Stable.
> AMO is using version 121.0a1 to temporarily limit the extension to only be available to Firefox Nightly releases on Android. 
From: https://discourse.mozilla.org/t/min-browser-version-for-android-extension/125091/3
So, 120 _should_ work fine next week.

web/extension: Lower minimum Firefox version on Android to 120

---

Cargo.lock
desktop/Cargo.toml

When running current ruffle HEAD on Wayland, I get an error popup with the following contents:
> Ruffle has encountered a fatal error, this is a bug.
> 
> panicked at desktop/src/player.rs:147:22:
> Couldn't create ui backend: Couldn't get platform clipboard
> 
> Caused by:
>     Unknown error while interacting with the clipboard: Display parsing error
> 
> Please report this to us so that we can fix it. Thank you!
This appears to be caused by using the "arboard" crate without the feature flag required for its Wayland support: https://github.com/1Password/arboard/issues/98
This PR enables this feature and fixes the panic.

Fix panic on Wayland

---

desktop/src/backends/external_interface.rs

I noticed this pattern while looking at #14217, but the code can't be hit yet because the `loaderURL` causes an error before.

desktop: Also spoof top.location.href

---

Cargo.lock
Cargo.toml
core/Cargo.toml
desktop/Cargo.toml
desktop/src/gui/controller.rs
exporter/src/main.rs
render/naga-agal/src/builder.rs
render/naga-agal/src/varying.rs
render/naga-pixelbender/src/lib.rs
render/wgpu/src/backend.rs
render/wgpu/src/context3d/mod.rs
render/wgpu/src/filters/bevel.rs
render/wgpu/src/filters/blur.rs
render/wgpu/src/filters/color_matrix.rs
render/wgpu/src/filters/displacement_map.rs
render/wgpu/src/filters/glow.rs
render/wgpu/src/pixel_bender.rs
render/wgpu/src/surface.rs
render/wgpu/src/surface/target.rs
render/wgpu/src/utils.rs

~~Currently blocked by, and~~ mostly based on: https://github.com/emilk/egui/pull/3505
~~EDIT: This is now merged, waiting for a new release.~~
EDIT: egui 0.24 is now out.
~~Also blocked by https://github.com/bevyengine/naga_oil/pull/63, which is in turn, by https://github.com/gfx-rs/wgpu/issues/4569~~.
~~EDIT: The latter is now merged, also waiting for a new release.~~
~~EDIT: A backport of the  latter is in v0.18: https://github.com/gfx-rs/wgpu/pull/4693~~
EDIT: naga_oil 0.11.0 and wgpu-core 0.18.1 are now out with these fixes.
Feel free to force-push this branch if any of you continue working on this!

Update to wgpu 0.18, naga 0.14, naga_oil 0.11, egui 0.24.1

---

core/src/timer.rs

Now that we have `BinaryHeap::retain`, stable since Rust 1.70.
https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#method.retain

core: Clean up `Timers::remove`, remove `Timer::is_alive`

---

tests/tests/swfs/avm2/pixelbender_effect_BlurredFocus/test.toml
tests/tests/swfs/avm2/pixelbender_effect_glassDisplace_shaderfilter/test.toml
tests/tests/swfs/avm2/pixelbender_effect_smudge/test.toml
tests/tests/swfs/avm2/pixelbender_effect_tintype/test.toml
tests/tests/swfs/avm2/pixelbender_effect_twirl/test.toml
tests/tests/swfs/avm2/pixelbender_images/test.toml
tests/tests/swfs/avm2/pixelbender_shaderdata/test.toml
tests/tests/swfs/avm2/stage3d_agal_cross_product/test.toml
tests/tests/swfs/avm2/stage3d_bitmap/test.toml
tests/tests/swfs/avm2/stage3d_blend/test.toml
tests/tests/swfs/avm2/stage3d_errors/test.toml
tests/tests/swfs/avm2/stage3d_errors_swf_29/test.toml
tests/tests/swfs/avm2/stage3d_fractal/test.toml
tests/tests/swfs/avm2/stage3d_rotating_cube/test.toml
tests/tests/swfs/avm2/stage3d_sampler/test.toml
tests/tests/swfs/avm2/stage3d_texture/test.toml
tests/tests/swfs/avm2/stage3d_texture_bytearray/test.toml
tests/tests/swfs/avm2/stage3d_texture_bytearray_compressed_alpha/test.toml
tests/tests/swfs/avm2/stage3d_texture_bytearray_compressed_raw_alpha/test.toml
tests/tests/swfs/avm2/stage3d_triangle/test.toml
tests/tests/swfs/avm2/stage3d_triangle_bytes4/test.toml
tests/tests/swfs/avm2/stage3d_triangle_float1/test.toml
tests/tests/swfs/avm2/stage3d_triangle_index_upload/test.toml
tests/tests/swfs/stage3d/sampler_odd_size/test.toml
tests/tests/swfs/stage3d/scissor_rectangle/test.toml
tests/tests/swfs/stage3d/scissor_rectangle_invalid/test.toml

As they are a prime suspects for causing hangs on CI.

tests/avm2: Exclude PixelBender and Scene3D visual tests on WARP

---

web/packages/core/package.json

While `npm test` in `web` works on CI, for some reason, on my local machine, I get this error:
`✖ ERROR: SyntaxError: Unexpected token 'v', "verbatimModuleSyntax" is not valid JSON`
Perhaps the `,` in that string confuses something. With this patch, I can test the `core` package successfully.
The removed option looks like a backward compatibility thing, that we're only trying to disable, but this _(leans on Chesterton's fence)_ doesn't seem necessary (anymore), and maybe it's not even enabled by default.

web: Simplify the `TS_NODE_COMPILER_OPTIONS` value for mocha in core test

---

core/src/avm2/object/array_object.rs
tests/tests/swfs/from_avmplus/ecma3/Array/e15_4_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/Array/e15_4_1_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/Array/e15_4_1_3/test.toml
tests/tests/swfs/from_avmplus/ecma3/Array/e15_4_2_1_1/test.toml
tests/tests/swfs/from_avmplus/ecma3/Array/e15_4_2_1_3/test.toml
tests/tests/swfs/from_avmplus/ecma3/Array/e15_4_2_3/test.toml
tests/tests/swfs/from_avmplus/ecma3/Expressions/e11_1_4/test.toml

This was causing the `Object.prototype.toString` to throw error 1050, instead of returning `[object Array]`, which was causing quite a few avmplus test failures.

avm2: Remove ArrayObject `to_string` impl

---

web/packages/extension/tools/sign_xpi.js

The version numbers must strictly equal one of those in these lists:
- https://addons.mozilla.org/api/v5/applications/firefox/
- https://addons.mozilla.org/api/v5/applications/android/

web/extension: Correct the version used for the Firefox extension

---

core/src/avm2/globals/flash/net/SharedObject.as
core/src/avm2/globals/flash/net/shared_object.rs

This PR adds the missing property `objectEncoding` to `SharedObject`, which fixes #14414.

avm2: Add missing property objectEncoding to SharedObject

---

swf/src/avm2/write.rs

This adds a test for `swf::avm2::write::Writer::write_op`, and makes it public, since it was private and unused before, and I myself will want to write ops in the future in order to patch the bytecode of SWF files.
The test is admittedly not all-encompassing (mainly in terms of explicitly testing that `write_u30` is used, since I don't use any values that would result in `write_u30` writing more than one byte), but there is an assert for every `Op` variant, and it was written without looking at the implementation of `write_op`, only at `Reader::read_op`.
I did consider changing the implementation of `write_op` by adding an `Op::opcode` method that would be used in `write_op` at the start to write the opcode, and then after would match on the op and write the extra data if applicable, but …

swf: Make avm2 Writer::write_op public

---

core/src/font.rs

Since font ascent and descent values in the SWF tag are unsigned, we need a 32-bit value to store them as signed.
Fixes #14434.

core: Use i32 for font ascent and descent

---

Cargo.lock
Cargo.toml

This is the part of https://github.com/ruffle-rs/ruffle/pull/14442 that we can do easily.
The `cargo update` was necessary to not duplicate `naga`.
Note that this also bumps `wgpu` to the `HEAD` of the `v0.18` branch.

chore: Update naga to 0.14.2, run `cargo update`

---

core/src/avm2/globals/flash/net/LocalConnection.as
core/src/avm2/globals/flash/net/local_connection.rs
core/src/avm2/object.rs
core/src/avm2/object/local_connection_object.rs
core/src/context.rs
core/src/lib.rs
core/src/local_connection.rs
core/src/player.rs

This is an initial implementation of `LocalConnection` that only considers connections local to the specific SWF file. It adds a `LocalConnections` struct to `UpdateContext`, and implements the `LocalConnection` APIs for AVM2.
I also changed `LocalConnection.send` to not immediately fire the `status` event, to match Flash. #12604 is _technically_ fixed by this, but I would like to leave the issue open until AVM1/mixed AVM `LocalConnection` works (since that's what the SWF really needs).

avm2/core: Partially implement `LocalConnection`

---

core/src/lib.rs
core/src/streams.rs
render/wgpu/src/lib.rs

Stop allowing previously buggy lint `clippy::extra_unused_type_parameters` - the corresponding Clippy issue (https://github.com/rust-lang/rust-clippy/issues/10318) was fixed long ago.
Stop allowing, and fix lint `clippy::explicit_auto_deref`.

chore: Remove obsolete lint allows
